### ISSUE TITLE
Patroni stucks if postgres port is blocked

### ISSUE THREAD

**Issue by chobostar** [zalando/patroni#1040]
I'm just trying out a patroni and testing some failure scenarios.

If I block Postgres ports like this:
```
iptables -I INPUT -p tcp -m multiport --dport 5432,6432 -j REJECT
```
local patroni do nothing. Postgres continues working and WAL archiving.

Also, patroni doesn't respond to any REST API calls:
```
$ curl  192.168.0.1:8008/patroni
```
and there are no any log output

Looks like `use_unix_socket` may help me, but it's strange for me because I expected some fencing/demoting Postgres. 

--------------------
* Debian Linux
* Patroni 1.5.5
* PostgreSQL 9.6.12
* Consul v1.4.2

postgres0.yml
```
--- 
  scope: patroni-test
  namespace: /service/patroni/
  name: patroni-test01
  restapi: 
    listen: "0.0.0.0:8008"
    connect_address: "192.168.0.1:8008"
  consul: 
    host: "127.0.0.1:8500"
  log: 
    dir: /var/log/
  bootstrap: 
    dcs: 
      ttl: "30"
      loop_wait: "10"
      retry_timeout: "10"
      maximum_lag_on_failover: "167772160"
      postgresql: 
        use_pg_rewind: true
        parameters: 
          lc_messages: C
    initdb: 
      - encoding: UTF-8
      - data-checksums
    pg_hba: 
      - "host all all 192.0.0.0/8 md5"
      - "host replication patroni 192.168.0.1/32 trust"
      - "host all all 192.168.0.1/32 trust"
      - "host replication patroni 192.168.0.2/32 trust"
      - "host all all 192.168.0.2/32 trust"
      - "host replication patroni 192.168.0.3/32 trust"
      - "host all all 192.168.0.3/32 trust"
  postgresql: 
    listen: "0.0.0.0:5432"
    connect_address: "192.168.0.1:5432"
    data_dir: /var/lib/postgresql/9.6/patroni-test
    config_dir: /etc/postgresql/9.6/patroni-test
    bin_dir: /usr/lib/postgresql/9.6/bin/
    pgpass: /var/lib/postgresql/.pgpass
    authentication: 
      replication: 
        username: patroni
        password: "patroni"
      superuser: 
        username: patroni
        password: "patroni"
    parameters: 
      unix_socket_directories: /var/run/postgresql
    pg_hba: 
      - "host    all             all             127.0.0.1/32            trust"
      - "local   all             all                                     trust"
      - "local   replication     all                                     trust"
      - "host    replication     all             127.0.0.1/32            trust"
      - "host all all 192.0.0.0/8 md5"
      - "host replication patroni 192.168.0.1/32 trust"
      - "host all all 192.168.0.1/32 trust"
      - "host replication patroni 192.168.0.2/32 trust"
      - "host all all 192.168.0.2/32 trust"
      - "host replication patroni 192.168.0.3/32 trust"
      - "host all all 192.168.0.3/32 trust"
    use_pg_rewind: true
    remove_data_directory_on_rewind_failure: true
    remove_data_directory_on_diverged_timelines: true
  tags: 
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```
