### ISSUE TITLE
entrypoint.sh: 35: exec: /usr/share/zookeeper/bin/zkServer.sh: not found

### ISSUE THREAD

**Issue by vitassecuriti** [zalando/patroni#1044]
I tooke repository and builded Docker image.

I tryed run container with zookeper from patroni image but i catch exception

```
demo-patroni1 | 2019-04-19 12:13:59,309 INFO: Connecting to zookeeper1:2181
demo-patroni1 | 2019-04-19 12:13:59,406 WARNING: Connection dropped: socket connection error: Temporary failure in name resolution
zookeeper1    | /entrypoint.sh: 35: exec: /usr/share/zookeeper/bin/zkServer.sh: not found
```

May be i not understood that line mean in entrypoint.sh

```
    zookeeper)
        exec /usr/share/zookeeper/bin/zkServer.sh start-foreground
        ;;
```

In docker-compose.yml i set section for zookeper's service
```
    zookeeper1:
        image: patroni
        networks: [ patroni ]
        hostname: zookeeper1
        container_name: zookeeper1
        command: zookeeper
```
I checked inside the container and not found /usr/share/zookeeper with dept
Can you give any examle? For what this check of with of $1 == zookeeper?
