### ISSUE TITLE
Patroni throwing exception when attempting to connect to zookeeper

### ISSUE THREAD

**Issue by vitassecuriti** [zalando/patroni#1047]
I try to create two containers (Docker) of patroni on remote hosts.

1st on host server1
```
version: "3"
services:
    patroni_server1:
        image: patroni:1.5.6
        hostname: patroni_server1
        container_name: patroni_server1
        ports:
            - 8008:8008
            - 5432:5432
        environment:
            PATRONI_NAME: patroni_server1
            PATRONI_SCOPE: patroni_test
            PATRONI_ZOOKEEPER_HOSTS: 'server1:2181','server2:2181'
            PATRONI_RESTAPI_USERNAME: admin
            PATRONI_RESTAPI_PASSWORD: admin
            PATRONI_RESTAPI_CONNECT_ADDRESS: server1:8008
            PATRONI_RESTAPI_LISTEN: "server1:8008,server2:8008"
            PATRONI_POSTGRESQL_CONNECT_ADDRESS: server1:5432
            PATRONI_POSTGRESQL_LISTEN: "server1:5432,server2:5432"
            PATRONI_SUPERUSER_USERNAME: postgres
            PATRONI_SUPERUSER_PASSWORD: postgres
            PATRONI_REPLICATION_USERNAME: replicator
            PATRONI_REPLICATION_PASSWORD: replicate
            PATRONI_admin_PASSWORD: admin
            PATRONI_admin_OPTIONS: createdb,createrole
```
2nd on host server2

```
version: "3"
services:
    patroni_server2:
        image: patroni:1.5.6_2
        hostname: patroni_server2
        container_name: patroni_server2
        ports:
            - 8008:8008
            - 5432:5432
        environment:
            PATRONI_NAME: patroni_server2
            PATRONI_SCOPE: patroni_test
            PATRONI_ZOOKEEPER_HOSTS: 'server1:2181','server2:2181'
            PATRONI_RESTAPI_USERNAME: admin
            PATRONI_RESTAPI_PASSWORD: admin
            PATRONI_RESTAPI_CONNECT_ADDRESS: server2:8008
            PATRONI_RESTAPI_LISTEN: "server1:8008,server2:8008"
            PATRONI_POSTGRESQL_CONNECT_ADDRESS: server2:5432
            PATRONI_POSTGRESQL_LISTEN: "server1:5432,server2:5432"
            PATRONI_SUPERUSER_USERNAME: postgres
            PATRONI_SUPERUSER_PASSWORD: postgres
            PATRONI_REPLICATION_USERNAME: replicator
            PATRONI_REPLICATION_PASSWORD: replicate
            PATRONI_admin_PASSWORD: admin
            PATRONI_admin_OPTIONS: createdb,createrole
```
Patroni need zookeeper.  I create two containers zookeper on remote hosts in one cluster.

1st on host server1

```
version: "3"
services:
   zookeeper_server1:
      image: jplock/zookeeper:3.4.6
      container_name: zookeeper_server1
      ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      environment:
        ZOO_PORT: "2181"
        ZOO_MY_ID: 1
        ZOO_SERVERS: "server.1=server1:2888:3888 server.2=server2:2888:3888"
      volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
```
2nd on host server2
```
version: "3"
services:
   zookeeper_server2:
      image: jplock/zookeeper:3.4.6
      container_name: zookeeper_server2
      ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      environment:
        ZOO_PORT: "2181"
        ZOO_MY_ID: 2
        ZOO_SERVERS: "server.1=server1:2888:3888 server.2=server2:2888:3888"
      volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
```
After I start zookeeper on remote hosts. 
After I start patroni on remote hosts. 

In logs patroni i see that both node works (1st leader 2nd secondary). In logs zookeepers i see that from patroni get requests. Later, I stop the container zookeeper with which patroni worked and i see error in the logs both patroni's node

```
patroni_server2 | 2019-04-23 15:00:12,666 INFO: Connecting to server1:2181
patroni_server2 | 2019-04-23 15:00:12,674 WARNING: Connection dropped: socket connection broken
patroni_server2 | 2019-04-23 15:00:12,674 INFO: Connecting to server2:2181
patroni_server2 | 2019-04-23 15:00:12,682 WARNING: Connection dropped: socket connection broken
patroni_server2 | 2019-04-23 15:00:13,083 ERROR: get_cluster
patroni_server2 | Traceback (most recent call last):
patroni_server2 |   File "/usr/lib/python3/dist-packages/kazoo/retry.py", line 123, in __call__
patroni_server2 |     return func(*args, **kwargs)
patroni_server2 |   File "/patroni/dcs/zookeeper.py", line 166, in _inner_load_cluster
patroni_server2 |     nodes = set(self.get_children(self.client_path(''), self.cluster_watcher))
patroni_server2 |   File "/patroni/dcs/zookeeper.py", line 150, in get_children
patroni_server2 |     return self._client.get_children(key, watch)
patroni_server2 |   File "/usr/lib/python3/dist-packages/kazoo/client.py", line 1079, in get_children
patroni_server2 |     return self.get_children_async(path, watch, include_data).get()
patroni_server2 |   File "/usr/lib/python3/dist-packages/kazoo/handlers/utils.py", line 72, in get
patroni_server2 |     raise self._exception
patroni_server2 | kazoo.exceptions.SessionExpiredError
patroni_server2 | patroni_server2 | During handling of the above exception, another exception occurred:
patroni_server2 | patroni_server2 | Traceback (most recent call last):
patroni_server2 |   File "/patroni/dcs/zookeeper.py", line 219, in _load_cluster
patroni_server2 |     cluster = self._client.retry(self._inner_load_cluster)
patroni_server2 |   File "/usr/lib/python3/dist-packages/kazoo/client.py", line 273, in _retry
patroni_server2 |     return self._retry.copy()(*args, **kwargs)
patroni_server2 |   File "/usr/lib/python3/dist-packages/kazoo/retry.py", line 136, in __call__
patroni_server2 |     raise RetryFailedError("Exceeded retry deadline")
patroni_server2 | kazoo.retry.RetryFailedError: Exceeded retry deadline
patroni_server2 | 2019-04-23 15:00:13,083 ERROR: Error communicating with DCS
patroni_server2 | 2019-04-23 15:00:13,084 INFO: DCS is not accessible
```
