### ISSUE TITLE
Why the huge_page can't be closed?

### ISSUE THREAD

**Issue by henrywangx** [zalando/patroni#1051]
I tried to close the huge_page.:

```yaml
bootstrap:
  dcs:
    ttl: 20
    loop_wait: 2
    retry_timeout: 9
  initdb:
  - auth-host: md5
  - auth-local: trust
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums
  pg_hba:
  - host all all 0.0.0.0/0 md5
  - host replication ${PATRONI_REPLICATION_USERNAME} ${POD_IP}/16 md5
restapi:
  connect_address: '${POD_IP}:8008'
postgresql:
  use_pg_rewind: true
  parameters:
    shared_preload_libraries: "timescaledb"
    synchronous_commit: "off"
    max_connections: "300"
    shared_buffers: "256MB"
    effective_cache_size: "768MB"
    huge_pages: "off"
```

But it looks didn't change the conf in docker:

```yaml
 cat postgresql.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
include 'postgresql.base.conf'

cluster_name = 'timescaledb'
effective_cache_size = '768MB'
hot_standby = 'on'
listen_addresses = '0.0.0.0'
max_connections = '300'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '10'
max_worker_processes = '8'
port = '5432'
shared_buffers = '256MB'
shared_preload_libraries = 'timescaledb'
synchronous_commit = 'off'
track_commit_timestamp = 'off'
wal_keep_segments = '8'
wal_level = 'replica'
wal_log_hints = 'on'
hba_file = '/home/postgres/pgdata/pgroot/data/pg_hba.conf'
ident_file = '/home/postgres/pgdata/pgroot/data/pg_ident.conf'
```
