### ISSUE TITLE
headless services should include ownerReferences

### ISSUE THREAD

**Issue by stang** [zalando/patroni#1055]
Since headless services were introduced in https://github.com/zalando/patroni/pull/958, those need to be cleaned after a cluster is deleted.

We could argue that whoever manage the patroni clusters (eg: `postgres-operator`) should take care of that, as they already do with the `endpoint config` but semantically: as the only reason they're here is to avoid the deletion of the `endpoint`, these new _headless services_ should have a [`.metadata.ownerReferences`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#ownerreference-v1-meta) set so they're automatically cleaned by kubernetes when the associated `endpoint` are deleted.

**Note:** we're running `kubernetes (api-server) v1.12.7` and `endpoints` don't seem to be deleted even without any `Service` associated (as it was already the case AFAIK).
Did the behavior change in a recent release, or is it configurable somewhere? In which case, would it make sense to make [`_should_create_config_service`](https://github.com/zalando/patroni/blob/bba9066315f8dda23e0a28909790a5a3d48d1842/patroni/dcs/kubernetes.py#L287) configurable?

cc @CyberDem0n

**Comment by CyberDem0n** [comment]
I would better prefer if the postgres-operator creates/drops a headless service.

> we're running kubernetes (api-server) v1.12.7 and endpoints don't seem to be deleted even without any Service associated (as it was already the case AFAIK).

Have you tried to rotate/replace/upgrade k8s master nodes?

**Comment by stang** [comment]
Thanks @CyberDem0n - see my answers inline.

> I would better prefer if the postgres-operator creates/drops a headless service.

Out of curiosity, is there a specific reason not to use the `ownerReferences`?

I'll be happy to open a new issue and raise a PR in the `postgres-operator` repository once we gather all the relevant information.

> Have you tried to rotate/replace/upgrade k8s master nodes?

I just tested with kubernetes `1.14.1` and it seem fine to have `Endpoints` without corresponding `Service`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

The `Endpoints` is there, without any `Service`. Can you confirm? That might mean that the headless service are no longer needed?

```
$ kubectl get svc,ep
NAME                     ENDPOINTS   AGE
endpoints/stang-foobar   <none>      13m
```

And here is the manifest I used for the test:
```yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    config: '{"loop_wait":10,"maximum_lag_on_failover":33554432,"postgresql":{"parameters":{"archive_mode":"on","archive_timeout":"1800s","autovacuum_analyze_scale_factor":0.02,"autovacuum_max_workers":5,"autovacuum_vacuum_scale_factor":0.05,"checkpoint_completion_target":0.9,"hot_standby":"on","log_autovacuum_min_duration":0,"log_checkpoints":"on","log_connections":"on","log_disconnections":"on","log_line_prefix":"%t
      [%p]: [%l-1] %c %x %d %u %a %h ","log_lock_waits":"on","log_min_duration_statement":500,"log_statement":"ddl","log_temp_files":0,"max_connections":"15","max_replication_slots":5,"max_wal_senders":5,"tcp_keepalives_idle":900,"tcp_keepalives_interval":100,"track_functions":"all","wal_keep_segments":8,"wal_level":"hot_standby","wal_log_hints":"on"},"use_pg_rewind":true,"use_slots":true},"retry_timeout":10,"ttl":30,"initdb":{"data-checksums":"true","encoding":"UTF8","locale":"en_US.UTF-8"},"pg_hba":["hostssl
      all all 0.0.0.0/0 md5","host    all all 0.0.0.0/0 md5"]}'
  labels:
    application: spilo
    cluster-name: stang-foobar
  name: stang-foobar

```
