### ISSUE TITLE
Patroni implementation in present cluster PostgreSQL with zero-downtime

### ISSUE THREAD

**Issue by Valeriyy** [zalando/patroni#1067]
Hello!
I want to implement Patroni in a working cluster PostgreSQL.
Workflow is clear to me. I stop the slave and after run it under the control of Patroni.
But in terms of configuration, I don't understand how to make it follow the current master that is not yet managed by Patroni.
As far as I understand, I can run a backup cluster https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#standby-cluster
```
I add settings:
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: false
      parameters:
        max_connections: 1000
        max_wal_senders: 15
        wal_keep_segments: 512
    standby_cluster:
      host: pg1
      port: 5432
```
restart Patroni and nothing happens
Tell me worflow and configuration of Patroni to achieve the desired result
