### ISSUE TITLE
patronictl -k is working, "ctl.insecure" not

### ISSUE THREAD

**Issue by Wolfsrudel** [zalando/patroni#1085]
I'm using self signed certificates for the rest api and with the "-k" option patronictl is working. With the "ctl.insecure" option in the yaml configuration, it is not working.

```
restapi:
  listen: <my_ip>:8008
  connect_address: <my_ip>8008
  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
  authentication:
    username: patroni
    password: patroni

ctl:
  insecure: true
```

I think I'm just understading the documentation wrong.
