### ISSUE TITLE
Question: patroni is deleting the default replication slot it created

### ISSUE THREAD

**Issue by RajKiranS** [zalando/patroni#1105]
Hello,

As per my understanding of replication_slots implementation in patroni, once we enable 'use_slots' parameter in the DCS, patroni takes care of creating a replication_slot of type 'physical' by default for a slave using its instance name. That's great and as expected.

But, as soon as the slave goes offline (the node is shutdown or patroni process is killed), the replication_slot is removed in 30 seconds. Why is the slot removed here? Is that expected? If so, then what is the use of replication_slot.

Here is my config in DCS;
```
loop_wait: 10
master_start_timeout: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    hot_standby: true
    max_connections: 300
    max_wal_senders: 5
    wal_keep_segments: 10
    wal_level: hot_standby
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
ttl: 30
``` 
I have a two node cluster. Please pardon if I have got something wrong here. Thanks in advance.
