### ISSUE TITLE
Replication is not working in patroni.

### ISSUE THREAD

**Issue by Tekchanddagar** [zalando/patroni#1108]
Hello Team,

Currently we are using master and slave in our postgresql with streaming replication. But now we need DR and HA. So we are decided to go with patroni. As per my knowledge patroni provide itself replication as well as HA (Automatic failover). We have setup patroni with 2 postgres+patroni, 1 etcd and 1 haproxy machine.

Now when i am shutdown master then slave become master and its reflecting over haproxy dashboard. But replication is not working.

Below is my `patroni.yml` file:

```
scope: postgres
namespace: /db/
name: master1

restapi:
    listen: 192.168.56.8:8008
    connect_address: 192.168.56.8:8008

etcd:
    host: 192.168.56.7:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:
             wal_level: replica
             hot_standby: "on"
             wal_keep_segments: 8
             max_wal_senders: 5
             max_replication_slots: 5
             checkpoint_timeout: 3

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 192.168.56.8/0 md5
    - host replication replicator 192.168.56.9/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 192.168.56.8:5432
    connect_address: 192.168.56.8:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: password
        superuser:
            username: postgres
            password: password
    parameters:
        unix_socket_directories: '.'
#tags:
#    nofailover: false
#    noloadbalance: false
#    clonefrom: false
#    nosync: false
```
Is my `patroni.yml` file configuration is fine?

i have followed the below link:

[https://www.alibabacloud.com/blog/how-to-set-up-a-highly-available-postgresql-cluster-using-patroni-on-ubuntu-16-04_594477](url)
Can you please help me to fix the issue of replication? Any assitance will be appreciated. Its become roadblock in my project.

Thanks in advance.

**Comment by Tekchanddagar** [comment]
This problem is resolved. Thanks.

**Comment by kozlou** [comment]
Hey dude, how did u fixed this?

**Comment by doruksonmez** [comment]
Yeah, exactly @Tekchanddagar; can you please tell how did you fix it?

Do you have any update on this @kozlou?

**Comment by kozlou** [comment]
Yeah hello, i'm sorry that I didn't updated this before. The replication is not working because of split brain problem. All what you need to fix it is just setup a **3-node cluster** (1 postgresql + 1 patroni for a node), then setup a 3 etcd nodes cluster (can be 1 etcd if it's not a production enviroment) and provide a single endpoint for a cluster (in my case this is HAproxy). Good luck!

**Comment by doruksonmez** [comment]
Thank you, @kozlou. I already have 2x HAproxy in front of 2x Postgres+Patroni and 1x Etcd instance (this can be 3 Etcd if that is how it should be for a production environment). So now I am going to add 3rd Postgresql 10 + patroni instance with the same config files (of course with appropriate IP addresses) to my cluster and then it should replicate without problem right?

I've also seen this thread https://github.com/zalando/patroni/issues/1012 and he says you should remove the main postgre10 cluster. But I wonder if my data_dir parameter should remains as **data_dir: /data/patroni/** or should I set it to **/var/lib/postgresql/10/main/**.

Is this **authentication** part should be done by patroni itself or do I have to create those users manually?
```
 authentication:
  replication:
   username: replicador
   password: pass1
  superuser:
   username: postgres
   password: pass2
```

Thank you.
