### ISSUE TITLE
admin user cannot log in after restart

### ISSUE THREAD

**Issue by mattymo** [zalando/patroni#1110]
spilo version: 1.4-p16

How to reproduce: 
1. deploy incubator/patroni chart with k8s DCS, one replica, and persistent storage
2. psql -U admin patroni.default postgres (works)
3. kubectl delete pod patroni-0
4. psql -U admin patroni.default postgres

Expected result: works
Actual result: 
psql: FATAL:  role "admin" is not permitted to log in

I can work around this by adding the following env vars to my statefulset:
```
        # Work around admin user losing login. Make admin2 user to have login permission
        - name: PATRONI_admin2_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "patroni.fullname" . }}
              key: password-admin
        - name: PATRONI_admin2_OPTIONS
          value: "createrole,createdb,login"
```
More information:
```
# psql -U admin2 -h patroni.default postgres 
Password for user admin2: 
psql (9.2.24, server 10.5 (Ubuntu 10.5-1.pgdg18.04+1))
WARNING: psql version 9.2, server version 10.0.
         Some psql features might not work.
SSL connection (cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256)
Type "help" for help.

postgres=> \du
                                                            List of roles
      Role name       |                   Attributes                   |                          Member of                           
----------------------+------------------------------------------------+--------------------------------------------------------------
 admin                | Create DB, Cannot login                        | {}
 admin2               | Create role, Create DB                         | {}
```
