### ISSUE TITLE
How we can use patroni with existing postgresql setup.

### ISSUE THREAD

**Issue by Tekchanddagar** [zalando/patroni#1111]
Hello Team,

Currently we are using postgresql with master and slave configuration. But now we want to use Patroni for HA with existing database. 

We have tested patroni in our testing environment and its working as per our expectation. 

But now we want to use it in production but we want to use our existing database setup which have huge data. 

Can you please help me how we can use the existing database with patroni?

As per my knowledge by default postgresl store the data in `/var/lib/postgresql/psql_version/main` directory.

We need to define the data directory in `patroni.yml` also where it keep all the configuration file.

Please help me how we can pass our existing database data to patroni so it can use that data?

Any assistance will be helpful. 
Thanks.

**Comment by kostiantyn-nemchenko** [comment]
Hi @Tekchanddagar ,
Please, take a look at #1067

**Comment by Tekchanddagar** [comment]
Hi @kostiantyn-nemchenko ,

Thank you for your response.

I have read the documents which are provided by you in that link.

But still i am finding the answer of my few question:

1. We are in testing phase and we also got the error `patroni fails to run because it cannot bind to the postgresql port.` because we have only single IP on our system which is used for replication between master and slave. What IP we need to define in `patroni.yml` file for `postgres listen address`?

2. Where we need to define our existing data directory so patroni can use it?

Thanks.

**Comment by kostiantyn-nemchenko** [comment]
1) `postgresql.listen`  key in `patroni.yml` should contain the IP address(es) + port on which the server is to listen for connections from client applications and other members in the cluster.
2) Put the location of your data directory into `postgresql.data_dir` in `patroni.yml`.

**Comment by Tekchanddagar** [comment]
Hi @kostiantyn-nemchenko ,

Thank you for your response.

As per my understanding, We have single IP over our system which is in use for streaming replication between master and slave. So first we need to stop postgresql service over both the system then we can use same IP in `patroni.yml` configuration.

2. i am confused how we will define the existing data directory. As shown below is correct way?

`/var/lib/postgresql/10/main/` is my existing data directory
```
postgresql:
    listen: 192.168.56.9:5432
    connect_address: 192.168.56.9:5432
    data_dir: /var/lib/postgresql/10/main/
```

Thanks.

**Comment by Tekchanddagar** [comment]
Hello @kostiantyn-nemchenko ,

I have replaced the `data_dir` with my existing data directory in `patroni.yml` file. Existing data directory means which is used by postgresql master and have all the old data.

Below is my current configuration of `patroni.yml` file:

```
scope: postgres
namespace: /db/
name: master1

restapi:
    listen: 192.168.56.19:8008
    connect_address: 192.168.56.19:8008

etcd:
    host: 192.168.56.7:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 192.168.56.9/0 md5
    - host replication replicator 192.168.56.19/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 192.168.56.19:5432
    connect_address: 192.168.56.19:5432
    data_dir: /var/lib/postgresql/9.5/main
    bin_dir: /usr/lib/postgresql/9.5/bin/
    config_dir: /etc/postgresql/9.5/main
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: password
        superuser:
            username: postgres
            password: password
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```
But i am getting below error when i am restarting patroni service using the command
`systemctl start patroni.service`

Error:

```
Jul 19 12:28:23 master1 patroni[2808]: 2019-07-19 12:28:23,736 CRITICAL: system ID mismatch, node master1 belongs to a different cluster: 6713836407329394798 != 6714158803621989816
```

Please help me how we can fix this issue and can take the advantage of patroni for HA.

Thanks.
