### ISSUE TITLE
Patroni API becomes unresponsive (timeout) for two clusters at the same time

### ISSUE THREAD

**Issue by jpuris** [zalando/patroni#1127]
**Some details on environment**
- Patroni version 1.5.6
- Patroni uses 5 node etcd cluster

**Problem**
We are running multiple clusters and API requests started to timeout on all nodes across 2 clusters seperate. All clusters are using the same etcd cluster.

This is happening for the third time now and happens roughly at 1-3 weeks interval.

**Recovery**
Restart patroni service on all nodes in all effected clusters.

**etcd state during incident**
All seems to be in order and all monitored metrics are normal. Logs are also clean.

**Whats working during incident**
- patronictl list
- postgresql nodes and replication
- patroni logs show absolutely no problems

**Whats not working during incident**
- patroni API is unresponsive
- patronictl switchover command times out and needs to be cancelled
```
Are you sure you want to switchover cluster my_cluster, demoting current master my_master_node? [y/N]: y
^C
Aborted!
```

One of the affected clusters had been recovered with the described recovery method, however the other (dev) cluster patroni API's are still in limbo.

Patroni config file from one of the nodes.
```yml
scope: <redacted>
name: node-1

watchdog:
    mode: off

restapi:
    listen: 0.0.0.0:8008
    connect_address: <redacted>:8008
    certfile: /etc/postgresql/ssl/self-signed-node-1.pem
    keyfile: /etc/postgresql/ssl/self-signed-node-1-key.pem
    cacert: /etc/postgresql/ssl/self-signed-ca.pem

etcd:
    hosts: <redacted>:2379,<redacted>:2379,<redacted>:2379,<redacted>:2379,<redacted>:2379
    protocol: https
    cacert: /etc/postgresql/ssl/self-signed-ca.pem
    cert: /etc/postgresql/ssl/self-signed-node-1.pem
    key: /etc/postgresql/ssl/self-signed-node-1-key.pem

bootstrap:
    dcs:
        ttl: 43200
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    pg_ident:
    - auth_map postgres postgres
    - auth_map <redacted> <redacted>

    pg_hba:
    # LOCAL
    - local all all ident map=auth_map
    # REPLICATION
    - hostssl replication repl_user 127.0.0.1/32 md5
    - hostssl replication repl_user <redacted>/32 md5
    - hostssl replication repl_user <redacted>/32 md5
    - hostssl replication repl_user <redacted>/32 md5
    - hostssl replication repl_user <redacted>/32 md5
    - hostssl replication repl_user <redacted>/32 md5
    # CLIENTS
    - hostssl all all 127.0.0.1/32 md5
    - hostssl all all <redacted>/24 md5
    - hostssl all all <redacted>/24 md5
    - hostssl all all <redacted>/24 md5
    - hostssl all all <redacted>/24 md5
    # GCP load balancers
    - hostssl all all <redacted>/32 md5
    - hostssl all all <redacted>/32 md5

postgresql:
    listen: 127.0.0.1,<redacted>,<redacted>
    connect_address: <some_ip>
    data_dir: /data/db/data
    bin_dir: /usr/lib/postgresql/9.4/bin/
    use_slots: true
    custom_conf: /etc/postgresql/postgresql.base.conf
    authentication:
        replication:
            username: repl_user
            password: <redacted>
        superuser:
            username: patroni
            password: <redacted>
    parameters:
        unix_socket_directories: '.,/var/run/postgresql/'
        archive_mode: "on"
        archive_timeout: "1800s"
        archive_command: "pgbackrest --stanza=<redacted> archive-push %p && pgbackrest --stanza=<redacted> archive-push %p"
        max_wal_senders: 10
    recovery_conf:
        restore_command: "pgbackrest --stanza=<redacted> archive-get %f %p"

    pg_ident:
    - auth_map <redacted> postgres
    - auth_map <redacted> <redacted>

    pg_hba:
    # LOCAL
    - local all all ident map=auth_map
    # REPLICATION
    - hostssl replication repl_user 127.0.0.1/32 md5
    - hostssl replication repl_user <redacted>/32 md5
    - hostssl replication repl_user <redacted>/32 md5
    - hostssl replication repl_user <redacted>/32 md5
    - hostssl replication repl_user <redacted>/32 md5
    - hostssl replication repl_user <redacted>/32 md5
    # CLIENTS
    - hostssl all all 127.0.0.1/32 md5
    - hostssl all all <redacted>/24 md5
    - hostssl all all <redacted>/24 md5
    - hostssl all all <redacted>/24 md5
    - hostssl all all <redacted>/24 md5
    # GCP load balancers
    - hostssl all all <redacted>/32 md5
    - hostssl all all <redacted>/32 md5
```

Another note is both failed clusters are spanning accross 2 regions.
_Topology_
**Region X**
- 3 nodes per cluster
- etcd cluster

**Region Y**
- 2 nodes per cluster, no failover is set to true in patroni
- talks to etcd in region X

This is especially problematic, because we rely on Patroni API to detect which one is primary and which one is replica. This is done with HAProxy.
