### ISSUE TITLE
Patroni is not reflecting the updated parameters from postgresql.conf file

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [zalando/patroni#1166]
Hey, I want to make all the config changes via conf file only. I don't want to use `edit-config` from ctl. Here is my `patroni.yml` file. (I moved a running PostgreSQL to patroni) 

```yml
scope: cluster2
namespace: /db/
name: bhuvi-psql

restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008

etcd:
    host: 10.128.0.18:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 0.0.0.0/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 0.0.0.0:5432
    connect_address: 0.0.0.0:5432
    data_dir: /data/patroni
    bin_dir: /usr/lib/postgresql/9.6/bin
    config_file: /etc/postgresql/9.6/main/postgresql.conf
    ident_file: /etc/postgresql/9.6/main/pg_ident.conf
    hba_file: /etc/postgresql/9.6/main/pg_hba.conf
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: rep-pass
        superuser:
            username: postgres
            password: secretpassword
    parameters:
        unix_socket_directories: '/tmp'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log:
    dir: /var/log/postgresql/
```

If I make any changes on `/etc/postgresql/9.6/main/postgresql.conf` or `pg_hba` files, even after restarting patroni, the values are still same. (I ran query to get the value like `select * from pg_settings where name='max_connections';`) 

I have granted `postgres:postgres` to conf file dir.
Im not able to find where I did mistake. Can someone help me to figure this out?
