### ISSUE TITLE
Patroni not creating database / users

### ISSUE THREAD

**Issue by jamessewell** [zalando/patroni#1168]
Hello,

I'm using Spilo / Patroni on K8s (deployed via the master branch of postgres-operator)

All works like magic, except my databases and users aren't being created:

I have this in my config:
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: f-postgres-cluster
  namespace: f
spec:
  teamId: "fg"
  volume:
    size: 11Gi
    storageClass: postgres
  numberOfInstances: 3
  users:
    fuser:
    - superuser
    - createdb
  databases:
    db1: fuser
    db2 : fuser
  postgresql:
    version: "11"
```
