### ISSUE TITLE
post_init for the reinit phase

### ISSUE THREAD

**Issue by wolfgangbrandl** [zalando/patroni#1172]
Hi
We have the effect that after an reinit we lost the symbolic link in the postgres data directory for the pg_wal or pg_xlog and also an entry in the .pgpass ist lost .
So i wanted to solve that with the post_init shell script. But it seems that this script is never called in the renit phase.
Is that correct?
Is there another possiblity to call a script?
Regards
Wolfgang

**Comment by CyberDem0n** [comment]
Hi @wolfgangbrandl 

There are many options available:
1. you can use the custom replica build methods for that: https://github.com/zalando/patroni/blob/master/docs/replica_bootstrap.rst#building-replicas. Basically just wrap a pg_basebackup in a script and do whatever you need before and after executing pg_basebackup.
2. If your problem is only pg_wal symlink, it is possible to configure a custom pg_basebackup options:
```yaml
postgresql:
    basebackup:
        max-rate: '100M'
        checkpoint: 'fast'
        waldir: /foo/bar
```
