### ISSUE TITLE
Question about the etcd or zookeeper's ip change

### ISSUE THREAD

**Issue by henrywangx** [zalando/patroni#1183]
Hi,
I have a question. Whether the patroni could handle the dcs's ip change case.
I mean, if I use the server name or ip. This situation is very normal in kubernetes or docker.
Like:
```yaml
zookeeper:
    hosts: ['host0-name:2181', 'host1-name:2181', 'host2-name:2181']
//or
etcd:
    hosts: ['etcd0:2379', 'etcd1:2379', 'etcd2:2379']
```
If those IPs have been changed by k8s, could the patroni aware it?
