### ISSUE TITLE
max_connections being set incorrectly on standby_cluster Patroni 1.6.0

### ISSUE THREAD

**Issue by cdloh** [zalando/patroni#1334]
I'm having trouble setting up a new standby_cluster using Patroni

```
(.patroni_env) bash-4.2$ patroni /etc/patroni.conf.yaml
2019-12-13 10:17:20,130 INFO: Failed to import patroni.dcs.consul
2019-12-13 10:17:20,155 INFO: Selected new etcd server http://127.0.0.1:2379
2019-12-13 10:17:20,169 INFO: No PostgreSQL configuration items changed, nothing to reload.
2019-12-13 10:17:20,210 WARNING: Postgresql is not running.
2019-12-13 10:17:20,211 INFO: Lock owner: None; I am HOSTNAME
2019-12-13 10:17:20,216 INFO: pg_controldata:
  Database system identifier: 6764377522007177110
  pg_control last modified: Wed Dec 11 09:41:48 2019
  Blocks per segment of large relation: 0
  Size of a large-object chunk: 0
  WAL block size: 0
  Latest checkpoint's oldestActiveXID: 0
  Latest checkpoint's TimeLineID: 1
  Bytes per WAL segment: 0
  Fake LSN counter for unlogged rels: 0/0
  max_connections setting: 16777216
  Latest checkpoint location: 180E488/0
  Float8 argument passing: by reference
  Minimum recovery ending location: 2/0
  track_commit_timestamp setting: on
  Latest checkpoint's newestCommitTsXid: 0
  Float4 argument passing: by reference
  Latest checkpoint's NextMultiXactId: 0
  Maximum size of a TOAST chunk: 0
  Maximum data alignment: 2847132569
  Date/time type storage: 64-bit integers
  Database block size: 0
  Data page checksum version: 0
  Time of latest checkpoint: Wed Dec 31 19:00:00 1969
  WARNING: Calculated CRC checksum does not match value stored in file.
  wal_log_hints setting: off
  Latest checkpoint's full_page_writes: off
  End-of-backup record required: no
  max_prepared_xacts setting: 32
  wal_level setting: unrecognized wal_level
  Latest checkpoint's NextMultiOffset: 1882
  Backup start location: 8/40
  Latest checkpoint's oldestMultiXid: 1576075308
  Mock authentication nonce: 0000000000000000000000000000000000000000000000000000000000000000
  Latest checkpoint's NextOID: 1
  Maximum columns in an index: 0
  Latest checkpoint's oldestCommitTsXid: 0
  Catalog version number: 201204301
  max_worker_processes setting: 64
  Maximum length of identifiers: 0
  Min recovery ending loc's timeline: 100
  max_locks_per_xact setting: 1996
  Latest checkpoint's NextXID: 1891:12927
  Latest checkpoint's REDO location: 180E488/0
  Backup end location: 4132D687/0
  Database cluster state: shut down
  pg_control version number: 922
  Prior checkpoint location: 180E428/0
  Latest checkpoint's REDO WAL file: 000000010180E48800000000
  Latest checkpoint's oldestXID: 1
  Latest checkpoint's oldestXID's DB: 0
  Latest checkpoint's oldestMulti's DB: 0
  Latest checkpoint's PrevTimeLineID: 1

2019-12-13 10:17:20,221 INFO: Lock owner: None; I am HOSTNAME
2019-12-13 10:17:20,228 INFO: trying to follow a remote master because standby cluster is unhealthy
2019-12-13 10:17:20,248 INFO: postmaster pid=727
2019-12-13 15:17:20.255 GMT [727] FATAL:  16777216 is outside the valid range for parameter "max_connections" (1 .. 262143)
localhost:5432 - no response
2019-12-13 10:17:21,271 ERROR: postmaster is not running
2019-12-13 10:17:21,299 INFO: Lock owner: None; I am HOSTNAME
2019-12-13 10:17:21,304 INFO: failed to start postgres
^C2019-12-13 10:17:21,426 INFO: Lock owner: None; I am HOSTNAME
```

For some reason max_connections is getting set to 16777216

my patroni config is below

```
---

name: HOSTNAME

bootstrap:
    dcs:
        loop_wait: 10
        maximum_lag_on_failover: 1048576
        retry_timeout: 10
        standby_cluster:
            create_replica_methods:
              - basebackup
            host: 127.0.0.1
            port: 5000
            primary_slot_name: patroni
        ttl: 30
    initdb:
    -   encoding: UTF8
    - data-checksums
    pg_hba:
    - local all postgres    peer
    - local all all    peer
    - host all all 127.0.0.1/32   md5
    - host all all ::1/128   md5
    postgresql:
        parameters:
            max_connections: 100
    users:
        postgres:
            password: SNIP
        replicator:
            password: SNIP


etcd:
    host: 127.0.0.1:2379
postgresql:
    authentication:
        replication:
            password: SNIP
            username: replicator
        superuser:
            password: SNIP
            username: postgres
    bin_dir: /usr/pgsql-10/bin
    connect_address: 10.9.52.45:5432
    data_dir: /var/lib/pgsql/data
    listen: 0.0.0.0:5432
    parameters:
        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f &&
            cp %p ../wal_archive/%f
        archive_mode: 'off'
        archive_timeout: 1800s
        autovacuum: true
        bytea_output: escape
        default_statistics_target: 150
        fsync: true
        hot_standby: 'on'
        log_autovacuum_min_duration: 0
        log_min_duration_statement: 2000
        logging_collector: true
        max_connections: 100
        max_replication_slots: 10
        max_wal_senders: 10
        ssl: true
        ssl_cert_file: /var/lib/pgsql/server.crt
        ssl_key_file: /var/lib/pgsql/server.key
        standard_conforming_strings: false
        track_counts: true
        wal_keep_segments: 8
        wal_level: hot_standby
        wal_log_hints: 'on'
        wal_sync_method: fdatasync
    pg_hba:
    - local all postgres peer map=postgres_access
    - host all postgres samehost md5
    - local all all md5
    - hostssl replication replicator 0.0.0.0/0 md5
    - hostssl all all all md5
    pg_ident:
    - postgres_access postgres postgres
    - postgres_access root     postgres
    pgpass: /tmp/pgpass2
restapi:
    connect_address: 0.0.0.0:8010
    listen: 0.0.0.0:8010
scope: production
tags:
    clonefrom: false
    nofailover: false
    noloadbalance: true
```

Any tips / pointers?
