### ISSUE TITLE
Can we use single etcd cluster for multiple patroni cluster

### ISSUE THREAD

**Issue by Tekchanddagar** [zalando/patroni#1354]
Hello Team,

Currently we are using 3 node etcd cluster and 3 node patroni cluster and everything is working fine.
But now we need to setup one more patroni cluster  of 3 node or another environment. 

Can we use existing etcd cluster for multiple patroni cluster?

If yes, please give some idea how we can do it.

Thanks.

**Comment by CyberDem0n** [comment]
Yes, we are running a few hundred Patroni clusters with a single etcd cluster.

**Comment by Tekchanddagar** [comment]
@CyberDem0n, Thank you for your quick response.

Any changes are required on etcd cluster?

Or we can define the etcd machine in same way like we defined in current running patroni cluster.

```
scope: promobi
namespace: /db/
name: sql01

restapi:
    listen: 10.12.15.9:8008
    connect_address: 10.12.15.9:8008
log:
   level: INFO
   dir: /var/log/patroni/
etcd:
    hosts: 10.12.238.133:2379,10.12.64.98:2379,10.12.69.184:2379
```

Thanks.
