### ISSUE TITLE
Info Required - Telegraf Monitoring for Patroni

### ISSUE THREAD

**Issue by dream4r1** [zalando/patroni#1357]
We are setting up telegraf to monitor patroni but having failures below are the telegraf conf as per the document could some one will share how to successfully configure this.

`[[inputs.prometheus]]
   urls = ["http://localhost:8008/patroni"]`

### Errors 
`Jan  9 15:18:00 hostname telegraf: 2020-01-09T15:18:00Z E! Error in plugin [inputs.prometheus]: error reading metrics for http://localhost:8008/patroni: reading text format failed: text format parsing error in line 1: invalid metric name`

**Comment by dream4r1** [comment]
@wilfriedroset - looping you in directly as you seem to have configured telegraf for patroni monitor.

**Comment by gowtham500** [comment]
Even i was not able to get this working and faced similar issue. I then used the procstat input plugin instead of http plugin.

[[inputs.procstat]]
  exe = "patroni"

**Comment by wilfriedroset** [comment]
Hello

I'm using telegraf for metrics collection only. For the monitoring, I'm relying on good old fashion icinga.

I would suggest that you use the input [http_response](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_response) from telegraf to monitor patroni.

In my case, I'm using the following:
* debian 9
* patroni 1.6.0-4.pgdg90+1
* telegraf 1.11.3-1

Here is an example of configuration (you might need to adjust it for your case)
```toml
# cat debug.conf
[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[inputs.http_response]]
  # For telegraf < 1.12
  address = "https://127.0.0.1:8443/health"
  # For telegraf >= 1.12
  #urls = ["https://127.0.0.1:8443/health"]

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  insecure_skip_verify = true
```

This would produce the following metrics
```
# curl -s -k https://127.0.0.1:8443/ | jq -r '.role'
replica

# telegraf --config debug.conf --test
2020-01-14T12:29:06Z I! Starting Telegraf 1.11.3
> http_response,host=patroni-99-node-1.ovh.ha.ovh.net,method=GET,result=success,server=https://localhost:8443/health,status_code=200 http_response_code=200i,response_time=0.015067637,result_code=0i,result_type="success" 1579004947000000000
```

Full disclamer: I'm not scrapping any metrics from patroni
