### ISSUE TITLE
Patroni missed creating the replication slot for the nodes in the cluster

### ISSUE THREAD

**Issue by RajKiranS** [zalando/patroni#1369]
Hello,

Recently we have started seeing that whenever a slave(sync-standby/standby) is restarted, the master doesn't create the replication slot. This doesn't happen at every restart but randomly/inconsistent.

In the slave postgres logs:
```
< 2020-01-22 05:21:12.824 GMT > FATAL:  could not start WAL streaming: ERROR:  replication slot "abcd_xyz_com" does not exist
```

In Master postgres logs:
```
< 2020-01-22 05:20:42.606 GMT > ERROR:  replication slot "abcd_xyz_com" does not exist
```

I don't see anything suspicious errors/warnings in the Patroni logs of both the Master and Slave.

Versions:
```
Patroni version: 1.6.0
DCS: ZooKeeper
PostgreSQL: 9.4
```

Our Patroni dynamic config:
```
loop_wait: 10
master_start_timeout: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: exit 0
    archive_mode: 'on'
    hot_standby: true
    max_connections: 200
    max_replication_slots: 5
    max_wal_senders: 5
    wal_keep_segments: 128
    wal_level: hot_standby
    wal_log_hints: true
  recovery_conf:
    restore_command: get-wal-from-barman barman abcd %f %p
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
slots:
  barman:
    type: physical
synchronous_mode: true
synchronous_mode_strict: false
ttl: 10
```
