### ISSUE TITLE
Unable to edit config

### ISSUE THREAD

**Issue by sc0rp10** [zalando/patroni#1372]
Hi.

I need to change some postgres parameters in runtime and unable to do it - my changes does not applied.

For example, I need to change `work_mem` parameter value.

```bash
# patroni --version
patroni 1.6.3
```

my `/etc/patroni.yaml`:
<details>

```yaml
scope: main
name: postgres-main-1

restapi:
    listen: 127.0.0.1:8008
    connect_address: 127.0.0.1:8008

consul:
    host: 127.0.0.1:8500

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:
                shared_preload_libraries: pg_stat_statements
                max_connections: 600
                max_locks_per_transaction: 64
                max_worker_processes: 10

    initdb:
        - 'encoding: UTF8'
        - data-checksums
    pg_hba:
        - host replication replicator 0.0.0.0/0 md5
        - host all all 0.0.0.0/0 md5

    users: {} # skipped

postgresql:
    listen: 10.10.10.10:5432
    connect_address: 10.10.10.10:5432
    data_dir: /opt/patroni
    pgpass: /tmp/pgpass
    parameters:
        max_parallel_workers: 10
        max_parallel_workers_per_gather: 5
        shared_buffers: 8GB
        temp_buffers: 128MB
        work_mem: 16MB
        maintenance_work_mem: 1GB
        wal_buffers: 16MB
        min_wal_size: 1GB
        max_wal_size: 2GB
        max_wal_senders: 3
        wal_keep_segments: 4
        effective_cache_size: 12GB
        autovacuum_naptime: 10min
        autovacuum_vacuum_threshold: 500
        autovacuum_analyze_threshold: 500
    pg_hba:
        - local all         all                     trust
        - host  all         all        127.0.0.1/32 trust
        - host  all         all        ::1/128      trust
        - local replication all                     trust
        - host  replication all        127.0.0.1/32 trust
        - host  replication all        ::1/128      trust
        - host  replication replicator 0.0.0.0/0  md5
        - host  all         all        0.0.0.0/0  md5
    authentication: {} # skipped

watchdog:
    mode: off
```
</details>

`# patronictl -c /etc/patroni.yaml edit-config main`

```diff
---
+++
@@ -7,7 +7,7 @@
     max_locks_per_transaction: 64
     max_worker_processes: 10
     shared_preload_libraries: pg_stat_statements
-    work_mem: 8MB
+    work_mem: 128MB
   use_pg_rewind: true
   use_slots: true
 retry_timeout: 10

Apply these changes? [y/N]: y
Configuration changed
```

But in the patroni log I see: `INFO: No PostgreSQL configuration items changed, nothing to reload.`

Let's check `work_mem` value:

```
# show work_mem;
 work_mem
----------
 16MB # WAT?
(1 row)

Time: 0.573 ms
```

```bash
# grep work_mem /opt/patroni/postgresql.conf*
postgresql.conf:work_mem = '16MB'
postgresql.conf.backup:work_mem = '16MB'
```

What I doing wrong? What is correct way to edit postgres config?

Thanks.
