### ISSUE TITLE
Delayed Replica

### ISSUE THREAD

**Issue by doribd** [zalando/patroni#1402]
Hi
What is the best way to define such with Patroni?

**Comment by CyberDem0n** [comment]
There is only one way, add to the config.yml:
```yaml
postgresql:
  recovery_conf:
    recovery_min_apply_delay: XXX
```
