### ISSUE TITLE
can't create replica on huge database

### ISSUE THREAD

**Issue by VerifiedUser5611** [zalando/patroni#1405]
Hello.
We use bare-metal servers in patroni cluster and huge size database (21 Tb).
PGDATA=/pgsql/11/data
Also, we use additional tablespaces:
```
    Name    |  Owner   |      Location
------------+----------+--------------------
 data       | postgres | /migr/tbs/data2
 pg_default | postgres |
 pg_global  | postgres |
 tmp        | postgres | /migr/tbs/temp/tbs
```

After starting patroni on replica server it copies all files from tablespace /migr/tbs/data2 (it tooks almost 20 hours), some wal files to /pgsql/11/data/pg_wal and stuck with messages:
```
Feb 19 15:47:20 node01 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Feb 20 10:03:45 node01 patroni[8560]: pg_basebackup: COPY stream ended before last file was finished
Feb 20 10:03:45 node01 patroni[8560]: pg_basebackup: removing contents of data directory "/pgsql/11/data"
Feb 20 10:18:01 node01 patroni[8560]: pg_basebackup: changes to tablespace directories will not be undone
```
Then patroni clean up PGDATA and 

Patroni config looks like this:
```
[root@nod02 pg_wal]# patronictl show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    autovacuum: 'off'
    checkpoint_timeout: 15min
    hot_standby: 'on'
    max_connections: '600'
    max_replication_slots: 5
    max_wal_senders: 5
    max_wal_size: 4GB
    max_worker_processes: 65
    synchronous_commit: 'off'
    synchronous_standby_names: ''
    temp_buffers: 256MB
    wal_keep_segments: 100
    wal_level: replica
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: 'false'
synchronous_mode_strict: 'false'
ttl: 30
```
Can be any benefits useful in creating replica if we increase parameters wal_keep_segments and/or max_wal_size?
