### ISSUE TITLE
Patroni removes recovery.conf anyway.

### ISSUE THREAD

**Issue by Badgerus54** [zalando/patroni#1426]
Hello!
There was a problem restoring the backup using pgBackRest. When starting after restoration, the Patroni are replaced by recovery.conf in any case, regardless of configuration.

I tried to delete the “recovery.conf” in the patroni.yml from the “dcs” or “method” or both, but this did not work.

Tell me, please, how can I configure Patroni so that it does not replace the recovery.conf created by pgBackRest?

Patroni.yaml for example:

```
scope: *some-scope*
name: *some-name*

consul:
  host: 127.0.0.1:8500
  register_service: true
  token: *some-token*

restapi:
  listen: 0.0.0.0:8008
  connect_address: *some-ip*:8008

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: logical
        hot_standby: "on"
        superuser_reserved_connections: 3
        effective_io_concurrency: 350
        synchronous_commit: "remote_write"
        checkpoint_completion_target: 0.9
        wal_keep_segments: 50
        max_wal_senders: 5
        max_replication_slots: 6
        checkpoint_timeout: 20min
        max_connections: 100
        autovacuum_max_workers: 10
        autovacuum_vacuum_cost_limit: 1000
        autovacuum_vacuum_threshold: 15000
        autovacuum_analyze_threshold: 500
        autovacuum_vacuum_scale_factor: 0.1
        autovacuum_analyze_scale_factor: 0.01
        autovacuum_freeze_max_age: 16000000
        autovacuum_multixact_freeze_max_age: 32000000
        autovacuum_vacuum_cost_delay: 10
        autovacuum_vacuum_cost_limit: 1000
        maintenance_work_mem: 1GB
        work_mem: 64MB
        vacuum_cost_limit: 1000
        max_wal_size: 4GB
        min_wal_size: 2GB
        effective_cache_size: 7168MB
        shared_buffers: 2048MB
        max_worker_processes: 4
        max_parallel_maintenance_workers: 2
        max_parallel_workers_per_gather: 2
        max_parallel_workers: 4
        wal_log_hints: "on"
        wal_buffers: 102MB
        max_locks_per_transaction: 1000
        full_page_writes: "off"
        random_page_cost: 1.1
        default_statistics_target: 100
        archive_mode: "on"
        archive_timeout: 600s
        archive_command: pgbackrest --stanza=*some-stanza* archive-push %p
        shared_preload_libraries: pg_stat_statements, pg_partman_bgw
        pg_stat_statements.max: 5000
        pg_stat_statements.track: "top"
        pg_stat_statements.track_utility: "off"
        pg_stat_statements.save: "on"

      recovery_conf:
        restore_command: /usr/bin/pgbackrest --stanza=*some-stanza* archive-get %f "%p"

  method: pgbackrest
  pgbackrest:
    command: /opt/test2.sh
------------------------------------------------
_File /opt/test2.sh content:
#!/usr/bin/env bash

while getopts ":-:" optchar; do
  [[ "${optchar}" == "-" ]] || continue
  case "${OPTARG}" in
    datadir=* )
        DATA_DIR=${OPTARG#*=}
        ;;
    scope=* )
        SCOPE=${OPTARG#*=}
        ;;
  esac
done

/usr/bin/pgbackrest --stanza=$SCOPE --delta --process-max=4_
------------------------------------------------
    keep_existing_recovery_conf: true
    recovery_conf:
      recovery_target_action: promote
      recovery_target_timeline: latest
      restore_command: /usr/bin/pgbackrest --stanza=*some-stanza* archive-get %f "%p"
      recovery_target_inclusive: true

  users:
    patroni:
      password: *some-password*
      options:
        - createrole
        - createdb
    replicator:
      password: *some-password*
      options:
        - replication

postgresql:
    listen: 0.0.0.0:5432
    connect_address: *some-ip*5432
    data_dir: /var/lib/pgsql/11/data/
    config_dir: /var/lib/pgsql/11/data/
    pgpass: /tmp/pgpass
    bin_dir: /usr/pgsql-11/bin
    callbacks:
      on_role_change: "/etc/patroni/scripts/rolechange.py"
      on_reload: "/etc/patroni/scripts/reload.py"
      on_restart: "/etc/patroni/scripts/restart.py"
      on_start: "/etc/patroni/scripts/start.py"
      on_stop: "/etc/patroni/scripts/stop.py"
    authentication:
        replication:
            username: replicator
            password: *some-password*
        superuser:
            username: patroni
            password: *some-password*
    parameters:
        unix_socket_directories: '/var/run/postgresql'
        port: 5432
    create_replica_methods:
    - pgbackrest
    pgbackrest:
        command: /opt/pgbackrest_replica.sh
------------------------------------------------
File /opt/pgbackrest_replica.sh content:
#!/bin/sh

mkdir /var/lib/pgsql/11/data/
chown -R postgres:postgres /var/lib/pgsql/11/data

while getopts ":-:" optchar; do
  [[ "${optchar}" == "-" ]] || continue
  case "${OPTARG}" in
    datadir=* )
        DATA_DIR=${OPTARG#*=}
        ;;
    scope=* )
        SCOPE=${OPTARG#*=}
        ;;
  esac
done

/usr/bin/pgbackrest --stanza=$SCOPE --delta restore
------------------------------------------------
        keep_data: True
        no_params: True
```

P.S. Sorry for my bad english!
