### ISSUE TITLE
k8s - pg_hba.conf config reset on restart

### ISSUE THREAD

**Issue by smirnov-mi** [zalando/patroni#1443]
Hi guys

I'm running patroni on a k8s cluster, installed as helm chart.
I'm trying to make some changes in the pg_hba.conf,
so I make patronictl edit-config and it works well.
Then I edit local postgres.yml in every container,
and reloading it all with   patronictl reload. So far so good,
it all works.  BUT after any container gets rescheduled,
it has the initial postgres.yml without my changes, and loads these default settings
which eliminates the config from DCS.

I have two clusters and see the same issue on patroni v 1.5.7 and 1.6,0

So I guess I'm missing something. Just what?

**Comment by CyberDem0n** [comment]
I suppose the helm chart is using spilo image.
Upon start it generates postgres.yml with hard-coded pg_hba: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py#L261-L283

The only way to make override it - via SPILO_CONFIGURATION environment variable.

**Comment by smirnov-mi** [comment]
Thanks for the fast reply!  Yes it's these images:

  repository: registry.opensource.zalan.do/acid/spilo-11
  tag: 1.5-p9

and
  repository: registry.opensource.zalan.do/acid/spilo-10
  tag: 1.4-p16

Will try to find how to do it.  
Btw. is there a way to use latest Spilo image but run PG10 or PG11 in it ?
I couldn't find it yet.

**Comment by CyberDem0n** [comment]
The latest image is `registry.opensource.zalan.do/acid/spilo-12:1.6-p2`
You can choose the posgres version by providing the environment variable: `PGVERSION=10`

**Comment by smirnov-mi** [comment]
thank you, i will try to find the place to set PGVERSION.

**Comment by smirnov-mi** [comment]
There is an extra custom env part in the values.yaml so I put PGVERSION in there:

# Extra custom environment variables.
env:
  PGVERSION: 10

which results in:

```
kind: StatefulSet
...
    spec:
      serviceAccountName: patroni
      containers:
      - name: patroni
        image: "registry.opensource.zalan.do/acid/spilo-12:1.6-p2"
        imagePullPolicy: IfNotPresent
        env:
        - name: PGPASSWORD_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: patroni
              key: password-superuser
        - name: PGPASSWORD_ADMIN
          valueFrom:
            secretKeyRef:
              name: patroni
              key: password-admin
...
...
        - name: SCOPE
          value: patroni
        - name: USE_WALE
          value: ""
        - name: PGROOT
          value: "/home/postgres/pgdata/pgroot"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: "PGVERSION"
          value: "10"
```

but it doesn't work. Still get 12.2 installed.
