### ISSUE TITLE
validate configuration parameters via patronictl

### ISSUE THREAD

**Issue by zpavlig** [zalando/patroni#1471]
Is there any way to validate configuration parameters via patronictl?

```
---
+++
@@ -5,7 +5,7 @@
   parameters:
     archive_command: /bin/true
     archive_mode: 'on'
-    max_connections: '500'
+    max_connections: '500ABC'
   use_pg_rewind: 'true'
 retry_timeout: 10
 synchronous_mode: 'true'

Apply these changes? [y/N]: y
Configuration changed
```

```
---
+++
@@ -6,6 +6,7 @@
     archive_command: /bin/true
     archive_mode: 'on'
     max_connections: 500ABC
+    maxxx_connections: 100
   use_pg_rewind: 'true'
 retry_timeout: 10
 synchronous_mode: 'true'

Apply these changes? [y/N]: y
Configuration changed
```

patronictl show-config
```
loop_wait: '5'
master_start_timeout: 30
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: /bin/true
    archive_mode: 'on'
    max_connections: 500ABC
    maxxx_connections: 100
  use_pg_rewind: 'true'
retry_timeout: 10
synchronous_mode: 'true'
synchronous_mode_strict: 'true'
ttl: '20'

```
