### ISSUE TITLE
no_params for custom bootstrap method

### ISSUE THREAD

**Issue by vitabaks** [zalando/patroni#1475]
**Please** add support the `no_params` parameter for the custom cluster bootstrap method.

> A special no_params parameter, if defined, restricts passing parameters to custom command.

In order not to wrap the restore command to a script.

Example:
```
bootstrap:
  method: wal_g
  wal_g:
    command: wal-g backup-fetch {{ postgresql_data_dir }} LATEST
    no_params: True
    recovery_conf: 
       recovery_target_action: promote
       recovery_target_timeline: latest
       restore_command: wal-g wal-fetch %f %p
```
