### ISSUE TITLE
PITR for Delayed Replica

### ISSUE THREAD

**Issue by Argha-2890** [zalando/patroni#1520]
HI Team,

Patroni Version : 1.6
Postgresql Version : 11
OS : Ubuntu 18.04

I have a delayed Replica in my cluster which is running without any issues. However, while trying to test PITR I am struggling to restore the database till a particular point of time of my choice using `recovery_target_time`.  Instead it is restoring the database to the current state which doesn't solve my purpose.

I am using pgBackRest for archiving WAL's.

Patroni Config : 

```
scope: mycluster
namespace: /pgdb/
name: pg3

restapi:
  listen: 10.0.0.31:8010
  connect_address: 10.0.0.31:8010

etcd:
  hosts: 10.0.0.5:2379,10.0.0.51:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      #      use_slots: true



  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator 10.0.1.59/32 md5
  - host replication replicator 10.0.0.60/32 md5
  - host replication replicator 10.0.0.31/32 md5
  - host all all 0.0.0.0/0 md5


  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 10.0.0.31:5432
  connect_address: 10.0.0.31:5432
  data_dir: /data/patroni3
  pgpass: /tmp/pgpass3
  authentication:
    replication:
      username: replicator
      password: repl@123
    superuser:
      username: postgres
      password: postgres@123
  parameters:
    unix_socket_directories: '/tmp, /var/run/postgresql'
    logging_collector: "on"
    log_directory: "/var/log/postgresql"
    log_filename: "postgresql-%Y-%m-%d_%H%M%S.log"
    log_statement: "all"
  create_replica_methods:
      - pgbackrest
        #      - basebackup
  pgbackrest:
      command: /usr/bin/pgbackrest --stanza=mdb --delta restore --log-level-console=info --process-max=3 --type=time "--target=2020-05-06 04:00:00.676347+00" --target-action=pause
      keep_data: True
      no_params: True
      #  basebackup:
      #      - verbose
      #      - max-rate: 100M
      #  recovery_conf:
      #      recovery_min_apply_delay: '360000'
      #      recovery_target_timeline: 'latest'
      #      recovery_target: 'immediate'
      #      recovery_target_action: 'pause'
      #      recovery_target_time: '2020-05-06 05:08:00.676347+00'

tags:
    nofailover: true
    noloadbalance: true
    clonefrom: false

log:
    dir: /var/log/postgresql
    level: INFO
```

**Comment by CyberDem0n** [comment]
After the data directory on the replica was initialized by pgpackrest Patroni overwrites recovery.conf, therefore it doesn't contain neither recovery_target_action nor recovery_target_time.
You have to configure it explicitly in the `postgresql.recovery_conf` section.

**Comment by Argha-2890** [comment]
Ok..So should I change the `recovery.conf` file configuration in the patroni.yml file or manually modify it in data directory. I have tried changing via `postgresql.recovery_conf` section, but it's still recovering till the current time.

**Comment by CyberDem0n** [comment]
> I have tried changing via postgresql.recovery_conf section, but it's still recovering till the current time.

It requires to restart or reload Patroni.

**Comment by Argha-2890** [comment]
@CyberDem0n I have tried the below settings and restarted as well as reloaded the cluster but to no avail. Could you please tell what I am doing incorrectly.

```
postgresql:
  listen: 10.0.0.31:5432
  connect_address: 10.0.0.31:5432
  data_dir: /data/patroni3
  pgpass: /tmp/pgpass3
  authentication:
    replication:
      username: replicator
      password: repl@123
    superuser:
      username: postgres
      password: postgres@123
  parameters:
    unix_socket_directories: '/tmp, /var/run/postgresql'
    logging_collector: "on"
    log_directory: "/var/log/postgresql"
    log_filename: "postgresql-%Y-%m-%d_%H%M%S.log"
    log_statement: "ddl"
  create_replica_methods:
      - pgbackrest
        #      - basebackup
  pgbackrest:
      command: /usr/bin/pgbackrest --stanza=mdb --delta restore --log-level-console=info --process-max=3
      keep_data: True
      no_params: True
      #  basebackup:
      #      - verbose
      #      - max-rate: 100M
  recovery_conf:
      recovery_target_timeline: 'latest'
      recovery_target: 'immediate'
      recovery_target_action: 'pause'
      recovery_target_time: '2020-05-06 05:08:00.676347+00'
```

**Comment by CyberDem0n** [comment]
Config looks good. After pgbackrest was executed Patroni should create the recovery.conf with parameters from the `postgresql.recovery_conf` and start postgres. You can verify it.

**Comment by Argha-2890** [comment]
@CyberDem0n - I reloaded and restarted the node but the recovery is not pausing at `recovery_target_time`. 
```

postgres=# SELECT pg_last_wal_replay_lsn(),pg_last_xact_replay_timestamp(),now(),'2020-05-06 04:55:00.676347+00'::timestamptz - pg_last_xact_replay_timestamp() as delay;
 pg_last_wal_replay_lsn | pg_last_xact_replay_timestamp |              now              |      delay
------------------------+-------------------------------+-------------------------------+------------------
 1/45CF2A80             | 2020-05-06 05:16:33.924381+00 | 2020-05-06 10:17:11.167031+00 | -00:21:33.248034
(1 row)

```

Any suggestions on this.

**Comment by CyberDem0n** [comment]
Have you reinitialized it?
There is no way to "roll back" replayed changes.

**Comment by Argha-2890** [comment]
I want to start from scratch. Could you please tell me the chronology of this operation.

1.  Change settings in the patroni config file
2. Restart and Reload the node
3. Reinitialize the node

**Comment by Argha-2890** [comment]
I want to start from scratch. Could you please tell me the chronology of this operation.

1.  Change settings in the patroni config file
2. Restart and Reload the node
3. Reinitialize the node

**Comment by CyberDem0n** [comment]
1. correct
2. restart or reload just Patroni process no the node where you changed the config (there is no need to restart the whole node!). It might take up to loop_wait seconds for reloading.
3. correct

**Comment by Argha-2890** [comment]
You are asking me to use patronictl reload right?

**Comment by CyberDem0n** [comment]
Please read the [documentation](https://patroni.readthedocs.io/en/latest/dynamic_configuration.html?highlight=reload#patroni-configuration)

**Comment by Argha-2890** [comment]
It's not working. I created and dropped a table at the below mentioned times.

```
sample=# create table tom as select s, md5(random()::text) from generate_Series(1,5000) s;
SELECT 5000
sample=#
sample=#
sample=# select now();
             now
------------------------------
 2020-05-06 11:26:36.73752+00
(1 row)
sample=# \dt
           List of relations
 Schema |    Name    | Type  |  Owner
--------+------------+-------+----------
 public | abcd       | table | postgres
 public | hello      | table | postgres
 public | t_random_2 | table | postgres
 public | tom        | table | postgres
(4 rows)

sample=#
sample=#
sample=# drop table t_random_2 ;
DROP TABLE
sample=#
sample=#
sample=# select now();
              now
-------------------------------
 2020-05-06 11:28:27.136311+00
(1 row)
```
Patroni.yml :

```
  create_replica_methods:
      - pgbackrest
        #      - basebackup
  pgbackrest:
      command: /usr/bin/pgbackrest --stanza=mdb --delta restore --log-level-console=info --process-max=3
      keep_data: True
      no_params: True
      #  basebackup:
      #      - verbose
      #      - max-rate: 100M
  recovery_conf:
      #      recovery_min_apply_delay: '360000'
      #      recovery_target_timeline: 'latest'
      recovery_target: 'immediate'
      recovery_target_action: 'pause'
      recovery_target_time: '2020-05-06 11:26:36.73752+00'
```

I performed the aforementioned steps but I see that the database was recovered beyond `recovery_target_time=2020-05-06 11:26:36.73752+00` as the dropped table (table dropped at 2020-05-06 11:28:27.136311+00 approximately ) is not showing.
