### ISSUE TITLE
patroni failed to start. System ID mismatch

### ISSUE THREAD

**Issue by KostLinux** [zalando/patroni#1539]
When restarting patroni, getting this error:
```
May 11 11:12:42 abiv-misp-b.prd.itarchive.home patroni[6121]: 2020-05-11 11:12:42,616 CRITICAL: system ID mismatch, node abiv-misp-b.prd.itarchive.home belongs to a different cluster:
May 11 11:12:43 abiv-misp-b.prd.itarchive.home patroni[6121]: 2020-05-11 11:12:43,107 INFO: Lock owner: abiv-psql-a.prd.itarchive.home; I am abiv-misp-b.prd.itarchive.home
```
Here's my conf:
```
scope: postgres
name: abiv-misp-b.prd.itarchive.home
restapi:
    listen: '10.11.10.126:8008'
    connect_address: '10.11.10.126:8008'
etcd:
    hosts:
       - 10.11.10.120:2379
       - 10.11.10.121:2379
       - 10.11.10.122:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters: {wal_level: replica, hot_standby: on, wal_keep_segments: 8, max_wal_senders: 5, max_replication_slots: 5, checkpoint_timeout: 30, synchronous_commit: on, synchronous_standby_names: '*'}
    initdb:
        - encoding: UTF8
        - data-checksums
    pg_hba:
        - 'host replication replicator 127.0.0.1/32 md5'
        - 'host replication replicator 10.11.10.123/24 md5'
        - 'host replication replicator 10.11.10.124/24 md5'
        - 'host replication replicator 10.11.10.125/24 md5'
        - 'host replication replicator 10.11.10.126/24 md5'
        - 'host all all 0.0.0.0/0 md5'
    users:
        admin:
            password: admin
            options: [createrole, createdb]
postgresql:
    listen: '10.11.10.126:5432'
    connect_address: '10.11.10.126:5432'
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: replica_pass
        superuser:
            username: postgres
            password: replica_pass
    parameters:
        unix_socket_directories: /var/run/postgresql/
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

```
The problem is, that other slaves are ok.
This slave is runs in error.

**Comment by CyberDem0n** [comment]
Please use [search](https://github.com/zalando/patroni/issues?q=is%3Aissue+system+ID+mismatch+is%3Aclosed).

**Comment by KaremSalhi** [comment]
Bonjour Est ce que vous pouvez résoudre cette erreur?

**Comment by oxycash** [comment]
I actually have a similar issue. I have started a single node cluster, did manual init and then when trying to follow "[Convert a Standalone to a Patroni Cluster](https://patroni.readthedocs.io/en/latest/existing_data.html)" , I get the same error.

```
bash-4.2$ /var/lib/pgsql/.local/bin/patroni /etc/patroni.yml
2023-02-03 11:31:18,676 INFO: No PostgreSQL configuration items changed, nothing to reload.
2023-02-03 11:31:18,680 INFO: establishing a new patroni connection to the postgres cluster
2023-02-03 11:31:18,693 INFO: Register service pglab, params {'service_id': 'pglab/PGDB1', 'address': '172.31.65.91', 'port': 5432, 'check': {'http': 'http://172.31.65.91:8008/master', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['master', 'primary'], 'enable_tag_override': True}
2023-02-03 11:31:18,709 CRITICAL: system ID mismatch, node PGDB1 belongs to a different cluster: 7195861889667348619 != 7195888495522992341
2023-02-03 11:31:18,710 INFO: Register service pglab, params {'service_id': 'pglab/PGDB1', 'address': '172.31.65.91', 'port': 5432, 'check': {'http': 'http://172.31.65.91:8008/master', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['master', 'primary'], 'enable_tag_override': True}
2023-02-03 11:31:19,147 INFO: Deregister service pglab/PGDB1
```

my patroni.yml looks like below

```
name: "PGDB1"
scope: pglab
namespace: /HAPG/

consul:
 url: http://127.0.0.1:8500
 register_service: true

postgresql:
  connect_address: "172.31.65.91:5432"
  bin_dir: /usr/pgsql-12/bin
  data_dir: /var/lib/pgsql/12/data
  listen: "127.0.0.1:5432"
  authentication:
    replication:
      username: replicator
      password: replicator
    superuser:
      username: postgrespatr
      password: postgrespatr
    rewind:
      username: rewind_user
      password: rewind_user
  parameters:
    unix_socket_directories: '/var/run/postgresql'
    synchronous_commit: "on"
    synchronous_standby_names: "*"

restapi:
  connect_address: "172.31.65.91:8008"
  listen: "172.31.65.91:8008"

bootstrap:
  dcs:
    loop_wait: 10
    retry_timeout: 5
    maximum_lag_on_failover: 1048576
    postgresql:
      parameters:
      use_pg_rewind: true
      use_slots: true

  users:
    app_user:
      password: "eW5guPae"
    admin:
      password: admin
      options:
        - createrole
        - createdb

  pg_hba:
    - local all all  trust
    - host all all 127.0.0.1/32 trust
    - host all all ::1/128 trust
    - host all all ::1/128 trust
    - host all all 0.0.0.0/0 trust
    - host replication replicator 127.0.0.1/32 trust
    - host replication replicator 172.31.64.0/20 trust
    - host all all 0.0.0.0/0 trust
  initdb:
    - encoding: UTF8
```
