### ISSUE TITLE
Patroni does not restore hba_file with custom bootstrap

### ISSUE THREAD

**Issue by pursultani** [zalando/patroni#1544]
With custom bootstrap method, when `hba_file` is explicitly set to `${postgresql.data_dir}/pg_hba.conf`, the [logic for the temporary pg_hba](https://github.com/zalando/patroni/blob/v1.6.5/patroni/postgresql/config.py#L458) overrides it and after bootstrapping it goes missing. 

```yaml
postgresql:
  bin_dir: /opt/gitlab/embedded/bin
  data_dir: /var/opt/gitlab/postgresql/data
  config_dir: /var/opt/gitlab/postgresql/data
  listen: 0.0.0.0:5432
  connect_address: 192.168.64.15:5432
  use_unix_socket: true
  parameters:
    unix_socket_directories: /var/opt/gitlab/postgresql
    ident_file: /var/opt/gitlab/postgresql/data/pg_ident.conf
    hba_file: /var/opt/gitlab/postgresql/data/pg_hba.conf
  ...
bootstrap:
  method: gitlab_bootstrap
  gitlab_bootstrap:
    command: /var/opt/gitlab/patroni/bootstrap
  post_bootstrap: /var/opt/gitlab/patroni/post-bootstrap
```

```
2020-05-09_21:40:00.20427 2020-05-10 07:40:00,202 INFO: running post_bootstrap
....
2020-05-09_21:40:00.64002 LOG:  received SIGHUP, reloading configuration files
2020-05-09_21:40:00.64162 LOG:  could not open configuration file "/var/opt/gitlab/postgresql/data/pg_hba.conf": No such file or directory
2020-05-09_21:40:00.64193 LOG:  pg_hba.conf was not reloaded
2020-05-09_21:40:00.64220 server signaled
```

This is of course redundant but one wouldn't expect it to happen.
