### ISSUE TITLE
Error in docker patronictl TypeError: sequence item 2: expected str instance, NoneType found

### ISSUE THREAD

**Issue by ellcrysx** [zalando/patroni#1562]
Deployed a cluster of postgres+patroni and etcd in docker swarm (3 node). using patronictl in docker container I get an error:
**patronictl -d etcd_db show-config**
Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 10, in <module>
    sys.exit(ctl())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/patroni/ctl.py", line 1207, in show_config
    cluster = get_dcs(obj, cluster_name).get_cluster()
  File "/usr/local/lib/python3.7/dist-packages/patroni/ctl.py", line 155, in get_dcs
    return _get_dcs(config)
  File "/usr/local/lib/python3.7/dist-packages/patroni/dcs/__init__.py", line 92, in get_dcs
    return item(config[name])
  File "/usr/local/lib/python3.7/dist-packages/patroni/dcs/etcd.py", line 395, in __init__
    super(Etcd, self).__init__(config)
  File "/usr/local/lib/python3.7/dist-packages/patroni/dcs/__init__.py", line 562, in __init__
    self._base_path = re.sub('/+', '/', '/'.join(['', config.get('namespace', 'service'), config['scope']]))
TypeError: sequence item 2: expected str instance, NoneType found

my image postgres;
```docker
FROM postgres:12

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-cache depends patroni | sed -n -e 's/.* Depends: \(python3-.\+\)$/\1/p' \
        | grep -Ev '^python3-(sphinx|etcd|consul|kazoo|kubernetes)' \
        | xargs apt-get install -y vim-tiny curl jq nano python3-pip python3-wheel \
    && pip3 install patroni[etcd] \
    && apt-get purge -y python3-pip python3-wheel\
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /root/.cache

RUN mkdir /database/ \
    && chown postgres:postgres /database

USER postgres

ENV PATH="/usr/lib/postgresql/12/bin:${PATH}"

EXPOSE 5432 8008

```
image etcd: gcr.io/etcd-development/etcd:v3.3.12

config patroni  (Each container has its own configuration file):
```yaml
scope: etcd_db
namespace: /database/
name: server1

restapi:
  listen: 0.0.0.0:8008
  connect_address: db1:8008
etcd:
  hosts: "etcd1:2379,etcd2:2379,etcd3:2379"

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql: #here pg conf
     
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba: #here pg_hba conf

  # Some additional users which needs to be created after initializing new cluster
  users:
    hello:
      password: hello
      options:
        - superuser

postgresql:
  listen: 0.0.0.0:5432
  connect_address: db1:5432
  data_dir: /database/data
  authentication:
    replication:
      username: qwerty
      password: qwerty
    superuser:
      username: postgres
      password: postgreshello

```
config etcd1.sh (Each container has its own configuration file):
```shell
#!/bin/sh
etcd --name etcd_node1 \
  --data-dir /etcd_data \
  --initial-advertise-peer-urls http://etcd1:2380 \
  --listen-peer-urls http://0.0.0.0:2380 \
  --listen-client-urls http://0.0.0.0:2379 \
  --advertise-client-urls http://etcd1:2379 \
  --initial-cluster-token etcd-cluster-1 \
  --initial-cluster etcd_node1=http://etcd1:2380,etcd_node2=http://etcd2:2380,etcd_node3=http://etcd3:2380 \
  --initial-cluster-state new
```
curl -s http://localhost:8008/cluster | jq  - it work

thanks for answers
