### ISSUE TITLE
How to tell `initdb`to initialize using "--auth-host=scram-sha-256"

### ISSUE THREAD

**Issue by Wolfsrudel** [zalando/patroni#1583]
We want to initialize a new cluster of 12 from scratch with SCRAM. This doesn't work out-of-the-box; we have to upgrade the password of the user "postgres" afterwards.
How do we teach `initdb` when initializing that" --auth-host = scram-sha-256 "should be used?
Current - not working - configuration for the bootstrap:
```
bootstrap:
  dcs:
  postgresql:
    parameters:
      password_encryption: scram-sha-256
```
(For the sake of clarity, reduced to the least things.)

Logfile told us:
```
2020-06-09 19:13:49.194 UTC (pid=1196309, error=28P01, application=[unknown], user=postgres, database=postgres, session=5edfdf6d.124115, transaction=0) DETAIL:  User "postgres" does not have a valid SCRAM verifier.
```

Steps that have been taken afterwards to make it work:
```
postgres=# SELECT                                                                                                                                                                                     
    rolname, rolpassword ~ '^SCRAM-SHA-256\$' AS has_upgraded                                                                                                                                         
FROM pg_authid                                                                                                                                                                                        
WHERE rolcanlogin;                                                                                                                                                                                    
 rolname  | has_upgraded                                                                                                                                                                              
----------+--------------                                                                                                                                                                             
 postgres | f                                                                                                                                                                                         
(1 row)
postgres=# \password
Enter new password: 
Enter it again: 
postgres=# SELECT
    rolname, rolpassword ~ '^SCRAM-SHA-256\$' AS has_upgraded
FROM pg_authid
WHERE rolcanlogin;
 rolname  | has_upgraded 
----------+--------------
 postgres | t
(1 row)
```

I think we are missing something. :)

**Comment by CyberDem0n** [comment]
https://patroni.readthedocs.io/en/latest/SETTINGS.html#bootstrap-configuration

```yaml

initdb: # List options to be passed on to initdb.
        - data-checksums: # Must be enabled when pg_rewind is needed on 9.3.
        - encoding: UTF8: # default encoding for new databases.
        - locale: UTF8: # default locale for new databases.

```

You can add there any other options you like.
