### ISSUE TITLE
bootstrapping stuck

### ISSUE THREAD

**Issue by arnaud-mey** [zalando/patroni#1601]
I'm using patroni with the postgres operator on Kubernetes.

When I'm configuring it to use wal-e for wal shipping, patroni is configured like this:

```  
create_replica_method:
  - wal_e
  - basebackup_fast_xlog
basebackup_fast_xlog:
  command: /scripts/basebackup.sh
  retries: 2
```

which seems to cause the issue. If no create_replica_method is configured (and therefore the basebackup method is used), replication works fine.

The wal files are being correctly sent to my S3 bucket.

The follower produces these logs:

https://gist.github.com/arnaud-mey/2292146540b1da1bff895e03ee5dcf51

and the leader:

https://gist.github.com/arnaud-mey/e15b4b98221919448291be1414adc381
