### ISSUE TITLE
rest api basic auth configuration not working

### ISSUE THREAD

**Issue by ravishekhar88** [zalando/patroni#1602]
I configured basic auth username and password in postgresql.yml file as following:
```
restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.128.0.3:8008
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
  authentication:
    username: admin
    password: secret
```

After restarting the patroni service, I am hitting the /configure endpoint without the basic auth header only to get a 200 OK.
```
$ curl -i http://10.128.0.3:8008/config 
HTTP/1.0 200 OK
Server: BaseHTTP/0.6 Python/3.6.8
Date: Tue, 30 Jun 2020 16:38:32 GMT
Content-Type: application/json

{"loop_wait": 10, "maximum_lag_on_failover": 1048576, "postgresql": {"parameters": {"archive_command": "test ! -f /mnt/locatedb/archive/%f && cp %p /mnt/locatedb/archive/%f", "archive_mode": "on", "hot_standby": "on", "log_connections": "on", "log_disconnections": "on", "log_line_prefix": "%m [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h ", "log_timezone": "GMT", "max_replication_slots": 10, "max_wal_senders": 10, "pgaudit.log": "write, ddl", "pgaudit.log_catalog": "on", "pgaudit.log_parameter": "off", "pgaudit.log_relation": "on", "shared_preload_libraries": "pgaudit", "wal_level": "hot_standby", "wal_log_hints": "on"}, "use_pg_rewind": true, "use_slots": true}, "retry_timeout": 10, "ttl": 30}
```

I was expecting 401 unauthorized. What am I missing here?
