### ISSUE TITLE
Can't bootstrap standby

### ISSUE THREAD

**Issue by Thoro** [zalando/patroni#1610]
Hi, 

I'm trying to get familiar with Patroni and tried it with PG12.3 (custom image).

The master instance started without an issue, and seems to be working good, I'm using kubernetes endpoints and they are correctly created and updated.

When starting a standby, and running through the bootstrap process I get the following error output with LOG_LEVEL=DEBUG

```
2020-07-09 10:20:31,928 INFO: trying to bootstrap from leader 'patroni-test-db-0'
2020-07-09 10:20:31,928 ERROR: failed to bootstrap from leader 'patroni-test-db-0'
```

Which tells me nothing ... Is there a way how to figure out what's going wrong?

**Comment by CyberDem0n** [comment]
Have you checked postgres logs on the primary?

**Comment by Thoro** [comment]
yep, completely empty :(

```
2020-07-09 10:00:56.682 UTC [148] LOG:  entering standby mode
2020-07-09 10:00:56.697 UTC [152] FATAL:  the database system is starting up
2020-07-09 10:00:56.700 UTC [148] LOG:  consistent recovery state reached at 0/20000A0
2020-07-09 10:00:56.700 UTC [148] LOG:  invalid record length at 0/20000A0: wanted 24, got 0
2020-07-09 10:00:56.701 UTC [146] LOG:  database system is ready to accept read only connections
2020-07-09 10:00:56.824 UTC [148] LOG:  received promote request
2020-07-09 10:00:56.824 UTC [148] LOG:  redo is not required
2020-07-09 10:00:56.835 UTC [148] LOG:  selected new timeline ID: 2
2020-07-09 10:00:56.897 UTC [148] LOG:  archive recovery complete
2020-07-09 10:00:56.904 UTC [146] LOG:  database system is ready to accept connections
```

**Comment by CyberDem0n** [comment]
I am pretty sure there should be some evidence.
Also without seeing you config files it is hard (not possible to help).

**Comment by Thoro** [comment]
Here is the patroni config for the master:

```
scope: patroni-test-cluster
name: patroni-test-db-0

bootstrap:
  dcs:
    postgresql:
      use_pg_rewind: true
      parameters:
        wal_level: logical
        hot_standby: "on"
        wal_keep_segments: 64
        max_wal_senders: 10
        max_replication_slots: 10
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: "/bin/true"
      recovery_conf:
        restore_command: "/bin/true"
  initdb:
  - auth-host: md5
  - auth-local: trust
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums
  pg_hba:
  - host all all 10.253.0.0/16 md5
  - host replication postgres 10.253.0.0/16 md5

restapi:
  connect_address: '10.253.41.242:8008'

kubernetes:
  namespace: pgo
  use_endpoints: true

postgresql:
  listen: '0.0.0.0:5432'
  connect_address: '10.253.41.242:5432'
  data_dir: /data/pgsql/12/data
  bin_dir: /usr/pgsql-12/bin
  pgpass: /tmp/pgpass

  authentication:
    superuser:
      username: postgres
      password: postgres
    replication:
      username: postgres
      password: postgres
```

and for the slave:

```
scope: patroni-test-cluster
name: patroni-test-slave-db-0

bootstrap:
  dcs:
    postgresql:
      use_pg_rewind: true
      parameters:
        wal_level: logical
        hot_standby: "on"
        wal_keep_segments: 64
        max_wal_senders: 10
        max_replication_slots: 10
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: "/bin/true"
      recovery_conf:
        restore_command: "/bin/true"
  initdb:
  - auth-host: md5
  - auth-local: trust
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums
  pg_hba:
  - host all all 10.253.0.0/16 md5
  - host replication postgres 10.253.0.0/16 md5

restapi:
  connect_address: '10.253.10.95:8008'

kubernetes:
  namespace: pgo
  use_endpoints: true

postgresql:
  listen: '0.0.0.0:5432'
  connect_address: '10.253.10.95:5432'
  data_dir: /data/pgsql/12/data
  bin_dir: /usr/pgsql-12/bin
  pgpass: /tmp/pgpass

  authentication:
    superuser:
      username: postgres
      password: postgres
    replication:
      username: postgres
      password: postgres
```

Do you need any other configs? What else can I check?

**Comment by CyberDem0n** [comment]
Since there is no custom replica creation methods defined Patroni will use pg_basebackup.
If there is something wrong, pg_basebackup writes logs to stderr, something like below:
```
2020-07-09 15:37:31,226 INFO: trying to bootstrap from leader 'postgresql0'
pg_basebackup: error: could not connect to server: FATAL:  password authentication failed for user "replicator"
password retrieved from file "/tmp/pgpass1"
2020-07-09 15:37:31,235 ERROR: Error when fetching backup: pg_basebackup exited with code=1
2020-07-09 15:37:31,236 WARNING: Trying again in 5 seconds
pg_basebackup: error: could not connect to server: FATAL:  password authentication failed for user "replicator"
password retrieved from file "/tmp/pgpass1"
2020-07-09 15:37:36,274 ERROR: Error when fetching backup: pg_basebackup exited with code=1
2020-07-09 15:37:36,274 ERROR: failed to bootstrap from leader 'postgresql0'
```

I can only recommend to try to call pg_basebackup manually and see why it fails.

Can it be that memory limits is too low?

**Comment by Thoro** [comment]
There's no memory or cpu limits defined, why doesn't it log the call to pg_basebackup? (since I'm running it with DEBUG)

**Comment by CyberDem0n** [comment]
Something is fishy.
If Patroni is using custom replica creation method it explicitly tells about it: https://github.com/zalando/patroni/blob/master/patroni/postgresql/bootstrap.py#L103
Since there is nothing in logs - it is using the pg_basebackup, but... If pg_basebackup fails, Patroni explicitly complains about it and retries: https://github.com/zalando/patroni/blob/master/patroni/postgresql/bootstrap.py#L255-L263
In your logs there are no complaints and no retries.

Also you claim that endpoints working correctly, while in fact your config is not complete:
```
kubernetes:
  namespace: pgo
  use_endpoints: true
```

There are no `labels` and `pod_ip` defined. It seems that the config fully or partially is coming from the environment variables.

**Comment by Thoro** [comment]
yes, sorry those are coming from env vars:

```
  env:
        - name: PATRONI_KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: PATRONI_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PATRONI_KUBERNETES_LABELS
          value: '{application: patroni-test, cluster-name: patroni-test-cluster}'
        - name: PATRONI_SUPERUSER_USERNAME
          value: postgres
        - name: PATRONI_SUPERUSER_PASSWORD
          value: postgres
        - name: PATRONI_REPLICATION_USERNAME
          value: postgres
        - name: PATRONI_REPLICATION_PASSWORD
          value: postgres
        - name: PATRONI_SCOPE
          value: patroni-test-cluster
        - name: PATRONI_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: PATRONI_POSTGRESQL_DATA_DIR
          value: /data/pgsql/12/data
        - name: PATRONI_POSTGRESQL_PGPASS
          value: /tmp/pgpass
        - name: PATRONI_POSTGRESQL_LISTEN
          value: 0.0.0.0:5432
        - name: PATRONI_RESTAPI_LISTEN
          value: 0.0.0.0:8008
```
