### ISSUE TITLE
standby_cluster is considered as replica

### ISSUE THREAD

**Issue by bukem** [zalando/patroni#1617]
Hi,
I have a cluster with Leader and 2 replicas. I want to add standby node to this deployment, so I prepared the following config before starting patroni on the 4th node:
```
scope: testcluster
name: stdb-node-345032702

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.38.48.138:8008

consul:
  register_service: true
  host: 127.0.0.1:8500
  checks: []

bootstrap:
  dcs:
    standby_cluster:
      host: master.testcluster.service.dc.consul
      post: 5432

  users:
    replicator:
      password: passwordhere
      options:
        - replication

postgresql:
...

log:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "process": %(process)d, "thread": %(thread)d, "level": "%(levelname)s", "message": "%(message)s"}'

```

But when I start patroni, the node joins as `replica`, while I expect it to be `standby_leader`:
```
Jul 21 09:58:33 stdb-node-345032702 patroni[29177]: {"time": "2020-07-21 09:58:33,886", "name": "patroni.dcs.consul", "process": 29177, "thread": 139955463599936, "level": "INFO", "message": "Register service testcluster, params {'service_id': 'testcluster/stdb-node-345032702', 'address': '10.38.48.226', 'port': 5432, 'check': {'http': 'http://10.38.48.138:8008/replica', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['replica']}"}
```

Config from leader node:
```
scope: testcluster
name: patroni-cluster-345032702

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.38.48.226:8008

consul:
  register_service: true
  host: 127.0.0.1:8500
  checks: []

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        archive_mode: "on"
...
        work_mem: "8MB"
      recovery_conf:
        restore_command: /bin/true
  initdb:
    - encoding: UTF8
    - data-checksums
    - locale: en_US.UTF-8
    - lc-collate: en_US.UTF-8
    - lc-ctype: en_US.UTF-8

  users:
    replicator:
      password: passwordhere
      options:
        - replication

postgresql:
...

watchdog:
  mode: off

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "process": %(process)d, "thread": %(thread)d, "level": "%(levelname)s", "message": "%(message)s"}'

```

Can you tell what am I doing wrong? According to the sources, the node should be considered as standby-cluster if standby_cluster is set and (host or port or restore_command) are defined - https://github.com/zalando/patroni/blob/master/patroni/utils.py#L400 , but in my case it's not enough.

Thank you!

**Comment by CyberDem0n** [comment]
The standby cluster either MUST use a different DCS or a different scope.
In your case scope is the same, therefore it joins as a replica to the existing cluster.

**Comment by bukem** [comment]
Okay, I made the following changes for standby config:
- changed the `scope` name
- added `bootstrap.initdb` to be the same as on the leader node

Now, when I start patroni on standby node it stays on `"level": "INFO", "message": "bootstrap_standby_leader in progress"`
 forever.

The interesting thing in journal is that the process expects for some password:
```
Jul 22 08:29:09 stdb-node-345032702 patroni[30960]: {"time": "2020-07-22 08:29:09,943", "name": "patroni", "process": 30960, "thread": 139965531764544
Jul 22 08:29:09 stdb-node-345032702 patroni[30960]: Password:
Jul 22 08:29:09 stdb-node-345032702 patroni[30960]: Password:
Jul 22 08:29:09 stdb-node-345032702 patroni[30960]: Password:
...
```
Which is strange, since postgresql.authentication.replication is filled and I expect this to be used by replicas to access the leader (according to https://patroni.readthedocs.io/en/latest/SETTINGS.html#bootstrap-configuration)

I extracted the command that was used for backup and executed it outside the patroni with the password from config file and the backup successfully completed:
```
$ ps fax
30812 ?        Ssl    0:01 /usr/bin/python3.6 /usr/local/bin/patroni /etc/postgresql.yml
30860 ?        S      0:26  \_ /usr/pgsql-11/bin/pg_basebackup --pgdata=/var/lib/pgsql/11/data -X stream --dbname=dbname=postgres user=replicator host=master.testcluster.service.dc.consul port= --verbose --checkpoint=fast



$ /usr/pgsql-11/bin/pg_basebackup --pgdata=/var/lib/pgsql/11/data -X stream --dbname='dbname=postgres user=replicator host=master.testcluster.service.dc.consul port=' --verbose --checkpoint=fast
Password:
pg_basebackup: initiating base backup, waiting for checkpoint to complete
pg_basebackup: checkpoint completed
pg_basebackup: write-ahead log start point: 6/C7000028 on timeline 2
pg_basebackup: starting background WAL receiver
pg_basebackup: created temporary replication slot "pg_basebackup_7765"
pg_basebackup: write-ahead log end point: 6/C7000130
pg_basebackup: waiting for background process to finish streaming ...
pg_basebackup: base backup completed

```

What could be the reason why the password from `postgresql.authentication.replication` is not used?

The last version of standby node's config:
```
scope: testcluster_ro
name: stdb-node-345032702

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.38.48.138:8008

consul:
  register_service: true
  host: 127.0.0.1:8500
  checks: []

bootstrap:
  dcs:
    standby_cluster:
      host: master.testcluster.service.dc.consul
      post: 5432

  initdb:
    - encoding: UTF8
    - data-checksums
    - locale: en_US.UTF-8
    - lc-collate: en_US.UTF-8
    - lc-ctype: en_US.UTF-8

  users:
    replicator:
      password: reppasswordhere
      options:
        - replication

postgresql:
  listen: '*'
  connect_address: 10.38.48.138:5432
  data_dir: /var/lib/pgsql/11/data
  bin_dir: /usr/pgsql-11/bin
  config_dir: /var/lib/pgsql/11/data
  hba_file: /var/lib/pgsql/11/data/pg_hba.conf
  restore: /usr/bin/patroni_wale_restore
  pgpass: /tmp/pgpass
  authentication:
    pg_rewind:
      username: postgres
      password: pgpasswordhere
    replication:
      username: replicator
      password: reppasswordhere
    superuser:
      username: postgres
      password: pgpasswordhere
  basebackup:
    - verbose
    - checkpoint: 'fast'

log:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "process": %(process)d, "thread": %(thread)d, "level": "%(levelname)s", "message": "%(message)s"}'
```

Thank you!

**Comment by CyberDem0n** [comment]
Password is supposed to be written to `  pgpass: /tmp/pgpass`.

**Comment by bukem** [comment]
pgpass is there and is generated by patroni based on config:
```
$ cat /tmp/pgpass
master.testcluster.service.dc.consul::*:replicator:reppasswordhere
```

The problem comes from the port - for some reason it is not set in pgpass.
```
PGPASSFILE=/tmp/pgpass psql "replication=true" -h master.testcluster.service.dc.consul -U replicator -c "IDENTIFY_SYSTEM
;"
Password for user replicator:
```

When I manually change /tmp/pgpass and set port from config, it works perfectly:
```
$ cat /tmp/pgpass
master.testcluster.service.dc.consul:5432:*:replicator:reppasswordhere

$ PGPASSFILE=/tmp/pgpass psql "replication=true" -h master.testcluster.service.dc.consul -U replicator -c "IDENTIFY_SYSTEM;"
      systemid       | timeline |  xlogpos   | dbname
---------------------+----------+------------+--------
 6849280110486734823 |        2 | 6/C9000108 |
```

Is it a bug?

**Comment by CyberDem0n** [comment]
Yes, bug.
But there is also typo in your configuration:
```
bootstrap:
  dcs:
    standby_cluster:
-      post: 5432
+      port: 5432
```

**Comment by bukem** [comment]
Oh... my fault :disappointed:

@CyberDem0n thanks a lot!

Can I close the issue or you plan to do something within it?

**Comment by bukem** [comment]
I have one more question, now about how to set the parameters for standby cluster. I have the following bootstrap config:
```
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    standby_cluster:
      host: master.testcluster.service.dc.consul
      port: 5432
      use_pg_rewind: true
      use_slots: false
      parameters:
        max_standby_streaming_delay: 1h
```

And expect to have `max_standby_streaming_delay = 1h` in postgresql.conf, but after bootstrap the config contains only default parameters:
```
$ cat /var/lib/pgsql/11/data/postgresql.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
include 'postgresql.base.conf'

cluster_name = 'testcluster_ro'
hot_standby = 'on'
listen_addresses = '*'
max_connections = '1000'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '10'
max_worker_processes = '8'
port = '5432'
track_commit_timestamp = 'off'
wal_keep_segments = '8'
wal_level = 'replica'
wal_log_hints = 'on'
hba_file = '/var/lib/pgsql/11/data/pg_hba.conf'
ident_file = '/var/lib/pgsql/11/data/pg_ident.conf'
```

And for some reason the node has `Pending restart=true` from the start:
```
$ patronictl -c /etc/postgresql.yml list
2020-07-24 04:46:48,500 - WARNING - Using testcluster-ro as consul service name instead of scope name testcluster_ro
+----------------+---------------------+--------------+----------------+---------+----+-----------+-----------------+
|   Cluster      |     Member          |     Host     |      Role      |  State  | TL | Lag in MB | Pending restart |
+----------------+---------------------+--------------+----------------+---------+----+-----------+-----------------+
| testcluster_ro | stdb-node-345032702 | 10.38.48.138 | Standby Leader | running |  2 |           |        *        |
+----------------+---------------------+--------------+----------------+---------+----+-----------+-----------------+
```

Restart makes no difference:
```
$ patronictl -c /etc/postgresql.yml restart testcluster_ro stdb-node-345032702
2020-07-24 04:51:08,501 - WARNING - Using testcluster-ro as consul service name instead of scope name testcluster_ro
+----------------+---------------------+--------------+----------------+---------+----+-----------+-----------------+
|   Cluster      |     Member          |     Host     |      Role      |  State  | TL | Lag in MB | Pending restart |
+----------------+---------------------+--------------+----------------+---------+----+-----------+-----------------+
| testcluster_ro | stdb-node-345032702 | 10.38.48.138 | Standby Leader | running |  2 |           |        *        |
+----------------+---------------------+--------------+----------------+---------+----+-----------+-----------------+
When should the restart take place (e.g. 2020-07-24T05:51)  [now]:
Are you sure you want to restart members stdb-node-345032702? [y/N]: y
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2)  []:
Success: restart on member stdb-node-345032702


$ patronictl -c /etc/postgresql.yml list
2020-07-24 04:52:55,810 - WARNING - Using testcluster-ro as consul service name instead of scope name testcluster_ro
+----------------+---------------------+--------------+----------------+---------+----+-----------+-----------------+
|   Cluster      |     Member          |     Host     |      Role      |  State  | TL | Lag in MB | Pending restart |
+----------------+---------------------+--------------+----------------+---------+----+-----------+-----------------+
| testcluster_ro | stdb-node-345032702 | 10.38.48.138 | Standby Leader | running |  2 |           |        *        |
+----------------+---------------------+--------------+----------------+---------+----+-----------+-----------------+
```


Changing the parameter value with `edit-config` has no effect either:
```
# patronictl -c /etc/postgresql.yml edit-config
2020-07-24 04:54:45,179 - WARNING - Using testcluster-ro as consul service name instead of scope name testcluster_ro
---
+++
@@ -3,7 +3,7 @@
 standby_cluster:
   host: master.testcluster.service.dc.consul
   parameters:
-    max_standby_streaming_delay: 1h
+    max_standby_streaming_delay: 50min
   port: 5432
   use_pg_rewind: true
   use_slots: false

Apply these changes? [y/N]: y
Configuration changed

$ grep max_standby_streaming_delay /var/lib/pgsql/11/data/postgresql.conf
    << no result here >>

```

Information from postgres log:
```
2020-07-24 04:55:15.652 UTC [16478] LOG:  received SIGHUP, reloading configuration files
2020-07-24 04:55:15.653 UTC [16478] LOG:  parameter "max_connections" cannot be changed without restarting the server
2020-07-24 04:55:15.653 UTC [16478] LOG:  configuration file "/var/lib/pgsql/11/data/postgresql.conf" contains errors; unaffected changes were applied
```

Which is strange as far as max_connections is already set to 1000 (the value from `postgresql.conf`):
```
$ psql -c "show max_connections";
 max_connections
-----------------
 1000
```

When I set this value in `postgresql.parameters` section it has effect:
```
postgresql:
...
  parameters:
    max_standby_streaming_delay: 1h
```

```
$ grep max_standby_streaming_delay /var/lib/pgsql/11/data/postgresql.conf
max_standby_streaming_delay = '1h'

```

But then we have another problem - it is not possible to change the value via DCS:
```
$ patronictl -c /etc/postgresql.yml edit-config
2020-07-24 05:22:45,498 - WARNING - Using testcluster-ro as consul service name instead of scope name testcluster_ro
---
+++
@@ -3,7 +3,7 @@
 standby_cluster:
   host: master.testcluster.service.dc.consul
   parameters:
-    max_standby_streaming_delay: 1h
+    max_standby_streaming_delay: 50min
   port: 5432
   use_pg_rewind: true
   use_slots: false

Apply these changes? [y/N]: y
Configuration changed

    << wait for 30 seconds >>

$ grep max_standby_streaming_delay /var/lib/pgsql/11/data/postgresql.conf
max_standby_streaming_delay = '1h'

```

In connection with the above, I have a few questions:

1. Am I right in assuming that bootstrap parameters for standby_cluster doesn't affect postgresql.conf, but are passed to DCS key-value storage?
2. Is there a way to set custom values for parameters on standby_cluster during the deploy and still be able to change their values using DCS KeyValue storage or using `edit-config` (which is equivalent if I understand correctly) ?
3. `max_connections` value is taken from the primary cluster configuration to be the same on Leader and standby_cluster? This probably applies to all the parameters that _must hold the same values on the master and the replicas_ mentioned in https://github.com/zalando/patroni/blob/master/docs/dynamic_configuration.rst#patroni-configuration .
4. If 3. is correct, could that be the reason for having "Pending restart = true" ? And if yes, isn't it wrong to have 1000 in both, config and database, but still show that the node is pending restart?
