### ISSUE TITLE
REST API security configuration

### ISSUE THREAD

**Issue by zelgo-dba** [zalando/patroni#1689]
Hi
I configured tls configuration as:
```
 restapi:
    listen: 1.2.3.4:8008
    connect_address: 1.2.3.4:8008
    cert: /etc/ssl/patroni/pg1.example.com.pem
    key: /etc/ssl/patroni/pg1.example.com.pem
    cacert: /etc/ssl/patroni/rootCA.pem
    verify_client: required
```
but after restarting the patroni service, I see:
```
[root@pg1] $  curl -s http://pg1.example.com:8008/config | jq .
{
  "loop_wait": 5,
  "maximum_lag_on_failover": 1048576,
  "postgresql": {
    "parameters": {
      "max_connections": "102",
      "synchronous_commit": true,
      "synchronous_standby_names": "*"
    },
    "use_pg_rewind": true,
    "use_slots": true
  },
  "retry_timeout": 10,
  "ttl": 20
}
```
Why not error 401?
