### ISSUE TITLE
RAFT failed to update leader lock

### ISSUE THREAD

**Issue by alexeymyltsev** [zalando/patroni#1701]
On Ubuntu 20.04 or 18.04 after some hours after installation leader in raft stuck with error "failed to update leader lock".

patroni 2.0.0 
pysyncobj 0.3.6
PostgreSQL 12.4-1.pgdg18.04+1

[patroni.conf](https://pastebin.com/xCTdUtns)

[patroni.log](https://pastebin.com/jY2kifJ7)

[postgresql.log](https://pastebin.com/L6Zzs0bc)

**Comment by CyberDem0n** [comment]
That means quorum is lost.

```yaml
raft:
  self_addr: 10.203.96.174:4321
  partner_addrs: ['10.203.96.177:4321','10.203.96.181:4321','10.203.96.174:4321']
```

Why have you added `self_addr` to the `partner_addrs`?
