### ISSUE TITLE
replication not working

### ISSUE THREAD

**Issue by catadetest** [zalando/patroni#1710]
**Describe the bug**
Did the installation of petroni, cluster is healthy, node1 leader, node2 replica, however replication is not working.

**To Reproduce**
create a new db named "test" on node 1

**Expected behavior**
the new db named "test" should be available on node 2 as well

**Screenshots**
![image](https://user-images.githubusercontent.com/25132800/93776538-513e0100-fc2c-11ea-852e-34975ac9a439.png)
![image](https://user-images.githubusercontent.com/25132800/93776598-631fa400-fc2c-11ea-89de-6f138e8d9783.png)
![image](https://user-images.githubusercontent.com/25132800/93776634-6f0b6600-fc2c-11ea-9e54-d1dabce3926b.png)

**Environment**
- Patroni version: 2.0.0
- PostgreSQL version: 9.5
- DCS (and its version):

**Patroni configuration file**
```
scope: postgres
namespace: /db/
name: postgre1

restapi:
    listen: 10.166.0.6:8008
    connect_address: 10.166.0.6:8008

etcd:
    host: 10.166.0.8:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.166.0.6/0 md5
    - host replication replicator 10.166.0.7/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 10.166.0.6:5432
    connect_address: 10.166.0.6:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: password
        superuser:
            username: postgres
            password: password
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false```
```
**patronictl show-config**

root@ubuntu-intance-1:~# patronictl show-config
2020-09-21 14:06:54,237 - WARNING - /usr/local/lib/python3.5/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release ofcryptography. Please upgrade your Python.
  from cryptography import x509

Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: etcd, etcd3, kubernetes'
```

**Have you checked Patroni logs?**
no logs

**Have you checked PostgreSQL logs?**
2020-09-21 12:56:52 UTC [4782-1] LOG:  database system was shut down at 2020-09-21 12:56:51 UTC
2020-09-21 12:56:52 UTC [4782-2] LOG:  MultiXact member wraparound protections are now enabled
2020-09-21 12:56:52 UTC [4773-1] LOG:  database system is ready to accept connections
2020-09-21 12:56:52 UTC [4786-1] LOG:  autovacuum launcher started
2020-09-21 12:56:53 UTC [4788-1] [unknown]@[unknown] LOG:  incomplete startup packet
2020-09-21 12:57:14 UTC [4773-2] LOG:  received fast shutdown request
2020-09-21 12:57:14 UTC [4773-3] LOG:  aborting any active transactions
2020-09-21 12:57:14 UTC [4786-2] LOG:  autovacuum launcher shutting down
2020-09-21 12:57:14 UTC [4783-1] LOG:  shutting down
2020-09-21 12:57:14 UTC [4783-2] LOG:  database system is shut down
2020-09-21 13:13:55 UTC [12854-1] LOG:  database system was shut down at 2020-09-21 12:57:14 UTC
2020-09-21 13:13:55 UTC [12854-2] LOG:  MultiXact member wraparound protections are now enabled
2020-09-21 13:13:55 UTC [12853-1] LOG:  database system is ready to accept connections
2020-09-21 13:13:55 UTC [12858-1] LOG:  autovacuum launcher started
2020-09-21 13:13:55 UTC [12860-1] [unknown]@[unknown] LOG:  incomplete startup packet
2020-09-21 13:14:37 UTC [12853-2] LOG:  received fast shutdown request
2020-09-21 13:14:37 UTC [12853-3] LOG:  aborting any active transactions
2020-09-21 13:14:37 UTC [12858-2] LOG:  autovacuum launcher shutting down
2020-09-21 13:14:37 UTC [12855-1] LOG:  shutting down
2020-09-21 13:14:37 UTC [12855-2] LOG:  database system is shut down
2020-09-21 13:14:51 UTC [13176-1] LOG:  database system was shut down at 2020-09-21 13:14:37 UTC
2020-09-21 13:14:51 UTC [13176-2] LOG:  MultiXact member wraparound protections are now enabled
2020-09-21 13:14:51 UTC [13175-1] LOG:  database system is ready to accept connections
2020-09-21 13:14:51 UTC [13180-1] LOG:  autovacuum launcher started
2020-09-21 13:14:52 UTC [13182-1] [unknown]@[unknown] LOG:  incomplete startup packet

**Have you tried to use GitHub issue search?**
yes, but did not find similar issue


**Additional context**
Add any other context about the problem here.
I like this software, cause is simple. However not sure how to make the replication to work.
Thanks!
