### ISSUE TITLE
patronictl edit-config --apply/replace does not work If the options changed are not part of the startup configuration

### ISSUE THREAD

**Issue by adiospeds** [zalando/patroni#1711]
**Describe the bug**
DCS options not getting applied if *ADDED* later

**To Reproduce**
I created a 3 node patroni cluster with below config which came up completely fine:

show-config returns this:
```
/usr/bin/patronictl -c /etc/patroni/config.yml show-config
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
ttl: 30
```
With default config the max connections were set to 100 in postgres:
```
postgres@ubuntu1804-14:~$ psql -c 'show max_connections;'
 max_connections
-----------------
 100
(1 row)
```

Then I create a file: 
```
root@ubuntu1804-14:~# cat /etc/patroni/patroni_dcs.conf
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 500000
postgresql:
  parameters:
    max_connections: 200
    max_locks_per_transaction: 64
    max_worker_processes: 8
    max_prepared_transactions: 0
    wal_level: replica
    wal_log_hints: on
    track_commit_timestamp: off
    max_wal_senders: 10
    max_replication_slots: 10
    wal_keep_segments: 64
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
ttl: 30
```

and then applied this dcs config (The reason for applying thru seperate file is bcas I want to automate this part with puppet.)
`/usr/bin/patronictl -c /etc/patroni/config.yml edit-config --apply /etc/patroni/patroni_dcs.conf --force`
even tried `replace` with fresh cluster.
`/usr/bin/patronictl -c /etc/patroni/config.yml edit-config --replace /etc/patroni/patroni_dcs.conf --force`

The DCS gets updated, and I am able to see the changes applied with show config. However the pending restart flag never show's up. And even If I force restart postgres as patroni - still the changes are not applied even though they are in the dcs.

```
postgres@ubuntu1804-14:~$ psql -c 'show max_connections;'
 max_connections
-----------------
 100
(1 row)

postgres@ubuntu1804-14:~$ logout
root@ubuntu1804-14:~# patronictl -c /etc/patroni/config.yml show-config
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 500000
postgresql:
  parameters:
    max_connections: 20
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    track_commit_timestamp: false
    wal_keep_segments: 64
    wal_level: replica
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
ttl: 30

root@ubuntu1804-14:~# patronictl -c /etc/patroni/config.yml list
+ Cluster: dbatest-12 (6875209418916196036) --+--------+---------+----+-----------+
|     Member    |             Host            |  Role  |  State  | TL | Lag in MB |
+---------------+-----------------------------+--------+---------+----+-----------+
| ubuntu1804-12 | ubuntu1804-12.vagrant.local |        | running |  1 |         0 |
| ubuntu1804-13 | ubuntu1804-13.vagrant.local | Leader | running |  1 |           |
| ubuntu1804-14 | ubuntu1804-14.vagrant.local |        | running |  1 |         0 |
+---------------+-----------------------------+--------+---------+----+-----------+
```

**Expected behavior**
As per statement in https://patroni.readthedocs.io/en/latest/dynamic_configuration.html

> These options can be set in DCS at any time. If the options changed are not part of the startup configuration, they are applied asynchronously (upon the next wake up cycle) to every node, which gets subsequently reloaded. 

The max_connections was not a part of the startup config and after applying it via file - Patroni shud had triggered the pending restart flag however it does not and will not let me change the max_connections and other settings.

**Environment**
- Patroni version: 1.6.5
- PostgreSQL version: 12.4-1.pgdg18.04+1
- DCS (and its version): Consul - 1.7.3

**Patroni Config file**:
```
root@ubuntu1804-13:~# cat /etc/patroni/config.yml
scope: dbatest-12
namespace: /postgresql-12/
name: ubuntu1804-13

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
  method: initdb
  initdb:
    - data-checksums
    - encoding: UTF-8
    - locale: en_US.UTF-8
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication rep_user 0.0.0.0/0 md5

postgresql:
  listen: 0.0.0.0:5432
  connect_address: ubuntu1804-13.vagrant.local:5432
  data_dir: /var/lib/postgresql/12/main
  bin_dir: /usr/lib/postgresql/12/bin
  config_dir: /etc/postgresql/12/main
  use_unix_socket: true
  pgpass: /var/lib/postgresql/.pgpass
  pg_ctl_timeout: 60
  use_pg_rewind: true
  remove_data_directory_on_rewind_failure: false
  authentication:
    superuser:
      username: postgres
      password: xxx
    replication:
      username: replicator
      password: xxx
  create_replica_methods:
    - basebackup
  pg_hba:
    - local   all              postgres                                ident
    - local   all              all                                     ident
    - host    all              postgres                127.0.0.1/32    md5
    - host    all              postgres                0.0.0.0/0       md5
    - host    all              all                     127.0.0.1/32    md5
    - host    all              all                     ::1/128         md5
    - host    all              monitor         127.0.0.1/32    md5
    - host    replication      replicator     0.0.0.0/0       md5
  parameters:
    shared_preload_libraries: pg_stat_statements
    autovacuum_analyze_scale_factor: 0.05
    autovacuum_vacuum_scale_factor: 0.1
    max_stack_depth: 2MB
    work_mem: 4MB
    temp_buffers: 32MB
    shared_buffers: 1GB
    max_wal_size: 1GB
    maintenance_work_mem: 256MB
    effective_cache_size: 4GB
    log_min_duration_statement: 10000
    logging_collector: on
    log_destination: stderr
    log_directory: /var/log/postgresql
    log_connections: on
    log_disconnections: on
    log_checkpoints: on
    log_lock_waits: on
    log_line_prefix: user=%u,db=%d,app=%a,client=%h

restapi:
  listen: 172.16.8.13:8008
  connect_address: ubuntu1804-13.vagrant.local:8008
  authentication:
    username: otadmin
    password: xxx

watchdog:
  mode: off
  device: /dev/watchdog
  safety_margin: 5

consul:
  host: localhost
  port: 8500
  scheme: http
  verify: false
  token: xxx
  register_service: true
```

**Have you checked Patroni logs?**
Found nothing significant

**Have you checked PostgreSQL logs?**
Found nothing significant

**Have you tried to use GitHub issue search?**
Yes, No matches

**Additional context**
If I change the max_connection value (or any other values) in `/etc/patroni/patroni_dcs.conf` and apply it once again (2nd time) they get applied and the restart pending flag comes. *But not at the first time.*
