### ISSUE TITLE
patronictl  no auth header received

### ISSUE THREAD

**Issue by major-sam** [zalando/patroni#1714]
descr:
Failed: reload for member dc-pg-node2, status code=401, (no auth header received)
on patronictl reload/reinit/restart/failover....

**To Reproduce**

**Environment**

- Patroni version: 2.0.0
- PostgreSQL version:  PostgreSQL 12.3
- DCS (and its version): etcd Version: 3.3.11

**Patroni configuration file**
```

name: dc-pg-node2
namespace: /db/
scope: postgres
restapi:
 listen: 0.0.0.0:8008
 connect_address: dc-pg-node2:8008
 authentication:
   username: patroni
   password: patroni
log:
 level: DEBUG
 dir: '/var/log/patroni/'
etcd:
 host: localhost:2379
 username: root
 password: PASSWD
bootstrap:
 dcs:
  ttl: 30
  loop_wait: 10
  retry_timeout: 10
  maximum_lag_on_failover: 1048576
  master_start_timeout: 300
  postgresql:
   use_pg_rewind: true
   use_slots: true
   parameters:
    wal_level: replica
    hot_standby: "on"
    wal_keep_segments: 8
    max_wal_senders: 5
    max_replication_slots: 5
    checkpoint_timeout: 30
 initdb:
 - auth-host: md5
 - auth-local: peer
 - encoding: UTF8
 - data-checksums
 - locale: ru_RU.UTF-8
 pg_hba:
 - host all all samenet md5
 - host replication replicator samenet md5
 - host replication all 127.0.0.1/32 md5
 - host replication all ::1/128 md5
 users:
  app1c:
    password: PASSWD
    options:
    - superuser
postgresql:
 listen: 0.0.0.0:5432
 connect_address: dc-pg-node2:5432
 config_dir: /var/lib/pgsql/12/data
 bin_dir: /usr/pgsql-12/bin/
 data_dir: /var/lib/pgsql/12/data
 pgpass: /tmp/pgpass
 authentication:
   superuser:
     username: postgres
     password: PASSWD
   replication:
     username: replicator
     password: PASSWD
   rewind:
     username: rewind_user
     password: PASSWD
 parameters:
  unix_socket_directories: '/var/run/postgresql/'

```
**patronictl show-config**
```

master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    checkpoint_timeout: 30
    hot_standby: 'on'
    max_replication_slots: 5
    max_wal_senders: 5
    wal_keep_segments: 8
    wal_level: replica
  use_pg_rewind: true
  use_slots: true
restapi:
  authentication:
    password: patroni
    username: patroni
retry_timeout: 10
ttl: 30

```
**Have you checked Patroni logs?**

2020-09-24 07:47:30,575 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-09-24 07:47:30,667 DEBUG: http://dc-pg-node1:2379 "GET /v2/keys/db/postgres/leader?wait=true&waitIndex=55941 HTTP/1.1" 200 None
2020-09-24 07:47:32,502 DEBUG: API thread: 172.16.0.230 - - "OPTIONS / HTTP/1.0" 503 - latency: 1.254 ms
2020-09-24 07:47:35,504 DEBUG: API thread: 172.16.0.230 - - "OPTIONS / HTTP/1.0" 503 - latency: 1.245 ms
2020-09-24 07:47:38,507 DEBUG: API thread: 172.16.0.230 - - "OPTIONS / HTTP/1.0" 503 - latency: 1.247 ms
2020-09-24 07:47:40,353 DEBUG: Issuing read for key /db/postgres/ with args {'recursive': True, 'retry': <patroni.utils.Retry object at 0x7f8a1ecea160>}
2020-09-24 07:47:40,353 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-09-24 07:47:40,445 DEBUG: http://dc-pg-node1:2379 "GET /v2/keys/db/postgres/?recursive=true HTTP/1.1" 200 None
2020-09-24 07:47:40,447 INFO: Lock owner: dc-pg-node3; I am dc-pg-node1
2020-09-24 07:47:40,447 INFO: does not have lock
2020-09-24 07:47:40,448 DEBUG: Writing {"conn_url":"postgres://dc-pg-node1:5432/postgres","api_url":"http://dc-pg-node1:8008/patroni","state":"running","role":"replica","version":"2.0.0","tags":{"osync":false},"xlog_location":84041856,"timeline":2} to key /db/postgres/members/dc-pg-node1 ttl=30 dir=False append=False
2020-09-24 07:47:40,448 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-09-24 07:47:40,543 DEBUG: http://dc-pg-node1:2379 "PUT /v2/keys/db/postgres/members/dc-pg-node1 HTTP/1.1" 200 812
2020-09-24 07:47:40,543 INFO: no action.  i am a secondary and i am following a leader
2020-09-24 07:47:40,543 DEBUG: About to wait on key /db/postgres/leader, index 55945
2020-09-24 07:47:40,543 DEBUG: Issuing read for key /db/postgres/leader with args {'wait': True, 'waitIndex': 55945, 'timeout': 10.309556245803833, 'recursive': None}
2020-09-24 07:47:40,543 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2020-09-24 07:47:40,636 DEBUG: http://dc-pg-node1:2379 "GET /v2/keys/db/postgres/leader?wait=true&waitIndex=55945 HTTP/1.1" 200 None
2020-09-24 07:47:41,511 DEBUG: API thread: 172.16.0.230 - - "OPTIONS / HTTP/1.0" 503 - latency: 1.237 ms

**Have you checked PostgreSQL logs?**
Logs on russian, sorry, but seems psql is ok, logining peer\md5 is ok, create\remove\bakup and replication is works fine, but becouse small wal_keep_segments, 100+MB lag recovers by pg_basebackup 

**Have you tried to use GitHub issue search?**
https://github.com/zalando/patroni/issues/186  says that restapi username and password must be configured for auth headers sending

**Comment by CyberDem0n** [comment]
Magic doesn't exist. You have to compare credentials in the patroni config between `dc-pg-node2` and config which is used by patronictl.

**Comment by major-sam** [comment]
you mean rest_api auth?
its a same:
```cat .config/patroni/patronictl.yaml
dcs_api:
 etcd://localhost:2379
namespace: /db/
scope: postgres
authentication:
 username: patroni
 password: patroni
rest_api:    # even add this to be shure
 authentication:
  username: patroni
  password: patroni```

**Comment by CyberDem0n** [comment]
You have to use the same config as for Patroni. That's it.

**Comment by major-sam** [comment]
yeap!
thank you. 
` patronictl  -c /etc/patroni/patroni.yml `
 works
```
patronictl  -c /etc/patroni/patroni.yml show-configmaster_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    checkpoint_timeout: 30
    hot_standby: 'on'
    max_replication_slots: 5
    max_wal_senders: 5
    wal_keep_segments: 8
    wal_level: replica
  use_pg_rewind: true
  use_slots: true
restapi:
  authentication:
    password: patroni
    username: patroni
retry_timeout: 10
ttl: 30
```
but config still looks the same
