### ISSUE TITLE
Patronictl in docker service container issue

### ISSUE THREAD

**Issue by creepymorties** [zalando/patroni#1751]
**Describe the bug**
The issue is the same as it was mentioned here #1652
In docker swarm setup patroni gets connected to zookeeper but patronictl fails to get connected to zookeeper
It is tested from inside the docker container created by patroni service. 

**Expected behavior**
Patronictl to work within the container which is running patroni service. 

**Environment**
- Patroni version: latest
- PostgreSQL version: 11
- DCS (and its version): zookeeper 3.4

**Patroni configuration file**
```
scope: patroni
namespace: /service/

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    postgresql:
      use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication all all md5
    - host all all all md5

zookeeper:
  hosts: 
      - zoo1:2181
      - zoo2:2181
      - zoo3:2181

postgresql:
    data_dir: /data/patroni
    bin_dir: /usr/lib/postgresql/11/bin
    pgpass: /tmp/pgpass
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```
```
version: "3.4"

networks:
    patroni_patroni: 
        external: true
services:
    patroni1:
        image: patroni-test
        networks: [ patroni_patroni ]
        ports:
            - 5441:5432
            - 8091:8091
        hostname: patroni1
        volumes:
          - /patroni/patroni1:/data/patroni
        environment:
            PATRONI_API_CONNECT_PORT: 8091
            REPLICATION_NAME: replicator 
            REPLICATION_PASS: replpass
            SU_NAME: postgres
            SU_PASS: supass
            POSTGRES_APP_ROLE_PASS: appass
        deploy:
          replicas: 1
          placement:
            constraints: [node.hostname == node1]

    patroni2:
        image: patroni-test
        networks: [ patroni_patroni ]
        ports:
            - 5442:5432
            - 8092:8091
        hostname: patroni2
        volumes:
          - /patroni/patroni2:/data/patroni
        environment:
            PATRONI_API_CONNECT_PORT: 8091
            REPLICATION_NAME: replicator 
            REPLICATION_PASS: replpass
            SU_NAME: postgres
            SU_PASS: supass
            POSTGRES_APP_ROLE_PASS: appass
        deploy:
          replicas: 1
          placement:
            constraints: [node.hostname == node1]


    patroni3:
        image: patroni-test
        networks: [ patroni_patroni ]
        ports:
            - 5443:5432
            - 8093:8091
        hostname: patroni3
        volumes:
          - /patroni/patroni3:/data/patroni
        environment:
            PATRONI_API_CONNECT_PORT: 8091
            REPLICATION_NAME: replicator 
            REPLICATION_PASS: replpass
            SU_NAME: postgres
            SU_PASS: supass
            POSTGRES_APP_ROLE_PASS: appass
        deploy:
          replicas: 1
          placement:
            constraints: [node.hostname == node1]

```

**Have you checked Patroni logs?**

``` 
docker ps

4a7e75ba0bd6        patroni-test:latest   "bin/sh /entrypoint.…"   33 minutes ago      Up 33 minutes       5432/tcp                       patroni_patroni3.1.21mxt72ylxitl0yf3bjoaq0je

docker exec -ti 4a7e75ba0bd6 /bin/bash
--

postgres@patroni3:/$ patronictl history
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: exhibitor, kubernetes, zookeeper' 

```
patroni service logs 
```
patroni_patroni3.1.21mxt72ylxit@floitet    | 2020-11-10 09:10:49,957 INFO: Lock owner: patroni1; I am patroni3
patroni_patroni3.1.21mxt72ylxit@floitet    | 2020-11-10 09:10:49,957 INFO: does not have lock
patroni_patroni3.1.21mxt72ylxit@floitet    | 2020-11-10 09:10:49,958 INFO: no action.  i am a secondary and i am following a leader

```

**Additional context**
Patroni itself is working which means that it has connection to zookeeper.
