### ISSUE TITLE
Change watchdog parameters on a running cluster

### ISSUE THREAD

**Issue by zorgan** [zalando/patroni#1753]
When trying to disable watchdog using patronictl, i get the following:
```
patroni[1103]: 2020-11-11 09:09:18,783 ERROR: Exception when setting dynamic_configuration
patroni[1103]: Traceback (most recent call last):
patroni[1103]:   File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 193, in set_dynamic_configuration
patroni[1103]:     self._local_configuration)
patroni[1103]:   File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 368, in _build_effective_configuration
patroni[1103]:     config = self._safe_copy_dynamic_configuration(dynamic_configuration)
patroni[1103]:   File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 238, in _safe_copy_dynamic_configuration
patroni[1103]:     config[name] = int(value)
patroni[1103]: TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
```

patronictl show-config:
```
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: archive.sh %p
    archive_mode: 'on'
    archive_timeout: 600s
    autovacuum_max_workers: 8
    checkpoint_completion_target: 0.7
    effective_cache_size: 4096MB
    hot_standby: 'on'
    maintenance_work_mem: 256MB
    max_connections: 100
    max_locks_per_transaction: 64
    max_parallel_maintenance_workers: 4
    max_parallel_workers: 5
    max_parallel_workers_per_gather: 3
    max_replication_slots: 32
    max_wal_senders: 17
    max_worker_processes: 6
    old_snapshot_threshold: 1d
    shared_buffers: 2048MB
    statement_timeout: 3600000
    vacuum_cost_limit: 800
    wal_keep_segments: 32
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 4MB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
ttl: 30
watchdog:
  mode: false
```
patronictl version 2.0.1
Where should i place the watchdog block?
