### ISSUE TITLE
Requests to patroni api node hangs on one node in cluster. DSC is raft  

### ISSUE THREAD

**Issue by Bro05** [zalando/patroni#1764]
**Describe the bug**
Request to patroni api hang to respond on most requests (GET - / , health  POST reinitialize ), and continue answer on GET cluster). Affected one node in 3 node cluster Nothing in log Postgres available 
If make request GET cluster/ to affected node, returned all 3 node from cluster
If make request to any healthy node, it got only health nodes
Only way to restore node, reinitialize it with patronictl reinit
 
Patroni run in docker   
**Environment**
- Patroni version: 2.01
- PostgreSQL version: 13.0
- DCS (and its version): RAFT

**Patroni configuration file**
```
---
scope: MyScope
name: postgres-ha-01

log:
  level: WARNING

restapi:
  listen: patroni-01.my.domain:8008
  connect_address: patroni-01.my.domain:8008
  authentication:
    username: user
    password: ********* 
  ctl:
    insecure: true

raft:
  data_dir: /var/lib/postgresql/pgdata/raft
  self_addr: <ip1>:5010
  partner_addrs: [ '<ip1>:5010', '<ip2>:5010', '<ip3>:5010']

bootstrap:
  dcs:
    loop_wait: 2
    master_start_timeout: 0
    maximum_lag_on_failover: 1048576
    postgresql:
      parameters:
        archive_command: /bin/true
        archive_mode: 'on'
        autovacuum_max_workers: '6'
        autovacuum_vacuum_scale_factor: '0.1'
        autovacuum_vacuum_threshold: '50'
        client_min_messages: NOTICE
        effective_cache_size: 512MB
        hot_standby: 'on'
        hot_standby_feedback: 'on'
        listen_addresses: '*'
        log_connections: 'on'
        log_destination: stderr
        log_disconnections: 'on'
        log_duration: 'off'
        log_min_duration_statement: 25
        log_min_error_statement: NOTICE
        log_min_messages: NOTICE
        logging_collector: 'off'
        maintenance_work_mem: 512MB
        max_connections: '1000'
        max_replication_slots: 10
        max_wal_senders: '20'
        port: 5432
        shared_buffers: 2GB
        shared_preload_libraries: pg_stat_statements
        wal_compression: 'off'
        wal_keep_segments: 8
        wal_level: hot_standby
        wal_log_hints: 'on'
        work_mem: 64MB
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 4

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - <pga_hba_settings>

  users:
      admin:
      password: *******
      options: ['createrole', 'createdb']
      replicator:
      password: *********
      options: ['superuser']
  
postgresql:
  listen: 0.0.0.0:5432
  connect_address: <ip1>:5432
  data_dir: /var/lib/postgresql/data
  bin_dir: /usr/lib/postgresql/13/bin/
  authentication:
    replication:
      username: replicator
      password: ************
    superuser:
      username: admin
      password: ************
  parameters:
    unix_socket_directories: '/run/postgresql'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

**patronictl show-config**
```
{
  "ttl": 4,
  "loop_wait": 2,
  "retry_timeout": 10,
  "master_start_timeout": 0,
  "maximum_lag_on_failover": 1048576,
  "postgresql": {
    "use_pg_rewind": true,
    "use_slots": true,
    "parameters": {
      "wal_level": "hot_standby",
      "hot_standby": "on",
      "wal_keep_segments": 8,
      "max_replication_slots": 10,
      "wal_log_hints": "on",
      "listen_addresses": "*",
      "port": 5432,
      "log_destination": "stderr",
      "logging_collector": "off",
      "log_min_messages": "NOTICE",
      "log_min_error_statement": "NOTICE",
      "log_connections": "on",
      "log_disconnections": "on",
      "log_duration": "off",
      "log_min_duration_statement": 25,
      "client_min_messages": "NOTICE",
      "hot_standby_feedback": "on",
      "shared_buffers": "2GB",
      "work_mem": "64MB",
      "effective_cache_size": "512MB",
      "maintenance_work_mem": "512MB",
      "wal_compression": "off",
      "max_wal_senders": "20",
      "shared_preload_libraries": "pg_stat_statements",
      "autovacuum_max_workers": "6",
      "autovacuum_vacuum_scale_factor": "0.1",
      "autovacuum_vacuum_threshold": "50",
      "archive_mode": "on",
      "archive_command": "/bin/true",
      "max_connections": "1000"
    }
  }
}

```

**Have you checked Patroni logs?**
Yes, I had checked, but nothing I saw

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Yes

**Additional context**
Run patroni in docker. Thats docker file 
```
FROM postgres:13
RUN usermod -u 1001 postgres && \
    groupmod -g 1001 postgres && \
    apt update && \
    apt install -y python3-psycopg2 python3-pip && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;
USER postgres
RUN pip3 install --no-cache-dir --user patroni[raft]==2.0.1
ENTRYPOINT []
```
