### ISSUE TITLE
How to use synchronous_node_count correctly?

### ISSUE THREAD

**Issue by xzizka** [zalando/patroni#1766]
I would like to understand how to synchronous_node_count works.
Environment: K8s, DigitalOcean.

Hello,

I try to setup Postgres-Operator to deploy PostgreSQL clusters in synchronous mode. In the documentation ([https://patroni.readthedocs.io/en/latest/replication_modes.html#synchronous-mode-implementation](https://patroni.readthedocs.io/en/latest/replication_modes.html#synchronous-mode-implementation)), there is written:
_Patroni will only assign one or more synchronous standby nodes based on **synchronous_node_count** parameter to **synchronous_standby_names**._

I have the following manifest (truncated):
```
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-12:1.6-p5
  teamId: postgres
  numberOfInstances: 4
  users: 

```

```
  postgresql:    
    version: "12"
    parameters:  # Expert section
      shared_buffers: "64MB"
      max_connections: "10"
      log_statement: "all"
      log_destination: "stderr"
      logging_collector: "false"
      synchronous_commit: "remote_apply"
      synchronous_standby_names: "*"
      shared_preload_libraries: "bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,timescaledb,pg_cron,pg_stat_kcache,pgaudit"
  volume:
    size: 1Gi
#    storageClass: my-sc
```
and another part
```
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
    - hostssl all all 0.0.0.0/0 md5
    - host    all all 0.0.0.0/0 md5
    ttl: 30
    loop_wait: &loop_wait 10
    retry_timeout: 10
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_node_count: 3
    maximum_lag_on_failover: 33554432
```

If I understand correctly, the parameter _synchronous_node_count: 3_, should put 3 of 4 instances into sync mode and one to async mode, but in reality, the situation after the deploy is following (executed on master):

```
postgres=# select application_name, sync_state from pg_stat_replication;
    application_name     | sync_state
-------------------------+------------
 postgres-test-cluster-1 | sync
 postgres-test-cluster-2 | async
 postgres-test-cluster-3 | async
(3 rows)

postgres=#

```
The situation was the same even if I typed the name of pods/application to the manifest.
Is this correct result based on the manifest I use?

Maybe there is some misunderstanding in configuration from my side. This is a combination of Patroni and Postgres Operator... I am not sure, where the issue can be so posting it here as Patroni is the underlying tool for the configuration.

Thank you
