### ISSUE TITLE
Patroni declines to failover if consul was unavailable

### ISSUE THREAD

**Issue by zorgan** [zalando/patroni#1782]
I've tested network outage and got some strange result.
I have 3-node cluster with single node consul server, node3 is a leader.
Here's log of events:
```
node1: stop consul client
node2: stop consul client
consul-server: stop consul server
node3: stop consul client
consul-server: start consul server
node2: start consul client
```
I've expected node2 to become patroni leader, but unfortunately it didn't with message:
`INFO: following a different leader because i am not the healthiest node`
But both nodes(node2 and node3) are at the same position:
```
# curl -s http://10.250.0.221:8008 | jq '.xlog, .timeline' 
{
  "received_location": 318767256,
  "replayed_location": 318767256,
  "replayed_timestamp": null,
  "paused": false
}
16

```
```
# curl -s http://10.250.2.149:8008 | jq '.xlog, .timeline' 
{
  "received_location": 318767256,
  "replayed_location": 318767256,
  "replayed_timestamp": null,
  "paused": false
}
16

```
node2 was "Sync standby", but after resurrection it became "Replica", that's why it hasn't been promoted.
How can i avoid such failure using `synchronous_mode: true` ?

**Environment**
- Patroni version: patronictl version 2.0.1
- PostgreSQL version: 12
- DCS (and its version): Consul v1.6.2

**patronictl show-config**
```
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 10048576
postgresql:
  parameters:
    archive_command: /bin/bash /opt/scripts/archive.sh %p
    archive_mode: 'on'
    archive_timeout: 600s
    autovacuum_max_workers: 1
    effective_cache_size: 3072MB
    hot_standby: 'on'
    maintenance_work_mem: 256MB
    max_connections: 100
    max_locks_per_transaction: 64
    max_parallel_maintenance_workers: 1
    max_parallel_workers: 2
    max_parallel_workers_per_gather: 1
    max_replication_slots: 32
    max_wal_senders: 17
    max_worker_processes: 2
    shared_buffers: 1024MB
    vacuum_cost_limit: 100
    wal_keep_segments: 32
    wal_level: replica
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
ttl: 30

```
