### ISSUE TITLE
single node fails with failure to get zookeeper node(`kazoo.exceptions.NodeExistsError`)

### ISSUE THREAD

**Issue by sandeepkalra** [zalando/patroni#1783]
**Describe the bug**
In a multi-host working setup (3 hosts), all nodes were killed, and only one node was restarted after 
deleting the PGDATA directory. Patroni reports `kazoo.exceptions.NodeExistsError` (1 in 10 tries)

**To Reproduce**
3 host setup with zookeeper as DCS
stop all 3
start just 1 (which probably was not leader earlier).
patroni on this node shows errors, and eventually starts as replica.

**Expected behavior**
clean restart with single host being leader.

**Environment**
- Patroni version: patronictl version 2.0.1
- PostgreSQL version: psql (PostgreSQL) 12.5 (Ubuntu 12.5-1.pgdg18.04+1)
- DCS (and its version): Zookeeper:3.6.1

**Patroni configuration file**
```
cope: postgres
namespace: /bp_postgres/
name: pg_1

log:
  level: INFO
  traceback_level: INFO
  file_num: 2
  dir: /bp2/log/

restapi:
  listen: 172.16.1.27:8008
  connect_address: 172.16.1.27:8008

zookeeper:
  hosts: zookeeper:2181

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    max_timelines_history: 0
    check_timeline: false
    standby_cluster:
      create_replica_method:
        - basebackup
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
         hot_standby: "on"
         wal_log_hints: "on"
         hot_standby_feedback: "on"
         wal_level: "hot_standby"
         track_commit_timestamp: "off"
         wal_keep_segments: 100
         max_wal_senders: 5
         max_replication_slots: 0
         max_prepared_transactions: 25
         max_connections: 300
         max_locks_per_transaction: 25
         max_worker_processes: 5
  initdb:
        - encoding: UTF8
        - locale: C
        - data-checksums
  pg_hba:
    - host replication rbpadmin 172.16.1.27/0  md5
    - host all spostgres 172.16.1.27/0 md5
    - host all wbpadmin 172.16.1.27/0 md5
    - host all postgres 172.16.1.27/0 md5
    - host replication rbpadmin 0.0.0.0/0  md5
    - host all spostgres 0.0.0.0/0 md5
    - host all wbpadmin 0.0.0.0/0 md5
    - host all postgres 0.0.0.0/0 md5
    - host all all 172.16.1.27/0 md5
  users:
    postgres:
        password: s12345678
        options:
            - createrole
            - createdb

postgresql:
  listen: 172.16.1.27:5432
  connect_address: 172.16.1.27:5432
  config_dir: /bp2/data/psql/
  data_dir: /bp2/data/psql/
  bin_dir: /usr/lib/postgresql/12/bin/
  create_replica_method:
    - basebackup
  callbacks:
    on_start: /bp2/src/chetak/patroni_callbacks.py
    on_stop: /bp2/src/chetak/patroni_callbacks.py
    on_role_change: /bp2/src/chetak/patroni_callbacks.py
  authentication:
    replication:
      username: rbpadmin
      password: s12345678
    superuser:
      username: spostgres
      password: s12345678
    rewind:
      username: wbpadmin
      password: s12345678
  pgpass: /bp2/data/.patroni_pgpass
  parameters:
    unix_socket_directories: '.'
    shared_buffers: 512MB
    maintenance_work_mem: 100MB
    wal_writer_delay: 500ms
    commit_delay: 500
    autovacuum_max_workers: 1
    autovacuum_work_mem: 500MB
    autovacuum_vacuum_cost_delay: 20ms
    autovacuum_vacuum_cost_limit: 200
    autovacuum_vacuum_scale_factor: 0.00
    autovacuum_analyze_scale_factor: 0.0
    autovacuum_naptime: 1
    checkpoint_completion_target: 0.
    bgwriter_delay: 1000
    bgwriter_lru_maxpages: 100
    bgwriter_lru_multiplier: 1
    temp_buffers: 32MB
    max_stack_depth: 4MB
    escape_string_warning: "off"
    standard_conforming_strings: "on"
    pg_stat_statements.max: 5000
    track_activity_query_size: 204
    track_io_timing: "on"
    tcp_keepalives_idle: 6
    tcp_keepalives_interval: 1
    tcp_keepalives_count: 0
    logging_collector: "on"
    log_min_messages: ERROR
    log_destination: "syslog"
    syslog_ident: postgres_1
    log_line_prefix: '%t %n [%p]: [%l] sqlstate=%e application_name=%a,user=%u,db=%d,client=%h '
    log_min_duration_statement: 500ms
    log_min_error_statement: ERROR
    log_autovacuum_min_duration: 500ms
    log_error_verbosity: TERSE
    log_autovacuum_min_duration: 500ms
    log_statement: none
    log_temp_files: -1
    log_checkpoints: off
    log_connections: off
    log_disconnections: off
    log_lock_waits: on
    synchronous_commit: on
    synchronous_standby_names: ""
    work_mem: 100MB
    max_wal_size: 10GB
    checkpoint_timeout: 15min
    idle_in_transaction_session_timeout: 5min
    default_statistics_target: 10000
    effective_cache_size: 512MB
    max_parallel_workers_per_gather: 2
    effective_io_concurrency: 200
    shared_preload_libraries: pg_stat_statements,pg_trgm,postgres_fdw,timescaledb
    seq_page_cost: "1"
    random_page_cost: "1.1"

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: true
    nosync: false

**patronictl show-config**
```
check_timeline: false
loop_wait: 10
max_timelines_history: 0
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    hot_standby: 'on'
    hot_standby_feedback: 'on'
    max_connections: 300
    max_locks_per_transaction: 25
    max_prepared_transactions: 25
    max_replication_slots: 0
    max_wal_senders: 5
    max_worker_processes: 5
    track_commit_timestamp: 'off'
    wal_keep_segments: 100
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
standby_cluster:
  create_replica_method:
  - basebackup
ttl: 30

**Have you checked Patroni logs?**
```
 5508 2020-12-08 09:07:12,600 INFO: running post_bootstrap
 5509 2020-12-08 09:07:12,624 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
 5510 2020-12-08 09:07:12,645 ERROR: Failed to create /bp_postgres/postgres/leader
 5511 Traceback (most recent call last):
 5512   File "/usr/local/lib/python3.7/dist-packages/patroni/dcs/zookeeper.py", line 255, in _create
 5513     self._client.retry(self._client.create, path, value, makepath=True, ephemeral=ephemeral)
 5514   File "/usr/local/lib/python3.7/dist-packages/kazoo/client.py", line 285, in _retry
 5515     return self._retry.copy()(*args, **kwargs)
 5516   File "/usr/local/lib/python3.7/dist-packages/kazoo/retry.py", line 129, in __call__
 5517     return func(*args, **kwargs)
 5518   File "/usr/local/lib/python3.7/dist-packages/kazoo/client.py", line 883, in create
 5519     sequence=sequence, makepath=makepath).get()
 5520   File "/usr/local/lib/python3.7/dist-packages/kazoo/handlers/utils.py", line 75, in get
 5521     raise self._exception
 5522   File "/usr/local/lib/python3.7/dist-packages/kazoo/handlers/utils.py", line 271, in captured_function
 5523     return function(*args, **kwargs)
 5524   File "/usr/local/lib/python3.7/dist-packages/kazoo/handlers/utils.py", line 289, in captured_function
 5525     value = function(*args, **kwargs)
 5526   File "/usr/local/lib/python3.7/dist-packages/kazoo/client.py", line 938, in create_completion
 5527     return self.unchroot(result.get())
 5528   File "/usr/local/lib/python3.7/dist-packages/kazoo/handlers/utils.py", line 69, in get
 5529     raise self._exception
 5530 kazoo.exceptions.NodeExistsError
 5531 2020-12-08 09:07:12,650 INFO: Could not take out TTL lock
 5532 2020-12-08 09:07:12,665 INFO: initialized a new cluster
 5533 2020-12-08 09:07:13,216 INFO: Lock owner: pg_1; I am pg_2
 5534 2020-12-08 09:07:13,216 INFO: does not have lock
 5535 2020-12-08 09:07:13,272 INFO: demoting self because i do not have the lock and i was a leader
 5536 2020-12-08 09:07:13,273 INFO: closed patroni connection to the postgresql cluster
 5537 2020-12-08 09:07:13,432 INFO: postmaster pid=149
 5538 2020-12-08 09:07:14,519 INFO: establishing a new patroni connection to the postgres cluster
 5539 2020-12-08 09:07:14,528 INFO: My wal position exceeds maximum replication lag
 5540 2020-12-08 09:07:14,540 INFO: following a different leader because i am not the healthiest node
 5541 2020-12-08 09:07:24,512 INFO: My wal position exceeds maximum replication lag
 5542 2020-12-08 09:07:24,521 INFO: following a different leader because i am not the healthiest node
