### ISSUE TITLE
Log status on change only

### ISSUE THREAD

**Issue by stephan2012** [zalando/patroni#1800]
**Describe the bug**

Patroni currently floods logs with status messages every five seconds:

```
2020-12-14 17:11:58,430 INFO: Lock owner: my-application-pg-0; I am my-applcation-pg-1
2020-12-14 17:11:58,430 INFO: does not have lock
2020-12-14 17:11:58,431 INFO: no action.  i am a secondary and i am following a leader
```

Emitting messages on status changes (or errors) only would not only reduce the number of log events but also make the log more clear.

**To Reproduce**
Setup any replicated database.

**Expected behavior**
Emit a log message only if there is news …

**Screenshots**
N/A

**Environment**
- Patroni version: `1.6.5`
- PostgreSQL version: Postgres 11
- DCS (and its version): N/A

**Patroni configuration file**
Generated by the Postgres Operator, N/A here

**patronictl show-config**
```
loop_wait: 5
maximum_lag_on_failover: 33554432
postgresql:
  parameters:
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_vacuum_scale_factor: 0.05
    checkpoint_completion_target: 0.9
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_statement: ddl
    log_temp_files: 0
    max_connections: '130'
    max_replication_slots: 10
    max_wal_senders: 10
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    track_functions: all
    wal_keep_segments: 8
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 5
ttl: 10
```

**Have you checked Patroni logs?**
N/A

**Have you checked PostgreSQL logs?**
N/A

**Have you tried to use GitHub issue search?**
Yes.

**Additional context**
