### ISSUE TITLE
Unable to disable kubernetes.use_endpoints via environment

### ISSUE THREAD

**Issue by cbandy** [zalando/patroni#1814]
**Describe the bug**
While I was inspecting the objects created by Patroni when using Kubernetes DCS, I noticed that I cannot disable `use_endpoints` using the `PATRONI_KUBERNETES_USE_ENDPOINTS` environment variable.

My configuration file contains:

```yaml
kubernetes:
  use_endpoints: true
```

When I run `PATRONI_KUBERNETES_USE_ENDPOINTS="false" patroni config.yaml`, it continues to write to Endpoints objects. I've also tried `PATRONI_KUBERNETES_USE_ENDPOINTS=""`.

**Expected behavior**
I expected to be able to override this local setting with an environment variable.

The `PATRONI_KUBERNETES_BYPASS_API_SERVICE` behaves the way I expect.

**Environment**
- Patroni version: v2.0.1
- PostgreSQL version: 13
- DCS (and its version): Kubernetes v1.18.10

**Patroni configuration file**
```yaml
scope: test
bootstrap:
  dcs: {}
kubernetes:
  labels: {}
  namespace: default
  use_endpoints: true
postgresql:
  data_dir: /tmp/data_dir
  authentication:
    replication:
      username: postgres
```

**patronictl show-config**
```
{}
```
