### ISSUE TITLE
With multiple consul servers patroni nodes split the cluster

### ISSUE THREAD

**Issue by kalimalrazif** [zalando/patroni#1821]
**Describe the bug**
With more than one consul server patroni splits the cluster, agents connects to different servers creating more than one "cluster", I have 4 patroni nodes.

**To Reproduce**
Setup 2 consul server for redundancy and config the agents to connect to a list: 
"retry_join": [
   "consul_server1",
   "consul_server2"
 ]

**Expected behavior**
Running patronictl -c /etc/patroni.yml list on nodes, shows different list on some, sometimes one node forms it's own cluster sometimes is 2 and 2

**Environment**
- Patroni version: 2.0.1
- PostgreSQL version: 10.15-0ubuntu0.18.04.1
- DCS (and its version): Consul 1.9.1 

**Patroni configuration file**
```
scope: alert_cluster
namespace: /alert_cluster/
name: ip-10-41-0-169

restapi:
    listen: 10.41.0.169:8008
    connect_address: 10.41.0.169:8008

consul:
    url: http://127.0.0.1:8500/

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout : 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_keep_segments: 100

  initdb:
    - encoding: UTF8
    - data-checksums

  pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.41.0.18/0 md5
    - host replication replicator 10.41.0.246/0 md5
    - host replication replicator 10.41.0.169/0 md5
    - host replication replicator 10.41.0.23/0 md5
    - host all all 0.0.0.0/0 md5

postgresql:
    listen: 10.41.0.169:5432
    connect_address: 10.41.0.169:5432
    data_dir: /var/lib/postgresql/ha_cluster/ip-10-41-0-169/data
    bin_dir: /usr/lib/postgresql/10/bin
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: a_very_complicated_password
        superuser:
            username: postgres
            password: a_very_complicated_password
    parameters:
        unix_socket_directories: '.'

watchdog:
    mode: automatic
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    wal_keep_segments: 100
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
no :-( 

**Have you checked PostgreSQL logs?**
no :-(

**Have you tried to use GitHub issue search?**
Yes but did not find any related
