### ISSUE TITLE
patronictl - cluster management status code=401, (not authenticated).

### ISSUE THREAD

**Issue by Aytuar** [zalando/patroni#1844]
**Describe the bug**
```
patronictl -c /opt/app/patroni/etc/postgresql.yml pause
Failed: pause cluster management status code=401, (not authenticated)
```
**To Reproduce**
Set authentication in Patroni configuration file
```
restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.1.2.3:8008
  authentication:
    username: test
    password: testpassword
```

**Expected behavior**
```
patronictl -c /opt/app/patroni/etc/postgresql.yml pause
Success: cluster management is paused.
```

**Environment**
- Patroni version: 1.6.5
- PostgreSQL version: 9.6 - 11
- DCS (and its version): etcd 2.3.8

**Have you tried to use GitHub issue search?**
Yes. Not found it.

**Additional context**
Documentation.
https://patroni.readthedocs.io/en/latest/SETTINGS.html#rest-api
https://patroni.readthedocs.io/en/latest/security.html#protecting-the-rest-api
https://github.com/zalando/patroni/blob/master/postgres1.yml#L10-L12

At the same time, it works through the API.
```
curl -u test:testpassword -sS -XPATCH -d '{"pause": true}' http://127.0.0.1:8008/config
curl -u test:testpassword -sS -XPATCH -d '{"pause": false}' http://127.0.0.1:8008/config
```
