### ISSUE TITLE
standby cluster won't stream only restore_command working

### ISSUE THREAD

**Issue by gspiegelberg-pivotal** [zalando/patroni#1855]
Versions:
PostgreSQL 11.7, Patroni 1.6.4, pgbackrest 2.23, etcd 3.3.11, CentOS 7.8

Brief database setup in lab mimicking a production environment:

1. Site 1 has database hosts s81, s82, s83 using synchronous "ANY 1" replication, all good here
2. Site 1 has own etcd cluster and s81, s82 and s83 are only hosts in Patroni cluster
3. Site 1 pg_hba configured to permit replication from site 2 hosts
4. Site 2 has database hosts s84 and s85 with intent to use asynchronous replication from Site 1 s83 to s84 and stream from s84 to s85
5. Site 2 has own etcd cluster and s84 and s85 are only hosts in Patroni cluster
6. Site 2 is standby cluster / replicas only

s84 and s85 only get configured with restore_command in recovery.conf.  Nothing I have done changes that to include primary_conninfo.  Site 2 s85 patroni.yml and recovery.conf below.

I'm certain this is a configuration issue on my part so hopefully a quick open & shut case.

Let me know if more info needed.

Thanks
-Greg

Site 2 s84 recovery. conf:
```
# Do not edit this file manually!
# It will be overwritten by Patroni!
recovery_target_timeline = 'latest'
standby_mode = 'on'
```

patroni.yml on s84 where 10.10.1.83 is site 1 s83 host:
```
scope: pgtest
name: s84

restapi:
  listen: 10.10.1.84:8008
  connect_address: 10.10.1.84:8008

log:
  dir: /var/lib/pgsql/patroni/log
  file_num: 8
  file_size: 1024000

etcd:
  hosts: 10.10.1.84:2379,10.10.1.85:2379,10.10.1.86:2379
  protocol: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout : 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
    standby_cluster:
      host: 10.10.1.83
      port: 6432
      create_replica_methods:
        - basebackup

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host all         all        127.0.0.1/32  md5
  - host all         all        10.10.1.0/24   md5
  - host replication repuser 10.10.1.81/32  md5
  - host replication repuser 10.10.1.82/32  md5
  - host replication repuser 10.10.1.83/32  md5
  - host replication repuser 10.10.1.84/32  md5
  - host replication repuser 10.10.1.85/32  md5

postgresql:
  listen: 10.10.1.84:6432
  connect_address: 10.10.1.84:6432
  data_dir: /pgdata/11
  bin_dir: /usr/bin
  authentication:
    replication:
      username: repuser
      password: repuser
    superuser:
      username: postgres
      password: postgres
  parameters:
    unix_socket_directories: '/var/run/postgresql, /tmp'
    port: 6432
    wal_level: logical
  create_replica_methods:
    basebackup:
      - verbose
      - max-rate: '100M'
      - checkpoint: 'fast'

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: true
  clonefrom: true
  noloadbalance: true
  replicatefrom: 10.10.1.83
  nosync: true
```
