### ISSUE TITLE
Kubernetes environment variables don't seem to take effect

### ISSUE THREAD

**Issue by vdamle** [zalando/patroni#1864]
**Describe the bug**
I'm trying to use the Kubernetes environment variables as documented here: https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html#kubernetes in a minikube based setup and I do not see:
* labels getting applied as configured in `PATRONI_KUBERNETES_LABELS`
* additional ports being exposed on the endpoint created for the master pod (set in `PATRONI_KUBERNETES_PORTS`)

**To Reproduce**
Specify the following environment variables for the `patroni` pod/container when bringing up a 3 node cluster in minikube:

* `PATRONI_KUBERNETES_USE_ENDPOINTS=true`
* `PATRONI_KUBERNETES_NAMESPACE=zzrs3r6h3f`
* `PATRONI_KUBERNETES_SCOPE_LABEL=app`
* `PATRONI_SCOPE=postgres`
* `PATRONI_KUBERNETES_PORTS=["name": "sidecar", "port": 3000},{"name": "dbport", "port": 5432}]` (service is defined with the same name for both ports)
* `PATRONI_KUBERNETES_LABELS={"release": "zzrs3r6h3f-zzttbm6jge"}`

**Expected behavior**

* Expected to see the `postgres` endpoint created with both `5432` and `3000` ports exposed. However, I only see `5432`.
* Expected to see `release=zzrs3r6h3f-zzttbm6jge` added to the endpoint

**Screenshots**

**Environment**
- Patroni version: 
- PostgreSQL version:
- DCS (and its version):

**Patroni configuration file**
```
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_mode: 'on'
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.05
        checkpoint_completion_target: 0.9
        hot_standby: 'on'
        log_autovacuum_min_duration: 0
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_lock_waits: 'on'
        log_min_duration_statement: 500
        log_statement: ddl
        log_temp_files: 0
        max_connections: 262
        max_replication_slots: 10
        max_wal_senders: 10
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        track_functions: all
        wal_level: hot_standby
        wal_log_hints: 'on'
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums
  post_init: /scripts/post_init.sh "zalandos"
  users:
    admin:
      options:
      - createrole
      - createdb
      password: admin
kubernetes:
  bypass_api_service: true
  labels:
    app: postgres
  pod_ip: 172.17.0.15
  ports:
  - name: postgresql
    port: 5432
  role_label: spilo-role
  scope_label: app
  use_endpoints: true
namespace: zzytq6ok7e
postgresql:
  authentication:
    replication:
      password: standby
      username: standby
    superuser:
      password: superuser
      username: postgres
  basebackup_fast_xlog:
    command: /scripts/basebackup.sh
    retries: 2
  bin_dir: /usr/lib/postgresql/13/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos true
  connect_address: 172.17.0.15:5432
  create_replica_method:
  - basebackup_fast_xlog
  data_dir: /home/postgres/pgdata/pgroot/data
  listen: '*:5432'
  name: zzytq6ok7e-zztizpewck-postgres-0
  parameters:
    archive_command: /bin/true
    bg_mon.history_buckets: 120
    bg_mon.listen_address: 0.0.0.0
    extwlist.custom_path: /scripts
    extwlist.extensions: btree_gin,btree_gist,citext,hstore,intarray,ltree,pgcrypto,pgq,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,hypopg,timescaledb,pg_partman
    log_destination: csvlog
    log_directory: ../pg_log
    log_file_mode: '0644'
    log_filename: postgresql-%u.log
    log_rotation_age: 1d
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    pg_stat_statements.track_utility: 'off'
    shared_buffers: 1575MB
    shared_preload_libraries: bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,timescaledb,pg_cron,pg_stat_kcache
    ssl: 'on'
    ssl_cert_file: /run/certs/server.crt
    ssl_key_file: /run/certs/server.key
  pg_hba:
  - local   all             all                                   trust
  - hostssl all             +zalandos    127.0.0.1/32       pam
  - host    all             all                127.0.0.1/32       md5
  - hostssl all             +zalandos    ::1/128            pam
  - host    all             all                ::1/128            md5
  - hostssl replication     standby all                md5
  - hostnossl all           all                all                reject
  - hostssl all             +zalandos    all                pam
  - hostssl all             all                all                md5
  pgpass: /run/postgresql/pgpass
  use_unix_socket: true
restapi:
  connect_address: 172.17.0.15:8008
  listen: :8008
scope: zzytq6ok7e-zztizpewck-postgres
```

```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

master:

```
2021-03-02 06:20:55,870 INFO: Lock owner: zzytq6ok7e-zztizpewck-postgres-0; I am zzytq6ok7e-zztizpewck-postgres-0
2021-03-02 06:20:55,922 INFO: no action.  i am the leader with the lock
2021-03-02 06:20:58.322 36 LOG {ticks: 0, maint: 0, retry: 0}
2021-03-02 06:21:05,869 INFO: Lock owner: zzytq6ok7e-zztizpewck-postgres-0; I am zzytq6ok7e-zztizpewck-postgres-0
2021-03-02 06:21:05,915 INFO: no action.  i am the leader with the lock
2021-03-02 06:21:15,869 INFO: Lock owner: zzytq6ok7e-zztizpewck-postgres-0; I am zzytq6ok7e-zztizpewck-postgres-0
2021-03-02 06:21:15,915 INFO: no action.  i am the leader with the lock
```

replica1/2
```
2021-03-02 06:21:25,920 INFO: trying to bootstrap from leader 'zzytq6ok7e-zztizpewck-postgres-0'
2021-03-02 06:21:25,921 ERROR: failed to bootstrap from leader 'zzytq6ok7e-zztizpewck-postgres-0'
2021-03-02 06:21:25,921 INFO: Removing data directory: /home/postgres/pgdata/pgroot/data
2021-03-02 06:21:35,915 INFO: Lock owner: zzytq6ok7e-zztizpewck-postgres-0; I am zzytq6ok7e-zztizpewck-postgres-1
2021-03-02 06:21:35,915 INFO: trying to bootstrap from leader 'zzytq6ok7e-zztizpewck-postgres-0'
2021-03-02 06:21:35,917 ERROR: failed to bootstrap from leader 'zzytq6ok7e-zztizpewck-postgres-0'
2021-03-02 06:21:35,917 INFO: Removing data directory: /home/postgres/pgdata/pgroot/data
```

**Have you checked PostgreSQL logs?**
No postgres logs on replica

**Have you tried to use GitHub issue search?**
Yes, could not find any

**Additional context**
