### ISSUE TITLE
Timestamp display of patronictl history

### ISSUE THREAD

**Issue by huiyalin525** [zalando/patroni#1879]
**Describe the bug**
Timestamp display problem when using the command Patroni history 

**To Reproduce**
Patroni connects to etcd, etcd opens the enable-v2 port, and now Patroni will be configured PATRONI_ ETCD_ HOSTS becomes Patroni_ ETCD3_ HOSTS 
before 
$ patronictl history
+----+--------------+------------------------------+----------------------------------+
| TL |          LSN | Reason                       | Timestamp                        |
+----+--------------+------------------------------+----------------------------------+
|  1 | 490851022008 | no recovery target specified |                                  |
|  2 | 490867785888 | no recovery target specified | 2020-12-10T18:37:06.718112+08:00 |
|  3 | 490884563104 | no recovery target specified | 2020-12-10T18:47:00.137245+08:00 |
|  4 | 490918117536 | no recovery target specified | 2020-12-10T19:01:52.007200+08:00 |
|  5 | 491002003616 | no recovery target specified | 2020-12-11T11:45:07.786737+08:00 |
|  6 | 491035558048 | no recovery target specified | 2020-12-11T17:12:22.356089+08:00 |
|  7 | 491136221344 | no recovery target specified | 2020-12-15T10:41:18.108117+08:00 |
|  8 | 491496861840 | no recovery target specified | 2020-12-23T10:00:33.360030+08:00 |
|  9 | 491522097312 | no recovery target specified | 2020-12-25T12:04:47.860347+08:00 |
| 10 | 491605983392 | no recovery target specified | 2021-01-08T13:17:35.154499+08:00 |
| 11 | 491643742600 | no recovery target specified | 2021-01-14T10:54:38.506782+08:00 |
| 12 | 491756978336 | no recovery target specified | 2021-01-14T15:35:00.748986+08:00 |
| 13 | 491790532768 | no recovery target specified | 2021-01-14T15:51:45.688471+08:00 |
| 14 | 491941527712 | no recovery target specified | 2021-01-15T10:12:14.281960+08:00 |
| 15 | 492008636576 | no recovery target specified | 2021-01-15T11:11:01.818900+08:00 |
| 16 | 492025413792 | no recovery target specified | 2021-01-15T11:25:43.496838+08:00 |
| 17 | 492142854304 | no recovery target specified | 2021-01-15T11:57:27.235425+08:00 |
| 18 | 492612616352 | no recovery target specified | 2021-01-15T16:02:00.090886+08:00 |
| 19 | 493233373344 | no recovery target specified | 2021-01-19T17:20:13.631970+08:00 |
| 20 | 493825795736 | no recovery target specified | 2021-02-18T08:45:23.874301+08:00 |
| 21 | 493852994872 | no recovery target specified | 2021-02-22T10:29:58.429181+08:00 |
+----+--------------+------------------------------+----------------------------------+
after
+----+--------------+------------------------------+----------------------------------+
| TL |          LSN | Reason                       | Timestamp                        |
+----+--------------+------------------------------+----------------------------------+
|  1 | 490851022008 | no recovery target specified |                                  |
|  2 | 490867785888 | no recovery target specified |                                  |
|  3 | 490884563104 | no recovery target specified |                                  |
|  4 | 490918117536 | no recovery target specified |                                  |
|  5 | 491002003616 | no recovery target specified |                                  |
|  6 | 491035558048 | no recovery target specified |                                  |
|  7 | 491136221344 | no recovery target specified |                                  |
|  8 | 491496861840 | no recovery target specified |                                  |
|  9 | 491522097312 | no recovery target specified |                                  |
| 10 | 491605983392 | no recovery target specified |                                  |
| 11 | 491643742600 | no recovery target specified |                                  |
| 12 | 491756978336 | no recovery target specified |                                  |
| 13 | 491790532768 | no recovery target specified |                                  |
| 14 | 491941527712 | no recovery target specified |                                  |
| 15 | 492008636576 | no recovery target specified |                                  |
| 16 | 492025413792 | no recovery target specified |                                  |
| 17 | 492142854304 | no recovery target specified |                                  |
| 18 | 492612616352 | no recovery target specified |                                  |
| 19 | 493233373344 | no recovery target specified |                                  |
| 20 | 493825795736 | no recovery target specified |                                  |
| 21 | 493852994872 | no recovery target specified |                                  |
| 22 | 494525253776 | no recovery target specified | 2021-03-11T16:24:11.871274+08:00 |
+----+--------------+------------------------------+----------------------------------+

**Expected behavior**
Partial loss of timestamp

**Screenshots**

**Environment**
- Patroni version: 2.0.1
- PostgreSQL version: 12.5
- DCS (and its version): etcd version:3.4.14     docker version: 19.03.14

**Patroni configuration file**
```
scope: batman
# namespace: /service/
name: postgresql0

restapi:
  listen: 0.0.0.0:8008
  # connect_address: 127.0.0.1:8008
  # certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
  # keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
  # authentication:
  #   username: username
  #   password: password

# ctl:
#   insecure: false # Allow connections to SSL sites without certs
#   certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#   cacert: /etc/ssl/certs/ssl-cacert-snakeoil.pem

  etcd:
  #Provide host to do the initial discovery of the cluster topology:
   host: 192.17.0.2:2379
  #Or use "hosts" to provide multiple endpoints
  #Could be a comma separated string:
  #hosts: host1:port1,host2:port2
  #or an actual yaml list:
  #hosts:
  #- host1:port1
  #- host2:port2
  #Once discovery is complete Patroni will use the list of advertised clientURLs
  #It is possible to change this behavior through by setting:
  #use_proxies: true

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    # master_start_timeout: 300
    # synchronous_mode: false
    # standby_cluster:
    #   host: 127.0.0.1
    #   port: 1111
    #   primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
      # use_slots: true
      pg_hba:
      - local all postgres trust
      - local replication postgres ident
      - host replication all all md5
      - host all all all md5
      parameters:
        checkpoint_timeout: 10min
        effective_cache_size: 4GB
        hot_standby_feedback: true
        log_autovacuum_min_duration: 1000
        log_destination: csvlog
        log_lock_waits: true
        log_min_duration_statement: 500
        log_min_messages: warning
        log_statement: none
        log_timezone: UTC
        logging_collector: 'on'
        maintenance_work_mem: 128MB
        max_connections: 800
        max_parallel_workers: 8
        max_parallel_workers_per_gather: 4
        max_standby_streaming_delay: 30s
        max_wal_size: 4GB
        max_worker_processes: 8
        min_wal_size: 1GB
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        shared_buffers: 4GB
        shared_preload_libraries: pg_stat_statements
        synchronous_commit: 'off'
        synchronous_standby_names: ANY 1(*)
        temp_buffers: 32MB
        track_functions: all
        track_io_timing: true
        wal_compression: true
        wal_keep_segments: 1000
        wal_level: logical
        work_mem: 8MB
        # wal_level: hot_standby
        # hot_standby: "on"
        # wal_keep_segments: 8
        # max_wal_senders: 10
        # max_replication_slots: 10
        # wal_log_hints: "on"
        # archive_mode: "on"
        # archive_timeout: 1800s
        # archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
      # recovery_conf:
        # restore_command: cp ../wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - locale: en_US.UTF-8
  - encoding: UTF8
  - data-checksums

  # pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  # For kerberos gss based connectivity (discard @.*$)
  # - host replication replicator 127.0.0.1/32 gss include_realm=0
  # - host all all 0.0.0.0/0 gss include_realm=0
  # - host replication replicator 0.0.0.0/0 md5
  # - host all all 0.0.0.0/0 md5
  # - hostssl all all 0.0.0.0/0 md5

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
  # post_init: /usr/local/bin/setup_cluster.sh

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      # password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  # connect_address: 127.0.0.1:5432
  data_dir: /home/postgres/data
  # bin_dir:
  # config_dir:
  pgpass: /tmp/pgpass0
  # authentication:
  #   replication:
  #     username: replicator
  #     password: rep-pass
  #   superuser:
  #     username: postgres
  #     password: zalando
  #   rewind:  # Has no effect on postgres 10 and lower
  #     username: rewind_user
  #     password: rewind_password
  # Server side kerberos spn
  # krbsrvname: postgres
  # parameters:
    # Fully qualified kerberos ticket file for the running user
    # same as KRB5CCNAME used by the GSS
    # krb_server_keyfile: /var/spool/keytabs/postgres
    # unix_socket_directories: '.'

#watchdog:
#  mode: automatic # Allowed values: off, automatic, required
#  device: /dev/watchdog
#  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=itc archive-push %p
    archive_mode: 'on'
    checkpoint_timeout: 30min
    effective_cache_size: 4GB
    hot_standby_feedback: true
    log_autovacuum_min_duration: 1000
    log_destination: csvlog
    log_lock_waits: true
    log_min_duration_statement: 500
    log_min_messages: warning
    log_statement: none
    log_timezone: UTC
    logging_collector: 'on'
    maintenance_work_mem: 256MB
    max_connections: 600
    max_parallel_workers: 8
    max_parallel_workers_per_gather: 4
    max_standby_streaming_delay: 30s
    max_wal_size: 4GB
    max_worker_processes: 8
    min_wal_size: 1GB
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    shared_buffers: 4GB
    shared_preload_libraries: pg_stat_statements
    synchronous_commit: 'on'
    synchronous_standby_names: ANY 1(*)
    temp_buffers: 32MB
    track_functions: all
    track_io_timing: true
    wal_compression: true
    wal_keep_segments: 1000
    wal_level: logical
    work_mem: 8MB
  pg_hba:
  - local all postgres trust
  - local replication postgres ident
  - host replication all all md5
  - host all all all md5
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
