### ISSUE TITLE
Urgent support: Issue when start patroni

### ISSUE THREAD

**Issue by thuybt** [zalando/patroni#1898]
**Describe the bug**
Patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: kubernetes'

**To Reproduce**
systemctl start patroni
systemctl status patroni 

**Expected behavior**
patroni status : RUNNING

**Screenshots**
![image](https://user-images.githubusercontent.com/59462501/113675767-e6df4080-96e5-11eb-9e7a-a996de1751ac.png)

**Environment**
- Patroni version: Patroni 2.0.2
- PostgreSQL version: postgresql-12
- DCS (and its version):
etcd Version: 3.3.11
Git SHA: 2cf9e51
Go Version: go1.10.3
Go OS/Arch: linux/amd64

**Patroni configuration file**
```
scope: postgres
namespace: /db/
name: postgres-mt

restapi:
    listen: 10.128.0.2:8008
    connect_address: 10.128.0.2:8008

etcd:
    host: 10.128.0.2:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.128.0.2/0 md5
    - host replication replicator 10.128.0.2/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 10.128.0.2:5432
    connect_address: 10.128.0.2:5432
    bin_dir: /usr/pgsql-12/bin/
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: rep-pass
        superuser:
            username: postgres
            password: secretpassword
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

```

**patronictl show-config**
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: kubernetes'
![image](https://user-images.githubusercontent.com/59462501/113676270-6f5de100-96e6-11eb-8f04-443e858feef0.png)

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here
![image](https://user-images.githubusercontent.com/59462501/113676423-9d432580-96e6-11eb-8680-a4557c9948ca.png)

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
I have search similar issue but their solutions can not solve mind 

**Additional context**
I have to manage implement this system successfully before Apr 8, but after gone throughts days of searching and implement and then searching 
I could not find a solution that successfully solve my problem
