### ISSUE TITLE
Don't Remove unexpected parameters in Patroni config.yml from postgresql.conf file

### ISSUE THREAD

**Issue by fourpastmidnight** [zalando/patroni#1907]
## Describe the bug

I am configuring a new PostgreSQL 12.6 database cluster and have specified the setting `recovery_min_apply_delay = 3600` as a property under the `bootstrap.dcs.postgresql.parameters` section of the Patroni configuration file. Upon successfully starting Patroni, the following warning appears in the systemd log for the Patroni service:

```log
Apr 18 23:12:11 pgsql0 patroni[26714]: 2021-04-18 23:12:11,035 WARNING: Removing unexpected parameter=recovery_min_apply_delay value=3600 from the config
```

## To Reproduce

Specify the following property in your Patroni configuration file. (Note, minimal file example shown.)

```yaml
bootstrap:
  dcs:
    postgresql:
      parameters:
        recovery_min_apply_delay_value: 3600
```

Upon starting a cluster containing this PostgreSQL parameter, the following log line will be displayed in `journalctl`:

```log
Apr 18 23:12:11 pgsql0 patroni[26714]: 2021-04-18 23:12:11,035 WARNING: Removing unexpected parameter=recovery_min_apply_delay value=3600 from the config
```

## Expected behavior

I expect that _any_ valid PostgreSQL setting should not be removed by Patroni. If Patroni does not recognize a setting, it should just leave it alone. I understand this _may_ be to prevent people from "shooting themselves in the foot" with bad parameters, but PostgreSQL will do that for you. It'll either log a warning, an error, or outright terminate itself. In short, Patroni is here to manage the cluster, and not the database settings, other than ensuring that all cluster members contain the same settings pursuant to having a functional, highly-available cluster insofar as correct settings have been supplied by those setting up the database.

## Screenshots

Not Applicable.

## Environment

- Patroni version: 2.0.2
- PostgreSQL version: 12.6
- DCS (and its version): Etcd 3.2.26

## Patroni configuration file

```yaml
namespace: /jfrog
scope: artifactory
name: pgsql0

restapi:
  listen: 192.168.10.70:8008
  connect_address: 192.168.10.70:8008
  certfile: /etc/patroni/pki/pgsql0.crt
  keyfile: /etc/patroni/pki/pgsql0.key
  cafile: /etc/patroni/pki/ca.crt
  verify_client: required

ctl:
  insecure: false
  certfile: /etc/patroni/pki/pgsql0.crt
  cacert:   /etc/patroni/pki/ca.crt

etcd3:
  hosts:
  - 192.168.10.60:2379
  - 192.168.10.61:2379
  - 192.168.10.62:2379
  protocol: https
  cacert: /etc/patroni/pki/ca.crt
  cert: /etc/patroni/pki/pgsql0.crt
  key: /etc/patroni/pki/pgsql0.key

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout : 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_command: 'gzip -qc %p > /pgdata/wal_archive/%f'
        #archive_mode: on
        archive_mode: off
        checkpoint_completion_target: 0.9
        log_checkpoints: true
        maintenance_work_mem: 1GB
        random_page_cost: 2.0
        # See the last setting in section 19.6.3 at https://www.postgresql.org/docs/12/runtime-config-replication.html
        recovery_min_apply_delay: 3600
        shared_buffers: 4GB
        ssl: on
        ssl_ca_file: /etc/patroni/pki/ca.crt
        ssl_cert_file: /etc/patroni/pki/pgsql0.crt
        ssl_key_file: /etc/patroni/pki/pgsql0.key
        ssl_min_protocol_version: TLSv1.2
        ssl_prefer_server_ciphers: true
        #wal_keep_segments: 100
        wal_keep_segments: 1000
        wal_level: logical
        wal_log_hints: "on"
        work_mem: 8MB

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - local       all             all                             trust
  - host        all             all           127.0.0.1/32      trust
  - host        postgres        postgres      192.168.10.70/32  md5
  - hostssl     artifactory     artifactory   192.168.10.70/32  cert        clientcert=1
  - host        replication     replicator    0.0.0.0/0         md5

  users:
    artifactory:
      options:
      - createdb

postgresql:
  listen: 192.168.10.70:5432
  connect_address: 127.0.0.1,192.168.10.70:5432
  bin_dir: /usr/lib/postgresql/12/bin
  data_dir: /db/pgdata
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: test
    superuser:
      username: postgres
      password: test
```

## Paste output of `patronictl show-config` Here

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: gzip -qc %p > /pgdata/wal_archive/%f
    archive_mode: false
    checkpoint_completion_target: 0.9
    log_checkpoints: true
    maintenance_work_mem: 1GB
    random_page_cost: 2.0
    recovery_min_apply_delay: 3600
    shared_buffers: 4GB
    ssl: true
    ssl_ca_file: /etc/patroni/pki/ca.crt
    ssl_cert_file: /etc/patroni/pki/pgsql0.crt
    ssl_key_file: /etc/patroni/pki/pgsql0.key
    ssl_min_protocol_version: TLSv1.2
    ssl_prefer_server_ciphers: true
    wal_keep_segments: 1000
    wal_level: logical
    wal_log_hints: 'on'
    work_mem: 8MB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

## Have you checked Patroni logs?

Yes, please see above.

## Have you checked PostgreSQL logs?

Not applicable.

## Have you tried to use GitHub issue search?

Yes.

## Additional context

Even though the command `patronictl show-config` shows the parameter, the `postgresql.conf` file in the `/db/pgdata` directory does not:

```conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
include 'postgresql.base.conf'

archive_command = 'gzip -qc %p > /pgdata/wal_archive/%f'
archive_mode = 'False'
checkpoint_completion_target = '0.9'
cluster_name = 'artifactory'
hot_standby = 'on'
listen_addresses = '192.168.10.70'
log_checkpoints = 'True'
maintenance_work_mem = '1GB'
max_connections = '100'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '10'
max_worker_processes = '8'
port = '5432'
random_page_cost = '2.0'
shared_buffers = '4GB'
ssl = 'True'
ssl_ca_file = '/etc/patroni/pki/ca.crt'
ssl_cert_file = '/etc/patroni/pki/pgsql0.crt'
ssl_key_file = '/etc/patroni/pki/pgsql0.key'
ssl_min_protocol_version = 'TLSv1.2'
ssl_prefer_server_ciphers = 'True'
track_commit_timestamp = 'off'
wal_keep_segments = '1000'
wal_level = 'logical'
wal_log_hints = 'on'
work_mem = '8MB'
hba_file = '/db/pgdata/pg_hba.conf'
ident_file = '/db/pgdata/pg_ident.conf'
```
