### ISSUE TITLE
Question about standby cluster setup.

### ISSUE THREAD

**Issue by gglybin** [zalando/patroni#1928]
Hello,

Can you help me to clarify following?

I've setup test lab with 2-node Patroni cluster as below:
```
$ patronictl -d etcd://localhost:2379 list main_cluster
+ Cluster: main_cluster  (6957767297136683746) -----------+---------+----+-----------+
|         Member         |       Host      |     Role     |  State  | TL | Lag in MB |
+------------------------+-----------------+--------------+---------+----+-----------+
| srv-co7-pgdb1.test.com | 192.168.159.156 |    Leader    | running |  2 |           |
| srv-co7-pgdb2.test.com | 192.168.159.157 | Sync Standby | running |  2 |         0 |
+------------------------+-----------------+--------------+---------+----+-----------+
```

I also created Standby Cluster:
```
$ patronictl -d etcd://localhost:2379 list  standby_cluster
+ Cluster: standby_cluster (6957767297136683746)  ----------+---------+----+-----------+
|         Member         |       Host      |      Role      |  State  | TL | Lag in MB |
+------------------------+-----------------+----------------+---------+----+-----------+
| srv-co7-pgdb3.test.com | 192.168.159.158 | Standby Leader | running |  2 |           |
| srv-co7-pgdb4.test.com | 192.168.159.159 |                | running |  2 |         0 |
+------------------------+-----------------+----------------+---------+----+-----------+
```

As you may notice I have following topology currently:
```
srv-co7-pgdb2.test.com (Replica) <===Sync=== srv-co7-pgdb1.test.com (Master) ===Async===> srv-co7-pgdb3.test.com (Replica) ===Async===> srv-co7-pgdb4.test.com (Replica)
````

But my goal is to set "Sync" between  "srv-co7-pgdb3.test.com" and  "srv-co7-pgdb4.test.com". Can you help me on how to achieve this?

I tried to set below values on Standby Leader ( srv-co7-pgdb3.test.com), but it has no effect:
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    synchronous_standby_names: srv-co7-pgdb4.test.com
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
standby_cluster:
  create_replica_methods:
  - basebackup
  host: 192.168.159.156
  port: 5432
synchronous_mode: true
ttl: 30
```

Is this actually possible to get below scheme finally?:
```
srv-co7-pgdb2.test.com (Replica) <===Sync=== srv-co7-pgdb1.test.com (Master) ===Async===> srv-co7-pgdb3.test.com (Replica) === SYNC ===> srv-co7-pgdb4.test.com (Replica)
```

Thank you.
