### ISSUE TITLE
Patroni w/ Raft sometimes won't elect a new leader when the leader node goes down in docker

### ISSUE THREAD

**Issue by The-TT-Hacker** [zalando/patroni#1930]
**Describe the bug**

Note: I am using the new Raft option for DCS as we intend to use it when it is stable.
I have a 3 node setup in docker swarm and each instance of Patroni tied to its own physical server in the swarm. Sometimes when I disconnect the server with the leader node from the network, the other 2 nodes get into an infinite loop where Postgres fails to resolve the hostname (docker-compose service name) of the leader node and Patroni does not elect a new leader. The docker DNS seems to remove entries when a container stops, however it looks like there's a race condition which means this error does not always happen. If the DNS entry for the master node is removed after Patroni does a leader election, the cluster fails over correctly, however if the DNS entry is removed quickly by docker then this infinite loop occurs.

Postgres failing to resolve the hostname of the leader
FATAL:  could not connect to the primary server: could not translate host name "postgres1" to address: Name or service not known

Patroni not electing a new leader
2021-05-06 23:51:00,613 INFO: Lock owner: postgres1; I am postgres3
2021-05-06 23:51:00,613 INFO: does not have lock
2021-05-06 23:51:02,617 INFO: no action.  i am a secondary and i am following a leader

This occurs on both standby nodes while the leader is down. The network connection with postgres1 has been physically broken yet the 2 standby nodes do not elect a new leader.

**To Reproduce**

My setup is here: https://github.com/SPG-Controls/patroni-raft-docker
I used 3 physical servers so I could unplug network cables however I think this could also be reproduced on a single node swarm by scaling the service acting as the leader to 0 replicas.

**Expected behavior**
One of the two standby nodes should be elected as leader and be promoted as the primary node

**Environment**
- Patroni version: 2.0.2 Commit 99626a07f23151aa1abd63b9fb07819ab10e6900
- PostgreSQL version: 13
- DCS (and its version): Raft

**Patroni configuration file**
```
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_node_count: 1

    postgresql:
      parameters:
        max_connections: 256
      use_pg_rewind: true
      remove_data_directory_on_diverged_timelines: false
      remove_data_directory_on_rewind_failure: true

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication replicator 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 256
  remove_data_directory_on_diverged_timelines: false
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: true
synchronous_node_count: 1
ttl: 30
```

**Have you checked Patroni logs?**

2021-05-06 23:24:36.744 UTC [73283] FATAL:  could not connect to the primary server: could not translate host name "postgres1" to address: Name or service not known
2021-05-06 23:24:40,614 INFO: Lock owner: postgres1; I am postgres3
2021-05-06 23:24:40,614 INFO: does not have lock
2021-05-06 23:24:41.750 UTC [73288] FATAL:  could not connect to the primary server: could not translate host name "postgres1" to address: Name or service not known
2021-05-06 23:24:42,619 INFO: no action.  i am a secondary and i am following a leader
2021-05-06 23:24:46.750 UTC [73291] FATAL:  could not connect to the primary server: could not translate host name "postgres1" to address: Name or service not known
2021-05-06 23:24:50,613 INFO: Lock owner: postgres1; I am postgres3
2021-05-06 23:24:50,613 INFO: does not have lock
2021-05-06 23:24:51.754 UTC [73296] FATAL:  could not connect to the primary server: could not translate host name "postgres1" to address: Name or service not known
2021-05-06 23:24:52,617 INFO: no action.  i am a secondary and i am following a leader
2021-05-06 23:24:56.756 UTC [73301] FATAL:  could not connect to the primary server: could not translate host name "postgres1" to address: Name or service not known
2021-05-06 23:25:00,614 INFO: Lock owner: postgres1; I am postgres3
2021-05-06 23:25:00,614 INFO: does not have lock

This continued in a loop overnight on both standbys..

**Have you tried to use GitHub issue search?**
yes
