### ISSUE TITLE
Patroni w/ Raft in Docker fails to start when using service hostnames for PATRONI_RAFT_PARTNER_ADDRS

### ISSUE THREAD

**Issue by The-TT-Hacker** [zalando/patroni#1931]
**Describe the bug**

Starting up a 3 node Patroni cluster in docker swarm using Raft for DCS will fail to start when you use hostnames instead of IP addresses because docker dynamically adds and removes DNS entries when containers startup and shut down. During the Raft bootstrap process each node will try to resolve each others hostnames, however the first node docker starts will immediately fail because the hostnames of the other 2 have not been entered into the DNS yet. The services will keep starting up and failing immediately unless they happen to all start at the exact same time which is rare. I solved this by adding a sleep in the entry-point script so that all services start before Patroni starts and tries resolve the hostnames, however this does not solve the scenario where 1 of the 3 servers is down and one of the other nodes restarts as it will never be able to resolve the hostname of the node which is down on startup.

Other projects which implement distributed consensus algorithms such as all the other DCS options Patroni supports do not seem to have this problem. I haven't looked into how they solve it, but maybe Patroni has to perform some DNS resolution retries for the partner nodes and then if it is unsuccessful behave as if that node is down instead of crashing out of the program.

I also tried assigning static IP addresses to the services to remove the DNS resolution but it seems like docker overlay networks do not support static IPs for docker services.

**To Reproduce**

Use this setup https://github.com/SPG-Controls/patroni-raft-docker/blob/main/docker-compose.yml

set the INIT_WAIT_TIME environment variable to 0 to remove the sleep in the entry-point script
start the stack

**Expected behavior**

Patroni w/ Raft should be able to:
- bootstrap a quorum in a dynamic environment like docker swarm
- behave as if a node is down when the DNS resolution for it fails

**Environment**
- Patroni version: 2.0.2 99626a07f23151aa1abd63b9fb07819ab10e6900
- PostgreSQL version: 13
- DCS (and its version): Raft

**Patroni configuration file**
```
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_node_count: 1

    postgresql:
      parameters:
        max_connections: 256
      use_pg_rewind: true
      remove_data_directory_on_diverged_timelines: false
      remove_data_directory_on_rewind_failure: true

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication replicator 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 256
  remove_data_directory_on_diverged_timelines: false
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: true
synchronous_node_count: 1
ttl: 30
```

**Have you checked Patroni logs?**

2021-05-07 00:36:42,610 WARNING: failed to resolve host postgres1
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pysyncobj/syncobj.py", line 520, in _autoTickThread
    self._onTick(self.__conf.autoTickPeriod)
  File "/usr/local/lib/python3.7/dist-packages/patroni/dcs/raft.py", line 251, in _onTick
    super(KVStoreTTL, self)._onTick(timeToWait)
  File "/usr/local/lib/python3.7/dist-packages/pysyncobj/syncobj.py", line 614, in _onTick
    callback()
  File "/usr/local/lib/python3.7/dist-packages/pysyncobj/transport.py", line 302, in _onTick
    self._connectIfNecessary()
  File "/usr/local/lib/python3.7/dist-packages/pysyncobj/transport.py", line 423, in _connectIfNecessary
    self._connectIfNecessarySingle(node)
  File "/usr/local/lib/python3.7/dist-packages/pysyncobj/transport.py", line 415, in _connectIfNecessarySingle
    return self._connections[node].connect(node.ip, node.port)
  File "/usr/local/lib/python3.7/dist-packages/pysyncobj/tcp_connection.py", line 76, in connect
    self.__socket = socket.socket(_getAddrType(host), socket.SOCK_STREAM)
  File "/usr/local/lib/python3.7/dist-packages/pysyncobj/tcp_connection.py", line 20, in _getAddrType
    socket.inet_aton(addr)
TypeError: inet_aton() argument 1 must be str, not None

**Have you tried to use GitHub issue search?**
Yes
