### ISSUE TITLE
Raft cluster initialization has been in the wait state

### ISSUE THREAD

**Issue by cobolbaby** [zalando/patroni#1951]
**Describe the bug**

The following are three container orchestration configurations. The v1 version starts normally, but if an instance is down, the dns parsing exception will be reported when the patroni command is executed. In the other two ways, the cluster cannot be started normally at all.

**To Reproduce**

- v1

```
version: '3'

services:
  pg11:
    image: registry.inventec/infra/postgres:12.7-raft
    hostname: pg11
    environment:
      PATRONI_NAME: pg11
      PATRONI_ENABLE: 'true'
      PATRONI_NAMESPACE: pgcluster_raft
      PATRONI_SCOPE: pgcluster_12_5_raft
      PATRONI_RAFT_SELF_ADDR: "pg11:2222"
      PATRONI_RAFT_PARTNER_ADDRS: "'pg22:2222','pg33:2222'"
      PATRONI_RAFT_DATA_DIR: /tmp/raft/datadir
      #PATRONI_LOG_LEVEL: DEBUG
    ports:
      - "5833:5432"
      - "8418:8008"
    networks:
      - patroni-raft
  pg22:
    image: registry.inventec/infra/postgres:12.7-raft
    hostname: pg22
    environment:
      PATRONI_NAME: pg22
      PATRONI_ENABLE: 'true'
      PATRONI_NAMESPACE: pgcluster_raft
      PATRONI_SCOPE: pgcluster_12_5_raft
      PATRONI_RAFT_SELF_ADDR: "pg22:2222"
      PATRONI_RAFT_PARTNER_ADDRS: "'pg11:2222','pg33:2222'"
      PATRONI_RAFT_DATA_DIR: /tmp/raft/datadir
      #PATRONI_LOG_LEVEL: DEBUG
    ports:
      - "5834:5432"
      - "8428:8008"
    networks:
      - patroni-raft
  pg33:
    image: registry.inventec/infra/postgres:12.7-raft
    hostname: pg33
    environment:
      PATRONI_NAME: pg33
      PATRONI_ENABLE: 'true'
      PATRONI_NAMESPACE: pgcluster_raft
      PATRONI_SCOPE: pgcluster_12_5_raft
      PATRONI_RAFT_SELF_ADDR: "pg33:2222"
      PATRONI_RAFT_PARTNER_ADDRS: "'pg11:2222','pg22:2222'"
      PATRONI_RAFT_DATA_DIR: /tmp/raft/datadir
      #PATRONI_LOG_LEVEL: DEBUG
    ports:
      - "5835:5432"
      - "8438:8008"
    networks:
      - patroni-raft
networks:
  patroni-raft:
    external:
      name: patroni-raft
```

![2021-06-09 18-10-01屏幕截图](https://user-images.githubusercontent.com/11460848/121336197-df3e5100-c94d-11eb-97a8-8431c46cd005.png)

- v2

```
version: '3'
  
services:
  pg11:
    image: registry.inventec/infra/postgres:12.7-raft
    hostname: pg11
    environment:
      PATRONI_NAME: pg11
      PATRONI_ENABLE: 'true'
      PATRONI_NAMESPACE: pgcluster_raft
      PATRONI_SCOPE: pgcluster_12_5_raft
      PATRONI_RAFT_SELF_ADDR: "pg11:2222"
      PATRONI_RAFT_PARTNER_ADDRS: "'pg22:2223','pg33:2224'"
      PATRONI_RAFT_DATA_DIR: /tmp/raft/datadir
      #PATRONI_LOG_LEVEL: DEBUG
    ports:
      - "5833:5432"
      - "8418:8008"
      - "2222:2222"
    networks:
      - patroni-raft
    extra_hosts:
      - pg11:10.191.7.22
      - pg22:10.191.7.22
      - pg33:10.191.7.22
  pg22:
    image: registry.inventec/infra/postgres:12.7-raft
    hostname: pg22
    environment:
      PATRONI_NAME: pg22
      PATRONI_ENABLE: 'true'
      PATRONI_NAMESPACE: pgcluster_raft
      PATRONI_SCOPE: pgcluster_12_5_raft
      PATRONI_RAFT_SELF_ADDR: "pg22:2223"
      PATRONI_RAFT_PARTNER_ADDRS: "'pg11:2222','pg33:2224'"
      PATRONI_RAFT_DATA_DIR: /tmp/raft/datadir
      #PATRONI_LOG_LEVEL: DEBUG
    ports:
      - "5834:5432"
      - "8428:8008"
      - "2223:2223"
    networks:
      - patroni-raft
    extra_hosts:
      - pg11:10.191.7.22
      - pg22:10.191.7.22
      - pg33:10.191.7.22
  pg33:
    image: registry.inventec/infra/postgres:12.7-raft
    hostname: pg33
    environment:
      PATRONI_NAME: pg33
      PATRONI_ENABLE: 'true'
      PATRONI_NAMESPACE: pgcluster_raft
      PATRONI_SCOPE: pgcluster_12_5_raft
      PATRONI_RAFT_SELF_ADDR: "pg33:2224"
      PATRONI_RAFT_PARTNER_ADDRS: "'pg11:2222','pg22:2223'"
      PATRONI_RAFT_DATA_DIR: /tmp/raft/datadir
      #PATRONI_LOG_LEVEL: DEBUG
    ports:
      - "5835:5432"
      - "8438:8008"
      - "2224:2224"
    networks:
      - patroni-raft
    extra_hosts:
      - pg11:10.191.7.22
      - pg22:10.191.7.22
      - pg33:10.191.7.22
networks:
  patroni-raft:
    external:
      name: patroni-raft
```

- v3

```
version: '3'
  
services:
  pg11:
    image: registry.inventec/infra/postgres:12.7-raft
    hostname: pg11
    environment:
      PATRONI_NAME: pg11
      PATRONI_ENABLE: 'true'
      PATRONI_NAMESPACE: pgcluster_raft
      PATRONI_SCOPE: pgcluster_12_5_raft
      PATRONI_RAFT_SELF_ADDR: "10.191.7.22:2222"
      PATRONI_RAFT_PARTNER_ADDRS: "'10.191.7.22:2223','10.191.7.22:2224'"
      PATRONI_RAFT_DATA_DIR: /tmp/raft/datadir
      #PATRONI_LOG_LEVEL: DEBUG
    ports:
      - "5833:5432"
      - "8418:8008"
      - "2222:2222"
    networks:
      - patroni-raft
  pg22:
    image: registry.inventec/infra/postgres:12.7-raft
    hostname: pg22
    environment:
      PATRONI_NAME: pg22
      PATRONI_ENABLE: 'true'
      PATRONI_NAMESPACE: pgcluster_raft
      PATRONI_SCOPE: pgcluster_12_5_raft
      PATRONI_RAFT_SELF_ADDR: "10.191.7.22:2223"
      PATRONI_RAFT_PARTNER_ADDRS: "'10.191.7.22:2222','10.191.7.22:2224'"
      PATRONI_RAFT_DATA_DIR: /tmp/raft/datadir
      #PATRONI_LOG_LEVEL: DEBUG
    ports:
      - "5834:5432"
      - "8428:8008"
      - "2223:2223"
    networks:
      - patroni-raft
  pg33:
    image: registry.inventec/infra/postgres:12.7-raft
    hostname: pg33
    environment:
      PATRONI_NAME: pg33
      PATRONI_ENABLE: 'true'
      PATRONI_NAMESPACE: pgcluster_raft
      PATRONI_SCOPE: pgcluster_12_5_raft
      PATRONI_RAFT_SELF_ADDR: "10.191.7.22:2224"
      PATRONI_RAFT_PARTNER_ADDRS: "'10.191.7.22:2222','10.191.7.22:2223'"
      PATRONI_RAFT_DATA_DIR: /tmp/raft/datadir
      #PATRONI_LOG_LEVEL: DEBUG
    ports:
      - "5835:5432"
      - "8438:8008"
      - "2224:2224"
    networks:
      - patroni-raft
networks:
  patroni-raft:
    external:
      name: patroni-raft
```

**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: 12.7
- DCS (and its version): Raft

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

![2021-06-09 17-54-31屏幕截图](https://user-images.githubusercontent.com/11460848/121333789-af8e4980-c94b-11eb-9979-7714655a9342.png)

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
