### ISSUE TITLE
Patroni restarting cluster-replica for no explicit reason

### ISSUE THREAD

**Issue by iomatters** [zalando/patroni#1952]
**Describe the bug**
One of the cluster replicas gets restarted on the permanent basis, like once per 10 days at about the same time.

**Environment**
- Patroni version: patroni v 1.6.5
- PostgreSQL version: 11.8
- DCS (and its version): etcd v3.2.21
- OS: CentOS 7

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: test ! -f /pgwal/pg_arch/%f && cp %p /pgwal/pg_arch/%f
    archive_mode: 'on'
    auto_explain.log_analyze: true
    auto_explain.log_min_duration: 1000ms
    autovacuum_analyze_scale_factor: 0.05
    autovacuum_analyze_threshold: 50
    autovacuum_max_workers: 5
    autovacuum_naptime: 1s
    autovacuum_vacuum_cost_delay: 5ms
    autovacuum_vacuum_cost_limit: -1
    autovacuum_vacuum_scale_factor: 0.05
    autovacuum_vacuum_threshold: 50
    checkpoint_completion_target: 0.9
    default_statistics_target: 100
    effective_io_concurrency: 200
    hot_standby_feedback: true
    listen_addresses: '*'
    log_autovacuum_min_duration: 250
    logging_collector: true
    max_connections: 1000
    max_parallel_workers: 8
    max_parallel_workers_per_gather: 2
    max_standby_archive_delay: 7200s
    max_standby_streaming_delay: 7200s
    max_worker_processes: 8
    random_page_cost: 1.1
    session_preload_libraries: auto_explain
    vacuum_cost_delay: 0
    vacuum_cost_limit: 200
    vacuum_cost_page_dirty: 5
    vacuum_cost_page_hit: 0
    vacuum_cost_page_miss: 5
    vacuum_defer_cleanup_age: 5
    wal_keep_segments: 1000
    work_mem: 8MB
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
Please see the latest debug logs.
2021-06-09 12:15:07,080 DEBUG: API thread: 10.106.10.100 - - [09/Jun/2021 12:15:07] OPTIONS /master 503 latency: 0.9207725524902344 ms
2021-06-09 12:15:07,341 DEBUG: API thread: 10.106.10.100 - - [09/Jun/2021 12:15:07] OPTIONS /replica 200 latency: 0.7572174072265625 ms
2021-06-09 12:15:07,735 DEBUG: API thread: 10.106.10.99 - - [09/Jun/2021 12:15:07] OPTIONS /master 503 latency: 0.9381771087646484 ms
2021-06-09 12:15:08,096 DEBUG: API thread: 10.106.10.99 - - [09/Jun/2021 12:15:08] OPTIONS /replica 200 latency: 0.8816719055175781 ms
2021-06-09 12:15:08,335 DEBUG: API thread: 10.106.10.98 - - [09/Jun/2021 12:15:08] OPTIONS /replica 200 latency: 0.9558200836181641 ms
2021-06-09 12:15:08,335 DEBUG: API thread: 10.106.10.98 - - [09/Jun/2021 12:15:08] OPTIONS /master 503 latency: 1.9803047180175781 ms
2021-06-09 12:15:09,791 DEBUG: Issuing read for key /service/rca/ with args {'recursive': True, 'retry': <patroni.utils.Retry object at 0x7f9641688ba8>}
2021-06-09 12:15:09,791 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2021-06-09 12:15:09,793 DEBUG: http://10.106.10.98:2379 "GET /v2/keys/service/rca/?recursive=true HTTP/1.1" 200 None
2021-06-09 12:15:09,795 INFO: Lock owner: psql4; I am psql5
2021-06-09 12:15:09,795 INFO: does not have lock
2021-06-09 12:15:09,824 DEBUG: Writing {"conn_url":"postgres://10.106.10.108:5432/postgres","api_url":"http://10.106.10.108:8008/patroni","state":"running","
role":"replica","version":"1.6.5"} to key /service/rca/members/psql5 ttl=30 dir=False append=False
2021-06-09 12:15:09,824 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2021-06-09 12:15:09,827 DEBUG: http://10.106.10.98:2379 "PUT /v2/keys/service/rca/members/psql5 HTTP/1.1" 200 751
2021-06-09 12:15:09,827 INFO: no action.  i am a secondary and i am following a leader
2021-06-09 12:15:10,085 DEBUG: API thread: 10.106.10.100 - - [09/Jun/2021 12:15:10] OPTIONS /master 503 latency: 1.1162757873535156 ms
**2021-06-09 12:15:10,297 INFO: closed patroni connection to the postgresql cluster
2021-06-09 12:15:10,335 DEBUG: Starting postgres: /usr/pgsql-11/bin/postgres -D /data/postdata/11 --config-file=/data/postdata/11/postgresql.conf --listen_addresses=0.0.0.0 --port=5432 --cluster_name=rca --wal_level=replica --hot_standby=on --max_connections=1000 --max_wal_senders=10 --max_prepared_transactions=0 --max_locks_per_transaction=64 --track_commit_timestamp=off --max_replication_slots=10 --max_worker_processes=8 --wal_log_hints=on**
2021-06-09 12:15:10,347 DEBUG: API thread: 10.106.10.100 - - [09/Jun/2021 12:15:10] OPTIONS /replica 503 latency: 1.1715888977050781 ms
2021-06-09 12:15:10,739 DEBUG: API thread: 10.106.10.99 - - [09/Jun/2021 12:15:10] OPTIONS /master 503 latency: 0.7565021514892578 ms
2021-06-09 12:15:11,097 DEBUG: API thread: 10.106.10.99 - - [09/Jun/2021 12:15:11] OPTIONS /replica 503 latency: 0.6947517395019531 ms
2021-06-09 12:15:11,333 INFO: postmaster pid=8684
2021-06-09 12:15:11,339 DEBUG: API thread: 10.106.10.98 - - [09/Jun/2021 12:15:11] OPTIONS /master 503 latency: 2.1135807037353516 ms
2021-06-09 12:15:11,341 DEBUG: API thread: 10.106.10.98 - - [09/Jun/2021 12:15:11] OPTIONS /replica 503 latency: 1.9655227661132812 ms
2021-06-09 12:15:12,381 DEBUG: Issuing read for key /service/rca/ with args {'recursive': True, 'retry': <patroni.utils.Retry object at 0x7f9642cedd30>}
2021-06-09 12:15:12,382 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2021-06-09 12:15:12,384 DEBUG: http://10.106.10.98:2379 "GET /v2/keys/service/rca/?recursive=true HTTP/1.1" 200 None
2021-06-09 12:15:12,386 INFO: Lock owner: psql4; I am psql5

**Have you checked PostgreSQL logs?**
2021-06-09 12:15:09 MSK; [unknown]; [unknown]; 127.0.0.1(48442); 8665; %LOG:  connection received: host=127.0.0.1 port=48442
2021-06-09 12:15:09 MSK; postgres; postgres; 127.0.0.1(48442); 8665; %LOG:  connection authorized: user=postgres database=postgres
2021-06-09 12:15:10 MSK; postgres; postgres; 127.0.0.1(48442); 8665; %LOG:  disconnection: session time: 0:00:00.415 user=postgres database=postgres host=127
.0.0.1 port=48442
2021-06-09 12:15:10 MSK; ; ; ; 56803; %LOG:  received fast shutdown request
2021-06-09 12:15:10 MSK; ; ; ; 56803; %LOG:  aborting any active transactions

Any ideas ?

Thanks.
