### ISSUE TITLE
Confused in choosing the right loadbalancer and target group port in AWS for patroni cluster

### ISSUE THREAD

**Issue by rjoroy89** [zalando/patroni#1962]
Hi,

I would like to use AWS Load Balancer to connect to my patroni cluster but confused in choosing the right kind of it. I request your help on the same.

This is my environment details - 

Postgresql v12.6
Patroni v2.0.2
etcd v3.4.16
3 nodes installed with etcd, patroni, postgresql

My intention is to use an AWS Load balancer as the applications end-point which will identify the current patroni Leader/master and route the write traffic into it. 

I am also planning to have a pgBouncer(again on the same ec2 instance where the patroni cluster is deployed) infront of the patroni cluster for a better connection pooling in the future i.e, 

App --> Load Balancer --->pgBouncer ---> Patroni cluster

Please advise on the right type of  Load balancer I should employ here.

I tried the below as of now - 

Failed to create a Network Load Balancer which is based on the TCP protocol as it failed to detect the target group I created which is nothing but the ec2 instances in which the patroni cluster is running and the port assigned to create the target group was 5432. 

Created an ALB which is based on the HTTP protocol which detected the target group I created above but the target groups status is shown as unhealthy.

Please let me know if you need any further details and help!

Thanks in advance!!

Rijo Roy

**Comment by CyberDem0n** [comment]
Hi @rjoroy89,

> Please advise on the right type of Load balancer I should employ here.

ELB or NLB would perfectly work.

> Failed to create a Network Load Balancer which is based on the TCP protocol

I am failing to see how this problem is related to Patroni. Neither Patroni knows that it runs on AWS, nor NLB behavior is specific to Patroni. You can replace Patroni in this setup with anything else and bump into exactly the same issue.


If I would speak about NLB setup that we use, then I should notice that we also use autoscaling groups and deploy everything with cloudformation. Below you can find some snippets from the CFN:
```yaml
Resources:
  MyASG: 
    Type: AWS::AutoScaling::AutoScalingGroup 
    TargetGroupARNs: 
    - Ref: PostgresMasterTargetGroup 
... 
 
  PostgresNlb: 
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer 
    Properties: 
      Name: "spilo-mycluster-nlb" 
      Type: network 
      Scheme: internal 
      Subnets: [....] 
      LoadBalancerAttributes: 
      - Key: load_balancing.cross_zone.enabled 
        Value: 'true' 
  PostgresMasterTargetGroup:                               
    Type: AWS::ElasticLoadBalancingV2::TargetGroup 
    Properties: 
      Name: "spilo-mycluster-master" 
      HealthCheckEnabled: true 
      HealthCheckIntervalSeconds: 10 
      HealthCheckPath: /master 
      HealthCheckPort: 8008                         
      HealthCheckProtocol: HTTP          
      HealthCheckTimeoutSeconds: 6 
      HealthyThresholdCount: 2                            
      UnhealthyThresholdCount: 2 
      Port: 5432 
      Protocol: TCP 
      TargetType: instance 
      VpcId: 
        Ref: VpcId 
  PostgresNlbMasterListener:                
    Type: AWS::ElasticLoadBalancingV2::Listener 
    Properties:       
      DefaultActions: 
      - Type: forward 
        TargetGroupArn: 
          Ref: PostgresMasterTargetGroup 
      LoadBalancerArn: 
        Ref: PostgresNlb 
      Port: 5432 
      Protocol: TCP 
```

It is also important that instance security group allows access to the Postgres and Patroni REST API ports.
