### ISSUE TITLE
Problem with resync slave after failover.

### ISSUE THREAD

**Issue by gsl23** [zalando/patroni#1966]
Hi ! Thx for your excellent HA Postgtres software, but we have some problems with it. 
**Describe the bug**
Slave not resynced after failover and lag is growing.

**To Reproduce**
We have 3 node cluster 
+ Cluster: sks06lkmcpgdb 
| Member          | Host          | 
+-----------------+---------------+-
| sks06lkmcpgdb01 | 10.42.106.116 | 
| sks06lkmcpgdb02 | 10.42.106.117 | 
| sks06lkmcpgdb03 | 10.42.106.118 | 
+-----------------+---------------+-

sks06lkmcpgdb03 was master. We shutdown them, sks06lkmcpgdb01 became master and we bring up sks06lkmcpgdb03 after 10 minutes. 
sks06lkmcpgdb03 became slave but can't to resync :
+ Cluster: sks06lkmcpgdb (6727158758502842924) -------+----+-----------+-----------------+
| Member          | Host          | Role    | State   | TL | Lag in MB | Pending restart |
+-----------------+---------------+---------+---------+----+-----------+-----------------+
| sks06lkmcpgdb01 | 10.42.106.116 | Leader  | running | 27 |           | *               |
| sks06lkmcpgdb02 | 10.42.106.117 | Replica | running | 27 |       0.0 | *               |
| sks06lkmcpgdb03 | 10.42.106.118 | Replica | running | 26 |   11292.0 | *               |
+-----------------+---------------+---------+---------+----+-----------+-----------------+

In pg_log sks06lkmcpgdb03 we see 
< 2021-06-15 14:54:12.094 MSK > FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 0000001B0000198100000017 has already been removed

But this wal exists on master in archive : 
[root@sks06lkmcpgdb01 wal_archive]# ll 0000001B0000198100000017
-rw------- 1 postgres postgres 16777216 Jun 15 14:28 0000001B0000198100000017

Why patroni doesn't send it to slave to resync  ? 

**Expected behavior**
Send wals to salves and resync them.

**Environment**
- Patroni version: 9.6
- PostgreSQL version: 2.0.2
- DCS (and its version): Consul v1.7.1

**Patroni configuration file**
```

scope: sks06lkmcpgdb
#namespace: /service/
name: sks06lkmcpgdb03

restapi:
  listen: <removed>  
  connect_address: <removed>  
  auth: 'username:test'
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

consul:
  host: 127.0.0.1:8500

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: hot_standby
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 10
        max_replication_slots: 5
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
      recovery_conf:
        restore_command: cp ../wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
<removed>  

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

  # Some additional users users which needs to be created after initializing new cluster
#  users:
#    admin:
#      password: admin
#      options:
#        - createrole
#        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: <removed>  
  data_dir: /data/pg
  bin_dir: /usr/pgsql-9.6/bin
#  config_dir:
  pg_rewind:
    username: postgres
    password: ***
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: ***
    superuser:
      username: postgres
      password: ***
  parameters:
    shared_preload_libraries: 'pg_stat_statements,pg_cron'
    unix_socket_directories: /run/postgresql
    max_connections: '2000'
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    shared_buffers: 4096MB
    checkpoint_completion_target: 0.9
    autovacuum_naptime: 20s
    autovacuum_max_workers: 10
    bgwriter_delay: 20ms
    bgwriter_lru_multiplier: 4.0
    bgwriter_lru_maxpages: 400
    work_mem: 128MB
    lo_compat_privileges: 'on'
    max_standby_archive_delay: 900s
    max_standby_streaming_delay: 1200s
    track_activity_query_size: 2048

```

**patronictl show-config**
```
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
    archive_mode: 'on'
    archive_timeout: 1800s
    hot_standby: 'on'
    max_replication_slots: 5
    max_wal_senders: 10
    wal_keep_segments: 8
    wal_level: hot_standby
    wal_log_hints: 'on'
  recovery_conf:
    restore_command: cp ../wal_archive/%f %p
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
ttl: 30


```
