### ISSUE TITLE
Warning when setting restore_command in postgresql.parameters

### ISSUE THREAD

**Issue by cbandy** [zalando/patroni#1992]
I'm deploying PostgreSQL 12 and 13 clusters and using pgBackRest to archive WAL files. I want replicas to fetch WAL from the archive when they are too far behind for streaming replication, so I've configured a `restore_command` in `postgresql.parameters`.

**Describe the bug**
Patroni emits a WARNING when starting a replica this way. The warning seems unjustified because Patroni recognizes the parameter and includes it in `postgresql.conf`.

```
2021-06-30 15:27:27,901 INFO: starting as a secondary
2021-06-30 15:27:27,912 WARNING: Removing unexpected parameter=restore_command value=pgbackrest --stanza=main archive-get %f "%p" from the config
2021-06-30 15:27:28.190 UTC [93] LOG:  starting PostgreSQL 12.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5), 64-bit
```

```
$ grep _command postgresql.conf
archive_command = 'pgbackrest --stanza=main archive-push "%p"'
restore_command = 'pgbackrest --stanza=main archive-get %f "%p"'
```

The [documentation for `postgresql.recovery_conf`](https://patroni.readthedocs.io/en/latest/SETTINGS.html) seems to say that the section isn't necessary since PostgreSQL 12, and I would prefer to put my `archive_command` and `restore_command` next to each other in `postgresql.parameters`. 

**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: 12.7
- DCS (and its version): Kubernetes, 1.18.15

**Patroni configuration file**
```
kubernetes:
  namespace: postgres
  role_label: postgres-role
  scope_label: postgres-patroni
  use_endpoints: true
postgresql:
  pgpass: /tmp/.pgpass
  use_unix_socket: true
scope: postgres-ha
```

**patronictl show-config**
```
loop_wait: 10
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=main archive-push "%p"
    archive_mode: 'on'
    restore_command: pgbackrest --stanza=main archive-get %f "%p"
    wal_level: logical
  pg_hba:
  - local all "postgres" peer
  - host all all all md5
  use_pg_rewind: true
  use_slots: false
ttl: 30
```
