### ISSUE TITLE
etcd3 proxy spam warnings

### ISSUE THREAD

**Issue by gangybas** [zalando/patroni#2006]
**Describe the bug**
When using etcd on a k8s cluster, patronictl spam "WARNING - failed to resolve host etcd-*.etcd-headless.test-etcd.svc.cluster.local"

**Screenshots**
![image](https://user-images.githubusercontent.com/31967223/125116894-12fbca80-e0f6-11eb-8ee7-83cfbf3df022.png)

**Environment**
- Patroni version: 2.1.0
- DCS (and its version): etcd: 3.4.16

**Patroni configuration file**
```
scope: test
namespace: /main/
name: db1_test

log:
  level: ERROR
  loggers:
    patroni.postmaster: ERROR
    urllib3: ERROR
  dir: /var/log/postgresql/

restapi:
    listen: 192.168.136.228:8008
    connect_address: 192.168.136.228:8008
etcd3:
  proxy: http://root:Qwerty123@192.168.136.131:2379
  use_proxies: true
  username: root
  password: Qwerty123
bootstrap:
    dcs:
      loop_wait: 10
      maximum_lag_on_failover: 1048576
      postgresql:
        parameters:
          autovacuum: 'on'
          autovacuum_analyze_scale_factor: '0.1'
          autovacuum_analyze_threshold: '1000'
          autovacuum_freeze_max_age: '1000000000'
          autovacuum_max_workers: '3'
          autovacuum_naptime: 5min
          autovacuum_vacuum_cost_delay: 20ms
          autovacuum_vacuum_cost_limit: '-1'
          autovacuum_vacuum_scale_factor: '0.2'
          autovacuum_vacuum_threshold: '1000'
          checkpoint_completion_target: '0.7'
          checkpoint_timeout: 5min
          client_min_messages: notice
          default_statistics_target: '100'
          effective_cache_size: 18GB
          effective_io_concurrency: '200'
          fsync: 'off'
          hot_standby: 'on'
          hot_standby_feedback: 'on'
          log_autovacuum_min_duration: '250'
          log_connections: 'on'
          log_destination: stderr
          log_directory: pg_log
          log_disconnections: 'on'
          log_duration: 'off'
          log_error_verbosity: default
          log_filename: postgresql-%H.log
          log_hostname: 'off'
          log_line_prefix: '%t:[%p]::[%l-1]:'
          log_min_duration_statement: '0'
          log_min_error_statement: error
          log_min_messages: warning
          log_rotation_age: '60'
          log_rotation_size: '1024000'
          log_statement: none
          log_truncate_on_rotation: 'on'
          logging_collector: 'on'
          maintenance_work_mem: 1536MB
          max_connections: '200'
          max_files_per_process: '1000'
          max_parallel_workers_per_gather: '4'
          max_standby_streaming_delay: 100s
          max_wal_senders: '3'
          max_wal_size: 2GB
          max_worker_processes: '8'
          min_wal_size: 1GB
          random_page_cost: '1.1'
          shared_buffers: 6GB
          standard_conforming_strings: 'off'
          track_activities: 'on'
          track_activity_query_size: '8192'
          track_counts: 'on'
          update_process_title: 'on'
          vacuum_cost_delay: 5ms
          vacuum_cost_limit: '200'
          vacuum_cost_page_dirty: '50'
          vacuum_cost_page_hit: '1'
          vacuum_cost_page_miss: '100'
          wal_buffers: 16MB
          wal_keep_segments: '200'
          wal_level: hot_standby
          work_mem: 7864kB
        use_pg_rewind: true
      retry_timeout: 10
      ttl: 30
    initdb:
      - encoding: UTF8
      - data-checksums
      - locale: en_US.UTF8
      - directory: /etc/postgresql/9.6/main
      - pgdata: /mnt/base/postgresql/9.6/main
    pg_hba:
      - local all all    trust
      - host all all 127.0.0.1/32   md5
      - host all all ::1/128   md5
      - host replication postgres 192.168.136.228/32   trust
      - host replication postgres 192.168.136.229/32   trust

postgresql:
    listen: "*:5432"
    bin_dir: /usr/lib/postgresql/9.6/bin
    config_dir: /etc/postgresql/9.6/main
    connect_address: 192.168.136.228:5432
    data_dir: /mnt/base/postgresql/9.6/main/
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: postgres
            password: postgres
        superuser:
            username: postgres
            password: postgres
    create_replica_methods:
        basebackup:
    parameters:
        unix_socket_directories: '/var/run/postgresql'
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    autovacuum: 'on'
    autovacuum_analyze_scale_factor: '0.1'
    autovacuum_analyze_threshold: '1000'
    autovacuum_freeze_max_age: '1000000000'
    autovacuum_max_workers: '3'
    autovacuum_naptime: 5min
    autovacuum_vacuum_cost_delay: 20ms
    autovacuum_vacuum_cost_limit: '-1'
    autovacuum_vacuum_scale_factor: '0.2'
    autovacuum_vacuum_threshold: '1000'
    checkpoint_completion_target: '0.7'
    checkpoint_timeout: 5min
    client_min_messages: notice
    default_statistics_target: '100'
    effective_cache_size: 18GB
    effective_io_concurrency: '200'
    fsync: 'off'
    hot_standby: 'on'
    hot_standby_feedback: 'on'
    log_autovacuum_min_duration: '250'
    log_connections: 'on'
    log_destination: stderr
    log_directory: pg_log
    log_disconnections: 'on'
    log_duration: 'off'
    log_error_verbosity: default
    log_filename: postgresql-%H.log
    log_hostname: 'off'
    log_line_prefix: '%t:[%p]::[%l-1]:'
    log_min_duration_statement: '0'
    log_min_error_statement: error
    log_min_messages: warning
    log_rotation_age: '60'
    log_rotation_size: '1024000'
    log_statement: none
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    maintenance_work_mem: 1536MB
    max_connections: '200'
    max_files_per_process: '1000'
    max_parallel_workers_per_gather: '4'
    max_standby_streaming_delay: 100s
    max_wal_senders: '3'
    max_wal_size: 2GB
    max_worker_processes: '8'
    min_wal_size: 1GB
    random_page_cost: '1.1'
    shared_buffers: 6GB
    standard_conforming_strings: 'off'
    track_activities: 'on'
    track_activity_query_size: '8192'
    track_counts: 'on'
    update_process_title: 'on'
    vacuum_cost_delay: 5ms
    vacuum_cost_limit: '200'
    vacuum_cost_page_dirty: '50'
    vacuum_cost_page_hit: '1'
    vacuum_cost_page_miss: '100'
    wal_buffers: 16MB
    wal_keep_segments: '200'
    wal_level: hot_standby
    work_mem: 7864kB
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```
