### ISSUE TITLE
 %ERROR:  cannot execute SQL commands in WAL sender for physical replication

### ISSUE THREAD

**Issue by iomatters** [zalando/patroni#2013]
**Describe the bug**
Possibly something wrong with my setup, though patronictl list indicates the cluster is operational.
+ Cluster: MYCLUSTER (6896971026107035679) ----+---------+----+-----------+
| Member        | Host         | Role    | State   | TL | Lag in MB |
+---------------+--------------+---------+---------+----+-----------+
| D3-ARK-DB01   | 10.101.4.166 | Leader  | running |  4 |           |
| D3-ARK-PATR01 | 10.101.4.157 | Replica | running |  4 |         0 |
| D3-ARK-PATR02 | 10.101.4.158 | Replica | running |  4 |         0 |
| D3-ARK-PATR03 | 10.101.4.159 | Replica | running |  4 |         0 |
+---------------+--------------+---------+---------+----+-----------+

Leader is generating tons of errors referring to the replicas:
2021-07-21 00:40:37 UTC; [unknown]; replicator; 10.101.4.159(35178); 2130325; %ERROR:  cannot execute SQL commands in WAL sender for physical replication
2021-07-21 00:40:37 UTC; [unknown]; replicator; 10.101.4.157(36128); 2130326; %ERROR:  cannot execute SQL commands in WAL sender for physical replication

On replicas:
2021-07-21 00:38:51 UTC; [unknown]; replicator; 127.0.0.1(57390); 1663596; %ERROR:  cannot execute SQL commands in WAL sender for physical replication
2021-07-21 00:38:52 UTC; [unknown]; replicator; 127.0.0.1(57394); 1663598; %ERROR:  cannot execute SQL commands in WAL sender for physical replication

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
- Patroni version: 2.1.0
- PostgreSQL version: 12.5
- DCS (and its version): 

**Patroni configuration file**
```
scope: MYCLUSTER
name: DB-PATR01

restapi:
    listen: 10.101.4.157:8008
    connect_address: 10.101.4.157:8008

etcd:
    hosts: 10.101.4.154:2379,10.101.4.155:2379,10.101.4.156:2379


bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.101.4.166/32 md5
    - host replication replicator 10.101.4.157/32 md5
    - host replication replicator 10.101.4.158/32 md5
    - host replication replicator 10.101.4.159/32 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 0.0.0.0
    bin_dir: /usr/pgsql-12/bin
    connect_address: 10.101.4.157:5432
    #data_dir: /data/db/12/data
    data_dir: /data/pgsql/12/data
    pgpass: /var/lib/pgsql_stats_tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: pass
        superuser:
            username: postgres
            password: pass
    parameters:
        max_connections: '100'
        shared_buffers: 4GB
        effective_cache_size: 12GB
        maintenance_work_mem: 1GB
        checkpoint_completion_target:  0.9
        wal_buffers: 16MB
        default_statistics_target: 100
        random_page_cost: 4
        effective_io_concurrency: 2
        work_mem: 5242kB
        min_wal_size: 1GB
        max_wal_size: 4GB
        max_worker_processes: 8
        max_parallel_workers_per_gather: 4
        max_parallel_workers: 8
        max_parallel_maintenance_workers: 4
        shared_preload_libraries: 'pg_stat_statements'
        log_directory: 'log'
        log_filename: 'postgresql-%Y-%m-%d_%H%M%S.log'
        log_rotation_size: 30MB
        logging_collector: on
        listen_addresses: '*'
        wal_level: 'replica'
        unix_socket_directories: '/var/run/postgresql'
        stats_temp_directory: '/var/lib/pgsql_stats_tmp'
        archive_mode: 'on'
        archive_command: 'test ! -f /data/pgwal/pg_arch/%f && cp %p /data/pgwal/pg_arch/%f'
        log_line_prefix: '%t; %d; %u; %r; %p; %%'
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**

pg_hba.conf
```
# "local" is for Unix domain socket connections only

local   all             postgres                                trust
local   all             all                                     trust

# IPv4 local connections:
host    all             postgres        10.101.4.172/32         trust
host    all             all             127.0.0.1/32            md5
host    all             all             0.0.0.0/0               md5

# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     md5
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
host    replication     replicator      127.0.0.1/32            md5

host    replication     replicator      10.101.4.167/32         md5
host    replication     replicator      10.101.4.166/32         md5
host    replication     replicator      10.101.4.157/32         md5
host    replication     replicator      10.101.4.158/32         md5
host    replication     replicator      10.101.4.159/32         md5
```
