### ISSUE TITLE
[Postgres cluster with patroni]One replica can be easily out of sync with leader when it's not sync at first and then leader changed.

### ISSUE THREAD

**Issue by Jane20161130** [zalando/patroni#2022]
**Describe the bug**
**Deployed a 3 nodes timescaledb-single cluster with latest release [v0.8.2] - 2021-01-14 in kubernetes v1.19.2. 
One replica can be easily out of sync with leader when it's not sync at first and then leader changed.**
https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-single

https://github.com/zalando/patroni/issues/1267

**To Reproduce**
1. In the beginning, 3 db nodes are all synced(node 0, node 1, node 2) , use_slot: true, use_rewind: true, wal_keep_segments is 1, node 0 is the leader node.
2. Start to insert data into db continuously.
3. Shutdown one replica(node 1) VM.
4. Stop inserting data into db after inserted more than 16MB data
5.  Swithover leader from node 0 to node 2. Now node 2 is the leader node.
6. Start to insert data into db continuously.
7. Stop inserting data into db after inserted more than 16MB data.
8. Stop inserting data into db.
9. Power on node 1 VM, node 1 will be out of sync with leader node.

**Expected behavior**
The replica node can synced with leader node in above scenario.

**Screenshots**
When leader changed at reproduce step 5, the 2 replica physical slots will be re-created on new leader node 2. Just the same with issue mentioned https://github.com/zalando/patroni/issues/1267
**My question is, is it possible to copy the physical slot from the old master/create the same physical slot with the old leader on the newly elected/promoted primary?**

**Environment**
- Patroni version: 2.0.1
- PostgreSQL version: 12
- DCS (and its version):

**Patroni configuration file**
```
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 0
    postgresql:
      parameters:
        archive_command: /etc/timescaledb/scripts/pgbackrest_archive.sh %p
        archive_mode: "on"
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 10
        autovacuum_naptime: 5s
        autovacuum_vacuum_cost_limit: 500
        autovacuum_vacuum_scale_factor: 0.05
        hot_standby: "on"
        log_autovacuum_min_duration: 1min
        log_checkpoints: "on"
        log_connections: "on"
        log_disconnections: "on"
        log_line_prefix: '%t [%p]: [%c-%l] %u@%d,app=%a [%e] '
        log_lock_waits: "on"
        log_min_duration_statement: 1s
        log_statement: ddl
        max_connections: 100
        max_prepared_transactions: 150
        shared_preload_libraries: timescaledb,pg_stat_statements
        ssl: "on"
        ssl_cert_file: /etc/certificate/tls.crt
        ssl_key_file: /etc/certificate/tls.key
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        temp_file_limit: 1GB
        timescaledb.passfile: ../.pgpass
        unix_socket_directories: /var/run/postgresql
        unix_socket_permissions: "0750"
        wal_keep_segments: 256
        wal_level: hot_standby
        wal_log_hints: "on"
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    slots:
      phy_slot_merck:
        type: physical
    standby_cluster:
      create_replica_methods:
      - basebackup
      primary_slot_name: phy_slot_merck
    ttl: 30
  method: restore_or_initdb
  post_init: /etc/timescaledb/scripts/post_init.sh
  restore_or_initdb:
    command: |
      /etc/timescaledb/scripts/restore_or_initdb.sh --encoding=UTF8 --locale=C.UTF-8
    keep_existing_recovery_conf: true
kubernetes:
  role_label: role
  scope_label: cluster-name
  use_endpoints: true
log:
  level: WARNING
postgresql:
  authentication:
    replication:
      username: standby
    superuser:
      username: postgres
  basebackup:
  - waldir: /var/lib/postgresql/wal/pg_wal
  callbacks:
    on_reload: /etc/timescaledb/scripts/patroni_callback.sh
    on_restart: /etc/timescaledb/scripts/patroni_callback.sh
    on_role_change: /etc/timescaledb/scripts/patroni_callback.sh
    on_start: /etc/timescaledb/scripts/patroni_callback.sh
    on_stop: /etc/timescaledb/scripts/patroni_callback.sh
  create_replica_methods:
  - pgbackrest
  - basebackup
  listen: 0.0.0.0:5432
  pg_hba:
  - local     all             postgres                              peer
  - local     all             all                                   md5
  - hostnossl all,replication all                all                reject
  - hostssl   all             all                127.0.0.1/32       md5
  - hostssl   all             all                ::1/128            md5
  - hostssl   replication     standby            all                md5
  - hostssl   all             all                all                md5
  pgbackrest:
    command: /etc/timescaledb/scripts/pgbackrest_restore.sh
    keep_data: true
    no_master: true
    no_params: true
  recovery_conf:
    restore_command: /etc/timescaledb/scripts/pgbackrest_archive_get.sh %f "%p"
  use_unix_socket: true
restapi:
  listen: 0.0.0.0:8008
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 0
postgresql:
  parameters:
    archive_command: /etc/timescaledb/scripts/pgbackrest_archive.sh %p
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 10
    autovacuum_naptime: 5s
    autovacuum_vacuum_cost_limit: 500
    autovacuum_vacuum_scale_factor: 0.05
    hot_standby: 'on'
    log_autovacuum_min_duration: 1min
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%c-%l] %u@%d,app=%a [%e] '
    log_lock_waits: 'on'
    log_min_duration_statement: 1s
    log_statement: ddl
    max_connections: 100
    max_prepared_transactions: 150
    shared_preload_libraries: timescaledb,pg_stat_statements
    ssl: 'on'
    ssl_cert_file: /etc/certificate/tls.crt
    ssl_key_file: /etc/certificate/tls.key
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    temp_file_limit: 1GB
    timescaledb.passfile: ../.pgpass
    unix_socket_directories: /var/run/postgresql
    unix_socket_permissions: '0750'
    wal_keep_segments: '1'
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
slots:
  phy_slot_merck:
    type: physical
standby_cluster:
  create_replica_methods:
  - basebackup
  primary_slot_name: phy_slot_merck
ttl: 30
```

**Comment by CyberDem0n** [comment]
> Power on node 1 VM, node 1 will be out of sync with leader node.

Something is fishy, according to your configs WAL files should be archived and the offline replica should be able to restore them from the archive. If it doesn't happen, the first thing you have to do - check postgres logs.

Also, the primary goal of Patroni i automatic failover, and it does it well. The rest is the best effort, nobody could implement 100% of it.

**Comment by Jane20161130** [comment]
Thank you for your feedback. Actually node 1 didn't restore from the archive. I will check postgres log soon.

**Comment by Jane20161130** [comment]
backup and bootstrapFromBackup are not enabled. I'm sorry that I have a question. restore from the archive, do you actually mean restore from backup?

**Comment by CyberDem0n** [comment]
I am talking about `archive_command` and `restore_command`: https://www.postgresql.org/docs/current/continuous-archiving.html

**Comment by CyberDem0n** [comment]
If names of all pods are known in advance you can always add them to permanent slots using `patronictl edit-config`
```yaml
slots:
  pod-0:
    type: physical
  pod-1:
    type: physical
```
