### ISSUE TITLE
etcd yaml file parameters not lining up with other parameters

### ISSUE THREAD

**Issue by drinking12many** [zalando/patroni#2023]
**Describe the bug**
When generating a yaml file for use with our cluster we are seeing issues setting up SSL using the following parameters: 

cacert: (optional) The ca certificate. If present it will enable validation.
cert: (optional) file with the client certificate.
key: (optional) file with the client key. Can be empty if the key is part of cert.

If I use these parameters I receive errors where etcd is telling me "tls: first record does not look like a handshake" on the Patroni side I see that in the error it's NOT using HTTPS in talking to the etcd system. If I change the parameters to "certfile" and "keyfile" I at least see in messages that it is attempting HTTPS in the URL. I believe that the YAML documentation may be incorrect and its causing issues getting our clusters set up as the parameters listed under etcd are not consistent with the naming in other sections for certificates. The example here https://github.com/zalando/patroni/blob/master/postgres0.yml also does not list the entries for SSL under etcd leading to further confusion on what the proper entries are. 

**To Reproduce**
attempt to use SSL with ETCd using the list YAML parameters in the documentation. 

**Expected behavior**
If the parameters are correct I would expect in /var/log/messages that I would at least see it's attempting an HTTPS connection. I only see this if I change it to "certfile" and "keyfile" otherwise the entries show HTTP.

**Environment**
- Patroni version: 2.1
- PostgreSQL version: 13.3
- DCS (and its version): Etcd 3.4.14

**Patroni configuration file**
```
unable to post full file due to client security - the relevant etcd section is 
etcd:
  hosts:
    - etcd1:2379
    - etcd2:2379
    - etcd3:2379
  protocol: https
  cacert: /var/lib/pgsql/certs/ca.pem   
  certfile: /var/lib/pgsql/certs/server-cert.pem #certfile seems to work vs cert to some level. 
  keyfile: /var/lib/pgsql/certs/server-key.pem #keyfile seems to work somewhat vs key as listed in documentation. 

```
If I use the "cert" and "key" listed in the documentation I get the following vs the "certfile" and "keyfile" which is consistent with other sections in the yaml. 
![image](https://user-images.githubusercontent.com/34074305/128230836-7b852ae7-33ea-457d-a8a2-4dd6d20c23ad.png)

Patroni is not fully starting. 
```

```

**Have you checked Patroni logs?**
Yes
![image](https://user-images.githubusercontent.com/34074305/128230853-606184f6-7792-4da9-ac8d-101202738c03.png)

**Have you checked PostgreSQL logs?**
not starting

**Have you tried to use GitHub issue search?**
yes
