### ISSUE TITLE
503 response on sync replica when querying /sync 

### ISSUE THREAD

**Issue by kolbasky** [zalando/patroni#2024]
**Describe the bug**
I have 3-node cluster with synchronous_commit = on and synchronous_standby_names = '*'.
I can see that one replica is in sync state via pg_stat_replication.
But when I curl -v http://%syncreplica%/sync i get 503 response.
Judging by docs https://patroni.readthedocs.io/en/latest/rest_api.html  request must return 200.

**Expected behavior**
I expect 200 response on sync replica.

**Screenshots**
![image](https://user-images.githubusercontent.com/42576088/128385200-fa380331-c24a-4ca2-9f18-4ab6ada06348.png)
![image](https://user-images.githubusercontent.com/42576088/128385383-407bea6e-09b1-4f25-9922-fc5de87c4ce6.png)

**Environment**
- Patroni version: 2.1.0
- PostgreSQL version: 13.3
- DCS (and its version): etcd 3.4.0

**Patroni configuration file**
```
scope: sandbox
namespace: /sandboxpg13/
name: sandboxpg13db3

restapi:
    listen: x.x.x.x:8008
    connect_address: x.x.x.x:8008

etcd:
    hosts: x.x.x.x
    username: asdasdasd
    password: asdasdasd
    protocol: https
    cacert: /etc/patroni/ca.crt


bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: false
            recovery_conf:
                restore_command: 'pgbackrest --stanza=sandboxpg13 archive-get %f %p'

    method: restore_with_pgbackrest
    restore_with_pgbackrest:
        command: /var/lib/pgsql/restore.sh
        recovery_conf:
            restore_command: 'pgbackrest --stanza=sandboxpg13 archive-get %f %p'
            recovery_target_timeline: latest
            recovery_target_action: promote
            recovery_target_time: '2021-07-07 15:19:00+03'

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host all zbx_monitor 127.0.0.1/32 trust
    - host all zbx_monitor 0.0.0.0/0 md5
    - host all zbx_monitor ::0/0 md5
    - local all all md5
    - host replication replica 127.0.0.1/32 md5
    - host replication replica x.x.x.x/24 md5
    - host replication replica x.x.x.x/24 md5
    - host replication replica x.x.x.x/24 md5
    - host all all 0.0.0.0/0 md5

    users:
        user:
            password: asdasdadsd%3
            options:
                - createrole
                - createdb

postgresql:
    create_replica_methods:
#       - pgbackrest
        - basebackup
    pgbackrest:
        command: pgbackrest --stanza=sandboxpg13 --delta --process-max=4 --link-all restore
        keep_data: True
        no_params: True
    basebackup:
        max-rate: '1000M'
    archive_command: 'pgbackrest --stanza=sandboxpg13 archive-push %p'
    listen: x.x.x.x:5432
    connect_address: x.x.x.x:5432
    data_dir: /data/patroni/
    pgpass: /tmp/pgpass
    recovery_conf:
        restore_command: 'pgbackrest --stanza=sandboxpg13 archive-get %f %p'
    authentication:
        replication:
            username: replication
            password: sadfadsf
        superuser:
            username: postgres
            password: gasdgsgfd
    parameters:
        unix_socket_directories: /var/run/postgresql
        archive_mode: on
        archive_command: pgbackrest --stanza=sandboxpg13 archive-push %p
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=sandboxpg13 archive-push %p
    archive_mode: true
    synchronous_commit: 'on'
    synchronous_standby_names: '*'
  pg_hba:
  - host all zbx_monitor 127.0.0.1/32 trust
  - host all zbx_monitor 0.0.0.0/0 md5
  - host all zbx_monitor ::0/0 md5
  - local all all trust
  - host replication replica 127.0.0.1/32 md5
  - host replication replica x.x.x.x/24 md5
  - host replication replica x.x.x.x/24 md5
  - host replication replica x.x.x.x/24 md5
  - host all all 0.0.0.0/0 md5
  recovery_conf:
    restore_command: pgbackrest --stanza=sandboxpg13 archive-get %f %p
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here
Aug 05 18:53:39 sandboxpg13db1.office.mow python[1505]: 2021-08-05 18:53:39,727 INFO: no action. I am a secondary (sandboxpg13db1) and following a leader (sandboxpg13db3)
Aug 05 18:53:49 sandboxpg13db1.office.mow python[1505]: 2021-08-05 18:53:49,720 INFO: no action. I am a secondary (sandboxpg13db1) and following a leader (sandboxpg13db3)
Aug 05 18:53:59 sandboxpg13db1.office.mow python[1505]: 2021-08-05 18:53:59,722 INFO: no action. I am a secondary (sandboxpg13db1) and following a leader (sandboxpg13db3)
Aug 05 18:54:09 sandboxpg13db1.office.mow python[1505]: 2021-08-05 18:54:09,724 INFO: no action. I am a secondary (sandboxpg13db1) and following a leader (sandboxpg13db3)
Aug 05 18:54:19 sandboxpg13db1.office.mow python[1505]: 2021-08-05 18:54:19,731 INFO: no action. I am a secondary (sandboxpg13db1) and following a leader (sandboxpg13db3)
Aug 05 18:54:29 sandboxpg13db1.office.mow python[1505]: 2021-08-05 18:54:29,728 INFO: no action. I am a secondary (sandboxpg13db1) and following a leader (sandboxpg13db3)
Aug 05 18:54:39 sandboxpg13db1.office.mow python[1505]: 2021-08-05 18:54:39,720 INFO: no action. I am a secondary (sandboxpg13db1) and following a leader (sandboxpg13db3)
Aug 05 18:54:49 sandboxpg13db1.office.mow python[1505]: 2021-08-05 18:54:49,726 INFO: no action. I am a secondary (sandboxpg13db1) and following a leader (sandboxpg13db3)

**Have you tried to use GitHub issue search?**
I treied but didn't find this situation.

I must be missing smth again. Please help.
