### ISSUE TITLE
archive_command does not change after API-call

### ISSUE THREAD

**Issue by mr-deamon** [zalando/patroni#2033]
**Describe the bug**
If archive_command is changed with patronictl edit-config or REST, parameter is not changed

**To Reproduce**
curl -s -XPATCH -d '{"postgresql":{"parameters":{"archive_command":"/bin/true"}}}' http://localhost:8008/config

**Expected behavior**
Parameter is changed in postgresql.conf

**Environment**
- Patroni version: 2.1.0
- PostgreSQL version: 13.3
- DCS (and its version): etcd 3.4.16

**Patroni configuration file**
```
scope: patroni_cluster_ptest
name: patroni_id-pgptest02
namespace: /service_prod

restapi:
  listen: 0.0.0.0:8008
  connect_address: 1.2.3.4:8008

etcd3:
  hosts: 'id-etcd01.xxx.ch:2379,id-etcd02.xxx.ch:2379,id-etcd03.xxx.ch:2379'
  protocol: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout : 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
    slots:
      barman:
        type: physical

  initdb:
  - encoding: UTF8
  - data-checksums
  - locale: en_US.UTF-8
  - lc-messages: en_US

  pg_hba:
    - host replication replicator 1.2.16.102/32 md5 #postgres/barman replication
    - host replication replicator 1.2.16.103/32 md5 #postgres/barman replication
    - local all all trust

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 1.2.16.109:5432
  data_dir: /var/lib/pgsql/patroni_cluster_ptest/13/data
  bin_dir: /usr/pgsql-13/bin
  parameters:
    max_connections: 1000
    shared_preload_libraries: pg_stat_statements
    statement_timeout: 1800000
    checkpoint_timeout: 20min
    logging_collector: on
    log_destination: stderr
    log_statement: ddl
    timed_statistics: on
    log_autovacuum_min_duration: 0
    log_lock_waits: on
    log_temp_files: 0
    log_filename: 'postgresql-%H.log'
    log_line_prefix: '%m [%p-%l] %u@%d app=%a '
    log_min_duration_statement: 1s
    log_connections: on
    log_checkpoints: on
    wal_compression: on
    autovacuum_max_workers: 5
    autovacuum_vacuum_cost_limit: 3000
    ssl: on
    ssl_cert_file: /var/lib/pgsql/ssl/server.crt
    ssl_key_file: /var/lib/pgsql/ssl/server.key
    max_connections: 100
    checkpoint_completion_target: 0.7
    default_statistics_target: 100
    random_page_cost: 1.1
    effective_io_concurrency: 200
    max_parallel_workers: 4
    max_worker_processes: 4
    min_wal_size: 1048576kB
    max_wal_size: 4194304kB
    max_parallel_workers_per_gather: 2
    shared_buffers: 4102144kB
    effective_cache_size: 12306432kB
    maintenance_work_mem: 1025536kB
    wal_buffers: 16384kB
    max_parallel_maintenance_workers: 2
    work_mem: 20510kB
    archive_mode: "on"
    archive_command: /bin/true
  authentication:
    replication:
      username: replicator
      password: replicator
    superuser:
      username: postgres
      password: postgres
log:
  dir: /var/log/patroni/
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: /bin/false
    log_temp_files: 0
  pg_hba:
  - local   all             all                                     trust
  - host    all             all             127.0.0.1/32            trust
  - host    all             all             ::1/128                 trust
  - 'host all all 1.2.16.100/32 md5 #pgbouncer all/all'
  - 'host all all 1.2.16.101/32 md5 #pgbouncer all/all'
  ssl: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
slots:
  barman:
    type: physical
ttl: 30
```

**Have you checked Patroni logs?**
If i change log_temp_files, it will do it:
`Changed log_temp_files from 7 to 0`
Changing archive_command only shows `Reloading PostgreSQL configuration.`

**Have you checked PostgreSQL logs?**
Same here: postgres logs
`received SIGHUP, reloading configuration files - parameter "log_temp_files" changed to "0"` for log_temp_files
or only `received SIGHUP, reloading configuration files` for archive_command

**Have you tried to use GitHub issue search?**
Yes. It seems that it should be working, but i can't make it work :)

**Additional context**
- I shortened pg_hba-section in the config-snippets above
- same outcome with patronictl edit-config or the REST-API
- Please be aware that /bin/false or /bin/true is only for testing. I know that they must not stay like this :)

Thanks for your help
