### ISSUE TITLE
Certificate authentication doesn't work with etcd v3

### ISSUE THREAD

**Issue by chobostar** [zalando/patroni#2036]
**Describe the bug**
Patroni 2.1.0 tries to work with etcd using http requests. So if one tries to use TLS with Common Name authentication it will not work.

https://etcd.io/docs/v3.4/dev-guide/api_grpc_gateway/#notes
```
gRPC-gateway does not support authentication using TLS Common Name.
```

Here is discussion: https://github.com/etcd-io/etcd/issues/11970#issuecomment-687875315

**To Reproduce**
1. have a cert with CN:
```
$ openssl x509 -in /etc/ssl/patroni.pem  -text | grep Subject:
        Subject: L = <redacted>, O = <redacted>, OU = <redacted>, CN = patroni-client
```
2. enable client-tls-auth in etcd
3. add user and role `patroni-client` in etcd server, then enable auth
4. try to run patroni with:
```
etcd3:
  protocol: https
  cert: "/etc/ssl/patroni.pem"
  key: "/etc/ssl/patroni.key"
  cacert: "/etc/ssl/ca.pem"  
```

**Expected behavior**
patroni agent authenticated using etcd v3 as `patroni-client` user

**Screenshots**
no screenshots

**Environment**
- Patroni version: 2.1.0
- PostgreSQL version: 12.3
- DCS (and its version): etcd 3.4.16

**Patroni configuration file**
```
---
name: test123-1
namespace: /patroni/
scope: test123
restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.11.12.3:8008
  authentication:
    username: patroni
    password: "123"
bootstrap:
  dcs:
    ttl: 60
    loop_wait: 10
    retry_timeout: 20
    maximum_lag_on_failover: 1048576
    master_start_timeout: 60
    postgresql:
      use_pg_rewind: True
      use_slots: True
      parameters:
        wal_level: logical
        hot_standby: 'on'
        wal_keep_segments: 100
        max_wal_senders: 12
        max_replication_slots: 12
        wal_log_hints: 'on'
        max_connections: '500'
  initdb: ['encoding=UTF8', 'data-checksums', 'auth-local=trust', 'locale=en_US.UTF-8', 'auth-host=md5', 'auth-local=trust']
  pg_hba: ['local all all trust', 'local replication all trust', 'host replication replication 127.0.0.1/32 trust', 'host replication replication 127.0.0.1/32 md5']
postgresql:
  listen: 0.0.0.0:5432
  connect_address: 10.11.12.3:5432
  data_dir: "/data/postgresql"
  config_dir: "/etc/postgresql/12/main"
  bin_dir: "/usr/lib/postgresql/12/bin"
  use_unix_socket: True
  parameters:
    unix_socket_directories: "/var/run/postgresql"
    hba_file: "/etc/postgresql/12/main/pg_hba.conf"
    ident_file: "/etc/postgresql/12/main/pg_ident.conf"
  authentication:
    replication:
      username: replication
      password: "123"
    superuser:
      username: postgres
      password: "123"
etcd3:
  protocol: https
  cert: "/etc/ssl/patroni.pem"
  key: "/etc/ssl/patroni.key"
  cacert: "/etc/ssl/ca.pem"  
  hosts: "etcd1:2379,etcd2:2379,etcd3:2379"
watchdog:
  mode: "off"
  device: "/dev/watchdog"
  safety_margin: 5
log:
  level: "INFO"
  dir: "/var/log/patroni"
  file_num: "2"
tags:
  nofailover: False
  noloadbalance: False
  clonefrom: False
  nosync: False
```

**patronictl show-config**
```
$ patronictl edit-config
2021-08-17 16:12:42,896 - ERROR - Failed to get list of machines from https://etcd1:2379/v3: <Unknown error: 'CommonName of client sending
```

**Have you checked Patroni logs?**
```
2021-08-17 16:12:42,896 - ERROR - Failed to get list of machines from https://etcd1:2379/v3: <Unknown error: 'CommonName of client sending
```
**Have you checked PostgreSQL logs?**
n/a

**Have you tried to use GitHub issue search?**
n/a

**Additional context**
n/a
