### ISSUE TITLE
Switchover is failing with patronictl command

### ISSUE THREAD

**Issue by AyushCloud** [zalando/patroni#2048]
**Describe the bug**
Unable to perform the switchover/failover with patronictl command

**To Reproduce**
 patronictl -c /etc/patroni/patroni.yml switchover 
Master [patroni01]: patroni01 
Candidate ['patroni02'] []: patroni02 
When should the switchover take place (e.g. 2021-09-02T11:48 ) [now]: now 
Current cluster topology 
+ Cluster: region_one (6972523391231779132) +----+-----------+-----------------+ 
| Member | Host | Role | State | TL | Lag in MB | Pending restart | 
+-----------+-----------+---------+---------+----+-----------+-----------------+ 
| patroni01 | patroni01 | Leader | running | 73 | | * | 
| patroni02 | patroni02 | Replica | running | 73 | 0 | * | 
+-----------+-----------+---------+---------+----+-----------+-----------------+ 
Are you sure you want to switchover cluster region_one, demoting current master patroni01? [y/N]: y 
Switchover failed, details: 412, switchover is not possible: no good candidates have been found 

**Expected behavior**

**Screenshots**

**Environment**
- Patroni version: 2.1.0
- PostgreSQL version: 9.6
- DCS (and its version): etcd 3.3

**Patroni configuration file**
```
scope: region_one 
 
namespace: /patroni_test/ 
 
name: patroni01 
restapi: 
  listen: privateIP:8008 
  connect_address: privateIP:8008 
etcd: 
  hosts: 1.2.3.4:2379,etcd-1:2379,etcd-2:2379
bootstrap:
  dcs:
    ttl: 10
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
  initdb:  
  - encoding: UTF8
  - data-checksums

  pg_hba:  
  - host replication replicator 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
  users:
postgresql:
  listen: "*:5432"
  connect_address: patroni01:5432
  data_dir: /var/lib/pgsql/data/postgresql0
  bin_dir: /usr/pgsql-9.6/bin/
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: replicator
    superuser:
      username: postgres
      password: postgres
    rewind:  
      username: rewind_user
      password: rewind
  parameters:

```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
patroni[4797]: 2021-09-02 10:48:40,258 WARNING: Watchdog not supported because leader TTL 10 is less than 2x loop_wait 10 
patroni[4797]: 2021-09-02 10:48:40,263 INFO: no action. I am (patroni01) the leader with the lock 
 patroni[4797]: 2021-09-02 10:48:50,254 INFO: Lock owner: patroni01; I am patroni01 
patroni[4797]: 2021-09-02 10:48:50,258 WARNING: Watchdog not supported because leader TTL 10 is less than 2x loop_wait 10 
patroni[4797]: 2021-09-02 10:48:50,261 INFO: no action. I am (patroni01) the leader with the lock 
patroni[4797]: 2021-09-02 10:49:00,255 INFO: Lock owner: patroni01; I am patroni01 
 patroni[4797]: 2021-09-02 10:49:00,261 WARNING: Watchdog not supported because leader TTL 10 is less than 2x loop_wait 10 
patroni[4797]: 2021-09-02 10:49:00,265 INFO: no action. I am (patroni01) the leader with the lock 
patroni[4797]: 2021-09-02 10:49:02,258 INFO: received switchover request with leader=patroni01 candidate=patroni02 scheduled_at=None 
patroni[4797]: 2021-09-02 10:49:02,262 WARNING: Request failed to patroni02: GET http://privateIP:8008/patroni (HTTPConnectionPool(host='privateIP', port=8008): Max retries exceeded with url: /patroni (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f18204e1208>: Failed to establish a new connection: [Errno 11
] No route to host',))) 

If i stop the master, then it is working fine but unable to perform the same operation with API call switchover/failover
