### ISSUE TITLE
Patroni on Kubernetes ignores pod readiness status

### ISSUE THREAD

**Issue by franck102** [zalando/patroni#2050]
**Describe the bug**
If a readiness probe fails on one of the PostgreSQL pod in a patroni managed cluster, patroni still exposes the pod behind the Kubernetes service endpoints

**To Reproduce**
Use a trivial readiness check that always fails on one or more of the nodes:
```
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - "exit 1"
```

The healthcheck we use actually combines pg_isready, and checks for disk space:
```
#!/bin/bash

    # Check PostgreSQL status
    PG_READY=$(pg_isready -h $PGHOST)
    if [ $? -ne 0 ]; then
      echo "$PG_READY" 2>&1
      exit 1;
    fi

    # Check disk space
    EXIT_STATUS=0
    SIZES=$(df -H | grep -vE '^Filesystem|tmpfs|cdrom' | awk '{ print $5 " " $1 }')
    while IFS= read -r output;
    do
      use_percent=$(echo $output | awk '{ print $1}' | cut -d'%' -f1  )
      partition=$(echo $output | awk '{ print $2 }' )
      if [ $use_percent -ge $DISK_SPACE_CONDITION ]; then
        echo "Running out of space \"$partition ($use_percent%)\" on $(hostname) as on $(date)" 2>&1
        EXIT_STATUS=1
      fi
    done <<< "$SIZES"
    exit $EXIT_STATUS
```
**Expected behavior**
When a node becomes unready (for any reason, e.g. disk space above) patroni should update the cluster so that the node is not exposed as an endpoint under K8s services; which if I am not mistaken means removing the "role" labels from the node's pod as far as patroni is concerned.
If there is a way to achieve this already I definitely cannot figure it out despite 1/2 day of googling and going through the documentation.

**Screenshots**
```
+ Cluster: dms-timescaledb (6997838974784888865) -------+----+-----------+
| Member            | Host          | Role    | State   | TL | Lag in MB |
+-------------------+---------------+---------+---------+----+-----------+
| dms-timescaledb-0 | 10.128.106.93 | Replica | running | 14 |         0 |
| dms-timescaledb-1 | 10.128.102.48 | Leader  | running | 14 |           |
| dms-timescaledb-2 | 10.128.98.157 | Replica | running | 14 |         0 |
+-------------------+---------------+---------+---------+----+-----------+
```
The master and one replica have failed readiness probes (2/3 -> postgres container is not ready):
```
dms-timescaledb-0                                       2/3     Running     0          132m
dms-timescaledb-1                                       2/3     Running     0          134m
dms-timescaledb-2                                       3/3     Running     0          135m
```

Yet both master and replica are picked up as valid service endpoints because of the "role" label:
```
dms-timescaledb-0   2/3     Running   0          135m   app=dms-timescaledb,cluster-name=dms-timescaledb,controller-revision-hash=dms-timescaledb-5b8cbcc5fb,release=dms-timescaledb,role=replica,statefulset.kubernetes.io/pod-name=dms-timescaledb-0
dms-timescaledb-1   2/3     Running   0          137m   app=dms-timescaledb,cluster-name=dms-timescaledb,controller-revision-hash=dms-timescaledb-5b8cbcc5fb,release=dms-timescaledb,role=master,statefulset.kubernetes.io/pod-name=dms-timescaledb-1
```

**Environment**
- Patroni version: patronictl version 2.0.1
- PostgreSQL version: (PostgreSQL) 12.6 (Debian 12.6-1.pgdg100+1)
- DCS (and its version): I can't say after reading the docs... we did *not* set PATRONI_KUBERNETES_USE_ENDPOINTS - so configmaps I assume: Kubernetes Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3"

**Patroni configuration file**
```
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_command: /etc/timescaledb/scripts/pgbackrest_archive.sh %p
        archive_mode: "on"
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 10
        autovacuum_naptime: 5s
        autovacuum_vacuum_cost_limit: 500
        autovacuum_vacuum_scale_factor: 0.05
        hot_standby: "on"
        log_autovacuum_min_duration: 1min
        log_checkpoints: "on"
        log_connections: "off"
        log_disconnections: "off"
        log_line_prefix: '%t [%p]: [%c-%l] %u@%d,app=%a [%e] '
        log_lock_waits: "on"
        log_min_duration_statement: 1s
        log_min_messages: notice
        log_statement: ddl
        max_connections: 100
        max_parallel_workers: 64
        max_prepared_transactions: 150
        max_worker_processes: 96
        shared_preload_libraries: timescaledb,pg_stat_statements
        ssl: "off"
        ssl_cert_file: /etc/certificate/tls.crt
        ssl_key_file: /etc/certificate/tls.key
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        temp_file_limit: 1GB
        timescaledb.max_background_workers: 64
        timescaledb.passfile: ../.pgpass
        timescaledb.telemetry_level: "off"
        unix_socket_directories: /var/run/postgresql
        unix_socket_permissions: "0750"
        wal_level: hot_standby
        wal_log_hints: "on"
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  method: restore_or_initdb
  post_init: /etc/timescaledb/scripts/post_init.sh
  restore_or_initdb:
    command: |
      /etc/timescaledb/scripts/restore_or_initdb.sh --encoding=UTF8 --locale=C.UTF-8
    keep_existing_recovery_conf: true
kubernetes:
  role_label: role
  scope_label: cluster-name
  use_endpoints: true
log:
  dir: /home/postgres
  level: WARNING
postgresql:
  authentication:
    replication:
      username: ***
    superuser:
      username: ***
  basebackup:
  - waldir: /var/lib/postgresql/wal/pg_wal
  create_replica_methods:
  - pgbackrest
  - basebackup
  listen: 0.0.0.0:5432
  pg_hba:
  - local     all             postgres                              peer
  -... and more sensitive info
  pgbackrest:
    command: /etc/timescaledb/scripts/pgbackrest_restore.sh
    keep_data: true
    no_master: 1
    no_params: true
  recovery_conf:
    restore_command: /etc/timescaledb/scripts/pgbackrest_archive_get.sh %f "%p"
  use_unix_socket: true
restapi:
  listen: 0.0.0.0:8008

```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 33554432
postgresql:
  parameters:
    archive_command: /etc/timescaledb/scripts/pgbackrest_archive.sh %p
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 10
    autovacuum_naptime: 5s
    autovacuum_vacuum_cost_limit: 500
    autovacuum_vacuum_scale_factor: 0.05
    hot_standby: 'on'
    log_autovacuum_min_duration: 1min
    log_checkpoints: 'on'
    log_connections: 'off'
    log_disconnections: 'off'
    log_line_prefix: '%t [%p]: [%c-%l] %u@%d,app=%a [%e] '
    log_lock_waits: 'on'
    log_min_duration_statement: 1s
    log_min_messages: notice
    log_statement: ddl
    max_connections: 100
    max_parallel_workers: 64
    max_prepared_transactions: 150
    max_worker_processes: 96
    shared_preload_libraries: timescaledb,pg_stat_statements
    ssl: 'off'
    ssl_cert_file: /etc/certificate/tls.crt
    ssl_key_file: /etc/certificate/tls.key
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    temp_file_limit: 1GB
    timescaledb.max_background_workers: 64
    timescaledb.passfile: ../.pgpass
    timescaledb.telemetry_level: 'off'
    unix_socket_directories: /var/run/postgresql
    unix_socket_permissions: '0750'
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
Nothing relevant there.

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
I did, and sent over the entire documentation 10 times :(

**Additional context**

**Comment by CyberDem0n** [comment]
Patroni neither knows nor cares about the infrastructure it is running on.

Specifically, liveness/readiness probes is something that is evaluated and used by K8s and Patroni doesn't aware that they exist, and should not even do that.

**Comment by CyberDem0n** [comment]
Yes, the leader endpoint subsets is managed by Patroni, and the leader service should not have a label selector in this case. The replica service at the same time will behave as expected.
I just don't understand what problem you want to solve by cutting connections to the primary if it is running out of disk space. The pod will continue to act as a leader, but from perspective of the application it will look like unavailability of Postgres.
Reaction on low disk space must be always external. Either volumes should be extended or disk space increased by other means. Cutting connections or doing a switchover in this case most likely will cause more problems in the nearest future.

In addition to that, your check with pg_isready is redundant. In case of replicas pods with postgres not accepting connections won't have the role label. And in case of primary we don't really care, whether the connection attempt is stopped on the service level, or reach postgres that does recovery and not yet accepting connections, in both cases it falls.

**Comment by franck102** [comment]
> Patroni neither knows nor cares about the infrastructure it is running on.
> 
> Specifically, liveness/readiness probes is something that is evaluated and used by K8s and Patroni doesn't aware that they exist, and should not even do that.

But in your next answer you are saying that “the leader endpoint subsets is managed by patroni”??
Who if not Patroni would be setting the role labels on the pods?.

**Comment by franck102** [comment]
> Yes, the leader endpoint subsets is managed by Patroni, and the leader service should not have a label selector in this case. The replica service at the same time will behave as expected.
> I just don't understand what problem you want to solve by cutting connections to the primary if it is running out of disk space. The pod will continue to act as a leader, but from perspective of the application it will look like unavailability of Postgres.

Which is precisely what I want to achieve. Only applications are generating new data and I want to disable them at 70%. At the same time I want to leave the Postgres instances running so that netops can come in and connect to SQL resolve issues.

> Reaction on low disk space must be always external.

That is most definitely not true. We have many scenarios in which a SQL retention policy job for example fails to run for some obvious reason. Being to connect to run it manually in that case is easy, it recovers the disk space, and it is much much less risky that going into shutdowns / FS expansion etc…

 > Either volumes should be extended or disk space increased by other means. Cutting connections or doing a switchover in this case most likely will cause more problems in the nearest future.

Blocking connections cannot cause more problems in Postgres. It will hurt the applications, which will be immediately noticed - before Postgres runs out of disk space and forces risky restore procedures.

> In addition to that, your check with pg_isready is redundant.
The timescaledb-single helm chart authors put that in.
But having a correct pod status of not-ready when PostgreSQL is not accepting connections seems to make a lot of sense - whether or not Patroni needs it for cluster management.

**Comment by CyberDem0n** [comment]
Patroni is a wrong tool for limiting the disk space usage. It's primary goal is high availability and automatic failover.

**Comment by franck102** [comment]
> Patroni is a wrong tool for limiting the disk space usage. It's primary goal is high availability and automatic failover.

We don’t need Patroni to monitor or limit disk usage.
The issue is that Patroni defines which node is ready to be part of the cluster without giving us any say in the decision: there are many reasons why someone may want a node to be neither a replica or a master even though Postgres is accepting connections (maintenance, SQL consistency checks, disk space).
The problem is that Patroni took over the endpoint management: if it were simply managing the pod labels we could use a regular K8s label selector to define the services, and not-ready pods would be taken out by K8s.

**Comment by CyberDem0n** [comment]
> there are many reasons why someone may want a node to be neither a replica or a master even though Postgres is accepting connections

Perfect, with [tags](https://patroni.readthedocs.io/en/latest/SETTINGS.html#tags) you can control that.

> Another issue is that Patroni took over the endpoint management

Nobody is forcing you to use endpoints for leader race, you can switch to config maps.

**Comment by franck102** [comment]
> > there are many reasons why someone may want a node to be neither a replica or a master even though Postgres is accepting connections
> 
> Perfect, with [tags](https://patroni.readthedocs.io/en/latest/SETTINGS.html#tags) you can control that.

I looked into that option, and ran into a couple issues:
- I see the nofailover tag, which would be acceptable, although a nomember tag is what we would really want
- changing tags at runtime is hard since it requires a yaml change and a reload. If I understand correctly we would need to modify a third-party helm chart (timescaledb-single) to use a config directory instead of a specific patroni.yml file; then create a z_disable.yaml file with the tag, and trigger a patroni config-reload

> > Another issue is that Patroni took over the endpoint management
> 
> Nobody is forcing you to use endpoints for leader race, you can switch to config maps.

Hmmm, will that actually work? From what I read in the docs, even when using a config map Patroni will still manage the endpoint addresses itself:
_"is safer than when using ConfigMaps, since both the annotations, containing the leader information, and the actual addresses pointing to the running leader pod are updated simultaneously"_
We are using ConfigMaps, and with the selectors below the not-ready pods are still listed as Endpoints behind the services, which makes my think that K8s has been short-circuited:

**Comment by franck102** [comment]
This is the fundamental K8s contract that the Patroni implementation seems to violate:

[https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/)

_"readinessProbe: Indicates whether the container is ready to respond to requests. If the readiness probe fails, the endpoints controller removes the Pod's IP address from the endpoints of all Services that match the Pod. "_

If Patroni want to override the endpoint controller then it needs to honor that contract IMHO.

**Comment by franck102** [comment]
What I don't understand is that Patroni already manages the "role" labels on the pods, why not let regular K8s service selectors manage the endpoints?

Is this to speed up or avoid race conditions during failovers?

**Comment by CyberDem0n** [comment]
> Hmmm, will that actually work? From what I read in the docs, even when using a config map Patroni will still manage the endpoint addresses itself:

Is it written in Patroni docs? I can tell for sure that it is not. And we can't be responsible for a 3rd party implementations.

> "is safer than when using ConfigMaps, since both the annotations, containing the leader information, and the actual addresses pointing to the running leader pod are updated simultaneously"

Yes, if the leader enforces only one IP in the endpoint subsets it is much safer than when you rely only on label selector. When a K8s node having problems all pods assigned to this node will remain in a "frozen" state for a while. Patroni will not be able to update roles on the pod, but at the same time the pod could be accessible from outside. Basically, you may end up that the leader endpoint will get more than one pod assigned.

> We are using ConfigMaps, and with the selectors below the not-ready pods are still listed as Endpoints behind the services, which makes my think that K8s has been short-circuited:

Once again, we are not responsible for a 3rd party implementations. If Patroni uses config maps it never touches endpoints on its own.

> This is the fundamental K8s contract that the Patroni implementation seems to violate:
If Patroni want to override the endpoint controller then it needs to honor that contract IMHO.

This is only your opinion. It is the application that defines rules and contracts, not K8s. The last one only provides only the platform. The primary goal of Patroni is implementing PostgreSQL HA, which means that there should be only one primary in the cluster and it must be accessible as much time as possible. Your wish to cut connections to the primary goes really against all the concepts of HA.

> What I don't understand is that Patroni already manages the "role" labels on the pods, why not let regular K8s service selectors manage the endpoints?
Is this to speed up or avoid race conditions during failover?

I already explained it above. The split-brain is the most dangerous situation that could happen with single-primary databases. By enforcing only one IP/Pod in the subsets we basically leave no chances for it to happen.

**Comment by franck102** [comment]
We will have to agree to disagree I guess.

Yes the quote I mentioned comes from the Patroni doc (https://patroni.readthedocs.io/en/latest/kubernetes.html). 

And yes despite setting PATRONI_KUBERNETES_USE_ENDPOINTS to false Patroni is directly managing at least the master service endpoints, as you confirmed above.

It is hard to imagine why you could not enforce at most one endpoint, but not enforce at most one pod with the role=master label.

And no, temporarily removing nodes from an HA cluster definitely does not go against the depths of HA, has already been requested in other issues, and is a basic featue of many HA frameworks.

**Comment by CyberDem0n** [comment]
> Yes the quote I mentioned comes from the Patroni doc (https://patroni.readthedocs.io/en/latest/kubernetes.html).

Please, quote the EXACT sentence. The doc is very explicit:

```
Use ConfigMaps
....

There are two ways to direct the traffic to the Postgres master:

  - use the callback script provided by Patroni
  - configure the Kubernetes Postgres service to use the label selector with the role_label (configured in patroni configuration).
```

The callback mechanism allows to have custom scripts that are executed on different events (start/stop/reload/role_change). Anyone can create a callback script. At one point there was one in Patroni repo, but it was never installed with Patroni.
Moreover, the second option explicitly mentions that K8s should be used with the label selector.

> And yes despite setting PATRONI_KUBERNETES_USE_ENDPOINTS to false Patroni is directly managing at least the master service endpoints, as you confirmed above.

Where did I confirm it? Please provide an explicit quote!
There are only two options:
- use_endpoints: false - Patroni works only with config maps and never touch endpoints
- use_endpoints: true - it works exclusively with endpoints and never touches config maps

> It is hard to imagine why you can enforce at most one mastendpoint, but could not enforce at most one pod with the role=master label.

Before making a point please invest a bit of time to learn how Patroni works. Every Patroni instance is responsible for itself. If Patroni running in one pod will start updating labels of other pods you will quickly get into trouble. Distributed systems are harder than you can imagine.

> And no, temporarily removing nodes from an HA cluster definitely does not go against the depths of HA, has already been requested in other issues, and is a basic featue of many HA frameworks.

Temporary removing nodes is fine. But cutting connections to the primary by the means of HA system is not fine.
If you want to cut connections there are many external mechanisms available, like firewall or pg_hba.conf, but you prefer instead to get the thing from Patroni that is never supposed to do.

As I already told you, you can achieve your goal by switching to config maps instead of endpoints. But, it will still not work exactly as you wish to, because after removing all pods from the endpoint existing connections are not affected and the application will continue to generate data.

**Comment by franck102** [comment]
> Where did I confirm it? Please provide an explicit quote! There are only two options:
> 
> * use_endpoints: false - Patroni works only with config maps and never touch endpoints
> * use_endpoints: true - it works exclusively with endpoints and never touches config maps

This is not what I am seeing. use_endpoints is false, I am using configmaps, my master service hos *no* selector, and yet it has an endpoint.
I don't want Patroni to "cut connections", I want it to not expose as an endpoint a pod that is not ready according to its probe.

```
apiVersion: v1
kind: Service
metadata:
  name: dms-timescaledb
  labels:
    app: dms-timescaledb
    chart: timescaledb-single-0.7.1
    release: dms-timescaledb
    heritage: Helm
    cluster-name: dms-timescaledb
    role: master
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
spec:
  type: LoadBalancer
  ports:
  - name: postgresql
    # This always defaults to 5432, even if `!loadBalancer.enabled`.
    port: 5432
    targetPort: postgresql
    protocol: TCP
```

```
km get endpoints dms-timescaledb
NAME              ENDPOINTS           AGE
dms-timescaledb   10.128.99.12:5432   4d17h
```
