### ISSUE TITLE
./patroni.py postgres0.yml excuted failed

### ISSUE THREAD

**Issue by Auggie321** [zalando/patroni#2053]
CentOS Linux release 7.9.2009 (Core)
Python 3.6.8                                                                        (yum -y install python36)
pip3:  21.2.4
Linux 5.4.138-1.el7.elrepo.x86_64
psycopg2 version: python-psycopg2-2.5.1-4.el7.x86_64   (yum -y install python-psycopg2)

root@ad1 ~/patroni (master) $ rpm -qa|grep postgresql
postgresql10-contrib-10.15-1PGDG.rhel7.x86_64
postgresql10-libs-10.15-1PGDG.rhel7.x86_64
postgresql10-10.15-1PGDG.rhel7.x86_64
postgresql10-server-10.15-1PGDG.rhel7.x86_64
postgresql10-devel-10.15-1PGDG.rhel7.x86_64

patroni     2.1.1
etcdctl version: 3.3.15, API version: 2

pip3 list:
```
root@ad1 ~/patroni (master) $ pip3 list
Package                           Version
--------------------------------- --------
backports.entry-points-selectable 1.1.0
click                             8.0.1
distlib                           0.3.2
filelock                          3.0.12
importlib-metadata                4.8.1
importlib-resources               5.2.2
patroni                           2.1.1
pip                               21.2.4
platformdirs                      2.3.0
prettytable                       2.2.0
psutil                            5.8.0
psycopg2                          2.7.7
psycopg2-binary                   2.9.1
python-dateutil                   2.8.2
PyYAML                            5.4.1
setuptools                        58.0.4
six                               1.16.0
typing-extensions                 3.10.0.2
urllib3                           1.26.6
virtualenv                        20.7.2
wcwidth                           0.2.5
ydiff                             1.2
zipp                              3.5.0
```
```
root@ad1 ~/patroni (master) $ ./patroni.py postgres0.yml 
/usr/local/lib64/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "./patroni.py", line 7, in <module>
    main()
  File "/root/patroni/patroni/__init__.py", line 171, in main
    return patroni_main()
  File "/root/patroni/patroni/__init__.py", line 139, in patroni_main
    abstract_main(Patroni, schema)
  File "/root/patroni/patroni/daemon.py", line 75, in abstract_main
    from .config import Config, ConfigParseError
  File "/root/patroni/patroni/config.py", line 13, in <module>
    from patroni.postgresql.config import CaseInsensitiveDict, ConfigHandler
  File "/root/patroni/patroni/postgresql/__init__.py", line 25, in <module>
    from .slots import SlotsHandler
  File "/root/patroni/patroni/postgresql/slots.py", line 8, in <module>
    from psycopg2.errors import UndefinedFile
ImportError: cannot import name 'UndefinedFile'
```

```
or python3 -p /usr/bin/python3 venv36
source venv36/bin/activate
(venv36) root@ad1 ~/patroni (master) $ pip --version
pip 21.2.3 from /root/patroni/venv36/lib/python3.6/site-packages/pip (python 3.6)
(venv36) root@ad1 ~/patroni (master) $ pip list
Package            Version
------------------ --------
click              8.0.1
importlib-metadata 4.8.1
patroni            2.1.1
pip                21.2.3
prettytable        2.2.0
psutil             5.8.0
python-dateutil    2.8.2
PyYAML             5.4.1
setuptools         57.4.0
six                1.16.0
typing-extensions  3.10.0.2
urllib3            1.26.6
wcwidth            0.2.5
wheel              0.37.0
ydiff              1.2
zipp               3.5.0

(venv36) root@ad1 ~/patroni (master) $ ./patroni.py postgres0.yml 
/usr/local/lib64/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "./patroni.py", line 7, in <module>
    main()
  File "/root/patroni/patroni/__init__.py", line 171, in main
    return patroni_main()
  File "/root/patroni/patroni/__init__.py", line 139, in patroni_main
    abstract_main(Patroni, schema)
  File "/root/patroni/patroni/daemon.py", line 75, in abstract_main
    from .config import Config, ConfigParseError
  File "/root/patroni/patroni/config.py", line 13, in <module>
    from patroni.postgresql.config import CaseInsensitiveDict, ConfigHandler
  File "/root/patroni/patroni/postgresql/__init__.py", line 25, in <module>
    from .slots import SlotsHandler
  File "/root/patroni/patroni/postgresql/slots.py", line 8, in <module>
    from psycopg2.errors import UndefinedFile
ImportError: cannot import name 'UndefinedFile'
```

postgres0.yaml
```
scope: batman
#namespace: /service/
name: postgresql0

restapi:
  listen: 192.168.1.138:8008
  connect_address: 192.168.1.138:8008
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password


etcd:
  hosts: 192.168.1.138:2379,192.168.1.139:2379,192.168.1.140:2379
  protocol: https
  cacert: /etc/kubernetes/ssl/ca.pem
  cert: /etc/kubernetes/ssl/etcd.pem
  key: /etc/kubernetes/ssl/etcd-key.pem

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    synchronous_mode: false
    #standby_cluster:
      #host: 127.0.0.1
      #port: 1111
      #primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
      #use_slots: true
      parameters:
        wal_level: hot_standby
        hot_standby: "on"
        max_connections: 100
        max_worker_processes: 8
        wal_keep_segments: 8
        max_wal_senders: 10
        max_replication_slots: 10
        max_prepared_transactions: 0
        max_locks_per_transaction: 64
        wal_log_hints: "on"
        track_commit_timestamp: "off"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: mkdir -p /data/wal_archive && test ! -f /data/wal_archive/%f && cp %p /data/wal_archive/%f
    recovery_conf:
        restore_command: cp /data/wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  # For kerberos gss based connectivity (discard @.*$)
  #- host replication replicator 127.0.0.1/32 gss include_realm=0
  #- host all all 0.0.0.0/0 gss include_realm=0
  - host replication all 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
#  - hostssl all all 0.0.0.0/0 md5

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 192.168.1.138:5432
  connect_address: 192.168.1.138:5432
  # data_dir: data/postgresql0
  data_dir: /data/
  bin_dir: /usr/pgsql-10/bin/
  pgpass: /var/lib/pgsql/10/.pgpass
  authentication:
    replication:
      username: rep
      password: 23$f!f6Xcd
    superuser:
      username: postgres
      password: 
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind
      password: Gbj%63!xFc
  # Server side kerberos spn
#  krbsrvname: postgres
  parameters:
    # Fully qualified kerberos ticket file for the running user
    # same as KRB5CCNAME used by the GSS
#   krb_server_keyfile: /var/spool/keytabs/postgres
    unix_socket_directories: '.'
  # Additional fencing script executed after acquiring the leader lock but before promoting the replica
  #pre_promote: /path/to/pre_promote.sh

watchdog:
  mode: automatic # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

```
