### ISSUE TITLE
[FEATURE] Add configuration option for pgpass file to provide passwords

### ISSUE THREAD

**Issue by mjf** [zalando/patroni#2061]
Hello,

I would like to suggest adding new option providing path to extra *pgpass* file to read passwords from to authenticate the superuser and the users for replication, rewind etc., for example:

```yaml
postgresql:
    # the file generated on runtime by Patroni
    pgpass: /var/lib/pgsql/<postgres-version>/data/.pgpass_patroni

    # a file containing passwords that now come from the authentication configuration branch
    pgpass_start: /var/lib/pgsql/.pgpass_patroni

    authentication:
        replication:
            username: replicator
            # password: 'no_more_needed'
        superuser:
            username: postgres
            # password: 'no_more_needed'
```

In many setups *Patroni* runs under the same user as *Postgres*. In many setups the ownership and the permissions **aren't set correctly** (aren't "tightened" enough) for `/etc/patroni*` (and operators can easily miss this fact). This option would at least remind of the fact (as well as extends overall configurability by allowing for separating credentials from configuration strictly).

There is already support for reading *pgpass* files in *Patroni* that can be used for it, I guess.

The only question is what would take precedence (the start *pgpass* file over authentication configuration branch or *vice versa*) if both of them is configured.
