### ISSUE TITLE
switchover on async replica

### ISSUE THREAD

**Issue by glushakov** [zalando/patroni#2074]
**Describe the bug**
when doing manual switchover , i did not specify target node (just pressed enter) and patroni sometimes switchs on async replica

**To Reproduce**
make 3 nodes (1 leader, 1 sync, 1 async), and try to switch without specify target node

**Expected behavior**
patroni should not accept empty value OR should switchover only on sync standby (if available)

**Screenshots**
patronictl -c /etc/patroni/postgres1.yml switchover
Master [postgres3]:
Candidate ['postgres1', 'postgres2'] []:
When should the switchover take place (e.g. 2021-09-30T22:48 )  [now]:
Current cluster topology
+---------------------+---------------------+--------------+---------+----+-----------+
| Member              | Host                | Role         | State   | TL | Lag in MB |
+ Cluster: main (7013793607822447442) ------+--------------+---------+----+-----------+
| postgres1 | postgres1 | Sync Standby | running |  2 |         0 |
| postgres2 | postgres2 | Replica      | running |  2 |         0 |
| postgres3 | postgres3 | Leader       | running |  2 |           |
+---------------------+---------------------+--------------+---------+----+-----------+
Are you sure you want to switchover cluster main, demoting current master postgres3? [y/N]: y
2021-09-30 21:48:38.96713 Successfully switched over to "postgres2"
+---------------------+---------------------+---------+---------+----+-----------+
| Member              | Host                | Role    | State   | TL | Lag in MB |
+ Cluster: main (7013793607822447442) ------+---------+---------+----+-----------+
| postgres1 | postgres1 | Replica | running |  2 |         0 |
| postgres2 | postgres2 | Leader  | running |  2 |           |
| postgres3 | postgres3 | Replica | stopped |    |   unknown |
+---------------------+---------------------+---------+---------+----+-----------+
(patroni_venv) [09:48:39 postgres@postgres1:]:~$ patronictl -c /etc/patroni/postgres1.yml  list
+---------------------+---------------------+--------------+---------+----+-----------+
| Member              | Host                | Role         | State   | TL | Lag in MB |
+ Cluster: main (7013793607822447442) ------+--------------+---------+----+-----------+
| postgres1 | postgres1 | Replica      | running |  3 |         0 |
| postgres2 | postgres2 | Leader       | running |  3 |           |
| postgres3 | postgres3 | Sync Standby | running |  3 |         0 |
+---------------------+---------------------+--------------+---------+----+-----------+

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 13.3
- DCS (and its version): etcd 3.2.32

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
scope: main
namespace: /service/
name: postgres1
log:
  level: INFO
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000
  dir: /var/log/patroni
  file_num: 4
  file_size: 25000000
restapi:
  listen: 0.0.0.0:8008
  connect_address: postgres1:8008
  authentication:
    username: patroni_rest
    password: Pa$$word
etcd:
  hosts: postgres1:2379,postgres2:2379,postgres3:2379
  protocol: http
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: false
    check_timeline: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 300
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: replica
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_segments: 256
      pg_hba:
        - local all all  trust
        - host all all 0.0.0.0/0 md5
        - host replication replicator 0.0.0.0/0 md5
  initdb:
    - encoding: UTF8
    - data-checksums
  users:
    postgres:
      password: superpassword
    replicator:
      password: superpassword
      options:
        - replication
postgresql:
  use_unix_socket: true
  listen: 0.0.0.0:5432
  connect_address: postgres1:5432
  data_dir: /var/lib/pgsql/data
  bin_dir: /usr/bin
  config_dir: /var/lib/pgsql/data
  pgpass: /var/lib/pgsql/.pgpass
  authentication:
    superuser:
      username: postgres
      password: superpassword
    replication:
      username: replicator
      password: superpassword
  create_replica_methods:
    - basebackup
  basebackup:
    checkpoint: fast
  parameters:
    unix_socket_directories: /var/run/postgresql
  pg_hba:
    - local all all  trust
    - host all all 0.0.0.0/0 md5
    - host replication replicator 0.0.0.0/0 md5
  pg_ctl_timeout: 60
  pg_rewind:
    username: postgres
    password: superpassword
  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false
watchdog:
  mode: off
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
check_timeline: false
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 300
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    track_commit_timestamp: false
    wal_keep_segments: 256
    wal_level: replica
    wal_log_hints: true
  pg_hba:
  - local all all  trust
  - host all all 0.0.0.0/0 md5
  - host replication replicator 0.0.0.0/0 md5
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
ttl: 30

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
