### ISSUE TITLE
database password not initialised when using SCRAM-SHA-256 (FATAL:  password authentication failed for user "postgres")

### ISSUE THREAD

**Issue by nbari** [zalando/patroni#2095]
**Describe the bug**
if creating a new server (no data) and using auth `scram-sha-256` user `postgres` can't log in:

```
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 86: "host    all             all             127.0.0.1/32            scram-sha-256"
```

**To Reproduce**

Use:

```yaml
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
        password_encryption: scram-sha-256

  initdb:
    - auth-host: scram-sha-256
    - auth-local: scram-sha-256
    - data-checksums
    - encoding: UTF8

```

**Expected behavior**

Login successfully after creating the database without need to modify pg_hba.conf, for example this works for initializing the db:

```
/usr/lib/postgresql/13/bin/pg_ctl initdb -D /db/data13 -o '--auth-local=scram-sha-256' -o '--auth-host=scram-sha-256' -o '-    -pwfile /db/tmp-pass'
```

**Screenshots**

**Environment**
- Patroni version: patroni 2.1.1
- PostgreSQL version:  13
- DCS (and its version): consul

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
