### ISSUE TITLE
 how to reload config.yml instead of using  patronictl  edit-config 

### ISSUE THREAD

**Issue by nbari** [zalando/patroni#2099]
Hi, sorry if an issue is not the proper way of asking this but I am unsure if this may be a bug or probably something not implemented.

I am installing `patroni+consul` via ansible, so far all good, but I haven't found a way to reload the config.yml and apply changes, for example, if I would like to change the  `max_connections` the only way I have found that works for my setup,  is to use the API or `patronictl edit-config`, for example, using:

     patronictl -c /etc/patroni/config.yml edit-config
     patronictl -c /etc/patroni/config.yml list
     patronictl -c /etc/patroni/config.yml restart patroni

Via ansible after modifying the config.yml I am trying without luck:

```
---
- name: restart patroni
  shell: patronictl --config-file /etc/patroni/config.yml reload patroni --force && patronictl --config-file /etc/patroni/config.yml restart patroni --force
  become_user: postgres
```

I am adding this in the `postgresql/parameters` section, not in `bootstrap/dcs` since from my understanding those options are only used once and when initializing the database

**To Reproduce**
modify `config.yml`, send SIGHUP,  or `-xPOST /reload` 

**Expected behavior**
changes applied in `postgresql.conf`

**Screenshots**

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 13.4
- DCS (and its version): Consul

**Patroni configuration file**
```
postgresql:
  bin_dir: /usr/lib/postgresql/13/bin
  listen: "*:5432"
  parameters:
    unix_socket_directories: '/tmp/, /var/run/postgresql/'
    max_connections: 100

```

**patronictl show-config**
```

loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    autovacuum_max_workers: 10
    autovacuum_naptime: 10
    checkpoint_completion_target: 0.9
    default_statistics_target: 500
    effective_cache_size: 3GB
    effective_io_concurrency: 256
    maintenance_work_mem: 491529kB
    max_connections: 50
    max_locks_per_transaction: 64
    max_parallel_maintenance_workers: 1
    max_parallel_workers: 2
    max_parallel_workers_per_gather: 1
    max_wal_size: 1GB
    max_worker_processes: 13
    min_wal_size: 512MB
    password_encryption: scram-sha-256
    random_page_cost: 1.1
    shared_buffers: 1GB
    shared_preload_libraries: timescaledb
    timescaledb.last_tuned: '2021-10-21T01:22:50Z'
    timescaledb.last_tuned_version: 0.12.0
    timescaledb.max_background_workers: 8
    wal_buffers: 16MB
    work_mem: 9830kB
  use_pg_rewind: true
retry_timeout: 10
ttl: 30

```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
