### ISSUE TITLE
[FEATURE] Allow environment variables for parameters in yaml config

### ISSUE THREAD

**Issue by bleleve** [zalando/patroni#2100]
Hi,

For the deployment of our infrastructure (k8s and postgres-operator/spilo/patroni), we need to pass custom variables to the PostgreSQL conf file (a global encryption key and the name of the POD on which the instance is executed).

It would be interesting to be able to indicate in the Patroni conf yaml file that a parameter depends on an environment variable:
```yaml
bootstrap:
  dcs:
    postgresql:
      parameters:
        custom.my_var_1: ${ENV_VAR_1}
postgresql:
  parameters:
    custom.my_var_2: ${ENV_VAR_2}
```

Unfortunately python is not a language that I use every day, I won't be able to control the side effects if I try to do a PR.

Thanks !
