### ISSUE TITLE
get_postgresql_status error in PK identity

### ISSUE THREAD

**Issue by SamuelMolling** [zalando/patroni#2101]
**Describe the bug**

Scenario where it runs: We run an application routine that does 700 TPS, the CPU is at ~30% and the memory used at 4GB (it doesn't seem to be using memory), the flow runs smoothly without problems.
Scenario where it doesn't run: We run the same stream, but at the end of the stream the bank drops out of the cluster, errors reported below, but the bank is still in the air processing some stuck queries, possible to connect, but very slow and because the application is connected to a load balancer (Haproxy) the bank is unavailable, as we have validation rules to balance transactions (health check of a patroni api, according to the architecture above)
What is the difference between the flows?
The only difference between one stream and another is the table PK, the stream that runs smoothly uses TEXT as a PK and the stream that does not run uses IDENTITY (message_id BIGINT CONSTRAINT clearing_message__message_id__pk PRIMARY KEY GENERATED ALWAYS AS IDENTITY), we saw considerable CPU increase , reaching almost 100%, the increase was made to 16 CPUs, during the flow the cpu remained at 40%, but even so the bank fell from the cluster

**To Reproduce**
The difference between the problem and not the table is found in the sqls below

**Expected behavior**

The database starts processing and the patroni makes errors, as shown in the log below

Oct 27 18:35:43 clr-v-psql-2p03 patroni[2639]: 2021-10-27 18:35:43,539 ERROR: get_postgresql_status
Oct 27 18:35:43 clr-v-psql-2p03 patroni[2639]: Traceback (most recent call last):
Oct 27 18:35:43 clr-v-psql-2p03 patroni: 2021-10-27 18:35:43,539 ERROR: get_postgresql_status
Oct 27 18:35:43 clr-v-psql-2p03 patroni[2639]: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 595, in get_postgresql_status
Oct 27 18:35:43 clr-v-psql-2p03 patroni: Traceback (most recent call last):
Oct 27 18:35:43 clr-v-psql-2p03 patroni[2639]: row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
Oct 27 18:35:43 clr-v-psql-2p03 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 595, in get_postgresql_status
Oct 27 18:35:43 clr-v-psql-2p03 patroni[2639]: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 577, in query
Oct 27 18:35:43 clr-v-psql-2p03 patroni: row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
Oct 27 18:35:43 clr-v-psql-2p03 patroni[2639]: return self.server.query(sql, *params)
Oct 27 18:35:43 clr-v-psql-2p03 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 577, in query
Oct 27 18:35:43 clr-v-psql-2p03 patroni[2639]: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 662, in query
Oct 27 18:35:43 clr-v-psql-2p03 patroni: return self.server.query(sql, *params)
Oct 27 18:35:43 clr-v-psql-2p03 patroni[2639]: raise e
Oct 27 18:35:43 clr-v-psql-2p03 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 662, in query
Oct 27 18:35:43 clr-v-psql-2p03 patroni[2639]: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 658, in query
Oct 27 18:35:43 clr-v-psql-2p03 patroni: raise e
Oct 27 18:35:43 clr-v-psql-2p03 patroni[2639]: cursor.execute(sql, params)
Oct 27 18:35:43 clr-v-psql-2p03 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 658, in query
Oct 27 18:35:43 clr-v-psql-2p03 patroni[2639]: psycopg2.errors.QueryCanceled: canceling statement due to statement timeout
Oct 27 18:35:43 clr-v-psql-2p03 patroni: cursor.execute(sql, params)
Oct 27 18:35:43 clr-v-psql-2p03 patroni: psycopg2.errors.QueryCanceled: canceling statement due to statement timeout

**Screenshots**

Logs bellow

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 13.4
- DCS (and its version): etcdctl version: 3.3.22, API version: 2

**Patroni configuration file**
```
---

scope: clearing-cluster
name: clr-v-psql-2p03
namespace: /service/

restapi:
  listen: IP:8008
  connect_address: IP:8008
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

etcd:
  hosts: IPS:2379

bootstrap:
  method: initdb
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: false
    synchronous_node_count: 1
    # standby_cluster:
      # host: 127.0.0.1
      # port: 1111
      # primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 100
        superuser_reserved_connections: 5
        max_locks_per_transaction: 64
        max_prepared_transactions: 0
        huge_pages: try
        shared_buffers: 512MB
        work_mem: 128MB
        maintenance_work_mem: 256MB
        effective_cache_size: 4GB
        checkpoint_timeout: 15min
        checkpoint_completion_target: 0.9
        min_wal_size: 4GB
        max_wal_size: 8GB
        wal_buffers: 32MB
        default_statistics_target: 1000
        seq_page_cost: 1
        random_page_cost: 4
        effective_io_concurrency: 2
        synchronous_commit: on
        autovacuum: on
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_vacuum_cost_limit: 200
        autovacuum_vacuum_cost_delay: 20
        autovacuum_naptime: 1s
        max_files_per_process: 4096
        archive_mode: on
        archive_timeout: 1800s
        archive_command: cd .
        wal_level: replica
        wal_keep_segments: 130
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: on
        wal_log_hints: on
        shared_preload_libraries: pg_stat_statements,auto_explain
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        pg_stat_statements.save: off
        auto_explain.log_min_duration: 10s
        auto_explain.log_analyze: true
        auto_explain.log_buffers: true
        auto_explain.log_timing: false
        auto_explain.log_triggers: true
        auto_explain.log_verbose: true
        auto_explain.log_nested_statements: true
        track_io_timing: on
        log_lock_waits: on
        log_temp_files: 0
        track_activities: on
        track_counts: on
        track_functions: all
        log_statement: all
        log_line_prefix: '[%m] %u,%d,%c,||| '
        log_disconnections: on
        log_connections: on
        log_destination: csvlog
        log_checkpoints: on
        logging_collector: on
        log_truncate_on_rotation: on
        log_rotation_age: 1d
        log_rotation_size: 0
        log_filename: 'postgresql-%a.log'
        log_directory: /postgres/logs

#  initdb:  # List options to be passed on to initdb
#    - encoding: UTF8
#    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5


postgresql:
  listen: IP:5432
  connect_address: IP:5432
  use_unix_socket: true
  data_dir: /postgres/data
  bin_dir: /usr/pgsql-13/bin
  config_dir: /postgres/data
  pgpass: /postgres/.pgpass_patroni
  authentication:
    replication:
      username: replicator
      password: ""
    superuser:
      username: postgres
      password: ""
#    rewind:  # Has no effect on postgres 10 and lower
#      username: rewind_user
#      password: rewind_password
  parameters:
    unix_socket_directories: /var/run/postgresql
    stats_temp_directory: /var/lib/pgsql_stats_tmp


  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false

#  callbacks:
#    on_start:
#    on_stop:
#    on_restart:
#    on_reload:
#    on_role_change:

  create_replica_methods:
    - basebackup
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'


watchdog:
  mode: off  # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

  # specify a node to replicate from (cascading replication)
#  replicatefrom: (node name)


```

**patronictl show-config**
```
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=clearing-cluster archive-push %p
    archive_mode: true
    archive_timeout: 1800s
    auto_explain.log_analyze: true
    auto_explain.log_buffers: true
    auto_explain.log_min_duration: 10s
    auto_explain.log_nested_statements: true
    auto_explain.log_timing: false
    auto_explain.log_triggers: true
    auto_explain.log_verbose: true
    autovacuum: true
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_naptime: 1s
    autovacuum_vacuum_cost_delay: 20
    autovacuum_vacuum_cost_limit: 200
    autovacuum_vacuum_scale_factor: 0.01
    checkpoint_completion_target: 0.7
    checkpoint_timeout: 15min
    default_statistics_target: 100
    effective_cache_size: 32GB
    effective_io_concurrency: 200
    enable_seqscan: false
    enable_sort: false
    hot_standby: true
    huge_pages: try
    log_checkpoints: true
    log_connections: true
    log_destination: csvlog
    log_directory: /postgres/logs
    log_disconnections: true
    log_filename: postgresql-%Y%m%d
    log_line_prefix: '[%m] %u,%d,%c,||| '
    log_lock_waits: true
    log_min_error_statement: INFO
    log_min_messages: INFO
    log_rotation_age: 1d
    log_rotation_size: 0
    log_statement: all
    log_temp_files: 0
    log_truncate_on_rotation: true
    logging_collector: true
    maintenance_work_mem: 2048MB
    max_connections: 4000
    max_files_per_process: 4096
    max_locks_per_transaction: 64
    max_parallel_maintenance_workers: 4
    max_parallel_workers: 8
    max_parallel_workers_per_gather: 4
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: 8GB
    max_worker_process: 8
    min_wal_size: 512MB
    pg_stat_statements.max: 10000
    pg_stat_statements.save: false
    pg_stat_statements.track: all
    random_page_cost: 1.1
    seq_page_cost: 1
    shared_buffers: 16GB
    shared_preload_libraries: pg_stat_statements,auto_explain,pg_hint_plan,pg_stat_monitor
    superuser_reserved_connections: 5
    synchronous_commit: true
    track_activities: true
    track_counts: true
    track_functions: all
    track_io_timing: true
    wal_buffers: 16MB
    wal_keep_segments: 130
    wal_level: replica
    wal_log_hints: true
    work_mem: 18MB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
synchronous_node_count: 1
ttl: 30

```

**Have you checked Patroni logs?**
Yes
[message_teste1.log](https://github.com/zalando/patroni/files/7429189/message_teste1.log)

**Have you checked PostgreSQL logs?**
ERROR:  canceling statement due to user request

**Have you tried to use GitHub issue search?**
Yes

**Additional context**
When we run with PK in text, the flow is smooth and does not reach 30% of CPU usage, but when using identity, the CPU starts to grow and the database falls outside the patroni cluster, even doubling the cpu, where it remains constant at 30%, the database falls out of the cluster
