### ISSUE TITLE
[Feature] Suggestion for callback hook on loss of replica node

### ISSUE THREAD

**Issue by Faxter** [zalando/patroni#2106]
Hi,
I'd like to suggest a new callback hook akin to on_role_change for the event that a node is lost.

If the lost node is leader, there will be a role change promoting some node to the new leader - so it would trigger on_role_change.
But if the lost node is replica, there is no way to automatically have a user-script run.

```yaml
[...]
postgresql:
  [...]
  callbacks:
    on_role_change: /opt/patroni/alert/some-script.sh
    on_node_lost: /opt/patroni/alert/some-other-script.sh
[...]
```

In certain setups we may expect a constant number of nodes in the cluster and may want to react to any of them getting lost.
Note that this would not necessarily be covered by on_stop, e.g. on hardware or network failure.
