### ISSUE TITLE
patroni 2.x start with errors for PostgreSQL 13 | INFO: Unexpected exception raised

### ISSUE THREAD

**Issue by naresh5310** [zalando/patroni#2111]
**Describe the bug**

The following is the message I am getting when I start the patroni 2.x on CentOS 7/8
 2021-11-07 06:59:45,941 ERROR: Unexpected exception
 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/patroni/ha.py", line 1471, in run_cycle
    info = self._run_cycle()
  File "/usr/lib/python3.6/site-packages/patroni/ha.py", line 1312, in _run_cycle
    self.state_handler.reset_cluster_info_state(self.cluster, self.patroni.nofailover)
  File "/usr/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 329, in reset_cluster_info_state
    cluster.has_permanent_logical_slots(self.name, nofailover, self.major_version)
  File "/usr/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 572, in has_permanent_logical_slots
    slots = self.get_replication_slots(my_name, 'replica', nofailover, major_version).values()
  File "/usr/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 509, in get_replication_slots
    use_slots = self.use_slots
  File "/usr/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 502, in use_slots
    return self.config and self.config.data.get('postgresql', {}).get('use_slots', True)
 AttributeError: 'NoneType' object has no attribute 'get'
 2021-11-07 06:59:45,941 INFO: Unexpected exception raised, please report it as a BUG
![bug](https://user-images.githubusercontent.com/45495252/140635812-39aa499e-e7ae-47bf-bc5e-0f4396c1f8e5.JPG)

**Screenshots**

**Environment**
- Patroni version:

[root@mx dbapath]# patroni --version
patroni 2.1.1
[root@mx dbapath]#

- PostgreSQL version:
13

- DCS (and its version):
[root@ ~]# etcd --version
etcd Version: 3.5.0

**Patroni configuration file**
```
scope: postgres
namespace: /db/
name: postgresql1

restapi:
    listen: 10.182.0.59:8008
    connect_address: 10.182.0.59:8008

etcd:
    host: 10.182.0.60:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
        use_pg_rewind: true
    initdb:
    - encoding: UTF8
    - data-checksums
    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.182.0.59/0 md5
    - host replication replicator 10.182.0.49/0 md5
    - host all all 0.0.0.0/0 md5
    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 10.182.0.59:5432
    wal_keep_segments: 8
    connect_address: 10.182.0.59:5432
    data_dir: /var/lib/pgsql/13/data
    bin_dir: /usr/pgsql-13/bin
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: replicator
        superuser:
            username: postgres
            password: postgres
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

```

**patronictl show-config**
```
[root@mx dbapath]# patronictl -c /etc/patroni/patroni.yml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql: null
retry_timeout: 10
ttl: 30
use_pg_rewind: true

[root@mx dbapath]#

```

**Have you tried to use GitHub issue search?**
No

**Additional context**
[root@mx dbapath]# systemctl status patroni.service
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/etc/systemd/system/patroni.service; disabled; vendor preset: disabled)
   Active: active (running) since Sun 2021-11-07 06:57:55 UTC; 44s ago
 Main PID: 1715 (patroni)
    Tasks: 5 (limit: 23651)
   Memory: 22.8M
   CGroup: /system.slice/patroni.service
           └─1715 /usr/bin/python3 /usr/bin/patroni /etc/patroni/patroni.yml

Nov 07 06:58:35 mx patroni[1715]:   File "/usr/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 329, in reset_cluster_info_state
Nov 07 06:58:35 mx patroni[1715]:     cluster.has_permanent_logical_slots(self.name, nofailover, self.major_version)
Nov 07 06:58:35 mx patroni[1715]:   File "/usr/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 572, in has_permanent_logical_slots
Nov 07 06:58:35 mx patroni[1715]:     slots = self.get_replication_slots(my_name, 'replica', nofailover, major_version).values()
Nov 07 06:58:35 mx patroni[1715]:   File "/usr/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 509, in get_replication_slots
Nov 07 06:58:35 mx patroni[1715]:     use_slots = self.use_slots
Nov 07 06:58:35 mx patroni[1715]:   File "/usr/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 502, in use_slots
Nov 07 06:58:35 mx patroni[1715]:     return self.config and self.config.data.get('postgresql', {}).get('use_slots', True)
Nov 07 06:58:35 mx patroni[1715]: AttributeError: 'NoneType' object has no attribute 'get'
Nov 07 06:58:35 mx patroni[1715]: 2021-11-07 06:58:35,917 INFO: Unexpected exception raised, please report it as a BUG
