### ISSUE TITLE
Patroni doesn't rewind standby if timeline is missing on master

### ISSUE THREAD

**Issue by fischerman** [zalando/patroni#2118]
**Describe the bug**
Given is a 2 node cluster with member A and B. A is master at TLI 132. Network problems cause A to demote. B is promoted and picks TLI 133. Some time later, B is demoted (apparently without replicating TLI 133 to A). Member A is promoted a switches to TLI 134, branching from TLI 132 (i.e. itself) at a point later than the branch point of TLI 133. Member B now has a diverging (old) timeline and must be rewound. However, Patroni doesn't attempt to rewind and instead starts the node. WAL replications fails because the timelines diverged.

**To Reproduce**

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 12
- DCS (and its version): Kubernetes

**Patroni configuration file**: generated by Spilo
```
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_mode: 'on'
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.05
        checkpoint_completion_target: 0.9
        hot_standby: 'on'
        log_autovacuum_min_duration: 0
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_lock_waits: 'on'
        log_min_duration_statement: 500
        log_statement: ddl
        log_temp_files: 0
        max_connections: 260
        max_replication_slots: 10
        max_wal_senders: 10
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        track_functions: all
        wal_compression: 'on'
        wal_level: hot_standby
        wal_log_hints: 'on'
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - auth-host: md5
  - auth-local: trust
  post_init: /scripts/post_init.sh "zalandos"
  users:
    zalandos:
      options:
      - CREATEDB
      - NOLOGIN
      password: ''
kubernetes:
  bypass_api_service: true
  labels:
    application: spilo
  pod_ip: 10.233.117.147
  ports:
  - name: postgresql
    port: 5432
  role_label: spilo-role
  scope_label: cluster-name
  use_endpoints: true
namespace: my-namespace
postgresql:
  authentication:
    replication:
      password: ...
      username: standby
    superuser:
      password: ...
      username: postgres
  basebackup_fast_xlog:
    command: /scripts/basebackup.sh
    retries: 2
  bin_dir: /usr/lib/postgresql/12/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos true
  connect_address: 10.233.117.147:5432
  create_replica_method:
  - wal_e
  - basebackup_fast_xlog
  data_dir: /home/postgres/pgdata/pgroot/data
  listen: '*:5432'
  name: ...
  parameters:
    archive_command: envdir "/run/etc/wal-e.d/env" wal-g wal-push "%p"
    bg_mon.history_buckets: 120
    bg_mon.listen_address: '::'
    extwlist.custom_path: /scripts
    extwlist.extensions: btree_gin,btree_gist,citext,hstore,intarray,ltree,pgcrypto,pgq,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,hypopg,timescaledb,pg_partman
    log_destination: csvlog
    log_directory: ../pg_log
    log_file_mode: '0644'
    log_filename: postgresql-%u.log
    log_rotation_age: 1d
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    pg_stat_statements.track_utility: 'off'
    shared_buffers: 1560MB
    shared_preload_libraries: bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,timescaledb,pg_cron,pg_stat_kcache
    ssl: 'on'
    ssl_cert_file: /run/certs/server.crt
    ssl_key_file: /run/certs/server.key
  pg_hba:
  - local   all             all                                   trust
  - hostssl all             +zalandos    127.0.0.1/32       pam
  - host    all             all                127.0.0.1/32       md5
  - hostssl all             +zalandos    ::1/128            pam
  - host    all             all                ::1/128            md5
  - local   replication     standby                    trust
  - hostssl replication     standby all                md5
  - hostnossl all           all                all                reject
  - hostssl all             +zalandos    all                pam
  - hostssl all             all                all                md5
  pgpass: /run/postgresql/pgpass
  recovery_conf:
    restore_command: envdir "/run/etc/wal-e.d/env" /scripts/restore_command.sh "%f" "%p"
  use_unix_socket: true
  use_unix_socket_repl: true
  wal_e:
    command: envdir /run/etc/wal-e.d/env bash /scripts/wale_restore.sh
    no_master: 1
    retries: 2
    threshold_backup_size_percentage: 30
    threshold_megabytes: 102400
restapi:
  connect_address: 10.233.117.147:8008
  listen: :8008
scope: ...
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 33554432
postgresql:
  parameters:
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_vacuum_scale_factor: 0.05
    checkpoint_completion_target: 0.9
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_statement: ddl
    log_temp_files: 0
    max_connections: 260
    max_replication_slots: 10
    max_wal_senders: 10
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    track_functions: all
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
ttl: 30
```

**Have you checked Patroni logs?**
When member node-1 joins as standby:
```
INFO: Lock owner: node-0; I am node-1
INFO: establishing a new patroni connection to the postgres cluster
INFO: Local timeline=133 lsn=9/29000000
INFO: master_timeline=134
INFO: master: history=129	9/53E71E8	no recovery target specified
	9/60000A0	no recovery target specified
	9/E000000	no recovery target specified
	9/260000A0	no recovery target specified
INFO: no action. I am a secondary (node-1) and following a leader (node-0)
```

**Have you checked PostgreSQL logs?**
After node-1 starts as standby.
```
2021-10-07 12:28:14.192 UTC,"standby","",92844,"10.233.112.133:38660",615ee7de.16aac,3,"idle",2021-10-07 12:28:14 UTC,9/0,0,ERROR,XX000,"requested starting point 9/26000000 on timeline 132 is not in this server's history","This server's history forked from timeline 132 at 9/25004188.",,,,,"START_REPLICATION SLOT ""node_0"" 9/26000000 TIMELINE 132",,,"node-0"
```

History files

```
root@node-0:/home/postgres# tail pgdata/pgroot/data/pg_wal/00000085.history 

128	9/5000110	no recovery target specified

129	9/53E71E8	no recovery target specified

130	9/60000A0	no recovery target specified

131	9/E000000	no recovery target specified

132	9/25004188	no recovery target specified
root@node-0:/home/postgres# tail pgdata/pgroot/data/pg_wal/00000086.history 

128	9/5000110	no recovery target specified

129	9/53E71E8	no recovery target specified

130	9/60000A0	no recovery target specified

131	9/E000000	no recovery target specified

132	9/260000A0	no recovery target specified
```

Output of `patronictl history` (note that TLI 133 is missing)
```
root@node-0:/home/postgres# patronictl history
+-----+-------------+------------------------------+----------------------------------+------------------------------------------------------+
|  TL |         LSN | Reason                       | Timestamp                        | New Leader                                           |
+-----+-------------+------------------------------+----------------------------------+------------------------------------------------------+
...
| 108 | 30433869824 | no recovery target specified | 2021-09-13T20:05:15.704176+00:00 |        |
| 109 | 30719082496 | no recovery target specified | 2021-09-14T13:40:30.364769+00:00 |        |
| 110 | 31524396216 | no recovery target specified | 2021-09-17T01:12:13.660367+00:00 |        |
| 111 | 32497467552 | no recovery target specified | 2021-09-19T20:59:08.762321+00:00 |        |
| 112 | 32631685120 | no recovery target specified | 2021-09-20T06:27:14.246110+00:00 |        |
| 113 | 33101447168 | no recovery target specified | 2021-09-21T14:17:52.606306+00:00 |        |
| 114 | 33470546080 | no recovery target specified | 2021-09-22T09:04:00.887970+00:00 | node-0 |
| 115 | 33621540864 | no recovery target specified | 2021-09-22T14:25:49.394278+00:00 | node-0 |
| 116 | 34460401664 | no recovery target specified | 2021-09-25T01:11:41.196702+00:00 | node-1 |
| 117 | 35366371488 | no recovery target specified | 2021-09-27T14:00:13.501485+00:00 | node-1 |
| 118 | 35383148704 | no recovery target specified | 2021-09-27T14:00:39.834182+00:00 | node-0 |
| 119 | 36540776448 | no recovery target specified | 2021-09-30T20:20:25.338109+00:00 | node-1 |
| 120 | 36624705792 | no recovery target specified | 2021-10-01T00:03:53.489931+00:00 | node-0 |
| 121 | 38000394400 | no recovery target specified | 2021-10-04T14:00:06.464126+00:00 | node-1 |
| 122 | 38453379072 | no recovery target specified | 2021-10-05T19:38:56.991454+00:00 | node-0 |
| 123 | 38705037312 | no recovery target specified | 2021-10-06T07:54:54.560519+00:00 | node-0 |
| 124 | 38708660648 | no recovery target specified | 2021-10-06T07:58:42.028846+00:00 | node-0 |
| 125 | 38713165680 | no recovery target specified | 2021-10-06T08:23:46.381883+00:00 | node-1 |
| 126 | 38717020568 | no recovery target specified | 2021-10-06T08:49:08.620239+00:00 | node-0 |
| 127 | 38720768048 | no recovery target specified | 2021-10-06T08:49:37.700275+00:00 | node-0 |
| 128 | 38738592016 | no recovery target specified | 2021-10-06T09:45:59.941295+00:00 | node-0 |
| 129 | 38742684136 | no recovery target specified | 2021-10-06T09:49:06.034448+00:00 | node-0 |
| 130 | 38755369120 | no recovery target specified | 2021-10-06T09:52:44.811576+00:00 | node-0 |
| 131 | 38889586688 | no recovery target specified | 2021-10-06T15:30:19.122568+00:00 | node-0 |
| 132 | 39292240032 | no recovery target specified |                                  |        |
| 134 | 39778779296 | no recovery target specified | 2021-10-08T20:42:30.173105+00:00 | node-0 |
| 135 | 40298872992 | no recovery target specified | 2021-10-10T00:29:37.862196+00:00 | node-0 |
| 136 | 40433090720 | no recovery target specified | 2021-10-11T11:39:30.158768+00:00 | node-0 |
| 137 | 40852521120 | no recovery target specified | 2021-10-12T15:39:51.220549+00:00 | node-0 |
| 138 | 42932895904 | no recovery target specified | 2021-10-18T14:21:47.626198+00:00 | node-0 |
| 139 | 43402657952 | no recovery target specified | 2021-10-19T15:46:51.444482+00:00 | node-0 |
| 140 | 44828721152 | no recovery target specified | 2021-10-23T22:39:45.445003+00:00 | node-0 |
| 141 | 45281705984 | no recovery target specified | 2021-10-25T06:52:07.410663+00:00 | node-0 |
| 142 | 45717913600 | no recovery target specified | 2021-10-26T14:36:42.914354+00:00 | node-0 |
| 143 | 47227881232 | no recovery target specified | 2021-10-30T22:20:56.067080+00:00 | node-0 |
| 144 | 47781511328 | no recovery target specified | 2021-11-01T14:21:21.849360+00:00 | node-0 |
| 145 | 47932506112 | no recovery target specified | 2021-11-01T21:08:00.850967+00:00 | node-0 |
| 146 | 48469377024 | no recovery target specified | 2021-11-03T10:06:31.238604+00:00 | node-0 |
| 147 | 48637149344 | no recovery target specified | 2021-11-03T17:10:01.236241+00:00 | node-0 |
+-----+-------------+------------------------------+----------------------------------+------------------------------------------------------+
```

**Additional context**

Node names were changed.

[Discussion in Slack](https://postgresteam.slack.com/archives/C9XPYG92A/p1636475881105500)
