### ISSUE TITLE
Transition of transactions to Read only

### ISSUE THREAD

**Issue by feelan03** [zalando/patroni#2134]
Hi. I am using Patroni 2.1.1 (Raft) from 3 nodes and PG 14.0 and am getting the problem when changing the leader. If the leader changes to a second or third node, then all postgres transactions become read only. What is the reason I cannot understand, the config is correct. Help me solve it
В данный момент когда переключается лидер на вторую или третью ноду, я чиню это с помощью `patronictl -c /etc/patroni.yml switchover` и назначяю первую ноду снова лидером.

Here is an example of one of the node configs
```
scope: prod
name: postgresql1

### logging
log:
    dir: /data/logs/patroni
    file_num: 3
    file_size: 52428800 # 50MB

restapi:
    listen: 10.110.100.1:8008
    connect_address: 10.110.100.1:8008

raft:
    data_dir: /data/raft
    self_addr: 10.110.100.1:5010
    partner_addrs:
        - 10.110.100.2:5010
        - 10.110.100.3:5010

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            checkpoint_completion_target: 0.9
            default_statistics_target: 100
            effective_cache_size: 3GB
            effective_io_concurrency: 200
            maintenance_work_mem: 1024MB
            max_connections: 1509
            max_parallel_maintenance_workers: 2
            max_parallel_workers: 4
            max_parallel_workers_per_gather: 2
            max_wal_size: 4GB
            max_worker_processes: 4
            min_wal_size: 1GB
            random_page_cost: 1.1
            shared_buffers: 1GB
            temp_buffers: 96MB
            wal_buffers: 16MB
            work_mem: 1024MB
            use_pg_rewind: true
            shared_preload_libraries: pg_stat_statements
            pg_stat_statements.max: 1000
            pg_stat_statements.track: all

    initdb:
        - encoding: UTF8
        - data-checksums

    pg_hba:
        - host replication replicator 127.0.0.1/32 md5
        - host replication replicator 10.110.100.1/0 md5
        - host replication replicator 10.110.100.2/0 md5
        - host replication replicator 10.110.100.3/0 md5
        - host all all 0.0.0.0/0 md5
    users:
        admin:
            password: asferpingiwv
            options:
                - createrole
                - createdb

postgresql:
    listen: 10.110.100.1:5432
    connect_address: 10.110.100.1:5432
    data_dir: /data/pg
    bin_dir: /usr/lib/postgresql/14/bin
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: pass
        superuser:
            username: postgres
            password: pass
    parameters:
        unix_socket_directories: '.'
        log_directory: /data/logs/pg
        logging_collector: on

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```
