### ISSUE TITLE
Switchover/Failover fails if cascade replication and replication slots are used

### ISSUE THREAD

**Issue by velechac** [zalando/patroni#2137]
**Describe the bug**
Patroni is not able to provide switchover or failover if cascade replication and replication slots are used.

**To Reproduce**
* 4 nodes in cascade replication

   ![pg-replication-schema_2-2](https://user-images.githubusercontent.com/1170359/144832821-f8639a33-ace6-41aa-b9f1-67ac4e3f1e98.png)

* `tags.replicatefrom` some node must be set on replica2
* `postgresql.use_slots: True`
* call `patronictl switchover` or `patronictl failover`

**Expected behavior**
Patroni should provide switchover or failover.

**Environment**
- Patroni version: >=2.1.0
- PostgreSQL version: tested with 12, 13, 14
- DCS (and its version): etcd

**Patroni configuration file**
```
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 0
    postgresql:
      parameters:
        max_connections: '100'
        max_locks_per_transaction: 64
        max_prepared_transactions: 0
        max_replication_slots: '5'
        max_wal_senders: '10'
        max_worker_processes: 8
        ssl_cert_file: ... 
        ssl_key_file: .. 
        track_commit_timestamp: 'off'
        wal_keep_segments: '100'
        wal_keep_size: '1600'
        wal_level: hot_standby
        wal_log_hints: 'on'
      use_pg_rewind: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - encoding: UTF8
  - data-checksums
  pg_hba:
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator sandbox1 md5
  - host replication replicator sandbox2 md5
  - host replication replicator sandbox3 md5
  - host replication replicator sandbox4 md5
  - local all postgres  peer map=admins
  - local all all  md5 
  - hostssl all postgres 0.0.0.0/0 cert 
  - hostssl all postgres ::0/0 cert 
  - host all all 0.0.0.0/0 md5 
  - host all all ::0/0 md5 
  pg_ident:
  - admins postgres postgres
  - admins root postgres
  - admins prometheus postgres
  post_bootstrap: /tmp/post_bootstrap.sh
etcd:
  cacert: ...
  cert: ...
  hosts:
   - etcd1:2379
   - etcd2:2379
   - etcd3:2379
  key: ... 
  password: XXX
  protocol: https
  username: sandbox-test
log:
  level: INFO
name: sandbox1
namespace: /sandbox-test/
postgresql:
  authentication:
    replication:
      password: XXX
      username: replicator
    superuser:
      password: XXX
      username: postgres
  basebackup:
    checkpoint: fast
    max-rate: 100M
  bin_dir: /usr/lib/postgresql/12/bin/
  config_dir: /etc/postgresql/12/main
  connect_address: 10.244.11.136:5432
  create_replica_methods:
  - basebackup
  data_dir: /var/lib/postgresql/12/main
  listen: '*:5432'
  parameters:
    max_connections: '100'
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: '5'
    max_wal_senders: '10'
    max_worker_processes: 8
    ssl_cert_file: ... 
    ssl_key_file: ... 
    track_commit_timestamp: 'off'
    wal_keep_segments: '100'
    wal_keep_size: '1600'
    wal_level: hot_standby
    wal_log_hints: 'on'
  pg_hba:
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator sandbox1 md5
  - host replication replicator sandbox2 md5
  - host replication replicator sandbox3 md5
  - host replication replicator sandbox4 md5
  - local all postgres  peer map=admins
  - local all all  md5 
  - hostssl all postgres 0.0.0.0/0 cert 
  - hostssl all postgres ::0/0 cert 
  - host all all 0.0.0.0/0 md5 
  - host all all ::0/0 md5 
  pg_ident:
  - admins postgres postgres
  - admins root postgres
  - admins prometheus postgres
  pgpass: /var/lib/postgresql/.pgpass
  use_slots: true
restapi:
  authentication:
    password: XXX 
    username: sandbox-test
  certfile: null
  connect_address: 10.244.11.136:8008
  keyfile: null
  listen: :8008
scope: main
tags:
  clonefrom: false
  nofailover: false  # true on sandbox3 and sandbox4
  noloadbalance: false
  nosync: false
  replicatefrom: false # sandbox1 on host sandbox3 | sandbox2 on host sandbox4
```

**patronictl show-config**
```yaml
loop_wait: 10
maximum_lag_on_failover: 0
postgresql:
  parameters:
    max_connections: '100'
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: '5'
    max_wal_senders: '10'
    max_worker_processes: 8
    ssl_cert_file: ...
    ssl_key_file: ... 
    track_commit_timestamp: 'off'
    wal_keep_segments: '100'
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
```
ERROR: Unexpected exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1471, in run_cycle
    info = self._run_cycle()
  File "/usr/lib/python3/dist-packages/patroni/ha.py", line 1312, in _run_cycle
    self.state_handler.reset_cluster_info_state(self.cluster, self.patroni.nofailover)
  File "/usr/lib/python3/dist-packages/patroni/postgresql/__init__.py", line 329, in reset_cluster_info_state
    cluster.has_permanent_logical_slots(self.name, nofailover, self.major_version)
  File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 572, in has_permanent_logical_slots
    slots = self.get_replication_slots(my_name, 'replica', nofailover, major_version).values()
  File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 518, in get_replication_slots
    slot_members = [m.name for m in self.members if use_slots and
  File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 519, in <listcomp>
    m.replicatefrom == my_name and m.name != self.leader.name]
AttributeError: 'NoneType' object has no attribute 'name'
INFO: Unexpected exception raised, please report it as a BUG
```

**Additional context**
Debian Buster machine is used for the installation. If `tags.nofailover` is commented and patroni is reloaded, then the cluster can be recovered automatically.

```
+ Cluster: main (7038499416752341862) -+---------------+---------+---------+----+-----------+-----------------------------------------------------+
| Member                               | Host          | Role    | State   | TL | Lag in MB | Tags                                                |
+--------------------------------------+---------------+---------+---------+----+-----------+-----------------------------------------------------+
| sandbox1                             | 10.244.11.136 | Leader  | running |  1 |           | replicatefrom: false                                |
+--------------------------------------+---------------+---------+---------+----+-----------+-----------------------------------------------------+
| sandbox2                             | 10.245.7.130  | Replica | running |  1 |         0 | replicatefrom: false                                |
+--------------------------------------+---------------+---------+---------+----+-----------+-----------------------------------------------------+
| sandbox3                             | 10.244.11.174 | Replica | running |  1 |         0 | nofailover: true                                    |
|                                      |               |         |         |    |           | replicatefrom: sandbox1                             |
+--------------------------------------+---------------+---------+---------+----+-----------+-----------------------------------------------------+
| sandbox4                             | 10.245.7.99   | Replica | running |  1 |         0 | nofailover: true                                    |
|                                      |               |         |         |    |           | replicatefrom: sandbox2                             |                                                                 
+--------------------------------------+---------------+---------+---------+----+-----------+-----------------------------------------------------+
```
