### ISSUE TITLE
WAL replay with patroni on delayed-replication 

### ISSUE THREAD

**Issue by bhairavdhanwade** [zalando/patroni#2139]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version: 2.36
2. PostgreSQL version: 13.5
3. Operating system/version - Ubuntu 20.04
4. Did you install pgBackRest from source or from a package ? : From package 

Description :
 - We have created delayed replication node successfully and its working fine.
    --  Configuration for reference: 
 `patroni.yml` - On Leader Server:
```
scope: test-dr-infra
namespace: /dbs/
name: dr-db-node1

restapi:
  listen: 1.2.3.4:8008
  connect_address: 1.2.3.4:8008

etcd:
  hosts: 2.3.4.5:2379,3.4.5.6:2379,4.5.6.7:2379
bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 512000
        postgresql:
            parameters:
                listen_addresses: '*'
                port: 5432
                archive_command: 'pgbackrest --stanza=test archive-push %p'
    method: pgbackrest
    pgbackrest:
        command: /etc/boot_pgbackrest.sh
        keep_existing_recovery_conf: False
        no_params: False
        recovery_conf:
            recovery_target: immediate
            recovery_target_action: pause
            restore_command: /usr/bin/pgbackrest --stanza=test archive-get %f %p                
    initdb:
        - encoding: UTF8
        - data-checksums
    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb       
postgresql:
    listen: 1.2.3.4:5432
    connect_address: 1.2.3.4:5432
    data_dir: /var/lib/postgresql/13/main
    bin_dir: /usr/lib/postgresql/13/bin
    config_dir: /etc/postgresql/13/main
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: repuser
            password: *******
        superuser:
            username: postgres
    create_replica_methods:
           - basebackup
           - pgbackrest
    pgbackrest:
           command: "pgbackrest --stanza=test --log-level-console=detail --delta --target-action=promote --type=immediate restore --link-all"
           keep_existing_recovery_conf: false
           keep_data: false
           no_params: false           
    parameters:
        unix_socket_directories: '/var/run/postgresql'
        stats_temp_directory: /var/run/postgresql/13-main.pg_stat_tmp
        wal_level: replica
        archive_mode: on
        archive_command: "/usr/bin/pgbackrest --stanza=test archive-push %p"
        log_statement: all
    recovery_conf:
        standby_mode: 'on'
        restore_command: "/usr/bin/pgbackrest --stanza=test archive-get %f %p"
        recovery_target_timeline: 'latest'
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log: 
   dir: /var/log/patroni/
```
 `patroni.yml` - On Delayed Replication :
 ```
scope: test-dr-infra
namespace: /dbs/
name: dr-db-node2

restapi:
  listen: 7.8.9.10:8008
  connect_address: 7.8.9.10:8008

etcd:
  hosts: 2.3.4.5:2379,3.4.5.6:2379,4.5.6.7:2379
bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 512000
        postgresql:
            parameters:
                listen_addresses: '*'
                port: 5432
                archive_command: 'pgbackrest --stanza=test archive-push %p'
    method: pgbackrest
    pgbackrest:
        command: /etc/boot_pgbackrest.sh
        keep_existing_recovery_conf: False
        no_params: False
        recovery_conf:
            recovery_target: immediate
            recovery_target_action: pause
            restore_command: /usr/bin/pgbackrest --stanza=test archive-get %f %p                
    initdb:
        - encoding: UTF8
        - data-checksums
    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb       
postgresql:
    listen: 7.8.9.10:5432
    connect_address: 7.8.9.10:5432
    data_dir: /var/lib/postgresql/13/main
    bin_dir: /usr/lib/postgresql/13/bin
    config_dir: /etc/postgresql/13/main
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: repuser
            password: *******
        superuser:
            username: postgres
    create_replica_methods:
           - basebackup
           - pgbackrest
    pgbackrest:
           command: "pgbackrest --stanza=test --log-level-console=detail --delta --target-action=promote --type=immediate restore --link-all"
           keep_existing_recovery_conf: false
           keep_data: false
           no_params: false           
    parameters:
        unix_socket_directories: '/var/run/postgresql'
        stats_temp_directory: /var/run/postgresql/13-main.pg_stat_tmp
        wal_level: replica
        archive_mode: on
        archive_command: "/usr/bin/pgbackrest --stanza=test archive-push %p"
        log_statement: all
    recovery_conf:
        standby_mode: 'on'
        restore_command: "/usr/bin/pgbackrest --stanza=test archive-get %f %p"
        recovery_min_apply_delay: '1h'
        recovery_target_timeline: 'latest'   	
tags:
    nofailover: true
    noloadbalance: false
    clonefrom: false
    nosync: false

log: 
   dir: /var/log/patroni/
 ```
  **Now we want to replay WAL and reach to particular time (PITR) by using below configuration, But some how we are reaching to latest state.**
  **-- Before performing below changes and patroni restart we are making all node down in Cluster. So This node become a master and do PITR.**
```
scope: test-dr-infra
namespace: /dbs/
name: dr-db-node2

restapi:
  listen: 7.8.9.10:8008
  connect_address: 7.8.9.10:8008

etcd:
  hosts: 2.3.4.5:2379,3.4.5.6:2379,4.5.6.7:2379
bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 512000
        postgresql:
            parameters:
                listen_addresses: '*'
                port: 5432
                archive_command: 'pgbackrest --stanza=test archive-push %p'
    method: pgbackrest
    pgbackrest:
        command: /etc/boot_pgbackrest.sh
        keep_existing_recovery_conf: False
        no_params: False
        recovery_conf:
            recovery_target: immediate
            recovery_target_action: pause
            restore_command: /usr/bin/pgbackrest --stanza=test archive-get %f %p                
    initdb:
        - encoding: UTF8
        - data-checksums
    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb       
postgresql:
    listen: 7.8.9.10:5432
    connect_address: 7.8.9.10:5432
    data_dir: /var/lib/postgresql/13/main
    bin_dir: /usr/lib/postgresql/13/bin
    config_dir: /etc/postgresql/13/main
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: repuser
            password: *******
        superuser:
            username: postgres
    create_replica_methods:
           - basebackup
           - pgbackrest
    pgbackrest:
           command: "pgbackrest --stanza=test --log-level-console=detail --delta --target-action=promote --type=immediate restore --link-all"
           keep_existing_recovery_conf: false
           keep_data: false
           no_params: false           
    parameters:
        unix_socket_directories: '/var/run/postgresql'
        stats_temp_directory: /var/run/postgresql/13-main.pg_stat_tmp
        wal_level: replica
        archive_mode: on
        archive_command: "/usr/bin/pgbackrest --stanza=test archive-push %p"
        log_statement: all
    recovery_conf:
        standby_mode: off
        restore_command: "/usr/bin/pgbackrest --stanza=test archive-get %f %p"
        recovery_target_time: "2021-12-08 10:38:14 UTC"
        recovery_target_action: "promote"
        # recovery_target_xid: 586273
        # recovery_target: "immediate"
        recovery_target_inclusive: "false"
        recovery_target_timeline: 'latest'
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log: 
   dir: /var/log/patroni/
```
 We believe we are doing something wrong in **postgresql.recovery_conf** section while doing WAL replay (PITR). Can you please help us.
