### ISSUE TITLE
There are no PATRONI_* environment variables inside the callback (e.g. on_reload). All other variables are set

### ISSUE THREAD

**Issue by ADMDevMit** [zalando/patroni#2141]
**Describe the bug**
It looks like the PATRONI_* environment variables are removed before the callback is executed

**To Reproduce**
1. Set in shell/docker PATRONI_NAME, PATRONI_SCOPE or other PATRONI_* variable
2. In callback script try to echo PATRONI_* variable (set earlier) or use env/set to list environment variables
3. The PATRONI_* variables will be missing

**Expected behavior**
All PATRONI_* environment variables set in the shell must be set with other shell variables.

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 13.4
- DCS (and its version): etcd 3.4

**Patroni configuration file**
<details><summary>patroni.yml</summary>

```
# Общий файл конфигурации
# Параметры для каждой ноды указываются в docker-compose.yml через переменные среды

#z scope: cluster-name
scope: cp
#namespace: /service/
#z name: srv

restapi:
  listen: 0.0.0.0:8008
  certfile: /etc/patroni/certs/cert.pem
  keyfile: /etc/patroni/certs/key.pem
  authentication:
    username: usr
    password: pwd

etcd3:

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums
  - auth-host: scram-sha-256
  - auth-local: peer

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 0.0.0.0/0 scram-sha-256
  - host all all 0.0.0.0/0 scram-sha-256

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: pwd
      options:
      - createrole
      - createdb

postgresql:
  listen: 0.0.0.0:5432
  data_dir: /var/lib/postgresql/data
  config_dir: /var/lib/postgresql/data
  pgpass: /var/lib/postgresql/.pgpass
  authentication:
    replication:
      username: replicator
      password: pwd
    superuser:
      username: postgres
      password: pwd
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: pwd
  parameters:
    unix_socket_directories: '/var/run/postgresql/'
  # Additional fencing script executed after acquiring the leader lock but before promoting the replica
  #pre_promote: /path/to/pre_promote.sh
  callbacks:
    on_reload: /etc/patroni/patroni-callback.sh
    on_restart: /etc/patroni/patroni-callback.sh
    on_role_change: /etc/patroni/patroni-callback.sh
    on_start: /etc/patroni/patroni-callback.sh
    on_stop: /etc/patroni/patroni-callback.sh

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

</details>

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters: null
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
<details><summary>log fragment with env call:</summary>

```
...
pg      | this is patroni callback on_reload replica cp
pg      | ------------------
pg      | POSTGRES_HOST_AUTH_METHOD=scram-sha-256
pg      | HOSTNAME=srv2
pg      | POSTGRES_PASSWORD=<pwd>
pg      | PWD=/
pg      | TZ=Europe/Moscow
pg      | HOME=/var/lib/postgresql
pg      | LANG=en_US.utf8
pg      | GOSU_VERSION=1.12
pg      | POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
pg      | PG_MAJOR=13
pg      | PG_VERSION=13.4-4.pgdg110+1
pg      | SHLVL=2
pg      | PATRONICTL_CONFIG_FILE=/etc/patroni/patroni.yml
pg      | PGDATA=/var/lib/postgresql/data
pg      | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/13/bin
pg      | _=/usr/bin/env
pg      | ------------------
...
```

</details>

**Have you tried to use GitHub issue search?**
Yes
