### ISSUE TITLE
Question : standby replication from (replicatefrom) replica node.

### ISSUE THREAD

**Issue by mineexchange89** [zalando/patroni#2143]
Hello, 

We have Primary and Secondary standby cluster running with patroni and its working great. (Manual failover in between  primary and stand by   cluster).

We want to overcome resource utilization on Leader node. So we are just thinking to fetch WAL from replica instead of Leader server to standby leader. (We have also pgbackrest integration and WAL are archiving on S3 but we want to fetch from replica only).

We know replication_slot functionality how it work but still we are interested if is there any workaround to achieve this.

**Comment by CyberDem0n** [comment]
> any workaround to achieve this.

achieve what?

**Comment by mineexchange89** [comment]
@CyberDem0n Thanks for your super fast response. 
> achieve what?
We want to pull WAL (replicatefrom) from Replica node instead of Leader node on standby leader.

**Comment by CyberDem0n** [comment]
Documentation seems to be not very correct: https://patroni.readthedocs.io/en/latest/SETTINGS.html#tags
`tags.replicatefrom` should contain the other node name where you want to replicate from.

**Comment by mineexchange89** [comment]
> `tags.replicatefrom` should contain the other node name where you want to replicate from.

Ohh Thanks  ... you mean to say if we add this tag on replica node with name of standby leader than it will replicate data on standby leader.

**Comment by CyberDem0n** [comment]
> Ohh Thanks ... you mean to say if we add this tag on replica node with name of standby leader than it will replicate data on standby leader.

NO! Standby cluster and standby leader are absolutely different concepts https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#standby-cluster

**Comment by Tekchanddagar** [comment]
@CyberDem0n , As per my understanding @mineexchange89 have `primary cluster` and `standby cluster` at his/her end. But he/she is asking is it possible to use `primary cluster replica` node `IP` in `standby cluster` config:
```
bootstrap:
    dcs:
        standby_cluster:
            host: remote_master_IP
            port: 5432
            primary_slot_name: patroni
            create_replica_methods:
            - basebackup
```
Beacuse when we fetch the WAL from remote master on `standby cluster` then it will use some resources of `remote master` and he/she  want to decrease `remote master` overhead.

@mineexchange89 , Please confirm if I understood your question correctly.

Thank You

**Comment by mineexchange89** [comment]
> @mineexchange89 , Please confirm if I understood your question correctly.

Thanks @Tekchanddagar for elaboration. 
```
       standby_cluster:
            host: remote_replica_IP
            port: 5432
            primary_slot_name: patroni
```
