### ISSUE TITLE
Database failover occurs when the raft cluster leader is changed

### ISSUE THREAD

**Issue by BillyBonsYM** [zalando/patroni#2147]
**Describe the bug**
We use patroni with pure raft, its our intented and conscious choosen solution because of the capabilities of our network.
During testing different scenario we hit the following issue. Change the leader of raft cluster leads to failover of patroni cluster.
This event happens from time to time, there is no network outage at this time, no database overhead and everyhthing is fine with hosts, consisted in cluster.

**To Reproduce**
I add here the explanation.
https://postgresteam.slack.com/archives/C9XPYG92A/p1638430054172000

**Expected behavior**

We consider, that change leadership in raft cluster should not affect patroni cluster. 

**Screenshots**

**Environment**
- Patroni version: **patroni 2.1.1**
- PostgreSQL version:  **PostgreSQL 9.5.25 and PostgreSQL 11.7**
- DCS (and its version): **internal raft(pysyncobj-0.3.10)**

**Patroni configuration file**

We have two config files, for raft and for patroni.
```
*********
raft:
  data_dir: /var/lib/raft/
  self_addr: iva-pgtools2.yamoney.ru:15432
  partner_addrs:
    - iva-pg-receiverng.yamoney.ru:15432
    - iva-pgtools.yamoney.ru:15432
    - ugr-pg-receiverng.yamoney.ru:15432
    - ugr-pgtools2.yamoney.ru:15432
 **********
scope: pgtools
name: iva-pgtools2.yamoney.ru

restapi:
  listen: 0.0.0.0:15433
  connect_address: iva-pgtools2.yamoney.ru:15433

raft:
  partner_addrs:
    - iva-pg-receiverng.yamoney.ru:15432
    - iva-pgtools.yamoney.ru:15432
    - iva-pgtools2.yamoney.ru:15432
    - ugr-pg-receiverng.yamoney.ru:15432
    - ugr-pgtools2.yamoney.ru:15432

log:
  dir: /var/log/patroni/
  level: DEBUG
  traceback_level: DEBUG

bootstrap:
  dcs:
    ttl: 60
    loop_wait: 5
    retry_timeout: 20
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        wal_level: hot_standby
        hot_standby: "on"
        wal_keep_segments: "8192"
        max_wal_senders: "5"
        max_replication_slots: "5"
        max_locks_per_transaction: "8192"
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: /bin/true
        max_connections: "1000"
      callbacks:
        on_role_change: /etc/patroni/change.sh

  initdb:
    - encoding: UTF8
    - data-checksums

postgresql:
  listen: 0.0.0.0:5432
  connect_address: iva-pgtools2.yamoney.ru:5432
  data_dir: /var/lib/postgresql/9.5/main/
  bin_dir: /usr/lib/postgresql/9.5/bin/
  config_dir: /etc/postgresql/9.5/main/
  use_unix_socket: true
  use_unix_socket_repl: true

  authentication:
    replication:
      username: postgres
    superuser:
      username: postgres
    rewind:
      username: postgres

watchdog:
  mode: off
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
  replicatefrom: iva-pgtools.yamoney.ru
```

**patronictl show-config**
```
root@iva-pgtools2:~# patronictl show-config
ignore_slots:
- name: barman
  type: physical
loop_wait: 5
master_start_timeout: 300
maximum_lag_on_failover: 1048576
pause: true
postgresql:
  callbacks:
    on_role_change: /etc/patroni/change.sh
  parameters:
    archive_command: /bin/true
    archive_mode: 'on'
    archive_timeout: 1800s
    hot_standby: 'on'
    max_connections: 1000
    max_locks_per_transaction: 8192
    max_replication_slots: 5
    max_wal_senders: 5
    wal_keep_segments: 8192
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: false
retry_timeout: 20
synchronous_mode: false
ttl: 60

```

**Have you checked Patroni logs?**

2021-11-24 07:52:58,070 INFO: PAUSE: no action. I am (iva-pgtools.yamoney.ru) the leader with the lock
2021-11-24 07:53:03,069 INFO: PAUSE: no action. I am (iva-pgtools.yamoney.ru) the leader with the lock
2021-11-24 07:53:08,068 INFO: PAUSE: no action. I am (iva-pgtools.yamoney.ru) the leader with the lock
2021-11-24 07:53:13,070 INFO: PAUSE: no action. I am (iva-pgtools.yamoney.ru) the leader with the lock
2021-11-24 07:53:18,068 INFO: PAUSE: no action. I am (iva-pgtools.yamoney.ru) the leader with the lock
2021-11-24 07:53:23,068 INFO: PAUSE: no action. I am (iva-pgtools.yamoney.ru) the leader with the lock
2021-11-24 07:53:28,070 INFO: PAUSE: no action. I am (iva-pgtools.yamoney.ru) the leader with the lock
2021-11-24 07:53:41,974 INFO: PAUSE: no action. I am (iva-pgtools.yamoney.ru) the leader with the lock
2021-11-24 07:53:41,976 WARNING: Loop time exceeded, rescheduling immediately.
2021-11-24 07:53:41,977 INFO: Lock owner: iva-pgtools.yamoney.ru; I am iva-pgtools.yamoney.ru
2021-11-24 07:54:02,017 ERROR: failed to update leader lock
2021-11-24 07:54:04,021 INFO: PAUSE: continue to run as master after failing to update leader lock in DCS
2021-11-24 07:54:04,023 WARNING: Loop time exceeded, rescheduling immediately.
2021-11-24 07:54:04,024 INFO: Lock owner: iva-pgtools.yamoney.ru; I am iva-pgtools.yamoney.ru
2021-11-24 07:54:24,060 ERROR: failed to update leader lock
2021-11-24 07:54:26,064 INFO: PAUSE: continue to run as master after failing to update leader lock in DCS
2021-11-24 07:54:26,065 WARNING: Loop time exceeded, rescheduling immediately.
2021-11-24 07:54:26,066 INFO: Lock owner: iva-pgtools.yamoney.ru; I am iva-pgtools.yamoney.ru
2021-11-24 07:54:46,103 ERROR: failed to update leader lock
2021-11-24 07:54:48,107 INFO: PAUSE: continue to run as master after failing to update leader lock in DCS
2021-11-24 07:54:48,109 WARNING: Loop time exceeded, rescheduling immediately.
2021-11-24 07:54:48,109 INFO: Lock owner: iva-pgtools.yamoney.ru; I am iva-pgtools.yamoney.ru
2021-11-24 07:55:08,145 ERROR: failed to update leader lock
2021-11-24 07:55:10,149 INFO: PAUSE: continue to run as master after failing to update leader lock in DCS
2021-11-24 07:55:10,151 WARNING: Loop time exceeded, rescheduling immediately.
2021-11-24 07:55:10,152 INFO: Lock owner: iva-pgtools.yamoney.ru; I am iva-pgtools.yamoney.ru

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
