### ISSUE TITLE
No leader available

### ISSUE THREAD

**Issue by mzimmer-ra** [zalando/patroni#2151]
**Describe the bug**
There is no leader node available.

**To Reproduce**
Create a Cluster with 2 nodes. The cluster crashed with both nodes. After that, the old leader node was deleted and a new second node was started.

**Expected behavior**
The Slave Database should become master.

**Screenshots**
+Cluster: acid-minimal-cluster (7040910440143814725) -----+----+-------+
| Member                       | Host            | Role       | State      | TL   | Lag in MB |
+------------------------+-------------+---------+----------+----+-----------+
| acid-minimal-cluster-0 | 10.42.3.184 | Replica  | running  | 77  |       784     |
| acid-minimal-cluster-1 | 10.42.3.183 | Replica  | stopped |       |  unknown |
+------------------------+-------------+---------+---------+----+-----------+

acid-minimal-cluster-0 is the old slave-node.
acid-minimal-cluster-1 has no data and is the old master-node.

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 14.0 (Ubuntu 14.0-1.pgdg18.04+1)
- etcd Version: 2.3.8

**Patroni configuration file**
I'm using the default configuration of the acid-minimal-cluster form zalando/postgres-operator. I hope this file is the right configuration file:
```
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_mode: 'on'
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.05
        checkpoint_completion_target: 0.9
        hot_standby: 'on'
        log_autovacuum_min_duration: 0
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_lock_waits: 'on'
        log_min_duration_statement: 500
        log_statement: ddl
        log_temp_files: 0
        max_connections: 100
        max_replication_slots: 10
        max_wal_senders: 10
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        track_functions: all
        wal_compression: 'on'
        wal_level: hot_standby
        wal_log_hints: 'on'
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - auth-host: md5
  - auth-local: trust
  post_init: /scripts/post_init.sh "zalandos"
  users:
    zalandos:
      options:
      - CREATEDB
      - NOLOGIN
      password: ''
kubernetes:
  bypass_api_service: true
  labels:
    application: spilo
  pod_ip: 10.42.3.184
  ports:
  - name: postgresql
    port: 5432
  role_label: spilo-role
  scope_label: cluster-name
  use_endpoints: true
namespace: postgres
postgresql:
  authentication:
    replication:
      password: q6NQVoxvqjwNTBsX8q1BGNzxmZdndMqoraz5nJ9uOQuqQng7xUq5U6FTSzvA8zJz
      username: standby
    superuser:
      password: kqEPWScpsowO2oyf1g21TwXgwZL4L5Pu48SPhzvsYEtK1j1KW0hKmfuijxZtAYfx
      username: postgres
  basebackup_fast_xlog:
    command: /scripts/basebackup.sh
    retries: 2
  bin_dir: /usr/lib/postgresql/14/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos true
  connect_address: 10.42.3.184:5432
  create_replica_method:
  - basebackup_fast_xlog
  data_dir: /home/postgres/pgdata/pgroot/data
  listen: '*:5432'
  name: acid-minimal-cluster-0
  parameters:
    archive_command: /bin/true
    bg_mon.history_buckets: 120
    bg_mon.listen_address: 0.0.0.0
    extwlist.custom_path: /scripts
    extwlist.extensions: btree_gin,btree_gist,citext,hstore,intarray,ltree,pgcrypto,pgq,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,hypopg,pg_partman
    log_destination: csvlog
    log_directory: ../pg_log
    log_file_mode: '0644'
    log_filename: postgresql-%u.log
    log_rotation_age: 1d
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    pg_stat_statements.track_utility: 'off'
    shared_buffers: 100MB
    shared_preload_libraries: bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,pg_cron,pg_stat_kcache
    ssl: 'on'
    ssl_cert_file: /run/certs/server.crt
    ssl_key_file: /run/certs/server.key
  pg_hba:
  - local   all             all                                   trust
  - hostssl all             +zalandos    127.0.0.1/32       pam
  - host    all             all                127.0.0.1/32       md5
  - hostssl all             +zalandos    ::1/128            pam
  - host    all             all                ::1/128            md5
  - local   replication     standby                    trust
  - hostssl replication     standby all                md5
  - hostnossl all           all                all                reject
  - hostssl all             +zalandos    all                pam
  - hostssl all             all                all                md5
  pgpass: /run/postgresql/pgpass
  use_unix_socket: true
  use_unix_socket_repl: true
restapi:
  connect_address: 10.42.3.184:8008
  listen: :8008
scope: acid-minimal-cluster
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 33554432
postgresql:
  parameters:
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_vacuum_scale_factor: 0.05
    checkpoint_completion_target: 0.9
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_statement: ddl
    log_temp_files: 0
    max_connections: 100
    max_replication_slots: 10
    max_wal_senders: 10
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    track_functions: all
    wal_compression: 'on'
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
Not available.

**Have you checked PostgreSQL logs?**
Node 1 (acid-minimal-cluster-0):
```
2021-12-28 23:29:11,972 INFO: following a different leader because i am not the healthiest node
2021-12-28 23:29:21,963 INFO: My wal position exceeds maximum replication lag
2021-12-28 23:29:21,972 INFO: following a different leader because i am not the healthiest node
2021-12-28 23:29:31,963 INFO: My wal position exceeds maximum replication lag
2021-12-28 23:29:31,971 INFO: following a different leader because i am not the healthiest node
```

Node 2 (acid-minimal-cluster-1):
```
2021-12-28 23:30:27,231 INFO: Lock owner: None; I am acid-minimal-cluster-1
2021-12-28 23:30:27,231 INFO: waiting for leader to bootstrap
2021-12-28 23:30:37,231 INFO: Lock owner: None; I am acid-minimal-cluster-1
2021-12-28 23:30:37,231 INFO: waiting for leader to bootstrap
2021-12-28 23:30:47,231 INFO: Lock owner: None; I am acid-minimal-cluster-1
2021-12-28 23:30:47,231 INFO: waiting for leader to bootstrap
```

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved. -> Could not be resolved with solutions of similar issues like #2140 (#2137 ).

**Additional context**
/
