### ISSUE TITLE
Switchover failed, details: 412, switchover is not possible: no good candidates have been found

### ISSUE THREAD

**Issue by bagafoot** [zalando/patroni#2153]
Hello,

when I try switchover get tihs error from master  and replika servers.
patronictl version 2.1.2
etcdctl version: 3.3.11
API version: 2
Centos7
this is from master node
![prod](https://user-images.githubusercontent.com/30403489/147668844-12d6f969-5a66-4c9d-a4db-6bf2b600c92b.PNG)

this is from replika node
![replika](https://user-images.githubusercontent.com/30403489/147668893-eeef1eae-43ba-4fb2-807c-69aa4791e772.PNG)


bootstrap1
```
bootstrap:
  dcs:
    loop_wait: 5
    ttl: 30
    retry_timeout: 10
#    maximum_lag_on_failover: 0
#    maximum_lag_on_syncnode: -1
    max_timelines_history: 0
    master_start_timeout: 45
#    master_stop_timeout: -1
    synchronous_mode: false
    synchronous_mode_strict: false
#    synchronous_node_count: 1
    check_timeline: true
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        max_connections: 1050
        superuser_reserved_connections: 50
        unix_socket_directories: "/var/run/postgresql"
        shared_buffers: "16GB"
        huge_pages: "off"
        temp_buffers: "8MB"
#        max_prepared_transactions: 0
        work_mem: "64MB"
        maintenance_work_mem: "128MB"
        autovacuum_work_mem: "256MB"
        temp_file_limit: 10485760
        max_files_per_process: 1000
        bgwriter_delay: "50ms"
        bgwriter_lru_maxpages: 10000
        bgwriter_lru_multiplier: 4
        effective_io_concurrency: 200
        max_worker_processes: 20
        backend_flush_after: "256kB"
        wal_level: "logical"
        synchronous_commit: "local"
        wal_compression: true
        wal_log_hints: true
        wal_buffers: "16MB"
        checkpoint_timeout: "5min"
        max_wal_size: "4GB"
        min_wal_size: "2GB"
        checkpoint_completion_target: 0.9
        archive_mode: "on"
        archive_command: "/bin/pgbackrest --config=/etc/pgbackrest-cbsprod2.conf --stanza=cbsprod2 archive-push %p"
        wal_keep_size: 1024
        track_commit_timestamp: true
        hot_standby_feedback: "on"
        random_page_cost: 2
        effective_cache_size: "42GB"
        default_statistics_target: 500
        log_destination: "csvlog"
        log_directory: "/pg12/mounts/pg_log/log"
        log_truncate_on_rotation: true
        log_rotation_age: "1d"
        log_min_duration_statement: "10s"
        log_checkpoints: true
        log_connections: true
        log_disconnections: true
        log_line_prefix: "#_# t[%m] p[%p] hp[%r] db[%d] u[%u] a[%a] tx[%x:%v] s[%c:%l] e[%e] i[%i] "
        log_lock_waits: true
#        log_parameter_max_length: 64
        log_temp_files: 0
        track_io_timing: true
        track_functions: "all"
        track_activity_query_size: 4096
        log_autovacuum_min_duration: 0
        autovacuum_max_workers: 4
        autovacuum_vacuum_cost_limit: 500
        idle_in_transaction_session_timeout: 0
#        datestyle: "iso, mdy"
        shared_preload_libraries: "pg_stat_statements, pg_stat_kcache, pg_qualstats, pg_squeeze, pg_wait_sampling, bgw_replstatus, timescaledb, pglogical, plpgsql_check, pgaudit, pgauditlogtofile, auto_explain"
        bgw_replstatus.bind: "0.0.0.0"
        bgw_replstatus.port: 5400
        timescaledb.telemetry_level: "off"
        timescaledb.max_background_workers: 16
        pgaudit.log_directory: "/pg12/mounts/pg_log/audit"
        pgaudit.log_rotation_age: 60
        pg_stat_statements.track: "all"
        pg_stat_statements.max: 5000
      recovery_conf:
        restore_command: "/bin/pgbackrest --config=/etc/pgbackrest-cbsprod2.conf --stanza=cbsprod2 archive-get %f %p"
```
                                                                                                                                                                                                                        84,1          Bot
