### ISSUE TITLE
patronictl edit-config not seeing DCS

### ISSUE THREAD

**Issue by git-noise** [zalando/patroni#2168]
**Describe the bug**
patronictl edit-config ( and patronictl show-config for that matter) are not working because DCS is missing - although DCS is here and patroni is otherwise actually working

**To Reproduce**
patronictl edit-config

**Expected behavior**
patronictl edit-config should enter edit configuration mode

**Screenshots**
Nothing to show

**Environment**
- Patroni version: patroni 2.1.1
- PostgreSQL version: postgres (PostgreSQL) 12.9
- DCS (and its version): consul 1.11.1

**Patroni configuration file**
```
name: "pgsql-i"
scope: pgsql-i
namespace: "patroni"

consul:
  url: http://127.0.0.1:8500
  register_service: true
  token: <my_token>

postgresql:
  connect_address: "pgsql-i.f.q.d.n:5432"
  bin_dir: /usr/lib/postgresql/12/bin
  data_dir: /opt/patroni/data/pg_data/12/main
  listen: "*:5432"
  use_unix_socket_repl: true
  authentication:
   superuser:
     username: postgres
     password: "my_password"
     sslmode: verify-full
     sslrootcert: /opt/patroni/chain.pem
     sslcert: /opt/patroni/cert.pem
     sslkey: /opt/patroni/key.pem
   replication:
     username: replicator
     password: "my_password"
     sslmode: verify-full
     sslrootcert: /opt/patroni/chain.pem
     sslcert: /opt/patroni/cert.pem
     sslkey: /opt/patroni/key.pem
   rewind:
     username: postgres
     password: "my_password"
     sslmode: verify-full
     sslrootcert: /opt/patroni/chain.pem
     sslcert: /opt/patroni/cert.pem
     sslkey: /opt/patroni/key.pem

restapi:
  connect_address: "my.f.q.d.n:8008"
  listen: "my.f.q.d.n:8008"
  verify_client: optional
  http_extra_headers:
    'X-Frame-Options': 'SAMEORIGIN'
    'X-XSS-Protection': '1; mode=block'
    'X-Content-Type-Options': 'nosniff'
  cafile: /opt/patroni/chain.pem
  certfile: /opt/patroni/cert.pem
  keyfile: /opt/patroni/key.pem
  https_extra_headers:
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'

bootstrap:
  dcs:
    postgresql:
      synchronous_mode: true
      use_pg_rewind: true
      parameters:
        synchronous_commit: "on"
        synchronous_standby_names: "*"
        ssl: "on"
        ssl_min_protocol_version: "TLSv1.3"
        ssl_ca_file: /opt/patroni/chain.pem
        ssl_cert_file: /opt/patroni/cert.pem
        ssl_key_file: /opt/patroni/key.pem
        password_encryption: scram-sha-256

  pg_hba:
    - local all all  md5
    - hostssl all all 127.0.0.1/32 md5
    - hostssl all all ::1/128 md5
    - hostssl all all ::1/128 md5
    - local replication replicator scram-sha-256
    - hostssl replication replicator pgsql-1.f.q.d.n scram-sha-256 clientcert=1
    - hostssl replication replicator pgsql-2.f.q.d.n scram-sha-256 clientcert=1
    - hostssl replication replicator pgsql-3.f.q.d.n scram-sha-256 clientcert=1
  initdb:
    - encoding: UTF8

watchdog:
  mode: off

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```
**patronictl show-config**
```
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: consul, kubernetes'
```

**Have you checked Patroni logs?**
```
INFO: no action. I am (pgsql-x), a secondary, and following a leader (pgsql-y)
```

**Have you checked PostgreSQL logs?**
Nothing

**Have you tried to use GitHub issue search?**
Nothing seems to be solving this issue. Other seemingly close issues are usually linked to a missing python-consul. It is however present and otherwise patroni is working.

**Additional context**
Nothing really, used to work and recently happened when trying to modify pg_hba.conf. I may be something really dumb I missed though. Many thanks for your insight
