### ISSUE TITLE
Replicas start failed with unrecognized configuration parameter "wal_keep_segments" in postgresql.conf on 14 PG

### ISSUE THREAD

**Issue by gsl23** [zalando/patroni#2171]
**Describe the bug**
We have succesfully working master but replicas can't start with this error  :
Jan 13 02:47:19 lk-mc-pgdb3 patroni[6925]: 2022-01-12 23:47:19.353 GMT [7243] LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/pg_data/pgsql/14/data/postgresql.conf" line 34
Jan 13 02:47:19 lk-mc-pgdb3 patroni[6925]: 2022-01-12 23:47:19.353 GMT [7243] FATAL:  configuration file "/pg_data/pgsql/14/data/postgresql.conf" contains errors

Postgresql 14.1 
Patroni 2.1.2 
```

# patronictl -c /etc/patroni/patroni.yml show-config
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
    archive_mode: 'on'
    archive_timeout: 1800s
    hot_standby: 'on'
    max_replication_slots: 5
    max_wal_senders: 10
    wal_keep_size: 128
    wal_level: hot_standby
    wal_log_hints: 'on'
  recovery_conf:
    restore_command: cp ../wal_archive/%f %p
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
ttl: 30
```
Config on master  (IPs changed to x.x.x.x and pg_hba section putged for security reasons )
```
scope: lk-mc-pgdb
#namespace: /service/
name: lk-mc-pgdb1

restapi:
  listen: x.x.x.x:8008
  connect_address: x.x.x.x:8008
  auth: 'username:test'


consul:
  host: 127.0.0.1:8500

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: hot_standby
        hot_standby: "on"
        wal_keep_size: 128
        max_wal_senders: 10
        max_replication_slots: 5
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
      recovery_conf:
        restore_command: cp ../wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  .........
  

postgresql:
  listen: x.x.x.x:5432
  connect_address: x.x.x.x:5432
  data_dir: /pg_data/pgsql/14/data
  bin_dir: /usr/pgsql-14/bin
#  config_dir:
  pg_rewind:
    username: postgres
    password: ***
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: ***
    superuser:
      username: postgres
      password: ***
  parameters:
    shared_preload_libraries: 'pg_stat_statements,pg_cron'
    unix_socket_directories: /run/postgresql
    max_connections: '2000'
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    shared_buffers: 4096MB
    checkpoint_completion_target: 0.9
    autovacuum_naptime: 20s
    autovacuum_max_workers: 10
    bgwriter_delay: 20ms
    bgwriter_lru_multiplier: 4.0
    bgwriter_lru_maxpages: 400
    work_mem: 128MB
    lo_compat_privileges: 'on'
    max_standby_archive_delay: 900s
    max_standby_streaming_delay: 1200s
    track_activity_query_size: 2048
```

postgresql.conf on master 
```
# Do not edit this file manually!
# It will be overwritten by Patroni!
include 'postgresql.base.conf'

archive_command = 'mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f'
archive_mode = 'on'
archive_timeout = '1800s'
autovacuum_max_workers = '10'
autovacuum_naptime = '20s'
bgwriter_delay = '20ms'
bgwriter_lru_maxpages = '400'
bgwriter_lru_multiplier = '4.0'
checkpoint_completion_target = '0.9'
cluster_name = 'lk-mc-pgdb'
hot_standby = 'on'
listen_addresses = 'x.x.x.x'
lo_compat_privileges = 'on'
max_connections = '2000'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '5'
max_standby_archive_delay = '900s'
max_standby_streaming_delay = '1200s'
max_wal_senders = '10'
max_worker_processes = '8'
pg_stat_statements.max = '10000'
pg_stat_statements.track = 'all'
port = '5432'
shared_buffers = '4096MB'
shared_preload_libraries = 'pg_stat_statements,pg_cron'
track_activity_query_size = '2048'
track_commit_timestamp = 'off'
unix_socket_directories = '/run/postgresql'
wal_keep_size = '128'
wal_level = 'replica'
wal_log_hints = 'on'
work_mem = '128MB'
hba_file = '/pg_data/pgsql/14/data/pg_hba.conf'
ident_file = '/pg_data/pgsql/14/data/pg_ident.conf'

# recovery.conf
recovery_target = ''
recovery_target_lsn = ''
recovery_target_name = ''
recovery_target_time = ''
recovery_target_timeline = 'latest'
recovery_target_xid = ''
restore_command = 'cp ../wal_archive/%f %p'
```

postgresql.conf on slaves 
```
# Do not edit this file manually!
# It will be overwritten by Patroni!
include 'postgresql.base.conf'

archive_command = 'mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f'
archive_mode = 'on'
archive_timeout = '1800s'
autovacuum_max_workers = '10'
autovacuum_naptime = '20s'
bgwriter_delay = '20ms'
bgwriter_lru_maxpages = '400'
bgwriter_lru_multiplier = '4.0'
checkpoint_completion_target = '0.9'
cluster_name = 'lk-mc-pgdb'
hot_standby = 'on'
listen_addresses = 'x.x.x.x'
lo_compat_privileges = 'on'
max_connections = '2000'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_standby_archive_delay = '900s'
max_standby_streaming_delay = '1200s'
max_wal_senders = '10'
max_worker_processes = '8'
pg_stat_statements.max = '10000'
pg_stat_statements.track = 'all'
port = '5432'
shared_buffers = '4096MB'
shared_preload_libraries = 'pg_stat_statements,pg_cron'
track_activity_query_size = '2048'
track_commit_timestamp = 'off'
unix_socket_directories = '/run/postgresql'
wal_keep_segments = '8'
wal_keep_size = '128'
wal_level = 'replica'
wal_log_hints = 'on'
work_mem = '128MB'
hba_file = '/pg_data/pgsql/14/data/pg_hba.conf'
ident_file = '/pg_data/pgsql/14/data/pg_ident.conf'

# recovery.conf
primary_conninfo = 'user=replicator password=*** host=x.x.x.x port=5432 sslmode=prefer application_name=lk-mc-pgdb3'
primary_slot_name = 'lk_mc_pgdb3'
recovery_target_timeline = 'latest'
restore_command = 'cp ../wal_archive/%f %p'

```

wal_keep_segments = '8' automatically added in postgresql.conf on slaves and deletion this parameter doesn't work , patroni automatically add it again, and we got permanently on slaves : 
```
Jan 13 02:46:58 lk-mc-pgdb3 patroni[6925]: 2022-01-13 02:46:58,832 INFO: Lock owner: lk-mc-pgdb1; I am lk-mc-pgdb3
Jan 13 02:46:58 lk-mc-pgdb3 patroni[6925]: 2022-01-13 02:46:58,868 INFO: Local timeline=None lsn=None
Jan 13 02:46:58 lk-mc-pgdb3 patroni[6925]: 2022-01-13 02:46:58,869 INFO: Lock owner: lk-mc-pgdb1; I am lk-mc-pgdb3
Jan 13 02:46:58 lk-mc-pgdb3 patroni[6925]: 2022-01-13 02:46:58,876 INFO: starting as a secondary
Jan 13 02:46:58 lk-mc-pgdb3 patroni[6925]: 2022-01-13 02:46:58,911 INFO: postmaster pid=7051
Jan 13 02:46:58 lk-mc-pgdb3 patroni[6925]: 2022-01-12 23:46:58.923 GMT [7051] LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/pg_data/pgsql/14/data/postgresql.conf" line 34
Jan 13 02:46:58 lk-mc-pgdb3 patroni[6925]: 2022-01-12 23:46:58.923 GMT [7051] FATAL:  configuration file "/pg_data/pgsql/14/data/postgresql.conf" contains errors
Jan 13 02:46:58 lk-mc-pgdb3 patroni[6925]: 10.144.129.7:5432 - no response
Jan 13 02:46:59 lk-mc-pgdb3 patroni[6925]: 2022-01-13 02:46:59,933 ERROR: postmaster is not running
Jan 13 02:46:59 lk-mc-pgdb3 patroni[6925]: 2022-01-13 02:46:59,952 WARNING: Postgresql is not running.
```
