### ISSUE TITLE
Too large DB: cannot create replica

### ISSUE THREAD

**Issue by haf** [zalando/patroni#2174]
**Describe the bug**
Initially like https://github.com/zalando/patroni/issues/689 which will happen every time you run out of disk for pg.

Then trying `patronictl reinit ...` which makes the replica in question go into this state

```
| Member                     | Host                                      | Role    | State            | TL | Lag in MB |
| analytics-instance1-s7qn-0 | analytics-instance1-s7qn-0.analytics-pods | Replica | creating replica |    |   unknown |
```

This is the case for a couple of hours while the 800 GiB DB is sent from the primary to the replica.

By the time the creation is complete and patroni wants to move to following the WAL:

```
2022-01-16 12:27:33.491 UTC [335116] LOG:  started streaming WAL from primary at D65/B0000000 on timeline 3
2022-01-16 12:27:33.491 UTC [335116] FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 0000000300000D65000000B0 has already been removed
```

**To Reproduce**
Insert large amounts of data, around 800 GiB into the primary.

Have it run out of disk.

Create a replica from it while continuously writing to the master.

**Expected behavior**

1. Running out of disk on the nodes should not disrupt the replication, since I should then be able to add more storage to the computers
2. If 1 is not solved, `reinit` should be able to recreate the replica.

**Screenshots**
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/193115/149663517-ce2f3f59-ae2c-4f04-ba8f-29173a561d68.png">
<img width="851" alt="image" src="https://user-images.githubusercontent.com/193115/149663522-b04e8cc3-3e55-4661-838b-198b51555f71.png">
<img width="971" alt="image" src="https://user-images.githubusercontent.com/193115/149663523-38f15d0a-b8fa-4f5d-880e-0485b1e577a5.png">

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 13
- DCS (and its version): What's DCS?

**Patroni configuration file**
```
# Where is it? This?
bash-4.4$ cat /etc/patroni/~postgres-operator_instance.yaml
# Generated by postgres-operator. DO NOT EDIT.
# Your changes will not be saved.
kubernetes: {}
postgresql:
  basebackup:
  - waldir=/pgdata/pg13_wal
  create_replica_methods:
  - pgbackrest
  - basebackup
  pgbackrest:
    command: '''bash'' ''-ceu'' ''--'' ''install --directory --mode=0700 "${PGDATA?}"
      && exec "$@"'' ''-'' ''pgbackrest'' ''restore'' ''--delta'' ''--stanza=db''
      ''--repo=1'' ''--link-map=pg_wal=/pgdata/pg13_wal'''
    keep_data: true
    no_master: true
    no_params: true
  pgpass: /tmp/.pgpass
  use_unix_socket: true
restapi: {}
tags: {}
```

**patronictl show-config**
```
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=db archive-push "%p"
    archive_mode: 'on'
    dynamic_shared_memory_type: sysv
    effective_cache_size: 37.5GB
    jit: 'off'
    max_parallel_workers: 14
    max_wal_senders: '10'
    max_worker_processes: 56
    password_encryption: scram-sha-256
    restore_command: pgbackrest --stanza=db archive-get %f "%p"
    shared_buffers: 12.5GB
    shared_preload_libraries: pg_stat_statements,pgnodemx
    ssl: 'on'
    ssl_ca_file: /pgconf/tls/ca.crt
    ssl_cert_file: /pgconf/tls/tls.crt
    ssl_key_file: /pgconf/tls/tls.key
    statement_timeout: 10m
    unix_socket_directories: /tmp/postgres
    wal_buffers: 64MB
    wal_level: logical
    wal_sender_timeout: 10m
  pg_hba:
  - local all "postgres" peer
  - hostssl replication "_crunchyrepl" all cert
  - hostssl "postgres" "_crunchyrepl" all cert
  - host all "_crunchyrepl" all reject
  - host all "ccp_monitoring" "127.0.0.0/8" md5
  - host all "ccp_monitoring" "::1/128" md5
  - hostssl all "_crunchypgbouncer" all md5
  - hostssl all all all md5
  use_pg_rewind: true
  use_slots: false
ttl: 30
```

**Have you checked Patroni logs?**
No

**Have you checked PostgreSQL logs?**
See logs above

**Have you tried to use GitHub issue search?**
See link to issue

**Additional context**
Using crunchy postgres operator.
