### ISSUE TITLE
Data loss if start Patroni in specific order

### ISSUE THREAD

**Issue by rrcrrcrrc** [zalando/patroni#2175]
**Describe the bug**
Data loss if Patroni is started in a specific order.

**To Reproduce**
I configured 3 etcd servers, in 2 of those servers (server 1 and server 2) I installed Patroni. If I forcefully shut down server 1 leader, Patroni promotes the leader to server 2. If I now forcefully shutdown server 2, and bring server 1 up again, server 1 becomes leader by writing to the database from point that was turned off causing data loss.

**Expected behavior**
Patroni should check which was the last leader, and if the leader is not raised first, and then its replica, it should not write anything to the database even if there is a service stop.

**Screenshots**
No.

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 12.9
- DCS (and its version): etcd 3.3.11

**Patroni configuration file**
```
scope: postgres
namespace: /pg_cluster/
name: node1

restapi:
  listen: 10.150.135.250:8008
  connect_address: 10.150.135.250:8008

etcd:
  hosts: 10.150.135.250:2379,10.150.135.251:2379,10.150.135.252:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        logging_collector: 'on'
        max_wal_senders: 5
        max_replication_slots: 5
        wal_log_hints: "on"
        check_timeline: true

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator 10.150.135.250/32 md5  
  - host replication replicator 10.150.135.251/32 md5 
  - host replication replicator 10.150.135.252/32 md5
  - host all all 0.0.0.0/0 md5

  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 10.150.135.250:5432
  connect_address: 10.150.135.250:5432
  data_dir: /data/patroni
  bin_dir: /usr/pgsql-12/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: replicator91
    superuser:
      username: postgres
      password: postgres91
    rewind:
      username: rewind
      password: rewind91
  parameters:
    unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    hot_standby: 'on'
    logging_collector: 'on'
    max_replication_slots: 5
    max_wal_senders: 5
    wal_level: replica
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
No.

**Have you checked PostgreSQL logs?**
No.

**Have you tried to use GitHub issue search?**
Yes.

**Additional context**
I just want 2 PostgreSQL servers in asynchronous mode.
If I disable Patroni service I can decide which server must be started first, but I want Patroni do it.
Maybe adding more etcd nodes solves this? 

Thanks :)
