### ISSUE TITLE
unable to bootstrap cluster from existing pvc

### ISSUE THREAD

**Issue by yelhouti** [zalando/patroni#2178]
**Describe the bug**
I am trying to retrieve a cluster from a pvc (bootstart); I remove the `initialize` annotation from the svc/ep as described in the doc.

The pod starts but not postgres.

when I run:
```
patronictl list
```
I get one member (as expected with) bit with state: `start failed`

when I try to start patroni manualy:
>  ERROR: Couldn't start a service on 'None:8008', please check your `restapi.listen` configuration
...
OSError: [Errno 98] Address already in use

When I try to start postgres:
```
service postgresql start
```
> No PostgreSQL clusters exist; see "man pg_createcluster"

**To Reproduce**
- start a cluster
- copy the pvc
- start a new cluster
- override the pvc
- remove the  `initialize` annotation from the svc/ep
- restart
- exec
- patronictl list
- patroni postgres.yaml

**Expected behavior**
show bootstrap correctly

**Environment**
- Patroni version: spilo-13:2.0-p7 (I tried also restoring with spilo-13:2.1-p1)
- PostgreSQL version: psql (PostgreSQL) 13.3 (Ubuntu 13.3-1.pgdg18.04+1)
- DCS (and its version): etcd from k8s cluster

**Patroni configuration file**
```
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_mode: 'on'
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.05
        checkpoint_completion_target: 0.9
        hot_standby: 'on'
        log_autovacuum_min_duration: 0
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_lock_waits: 'on'
        log_min_duration_statement: 500
        log_statement: ddl
        log_temp_files: 0
        max_connections: 100
        max_replication_slots: 10
        max_wal_senders: 10
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        track_functions: all
        wal_level: hot_standby
        wal_log_hints: 'on'
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - auth-host: md5
  - auth-local: trust
  post_init: /scripts/post_init.sh "zalandos"
  users:
    zalandos:
      options:
      - CREATEDB
      - NOLOGIN
      password: ''
kubernetes:
  bypass_api_service: true
  labels:
    application: spilo
  pod_ip: 10.233.66.16
  ports:
  - name: postgresql
    port: 5432
  role_label: spilo-role
  scope_label: cluster-name
  use_endpoints: true
namespace: app
postgresql:
  authentication:
    replication:
      password: REDACTED
      username: standby
    superuser:
      password: REDACTED
      username: postgres
  basebackup_fast_xlog:
    command: /scripts/basebackup.sh
    retries: 2
  bin_dir: /usr/lib/postgresql/13/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos true
  connect_address: 10.233.66.16:5432
  create_replica_method:
  - wal_e
  - basebackup_fast_xlog
  data_dir: /home/postgres/pgdata/pgroot/data
  listen: '*:5432'
  name: app-postgres-0
  parameters:
    archive_command: envdir "/run/etc/wal-e.d/env" wal-g wal-push "%p"
    bg_mon.history_buckets: 120
    bg_mon.listen_address: '::'
    extwlist.custom_path: /scripts
    extwlist.extensions: btree_gin,btree_gist,citext,hstore,intarray,ltree,pgcrypto,pgq,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,hypopg,timescaledb,pg_partman
    log_destination: csvlog
    log_directory: ../pg_log
    log_file_mode: '0644'
    log_filename: postgresql-%u.log
    log_rotation_age: 1d
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    pg_stat_statements.track_utility: 'off'
    shared_buffers: 100MB
    shared_preload_libraries: bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,timescaledb,pg_cron,pg_stat_kcache
    ssl: 'on'
    ssl_cert_file: /run/certs/server.crt
    ssl_key_file: /run/certs/server.key
  pg_hba:
  - local   all             all                                   trust
  - hostssl all             +zalandos    127.0.0.1/32       pam
  - host    all             all                127.0.0.1/32       md5
  - hostssl all             +zalandos    ::1/128            pam
  - host    all             all                ::1/128            md5
  - hostssl replication     standby all                md5
  - hostnossl all           all                all                reject
  - hostssl all             +zalandos    all                pam
  - hostssl all             all                all                md5
  pgpass: /run/postgresql/pgpass
  recovery_conf:
    restore_command: envdir "/run/etc/wal-e.d/env" /scripts/restore_command.sh "%f" "%p"
  use_unix_socket: true
  wal_e:
    command: envdir /run/etc/wal-e.d/env bash /scripts/wale_restore.sh
    no_master: 1
    retries: 2
    threshold_backup_size_percentage: 30
    threshold_megabytes: 102400
restapi:
  connect_address: 10.233.66.16:8008
  listen: :8008
scope: app-postgres

```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 33554432
postgresql:
  parameters:
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_vacuum_scale_factor: 0.05
    checkpoint_completion_target: 0.9
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_statement: ddl
    log_temp_files: 0
    max_connections: 100
    max_replication_slots: 10
    max_wal_senders: 10
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    track_functions: all
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
<details>
2022-01-19 16:18:46,177 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2022-01-19 16:18:48,181 - bootstrapping - INFO - Could not connect to 169.254.169.254, assuming local Docker setup
2022-01-19 16:18:48,182 - bootstrapping - INFO - No meta-data available for this provider
2022-01-19 16:18:48,182 - bootstrapping - INFO - Looks like your running local
2022-01-19 16:18:48,199 - bootstrapping - INFO - Configuring certificate
2022-01-19 16:18:48,199 - bootstrapping - INFO - Generating ssl certificate
2022-01-19 16:18:48,257 - bootstrapping - INFO - Configuring pgbouncer
2022-01-19 16:18:48,257 - bootstrapping - INFO - No PGBOUNCER_CONFIGURATION was specified, skipping
2022-01-19 16:18:48,257 - bootstrapping - INFO - Configuring bootstrap
2022-01-19 16:18:48,257 - bootstrapping - INFO - Configuring patroni
2022-01-19 16:18:48,263 - bootstrapping - INFO - Writing to file /run/postgres.yml
2022-01-19 16:18:48,263 - bootstrapping - INFO - Configuring crontab
2022-01-19 16:18:48,263 - bootstrapping - INFO - Skipping creation of renice cron job due to lack of SYS_NICE capability
2022-01-19 16:18:48,331 - bootstrapping - INFO - Configuring wal-e
2022-01-19 16:18:48,331 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_S3_PREFIX
2022-01-19 16:18:48,332 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_S3_PREFIX
2022-01-19 16:18:48,332 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_ACCESS_KEY_ID
2022-01-19 16:18:48,332 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY
2022-01-19 16:18:48,332 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_S3_ENDPOINT
2022-01-19 16:18:48,332 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_ENDPOINT
2022-01-19 16:18:48,332 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_DISABLE_S3_SSE
2022-01-19 16:18:48,332 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/AWS_S3_FORCE_PATH_STYLE
2022-01-19 16:18:48,332 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_DOWNLOAD_CONCURRENCY
2022-01-19 16:18:48,332 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALG_UPLOAD_CONCURRENCY
2022-01-19 16:18:48,332 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/USE_WALG_BACKUP
2022-01-19 16:18:48,332 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/USE_WALG_RESTORE
2022-01-19 16:18:48,333 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/WALE_LOG_DESTINATION
2022-01-19 16:18:48,333 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/PGPORT
2022-01-19 16:18:48,333 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/BACKUP_NUM_TO_RETAIN
2022-01-19 16:18:48,333 - bootstrapping - INFO - Writing to file /run/etc/wal-e.d/env/TMPDIR
2022-01-19 16:18:48,333 - bootstrapping - INFO - Configuring pam-oauth2
2022-01-19 16:18:48,333 - bootstrapping - INFO - Writing to file /etc/pam.d/postgresql
2022-01-19 16:18:48,333 - bootstrapping - INFO - Configuring log
2022-01-19 16:18:48,333 - bootstrapping - INFO - Writing to file /run/etc/log.d/env/LOG_TMPDIR
2022-01-19 16:18:48,333 - bootstrapping - INFO - Writing to file /run/etc/log.d/env/LOG_AWS_HOST
2022-01-19 16:18:48,333 - bootstrapping - INFO - Writing to file /run/etc/log.d/env/LOG_S3_KEY
2022-01-19 16:18:48,333 - bootstrapping - INFO - Writing to file /run/etc/log.d/env/LOG_S3_BUCKET
2022-01-19 16:18:48,333 - bootstrapping - INFO - Writing to file /run/etc/log.d/env/PGLOG
2022-01-19 16:18:48,333 - bootstrapping - INFO - Configuring standby-cluster
2022-01-19 16:18:48,334 - bootstrapping - INFO - Configuring pgqd
2022-01-19 16:18:49,532 WARNING: Kubernetes RBAC doesn't allow GET access to the 'kubernetes' endpoint in the 'default' namespace. Disabling 'bypass_api_service'.
2022-01-19 16:18:49,712 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-01-19 16:18:49,717 WARNING: Postgresql is not running.
2022-01-19 16:18:49,717 INFO: Lock owner: None; I am metaphysiks-postgres-0
2022-01-19 16:18:49,718 INFO: pg_controldata:
  pg_control version number: 1300
  Catalog version number: 202007201
  Database system identifier: 7018272250990874706
  Database cluster state: shut down
  pg_control last modified: Mon Jan 10 03:48:41 2022
  Latest checkpoint location: 1/74000028
  Latest checkpoint's REDO location: 1/74000028
  Latest checkpoint's REDO WAL file: 000000050000000100000074
  Latest checkpoint's TimeLineID: 5
  Latest checkpoint's PrevTimeLineID: 5
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:4325
  Latest checkpoint's NextOID: 49608
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 479
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 0
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Mon Jan 10 03:48:37 2022
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 0/0
  Min recovery ending loc's timeline: 0
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: replica
  wal_log_hints setting: on
  max_connections setting: 100
  max_worker_processes setting: 8
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float8 argument passing: by value
  Data page checksum version: 0
  Mock authentication nonce: 4d7d9dc52f8516beb2ffd4c575a8842e75749ac2114f86f3d89837892842254c

2022-01-19 16:18:49,718 INFO: Lock owner: None; I am metaphysiks-postgres-0
2022-01-19 16:18:49,724 INFO: Lock owner: None; I am metaphysiks-postgres-0
2022-01-19 16:18:49,988 INFO: starting as a secondary
2022-01-19 16:18:50 UTC [72]: [1-1] 61e839ea.48 0     FATAL:  bogus data in lock file "postmaster.pid": "lse,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Networks":null,"Service":null,"Ports":null,"Sa"
2022-01-19 16:18:50,146 INFO: postmaster pid=72
/var/run/postgresql:5432 - no response
2022-01-19 16:18:50,190 WARNING: Postgresql is not running.
2022-01-19 16:18:50,190 INFO: Lock owner: None; I am metaphysiks-postgres-0
2022-01-19 16:18:50,192 INFO: pg_controldata:

</details>

**Have you checked PostgreSQL logs?**
folder /home/postgres/pgdata/pgroot/pg_log/ contains only files older that when i tried to recreate.

**Have you tried to use GitHub issue search?**
yes
