### ISSUE TITLE
Failover on Patroni + Raft configuration

### ISSUE THREAD

**Issue by aomelchuk-incountry** [zalando/patroni#2188]
**Describe the bug**
Patroni wasn't able to perform a correct failover so we faced with Split-Brain situation. There was no failover on Master but Replica was promoted to Master. Looks like Patroni on the initial master node stopped to communicate with other nodes but the process was still running.

**To Reproduce**
Didn't find a way to reproduce the issue yet.

**Expected behavior**
Patroni performs a correct failover between nodes.

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 13.4
- DCS (and its version): Raft (pysyncobj==0.3.10)

We have 2 Patroni Database nodes and 1 Raft controller node.
All of them run in Docker containers.

**Patroni configuration file**
```
scope: cn-el-01
name: 10.1.1.3

raft:
  data_dir: /var/data/raft
  self_addr: 10.1.1.3:3025
  partner_addrs:
    - 10.1.1.4:3025
    - 10.1.1.5:3025

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.1.1.3:8008
  authentication:
    username: api_user
    password: '***'
  certfile: /etc/ssl/postgres/patroni_restapi.crt
  keyfile: /etc/ssl/postgres/patroni_restapi.key
  verify_client: none

bootstrap:
  dcs:
    ttl: 62
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: false
      remove_data_directory_on_diverged_timelines: true
      parameters:
        archive_mode: "always"
        archive_timeout: 1800s
        wal_level: hot_standby
        max_wal_senders: 5
        wal_keep_size: 3200
        max_replication_slots: 5
        hot_standby: on
        wal_log_hints: on
        # optimization
        max_connections: 200
        superuser_reserved_connections: 7
        max_prepared_transactions: 10
        shared_buffers: 2048MB
        effective_cache_size: 6384MB
        maintenance_work_mem: 896MB
        checkpoint_completion_target: 0.7
        wal_buffers: 16MB
        default_statistics_target: 100
        random_page_cost: 1.1
        effective_io_concurrency: 200
        work_mem: 9175kB
        min_wal_size: 1GB
        max_wal_size: 2GB
        max_worker_processes: 8
        max_parallel_workers_per_gather: 4
        max_parallel_workers: 8

  initdb:
  - encoding: UTF8
  - data-checksums
  - allow-group-access

  post_init: /home/postgres/.config/patroni/cluster_init.sh

postgresql:
  listen: 10.1.1.3:5432
  bin_dir: /usr/lib/postgresql/13/bin/
  connect_address: 10.1.1.3:5432
  data_dir: /var/data/base
  pgpass: /home/postgres/.patroni
  authentication:
    replication:
      username: replication
      password: '***'
    superuser:
      username: postgres
      password: '***'
    rewind:
      username: rewinduser
      password: '***'
  parameters:
    archive_mode: 'always'
    archive_command: 'pg_probackup-13 archive-push -B /var/backup/ --instance cn-el-01 --compress-algorithm=zlib --compress-level=9 --wal-file-path=%p --wal-file-name=%f --remote-host=10.1.2.3 --remote-user=backupuser'
    ssl: "on"
    ssl_cert_file: '/etc/ssl/postgres/server.crt'
    ssl_key_file: '/etc/ssl/postgres/server.key'
    ssl_ca_file: '/etc/ssl/postgres/root.crt'
    shared_preload_libraries: 'pg_stat_statements,pgaudit,passwordpolicy,pg_cron'
    pgaudit.log: 'ddl,role,misc'
    pgaudit.role: 'auditor'
    pgaudit.log_catalog: 'off'
    pgaudit.log_parameter: 'off'
    logging_collector: 'off'
    log_destination: 'stderr'
    log_connections: 'on'
    log_disconnections: 'on'
    log_min_messages: 'NOTICE'
    log_min_error_statement: 'ERROR'
    log_min_duration_statement: '-1'
    debug_print_parse: 'off'
    debug_print_rewritten: 'off'
    debug_print_plan: 'off'
    debug_pretty_print: 'on'
    log_checkpoints: 'on'
    log_duration: 'on'
    log_error_verbosity: 'terse'
    log_hostname: 'off'
    log_line_prefix: '[postgres] %m %h %s %u %d %x %e %c %p %i: '
    log_lock_waits: 'off'
    log_statement: 'ddl'
    log_temp_files: '-1'
    log_timezone: 'UTC'
    log_parser_stats: 'off'
    log_planner_stats: 'off'
    log_executor_stats: 'off'
    log_statement_stats: 'off'
    p_policy.min_password_len: 24
    p_policy.min_special_chars: 2
    p_policy.min_numbers: 2
    p_policy.min_uppercase_letter: 2
    p_policy.min_lowercase_letter: 2
    cron.database_name: 'postgres'
    cron.use_background_workers: 'on'

  pg_hba:

...

log:
  level: INFO
  format: '[patroni] %(asctime)s %(levelname)s: %(message)s'
watchdog:
  mode: off
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false  
```

**Patroni Raft controller configuration file**
```
scope: cn-el-01
name: 10.1.1.5
raft:
  data_dir: /var/data/raft
  self_addr: 10.1.1.5:3025
  partner_addrs:
    - 10.1.1.3:3025
    - 10.1.1.4:3025


log:
  level: DEBUG
  format: '[patroni] %(asctime)s %(levelname)s: %(message)s'
  traceback_level: DEBUG
  loggers:
    patroni.postmaster: WARNING
    urllib3: DEBUG
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_mode: always
    archive_timeout: 1800s
    checkpoint_completion_target: 0.7
    default_statistics_target: 100
    effective_cache_size: 6384MB
    effective_io_concurrency: 200
    hot_standby: true
    maintenance_work_mem: 896MB
    max_connections: 200
    max_parallel_workers: 8
    max_parallel_workers_per_gather: 4
    max_prepared_transactions: 10
    max_replication_slots: 5
    max_wal_senders: 5
    max_wal_size: 2GB
    max_worker_processes: 8
    min_wal_size: 1GB
    random_page_cost: 1.1
    shared_buffers: 2048MB
    superuser_reserved_connections: 7
    wal_buffers: 16MB
    wal_keep_size: 3200
    wal_level: hot_standby
    wal_log_hints: true
    work_mem: 9175kB
  remove_data_directory_on_diverged_timelines: true
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
synchronous_mode: true
ttl: 62
```

**Have you checked Patroni logs?**
From the initial master (10.1.1.3) node:
```
Jan 25, 2022 @ 13:39:15.763	Failed to store full dump 
Jan 25, 2022 @ 13:39:05.930	no action. I am (10.1.1.3) the leader with the lock
Jan 25, 2022 @ 13:38:55.930	no action. I am (10.1.1.3) the leader with the lock 
Jan 25, 2022 @ 13:38:45.930	no action. I am (10.1.1.3) the leader with the lock 
Jan 25, 2022 @ 13:38:35.930	no action. I am (10.1.1.3) the leader with the lock 
Jan 25, 2022 @ 13:38:25.930	no action. I am (10.1.1.3) the leader with the lock 
Jan 25, 2022 @ 13:38:15.930	no action. I am (10.1.1.3) the leader with the lock 
Jan 25, 2022 @ 13:38:05.930	no action. I am (10.1.1.3) the leader with the lock 
Jan 25, 2022 @ 13:37:55.930	no action. I am (10.1.1.3) the leader with the lock 
Jan 25, 2022 @ 13:37:45.929	no action. I am (10.1.1.3) the leader with the lock
```

From the initial replica node (10.1.1.4) node which was promoted to master:
```
Jan 25, 2022 @ 13:40:11.926	no action. I am (10.1.1.4) the leader with the lock 
Jan 25, 2022 @ 13:40:11.610	no action. I am (10.1.1.4) the leader with the lock 
Jan 25, 2022 @ 13:40:10.386	updated leader lock during promote 
Jan 25, 2022 @ 13:40:10.178	cleared rewind state after becoming the leader 
Jan 25, 2022 @ 13:40:10.173	promoted self to leader by acquiring session lock 
Jan 25, 2022 @ 13:40:10.173	Lock owner: 10.1.1.4; I am 10.1.1.4 
Jan 25, 2022 @ 13:40:09.858	Request failed to 10.1.1.3: GET https://10.1.1.3:8008/patroni (HTTPSConnectionPool(host='10.1.1.3', port=8008): Max retries exceeded with url: /patroni (Caused by ReadTimeoutError("HTTPSConnectionPool(host='10.1.1.3', port=8008): Read timed out. (read timeout=2)"))) 
Jan 25, 2022 @ 13:40:06.040	no action. I am a secondary (10.1.1.4) and following a leader (10.1.1.3) 
Jan 25, 2022 @ 13:39:56.040	no action. I am a secondary (10.1.1.4) and following a leader (10.1.1.3)
```

**Have you checked PostgreSQL logs?**
For initial master (10.1.1.3) node from the PostgreSQL side there were no any system messages and was totally nothing happened.
For replica (10.1.1.4) there were standard messages when replica promoting to master.

**Additional context**
Is there a way to find out what was the cause of such behavior?
