### ISSUE TITLE
When patroni service stop, replication slot couldn't killed in postgres.

### ISSUE THREAD

**Issue by HalacliSeda** [zalando/patroni#2190]
**Describe the bug**
I'm stopping the patrony service, but the member is still on the list. The member's state is stopped. The slot in PostgreSQL also appears in pg_replication_slots. That's why wal files are piling up.

**To Reproduce**
I stopped the service with 'systemctl stop patroni' command.
The member seen in 'patronictl list' command:
+ Cluster: () ---------+---------+----+-----------+---------------------+
| Member                  | Host        | Role    | State   | TL | Lag in MB | Tags                |
+-------------------------+-------------+---------+---------+----+-----------+---------------------+
| pg1               | <ip> | Leader  | running | 12 |           |                     |
+-------------------------+-------------+---------+---------+----+-----------+---------------------+
| pg2               |<ip> | Replica | running | 12 |         0 |                     |
+-------------------------+-------------+---------+---------+----+-----------+---------------------+
| pg3              | <ip> | Replica | running | 12 |         0 |                     |
+-------------------------+-------------+---------+---------+----+-----------+---------------------+
|pg4 | <ip>  | Replica | **stopped** |    |   unknown | nofailover: true    |
|                         |             |         |         |    |           | noloadbalance: true |
|                         |             |         |         |    |           | nosync: true        |
+-------------------------+-------------+---------+---------+----+-----------+---------------------+

**Expected behavior**
I  expect the PostgreSQL replication slot to be deleted and no wal file backlog.

**Screenshots**

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 12.8
- DCS (and its version): Consul 1.8.4

**Patroni configuration file**
```
namespace: patroni
scope: scope1
name: pg4

log:
  dir: /var/log/patroni

restapi:
  listen: 0.0.0.0:8008
  connect_address: <ip>:8008

consul:
  host: 127.0.0.1:8500
  register_service: true
  checks: []
  token: "<token>"

bootstrap:
  dcs:
    ttl: 670
    loop_wait: 10
    retry_timeout: 300
    maximum_lag_on_failover: 5000000000
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        ...
     ...
    ... 

      pg_hba:
      - local all postgres trust
      - local all pgspotter ident map=monitoring
      - local all all peer
     ...
     ...
    ...
  initdb:
  - encoding: UTF8
  - data-checksums

  users:
    postgres:
      options:
      - superuser
      - createdb
      - createrole

postgresql:
  use_unix_socket: true
  listen: 0.0.0.0:5432
  connect_address: <ip>:5432
  data_dir: /pgsql/12/data
  config_dir: /pgsql/12/data
  pgpass: /var/lib/pgsql/.pgpass
  bin_dir: /usr/pgsql-12/bin
tags:
  nofailover: true
  noloadbalance: true
  clonefrom: false
  nosync: true


```

**patronictl show-config**
```

loop_wait: 10
maximum_lag_on_failover: 5000000000
postgresql:
  parameters:
    ...
     ...
    ...
  pg_hba:
    ...
     ...
    ...
  pg_ident:
  - monitoring zabbix pgspotter
  use_pg_rewind: true
  use_slots: true
retry_timeout: 300
ttl: 670

```

**Have you checked Patroni logs?**
There isn't any error both of leader and stopped members.

**Have you checked PostgreSQL logs?**
There isn't any error in postgres.

**Have you tried to use GitHub issue search?**
Yes, but I couldn't see same issue.

**Additional context**
I think stopped member gone after for a long time  but in this time wal files pile up in leader. Can we change this time? For example when I stop the patroni, I want to kill replication slot now. 
I would be glad if you help.
