### ISSUE TITLE
Patroni node different timeline at unexpected shutdown

### ISSUE THREAD

**Issue by rrcrrcrrc** [zalando/patroni#2196]
**Describe the bug**
In a synchronous Patroni cluster with 3 nodes, all with same TL, if I force to shutdown the "Leader" node, then "Sync Standby" node becomes the "Leader" and the "Replica" node becomes the "Sync Standby". The new "Leader" and "Sync Standby" nodes increase the TL, but when I start again the old "Leader", this node dont increase the TL. Only when I execute "systemctl restart patroni" on old "Leader" node increase the TL. Patroni service is enabled.

**To Reproduce**
Stop "Leader" node
Wait Patroni change "Leader" and "Sync Standby" nodes with the correct TL
Start old "Leader" node

**Expected behavior**
Patroni checks TL from the old "Leader" and synchronize DB at start without restart the Patroni service.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/97697681/151790178-8fbdb631-dc26-43ed-8fc6-3cdc14e58587.png)

![imagen](https://user-images.githubusercontent.com/97697681/151790939-3bdae715-09c8-45d7-ae67-87891b8ef8b0.png)

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 12.9
- DCS (and its version): etcd 3.3.11

**Patroni configuration file**
```
scope: patroni
namespace: /patroni_cluster/
name: dblts1
restapi:
  connect_address: 10.150.135.105:8008
  listen: 10.150.135.105:8008
log:
  level: INFO
  dir: /storage/bss_resources/logs/patroni
  file_num: 5
  file_size: 100000000
etcd:
  host: 10.150.135.105:2379
postgresql:
  listen: 10.150.135.105:5432
  connect_address: 10.150.135.105:5432
  data_dir: /storage/databases/postgres/data
  bin_dir: /usr/pgsql-12/bin
  pgpass: /storage/databases/postgres/pgpass0
  authentication:
    superuser:
      username: XXX
      password: XXX
    replication:
      username: XXX
      password: XXX
    rewind:
      username: XXX
      password: XXX
  parameters:
    unix_socket_directories: '.'
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
bootstrap:
  dcs:
    loop_wait: 10
    ttl: 30
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    max_timelines_history: 100
    master_start_timeout: 0
    master_stop_timeout: 0
    synchronous_mode: true
    synchronous_mode_strict: true
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        timezone: "Europe/Madrid"
        log_timezone: "Europe/Madrid"
        log_directory: "/storage/databases/postgres/log"
        log_filename: "postgresql-%a.log"
        log_truncate_on_rotation: "on"
        log_rotation_age: 1d
        log_rotation_size: 0
        logging_collector: "on"
        max_connections: 100
        max_wal_senders: 10
        max_prepared_transactions: 0
        max_locks_per_transaction: 64
        max_replication_slots: 5
        max_worker_processes: 8
        wal_level: replica
        wal_keep_size: 2GB 
        wal_log_hints: "on"
        hot_standby: "on"
  initdb:
  - encoding: UTF8
  - data-checksums
  pg_hba:
  - host all all 0.0.0.0/0 md5
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator 10.150.135.105/32 md5  
  - host replication replicator 10.150.135.106/32 md5 
  - host replication replicator 10.150.135.107/32 md5
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb
```

**patronictl show-config**
```
loop_wait: 10
master_start_timeout: 0
master_stop_timeout: 0
max_timelines_history: 100
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    hot_standby: 'on'
    log_directory: /storage/databases/postgres/log
    log_filename: postgresql-%a.log
    log_rotation_age: 1d
    log_rotation_size: 0
    log_timezone: Europe/Madrid
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    max_connections: 100
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 5
    max_wal_senders: 10
    max_worker_processes: 8
    timezone: Europe/Madrid
    wal_keep_size: 2GB
    wal_level: replica
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: true
ttl: 30
```

**Have you checked Patroni logs?**
```
2022-01-31 11:56:29,958 INFO: no action. I am (dblts1) the leader with the lock
2022-01-31 11:56:39,964 INFO: no action. I am (dblts1) the leader with the lock
2022-01-31 11:56:49,969 INFO: no action. I am (dblts1) the leader with the lock
2022-01-31 11:56:59,960 INFO: no action. I am (dblts1) the leader with the lock
2022-01-31 11:57:09,958 INFO: no action. I am (dblts1) the leader with the lock
2022-01-31 11:57:19,963 INFO: no action. I am (dblts1) the leader with the lock
2022-01-31 11:57:29,961 INFO: no action. I am (dblts1) the leader with the lock
2022-01-31 11:57:39,962 INFO: no action. I am (dblts1) the leader with the lock
2022-01-31 11:57:49,961 INFO: no action. I am (dblts1) the leader with the lock
2022-01-31 11:59:10,710 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-01-31 11:59:10,736 WARNING: Postgresql is not running.
2022-01-31 11:59:10,736 INFO: Lock owner: dblts3; I am dblts1
2022-01-31 11:59:10,740 INFO: pg_controldata:
  pg_control version number: 1201
  Catalog version number: 201909212
  Database system identifier: 7055759580436545892
  Database cluster state: in production
  pg_control last modified: Mon Jan 31 11:22:30 2022
  Latest checkpoint location: 0/74C6C70
  Latest checkpoint's REDO location: 0/74C6C38
  Latest checkpoint's REDO WAL file: 000000180000000000000007
  Latest checkpoint's TimeLineID: 24
  Latest checkpoint's PrevTimeLineID: 24
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:3736
  Latest checkpoint's NextOID: 106565
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 480
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 3736
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Mon Jan 31 11:22:30 2022
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 0/0
  Min recovery ending loc's timeline: 0
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: replica
  wal_log_hints setting: on
  max_connections setting: 100
  max_worker_processes setting: 8
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float4 argument passing: by value
  Float8 argument passing: by value
  Data page checksum version: 1
  Mock authentication nonce: 8b6745f71bfde052dc98128887fcef69f8ff6702dbe9054a08970ed830ee6801

2022-01-31 11:59:10,788 INFO: doing crash recovery in a single user mode
2022-01-31 11:59:11,254 WARNING: Postgresql is not running.
2022-01-31 11:59:11,254 INFO: Lock owner: dblts3; I am dblts1
2022-01-31 11:59:11,258 INFO: pg_controldata:
  pg_control version number: 1201
  Catalog version number: 201909212
  Database system identifier: 7055759580436545892
  Database cluster state: shut down
  pg_control last modified: Mon Jan 31 11:59:11 2022
  Latest checkpoint location: 0/8000028
  Latest checkpoint's REDO location: 0/8000028
  Latest checkpoint's REDO WAL file: 000000180000000000000008
  Latest checkpoint's TimeLineID: 24
  Latest checkpoint's PrevTimeLineID: 24
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:3736
  Latest checkpoint's NextOID: 106565
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 480
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 0
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Mon Jan 31 11:59:11 2022
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 0/0
  Min recovery ending loc's timeline: 0
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: replica
  wal_log_hints setting: on
  max_connections setting: 100
  max_worker_processes setting: 8
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float4 argument passing: by value
  Float8 argument passing: by value
  Data page checksum version: 1
  Mock authentication nonce: 8b6745f71bfde052dc98128887fcef69f8ff6702dbe9054a08970ed830ee6801

2022-01-31 11:59:11,261 INFO: Lock owner: dblts3; I am dblts1
2022-01-31 11:59:11,273 INFO: Local timeline=24 lsn=0/8000028
2022-01-31 11:59:11,282 INFO: master_timeline=25
2022-01-31 11:59:11,283 INFO: master: history=21        0/7453E60       no recovery target specified
22      0/747C3B8       no recovery target specified
23      0/74C61C8       no recovery target specified
24      0/74C6D20       no recovery target specified
2022-01-31 11:59:11,300 INFO: running pg_rewind from dblts3
2022-01-31 11:59:11,308 INFO: running pg_rewind from dbname=postgres user=rewind host=10.150.135.107 port=5432
2022-01-31 11:59:11,358 INFO: pg_rewind exit code=1
2022-01-31 11:59:11,359 INFO:  stdout=
2022-01-31 11:59:11,359 INFO:  stderr=pg_rewind: servers diverged at WAL location 0/74C6D20 on timeline 24
pg_rewind: rewinding from last common checkpoint at 0/74C6C70 on timeline 24
pg_rewind: fatal: "/storage/databases/postgres/data/.s.PGSQL.5432" is not a regular file

2022-01-31 11:59:11,366 ERROR: Failed to rewind from healty master: dblts3
2022-01-31 11:59:11,371 WARNING: Postgresql is not running.
2022-01-31 11:59:11,371 INFO: Lock owner: dblts3; I am dblts1
2022-01-31 11:59:11,379 INFO: pg_controldata:
  pg_control version number: 1201
  Catalog version number: 201909212
  Database system identifier: 7055759580436545892
  Database cluster state: shut down
  pg_control last modified: Mon Jan 31 11:59:11 2022
  Latest checkpoint location: 0/8000028
  Latest checkpoint's REDO location: 0/8000028
  Latest checkpoint's REDO WAL file: 000000180000000000000008
  Latest checkpoint's TimeLineID: 24
  Latest checkpoint's PrevTimeLineID: 24
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:3736
  Latest checkpoint's NextOID: 106565
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 480
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 0
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Mon Jan 31 11:59:11 2022
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 0/0
  Min recovery ending loc's timeline: 0
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: replica
  wal_log_hints setting: on
  max_connections setting: 100
  max_worker_processes setting: 8
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float4 argument passing: by value
  Float8 argument passing: by value
  Data page checksum version: 1
  Mock authentication nonce: 8b6745f71bfde052dc98128887fcef69f8ff6702dbe9054a08970ed830ee6801

2022-01-31 11:59:11,382 INFO: Lock owner: dblts3; I am dblts1
2022-01-31 11:59:11,390 INFO: starting as a secondary
2022-01-31 11:59:11,818 INFO: postmaster pid=370
2022-01-31 11:59:12,874 INFO: Lock owner: dblts3; I am dblts1
2022-01-31 11:59:12,875 INFO: establishing a new patroni connection to the postgres cluster
2022-01-31 11:59:12,960 INFO: no action. I am a secondary (dblts1) and following a leader (dblts3)
2022-01-31 11:59:13,307 INFO: no action. I am a secondary (dblts1) and following a leader (dblts3)
2022-01-31 11:59:23,236 INFO: no action. I am a secondary (dblts1) and following a leader (dblts3)
2022-01-31 11:59:33,244 INFO: no action. I am a secondary (dblts1) and following a leader (dblts3)
2022-01-31 11:59:43,233 INFO: no action. I am a secondary (dblts1) and following a leader (dblts3)
2022-01-31 11:59:53,234 INFO: no action. I am a secondary (dblts1) and following a leader (dblts3)
2022-01-31 12:00:03,234 INFO: no action. I am a secondary (dblts1) and following a leader (dblts3)
2022-01-31 12:00:13,253 INFO: no action. I am a secondary (dblts1) and following a leader (dblts3)
2022-01-31 12:00:23,253 INFO: no action. I am a secondary (dblts1) and following a leader (dblts3)
```

**Have you checked PostgreSQL logs?**
```
2022-01-31 13:01:21.954 CET [374] LOG:  new timeline 25 forked off current database system timeline 24 before current recovery point 0/80000A0
2022-01-31 13:01:26.958 CET [1065] FATAL:  could not start WAL streaming: ERROR:  requested starting point 0/8000000 on timeline 24 is not in this server's history
        DETAIL:  This server's history forked from timeline 24 at 0/74C6D20.
2022-01-31 13:01:26.958 CET [374] LOG:  new timeline 25 forked off current database system timeline 24 before current recovery point 0/80000A0
2022-01-31 13:01:31.961 CET [1082] FATAL:  could not start WAL streaming: ERROR:  requested starting point 0/8000000 on timeline 24 is not in this server's history
        DETAIL:  This server's history forked from timeline 24 at 0/74C6D20.
2022-01-31 13:01:31.961 CET [374] LOG:  new timeline 25 forked off current database system timeline 24 before current recovery point 0/80000A0
2022-01-31 13:01:36.971 CET [1100] FATAL:  could not start WAL streaming: ERROR:  requested starting point 0/8000000 on timeline 24 is not in this server's history
        DETAIL:  This server's history forked from timeline 24 at 0/74C6D20.
2022-01-31 13:01:36.971 CET [374] LOG:  new timeline 25 forked off current database system timeline 24 before current recovery point 0/80000A0
2022-01-31 13:01:41.970 CET [1109] FATAL:  could not start WAL streaming: ERROR:  requested starting point 0/8000000 on timeline 24 is not in this server's history
        DETAIL:  This server's history forked from timeline 24 at 0/74C6D20.
2022-01-31 13:01:41.970 CET [374] LOG:  new timeline 25 forked off current database system timeline 24 before current recovery point 0/80000A0
2022-01-31 13:01:46.980 CET [1130] FATAL:  could not start WAL streaming: ERROR:  requested starting point 0/8000000 on timeline 24 is not in this server's history
        DETAIL:  This server's history forked from timeline 24 at 0/74C6D20.
2022-01-31 13:01:46.981 CET [374] LOG:  new timeline 25 forked off current database system timeline 24 before current recovery point 0/80000A0
2022-01-31 13:01:51.979 CET [1148] FATAL:  could not start WAL streaming: ERROR:  requested starting point 0/8000000 on timeline 24 is not in this server's history
        DETAIL:  This server's history forked from timeline 24 at 0/74C6D20.
2022-01-31 13:01:51.979 CET [374] LOG:  new timeline 25 forked off current database system timeline 24 before current recovery point 0/80000A0
```

**Have you tried to use GitHub issue search?**
Yes.

**Additional context**
-

**Comment by CyberDem0n** [comment]
> if I force to shutdown the "Leader" node

Please define "force to shutdown"

> 2022-01-31 11:59:11,359 INFO:  stderr=pg_rewind: servers diverged at WAL location 0/74C6D20 on timeline 24
pg_rewind: rewinding from last common checkpoint at 0/74C6C70 on timeline 24
pg_rewind: fatal: "/storage/databases/postgres/data/.s.PGSQL.5432" is not a regular file


pg_rewind failed because there are unexpected files in PGDATA, this is not a Patroni fault.

And here is the reason:

```yaml
postgresql:
  parameters:
    unix_socket_directories: '.'
```

Please don't set unix_socket_directories to PGDATA and everything would work correctly.
