### ISSUE TITLE
Complete WAL-E support

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#22]
There's some  configuration information for WAL-E integration.  However, there doesn't seem to be any code for it.  What's intended here other than just writing to pg.conf?

**Comment by alexeyklyukin** [comment]
Hi Josh,

Take a look at scrips/restore.py. The code there deals with initialization of new replicas. It was intentionally moved out of the core Patroni to avoid requiring unnecessary dependencies for non-AWS use-cases. The WAL-E support relies on the archive/restore command being properly configured in Patroni, as well as regular base backups (part of the Docker container in the Spilo project).

**Comment by jberkus** [comment]
Oh, I see!

How does restore integrate with the rest of patroni?

**Comment by LappleApple** [comment]
@jberkus @alexeyklyukin This issue's almost a year old -- can we resolve or close?

**Comment by alexeyklyukin** [comment]
From my POV it's not an issue anymore.

**Comment by LappleApple** [comment]
OK, I'll close and you guys can reopen if necessary.

**Comment by Firefishy** [comment]
Is there any public documentation on how to use patroni + wal-e? I am failing to get it configured.

**Comment by CyberDem0n** [comment]
postgres.yaml:
```yaml
postgresql:
  parameters:
    archive_mode: "on"
    archive_command: envdir "/path/to/env-dir" wal-e wal-push "%p"
  recovery_conf:
    restore_command: envdir "/path/to/env-dir" wal-e wal-fetch "%f" "%p"
```

Although don't forget to create a cronjob, which will do `envdir "/path/to/env-dir" wal-e backup-push "/path/to/postgres/data/directory"

Please read about envdir in wal-e documentation: https://github.com/wal-e/wal-e/
