### ISSUE TITLE
on_role_change had no been called

### ISSUE THREAD

**Issue by mshalabi-ionos** [zalando/patroni#2206]
**Describe the bug**
I am using spilo and patroni on Kubernetes. I want to have some custom behavior, so I changed the code on spilo /scripts/on_role_change.sh. but this script was not executed at all. 

**To Reproduce**
create a cluster with 2 replicas
patronictl switchover or failover

**Expected behavior**
/scripts/on_role_change.sh is executed

**Screenshots**

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 13
- DCS (and its version):

**Patroni configuration file**
```
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_mode: 'on'
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.05
        checkpoint_completion_target: 0.9
        hot_standby: 'on'
        log_autovacuum_min_duration: 0
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_lock_waits: 'on'
        log_min_duration_statement: 500
        log_rotation_size: '25000'
        log_statement: ddl
        log_temp_files: 0
        max_connections: 100
        max_replication_slots: 10
        max_wal_senders: 10
        password_encryption: scram-sha-256
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        track_functions: all
        wal_compression: 'on'
        wal_level: hot_standby
        wal_log_hints: 'on'
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 20
    ttl: 40
  initdb:
  - auth-host: md5
  - auth-local: trust
  post_init: /scripts/post_init.sh "aaa_com"
  users:
    ionos_cloud_com:
      options:
      - CREATEDB
      - NOLOGIN
      password: ''
kubernetes:
  bypass_api_service: true
  labels:
    application: spilo
  pod_ip: 196.178.10.203
  ports:
  - name: postgresql
    port: 5432
  role_label: spilo-role
  scope_label: cluster-name
  use_endpoints: true
namespace: 4262b15a-7e8e-11ec-bd16-86e0daae0c49
postgresql:
  authentication:
    replication:
      password: kbnFbiCrRc7IgXLR5WKevlr9eSu5TMrtk4M1P7QHwGLNKjsVRpS
      username: standby
    superuser:
      password: w97Dab8qQxYfu3RmDW5oeOHwCGy20i2o3ebSx9nQ4QpgJaVE
      username: postgres
  basebackup_fast_xlog:
    command: /scripts/basebackup.sh
    retries: 2
  bin_dir: /usr/lib/postgresql/13/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh aaa_com true
  connect_address: 196.178.10.203:5432
  create_replica_method:
  - wal_e
  - basebackup_fast_xlog
  data_dir: /home/postgres/pgdata/pgroot/data
  listen: '*:5432'
  name: 4262b15a-7e8e-11ec-bd16-86e0daae0c49-4oymiqu-0
  parameters:
    archive_command: envdir "/run/etc/wal-e.d/env" wal-g wal-push "%p"
    bg_mon.history_buckets: 120
    bg_mon.listen_address: '::'
    extwlist.custom_path: /scripts
    extwlist.extensions: btree_gin,btree_gist,citext,hstore,intarray,ltree,pgcrypto,pgq,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,hypopg,timescaledb,pg_partman
    log_destination: csvlog
    log_directory: ../pg_log
    log_file_mode: '0644'
    log_filename: postgresql-%Y-%m-%d_%H%M%S.log
    log_rotation_age: 1d
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    pg_stat_statements.track_utility: 'off'
    shared_buffers: 391MB
    shared_preload_libraries: bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,timescaledb,pg_cron,pg_stat_kcache
    ssl: 'on'
    ssl_cert_file: /run/certs/server.crt
    ssl_key_file: /run/certs/server.key
  pg_hba:
  - local   all             all                                   trust
  - hostssl all             +aa_com    127.0.0.1/32       pam
  - host    all             all                127.0.0.1/32       md5
  - hostssl all             +aa_com    ::1/128            pam
  - host    all             all                ::1/128            md5
  - local   replication     standby                    trust
  - hostssl replication     standby all                md5
  - hostnossl all           all                all                reject
  - hostssl all             +aa_com    all                pam
  - hostssl all             all                all                md5
  pgpass: /run/postgresql/pgpass
  recovery_conf:
    restore_command: envdir "/run/etc/wal-e.d/env" /scripts/restore_command.py "%f" "%p"
  use_unix_socket: true
  use_unix_socket_repl: true
  wal_e:
    command: envdir /run/etc/wal-e.d/env bash /scripts/wale_restore.sh
    no_master: 1
    retries: 2
    threshold_backup_size_percentage: 30
    threshold_megabytes: 102400
restapi:
  connect_address: 10.219.233.203:8008
  listen: :8008
scope: 4262b15a-7e8e-11ec-bd16-86e0daae0c49-4oymiqu
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 33554432
postgresql:
  parameters:
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_vacuum_scale_factor: 0.05
    checkpoint_completion_target: 0.9
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_rotation_size: '25000'
    log_statement: ddl
    log_temp_files: 0
    max_connections: 100
    max_replication_slots: 10
    max_wal_senders: 10
    password_encryption: scram-sha-256
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    track_functions: all
    wal_compression: 'on'
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 20
synchronous_mode: false
synchronous_mode_strict: false
ttl: 40

```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
