### ISSUE TITLE
Error during pip install patroni

### ISSUE THREAD

**Issue by sahanasreenath** [zalando/patroni#2213]
**Describe the bug**
I am trying to install patroni using pip with python2.7, getting the following error.
```
[patroni]# pip install patroni==2.1.2
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting patroni==2.1.2
  Using cached patroni-2.1.2.tar.gz (175 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4rrjfY/patroni/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4rrjfY/patroni/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fN18ww
         cwd: /tmp/pip-install-4rrjfY/patroni/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4rrjfY/patroni/setup.py", line 226, in <module>
        check_psycopg()
      File "patroni/__init__.py", line 176, in check_psycopg
        fatal(error)
    TypeError: 'NoneType' object is not callable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
So i tried to install pyscopg2 using pip but I get below error
```
[root@ip-10-50-218-188 patroni]# pip install psycopg2>=2.5.4
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-McuTp4/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-McuTp4/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-eEMOF4
         cwd: /tmp/pip-install-McuTp4/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-eEMOF4/psycopg2.egg-info
    writing /tmp/pip-pip-egg-info-eEMOF4/psycopg2.egg-info/PKG-INFO
    writing top-level names to /tmp/pip-pip-egg-info-eEMOF4/psycopg2.egg-info/top_level.txt
    writing dependency_links to /tmp/pip-pip-egg-info-eEMOF4/psycopg2.egg-info/dependency_links.txt
    writing manifest file '/tmp/pip-pip-egg-info-eEMOF4/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Instead of using pip if I try via setup.py, I face the following error

```
[patroni]# cd /tmp/patroni && python setup.py build && python setup.py install
Traceback (most recent call last):
  File "setup.py", line 184, in <module>
    check_psycopg()
  File "/tmp/patroni/patroni/__init__.py", line 41, in check_psycopg
    fatal(error)
TypeError: 'NoneType' object is not callable
```

I tried to install patroni with pip3 and python3 and it works - but get the following error
```
[patroni]# patronictl -c /opt/patroni.yml list -f json
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: kubernetes'
```

I tried to upgrade pip, update setuptools, install pyscopg2, install pyscopg2-binary, install python-psutil
**To Reproduce**
Have a docker container setup with 2 nodes of Patroni - zookeeper - postgresql
have both python2.7.5 and python3.6.10 installed.
Package python3-setuptools-39.2.0-10.el7.noarch already installed and latest version
```
mkdir /tmp/
git clone https://github.com/zalando/patroni.git
cd /tmp/patroni && pip install -r requirements.txt
cd /tmp/patroni && python setup.py build && python setup.py install
export PATH=/usr/pgsql-10/bin:$PATH
pip install psycopg2>=2.5.4
```

**Expected behavior**
I expect to see setup.py install and build successfully without errors 

```
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: kubernetes'
```
**Screenshots**

**Environment**
- Patroni version: 2.1.2
- PostgreSQL version: 10.5
- DCS (and its version): local patroni.yml config

**Patroni configuration file**
```
scope: <cluster>
name: <member>

restapi:
    listen: 0.0.0.0:8008
    connect_address: 127.0.0.1:8008

zookeeper:
    hosts:
        - "<ip1>:2181"
        - "<ip2>:2181"
    
bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: True
            use_slots: True
            parameters:
                max_connections: 1000
                shared_buffers: '15GB'
                max_worker_processes: 4
                max_parallel_workers_per_gather: 2
                max_parallel_workers: 4
                work_mem: '4MB'
                random_page_cost: 1.1
                checkpoint_completion_target: '0.7'
                wal_buffers: 16MB
                default_statistics_target: 100
                min_wal_size: 1GB
                max_wal_size: 16GB
                wal_level: replica
                hot_standby: on
                wal_keep_segments: 8
                wal_sender_timeout: 300000
                max_wal_senders: 4
                max_replication_slots: 15
                checkpoint_timeout: 1800
                max_locks_per_transaction: 3200
    pg_hba: 
    - local all all  trust
    - local all all  md5
    - host all postgres 0.0.0.0/0 md5
    users:
        postgres:
            password: <redacted>
            options:
                - superuser

    post_init: /abc.sh

postgresql:
    listen: 0.0.0.0:5432
    connect_address: 10.50.219.136:5432
    data_dir: /var/lib/postgresql/data
    config_dir: /var/lib/postgresql/data
    bin_dir: /usr/pgsql-10/bin
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
