### ISSUE TITLE
Question: edit-config with -s option for list

### ISSUE THREAD

**Issue by avi1818** [zalando/patroni#2226]
I would like to have the following configuration:
```
postgresql:
  basebackup:
  - max-rate: 1000M
  - verbose
```

How is it possible to add the "-verbose" with the edit-config -s option
Something like the following did not work
patronictl edit-config -s 'postgresql.basebackup.verbose'

Thanks!

**Comment by mbanck** [comment]
What exactly did you run and which error did you get? I am not sure exactly, but maybe if you set `verbose` to `true` it works?

I get:
```
root@pg1:~# patronictl -c /etc/patroni/11-main.yml edit-config -s 'postgresql.basebackup.verbose=true'
--- 
+++ 
@@ -1,6 +1,8 @@
 loop_wait: 10
 maximum_lag_on_failover: 1048576
 postgresql:
+  basebackup:
+    verbose: true
   parameters:
     synchronous_commit: local
     synchronous_standby_names: '*'

Apply these changes? [y/N]:
```

**Comment by CyberDem0n** [comment]
The value under basebackup has to be the list, you can't do it with `patronictl edit-config -s`

**Comment by avi1818** [comment]
Thanks for the reply.  
I would like to add the following standby_cluster section using a command (not editor).  

```
    standby_cluster:
      host: 10.10.1.8
      port: 5432
      create_replica_methods:
        - basebackup

```
If I omit the part with the "- basebackup" will it still be using basebackup because it is the default?  
Will it also use the max-rate if I specify one?
```
  create_replica_methods:
        - basebackup

```
