### ISSUE TITLE
[Question] replication user and password must be the same for Active and Standby Clusters?

### ISSUE THREAD

**Issue by avi1818** [zalando/patroni#2227]
I'm trying to setup Active and Standby clusters.  I know the standby leader is connecting the active site master and the other replicas on standby cluster are connected to the standby leader.  Since the leader and replicas are connected to different servers, how can I configure their passwords differently?  Or do I need to have the replication user and password be the same for the Active and Standby sites?

2) I saw that username: standby and its password defined in the configuration file are also defined as env  variables.  In case I would like to change the password, where is the should it be changed?

```
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_mode: 'on'
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.05
        checkpoint_completion_target: 0.9
        hot_standby: 'on'
        log_autovacuum_min_duration: 0
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_lock_waits: 'on'
        log_min_duration_statement: 500
        log_statement: ddl
        log_temp_files: 0
        max_connections: 533
        max_replication_slots: 10
        max_wal_senders: 10
        max_worker_processes: '20'
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        track_commit_timestamp: 'on'
        track_functions: all
        wal_level: logical
        wal_log_hints: 'on'
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - auth-host: md5
  - auth-local: trust
  post_init: /scripts/post_init.sh "zalandos"
  users:
    zalandos:
      options:
      - CREATEDB
      - NOLOGIN
      password: ''
kubernetes:
  bypass_api_service: true
  labels:
    application: spilo
  pod_ip: ...
  ports:
  - name: postgresql
    port: 5432
  role_label: spilo-role
  scope_label: cluster-name
  use_endpoints: true
namespace: nms-postgres
postgresql:
  authentication:
    replication:
      password: PaJl5Li6hBIi6...
      username: standby
    superuser:
      password: oou85nUGo9...
      username: postgres
  basebackup_fast_xlog:
    command: /scripts/basebackup.sh
    retries: 2
  bin_dir: /usr/lib/postgresql/13/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos true
  connect_address: ...:5432
  create_replica_method:
  - basebackup_fast_xlog
  data_dir: /home/postgres/pgdata/pgroot/data
  listen: '*:5432'
  name: nms-postgres-cluster-0
  parameters:
    archive_command: /bin/true
    archive_mode: 'off'
    bg_mon.history_buckets: 120
    bg_mon.listen_address: 0.0.0.0
    extwlist.custom_path: /scripts
    extwlist.extensions: btree_gin,btree_gist,citext,hstore,intarray,ltree,pgcrypto,pgq,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,hypopg,pg_partman
    log_destination: stderr
    log_directory: ../pg_log
    log_file_mode: '0644'
    log_filename: postgresql-%u.log
    log_rotation_age: 1d
    log_truncate_on_rotation: 'on'
    logging_collector: 'false'
    max_logical_replication_workers: '10'
    pg_stat_statements.track_utility: 'off'
    shared_buffers: 3200MB
    shared_preload_libraries: bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,pg_cron,pg_stat_kcache
    ssl: 'on'
    ssl_cert_file: /run/certs/server.crt
    ssl_key_file: /run/certs/server.key
  pg_hba:
  - local   all             all                                   trust
  - hostssl all             +zalandos    127.0.0.1/32       pam
  - host    all             all                127.0.0.1/32       md5
  - hostssl all             +zalandos    ::1/128            pam
  - host    all             all                ::1/128            md5
  - hostssl replication     standby all                md5
  - hostnossl all           all                all                reject
  - hostssl all             +zalandos    all                pam
  - hostssl all             all                all                md5
  pgpass: /run/postgresql/pgpass
  use_unix_socket: true
restapi:
  connect_address: ...:8008
  listen: :8008
scope: nms-postgres-cluster

```

**Comment by CyberDem0n** [comment]
The replication user on the standby cluster should not be necessarily the same as used in the primary cluster, but the primary cluster must accept replication connection from the standby cluster.

> saw that username: standby and its password defined in the configuration file are also defined as env variables. In case I would like to change the password, where is the should it be changed?

https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html:

> It is possible to override some of the configuration parameters defined in the Patroni configuration file using the system environment variables. This document lists all **environment variables handled by Patroni. The values set via those variables always take precedence over the ones set in the Patroni configuration file.**

**Comment by avi1818** [comment]
Thanks for the quick reply, but I did not fully understood your answer.  
I assume pgpass file is automatically populated with user and password taken from configuration postgresql-authentication-replication-username.  If both standby leader and replicas pgpass files are taking the user and password from the same source the standby leader should have incorrect password.  What am I missing?

```
postgresql:
  authentication:
    replication:
      password: PaJl5Li6hBIi6
      username: standby

```
