### ISSUE TITLE
Provide a way to change pg_hba.conf of a running cluster on the Patroni level, without changing individual nodes.

### ISSUE THREAD

**Issue by Aytuar** [zalando/patroni#2230]
Please provide a way to change pg_hba.conf of a running cluster on the Patroni level, without changing individual nodes.

**Comment by CyberDem0n** [comment]
you can do it with `patronictl edit-config` (if `postgresql.pg_hba` isn't overridden in the local patroni.yaml).

**Comment by Aytuar** [comment]
It does not work if the **postgresql.parameters.hba_file** parameter is specified in the configuration file. If this parameter is not specified, the path to the pg_hba file by default, then it works.

**Comment by CyberDem0n** [comment]
@Aytuar that's exactly what I said.

**Comment by Aytuar** [comment]
What prevents patroni from managing this file if a parameter is specified?

**Comment by CyberDem0n** [comment]
The local configuration has HIGHER priority and overrides global configuration (that you set with patronictl edit-config)

**Comment by CyberDem0n** [comment]
Because the config is wrong.
You have to place it to the `bootstrap.dcs.postgresql.pg_hba`.
In case if the cluster is already up and running changes to the bootstrap section will not work. You have to use `patronictl edit-config` instead.

**Comment by Aytuar** [comment]
This doesn't work either.
```

scope: scope_name
namespace: /service/
name: cluster_name

restapi:
  listen: 0.0.0.0:8008
  connect_address: 1.2.3.4:8008
  authentication:
    username: api_user
    password: password

etcd3:
  hosts: 1.2.3.4:2379,1.2.3.5:2379,1.2.3.6:2379

bootstrap:
  method: wal-g
  wal-g:
    command: /usr/local/bin/wal_g_bootstrap.sh
    recovery_conf:
      recovery_target_action: promote
      recovery_target_timeline: latest
      restore_command: '/usr/bin/timeout 600 /usr/local/bin/wal-g wal-fetch %f %p'
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 30
    synchronous_mode: false
    synchronous_mode_strict: false
    postgresql:
    pg_hba:
    - host all all 127.0.0.1/32 md5
    - host all all 127.0.0.2/32 md5
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 1.2.3.4/32 md5
    - host all all 1.2.3.4/32 md5
    - host replication replicator 1.2.3.5/32 md5
    - host all all 1.2.3.5/32 md5
    - host replication replicator 1.2.3.6/32 md5
    - host all all 1.2.3.6/32 md5
    - host replication replicator 10.233.47.150/32 md5
    - host all all 10.233.47.150/32 md5
    - host replication replicator 10.233.47.151/32 md5
    - host all all 10.233.47.151/32 md5
    - host replication replicator 10.233.47.152/32 md5
    - host all all 10.233.47.152/32 md5
  use_pg_rewind: true
      parameters:
        hba_file: /var/lib/pgsql/13/pg_hba.conf
        archive_mode: 'on'
        archive_command: '/usr/bin/timeout 600 /usr/local/bin/wal-g wal-push %p'

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host all all 127.0.0.1/32 md5
  - host all all 127.0.0.2/32 md5
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator 1.2.3.4/32 md5
  - host all all 1.2.3.4/32 md5
  - host replication replicator 1.2.3.5/32 md5
  - host all all 1.2.3.5/32 md5
  - host replication replicator 1.2.3.6/32 md5
  - host all all 1.2.3.6/32 md5
  - host replication replicator 10.233.47.150/32 md5
  - host all all 10.233.47.150/32 md5
  - host replication replicator 10.233.47.151/32 md5
  - host all all 10.233.47.151/32 md5
  - host replication replicator 10.233.47.152/32 md5
  - host all all 10.233.47.152/32 md5

  users:
    admin:
      password: password
      options:
        - createrole
        - createdb
postgresql:
  recovery_conf:
    restore_command: '/usr/bin/timeout 600 /usr/local/bin/wal-g wal-fetch %f %p'
  create_replica_methods:
    - wal_g
    - basebackup
  wal_g:
    command: /usr/local/bin/wal_g_bootstrap.sh
    no_master: 0
    recovery_conf:
      restore_command: '/usr/bin/timeout 600 /usr/local/bin/wal-g wal-fetch %f %p'
  basebackup:
    max-rate: '1000M'
    checkpoint: 'fast'
  listen: 0.0.0.0:5432
  connect_address: 1.2.3.4:5432
  data_dir: /var/lib/pgsql/13/data
  bin_dir: /usr/pgsql-13/bin
  pgpass: /var/lib/pgsql/.pgpass
  authentication:
    replication:
      username: replicator
      password: password
    superuser:
      username: postgres
      password: password
  parameters:
    hba_file: /var/lib/pgsql/13/pg_hba.conf

```

**Comment by Aytuar** [comment]
Yes, I did not notice this error. The editor removed the indent. But on the server itself, the indentation is correct as you pointed out.
Here is the config on the server now.
```

scope: scope_name
namespace: /service/
name: cluster_name

restapi:
  listen: 0.0.0.0:8008
  connect_address: 1.2.3.4:8008
  authentication:
    username: api_user
    password: password

etcd3:
  hosts: 1.2.3.4:2379,1.2.3.5:2379,1.2.3.6:2379

bootstrap:
  method: wal-g
  wal-g:
    command: /usr/local/bin/wal_g_bootstrap.sh
    recovery_conf:
      recovery_target_action: promote
      recovery_target_timeline: latest
      restore_command: '/usr/bin/timeout 600 /usr/local/bin/wal-g wal-fetch %f %p'
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 30
    synchronous_mode: false
    synchronous_mode_strict: false
    postgresql:
      pg_hba:
      - host all all 127.0.0.1/32 md5
      - host all all 127.0.0.2/32 md5
      - host replication replicator 127.0.0.1/32 md5
      - host replication replicator 1.2.3.4/32 md5
      - host all all 1.2.3.4/32 md5
      - host replication replicator 1.2.3.5/32 md5
      - host all all 1.2.3.5/32 md5
      - host replication replicator 1.2.3.6/32 md5
      - host all all 1.2.3.6/32 md5
      - host replication replicator 10.233.47.150/32 md5
      - host all all 10.233.47.150/32 md5
      - host replication replicator 10.233.47.151/32 md5
      - host all all 10.233.47.151/32 md5
      - host replication replicator 10.233.47.152/32 md5
      - host all all 10.233.47.152/32 md5
    use_pg_rewind: true
      parameters:
        hba_file: /var/lib/pgsql/13/pg_hba.conf
        archive_mode: 'on'
        archive_command: '/usr/bin/timeout 600 /usr/local/bin/wal-g wal-push %p'

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host all all 127.0.0.1/32 md5
  - host all all 127.0.0.2/32 md5
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator 1.2.3.4/32 md5
  - host all all 1.2.3.4/32 md5
  - host replication replicator 1.2.3.5/32 md5
  - host all all 1.2.3.5/32 md5
  - host replication replicator 1.2.3.6/32 md5
  - host all all 1.2.3.6/32 md5
  - host replication replicator 10.233.47.150/32 md5
  - host all all 10.233.47.150/32 md5
  - host replication replicator 10.233.47.151/32 md5
  - host all all 10.233.47.151/32 md5
  - host replication replicator 10.233.47.152/32 md5
  - host all all 10.233.47.152/32 md5

  users:
    admin:
      password: password
      options:
        - createrole
        - createdb
postgresql:
  recovery_conf:
    restore_command: '/usr/bin/timeout 600 /usr/local/bin/wal-g wal-fetch %f %p'
  create_replica_methods:
    - wal_g
    - basebackup
  wal_g:
    command: /usr/local/bin/wal_g_bootstrap.sh
    no_master: 0
    recovery_conf:
      restore_command: '/usr/bin/timeout 600 /usr/local/bin/wal-g wal-fetch %f %p'
  basebackup:
    max-rate: '1000M'
    checkpoint: 'fast'
  listen: 0.0.0.0:5432
  connect_address: 1.2.3.4:5432
  data_dir: /var/lib/pgsql/13/data
  bin_dir: /usr/pgsql-13/bin
  pgpass: /var/lib/pgsql/.pgpass
  authentication:
    replication:
      username: replicator
      password: password
    superuser:
      username: postgres
      password: password
  parameters:
    hba_file: /var/lib/pgsql/13/pg_hba.conf
```

And it only works if completely remove the hba_file parameter.

**Comment by CyberDem0n** [comment]
@Aytuar works for me, what am I doing wrong?
```yaml
$ cat postgres2.yml 
scope: test
name: postgresql2

restapi:
  listen: 127.0.0.1:8010
  connect_address: 127.0.0.1:8010

etcd:
  host: 127.0.0.1:2379

bootstrap:
  dcs:
    postgresql:
      use_pg_rewind: true
      pg_hba:
      - local all all trust
      - host all all 127.0.0.1/32 trust
      - host all all ::1/128 trust
      - local replication replicator trust
      - host replication replicator 127.0.0.1/32 trust
      - host replication replicator ::1/128 trust
      - host all all 0.0.0.0/0 md5
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

postgresql:
  listen: 127.0.0.1:5434
  connect_address: 127.0.0.1:5434
  data_dir: data/postgresql2
  pgpass: /tmp/pgpass2
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: zalando
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: rewind_password
  parameters:
    unix_socket_directories: /tmp
```

```bash
$ PATH=/usr/lib/postgresql/14/bin:$PATH ./patroni.py postgres2.yml
2022-03-02 11:13:09,707 INFO: Selected new etcd server http://localhost:2379
2022-03-02 11:13:09,711 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-03-02 11:13:09,714 INFO: Lock owner: None; I am postgresql2
2022-03-02 11:13:09,719 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "akukushkin".
This user must also own the server process.

The database cluster will be initialized with locales
  COLLATE:  en_US.UTF-8
  CTYPE:    en_US.UTF-8
  MESSAGES: en_US.UTF-8
  MONETARY: de_DE.UTF-8
  NUMERIC:  de_DE.UTF-8
  TIME:     de_DE.UTF-8
The default text search configuration will be set to "english".

Data page checksums are enabled.

creating directory data/postgresql2 ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Europe/Berlin
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/lib/postgresql/14/bin/pg_ctl -D data/postgresql2 -l logfile start

2022-03-02 11:13:10.785 CET [2914] LOG:  starting PostgreSQL 14.2 (Ubuntu 14.2-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
2022-03-02 11:13:10.785 CET [2914] LOG:  listening on IPv4 address "127.0.0.1", port 5434
2022-03-02 11:13:10.792 CET [2914] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5434"
2022-03-02 11:13:10.800 CET [2915] LOG:  database system was shut down at 2022-03-02 11:13:10 CET
2022-03-02 11:13:10.811 CET [2914] LOG:  database system is ready to accept connections
2022-03-02 11:13:10,812 INFO: postmaster pid=2914
localhost:5434 - accepting connections
localhost:5434 - accepting connections
2022-03-02 11:13:10,843 INFO: establishing a new patroni connection to the postgres cluster
2022-03-02 11:13:10,851 INFO: running post_bootstrap
2022-03-02 11:13:10,898 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
2022-03-02 11:13:10,914 INFO: initialized a new cluster
2022-03-02 11:13:20,905 INFO: no action. I am (postgresql2), the leader with the lock
^C2022-03-02 11:13:21.730 CET [2914] LOG:  received fast shutdown request
2022-03-02 11:13:21.734 CET [2914] LOG:  aborting any active transactions
2022-03-02 11:13:21.734 CET [2926] FATAL:  terminating connection due to administrator command
2022-03-02 11:13:21.739 CET [2914] LOG:  background worker "logical replication launcher" (PID 2921) exited with exit code 1
2022-03-02 11:13:21.740 CET [2916] LOG:  shutting down
2022-03-02 11:13:21.789 CET [2914] LOG:  database system is shut down
```

```bash
$ cat data/postgresql2/pg_hba.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
local all all trust
host all all 127.0.0.1/32 trust
host all all ::1/128 trust
local replication replicator trust
host replication replicator 127.0.0.1/32 trust
host replication replicator ::1/128 trust
host all all 0.0.0.0/0 md5
```
