### ISSUE TITLE
Unable to change max_connections

### ISSUE THREAD

**Issue by AllwynJesu** [zalando/patroni#2235]
Hi,

I tried changing the max_connections using patronictl but it is not reflecting the PostgreSQL. Below is the command I have used for changing the max_connections from 100 to 300. My patroni version is 

```
patronictl -c patroni.yml edit-config
patronictl -c patroni.yml reload <cluster_name>
```

I have verified using the below command 

```
patronictl -c patroni.yml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 300
    wal_level: replica
  pg_hba:
  - local all all trust
  - host replication replication_user 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
  use_slot: true
retry_timeout: 10
ttl: 30
```

But PostgreSQL is showing max_connection is still 100

```
app_db=> select max_conn,used,res_for_super,max_conn-used-res_for_super res_for_normal from (select count(*) used from pg_stat_activity) t1, (select setting::int res_for_super from pg_settings where name='superuser_reserved_connections') t2, (select setting::int max_conn from pg_settings where name='max_connections') t3;

 max_conn | used | res_for_super | res_for_normal
----------+------+---------------+----------------
      100 |    6 |             3 |             91
(1 row)
```

Patroni and PostgreSQL versions 

```
 PostgreSQL 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

 patroni 2.1.2
```

Please let me know whether there is another command for changing the configuration.
