### ISSUE TITLE
Missing bits for ENV

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#224]
There's two missing bits which we could use as individual ENV vars, because they are often changed by the orchestration system:
- postgresql/pg_hba
- postgresql/parameters

Obviously, both of these are somewhat complex because they are multiple lines; I was thinking we could pass in JSON, though.

The reason why using PATRONI_CONFIGURATION isn't great here is that I'm looking to pass parameters using the ENV passed by the orchestration system (Kubernetes, in my case).  Composing complex JSON in ENV on the Kube-master side isn't supported, so I need individual values which can be set equal to something.

**Comment by CyberDem0n** [comment]
You are definitely right about pg_hba (and I envisioned it), because it must contain some custom network ranges. Everything else is pretty static and I kind of not implemented this functionality intentionally.

``postgresql.parameters`` -- usually this is something what you want to have similar across all cluster nodes. In order to solve this problem we introduced dynamic global configuration. Nodes are looking on ``config`` key and if there are some changes they are trying to apply them (including ``postgresql/parameters``).

I was thinking it would be not a problem to put some small static file into a docker:
```yaml
bootstrap:
  dcs:
    ttl: 20
    loop_wait: 10
    postgresql:
      parameters:
        shared_buffers: XXX
        max_connections: 200
        etc: ...

  initdb:
  - encoding: UTF8
  - data-checksums
  pg_hba:
  - line1
  - line2
  
```

Later it's possible to change global dynamic configuration  via API: https://github.com/zalando/patroni/blob/master/docs/dynamic_configuration.rst#rest-api for all cluster nodes.
