### ISSUE TITLE
/patroni endpoint not showing upgraded version

### ISSUE THREAD

**Issue by Dadavan** [zalando/patroni#2240]
**Describe the bug**
As far as I understand in order to check the actual running version of the Patroni cluster (and not just the version of the CLI tool) you can curl this endpoint: `http://localhost:8008/patroni`

But it seems that this endpoint isn't getting updated with the latest version. I have upgraded my cluster from 2.1.2 to 2.1.3 but for some reason this endpoint is still showing an older version (it's actually showing 2.1.0, so seems that this has been happening for a while). Is this a known bug? Is there a different way to check the running version?

**To Reproduce**
* Upgrade Patroni cluster - upgrade `patroni` on replica, perform switchover and then upgrade the old leader...
* `curl http://localhost:8008/patroni | jq .`

**Expected behavior**
Endpoint should show the new version

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 14.1

**Patroni configuration file**
```
scope: postgres-main
namespace: "/patroni"
name: postgres-main-i-0aa5457f1f91db27c
bootstrap:
  dcs:
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_replication_slots: 10
        max_wal_senders: 10
        wal_level: logical
        max_connections: 1000
        max_worker_processes: 8
  initdb:
  - encoding: UTF8
  - locale: en_US.UTF-8
  users:
    barman:
      password: ***
      options:
      - replication
    debezium:
      password: ***
      options:
      - replication
restapi:
  listen: 0.0.0.0:8008
  connect_address: ***:8008
consul:
  host: localhost
  port: 8500
  register_service: true
  checks: []
postgresql:
  listen: 0.0.0.0:5432
  connect_address: ***:5432
  data_dir: "/data/postgresql/14"
  bin_dir: "/usr/lib/postgresql/14/bin"
  authentication:
    replication:
      username: repl_user
      password: ***
    superuser:
      username: postgres
      password: ***
  pg_hba:
  - host replication repl_user 0.0.0.0/0 md5
  - host replication barman 0.0.0.0/0 md5
  - host replication debezium 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
  parameters:
    auto_explain.log_analyze: 'on'
    auto_explain.log_buffers: 'on'
    auto_explain.log_min_duration: 500ms
    auto_explain.log_nested_statements: 'on'
    auto_explain.log_timing: 'off'
    auto_explain.log_triggers: 'on'
    auto_explain.log_verbose: 'off'
    checkpoint_completion_target: 0.9
    effective_io_concurrency: 200
    hot_standby: 'on'
    log_autovacuum_min_duration: 3s
    log_connections: 'on'
    log_directory: "/var/log/postgresql"
    log_filename: server.log
    log_lock_waits: 'on'
    log_min_duration_statement: -1
    log_rotation_age: 0
    log_rotation_size: 0
    log_statement: ddl
    log_temp_files: 1kB
    logging_collector: 'on'
    max_wal_size: 1GB
    min_wal_size: 512MB
    old_snapshot_threshold: 120
    random_page_cost: 1.1
    shared_preload_libraries: auto_explain, pg_repack, pg_stat_statements
    ssl_cert_file: "/etc/patroni/ssl.crt"
    ssl_key_file: "/etc/patroni/ssl.key"
    ssl: 'on'
    temp_file_limit: -1
    track_activity_query_size: 2048
    track_io_timing: 'on'
    wal_buffers: 16MB
    wal_compression: 'on'
    wal_keep_segments: 64
    effective_cache_size: 24GB
    maintenance_work_mem: 2GB
    max_parallel_workers_per_gather: 4
    max_parallel_workers: 8
    shared_buffers: 8GB
    work_mem: 10MB
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: true
watchdog:
  mode: 'off'
```

**patronictl show-config**
```
postgresql:
  parameters:
    max_connections: 1000
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    wal_level: logical
  use_pg_rewind: true
  use_slots: true
slots:
  debezium:
    database: bringg
    plugin: pgoutput
    type: logical
```
