### ISSUE TITLE
[Question] How to configure patroni instances to pick the correct hostname for bootstrapping

### ISSUE THREAD

**Issue by manuel-koch** [zalando/patroni#2243]
I'm trying out the patroni docker-compose setup with some modifications, mainly to use a timescaledb docker image ( with builtin Patroni ) instead of the patroni image.
The etcd and haproxy container startup properly as far as I can tell, but when a postgres instance starts and I query the patroni information I get the following:

```
$ docker-compose exec patroni1 bash -c "patronictl -c postgres.yml list"
+ Cluster: demo (7073882635747729435) ----+----+-----------+-----------------+
| Member   | Host      | Role   | State   | TL | Lag in MB | Tags            |
+----------+-----------+--------+---------+----+-----------+-----------------+
| patroni1 | 127.0.0.1 | Leader | running |  3 |           | clonefrom: true |
+----------+-----------+--------+---------+----+-----------+-----------------+
```

Subsequently when starting the second postgres instance (patroni2), the bootstraping fails because patroni2 tries to connect to "127.0.0.1" instead to the running patroni1 instance.

```
patroni2: 2022-03-14 08:12:42,654 INFO: trying to bootstrap from leader 'patroni1'
patroni2: pg_basebackup: error: connection to server at "127.0.0.1", port 5432 failed: Connection refused
patroni2:   Is the server running on that host and accepting TCP/IP connections?
patroni2: 2022-03-14 08:12:42,674 ERROR: Error when fetching backup: pg_basebackup exited with code=1
patroni2: 2022-03-14 08:12:42,675 WARNING: Trying again in 5 seconds
```

Can someone give a hint what I'm doing wrong ? Likely the configuration is broken by my adjustments or I'm missing a key feature of the configuration that has a wrong setting for my setup ?

Here is my docker-compose setup:

```yaml
version: "2"

networks:
  demo: {}

volumes:
  patroni1-volume: {}
  patroni2-volume: {}
  patroni3-volume: {}

services:
    etcd1: &etcd
        image: patroni
        networks: [ demo ]
        environment:
            ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
            ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
            ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
            ETCD_INITIAL_CLUSTER_STATE: new
            ETCD_INITIAL_CLUSTER_TOKEN: tutorial
        container_name: demo-etcd1
        hostname: etcd1
        command: etcd -name etcd1 -initial-advertise-peer-urls http://etcd1:2380

    etcd2:
        <<: *etcd
        container_name: demo-etcd2
        hostname: etcd2
        command: etcd -name etcd2 -initial-advertise-peer-urls http://etcd2:2380

    etcd3:
        <<: *etcd
        container_name: demo-etcd3
        hostname: etcd3
        command: etcd -name etcd3 -initial-advertise-peer-urls http://etcd3:2380

    haproxy:
        image: patroni
        networks: [ demo ]
        env_file: docker/patroni.env
        hostname: haproxy
        container_name: demo-haproxy
        ports:
            - "5000:5000"
            - "5001:5001"
        command: haproxy
        environment: &haproxy_env
            ETCDCTL_ENDPOINTS: http://etcd1:2379,http://etcd2:2379,http://etcd3:2379
            PATRONI_ETCD3_HOSTS: "'etcd1:2379','etcd2:2379','etcd3:2379'"
            PATRONI_SCOPE: demo

    patroni1:
        image: timescale/timescaledb-ha:pg14.2-ts2.6.0-p4
        networks: [ demo ]
        env_file: docker/patroni.env
        hostname: patroni1
        container_name: demo-patroni1
        entrypoint: ["/patroni_entrypoint.sh"]
        environment:
            <<: *haproxy_env
            PATRONI_NAME: patroni1
        volumes:
        - ./postgres0.yml:/home/postgres/postgres.yml
        - patroni1-volume:/home/postgres/data

    patroni2:
        image: timescale/timescaledb-ha:pg14.2-ts2.6.0-p4
        networks: [ demo ]
        env_file: docker/patroni.env
        hostname: patroni2
        container_name: demo-patroni2
        entrypoint: ["/patroni_entrypoint.sh"]
        environment:
            <<: *haproxy_env
            PATRONI_NAME: patroni2
        volumes:
        - ./postgres1.yml:/home/postgres/postgres.yml
        - patroni2-volume:/home/postgres/data

    patroni3:
        image: timescale/timescaledb-ha:pg14.2-ts2.6.0-p4
        networks: [ demo ]
        env_file: docker/patroni.env
        hostname: patroni3
        container_name: demo-patroni3
        entrypoint: ["/patroni_entrypoint.sh"]
        environment:
            <<: *haproxy_env
            PATRONI_NAME: patroni3
        volumes:
        - ./postgres2.yml:/home/postgres/postgres.yml
        - patroni3-volume:/home/postgres/data

    fix-volumes:    
        image: busybox
        command:
        - sh
        - -c
        - >
            echo "Fixing permissions..." ;
            chown -R 1000:1000 /mnt/volume? ; 
            chmod -R 700 /mnt/volume? ;
            ls -la /mnt/volume? ;
        volumes:
        - ./postgres0.yml:/home/postgres/postgres.yml
        - patroni1-volume:/mnt/volume1
        - patroni2-volume:/mnt/volume2
        - patroni3-volume:/mnt/volume3
```

Here is the configuration of the 1st and 2nd patroni instances:
```
scope: batman
name: postgresql0

log:
  level: DEBUG

restapi:
  listen: 127.0.0.1:8008
  connect_address: 127.0.0.1:8008

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 127.0.0.1/32 md5
  - host all all 0.0.0.0/0 md5

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: admin%
      options:
        - createrole
        - createdb

postgresql:
  listen: 127.0.0.1:5432
  connect_address: 127.0.0.1:5432
  data_dir: data/postgresql0
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: zalando
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: rewind_password
  parameters:
    unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: true
    nosync: false
```

```
scope: batman
name: postgresql1

log:
  level: DEBUG

restapi:
  listen: 127.0.0.1:8008
  connect_address: 127.0.0.1:8008

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 127.0.0.1/32 md5
  - host all all 0.0.0.0/0 md5

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: admin%
      options:
        - createrole
        - createdb

postgresql:
  listen: 127.0.0.1:5432
  connect_address: 127.0.0.1:5432
  data_dir: data/postgresql1
  pgpass: /tmp/pgpass1
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: zalando
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: rewind_password
  parameters:
    # Fully qualified kerberos ticket file for the running user
    # same as KRB5CCNAME used by the GSS
    unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: true
    nosync: false
```
