### ISSUE TITLE
Changing shared_buffers via `patronictl edit-config` has no effect

### ISSUE THREAD

**Issue by victor-sudakov** [zalando/patroni#2251]
**Describe the bug**
When changing the shared_buffers parameter in DCS, the new value is applied and kept in kv but has no effect on Postgres instances. 
![image](https://user-images.githubusercontent.com/12457866/159806119-ad251213-650c-4e77-9245-57b1e129dd27.png)

**Expected behavior**
I expect that after changing shared_buffers in DCS, a "pending restart" indicator should appear in `patronictl list` output, but there is none.
![image](https://user-images.githubusercontent.com/12457866/159806441-ccc74494-247a-4f65-88dd-5ebc18d25f14.png)

However the changed value is visible in `patronictl show-config`.

If I change some other parameter which does not require a restart like effective_cache_size, it's applied all right.

**Environment**
- Patroni version: patroni/bullseye-pgdg,now 2.1.3-1.pgdg110+1
- PostgreSQL version:  13.6 
- DCS (and its version): consul Consul v1.11.4

**patronictl show-config**
```
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  check_timeline: true
  parameters:
    effective_cache_size: 20GB
    max_connections: 960
    max_locks_per_transaction: 256
    max_prepared_transactions: 960
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 16
    shared_buffers: 10GB
    track_commit_timestamp: 'on'
    wal_keep_size: 12GB
  pg_hba:
  - local   all             all                               trust
  - host    all             all       0.0.0.0/0               md5
  - local   replication   repmgr                              trust
  - host    replication   repmgr      0.0.0.0/0               md5
  remove_data_directory_on_diverged_timelines: true
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: false
retry_timeout: 10
synchronous_mode: true
synchronous_node_count: 2
ttl: 30

```

**Have you checked Patroni logs?**
Found nothing relevant in Patroni or PostgreSQL logs.
