### ISSUE TITLE
Cannot Major Upgrade: dcs __init__.py doesn't include dateutil.parser

### ISSUE THREAD

**Issue by wmendes-ionos** [zalando/patroni#2258]
**Describe the bug**
When a major update takes place, during a leader election, dcs fails when parsing `scheduled_at`.
The reason is the lack of `dateutil.parser` import
https://github.com/zalando/patroni/blob/cb3071adfbffb540f24ce67370ffc8599a7207de/patroni/dcs/__init__.py#L322-L323

**To Reproduce**
Create a multi-node cluster
Schedule a Major upgrade
After complete, check the containers, $PGVERSION shows the desired version
pg_controldata shows yet the previous version
Execute a major upgrade directly
```
~$ /bin/su postgres -c '/usr/bin/python3 /scripts/inplace_upgrade.py 2'
```

**Expected behavior**
A major upgrade takes place successfully

**Screenshots**
<img width="1264" alt="Screenshot 2022-03-30 at 17 18 41" src="https://user-images.githubusercontent.com/99019868/160870618-b9cbaa8d-72b7-4a75-b5d0-a2bb5ebc307d.png">

<img width="1718" alt="Screenshot 2022-03-30 at 17 24 21" src="https://user-images.githubusercontent.com/99019868/160871842-020dbd70-d61b-4afc-80da-3ec8f210b59a.png">

**Environment**
- Patroni version: latest release
- PostgreSQL version: any
- DCS (and its version): latest release

**Patroni configuration file**
```
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 33554432
pause: false
postgresql:
  parameters:
    archive_mode: 'on'
    archive_timeout: 1800s
    auth_delay.milliseconds: '2000'
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_vacuum_scale_factor: 0.05
    checkpoint_completion_target: 0.9
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_rotation_size: '25000'
    log_statement: ddl
    log_temp_files: 0
    max_connections: 100
    max_replication_slots: 10
    max_wal_senders: 10
    password_encryption: scram-sha-256
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    track_functions: all
    wal_compression: 'on'
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 40
synchronous_mode: false
synchronous_mode_strict: false
ttl: 60
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
