### ISSUE TITLE
watchdog - inappropriate ioctl for device  on RHEL 8 ppc64le.

### ISSUE THREAD

**Issue by zejeanmi** [zalando/patroni#2265]
We run Postgres and Patroni on RedHat 8 ppc64le, and get these errors with watchdog :
```
WARNING: Could not activate Linux watchdog device:
   'Could not get information about watchdog device: [Errno 25] Inappropriate ioctl for device'
ERROR: Configuration requires watchdog, but watchdog could not be configured.
INFO: Not promoting self because watchdog could not be activated
WARNING: Watchdog device is not usable

```
I get the same error on all my test RHEL 8 ppc64le virtual machines.
we ran modprobe softdog and the /dev/watchdog  exists and is owned by postgres.
crw-------. 1 postgres postgres 10, 130 Apr  5 16:11 /dev/watchdog

**Environment**
- Patroni version:   2.1.3
- PostgreSQL version:   14.1
- DCS :  etcd 3.5.2  (linux/amd64)
- OS  (patroni / postgres ) : 
```
    Virtualization: powervm
    Operating System: Red Hat Enterprise Linux 8.5 (Ootpa)
    CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
    Kernel: Linux 4.18.0-348.12.2.el8_5.ppc64le
    Architecture: ppc64-le
```
- Python : 3.6.8

**Patroni configuration file**
```
scope: patronicluster
name: postgresql2

restapi:
  listen: lab-rh734db216.ceti.etat-ge.ch:8008
  connect_address: lab-rh734db216.ceti.etat-ge.ch:8008

etcd3:
  hosts:
  - lab-rh734std555:2379
  - lab-rh734std556:2379
  - lab-rh734std557:2379
  username: patroni_user
  password: **********


bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:

  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host postgres patroni_rep all md5
  - host all postgres all md5
  - host all patroni_rwnd all md5
  - host replication patroni_rep all md5

  users:
    admin:
      password: admin%
      options:
        - createrole
        - createdb

postgresql:
  listen: lab-rh734db216.ceti.etat-ge.ch:5432
  connect_address: lab-rh734db216.ceti.etat-ge.ch:5432
  data_dir: /data/postgres/pgdata/
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: patroni_rep
      password: **********
    superuser:
      username: postgres
      password: **********
    rewind:  # Has no effect on postgres 10 and lower
      username: patroni_rwnd
      password: **********
  parameters:

watchdog:
  mode: required  # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters: null
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

**Have you tried to use GitHub issue search?**
https://github.com/zalando/patroni/pull/531
Fixed bug with python 3. 

**Additional context**
I highly suspect this problem is related to ppc64le.

Thanks for your help !
