### ISSUE TITLE
Patroni showing different lags on primary vs few (2) standby nodes

### ISSUE THREAD

**Issue by Arvindtoorpudba** [zalando/patroni#2268]
**Describe the bug**

I am facing an inssue here with my 5 nodes patroni cluster. where the ABCD-c2p-074217.XXXXXXX.com host is always showing zero lag at all times, even though the primary Node ABCD-asc-02p.XXXXXXX.com  is showing correct lag, this is causing a confusion and the only way currently to get the lag is to query from Nodes . At any given time the lag is always different on below 3 nodes vs c2p* Nodes: 

ABCD-asc-01p.XXXXXXX.com   
ABCD-asc-02p.XXXXXXX.com   
ABCD-hoc-01p.XXXXXXX.com 

and Nodes that are showing wrong lag are:

ABCD-c2p-073183.XXXXXXX.com
ABCD-c2p-074217.XXXXXXX.com

Note : One thing that I have noticed is that patroni versions are different, could that be causing the issue ?? This configuration has been setup before I have started working at place.. and I am a newbie to patroni setup. 
Please ignore any mistakes in logging this ticket

**To Reproduce**

#####################################################################
From Nodes ABCD-c2p-074217:
#####################################################################

[root@ABCD-c2p-074217 ~]# /app/bin/patronictl -c /etc/patroni/patroni.yml list xfwapplr_prd
+---------------------------------------------+---------------------------------------------+--------------+---------+----+-----------+
| Member                                      | Host                                        | Role         | State   | TL | Lag in MB |
+ Cluster: xfwapplr_prd (6871356810020004807) +---------------------------------------------+--------------+---------+----+-----------+
| ABCD-asc-01p.XXXXXXX.com   | ABCD-asc-01p.XXXXXXX.com   | Sync Standby | running | 72 |         0 |
| ABCD-asc-02p.XXXXXXX.com   | ABCD-asc-02p.XXXXXXX.com   | Leader       | running | 72 |           |
| ABCD-c2p-073183.XXXXXXX.com| ABCD-c2p-073183.XXXXXXX.com| Replica      | running | 72 |         0 |
| ABCD-c2p-074217.XXXXXXX.com| ABCD-c2p-074217.XXXXXXX.com| Replica      | running | 72 |         0 |
| ABCD-hoc-01p.XXXXXXX.com   | ABCD-hoc-01p.XXXXXXX.com   | Replica      | running | 72 |         0 |
+---------------------------------------------+---------------------------------------------+--------------+---------+----+-----------+
[root@ABCD-c2p-074217 ~]# date
Thu Apr  7 13:33:58 UTC 2022
[root@ABCD-c2p-074217 ~]# /app/bin/patronictl -c /etc/patroni/patroni.yml list xfwapplr_prd
+---------------------------------------------+---------------------------------------------+--------------+---------+----+-----------+
| Member                                      | Host                                        | Role         | State   | TL | Lag in MB |
+ Cluster: xfwapplr_prd (6871356810020004807) +---------------------------------------------+--------------+---------+----+-----------+
| ABCD-asc-01p.XXXXXXX.com   | ABCD-asc-01p.XXXXXXX.com   | Sync Standby | running | 72 |         0 |
| ABCD-asc-02p.XXXXXXX.com   | ABCD-asc-02p.XXXXXXX.com   | Leader       | running | 72 |           |
| ABCD-c2p-073183.XXXXXXX.com| ABCD-c2p-073183.XXXXXXX.com| Replica      | running | 72 |         0 |
| ABCD-c2p-074217.XXXXXXX.com| ABCD-c2p-074217.XXXXXXX.com| Replica      | running | 72 |         0 |
| ABCD-hoc-01p.XXXXXXX.com   | ABCD-hoc-01p.XXXXXXX.com   | Replica      | running | 72 |         0 |
+---------------------------------------------+---------------------------------------------+--------------+---------+----+-----------+
[root@ABCD-c2p-074217 ~]#

#####################################################################
From Node ABCD-asc-02p
#####################################################################

[root@ABCD-asc-02p ~]# /app/bin/patronictl -c /etc/patroni/patroni.yml list xfwapplr_prd
+ Cluster: xfwapplr_prd (6871356810020004807) +---------------------------------------------+--------------+---------+----+-----------+
| Member                                      | Host                                        | Role         | State   | TL | Lag in MB |
+---------------------------------------------+---------------------------------------------+--------------+---------+----+-----------+
| ABCD-asc-01p.XXXXXXX.com   | ABCD-asc-01p.XXXXXXX.com   | Sync Standby | running | 72 |         0 |
| ABCD-asc-02p.XXXXXXX.com   | ABCD-asc-02p.XXXXXXX.com   | Leader       | running | 72 |           |
| ABCD-c2p-073183.XXXXXXX.com| ABCD-c2p-073183.XXXXXXX.com| Replica      | running | 72 |       227 |
| ABCD-c2p-074217.XXXXXXX.com| ABCD-c2p-074217.XXXXXXX.com| Replica      | running | 72 |         1 |
| ABCD-hoc-01p.XXXXXXX.com   | ABCD-hoc-01p.XXXXXXX.com   | Replica      | running | 72 |       137 |
+---------------------------------------------+---------------------------------------------+--------------+---------+----+-----------+
[root@ABCD-asc-02p ~]# date
Thu Apr  7 13:33:54 UTC 2022
[root@ABCD-asc-02p ~]# /app/bin/patronictl -c /etc/patroni/patroni.yml list xfwapplr_prd
+ Cluster: xfwapplr_prd (6871356810020004807) +---------------------------------------------+--------------+---------+----+-----------+
| Member                                      | Host                                        | Role         | State   | TL | Lag in MB |
+---------------------------------------------+---------------------------------------------+--------------+---------+----+-----------+
| ABCD-asc-01p.XXXXXXX.com   | ABCD-asc-01p.XXXXXXX.com   | Sync Standby | running | 72 |         0 |
| ABCD-asc-02p.XXXXXXX.com   | ABCD-asc-02p.XXXXXXX.com   | Leader       | running | 72 |           |
| ABCD-c2p-073183.XXXXXXX.com| ABCD-c2p-073183.XXXXXXX.com| Replica      | running | 72 |         0 |
| ABCD-c2p-074217.XXXXXXX.com| ABCD-c2p-074217.XXXXXXX.com| Replica      | running | 72 |         0 |
| ABCD-hoc-01p.XXXXXXX.com   | ABCD-hoc-01p.XXXXXXX.com   | Replica      | running | 72 |       116 |
+---------------------------------------------+---------------------------------------------+--------------+---------+----+-----------+
[root@ABCD-asc-02p ~]# date
Thu Apr  7 13:34:54 UTC 2022
[root@ABCD-asc-02p ~]#

Nodes in the cluster :

[root@ABCD-sc-02p ~]# /app/bin/patronictl -c /etc/patroni/patroni.yml list xfwapplr_prd
+ Cluster: xfwapplr_prd (6871356810020004807) +---------------------------------------------+--------------+---------+----+-----------+
| Member                                      | Host                                        | Role         | State   | TL | Lag in MB |
+---------------------------------------------+---------------------------------------------+--------------+---------+----+-----------+
| ABCD-sc-01pXXXXXXX.COM    | ABCD-sc-01pXXXXXXX.COM    | Sync Standby | running | 72 |         0 |
| ABCD-sc-02pXXXXXXX.COM    | ABCD-sc-02pXXXXXXX.COM    | Leader       | running | 72 |           |
| ABCD-c2p-073183XXXXXXX.COM | ABCD-c2p-073183.XXXXXXX.COM | Replica      | running | 72 |         0 |
| ABCD-c2p-074217XXXXXXX.COM | ABCD-c2p-074217.XXXXXXX.COM | Replica      | running | 72 |         0 |
| ABCD-hoc-01pXXXXXXX.COM    | ABCD-hoc-01p.XXXXXXX.COM    | Replica      | running | 72 |         5 |
+---------------------------------------------+---------------------------------------------+--------------+---------+----+-----------+
[root@ABCD-asc-02p ~]#

**Expected behavior**

**Screenshots**

**Environment**
- Patroni version: 2.0 & 2.1
- PostgreSQL version: 11.7
- DCS (and its version): Consul v1.4.4

[root@ABCD-asc-02p ~]# curl -s `hostname`:8008/patroni | jq .
{
  "state": "running",
  "postmaster_start_time": "2022-03-24 20:28:23.900 UTC",
  "role": "master",
  "server_version": 110007,
  "cluster_unlocked": false,
  "xlog": {
    "location": 213050944456696
  },
  "timeline": 72,
  "replication": [
    {
      "usename": "replicator",
      "application_name": "ABCD-c2p-073183.XXXXXXX.COM ,
      "client_addr": "x.x.x.x",
      "state": "streaming",
      "sync_state": "async",
      "sync_priority": 0
    },
    {
      "usename": "replicator",
      "application_name": "ABCD-asc-01p.XXXXXXX.COM ,
      "client_addr": "x.x.x.x",
      "state": "streaming",
      "sync_state": "sync",
      "sync_priority": 1
    },
    {
      "usename": "replicator",
      "application_name": "ABCD-hoc-01p.XXXXXXX.COM ,
      "client_addr": "x.x.x.x",
      "state": "streaming",
      "sync_state": "async",
      "sync_priority": 0
    },
    {
      "usename": "replicator",
      "application_name": "ABCD-c2p-074217.XXXXXXX.COM ,
      "client_addr": "x.x.x.x",
      "state": "streaming",
      "sync_state": "async",
      "sync_priority": 0
    }
  ],
  "database_system_identifier": "6871356810020004807",
  "patroni": {
    "version": "2.0.0",
    "scope": "xfwapplr_prd"
  }
}

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

[root@ABCD-c2p-074217 ~]# curl -s http://localhost:8008/patroni | jq .
{
  "state": "running",
  "postmaster_start_time": "2022-03-26 04:48:58.183855+00:00",
  "role": "replica",
  "server_version": 110007,
  "xlog": {
    "received_location": 213050277099264,
    "replayed_location": 213050277099264,
    "replayed_timestamp": "2022-04-07 13:13:55.610674+00:00",
    "paused": false
  },
  "timeline": 72,
  "dcs_last_seen": 1649337228,
  "database_system_identifier": "6871356810020004807",
  "patroni": {
    "version": "2.1.3",
    "scope": "xfwapplr_prd"
  }
}

**Patroni configuration file**
```
scope: xfwapplr_prd
name: ABCD-asc-02p.XXXXXXXXX.com

restapi:
  listen: ABCD-asc-02p.XXXXXXXXX.com:8008
  connect_address: ABCD-asc-02p.XXXXXXXXX.com:8008
consul:
  host: ABCD-asc-02p.XXXXXXXXX.com:8500

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: hot_standby
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 10
        max_replication_slots: 10
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
  pg_hba:
    - local all postgres    peer
    - local all all    peer
    - local replication all    peer
    - host all all 127.0.0.1/32   md5
    - host all replicator 127.0.0.1/32   md5
    - host all all 96.xxx.xxx.xxx/32   md5
    - host all all ::1/128   md5
    - host replication replicator 0.0.0.0/32   md5
  recovery_conf:
    restore_command: cp ../wal_archive/%f %p
    recovery_target_timeline: "latest"

initdb:  # Note: It needs to be a list (some options need values, others are switches)
 - encoding: UTF8
 - data-checksums

# Some additional users users which needs to be created after initializing new cluster
users:
 admin:
   password: XXXXXXXXXX
   options:
     - createrole
     - createdb

postgresql:
listen: ABCD-asc-02p.XXXXXXXXX.com:5432
connect_address: ABCD-asc-02p.XXXXXXXXX.com:5432
data_dir: /app/postgres/data
bin_dir: /usr/pgsql-11/bin
shared_buffers: 3840MB
effective_cache_size: 9000MB
maintenance_work_mem: 1920MB
work_mem: 24MB
default_statistics_target: 500
random_page_cost: 1.1
min_wal_size: 4GB
max_wal_size: 16GB
shared_preload_libraries: 'timescaledb'
timescaledb.max_background_workers: 8
pgpass: /tmp/.pgpass0
authentication:
 replication:
   username: replicator
   password: XXXXXXXXXX
 superuser:
   username: postgres
   password: XXXXXXXXXX
 rewind:  # Has no effect on postgres 10 and lower
   username: rewind_user
   password: XXXXXXXXXX

   parameters:
  unix_socket_directories: /var/run/postgresql
  max_connections: 100
  logging_collector: "on"
  log_directory: /app/postgres/logs
  log_truncate_on_rotation: "on"
  log_checkpoints: "on"
  log_lock_waits: "on"
  log_rotation_size: 1GB
  log_rotation_age: 1440
  log_filename: postgresql-%a.log
  log_min_duration_statement: 1000

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

**patronictl show-config**
```
###############################################################
patronictl show-config:
###############################################################

[root@ABCD--asc-02p ~]# /app/bin/patronictl -c /etc/patroni/patroni.yml show-config xfwapplr_prd
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=wapplr-prod archive-push %p
    archive_mode: 'on'
    archive_timeout: 1800s
    checkpoint_timeout: 900
    effective_cache_size: 10GB
    hot_standby: 'on'
    log_min_duration_statement: 40000
    log_statement: ddl
    maintenance_work_mem: 1GB
    max_connections: 350
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: 50GB
    shared_buffers: 10GB
    shared_preload_libraries: timescaledb
    statement_timeout: 2h
    temp_buffer: 100MB
    wal_keep_segments: 200
    wal_level: hot_standby
    wal_log_hints: 'on'
    wal_sender_timeout: 300s
    work_mem: 64MB
  pg_hba:
  - local   all      postgres                         peer
  - host    all      all        0.0.0.0/0             md5
  - host    replication     replicator     0.0.0.0/0  md5
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
ttl: 30
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Yes , no similar issues

**Additional context**
