### ISSUE TITLE
Patroni reload is not loading the renewed certificates 

### ISSUE THREAD

**Issue by Shiva2199** [zalando/patroni#2272]
**Describe the bug**
As mentioned in official Patroni documentation, local configuration patroni.yml could be changed and reloaded in runtime (without restart of Patroni) https://patroni.readthedocs.io/en/latest/dynamic_configuration.html
but when I run  patronictl -c /etc/patroni reload cluster_name it is not using the new certificates .

**To Reproduce**
1. renew the certificates 
2. run  patronictl -c /etc/patroni reload cluster_name

**Expected behavior**
To load the new certificates without any downtime/restart

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
scope: clustername
name: patroni

restapi:
  listen: 0.0.0.0:8008
  connect_address: localhost:8008
  certfile: /data/keys/patroni/cert.pem
  keyfile: /data/keys/patroni/key.pem
  cafile: /data/keys/patroni/cacert.pem
  verify_client: required

ctl:
  insecure: true
  certfile: /data/keys/patroni/cert.pem
  cacert: /data/keys/patroni/cacert.pem
  keyfile: /data/keys/patroni/key.pem

zookeeper:
  hosts:
    - node1:2281
    - node22281
    - zk_node:2281
  use_ssl: true
  cacert: /data/keys/patroni/cacert.pem
  cert: /data/keys/patroni/cert.pem
  key: /data/keys/patroni/key.pem
  verify: true

log:
  dir: "/data/pgsql/cluster01/logs"

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
      use_slots: false
      basebackup:
        max-rate: '70M'
        checkpoint: 'fast'
      parameters:
        hot_standby: "on"
        max_connections: 2003
        max_wal_senders: 10
        wal_keep_segments: 100
        max_parallel_workers: 24
        max_worker_processes: 24
        archive_mode: "off"
        archive_command: ""
      recovery_conf:
        restore_command: ""

# No need, since no HAProxy health checks
#  users:
#    haproxy:
#      options: []


postgresql:
  postgresql:
    create_replica_methods:
      - pgbackrest
      - basebackup
    pgbackrest:
      command: /usr/bin/pgbackrest --stanza=DOP_cluster01 --delta restore
      keep_data: True
      no_params: True
    basebackup:
      max-rate: '70M'
      checkpoint: 'fast'
  listen: "0.0.0.0:6432"
  connect_address: <Ip>:6432
  data_dir: /data/pgsql/cluster01/data
  bin_dir: /usr/pgsql-12/bin
  pgpass: "/data/pgsql/cluster01/pgpass0"

  pg_hba:
    - hostssl all postgres 127.0.0.1/32 cert clientcert=verify-ca
    - hostssl all postgres ::1/128 cert clientcert=verify-ca
    - hostssl replication replicator 0.0.0.0/0 cert clientcert=verify-ca
    - hostssl all all 0.0.0.0/0 scram-sha-256
    - hostnossl sameuser haproxy 0.0.0.0/0 scram-sha-256
    - hostnossl grafana postgres 0.0.0.0/0 trust
    - local all postgres peer

  authentication:
    superuser:
      username: "postgres"
      sslmode: verify-ca
      sslkey: "/data/keys/patroni/users/postgres/key.pem"
      sslcert: "/data/keys/patroni/users/postgres/cert.pem"
      sslrootcert: "/data/keys/patroni/users/postgres/cacert.pem"
    replication:
      username: "replicator"
      sslmode: verify-ca
      sslkey: "/data/keys/patroni/users/replicator/key.pem"
      sslcert: "/data/keys/patroni/users/replicator/cert.pem"
      sslrootcert: "/data/keys/patroni/users/replicator/cacert.pem"
    rewind:
      username: "rewinder"
      sslmode: verify-ca
      sslkey: "/data/keys/patroni/users/rewinder/key.pem"
      sslcert: "/data/keys/patroni/users/rewinder/cert.pem"
      sslrootcert: "/data/keys/patroni/users/rewinder/cacert.pem"
  parameters:
    unix_socket_directories: '/var/run/postgresql'
    password_encryption: "scram-sha-256"
    ssl: "on"
    ssl_key_file: "/data/keys/postgress/key.pem"
    ssl_cert_file: "/data/keys/postgress/cert.pem"
    ssl_ca_file: "/data/keys/postgress/cacert.pem"
    dynamic_shared_memory_type: posix
    log_destination: 'stderr'
    logging_collector: on
    log_directory: 'log'
    log_filename: 'postgresql-%a.log'
    log_truncate_on_rotation:  on
    log_rotation_age:  1d
    log_error_verbosity: default
    datestyle: 'iso, mdy'
    lc_messages: 'C'
    lc_monetary: 'en_US.UTF-8'
    lc_numeric: 'en_US.UTF-8'
    lc_time: 'en_US.UTF-8'
    default_text_search_config: 'pg_catalog.english'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```
 patronictl -c /etc/patroni.yaml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  basebackup:
    checkpoint: fast
    max-rate: 70M
  parameters:
    archive_command: ''
    archive_mode: 'off'
    hot_standby: 'on'
    max_connections: 2003
    max_parallel_workers: 24
    max_wal_senders: 10
    max_worker_processes: 24
    wal_keep_segments: 100
  recovery_conf:
    restore_command: ''
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
synchronous_mode: true
ttl: 30

**Additional context**
Please help me in understanding how to reload the certificates
