### ISSUE TITLE
No new sync-standby if the current sync-standby fails

### ISSUE THREAD

**Issue by haslersn** [zalando/patroni#2280]
**Describe the bug**

I have a cluster that currently has no sync-standby. One replica failed, so I assume that it was the sync-standby, so now there's no sync-standby.

Furthermore, the cluster is in read-only mode. This is perhaps due to the missing sync-standby and because I'm using `synchronous_mode`. However, I'm currently not using `synchronous_mode_strict`, so I'm not sure if this read-only behaviour is intended.

Then I tried to do a switchover in order to fix the read-only state. This also fails due to the missing sync-standby:

```
root@my-db-1:/home/postgres# patronictl switchover my-db
Master [my-db-1]: 
Candidate ['my-db-0', 'my-db-2'] []: my-db-0
When should the switchover take place (e.g. 2022-04-26T10:30 )  [now]: 
Current cluster topology
+ Cluster: my-db (7050441988668362834) -----------------------------+----+-----------+
| Member                       | Host           | Role    | State   | TL | Lag in MB |
+------------------------------+----------------+---------+---------+----+-----------+
| my-db-0 | 10.100.105.171 | Replica | running |  6 |         0 |
| my-db-1 | 10.100.34.69   | Leader  | running |  6 |           |
| my-db-2 | 10.100.226.204 | Replica | stopped |    |   unknown |
+------------------------------+----------------+---------+---------+----+-----------+
Are you sure you want to switchover cluster my-db, demoting current master my-db-1? [y/N]: y
Switchover failed, details: 412, candidate name does not match with sync_standby
```

**Expected behavior**

The remaining replica should probably be the new sync-standby.

**Environment**
- Patroni version: `patronictl version 2.1.1`
- PostgreSQL version: 12
- DCS (and its version): What's this?

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 33554432
postgresql:
  parameters:
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_vacuum_scale_factor: 0.05
    checkpoint_completion_target: 0.9
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_statement: ddl
    log_temp_files: 0
    max_connections: 100
    max_replication_slots: 10
    max_wal_senders: 10
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    track_functions: all
    wal_level: hot_standby
    wal_log_hints: 'on'
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
ttl: 30
```

**Have you checked Patroni logs?**
On my-db-0:
```
2022-04-26 11:06:30.489 39 LOG {ticks: 0, maint: 0, retry: 0}
2022-04-26 11:07:00.517 39 LOG {ticks: 0, maint: 0, retry: 0}
2022-04-26 11:07:14.619 39 ERROR connection error: PQconnectPoll
2022-04-26 11:07:14.619 39 ERROR 
2022-04-26 11:07:14.619 39 WARNING postgres: default timeout
2022-04-26 11:07:14.619 39 ERROR connection error: PQconnectPoll
2022-04-26 11:07:14.619 39 ERROR 
2022-04-26 11:07:14.620 39 ERROR connection error: PQconnectPoll
2022-04-26 11:07:14.620 39 ERROR 
2022-04-26 11:07:14.620 39 WARNING db: default timeout
```

**Have you checked PostgreSQL logs?**
There's no ongoing PostgreSQL log on my-db-0. That maybe just indicates, that it operates normally.
