### ISSUE TITLE
Patroni connect leader node postgres database from replication node

### ISSUE THREAD

**Issue by yinan8128** [zalando/patroni#2281]
**Describe the bug**
leader node pg_hba.conf rejects replication node replicator user postgres database connection, seems patroni 2.1.3 version need to connect leader node postgres database from replication node which is not in patroni 2.0.1

--after add below part to pg_hba.conf then resolved
host postgres replicator 10.35.53.30/32 scram-sha-256
host postgres replicator 10.35.53.29/32 scram-sha-256
host postgres replicator 10.35.53.28/32 scram-sha-256

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 14.2
- DCS (and its version): consul 1.2.2

**pg_hba.conf**
```
local all postgres trust
local all all trust
host replication replicator 0.0.0.0/0 scram-sha-256
host replication replicator ::/0 scram-sha-256
host replication postgres 127.0.0.1/32 trust
host replication postgres ::1/128 trust
host all all 127.0.0.1/32 scram-sha-256
host all all ::1/128 scram-sha-256
host postgres postgres 10.35.53.30/32 scram-sha-256
host postgres pgwatch2 10.35.53.30/32 scram-sha-256
host postgres postgres 10.35.53.29/32 scram-sha-256
host postgres pgwatch2 10.35.53.29/32 scram-sha-256
host postgres postgres 10.35.53.28/32 scram-sha-256
host postgres pgwatch2 10.35.53.28/32 scram-sha-256
host postgres all 0.0.0.0/0 reject
host postgres all ::/0 reject
hostnossl all all 0.0.0.0/0 scram-sha-256
hostnossl all all ::/0 scram-sha-256
hostssl all all 0.0.0.0/0 scram-sha-256 clientcert=verify-full
hostssl all all ::/0 scram-sha-256 clientcert=verify-full
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: /bin/true
    archive_mode: 'on'
    archive_timeout: 1800s
    auto_explain.log_min_duration: 60000
    auto_explain.log_nested_statements: true
    autovacuum: 'on'
    autovacuum_analyze_scale_factor: 0.05
    autovacuum_analyze_threshold: 50
    autovacuum_max_workers: 6
    autovacuum_vacuum_cost_delay: 2ms
    autovacuum_vacuum_cost_limit: 8000
    autovacuum_vacuum_scale_factor: 0.01
    autovacuum_vacuum_threshold: 50
    autovacuum_work_mem: 1GB
    bgwriter_delay: 50ms
    bgwriter_lru_maxpages: 4000
    bgwriter_lru_multiplier: 4
    checkpoint_completion_target: 0.7
    checkpoint_timeout: 30min
    config_file: /var/lib/pgsql/14/data/postgresql.conf
    constraint_exclusion: partition
    cron.database_name: postgres
    datestyle: ISO, MDY
    default_statistics_target: 100
    default_text_search_config: pg_catalog.english
    effective_cache_size: 5952MB
    hot_standby: 'on'
    idle_in_transaction_session_timeout: 10min
    jit: 'off'
    lc_messages: C
    lc_monetary: C
    lc_numeric: C
    lc_time: C
    lock_timeout: 30s
    log_autovacuum_min_duration: 500
    log_checkpoints: 'off'
    log_connections: 'off'
    log_destination: stderr
    log_directory: /var/log/postgresql
    log_disconnections: 'off'
    log_duration: 'off'
    log_filename: postgresql.log
    log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
    log_lock_waits: 'on'
    log_min_duration_statement: 5s
    log_recovery_conflict_waits: 'on'
    log_rotation_age: 0
    log_rotation_size: 0
    log_statement: ddl
    log_temp_files: 1MB
    log_timezone: UTC
    log_truncate_on_rotation: 'off'
    logging_collector: 'on'
    maintenance_work_mem: 2GB
    max_connections: 1000
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: '7936'
    min_wal_size: 1024
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    random_page_cost: 1.1
    shared_buffers: 1984MB
    shared_preload_libraries: pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron
    ssl: 'on'
    ssl_ca_file: /var/lib/pgsql/tls/root.crt
    ssl_cert_file: /var/lib/pgsql/tls/server.crt
    ssl_key_file: /var/lib/pgsql/tls/server.key
    statement_timeout: 10min
    temp_file_limit: 5GB
    timezone: UTC
    track_io_timing: 'on'
    unix_socket_directories: /var/run/postgresql
    wal_buffers: -1
    wal_compression: 'on'
    wal_keep_size: 160MB
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 3MB
  recovery_conf:
    restore_command: /bin/true
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
synchronous_mode: true
ttl: 30
```

**Have you checked Patroni logs?**
--replication node patroni log
Apr 27 08:59:58 s87653y-patroni patroni[23364]: Traceback (most recent call last):
Apr 27 08:59:58 s87653y-patroni patroni[23364]: File "/usr/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 60, in check_leader_is_not_in_recovery
Apr 27 08:59:58 s87653y-patroni patroni[23364]: with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
Apr 27 08:59:58 s87653y-patroni patroni[23364]: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Apr 27 08:59:58 s87653y-patroni patroni[23364]: return next(self.gen)
Apr 27 08:59:58 s87653y-patroni patroni[23364]: File "/usr/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 44, in get_connection_cursor
Apr 27 08:59:58 s87653y-patroni patroni[23364]: conn = psycopg.connect(**kwargs)
Apr 27 08:59:58 s87653y-patroni patroni[23364]: File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Apr 27 08:59:58 s87653y-patroni patroni[23364]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Apr 27 08:59:58 s87653y-patroni patroni[23364]: psycopg2.OperationalError: connection to server at "10.35.53.29", port 5432 failed: FATAL:  pg_hba.conf rejects connection for host "10.35.53.30", user "replicator", database "postgres", SSL encryption
Apr 27 08:59:58 s87653y-patroni patroni[23364]: connection to server at "10.35.53.29", port 5432 failed: FATAL:  pg_hba.conf rejects connection for host "10.35.53.30", user "replicator", database "postgres", no encryption
