### ISSUE TITLE
no switching

### ISSUE THREAD

**Issue by orlakwahr** [zalando/patroni#2284]
**Describe the bug**
I setup a cluster with 3 nodes with haproxy, keepalived and etcd - that works.
then I add one more node
now I have 4 nodes in the cluster - works.
ok now I start sending load to the cluster I get all around very good RPS.

now I disconnect network on node 4 - in 10 seconds or so the node gets removed from the list
/usr/local/bin/patronictl list postgres-cluster
even before 10 seconds haproxy stops balancing traffic to the node and
I get 0 errors and node nicely gets removed from the cluster.
i.e. it does not show up in /usr/local/bin/patronictl list postgres-cluster

If I later turn on network on node 4 again - it gets in sync and the appears in
/usr/local/bin/patronictl list postgres-cluster

now one mode test
I disconnect network from node 4 and - it gets removed from the cluster automatically.
and then I disconnect network on any other read replica - now things get funny.
the node is not getting removed from the
/usr/local/bin/patronictl list postgres-cluster

it actually sits there with state running even though it is not even in the network.

things will get even more funny if I disconnect network on the master - it also never gets removed from the cluster and actually new master is not getting assigned.

with both latter scenarios a lot of errors and RPS degraded dramatically to an unusable extent in case with master disconnection.

all this with patroni 2.1.3

later on I created similar cluster with patroni 2.1.1 and all is working as expected - network disconnected - replica gone from the list, network connected - back in the list. master disconnected - some other replica becomes a master and no python traces in logs - the configs are identical.

**To Reproduce**
I use oracle linux 8.5 and https://github.com/vitabaks/postgresql_cluster to create the cluster.
python3.8

**Expected behavior**
If I loose a replica - I hope it to be gone from the 
/usr/local/bin/patronictl list postgres-cluster
and if it gets back on line I hope it to get back to
/usr/local/bin/patronictl list postgres-cluster

also If I disconnect the master I hope some other replica will become new master.

**Screenshots**

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 14
- etcd Version: 3.3.25
- confd 0.16.0 (Git SHA: 7217b0ca, Go Version: go1.10.2)

**Patroni configuration file**
```
---

scope: postgres-cluster
name: pg-db1
namespace: /service/


restapi:
  listen: 10.16.18.133:8008
  connect_address: 10.16.18.133:8008

etcd:
        hosts: 10.16.18.133:2379,10.16.18.134:2379,10.16.18.135:2379

bootstrap:
  method: initdb
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    synchronous_node_count: 1
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 500
        superuser_reserved_connections: 5
        max_locks_per_transaction: 64
        max_prepared_transactions: 0
        huge_pages: try
        shared_buffers: 8Gb
        work_mem: 20971kB
        maintenance_work_mem: 2GB
        effective_cache_size: 24GB
        checkpoint_timeout: 15min
        checkpoint_completion_target: 0.9
        min_wal_size: 1GB
        max_wal_size: 4GB
        wal_buffers: 16MB
        default_statistics_target: 100
        seq_page_cost: 1
        random_page_cost: 4
        effective_io_concurrency: 2
        synchronous_commit: on
        autovacuum: on
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_scale_factor: 0.01
        autovacuum_vacuum_cost_limit: 500
        autovacuum_vacuum_cost_delay: 2
        autovacuum_naptime: 1s
        max_files_per_process: 4096
        archive_mode: on
        archive_timeout: 1800s
        archive_command: cd .
        wal_level: replica
        wal_keep_size: 2GB
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: on
        wal_log_hints: on
        wal_compression: on
        shared_preload_libraries: pg_stat_statements,auto_explain
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        pg_stat_statements.track_utility: false
        pg_stat_statements.save: true
        auto_explain.log_min_duration: 10s
        auto_explain.log_analyze: true
        auto_explain.log_buffers: true
        auto_explain.log_timing: false
        auto_explain.log_triggers: true
        auto_explain.log_verbose: true
        auto_explain.log_nested_statements: true
        track_io_timing: on
        log_lock_waits: on
        log_temp_files: 0
        track_activities: on
        track_counts: on
        track_functions: all
        log_checkpoints: on
        logging_collector: on
        log_truncate_on_rotation: on
        log_rotation_age: 1d
        log_rotation_size: 0
        log_line_prefix: '%t [%p-%l] %r %q%u@%d '
        log_filename: 'postgresql-%a.log'
        log_directory: /var/log/postgresql
        hot_standby_feedback: on
        max_standby_streaming_delay: 30s
        wal_receiver_status_interval: 10s
        idle_in_transaction_session_timeout: 10min
        datestyle: 'iso, dmy'
        timezone: 'UTC'

  initdb:  # List options to be passed on to initdb
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5


postgresql:
  listen: 10.16.18.133,127.0.0.1:5432
  connect_address: 10.16.18.133:5432
  use_unix_socket: true
  data_dir: /var/lib/pgsql/14/data
  bin_dir: /usr/pgsql-14/bin
  config_dir: /var/lib/pgsql/14/data
  pgpass: /var/lib/pgsql/.pgpass_patroni
  authentication:
    replication:
      username: replicator
      password: replicator-pass
    superuser:
      username: postgres
      password: postgres-pass
#    rewind:  # Has no effect on postgres 10 and lower
#      username: rewind_user
#      password: rewind_password
  parameters:
    unix_socket_directories: /var/run/postgresql
    stats_temp_directory: /var/lib/pgsql_stats_tmp


  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false

  create_replica_methods:
    - basebackup
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'


watchdog:
  mode: off  # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

  # specify a node to replicate from (cascading replication)
#  replicatefrom: (node name)
```

**patronictl show-config**
```
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: cd .
    archive_mode: true
    archive_timeout: 1800s
    auto_explain.log_analyze: true
    auto_explain.log_buffers: true
    auto_explain.log_min_duration: 10s
    auto_explain.log_nested_statements: true
    auto_explain.log_timing: false
    auto_explain.log_triggers: true
    auto_explain.log_verbose: true
    autovacuum: true
    autovacuum_analyze_scale_factor: 0.01
    autovacuum_max_workers: 5
    autovacuum_naptime: 1s
    autovacuum_vacuum_cost_delay: 2
    autovacuum_vacuum_cost_limit: 500
    autovacuum_vacuum_scale_factor: 0.01
    checkpoint_completion_target: 0.9
    checkpoint_timeout: 15min
    cpu_index_tuple_cost: 0.002
    datestyle: iso, dmy
    default_statistics_target: 100
    effective_cache_size: 24GB
    effective_io_concurrency: 2
    hot_standby: true
    hot_standby_feedback: true
    huge_pages: true
    idle_in_transaction_session_timeout: 10min
    log_checkpoints: true
    log_directory: /var/log/postgresql
    log_filename: postgresql-%a.log
    log_line_prefix: '%t [%p-%l] %r %q%u@%d '
    log_lock_waits: true
    log_rotation_age: 1d
    log_rotation_size: 0
    log_temp_files: 0
    log_truncate_on_rotation: true
    logging_collector: true
    maintenance_work_mem: 2GB
    max_connections: 500
    max_files_per_process: 4096
    max_locks_per_transaction: 32768
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_standby_streaming_delay: 30s
    max_wal_senders: 10
    max_wal_size: 4GB
    min_wal_size: 1GB
    pg_stat_statements.max: 10000
    pg_stat_statements.save: true
    pg_stat_statements.track: all
    pg_stat_statements.track_utility: false
    random_page_cost: 0.1
    seq_page_cost: 1.0
    shared_buffers: 8Gb
    shared_preload_libraries: pg_stat_statements,auto_explain
    superuser_reserved_connections: 5
    synchronous_commit: true
    timezone: UTC
    track_activities: true
    track_counts: true
    track_functions: all
    track_io_timing: true
    wal_buffers: 16MB
    wal_compression: true
    wal_keep_size: 2GB
    wal_level: replica
    wal_log_hints: true
    wal_receiver_status_interval: 10s
    work_mem: 20971kB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
synchronous_node_count: 1
ttl: 30
```

**Have you checked Patroni logs?**
Apr 28 13:49:01 localhost patroni[988]: 2022-04-28 13:48:58,543 INFO: Lock owner: pg-db3; I am pg-db1
Apr 28 13:49:01 localhost patroni[988]: 2022-04-28 13:49:01,048 INFO: Selected new etcd server http://10.16.18.135:2379
Apr 28 13:49:01 localhost patroni[988]: 2022-04-28 13:49:01,048 ERROR: Request to server http://10.16.18.133:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'10.16.18.133\', port=2379): Max retries exceeded with url: /v2/keys/service/postgres-cluster/members/pg-db1 (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'10.16.18.133\', port=2379): Read timed out. (read timeout=2.499780117010232)",))',)
Apr 28 13:49:01 localhost patroni[988]: 2022-04-28 13:49:01,048 INFO: Reconnection allowed, looking for another server.
Apr 28 13:49:01 localhost patroni[988]: 2022-04-28 13:49:01,048 ERROR:
Apr 28 13:49:01 localhost patroni[988]: Traceback (most recent call last):
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 449, in _make_request
Apr 28 13:49:01 localhost patroni[988]:    six.raise_from(e, None)
Apr 28 13:49:01 localhost patroni[988]:  File "<string>", line 3, in raise_from
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 444, in _make_request
Apr 28 13:49:01 localhost patroni[988]:    httplib_response = conn.getresponse()
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/lib64/python3.6/http/client.py", line 1361, in getresponse
Apr 28 13:49:01 localhost patroni[988]:    response.begin()
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/lib64/python3.6/http/client.py", line 311, in begin
Apr 28 13:49:01 localhost patroni[988]:    version, status, reason = self._read_status()
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/lib64/python3.6/http/client.py", line 272, in _read_status
Apr 28 13:49:01 localhost patroni[988]:    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
Apr 28 13:49:01 localhost patroni[988]:    return self._sock.recv_into(b)
Apr 28 13:49:01 localhost patroni[988]: socket.timeout: timed out
Apr 28 13:49:01 localhost patroni[988]: During handling of the above exception, another exception occurred:
Apr 28 13:49:01 localhost patroni[988]: Traceback (most recent call last):
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
Apr 28 13:49:01 localhost patroni[988]:    chunked=chunked,
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 451, in _make_request
Apr 28 13:49:01 localhost patroni[988]:    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 341, in _raise_timeout
Apr 28 13:49:01 localhost patroni[988]:    self, url, "Read timed out. (read timeout=%s)" % timeout_value
Apr 28 13:49:01 localhost patroni[988]: urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.16.18.133', port=2379): Read timed out. (read timeout=2.499780117010232)
Apr 28 13:49:01 localhost patroni[988]: During handling of the above exception, another exception occurred:
Apr 28 13:49:01 localhost patroni[988]: Traceback (most recent call last):
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 211, in _do_http_request
Apr 28 13:49:01 localhost patroni[988]:    response = request_executor(method, base_uri + path, **kwargs)
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 79, in request
Apr 28 13:49:01 localhost patroni[988]:    method, url, fields=fields, headers=headers, **urlopen_kw
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 170, in request_encode_body
Apr 28 13:49:01 localhost patroni[988]:    return self.urlopen(method, url, **extra_kw)
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 376, in urlopen
Apr 28 13:49:01 localhost patroni[988]:    response = conn.urlopen(method, u.request_uri, **kw)
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
Apr 28 13:49:01 localhost patroni[988]:    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
Apr 28 13:49:01 localhost patroni[988]:    raise MaxRetryError(_pool, url, error or ResponseError(cause))
Apr 28 13:49:01 localhost patroni[988]: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.16.18.133', port
=2379): Max retries exceeded with url: /v2/keys/service/postgres-cluster/members/pg-db1 (Caused by ReadTimeoutError("HTTPConnectionPool(host='10.16.18.133', port=2379): Read timed out. (read timeout=2.499780117010232)",))
Apr 28 13:49:01 localhost patroni[988]: During handling of the above exception, another exception occurred:
Apr 28 13:49:01 localhost patroni[988]: Traceback (most recent call last):
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 566, in wrapper
Apr 28 13:49:01 localhost patroni[988]:    retval = func(self, *args, **kwargs) is not None
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 659, in touch_member
Apr 28 13:49:01 localhost patroni[988]:    return self._client.set(self.member_path, data, None if permanent else self._ttl)
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 721, in set
Apr 28 13:49:01 localhost patroni[988]:    return self.write(key, value, ttl=ttl)
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/etcd/client.py", line 500, in write
Apr 28 13:49:01 localhost patroni[988]:    response = self.api_execute(path, method, params=params)
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 256, in api_execute
Apr 28 13:49:01 localhost patroni[988]:    response = self._do_http_request(retry, machines_cache, request_executor, method, path, **kwargs)
Apr 28 13:49:01 localhost patroni[988]:  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 230, in _do_http_request
Apr 28 13:49:01 localhost patroni[988]:    raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
Apr 28 13:49:01 localhost patroni[988]: etcd.EtcdException: PUT /v2/keys/service/postgres-cluster/members/pg-db1 request failed
Apr 28 13:49:01 localhost patroni[988]: 2022-04-28 13:49:01,050 INFO: no action. I am (pg-db1), a secondary, and following a leader (pg-db3)
Apr 28 13:49:01 localhost etcd[1078]: got unexpected response error (etcdserver: request timed out)
Apr 28 13:49:02 localhost etcd[1078]: 33070dbf2451ad42 [term: 261] received a MsgVote message with higher term from 99de4181ac8b022 [term: 262]
Apr 28 13:49:02 localhost etcd[1078]: 33070dbf2451ad42 became follower at term 262
Apr 28 13:49:02 localhost etcd[1078]: 33070dbf2451ad42 [logterm: 203, index: 16576203, vote: 0] cast MsgVote for 99de4181ac8b022 [logterm: 203, index: 16576203] at term 262
Apr 28 13:49:03 localhost etcd[1078]: health check for peer a5b9a4993cb72fad could not connect: dial tcp 10.16.18.134:2380: connect: no route to host (prober "ROUND_TRIPPER_RAFT_MESSAGE")
Apr 28 13:49:03 localhost etcd[1078]: health check for peer f12d636a65b65d2f could not connect: dial tcp 10.16.18.141:2380: connect: no route to host (prober "ROUND_TRIPPER_RAFT_MESSAGE")
Apr 28 13:49:03 localhost etcd[1078]: got unexpected response error (etcdserver: request timed out)
Apr 28 13:49:07 localhost etcd[1078]: 33070dbf2451ad42 is starting a new election at term 262
Apr 28 13:49:07 localhost etcd[1078]: 33070dbf2451ad42 became candidate at term 263
Apr 28 13:49:07 localhost etcd[1078]: 33070dbf2451ad42 received MsgVoteResp from 33070dbf2451ad42 at term 263
Apr 28 13:49:07 localhost etcd[1078]: 33070dbf2451ad42 [logterm: 203, index: 16576203] sent MsgVote request to a5b9a4993cb72fad at term 263
Apr 28 13:49:07 localhost etcd[1078]: 33070dbf2451ad42 [logterm: 203, index: 16576203] sent MsgVote request to f12d636a65b65d2f at term 263
Apr 28 13:49:07 localhost etcd[1078]: 33070dbf2451ad42 [logterm: 203, index: 16576203] sent MsgVote request to 99de4181ac8b022 at term 263
Apr 28 13:49:07 localhost etcd[1078]: 33070dbf2451ad42 received MsgVoteResp from 99de4181ac8b022 at term 263
Apr 28 13:49:07 localhost etcd[1078]: 33070dbf2451ad42 [quorum:3] has received 2 MsgVoteResp votes and 0 vote rejections
Apr 28 13:49:07 localhost etcd[1078]: got unexpected response error (etcdserver: request timed out)
Apr 28 13:49:08 localhost etcd[1078]: health check for peer a5b9a4993cb72fad could not connect: dial tcp 10.16.18.134:2380: connect: no route to host (prober "ROUND_TRIPPER_RAFT_MESSAGE")
Apr 28 13:49:08 localhost etcd[1078]: health check for peer f12d636a65b65d2f could not connect: dial tcp 10.16.18.141:2380: connect: no route to host (prober "ROUND_TRIPPER_RAFT_MESSAGE")
Apr 28 13:49:08 localhost patroni[988]: 2022-04-28 13:49:08,539 INFO: Selected new etcd server http://10.16.18.133:2379
Apr 28 13:49:11 localhost patroni[988]: 2022-04-28 13:49:08,542 INFO: Lock owner: pg-db3; I am pg-db1
Apr 28 13:49:11 localhost patroni[988]: 2022-04-28 13:49:11,047 INFO: Selected new etcd server http://10.16.18.135:2379
Apr 28 13:49:11 localhost patroni[988]: 2022-04-28 13:49:11,047 ERROR: Request to server http://10.16.18.133:2379 fail

root@pg-db1:keepalived# /usr/local/bin/patronictl list postgres-cluster
2022-04-28 14:42:52,915 - ERROR - Request to server http://10.16.18.141:2379 failed: MaxRetryError("HTTPConnectionPool(host='10.16.18.141', port=2379): Max retries exceeded with url: /v2/keys/service/postgres-cluster/?recursive=true (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fe4ce701d68>, 'Connection to 10.16.18.141 timed out. (connect timeout=1.25)'))",)

+--------------+----------------+---------+---------+----+-----------+
| Member       | Host           | Role    | State   | TL | Lag in MB |
+ Cluster: postgres-cluster (7068655480869002509) --+----+-----------+
| pg-db1 | 10.16.18.133 | Replica | running | 13 |         0 |
| pg-db2 | 10.16.18.134 | Replica | running | 13 |         0 |
| pg-db3 | 10.16.18.135 | Leader  | running | 13 |           |
+--------------+----------------+---------+---------+----+-----------+
