### ISSUE TITLE
patroni instalation

### ISSUE THREAD

**Issue by bj-pop** [zalando/patroni#2288]
**Describe the bug**
after fallowing the installation instruction i encountered

ModuleNotFoundError: No module named 'patroni.__main__'

**To Reproduce**
on ubuntu 20.04 installed with postgresql14

apt install python3-pip python3-dev libpq-dev -y
pip3 install --upgrade pip
pip install patroni
pip install python-etcd
pip install psycopg2

**Expected behavior**
● patroni.service - High availability PostgreSQL Cluster
     Loaded: loaded (/etc/systemd/system/patroni.service; disabled; vendor preset: enabled)
     Active: active (running) since 
 

**Screenshots**
siad@DB2:~$ sudo systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
     Loaded: loaded (/etc/systemd/system/patroni.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-05-04 16:42:44 CEST; 3s ago
    Process: 2233 ExecStart=/usr/local/bin/patroni /etc/patroni.yml (code=exited, status=1/FAILURE)
   Main PID: 2233 (code=exited, status=1/FAILURE)

May 04 16:42:43 DB2 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
May 04 16:42:44 DB2 patroni[2233]: Traceback (most recent call last):
May 04 16:42:44 DB2 patroni[2233]:   File "/usr/local/bin/patroni", line 5, in <module>
May 04 16:42:44 DB2 patroni[2233]:     from patroni.__main__ import main
May 04 16:42:44DB2 patroni[2233]: ModuleNotFoundError: No module named 'patroni.__main__'
May 04 16:42:44 DB2 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
May 04 16:42:44 DB2 systemd[1]: patroni.service: Failed with result 'exit-code'.

**Environment**
-root@DB2:~# patroni --version
patroni 2.1.3

- PostgreSQL version:
-  psql -V
psql (PostgreSQL) 14.2 (Ubuntu 14.2-1.pgdg20.04+1+b1)
- DCS (and its version):
etcd Version: 3.2.26

**Patroni configuration file**
```
scope: postgres
namespace: /patroni
name: postgresqldb2

restapi:
    listen: 10.x.x.x3:8008
    connect_address: 10.x.x.3:8008
etcd:
    host: 10.x.x.4:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.x.x.3/0 md5
    - host replication replicator 10..x.x.2/0 md5
  - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
             - createdb

postgresql:
   listen: 10.x.x.3:5432
    connect_address: 10.x.x.3:5432
    data_dir: /mydata
    pgpass: /tmp/pgpass
   authentication:
        replication:
            username: replicator
            password: password
        superuser:
            username: postgres
            password: password
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
   noloadbalance: false
    clonefrom: false
    nosync: false



```

**patronictl show-config**
```
patronictl show-config
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: etcd, etcd3, kubernetes'

```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
