### ISSUE TITLE
Patroni dynamicConfiguration error

### ISSUE THREAD

**Issue by Alepefe** [zalando/patroni#2294]
Hello guys,

I am using **patroni** on a **k8s v1.22.9** cluster.

One of our project's requirement is to use the **postgres 14** citus preloaded library.
*The citus library need to be the first of the directive **shared_preload_libraries** in the postgres configuration file.

In order to achieve that, I added some values to the dynamicConfiguraiton yaml file
```
      postgresql:
        # custom_conf : /opt/custom-postgresql.conf
        parameters:
          shared_preload_libraries: citus,pgaudit,pg_stat_statements,pgnodemx
          shared_buffers: 256MB
```

After applying the new configuration postgres doesnt boot as the citus extension was not the first library loaded.
The problem is that the value of 
`
shared_preload_libraries: citus,pgaudit,pg_stat_statements,pgnodemx
`
what really does is concatenate pgaudit plus your custom value, the result is:
`shared_preload_libraries = pgaudit, citus,pgaudit,pg_stat_statements,pgnodemx`
Thats why the postgres server boot fails.

I also tried defining a custom postgres configuration `custom_conf : /opt/custom-postgresql.conf` but It didnt work either.

Is there any way to solve this problem?

Thank you,
Alepefe
