### ISSUE TITLE
Bootstrap patroni cluster from wal-g base backup

### ISSUE THREAD

**Issue by manish-k-sharma** [zalando/patroni#2319]
Hi,
I'm trying to restore a patroni cluster using the base backups created by another patroni cluster using wal-g to do restoration tests. I'm unable to restore this using only the base backup. I don't want to use the WAL files as they're huge.

Can someone suggest to me if it is even possible and if yes, what's the right configuration to do it?

My patroni configuration looks like below
```
method: bootstrap_with_walg
bootstrap_with_walg:
    command: /data/conf/wal-backup-fetch.sh
    keep_existing_recovery_conf: True
    recovery_conf:
        recovery_target_action: promote
        recovery_target_timeline: latest
        restore_command: /data/conf/wal-restore-command.sh "%f" "%p"
```

`wal-backup-fetch.sh` pulls the latest available wal-backup
```
wal-g backup-fetch /data/postgresql/current LATEST
```

`wal-restore-command` pull wal files
```
wal-g wal-fetch "$1" "$2"
```

The backups listed with wal-g are
```
name                          modified             wal_segment_backup_start
base_00000054000000FB000000D1 2022-05-23T05:36:03Z 00000054000000FB000000D1
```

I tried changing the `recovery_target_timeline` to different values but didn't help.
Also tried to remove the `recovery_conf` settings to bootstrap only from the base backup but the postgres server keeps failing. Also, tried changing the `restore_command` to `exit 0` but that didn't help too.

The most common error is below
```
t=2022-05-26 09:57:49.153 GMT u= db= pid=[594]: FATAL:  could not locate required checkpoint record
t=2022-05-26 09:57:49.153 GMT u= db= pid=[594]: HINT:  If you are restoring from a backup, touch "/data/postgresql/current/recovery.signal" and add required recovery options.
	If you are not restoring from a backup, try removing the file "/data/postgresql/current/backup_label".
```

Thanks in advance
