### ISSUE TITLE
Question about custom bootstrap and dynamic configuration (patroni.dynamic.json) restore

### ISSUE THREAD

**Issue by alago197** [zalando/patroni#2320]
Hi, just a quick question.

Yesterday I've had to restore via pgBackRest a cluster - PostgreSQL 10, Patroni 1.5.0, etcd 3.2.18. I've done the restore via the custom bootstrap method and all went ok.  

But after restoring, once the custom bootstrap script returned ok to patroni, I've seen patroni overwrote the (restored in PGDATA by the previous pgBackRest restore) patroni.dynamic.json dynamic config file that was present, replacing it by one with a minimal content:

   ```
ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true

```
Seeing this, I just entered again my actual config (the one that was present in the restored (by pgbackrest) "patroni.dynamic.json", before the overwrite), via patronictl edit-config, and problem was just solved. The problem was that that minimal config didn't included for example the postgresql logging configuration, or the continuous archiving configuration, so I've lost some details of log info regarding the WAL archives applied after the restore, etc. 

The initial YAML config (in /etc/patroni) I have (I didn't touched it yet) didn't included the logging, archiving (and other params I've added exclusively via the dynamic configuration, through these years) (the custom bootstrap section was added just before the restore)

```
bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  method: pgbackrest
  pgbackrest:
    command:  /var/lib/postgresql/custom_bootstrap.sh
    keep_existing_recovery_conf: True
    no_params: False
    recovery_conf:
      recovery_target_timeline: latest
      recovery_target_action: promote
      restore_command:  pgbackrest --repo1-path=/tmp/pgcluster  --stanza=dbcluster archive-get %f %p
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true

      parameters:
 #       wal_level: hot_standby
 #       hot_standby: "on"
        wal_keep_segments: 100
 #       max_wal_senders: 5
 #       max_replication_slots: 5
 #       wal_log_hints: "on"
#       archive_mode: "on"
#        archive_timeout: 1800s
#        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
#      recovery_conf:
#        restore_command: cp ../wal_archive/%f %p
------------

```
I understand that if I had entered in the static config that parameters (before the restore), patroni would of course read them. What I would like to confirm is that, after the initial patroni startup just after a custom bootstrap (involving a full pgbackrest restore, as it was my case), Patroni don't loads any dynamic configuration file present in PGDATA (restored by pgbackrest, along the rest of the files of the database), but instead uses the static configuration file. Is that correct, is that an expected behavior?
