### ISSUE TITLE
A Patroni standby cluster assumes that a postgresql.conf should exist in the source server's PGDATA

### ISSUE THREAD

**Issue by victor-sudakov** [zalando/patroni#2337]
**Describe the bug**
A Patroni standby cluster assumes that a postgresql.conf should exist  in the source server's PGDATA, and refuses to start if it does not find it in the basebackup'ed directory.

**To Reproduce**
1. Configure a PostgreSQL server A with a postgresql.conf elsewhere (not within its PGDATA).
2. Create a Patroni cluster B as a standby to A.
3. Cluster B will perform a basebackup from A and then refuse to start. See the attached [fail.log](https://github.com/zalando/patroni/files/8911213/fail.log)

**Workaround**
Create an empty postgresql.conf in A's PGDATA

**Expected behavior**
Patroni should not assume that a postgresql.conf exists in A's PGDATA because it's often not the case. For example in Debian its always in `/etc/postgresql/$version/$clustername`

**Environment**
- Patroni version: patroni/buster-pgdg,now 2.1.3-2.pgdg100+1
- PostgreSQL version: 13.7
- DCS (and its version): consul 1.12.2

**Patroni configuration file**
The relevant part:
```YAML
bootstrap:
  initdb:
    - encoding: UTF-8
    - locale: C.UTF-8
    - data-checksums
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_node_count: 3
    standby_cluster:
      host: 127.0.0.1
      port: 5444
      primary_slot_name: patroni
postgresql:
  create_replica_method:
    - basebackup
  basebackup:
    checkpoint: 'fast'
```
**Have you checked Patroni logs?**
See the attached [fail.log](https://github.com/zalando/patroni/files/8911213/fail.log)
