### ISSUE TITLE
post_init script does not get called on re-install/restart

### ISSUE THREAD

**Issue by udesaiitrs** [zalando/patroni#2355]
**Describe the bug**
We have a timescale cluster running on Kubernetes where we are seeing some unexpected behavior. When installing the cluster fresh, the `post_init` script runs as expected. We have some `CREATE TABLESPACE` calls in that script. However, when uninstalling the cluster and then re-installing it via helm without deleting PVCs, we see that the `post_init` script is never called. Is this expected? 

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 14.1
- DCS (and its version):

**Patroni configuration file**
```
  patroni.yaml: |
    bootstrap:
      dcs:
        loop_wait: 10
        ttl: 30
        retry_timeout: 10
        maximum_lag_on_failover: 33554432
        postgresql:
          parameters:
            archive_command: /etc/timescaledb/scripts/pgbackrest_archive.sh %p
            archive_mode: "on"
            archive_timeout: 1800s
            autovacuum_analyze_scale_factor: 0.02
            autovacuum_max_workers: 10
            autovacuum_naptime: 120s
            autovacuum_vacuum_cost_limit: 500
            autovacuum_vacuum_scale_factor: 0.2
            dynamic_shared_memory_type: "sysv"
            hot_standby: "on"
            log_autovacuum_min_duration: 1000
            log_checkpoints: "on"
            log_connections: "on"
            log_disconnections: "on"
            log_line_prefix: '%m: %u@%d,app=%a '
            log_lock_waits: "on"
            log_min_duration_statement: 1s
            log_replication_commands: "on"
            log_statement: none
            max_connections: {{ .Values.timescale.maxConnections }}
            max_parallel_workers: 20
            max_prepared_transactions: 150
            max_worker_processes: 40
            max_standby_archive_delay: 120s
            max_standby_streaming_delay: 120s
            pg_stat_statements.max: 1000
            pljava.java_thread_pg_entry: 'throw'
            pljava.vmoptions: '{{ .Values.timescale.pljavaJvmOptions }}'
            shared_preload_libraries: timescaledb,pg_stat_statements
            synchronous_commit: local
            tcp_keepalives_idle: 900
            tcp_keepalives_interval: 100
            temp_file_limit: 20GB
            timescaledb.max_background_workers: 20
            timescaledb.passfile: ../.pgpass
            timescaledb.telemetry_level: 'off'
            unix_socket_directories: /var/run/postgresql
            unix_socket_permissions: "0750"
            wal_level: "replica"
            wal_log_hints: "on"
            wal_compression: "true"
      method: restore_or_initdb
      post_init: /etc/timescaledb/scripts/post_init.sh
      restore_or_initdb:
        command: |
          /etc/timescaledb/scripts/restore_or_initdb.sh --encoding=UTF8 --locale=C.UTF-8
        keep_existing_recovery_conf: true
    kubernetes:
      role_label: obcerv.itrsgroup.com/timescale-role
      scope_label: obcerv.itrsgroup.com/timescale-cluster
      use_endpoints: true
    log:
      level: INFO
    postgresql:
      authentication:
        replication:
          username: standby
        superuser:
          username: postgres
      basebackup:
      - waldir: /var/lib/postgresql/wal/pg_wal
      callbacks:
        on_reload: /etc/timescaledb/scripts/patroni_callback.sh
        on_restart: /etc/timescaledb/scripts/patroni_callback.sh
        on_role_change: /etc/timescaledb/scripts/patroni_callback.sh
        on_start: /etc/timescaledb/scripts/post_init.sh
        on_stop: /etc/timescaledb/scripts/patroni_callback.sh
      create_replica_methods:
      - basebackup
      listen: 0.0.0.0:5432
      pg_hba:
      - local     all             postgres                              peer
      - local     all             all                                   md5
      - host      all             all                127.0.0.1/32       md5
      - host      all             all                ::1/128            md5
      - host      replication     standby            all                md5
      - host      all             all                all                md5
      recovery_conf:
        restore_command: /etc/timescaledb/scripts/pgbackrest_archive_get.sh %f "%p"
      use_unix_socket: true
    restapi:
      listen: 0.0.0.0:8008
```

**patronictl show-config**
```
{}
```
