### ISSUE TITLE
Pure raft doesn't switch

### ISSUE THREAD

**Issue by AlexFavre** [zalando/patroni#2394]
**Describe the bug**
Raft leader doesn't switch also the Postgres leader switch in RO mode
We have four node for raft (two dedicated and two with postgres)

**To Reproduce**
have a raft folder without space

**Expected behavior**
The folder of our raft leader has been full (no space left) also the raft cluster have wait the previous leader and Patroni cluster fall in error (leader in RO mode and Replica can't start).

To fix this issue we have increase space of raft folder but we think it's not the best way.
How we can purge raft file to save space ?
Why raft cluster doesn't switch? 

**Environment**
- Patroni version:2.1.4
- PostgreSQL version:13.7
- DCS (and its version): pure Raft version 0.3.8

**Patroni configuration file**

```
cat /etc/patroni/patroni.yml
scope: PGSQLGrafanaProd
namespace: /PGSQLGrafana/
name: PGSQLGrafanaProd1

restapi:
  listen: 1.1.1.1:8008
  connect_address: 1.1.1.1:8008

raft:
  data_dir: /apps/pgsql/raft
  self_addr: 1.1.1.1:5010
  partner_addrs: ['1.1.1.2:5010','1.1.1.3:5010','1.1.1.4:5010']

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
        fsync: 'on'
        hot_standby: 'on'
        max_replication_slots: 30
        max_wal_senders: 30
        primary_slot_name: replica_grafana
        synchronous_commit: 'off'
        synchronous_standby_names: `'*'`
        max_connections: '2000'
        wal_level: hot_standby

  initdb:
   - encoding: UTF8
   - data-checksums

postgresql:
  listen: 1.1.1.1:5432
  connect_address: 1.1.1.1:5432
  data_dir: /apps/pgsql/data
  bin_dir: /usr/pgsql-13/bin
  pgpass: /tmp/pgpass
  
   
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    fsync: 'on'
    hot_standby: 'on'
    max_connections: '2000'
    max_replication_slots: 30
    max_wal_senders: 30
    primary_slot_name: replica_grafana
    synchronous_commit: 'off'
    synchronous_standby_names: '*'
    wal_level: hot_standby
  use_pg_rewind: true
retry_timeout: 10
ttl: 30

```

**Have you checked Patroni logs?**
Before crash:
Aug 22 20:39:51 s01vl9950891 systemd[1]: patroni.service: Failed with result 'signal'.
Aug 22 20:39:51 s01vl9950891 systemd[1]: patroni.service: Main process exited, code=killed, status=11/SEGV
Aug 22 20:39:46 s01vl9950891 patroni[1906]: 2022-08-22 20:39:46,414 INFO: no action. I am (PGSQLGrafanaProd1), the leader with the lock
Aug 22 20:39:45 s01vl9950891 patroni[1906]: 2022-08-22 20:39:45,672 WARNING: Failed to store full dump
Aug 22 20:39:40 s01vl9950891 patroni[1906]: 2022-08-22 20:39:40,751 WARNING: Failed to store full dump
Aug 22 20:39:36 s01vl9950891 patroni[1906]: 2022-08-22 20:39:36,413 INFO: no action. I am (PGSQLGrafanaProd1), the leader with the lock
Aug 22 20:39:35 s01vl9950891 patroni[1906]: 2022-08-22 20:39:35,927 WARNING: Failed to store full dump
Aug 22 20:39:30 s01vl9950891 patroni[1906]: 2022-08-22 20:39:30,973 WARNING: Failed to store full dump

When we have try to run daemon manually:
Aug 23 09:47:46 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:46,564 WARNING: Loop time exceeded, rescheduling immediately.
Aug 23 09:47:46 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:46,562 INFO: starting after demotion in progress
Aug 23 09:47:46 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:34,561 INFO: Lock owner: PGSQLGrafanaProd1; I am PGSQLGrafanaProd1
Aug 23 09:47:44 s01vl9950891 patroni[1212815]: 10.244.120.156:5432 - accepting connections
Aug 23 09:47:42 s01vl9950891 patroni[1212815]: 10.244.120.156:5432 - rejecting connections
Aug 23 09:47:41 s01vl9950891 patroni[1212815]: 10.244.120.156:5432 - rejecting connections
Aug 23 09:47:40 s01vl9950891 patroni[1212815]: 10.244.120.156:5432 - rejecting connections
Aug 23 09:47:39 s01vl9950891 patroni[1212815]: 10.244.120.156:5432 - rejecting connections
Aug 23 09:47:38 s01vl9950891 patroni[1212815]: 10.244.120.156:5432 - rejecting connections
Aug 23 09:47:37 s01vl9950891 patroni[1212815]: 10.244.120.156:5432 - rejecting connections
Aug 23 09:47:36 s01vl9950891 patroni[1212815]: 10.244.120.156:5432 - rejecting connections
Aug 23 09:47:36 s01vl9950891 patroni[1212815]: 10.244.120.156:5432 - rejecting connections
Aug 23 09:47:35 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:35.222 CEST [1212938] HINT:  Future log output will appear in directory "/apps/pgsql/log".
Aug 23 09:47:35 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:35.222 CEST [1212938] LOG:  redirecting log output to logging collector process
Aug 23 09:47:35 s01vl9950891 patroni[1212815]: 10.244.120.156:5432 - no response
Aug 23 09:47:35 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:35,064 INFO: postmaster pid=1212938
Aug 23 09:47:34 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:34,561 WARNING: Loop time exceeded, rescheduling immediately.
Aug 23 09:47:34 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:34,560 INFO: closed patroni connection to the postgresql cluster
Aug 23 09:47:34 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:34,559 INFO: demoted self because failed to update leader lock in DCS
Aug 23 09:47:32 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:32,324 INFO: Demoting self (immediate-nolock)
Aug 23 09:47:32 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:32,324 ERROR: failed to update leader lock
Aug 23 09:47:32 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:22,322 INFO: Lock owner: PGSQLGrafanaProd1; I am PGSQLGrafanaProd1
Aug 23 09:47:22 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:22,205 INFO: establishing a new patroni connection to the postgres cluster
Aug 23 09:47:22 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:22,100 INFO: No PostgreSQL configuration items changed, nothing to reload.
Aug 23 09:47:22 s01vl9950891 patroni[1212815]: OSError: [Errno 28] No space left on device
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     self.__incomingTransmissionFile.close()
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/var/lib/pgsql/.local/lib/python3.6/site-packages/pysyncobj/serializer.py", line 193, in setTransmissionData
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     if self.__serializer.setTransmissionData(serialized):
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/var/lib/pgsql/.local/lib/python3.6/site-packages/pysyncobj/syncobj.py", line 896, in __onMessageReceived
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     self._onMessageReceivedCallback(node, message)
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/var/lib/pgsql/.local/lib/python3.6/site-packages/pysyncobj/transport.py", line 107, in _onMessageReceived
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     self.__onMessageReceived(message)
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/var/lib/pgsql/.local/lib/python3.6/site-packages/pysyncobj/tcp_connection.py", line 173, in __processConnection
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     self.__descrToCallbacks[descr](descr, eventMask)
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/var/lib/pgsql/.local/lib/python3.6/site-packages/pysyncobj/poller.py", line 97, in poll
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     self._poller.poll(timeToWait)
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/var/lib/pgsql/.local/lib/python3.6/site-packages/pysyncobj/syncobj.py", line 616, in _onTick
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     super(DynMemberSyncObj, self)._onTick(timeToWait)
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/usr/lib/python3.6/site-packages/patroni/dcs/raft.py", line 84, in _onTick
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     super(KVStoreTTL, self)._onTick(timeToWait)
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/usr/lib/python3.6/site-packages/patroni/dcs/raft.py", line 238, in _onTick
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     self._onTick(timeToWait)
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/var/lib/pgsql/.local/lib/python3.6/site-packages/pysyncobj/syncobj.py", line 532, in doTick
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     self.doTick(self.conf.autoTickPeriod)
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/usr/lib/python3.6/site-packages/patroni/dcs/raft.py", line 248, in _autoTickThread
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     self._target(*self._args, **self._kwargs)
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/usr/lib64/python3.6/threading.py", line 867, in run
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:     self.run()
Aug 23 09:47:22 s01vl9950891 patroni[1212815]:   File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
Aug 23 09:47:22 s01vl9950891 patroni[1212815]: Traceback (most recent call last):
Aug 23 09:47:22 s01vl9950891 patroni[1212815]: Exception in thread Thread-2:
Aug 23 09:47:17 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:17,084 INFO: waiting on raft
Aug 23 09:47:12 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:12,071 INFO: waiting on raft
Aug 23 09:47:07 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:07,060 INFO: waiting on raft
Aug 23 09:47:02 s01vl9950891 patroni[1212815]: 2022-08-23 09:47:02,049 INFO: waiting on raft

**Have you checked PostgreSQL logs?**
When we trying to start patroni manually
2022-08-23 09:47:32.505 CEST [1965] LOG:  received immediate shutdown request
2022-08-23 09:47:32.515 CEST [1766065] WARNING:  terminating connection because of crash of another server process
2022-08-23 09:47:32.515 CEST [1766065] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2022-08-23 09:47:32.515 CEST [1766065] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2022-08-23 09:47:32.516 CEST [1212898] WARNING:  terminating connection because of crash of another server process
2022-08-23 09:47:32.516 CEST [1212898] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2022-08-23 09:47:32.516 CEST [1212898] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2022-08-23 09:47:32.541 CEST [1965] LOG:  database system is shut down
2022-08-23 09:47:35.222 CEST [1212938] LOG:  starting PostgreSQL 13.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4), 64-bit
2022-08-23 09:47:35.222 CEST [1212938] LOG:  listening on IPv4 address "1.1.1.1", port 5432
2022-08-23 09:47:35.229 CEST [1212938] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-08-23 09:47:35.244 CEST [1212938] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-08-23 09:47:35.274 CEST [1212941] LOG:  database system was interrupted; last known up at 2022-08-22 23:59:43 CEST
2022-08-23 09:47:36.270 CEST [1212946] FATAL:  the database system is starting up
2022-08-23 09:47:36.297 CEST [1212947] FATAL:  the database system is starting up
2022-08-23 09:47:36.300 CEST [1212948] FATAL:  the database system is starting up
2022-08-23 09:47:36.370 CEST [1212950] FATAL:  the database system is starting up
2022-08-23 09:47:37.425 CEST [1212955] FATAL:  the database system is starting up
2022-08-23 09:47:37.473 CEST [1212956] FATAL:  the database system is starting up
2022-08-23 09:47:38.573 CEST [1212958] FATAL:  the database system is starting up
2022-08-23 09:47:39.046 CEST [1212961] FATAL:  the database system is starting up
2022-08-23 09:47:39.678 CEST [1212964] FATAL:  the database system is starting up
2022-08-23 09:47:39.854 CEST [1212966] FATAL:  the database system is starting up
2022-08-23 09:47:40.778 CEST [1212974] FATAL:  the database system is starting up
2022-08-23 09:47:41.881 CEST [1212978] FATAL:  the database system is starting up
2022-08-23 09:47:42.985 CEST [1212981] FATAL:  the database system is starting up
2022-08-23 09:47:43.277 CEST [1212941] WARNING:  specified neither primary_conninfo nor restore_command
2022-08-23 09:47:43.277 CEST [1212941] HINT:  The database server will regularly poll the pg_wal subdirectory to check for files placed there.
2022-08-23 09:47:43.277 CEST [1212941] LOG:  entering standby mode
2022-08-23 09:47:43.283 CEST [1212941] LOG:  database system was not properly shut down; automatic recovery in progress
2022-08-23 09:47:43.291 CEST [1212941] LOG:  redo starts at 7/36F9E640
2022-08-23 09:47:43.291 CEST [1212941] LOG:  invalid record length at 7/36F9E728: wanted 24, got 0
2022-08-23 09:47:43.333 CEST [1212941] LOG:  consistent recovery state reached at 7/36F9E728
2022-08-23 09:47:43.334 CEST [1212938] LOG:  database system is ready to accept read only connections
2022-08-23 09:47:51.363 CEST [1212991] ERROR:  cannot set transaction read-write mode during recovery
2022-08-23 09:47:51.363 CEST [1212991] STATEMENT:  BEGIN READ WRITE

**Have you tried to use GitHub issue search?**
nothing has been found
