### ISSUE TITLE
Replica node keep restarting endlessly

### ISSUE THREAD

**Issue by dbaasvc** [zalando/patroni#2412]
**Describe the bug**
After initial bootstrap of the primary server, next replica node keeps getting restarted endlessly 

**To Reproduce**
  Configuring patroni as per the doc  
**Expected behavior**
After the initial primary setup , all other node should be joining as Replica node and should be up and running instead of restarting every second 

**Screenshots**
![image](https://user-images.githubusercontent.com/37077814/189426585-1215ce9b-627c-444c-ba69-053fd9dd8ec4.png)
![image](https://user-images.githubusercontent.com/37077814/189426772-e934b71e-6626-4670-9f98-9c01d4dec792.png)
![image](https://user-images.githubusercontent.com/37077814/189426924-8f2134e6-e4aa-484a-a33e-4fbeec5da9b1.png)

**Environment**
- Patroni version: 2.1.4
- PostgreSQL version: 11.9/11.17
- DCS (and its version): etcd v3 

**Patroni configuration file**
```
scope: devdb
#namespace: /service/
name: pgptrnynd01

log:
  dir: /apps/pgsql/pghome/patroni/log
  file_num: 8

restapi:
  listen: pgptrnynd01:8080
  connect_address: pgptrnynd01:8080
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

# ctl:
#   insecure: false # Allow connections to SSL sites without certs
#   certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#   cacert: /etc/ssl/certs/ssl-cacert-snakeoil.pem

etcd3:
  #Provide host to do the initial discovery of the cluster topology:
    hosts: 192.168.1.34:9432,192.168.1.35:9432,192.168.1.36:9432

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 120
    maximum_lag_on_failover: 1048576
    max_timelines_history: 10
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_keep_segments: 1000
        archive_command: 'test ! -f /apps/pgsql/pgarchive/devdb/%f && cp %p /apps/pgsql/pgarchive/devdb/%f'
      recovery_conf:
        restore_command:
  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - locale: en_US.UTF-8
  - waldir: /apps/pgsql/pgwal/devdb
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  # For kerberos gss based connectivity (discard @.*$)
  #- host replication replicator 127.0.0.1/32 gss include_realm=0
  #- host all all 0.0.0.0/0 gss include_realm=0
  - local replication all                       trust
  - host replication  all       127.0.0.1/32    ident
  - host replication  all       0.0.0.0/0        md5
  - host   all        all       0.0.0.0/0        md5
#  - hostssl all       all       0.0.0.0/0        md5


  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

  # Some additional users users which needs to be created after initializing new cluster
#  users:
#    admin:
#      password: admin%
#      options:
#        - createrole
#        - createdb

postgresql:
  listen: 'pgptrnynd01:9432'
  port: 9432
  connect_address: 'pgptrnynd01:9432'
  data_dir: /apps/pgsql/pgdata01/devdb
  bin_dir: /usr/pgsql-11/bin
#  config_dir:
  pgpass: /apps/pgsql/pghome/.config/patroni/.pgpass
  basebackup:
    - checkpoint: 'fast'
    - waldir: /apps/pgsql/pgwal/devdb
  authentication:
    replication:
      username: postgres
      password: pg123
    superuser:
      username: postgres
      password:  pg123
    rewind:  # Has no effect on postgres 10 and lower
      username: postgres
  # Server side kerberos spn
#  krbsrvname: postgres
  parameters: 
    shared_buffers: "1024MB"
    wal_sync_method: "fsync"
    logging_collector: "on"
    max_connections: 100
    port: 9432
    shared_preload_libraries: "repmgr,pg_stat_statements"
    min_wal_size: "256MB"
    max_wal_size: "16GB"
    work_mem: "8MB"
    random_page_cost: 2
    effective_io_concurrency: 200
    effective_cache_size: "3072MB"
    maintenance_work_mem: "512MB"
    log_min_duration_statement: 2000
    autovacuum_vacuum_threshold: 25
    autovacuum_vacuum_scale_factor: "0.1"
    autovacuum_analyze_scale_factor: "0.05"
    autovacuum_analyze_threshold: 10
    autovacuum_vacuum_cost_limit: 1000
    autovacuum_vacuum_cost_delay: "-1"
    log_line_prefix: "%m [%p] :[%e]:"
    # Fully qualified kerberos ticket file for the running user
    # same as KRB5CCNAME used by the GSS
#   krb_server_keyfile: /var/spool/keytabs/postgres
    #unix_socket_directories: '..'  # parent directory of data_dir
  # Additional fencing script executed after acquiring the leader lock but before promoting the replica
  #pre_promote: /path/to/pre_promote.sh

watchdog:
  mode: automatic # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

```

**patronictl show-config**
```
loop_wait: 10
max_timelines_history: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: test ! -f /apps/pgsql/pgarchive/devdb/%f && cp %p /apps/pgsql/pgarchive/devdb/%f
    wal_keep_segments: 1000
  recovery_conf:
    restore_command: null
  use_pg_rewind: true
  use_slots: true
retry_timeout: 120
ttl: 30
```

**Have you checked Patroni logs? Yes 

2022-09-10 00:16:36,370 INFO: Lock owner: pgptrnynd02; I am pgptrnynd01
2022-09-10 00:16:36,390 INFO: Local timeline=3 lsn=0/3039CA8
2022-09-10 00:16:36,405 INFO: master_timeline=4
2022-09-10 00:16:36,406 INFO: master: history=1 0/3000060       no recovery target specified
2       0/30202D0       no recovery target specified
3       0/3039CA8       no recovery target specified
2022-09-10 00:16:36,419 INFO: running pg_rewind from pgptrnynd02
2022-09-10 00:16:36,426 INFO: running pg_rewind from dbname=postgres user=postgres host=pgptrnynd02 port=9432 target_session_attrs=read-write
2022-09-10 00:16:37,467 INFO: pg_rewind exit code=0
2022-09-10 00:16:37,467 INFO:  stdout=servers diverged at WAL location 0/3039CA8 on timeline 3
rewinding from last common checkpoint at 0/3039C00 on timeline 3
Done!

2022-09-10 00:16:37,467 INFO:  stderr=
2022-09-10 00:16:37,468 WARNING: Postgresql is not running.
2022-09-10 00:16:37,468 INFO: Lock owner: pgptrnynd02; I am pgptrnynd01
2022-09-10 00:16:37,471 INFO: pg_controldata:
  pg_control version number: 1100
  Catalog version number: 201809051
  Catalog version number: 201809051
  Database system identifier: 7141442446275665675
  Database cluster state: in archive recovery
  pg_control last modified: Sat Sep 10 00:15:18 2022
  Latest checkpoint location: 0/3039D10
  Latest checkpoint's REDO location: 0/3039CD8
  Latest checkpoint's REDO WAL file: 000000040000000000000003
  Latest checkpoint's TimeLineID: 4
  Latest checkpoint's PrevTimeLineID: 4
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:582
  Latest checkpoint's NextOID: 32768
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 562
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 582
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Sat Sep 10 00:15:18 2022
  Fake LSN counter for unlogged rels: 0/1
  Minimum recovery ending location: 0/3056200
  Min recovery ending loc's timeline: 4
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: replica
  wal_log_hints setting: on
  max_connections setting: 100
  max_worker_processes setting: 8

 max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float4 argument passing: by value
  Float8 argument passing: by value
  Data page checksum version: 0
  Mock authentication nonce: c5d70010850a8a42b47d2e471f7e93050482f8c3c1c1d095833d37426474942a

2022-09-10 00:16:37,472 INFO: Lock owner: pgptrnynd02; I am pgptrnynd01
2022-09-10 00:16:37,473 INFO: starting as a secondary
2022-09-10 00:16:37,946 INFO: postmaster pid=1497
2022-09-10 00:16:39,011 INFO: Lock owner: pgptrnynd02; I am pgptrnynd01
2022-09-10 00:16:39,012 INFO: establishing a new patroni connection to the postgres cluster
2022-09-10 00:16:39,049 INFO: no action. I am (pgptrnynd01), a secondary, and following a leader (pgptrnynd02)
2022-09-10 00:16:39,181 INFO: closed patroni connection to the postgresql cluster
2022-09-10 00:16:39,171 INFO: Lock owner: pgptrnynd02; I am pgptrnynd01
2022-09-10 00:16:39,225 INFO: changing primary_conninfo and restarting in progress
2022-09-10 00:16:39,511 INFO: postmaster pid=1519
2022-09-10 00:16:40,573 INFO: Lock owner: pgptrnynd02; I am pgptrnynd01
2022-09-10 00:16:40,573 INFO: establishing a new patroni connection to the postgres cluster
2022-09-10 00:16:40,580 INFO: Local timeline=4 lsn=0/3056E28
2022-09-10 00:16:40,593 INFO: master_timeline=4
2022-09-10 00:16:40,610 INFO: no action. I am (pgptrnynd01), a secondary, and following a leader (pgptrnynd02)
2022-09-10 00:16:40,735 INFO: closed patroni connection to the postgresql cluster
2022-09-10 00:16:41,076 INFO: postmaster pid=1541
2022-09-10 00:16:41,115 INFO: Lock owner: pgptrnynd02; I am pgptrnynd01
2022-09-10 00:16:41,115 INFO: establishing a new patroni connection to the postgres cluster
2022-09-10 00:16:41,120 INFO: Local timeline=4 lsn=0/3056E28
2022-09-10 00:16:41,132 INFO: master_timeline=4
2022-09-10 00:16:41,142 INFO: no action. I am (pgptrnynd01), a secondary, and following a leader (pgptrnynd02)
2022-09-10 00:16:41,265 INFO: closed patroni connection to the postgresql cluster
2022-09-10 00:16:41,685 INFO: postmaster pid=1561
2022-09-10 00:16:41,726 INFO: Lock owner: pgptrnynd02; I am pgptrnynd01
2022-09-10 00:16:41,726 INFO: establishing a new patroni connection to the postgres cluster
2022-09-10 00:16:41,731 INFO: Local timeline=4 lsn=0/3056E28
2022-09-10 00:16:41,741 INFO: master_timeline=4
2022-09-10 00:16:41,752 INFO: no action. I am (pgptrnynd01), a secondary, and following a leader (pgptrnynd02)
2022-09-10 00:16:41,881 INFO: closed patroni connection to the postgresql cluster
2022-09-10 00:16:42,207 INFO: postmaster pid=1581
2022-09-10 00:16:43,255 INFO: Lock owner: pgptrnynd02; I am pgptrnynd01
2022-09-10 00:16:43,255 INFO: establishing a new patroni connection to the postgres cluster
2022-09-10 00:16:43,261 INFO: Local timeline=4 lsn=0/3056E28
2022-09-10 00:16:43,273 INFO: master_timeline=4
2022-09-10 00:16:43,285 INFO: no action. I am (pgptrnynd01), a secondary, and following a leader (pgptrnynd02)
2022-09-10 00:16:43,412 INFO: closed patroni connection to the postgresql cluster
2022-09-10 00:16:43,739 INFO: postmaster pid=1603
2022-09-10 00:16:44,788 INFO: Lock owner: pgptrnynd02; I am pgptrnynd01
2022-09-10 00:16:44,788 INFO: establishing a new patroni connection to the postgres cluster
2022-09-10 00:16:44,794 INFO: Local timeline=4 lsn=0/3056E28
2022-09-10 00:16:44,805 INFO: master_timeline=4
2022-09-10 00:16:44,816 INFO: no action. I am (pgptrnynd01), a secondary, and following a leader (pgptrnynd02)
2022-09-10 00:16:44,942 INFO: closed patroni connection to the postgresql cluster

**Have you checked PostgreSQL logs?Yes 
2022-09-10 00:15:18.766 IST [12361] :[57P01]:FATAL:  terminating walreceiver process due to administrator command
2022-09-10 00:15:18.767 IST [12355] :[00000]:LOG:  redo done at 0/3039C70
2022-09-10 00:15:18.768 IST [12355] :[00000]:LOG:  selected new timeline ID: 4
2022-09-10 00:15:18.800 IST [12355] :[00000]:LOG:  archive recovery complete
2022-09-10 00:15:18.808 IST [12352] :[00000]:LOG:  database system is ready to accept connections
2022-09-10 00:16:38.148 IST [1500] :[00000]:LOG:  database system was interrupted while in recovery at log time 2022-09-10 00:15:18 IST
2022-09-10 00:16:38.148 IST [1500] :[00000]:HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
2022-09-10 00:16:38.161 IST [1500] :[00000]:LOG:  entering standby mode
2022-09-10 00:16:38.163 IST [1500] :[00000]:LOG:  redo starts at 0/3039BC8
2022-09-10 00:16:38.165 IST [1500] :[00000]:LOG:  consistent recovery state reached at 0/3056200
2022-09-10 00:16:38.165 IST [1500] :[00000]:LOG:  invalid record length at 0/3056200: wanted 24, got 0
2022-09-10 00:16:38.166 IST [1497] :[00000]:LOG:  database system is ready to accept read only connections
2022-09-10 00:16:38.174 IST [1504] :[XX000]:FATAL:  could not start WAL streaming: ERROR:  replication slot "pgptrnynd01" does not exist
2022-09-10 00:16:38.182 IST [1505] :[XX000]:FATAL:  could not start WAL streaming: ERROR:  replication slot "pgptrnynd01" does not exist
2022-09-10 00:16:39.160 IST [1497] :[00000]:LOG:  received fast shutdown request
2022-09-10 00:16:39.161 IST [1497] :[00000]:LOG:  aborting any active transactions
2022-09-10 00:16:39.164 IST [1510] :[57P01]:FATAL:  terminating connection due to administrator command
2022-09-10 00:16:39.166 IST [1501] :[00000]:LOG:  shutting down
2022-09-10 00:16:39.177 IST [1497] :[00000]:LOG:  database system is shut down
2022-09-10 00:16:39.539 IST [1522] :[00000]:LOG:  database system was shut down in recovery at 2022-09-10 00:16:39 IST
2022-09-10 00:16:39.539 IST [1522] :[00000]:LOG:  entering standby mode
2022-09-10 00:16:39.540 IST [1523] :[57P03]:FATAL:  the database system is starting up
2022-09-10 00:16:39.547 IST [1522] :[00000]:LOG:  redo starts at 0/3039CD8
2022-09-10 00:16:39.548 IST [1522] :[00000]:LOG:  consistent recovery state reached at 0/3056200
2022-09-10 00:16:39.548 IST [1522] :[00000]:LOG:  invalid record length at 0/3056200: wanted 24, got 0
2022-09-10 00:16:39.549 IST [1519] :[00000]:LOG:  database system is ready to accept read only connections
2022-09-10 00:16:39.550 IST [1525] :[57P03]:FATAL:  the database system is starting up
2022-09-10 00:16:39.565 IST [1529] :[00000]:LOG:  started streaming WAL from primary at 0/3000000 on timeline 4
2022-09-10 00:16:40.717 IST [1519] :[00000]:LOG:  received fast shutdown request
2022-09-10 00:16:40.718 IST [1519] :[00000]:LOG:  aborting any active transactions
2022-09-10 00:16:40.719 IST [1532] :[57P01]:FATAL:  terminating connection due to administrator command
2022-09-10 00:16:40.721 IST [1529] :[57P01]:FATAL:  terminating walreceiver process due to administrator command
2022-09-10 00:16:40.722 IST [1526] :[00000]:LOG:  shutting down
2022-09-10 00:16:40.734 IST [1519] :[00000]:LOG:  database system is shut down
2022-09-10 00:16:41.093 IST [1544] :[00000]:LOG:  database system was shut down in recovery at 2022-09-10 00:16:40 IST
2022-09-10 00:16:41.094 IST [1544] :[00000]:LOG:  entering standby mode
2022-09-10 00:16:41.094 IST [1545] :[57P03]:FATAL:  the database system is starting up
2022-09-10 00:16:41.097 IST [1544] :[00000]:LOG:  redo starts at 0/3039CD8
2022-09-10 00:16:41.098 IST [1544] :[00000]:LOG:  consistent recovery state reached at 0/3056E28
2022-09-10 00:16:41.098 IST [1544] :[00000]:LOG:  invalid record length at 0/3056E28: wanted 24, got 0
2022-09-10 00:16:41.099 IST [1541] :[00000]:LOG:  database system is ready to accept read only connections
2022-09-10 00:16:41.106 IST [1550] :[00000]:LOG:  started streaming WAL from primary at 0/3000000 on timeline 4
2022-09-10 00:16:41.249 IST [1541] :[00000]:LOG:  received fast shutdown request
2022-09-10 00:16:41.250 IST [1541] :[00000]:LOG:  aborting any active transactions
2022-09-10 00:16:41.252 IST [1552] :[57P01]:FATAL:  terminating connection due to administrator command
2022-09-10 00:16:41.252 IST [1550] :[57P01]:FATAL:  terminating walreceiver process due to administrator command
2022-09-10 00:16:41.253 IST [1547] :[00000]:LOG:  shutting down
2022-09-10 00:16:41.264 IST [1541] :[00000]:LOG:  database system is shut down
2022-09-10 00:16:41.703 IST [1564] :[00000]:LOG:  database system was shut down in recovery at 2022-09-10 00:16:41 IST
2022-09-10 00:16:41.704 IST [1564] :[00000]:LOG:  entering standby mode
2022-09-10 00:16:41.704 IST [1565] :[57P03]:FATAL:  the database system is starting up
2022-09-10 00:16:41.707 IST [1564] :[00000]:LOG:  redo starts at 0/3039CD8

**Have you tried to use GitHub issue search?yes, Didn't get any info on this 
Maybe there is already a similar issue solved.

**Additional context**
If I stop patroni service using sudo systemctls stop patroni and just starting normally with "pg_ctl start Or systemctl start postgresql-11, replication works as expected and  replication slot exists but as and when I start patroni service , the above mentioned issue occurs and keep restarting replica node endlessly . In that process, replication slots gets dropped and recreated frequently and attached the screenshot of same in this doc

**Comment by CyberDem0n** [comment]
> patronictl show-config
```yaml
postgresql:
  recovery_conf:
    restore_command: null
```

The error originated from the:
```yaml
bootstrap:
  dcs:
    postgresql:
      recovery_conf:
        restore_command:
```

The empty value of the `restore_command` is evaluated as `null`. Either you have to set it to something valid or remove it completely.
