### ISSUE TITLE
Is there any way to trigger restart activity in replica with scheduled basis when master switchover

### ISSUE THREAD

**Issue by novanbramantya** [zalando/patroni#2422]
**Describe the bug**
Actually when I trigger manual leader switchover, after switchover has been completed, then in all replicas triggered restart from patroni parallely.

**To Reproduce**
After leader got switchover, i checked DB uptime in master and replicas
master
<img width="223" alt="image" src="https://user-images.githubusercontent.com/44095576/192927639-eda63630-bca2-4064-906d-c4478681636b.png">
replicas
<img width="120" alt="image" src="https://user-images.githubusercontent.com/44095576/192927677-1dd2757b-b218-4bdc-b97f-e918db06cf94.png">
<img width="136" alt="image" src="https://user-images.githubusercontent.com/44095576/192927697-7d396b70-7ad1-48aa-8cb3-0c92f2de1d71.png">

**Expected behavior**
So, is there any way to us to have scheduled restart in replicas to prevent disruption on application perspective

**Environment**
- Patroni version: 2.1.4
- PostgreSQL version: 12.11
- DCS (and its version): etcd 3.4.13

**patronictl show-config**
```
check_timeline: false
ignore_slots:
loop_wait: 10
master_start_timeout: 1800
maximum_lag_on_failover: 50000000
postgresql:
  parameters:
    archive_mode: true
    hot_standby: true
    log_lock_waits: true
    log_truncate_on_rotation: false
    logging_collector: true
    max_connections: 1024
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 20
    max_wal_senders: 64
    max_worker_processes: 8
    pg_stat_statements.track: all
    shared_preload_libraries: pg_stat_statements,pglogical,wal2json,pg_partman_bgw
    track_commit_timestamp: false
    wal_keep_segments: 100
    wal_level: logical
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 60
synchronous_mode: false
synchronous_mode_strict: false
ttl: 30
```
