### ISSUE TITLE
After PostgreSQL 10 to 14 upgrade, receiving: LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/data/patroni/postgresql.conf" line 17

### ISSUE THREAD

**Issue by tomkcpr** [zalando/patroni#2443]
**Describe the bug**
Patroni fails to rename the setting in postgresql.conf from wal_keep_segments to wal_keep_size even though /etc/patroni.yml nor patronictl edit-config contain "wal_keep_segments = '8"

patroni-2.1.4-1.rhel7.x86_64

**To Reproduce**
Upgrade from PostgreSQL 10 to PostgreSQL 14

**Expected behavior**
Patroni correctly regenerates postgresql.conf with updated value for PostgreSQL 14, wal_keep_size.

**Screenshots**
Described above.  Status output below:

```
Oct 30 00:11:16 psql07.nix.mds.xyz patroni[2219]: 2022-10-30 04:11:16.994 GMT [2777] FATAL:  configuration file "/data/patroni/postgresql.conf" contains errors
Oct 30 00:11:26 psql07.nix.mds.xyz patroni[2219]: 2022-10-30 04:11:26.986 GMT [2798] LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/data/patroni/postgresql.conf" line 17
```

**Environment**
- Patroni version: patroni-2.1.4-1.rhel7.x86_64
- PostgreSQL version:
- DCS (and its version):

**Patroni configuration file**
```
scope: postgres
namespace: /db/
name: psql07

log:
    level: DEBUG
    dir: /var/log/patroni/
    file_num: 37
    file_size: 52428800

restapi:
    listen: psql07.nix.mds.xyz:8008
    connect_address: psql07.nix.mds.xyz:8008

etcd:
    host: psql07.nix.mds.xyz:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

        standby_cluster:
            host: psql-c02.nix.mds.xyz
            port: 5432
            create_replica_methods:
            - basebackup

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator psql07.nix.mds.xyz md5
    - host replication replicator psql08.nix.mds.xyz md5
    - host replication replicator psql09.nix.mds.xyz md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: psql07.nix.mds.xyz:5432
    bin_dir: /usr/pgsql-14/bin
    connect_address: psql07.nix.mds.xyz:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    unix_socket_directories: /data/patroni
    authentication:
        replication:
            username: replicator
            password: replicatorpass
        superuser:
            username: postgres
            password: postgrespassword
    parameters:
        unix_socket_directories: '.'
        max_connections: '256'
        max_replication_slots: '64'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
#

```

**patronictl show-config**
```
# patronictl --config-file=/etc/patroni.yml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  use_pg_rewind: true
retry_timeout: 10
ttl: 30


```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please see above.  Once more below:

```
Oct 30 00:22:16 psql07 patroni: 2022-10-30 04:22:16.928 GMT [4336] LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/data/patroni/postgresql.conf" line 17
Oct 30 00:22:16 psql07 patroni: 2022-10-30 04:22:16.928 GMT [4336] FATAL:  configuration file "/data/patroni/postgresql.conf" contains errors
```

**Have you tried to use GitHub issue search?**
Yes, expected behavior is documented on a number of online blogs and patroni sources, but does not occur in my cluster.

**Additional context**
As mentioned above, neither edit-config nor patroni.yml explicitly list wal_keep_segments as an explicit setting, suggesting this is internally generated from default values.  Other files including base config only show commented entries:

```
# grep -Ei wal_keep_segments *
backup-postgresql.conf:wal_keep_segments = '8'
postgresql.base.conf:#wal_keep_segments = 0             # in logfile segments, 16MB each; 0 disables
postgresql.base.conf.backup:#wal_keep_segments = 0              # in logfile segments, 16MB each; 0 disables
postgresql.conf:wal_keep_segments = '8'
postgresql.conf.backup:wal_keep_segments = '8'
#
```
