### ISSUE TITLE
standby-leader node starts complaining warning after failover happens on primary site

### ISSUE THREAD

**Issue by duj4** [zalando/patroni#2460]
**Describe the bug**
Standby-leader on DR site starts complaining lost connection to leader node on primary site after switchover happends on primary site.

**To Reproduce**
1. Set up 2 node PG cluster on primary site (node A and B, A is leader)
2. Set up another 2 node PG cluster on DR site (node C and D, C is standby leader and points to A)
3. Trigger a switchover on primary site so that A will be demoted to replica and B will be promoted to leader

**Expected behavior**
There won't be warning on C

**Screenshots**
N/A

**Environment**
- Patroni version: 2.1.4
- PostgreSQL version: 13.7
- DCS (and its version): consul 1.12.2

**Patroni configuration file**
DR part configuration on node C (vhkgpf77 in my case):
```
standby_cluster:
      create_replica_methods:
      - basebackup
      host: vhkgpf27.hkintegrationlab.com (node A on primary site)
      port: 5432
```

**patronictl show-config**
```
Node A on primary site:
[itsm_jsm_qa@vhkgpf27 bin]$ ./patronictl -c ../../conf/patroni.yml show-config
loop_wait: 10
maximum_lag_on_failvoer: 1048576
postgresql:
  parameters:
    debug_pretty_print: 'on'
    debug_print_parse: 'off'
    debug_print_plan: 'off'
    debug_print_rewritten: 'off'
    log_connections: 'on'
    log_destination: stderr
    log_disconnections: 'on'
    log_error_verbosity: verbose
    log_file_mode: 384
    log_filename: postgresql-%Y%m%d.log
    log_hostname: 'on'
    log_line_prefix: '%m [%p]: [%l-1] db=%d, user=%u, app=%a, client=%r '
    log_min_error_statement: warning
    log_min_messages: warning
    log_rotation_age: 1d
    log_rotation_size: 1GB
    log_statement: ddl
    log_timezone: GMT
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    max_connections: 500
    password_encryption: scram-sha-256
    ssl: 'on'
    ssl_ca_file: /d/d1/jsm/certs/ca.crt
    ssl_cert_file: /d/d1/jsm/certs/pg_server_all.crt
    ssl_ciphers: HIGH:!3DES
    ssl_key_file: /d/d1/jsm/certs/pg_server_all.key
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: 'on'
ttl: 30

Node C on DR site:
[itsm_jsm_qa@vhkgpf77 bin]$ ./patronictl -c ../../conf/patroni.yml show-config
loop_wait: 10
maximum_lag_on_failvoer: 1048576
postgresql:
  parameters:
    debug_pretty_print: 'on'
    debug_print_parse: 'off'
    debug_print_plan: 'off'
    debug_print_rewritten: 'off'
    log_connections: 'on'
    log_destination: stderr
    log_disconnections: 'on'
    log_error_verbosity: verbose
    log_file_mode: 384
    log_filename: postgresql-%Y%m%d.log
    log_hostname: 'on'
    log_line_prefix: '%m [%p]: [%l-1] db=%d, user=%u, app=%a, client=%r '
    log_min_error_statement: warning
    log_min_messages: warning
    log_rotation_age: 1d
    log_rotation_size: 1GB
    log_statement: ddl
    log_timezone: GMT
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    max_connections: 500
    password_encryption: scram-sha-256
    ssl: 'on'
    ssl_ca_file: /d/d1/jsm/certs/ca.crt
    ssl_cert_file: /d/d1/jsm/certs/pg_server_all.crt
    ssl_ciphers: HIGH:!3DES
    ssl_key_file: /d/d1/jsm/certs/pg_server_all.key
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
standby_cluster:
  create_replica_methods:
  - basebackup
  host: vhkgpf27.hkintegrationlab.com
  port: 5432
ttl: 30
```

**Have you checked Patroni logs?**
patroni.log on node C after failover happened on primary site:

> 2022-11-25 17:21:12 +0800 INFO: Lock owner: vhkgpf77.linux.hkintegrationlab.com; I am vhkgpf77.linux.hkintegrationlab.com
2022-11-25 17:21:12 +0800 INFO: Local timeline=6 lsn=0/5001470
2022-11-25 17:21:12 +0800 ERROR: Exception when working with leader
Traceback (most recent call last):
  File "/d/d1/jsm/patroni/patroni_venv/lib64/python3.9/site-packages/patroni/postgresql/rewind.py", line 68, in check_leader_is_not_in_recovery
    with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
  File "/usr/lib64/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/d/d1/jsm/patroni/patroni_venv/lib64/python3.9/site-packages/patroni/postgresql/connection.py", line 44, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
  File "/d/d1/jsm/patroni/patroni_venv/lib64/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "vhkgpf27.hkintegrationlab.com" (10.233.252.204), port 5432 failed: session is read-only

**Have you checked PostgreSQL logs?**
postgresql.log on node C after switchover happened on primary site:

> 2022-11-25 09:11:25.835 GMT [1668464]: [4-1] db=postgres, user=itsm_jsm_qa, app=[unknown], client=vhkgpf27.hkintegrationlab.com(56446) LOCATION:  PerformAuthentication, postinit.c:292
2022-11-25 09:11:33.450 GMT [1668464]: [5-1] db=postgres, user=itsm_jsm_qa, app=psql, client=vhkgpf27.hkintegrationlab.com(56446) LOG:  00000: disconnection: session time: 0:00:07.626 user=itsm_jsm_qa database=postgres host=vhkgpf27.hkintegrationlab.com port=56446
2022-11-25 09:11:33.450 GMT [1668464]: [6-1] db=postgres, user=itsm_jsm_qa, app=psql, client=vhkgpf27.hkintegrationlab.com(56446) LOCATION:  log_disconnections, postgres.c:4777
2022-11-25 09:20:58.632 GMT [1668432]: [10-1] db=, user=, app=, client= LOG:  00000: replication terminated by primary server
2022-11-25 09:20:58.632 GMT [1668432]: [11-1] db=, user=, app=, client= DETAIL:  End of WAL reached on timeline 5 at 0/5001358.
2022-11-25 09:20:58.632 GMT [1668432]: [12-1] db=, user=, app=, client= LOCATION:  WalReceiverMain, walreceiver.c:483
2022-11-25 09:20:58.632 GMT [1668432]: [13-1] db=, user=, app=, client= FATAL:  XX000: could not send end-of-streaming message to primary: no COPY in progress
2022-11-25 09:20:58.632 GMT [1668432]: [14-1] db=, user=, app=, client= LOCATION:  libpqrcv_endstreaming, libpqwalreceiver.c:493
2022-11-25 09:20:58.634 GMT [1668428]: [13-1] db=, user=, app=, client= LOG:  00000: invalid record length at 0/5001358: wanted 24, got 0
2022-11-25 09:20:58.634 GMT [1668428]: [14-1] db=, user=, app=, client= LOCATION:  ReadRecord, xlog.c:4400
2022-11-25 09:20:58.640 GMT [1668812]: [1-1] db=, user=, app=, client= FATAL:  XX000: could not connect to the primary server: server closed the connection unexpectedly
                This probably means the server terminated abnormally
                before or while processing the request.

**Have you tried to use GitHub issue search?**
No similar issue.

**Additional context**
I would like to know whether I need to modify the config file on node C (vhkgpf77 in my case) to re-point the primary node to B(new leader after switchover) from A(previous leader) after switchover happens on primary site.
