### ISSUE TITLE
patronictl remove doesn't work as expected once hostname renaming

### ISSUE THREAD

**Issue by yinan8128** [zalando/patroni#2461]
**Describe the bug**
patronictl remove doesn't work as expected once hostname renaming

**To Reproduce**
--Check patroni cluster roles and status
CT-317940710 /# patronictl -c /etc/patroni/postgresql.yml list
+-------------------------------------+-------------+--------------+---------+----+-----------+
| Member                              | Host        | Role         | State   | TL | Lag in MB |
+ Cluster: pgcluster02 (7167634132365987050) -------+--------------+---------+----+-----------+
| s23456y-patroni_cluster02-317940710 | 10.35.53.47 | Leader       | running |  2 |           |
| s23456y-patroni_cluster02-317940711 | 10.35.53.48 | Sync Standby | running |  2 |         0 |
| s23456y-patroni_cluster02-317940712 | 10.35.53.49 | Replica      | running |  2 |         0 |
+-------------------------------------+-------------+--------------+---------+----+-----------+

--Check consul key value
CT-317940710 /# consul kv export service/pgcluster02/members
[
        {
                "key": "service/pgcluster02/members/s23456y-patroni_cluster02-317940710",
                "flags": 0,
                "value": "..."
        },
        {
                "key": "service/pgcluster02/members/s23456y-patroni_cluster02-317940711",
                "flags": 0,
                "value": "..."
        },
        {
                "key": "service/pgcluster02/members/s23456y-patroni_cluster02-317940712",
                "flags": 0,
                "value": "..."
        }
]

--Change 317940710 node hostname
CT-317940710 /# hostname
s23456y-patroni_cluster02-317940710.acronis
CT-317940710 /# hostnamectl set-hostname new01-patroni_cluster02-317940710.acronis
CT-317940710 /# hostname
new01-patroni_cluster02-317940710.acronis

--Edit /etc/patroni/postgresql.yml name to new01-patroni_cluster02-317940710.acronis

--patronictl remove
CT-317940710 /# patronictl -c /etc/patroni/postgresql.yml remove pgcluster02
+-------------------------------------+-------------+--------------+---------+----+-----------+
| Member                              | Host        | Role         | State   | TL | Lag in MB |
+ Cluster: pgcluster02 (7167634132365987050) -------+--------------+---------+----+-----------+
| s23456y-patroni_cluster02-317940710 | 10.35.53.47 | Leader       | running |  2 |           |
| s23456y-patroni_cluster02-317940711 | 10.35.53.48 | Sync Standby | running |  2 |         0 |
| s23456y-patroni_cluster02-317940712 | 10.35.53.49 | Replica      | running |  2 |         0 |
+-------------------------------------+-------------+--------------+---------+----+-----------+
Please confirm the cluster name to remove: pgcluster02
You are about to remove all information in DCS for pgcluster02, please type: "Yes I am aware": Yes I am aware
This cluster currently is healthy. Please specify the master name to continue: s23456y-patroni_cluster02-317940710

--Check patroni cluster roles and status
CT-317940710 /# patronictl -c /etc/patroni/postgresql.yml list
+-------------------------------------+-------------+--------------+---------+----+-----------+
| Member                              | Host        | Role         | State   | TL | Lag in MB |
+ Cluster: pgcluster02 (7167634132365987050) -------+--------------+---------+----+-----------+
| s23456y-patroni_cluster02-317940710 | 10.35.53.47 | Leader       | running |  2 |           |
| s23456y-patroni_cluster02-317940711 | 10.35.53.48 | Sync Standby | running |  2 |         0 |
| s23456y-patroni_cluster02-317940712 | 10.35.53.49 | Replica      | running |  2 |         0 |
+-------------------------------------+-------------+--------------+---------+----+-----------+

--Check consul key value
CT-317940710 /# consul kv export service/pgcluster02/members
[
        {
                "key": "service/pgcluster02/members/s23456y-patroni_cluster02-317940710",
                "flags": 0,
                "value": "..."
        },
        {
                "key": "service/pgcluster02/members/s23456y-patroni_cluster02-317940711",
                "flags": 0,
                "value": "..."
        },
        {
                "key": "service/pgcluster02/members/s23456y-patroni_cluster02-317940712",
                "flags": 0,
                "value": "..."
        }
]

**Environment**
- centos: 7.9.2009
- Patroni version: 2.1.3
- PostgreSQL version: 14.5
- DCS (and its version): consul 1.2.2-6

**Patroni configuration file**
```
scope: pgcluster02
name: new01-patroni_cluster02-317940710.acronis

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.35.53.47:8008

consul:
  host: 127.0.0.1:8500
  checks: []
  register_service: true

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        archive_mode: "on"
        archive_command: /bin/true
        archive_timeout: 1800s
        autovacuum: "on"
        autovacuum_work_mem: 1GB
        autovacuum_vacuum_threshold: 50
        autovacuum_vacuum_cost_limit: 8000
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_threshold: 50
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_max_workers: 6
        auto_explain.log_min_duration: 60000
        auto_explain.log_nested_statements: true
        bgwriter_delay: 50ms
        bgwriter_lru_maxpages: 4000
        bgwriter_lru_multiplier: 4
        checkpoint_completion_target: 0.7
        checkpoint_timeout: 30min
        config_file: /var/lib/pgsql/14/data/postgresql.conf
        constraint_exclusion: partition
        cron.database_name: postgres
        datestyle: "ISO, MDY"
        default_statistics_target: 100
        default_text_search_config: "pg_catalog.english"
        effective_cache_size: "2880MB"
        hot_standby: "on"
        idle_in_transaction_session_timeout: 10min
        jit: "off"
        lc_messages: 'C'
        lc_monetary: 'C'
        lc_numeric: 'C'
        lc_time: 'C'
        lock_timeout: 30s
        log_autovacuum_min_duration: 500
        log_checkpoints: "off"
        log_connections: "off"
        log_destination: "stderr"
        log_directory: "/var/log/postgresql"
        log_disconnections: "off"
        log_duration: "off"
        log_filename: 'postgresql.log'
        log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
        log_lock_waits: "on"
        log_min_duration_statement: "5s"
        log_recovery_conflict_waits: "on"
        log_rotation_age: 0
        log_rotation_size: 0
        log_statement: "ddl"
        log_temp_files: 1MB
        log_timezone: "UTC"
        log_truncate_on_rotation: "off"
        logging_collector: "on"
        maintenance_work_mem: 2GB
        max_connections: 1000
        max_replication_slots: 10
        max_wal_senders: 10
        max_wal_size: "3840"
        min_wal_size: 1024
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        random_page_cost: 1.1
        shared_buffers: 960MB
        shared_preload_libraries: 'pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron'
        ssl: 'on'
        ssl_ca_file: '/var/lib/pgsql/tls/root.crt'
        ssl_cert_file: '/var/lib/pgsql/tls/server.crt'
        ssl_key_file: '/var/lib/pgsql/tls/server.key'
        statement_timeout: 10min
        temp_file_limit: 5GB
        timezone: "UTC"
        track_io_timing: "on"
        unix_socket_directories: '/var/run/postgresql'
        wal_buffers: -1
        wal_compression: "on"
        wal_keep_size: "160MB"
        wal_level: replica
        wal_log_hints: "on"
        work_mem: "1MB"
      recovery_conf:
        restore_command: /bin/true
  initdb:
    - encoding: UTF8
    - data-checksums
    - locale: en_US.UTF-8
    - lc-collate: en_US.UTF-8
    - lc-ctype: en_US.UTF-8

  users:
    replicator:
      password: bbb
      options:
        - replication

postgresql:
  listen: '*'
  connect_address: 10.35.53.47:5432
  data_dir: /var/lib/pgsql/14/data
  bin_dir: /usr/pgsql-14/bin
  config_dir: /var/lib/pgsql/14/data
  hba_file: /var/lib/pgsql/14/data/pg_hba.conf
  restore: /usr/bin/patroni_wale_restore
  pgpass: /tmp/pgpass
  authentication:
    pg_rewind:
      username: postgres
      password: aaa
    replication:
      username: replicator
      password: bbb
      network: 0.0.0.0/0
    superuser:
      username: postgres
      password: aaa
  callbacks:
    on_start: /etc/patroni/callback.sh
    on_stop: /etc/patroni/callback.sh
    on_role_change: /etc/patroni/callback.sh
  basebackup:
    - verbose
    - checkpoint: 'fast'
  pg_hba:
    - local all postgres trust
    - local all all trust
    - host replication replicator 0.0.0.0/0 scram-sha-256
    - host replication replicator ::/0 scram-sha-256
    - host replication postgres 127.0.0.1/32 trust
    - host replication postgres ::1/128 trust
    - host all all 127.0.0.1/32 scram-sha-256
    - host all all ::1/128 scram-sha-256
    - host postgres postgres 10.35.53.47/32 scram-sha-256
    - host postgres pgwatch2 10.35.53.47/32 scram-sha-256
    - host postgres replicator 10.35.53.47/32 scram-sha-256
    - host postgres postgres 10.35.53.48/32 scram-sha-256
    - host postgres pgwatch2 10.35.53.48/32 scram-sha-256
    - host postgres replicator 10.35.53.48/32 scram-sha-256
    - host postgres postgres 10.35.53.49/32 scram-sha-256
    - host postgres pgwatch2 10.35.53.49/32 scram-sha-256
    - host postgres replicator 10.35.53.49/32 scram-sha-256
    - host postgres all 0.0.0.0/0 reject
    - host postgres all ::/0 reject
    - hostnossl all all 0.0.0.0/0 scram-sha-256
    - hostnossl all all ::/0 scram-sha-256
    - hostssl all all 0.0.0.0/0 scram-sha-256 clientcert=verify-full
    - hostssl all all ::/0 scram-sha-256 clientcert=verify-full

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "process": %(process)d, "thread": %(thread)d, "level": "%(levelname)s", "message": "%(message)s"}'
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: /bin/true
    archive_mode: 'on'
    archive_timeout: 1800s
    auto_explain.log_min_duration: 60000
    auto_explain.log_nested_statements: true
    autovacuum: 'on'
    autovacuum_analyze_scale_factor: 0.05
    autovacuum_analyze_threshold: 50
    autovacuum_max_workers: 6
    autovacuum_vacuum_cost_limit: 8000
    autovacuum_vacuum_scale_factor: 0.01
    autovacuum_vacuum_threshold: 50
    autovacuum_work_mem: 1GB
    bgwriter_delay: 50ms
    bgwriter_lru_maxpages: 4000
    bgwriter_lru_multiplier: 4
    checkpoint_completion_target: 0.7
    checkpoint_timeout: 30min
    config_file: /var/lib/pgsql/14/data/postgresql.conf
    constraint_exclusion: partition
    cron.database_name: postgres
    datestyle: ISO, MDY
    default_statistics_target: 100
    default_text_search_config: pg_catalog.english
    effective_cache_size: 2880MB
    hot_standby: 'on'
    idle_in_transaction_session_timeout: 10min
    jit: 'off'
    lc_messages: C
    lc_monetary: C
    lc_numeric: C
    lc_time: C
    lock_timeout: 30s
    log_autovacuum_min_duration: 500
    log_checkpoints: 'off'
    log_connections: 'off'
    log_destination: stderr
    log_directory: /var/log/postgresql
    log_disconnections: 'off'
    log_duration: 'off'
    log_filename: postgresql.log
    log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
    log_lock_waits: 'on'
    log_min_duration_statement: 5s
    log_recovery_conflict_waits: 'on'
    log_rotation_age: 0
    log_rotation_size: 0
    log_statement: ddl
    log_temp_files: 1MB
    log_timezone: UTC
    log_truncate_on_rotation: 'off'
    logging_collector: 'on'
    maintenance_work_mem: 2GB
    max_connections: 1000
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: '3840'
    min_wal_size: 1024
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    random_page_cost: 1.1
    shared_buffers: 960MB
    shared_preload_libraries: pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron
    ssl: 'on'
    ssl_ca_file: /var/lib/pgsql/tls/root.crt
    ssl_cert_file: /var/lib/pgsql/tls/server.crt
    ssl_key_file: /var/lib/pgsql/tls/server.key
    statement_timeout: 10min
    temp_file_limit: 5GB
    timezone: UTC
    track_io_timing: 'on'
    unix_socket_directories: /var/run/postgresql
    wal_buffers: -1
    wal_compression: 'on'
    wal_keep_size: 160MB
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 1MB
  recovery_conf:
    restore_command: /bin/true
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
synchronous_mode: true
ttl: 30
```
