### ISSUE TITLE
Not all Watchdog settings applied when expected

### ISSUE THREAD

**Issue by matthbakeredb** [zalando/patroni#2470]
**Describe the bug**

With this minimal config (minus other irrelevant stuff)
```
bootstrap:
  dcs:
    ttl: 60
    loop_wait: 10
    retry_timeout: 10
watchdog:
  mode: required
  device: /dev/watchdog
  safety_margin: -1
```
The watchdog starts with timings that are derived from the default ttl, loop_wait and retry_timeout not the ones in bootstrap.dcs. 

In addition to this, I can see that changes to watchdog when it is running and activated happen during the next `keepalive`, however a `patronictl reload` does not log a change in the watchdog for the `ttl` setting and `safety_margin` doesn't appear to be applied without a `pause`, `resume`. This makes it appear that this requires a `patronictl pause` amd `patronictl resume` after the `patronictl reload`. 

**To Reproduce**

Create a new cluster, with no data stored in the dcs, with watchdog enabled and different settings for dcs ttl, loop_wait and retry_timeout. When patroni is started watch the log for the watchdog to activate.

To apply the settings in the dcs to the watchdog run `patronictl pause` and `patronictl resume`.

To change the settings, use `patronictl edit-config` to change ttl,, or edit the local config yaml file to update `safety_margin` followed by running `patronictl reload` to refresh the local config. No log entry shows a change to watchdog settings. Run `pause` and `resume` again to apply changes.

**Expected behavior**

The watchdog should be first opened with the settings provided in the `bootstrap.dcs` without a `pause` and `resume`.
Patroni should log the current watchdog config and any changes performed.
A single `patronictl reload` or `edit-config` should be sufficient after a configuration change.

**Environment**
- Patroni version: 2.1.4
- PostgreSQL version: 13
- DCS (and its version): etcd 3.2.26

**Patroni configuration file**
```
scope: pat-aws-ubuntu
namespace: /db/
name: db0
restapi:
  listen: 0.0.0.0:8008
  connect_address: db0:8008
  authentication:
    username: patroni
    password: *******************
bootstrap:
  initdb:
  - encoding: UTF8
  - data-checksums
  - auth-local: peer
  - auth-host: scram-sha-256
  dcs:
    ttl: 60
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: false
      use_slots: true
    ignore_slots:
    - name: backup_bak0
      type: physical
postgresql:
  listen: 0.0.0.0:5432
  connect_address: 10.33.168.200:5432
  data_dir: /opt/postgres/data
  bin_dir: /usr/lib/postgresql/13/bin
  pgpass: /etc/patroni/.pgpass
  authentication:
    replication:
      username: replicator
      password: *******************
    superuser:
      username: postgres
      password: *******************
  parameters:
    unix_socket_directories: /var/run/postgresql,/tmp
    listen_addresses: '*'
    port: '5432'
    cluster_name: pat-aws-ubuntu
    wal_level: logical
    hot_standby: 'on'
    max_connections: '250'
    max_wal_senders: '6'
    max_prepared_transactions: '0'
    max_locks_per_transaction: '32'
    track_commit_timestamp: 'off'
    max_replication_slots: '6'
    max_worker_processes: '16'
    wal_log_hints: 'on'
    wal_keep_size: '0'
watchdog:
  mode: required
  device: /dev/watchdog
  safety_margin: -1
log:
  dir: /var/log/patroni
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
etcd3:
  hosts:
  - dcs0:2379
  - dcs1:2379
  - dcs2:2379
```

**patronictl show-config**
```
ignore_slots:
- name: backup_bak0
  type: physical
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  use_pg_rewind: false
  use_slots: true
retry_timeout: 10
ttl: 60
```

**Have you checked Patroni logs?**

Log entries for watchdog with normal behaviour, starting a new cluster and then pause, resume.

```
2022-11-28 18:08:45,913 INFO: Software Watchdog activated with 15 second timeout, timing slack 5 seconds
2022-11-28 18:28:48,316 INFO: Software Watchdog activated with 30 second timeout, timing slack 20 seconds
```

and after my change just with a start on a fresh cluster:
```
2022-11-29 13:43:39,565 INFO: Software Watchdog activated with 30 second timeout, timing slack 20 seconds
```

**Additional context**

This appears to be because the dcs is bootstrapped after the Watchdog class is instantiated. so it takes the defaults loaded in config.
https://github.com/zalando/patroni/blob/master/patroni/__main__.py#L26
If I move this one line down and start patroni on a fresh cluster it appears to load the values defined in the bootstrap.dcs. Without this I need to reload the patroni daemon, or pause and resume the cluster. That appears to then propagate the dcs settings to the watchdog.
