### ISSUE TITLE
Postgresql isn't initiated after starting patroni

### ISSUE THREAD

**Issue by phuonghuynguyen** [zalando/patroni#2473]
**Describe the bug**
When I start patroni for the first time, the patroni cluster is up as expected. However, patroni does not initiate any postgresql server or start postgresql as when I  use: `psql -U postgres`, it sends output:

    psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
However, when check with `netstat -tulpn`, server is listening on port 5432.
Restart patroni but still no luck.

**To Reproduce**
I install patroni and postgres follow this [link](https://www.askvikram.com/set-up-a-highly-available-postgresql-cluster-using-patroni-and-haproxy/?fbclid=IwAR1xGuaQLMYnooTuqolbbO_sSEm9qf0GcrhuBzDckxwGL5Y6Phj_PrT6R8w)
After `systemctl start patroni`: postgresql does not start with it.

**Expected behavior**
The cluster initialization and setup are handled by Patroni during the bootsrapping stage. So after starting patroni, I can access postgresql

**Screenshots**
![image](https://user-images.githubusercontent.com/74166188/205599061-09759e8e-456f-441b-94dd-0656a979413e.png)

**Environment**
- Patroni version: 2.1.5
- PostgreSQL version: 15.1
- DCS (and its version): 3.3.11

**Patroni configuration file**
Patroni configuration is the same on 3 nodes postgresql:
```
scope: postgres
namespace: /db/
name: node1

restapi:
  listen: 192.168.125.101:8008
  connect_address: 192.168.125.101:8008

etcd:
  host: 192.168.125.101:2379

bootstrap:
 dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:

  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator 192.168.125.101/0 md5
  - host replication replicator 192.168.125.100/0 md5
  - host replication replicator 192.168.125.102/0 md5
  - host all all 0.0.0.0/0 md5

  users:
    admin:
      password: admin%
      options:
        - createrole
        - createdb

postgresql:
  listen: 192.168.125.101:5432
  connect_address: 192.168.125.101:5432
  data_dir: data/patroni
  bin_dir: /usr/pgsql-15/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: huy123
    superuser:
      username: postgres
      password: huy123
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: rewind_password

  parameters:
    unix_socket_directories: '..'  # parent directory of data_dir

log:
  dir: /data

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

**patronictl show-config**
```
patronictl show-config
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: etcd, etcd3, kubernetes'
```

**Have you checked Patroni logs?**
![image](https://user-images.githubusercontent.com/74166188/205599938-7c934409-26e2-4ca1-8c39-c36a181b7b4a.png)

**Have you checked PostgreSQL logs?**
![image](https://user-images.githubusercontent.com/74166188/205600303-888c9204-37c5-4eff-b658-cd51dce776d3.png)

**Additional context**
`patronictl -c /etc/patroni/config.yml list` shows no problems
![image](https://user-images.githubusercontent.com/74166188/205601077-72d59f8b-24a4-4521-9b9f-d4692e91d630.png)

I tried follow other documents but still stuck in this step.
