### ISSUE TITLE
pg_hba not visible when using patronictl edit-config

### ISSUE THREAD

**Issue by goran-kuzmanovic** [zalando/patroni#2474]
**Describe the bug**
When I deploy Patroni Postgres cluster, pg_hba entries specified in patroni.yml are present in pg_hba.conf, however, they are not visible when using patronictl edit-config. If I then add that section in patroni.yml and reload, everything is visible going forward (that's the workaround we are using at the moment). Now is that a bug or am I missing something ?

The reason why this would be beneficial to us is that we want to enforce configuration changes to be done only via patronictl, to avoid overriding and miss-configuration elsewhere.

**To Reproduce**
- deploy cluster
- execute patronictl edit-config and check for pg_hba section under postgresql section
- add it manually and reload config (verify it is visible)

**Expected behavior**
Expectation would be that on initial cluster setup, this is already present as is in patroni.yml

**Screenshots**

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 13.7 (Percona distribution)
- DCS (and its version): ETCD v3.3.11

**Patroni configuration file**
patroni.yml:
```
scope: cluster_1
namespace: /postgres/
name: node_a

log:
  level: INFO
  traceback_level: ERROR
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000
  dir: /dbs0001/pglog
  file_num: 4
  file_size: 25000000
  loggers:
    patroni.postmaster: WARNING
    urllib3: WARNING

restapi:
  listen: 10.0.0.1:8008
  connect_address: 10.0.0.1:8008

etcd3:
  hosts:
  - etcd_node_1:2379
  - etcd_node_2:2379
  - etcd_node_3:2379
  protocol: http

bootstrap:
  method: initdb_cust
  initdb_cust:
    command: initdb-bootstrap.sh
    keep_existing_recovery_conf: false
    no_params: False

  dcs:
    ttl: 45
    loop_wait: 15
    retry_timeout: 15
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    synchronous_node_count: 1
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_command: 'test ! -f /dbdump/archive/%f && cp %p /dbdump/archive/%f'
        archive_mode: on
        archive_timeout: 1h
        client_min_messages: notice
        datestyle: 'iso, mdy'
        default_text_search_config: 'pg_catalog.english'
        dynamic_shared_memory_type: posix
        effective_cache_size: 4GB
        fsync: on
        hash_mem_multiplier: 1.0
        hot_standby: true
        wal_buffers: 128
        wal_keep_size: 2048
        wal_level: logical
        wal_log_hints: on
        wal_receiver_create_temp_slot: off
        wal_skip_threshold: 2MB
        work_mem: 4MB

postgresql:
  listen: '*:5432'
  connect_address: 10.0.0.1:5432
  use_unix_socket: true
  data_dir: /data/pgdata
  bin_dir: /usr/pgsql-13/bin
  config_dir: /data/pgdata
  pgpass: /software/.pgpass_patroni
  authentication:
    superuser:
      username: postgres
    replication:
      username: postgres
  pg_hba:
    - local all all  trust
    - host all all 127.0.0.1/32 trust
    - host all all ::1/128 trust
    - local replication all  trust
    - host replication all 127.0.0.1/32 trust
    - host replication all ::1/128 trust
    - host replication postgres node_a_host trust
    - host replication postgres node_b_host trust
  remove_data_directory_on_rewind_failure: true
  remove_data_directory_on_diverged_timelines: false
  parameters:
    unix_socket_directories: '/var/run/postgresql, /tmp'
  create_replica_methods:
    - basebackup
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'
    waldir: '/wals/pgwal'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

**patronictl show-config**
```
loop_wait: 15
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: 'test ! -f /dbdump/archive/%f && cp %p /dbdump/archive/%f'
    archive_mode: on
    archive_timeout: 1h
    client_min_messages: notice
    datestyle: 'iso, mdy'
    default_text_search_config: 'pg_catalog.english'
    dynamic_shared_memory_type: posix
    effective_cache_size: 4GB
    fsync: on
    hash_mem_multiplier: 1.0
    hot_standby: true
    wal_buffers: 128
    wal_keep_size: 2048
    wal_level: logical
    wal_log_hints: on
    wal_receiver_create_temp_slot: off
    wal_skip_threshold: 2MB
    work_mem: 4MB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 15
synchronous_mode: false
synchronous_mode_strict: false
synchronous_node_count: 1
ttl: 45
```

**Have you checked Patroni logs?**
N/A

**Have you checked PostgreSQL logs?**
N/A

**Have you tried to use GitHub issue search?**
Not found

**Additional context**

Thanks in advance!
