### ISSUE TITLE
patroni raft (2.1.5) single binary created with pyinstaller gives patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations:

### ISSUE THREAD

**Issue by coffeemug01** [zalando/patroni#2481]
**Describe the bug**
Created patroni raft single binary using pyinstaller with --onefile option. This single binary gives proper output with command './patroni --version', but gives PatroniFatalException when trying to execute with Patroni configuration yml file ('./patroni test.yml')
Install Patroni[raft] using pip command in Docker Linux container . I used Rocky Linux 8
Install Postgres 14
Install pyinstaller
Execute command
   pyinstaller --hidden-import="http.server" --hidden-import="pysyncobj"  /usr/local/bin/patroni --onefile
Try to run the created Patroni binary with configuration file 
./patroni test.yml
**Expected behavior**
No crash and some Patroni logs
**Screenshots**
![image](https://user-images.githubusercontent.com/120054456/206556229-f1ea1fdc-d3d2-45f2-b91c-bbdc3b63a021.png)
**Environment**
- Patroni version: 2.1.5
- PostgreSQL version: 14
- DCS (and its version): Patroni Raft

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
scope: demo-cluster-1
namespace: /db/
name: f6fd681c4e9a
restapi:
  listen: "0.0.0.0:8008"
  connect_address: "172.17.0.8:8008"
raft:
  data_dir: /home/core/raft
  self_addr: "172.17.0.8:5010"
  partner_addrs: ['172.17.0.5:5010']
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: false
      use_slots: true
      parameters:
        archive_mode: "on"
        archive_command: "/bin/true"
  initdb:
  - encoding: UTF8
  - data-checksums
  pg_hba:
  - host replication replicator 0.0.0.0/0 scram-sha-256
  - host all all 0.0.0.0/0 scram-sha-256
postgresql:
  listen: "172.17.0.8:5432"
  connect_address: "172.17.0.8:5432"
  proxy_address: "172.17.0.8:5432"
  data_dir: /var/lib/pgsql/14/data
  bin_dir: //usr/pgsql-14/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: confidential
    superuser:
      username: postgres
      password: my-super-password
    rewind:
      username: rewind_user
      password: rewind_password
  parameters:
    unix_socket_directories: '/var/run/postgresql,/tmp'
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.


**Additional context**
Add any other context about the problem here.
