### ISSUE TITLE
 Failed to drop replication slot

### ISSUE THREAD

**Issue by Aleksanrd** [zalando/patroni#2486]
**Describe the bug**
I have 3 cluster nodes (etcdctl version: 3.5.6, postgres 13.9, patroni version 2.1.5).
Everything works well, except for one node, after it ceased to be the leader, an entry appeared in the logs:

```
ERROR: Failed to drop replication slot 'db2'
INFO: no action. I am (db3), a secondary, and following a leader (db1)
```

As far as I understand, in this topic a similar problem is painted, and it has already been closed a year ago.
https://github.com/zalando/patroni/pull/2055#ref-issue-1363223511
https://github.com/zalando/patroni/commit/33ce08f7cb385d5c84fc464ba6b2a660fa2f2386
And in my installed patroni version 2.1.5 should already be fixed?

**To Reproduce**
Switchover cluster

Slave node display:
`postgres=# select * from pg_replication_slots ;
 slot_name | plugin | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn | wal_status | safe_wal_size
-----------+--------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------+------------+---------------
 db2       |        | physical  |        |          | f         | t      |     456396 |      |              | 0/2180D8A8  |                     | reserved   |
`

**Expected behavior**
Slave node drop replication slot after switchover from master to slave.

**Environment**
- Patroni version: 2.1.5 etcdctl version: 3.5.6
- PostgreSQL version: 13.9
- Etcd version: 3.5.6:

**Comment by CyberDem0n** [comment]
You really need to elaborate more.
From what you show it is only evident that db2 is streaminf from the db3 and therefore the replication slot could not be dropped.
What is the status of db2? Why is it streaming from db3?

**Comment by Aleksanrd** [comment]
The current state of the cluster
patronictl -c /etc/patroni/patroni.yml list
![изображение](https://user-images.githubusercontent.com/60338805/207546852-8a6ae13a-31d0-46b1-87d5-006bf206ac4c.png)

**Comment by CyberDem0n** [comment]
It is still answers nothing.
The issue template is quite explicit about what should be done and what information should be provided, like: config files and Patroni/Postgres logs.

**Comment by Aleksanrd** [comment]
```
scope: mobile
namespace: /mobile/
name: db3

restapi:
    listen: 15.28.5.88:8008
    connect_address: 15.28.5.88:8008

etcd3:
    hosts: 15.28.5.84:2379,15.28.5.87:2379,15.28.5.88:2379
    username: root
    password: root

bootstrap:
    dcs:
        ttl: 100
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:
                    wal_level: replica
                    hot_standby: "on"
                    wal_keep_segments: 5120
                    max_wal_senders: 5
                    max_replication_slots: 5
                    checkpoint_timeout: 30
                    max_connections: '1000'

    initdb:
    - encoding: UTF8
    - data-checksums
    - locale: en_US.UTF8
    - directory: /etc/postgresql/13/main
    - pgdata: /var/lib/postgresql/13/main

    pg_hba:
    - host replication patroni_replica 15.28.5.84/32 md5
    - host replication patroni_replica 15.28.5.87/32 md5
    - host replication patroni_replica 15.28.5.88/32 md5
    - host all all 0.0.0.0/0 md5

postgresql:
    listen: 15.28.5.88:5432
    connect_address: 15.28.5.88:5432
    data_dir: /var/lib/postgresql/13/main
    bin_dir:  /usr/lib/postgresql/13/bin
    config_dir: /etc/postgresql/13/main
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: patroni_replica
            password: Pass
        superuser:
            username: patroni_superuser
            password: Pass
    create_replica_methods:
        basebackup:
            checkpoint: 'fast'
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```
`Dec 14 09:16:05 srvdb3 patroni[337821]: 2022-12-14 09:16:05,744 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:16:15 srvdb3 patroni[337821]: 2022-12-14 09:16:15,692 INFO: Lock owner: db1; I am db3
Dec 14 09:16:15 srvdb3 patroni[337821]: 2022-12-14 09:16:15,697 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:16:15 srvdb3 patroni[337821]: 2022-12-14 09:16:15,697 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:16:25 srvdb3 patroni[337821]: 2022-12-14 09:16:25,692 INFO: Lock owner: db1; I am db3
Dec 14 09:16:25 srvdb3 patroni[337821]: 2022-12-14 09:16:25,696 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:16:25 srvdb3 patroni[337821]: 2022-12-14 09:16:25,701 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:16:35 srvdb3 patroni[337821]: 2022-12-14 09:16:35,692 INFO: Lock owner: db1; I am db3
Dec 14 09:16:35 srvdb3 patroni[337821]: 2022-12-14 09:16:35,696 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:16:35 srvdb3 patroni[337821]: 2022-12-14 09:16:35,697 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:16:45 srvdb3 patroni[337821]: 2022-12-14 09:16:45,692 INFO: Lock owner: db1; I am db3
Dec 14 09:16:45 srvdb3 patroni[337821]: 2022-12-14 09:16:45,697 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:16:45 srvdb3 patroni[337821]: 2022-12-14 09:16:45,700 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:16:55 srvdb3 patroni[337821]: 2022-12-14 09:16:55,692 INFO: Lock owner: db1; I am db3
Dec 14 09:16:55 srvdb3 patroni[337821]: 2022-12-14 09:16:55,696 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:16:55 srvdb3 patroni[337821]: 2022-12-14 09:16:55,697 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:17:05 srvdb3 patroni[337821]: 2022-12-14 09:17:05,692 INFO: Lock owner: db1; I am db3
Dec 14 09:17:05 srvdb3 patroni[337821]: 2022-12-14 09:17:05,696 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:17:05 srvdb3 patroni[337821]: 2022-12-14 09:17:05,744 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:17:15 srvdb3 patroni[337821]: 2022-12-14 09:17:15,692 INFO: Lock owner: db1; I am db3
Dec 14 09:17:15 srvdb3 patroni[337821]: 2022-12-14 09:17:15,696 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:17:15 srvdb3 patroni[337821]: 2022-12-14 09:17:15,697 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:17:25 srvdb3 patroni[337821]: 2022-12-14 09:17:25,692 INFO: Lock owner: db1; I am db3
Dec 14 09:17:25 srvdb3 patroni[337821]: 2022-12-14 09:17:25,696 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:17:25 srvdb3 patroni[337821]: 2022-12-14 09:17:25,700 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:17:35 srvdb3 patroni[337821]: 2022-12-14 09:17:35,692 INFO: Lock owner: db1; I am db3
Dec 14 09:17:35 srvdb3 patroni[337821]: 2022-12-14 09:17:35,696 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:17:35 srvdb3 patroni[337821]: 2022-12-14 09:17:35,696 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:17:45 srvdb3 patroni[337821]: 2022-12-14 09:17:45,692 INFO: Lock owner: db1; I am db3
Dec 14 09:17:45 srvdb3 patroni[337821]: 2022-12-14 09:17:45,696 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:17:45 srvdb3 patroni[337821]: 2022-12-14 09:17:45,701 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:17:55 srvdb3 patroni[337821]: 2022-12-14 09:17:55,693 INFO: Lock owner: db1; I am db3
Dec 14 09:17:55 srvdb3 patroni[337821]: 2022-12-14 09:17:55,697 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:17:55 srvdb3 patroni[337821]: 2022-12-14 09:17:55,697 INFO: no action. I am (db3), a secondary, and following a leader (db1)
Dec 14 09:18:05 srvdb3 patroni[337821]: 2022-12-14 09:18:05,693 INFO: Lock owner: db1; I am db3
Dec 14 09:18:05 srvdb3 patroni[337821]: 2022-12-14 09:18:05,696 ERROR: Failed to drop replication slot 'db2'
Dec 14 09:18:05 srvdb3 patroni[337821]: 2022-12-14 09:18:05,744 INFO: no action. I am (db3), a secondary, and following a leader (db1)
lines 46-101/101 (END)
`
