### ISSUE TITLE
question: patroni_raft_controller 

### ISSUE THREAD

**Issue by bagafoot** [zalando/patroni#2487]
I'm trying imlement pure raft feature with 3 nodes, single patroni cluster and 2 patroni_raft_controller 
node 1 raft conf (patroni init)
```
raft:
  data_dir: /var/lib/pgsql/raft
  self_addr: :172.17.30.81:6666
#  partner_addrs: ['172.17.30.83:6666','172.17.30.82:6666']
  partner_addrs:
  - 172.17.30.82:6666
  - 172.17.30.83:6666
```

node2: (patroni_raft_controller )   command : patroni_raft_controller  .patroni2.yaml &
```
raft:
  data_dir: /var/lib/pgsql/raft
  self_addr: :172.17.30.82:6666
#  partner_addrs: ['172.17.30.81:6666','172.17.30.83:6666']
  partner_addrs:
  - 172.17.30.81:6666
  - 172.17.30.83:6666
```

node3: (patroni_raft_controller ) command :  patroni_raft_controller  .patroni2.yaml &
```
raft:
  data_dir: /var/lib/pgsql/raft
  self_addr: :172.17.30.83:6666
#  partner_addrs: ['172.17.30.81:6666','172.17.30.82:6666']
  partner_addrs:
  - 172.17.30.81:6666
  - 172.17.30.82:6666
```

after starting patroni service I get WARNING: failed to resolve host :172.17.30.81

WARNING: failed to resolve hostname: :172.17.30.82
2022-12-09 17:05:49,317 WARNING: failed to resolve host :172.17.30.81
2022-12-09 17:05:49,317 WARNING: failed to resolve hostname: :172.17.30.81
2022-12-09 17:05:54,354 WARNING: failed to resolve host :172.17.30.82
2022-12-09 17:05:54,354 WARNING: failed to resolve hostname: :172.17.30.82

```
patronictl -c  .patroni2.yaml show-config
2022-12-14 11:06:00,848 - WARNING - failed to resolve host :172.17.30.81
2022-12-14 11:06:00,849 - WARNING - failed to resolve hostname: :172.17.30.81
2022-12-14 11:06:00,852 - WARNING - failed to resolve host :172.17.30.83
2022-12-14 11:06:00,852 - WARNING - failed to resolve hostname: :172.17.30.83
2022-12-14 11:06:00,852 - WARNING - failed to resolve host :172.17.30.82
2022-12-14 11:06:00,852 - WARNING - failed to resolve hostname: :172.17.30.82

```

what is wrong in config  ?
and when I check listen port raft binding on ipv6  is it relate with that
![image](https://user-images.githubusercontent.com/30403489/207542007-8fc8aa10-a291-4294-bcc2-fcfe8d30fef0.png)

is there any docs abount patroni_raft_controller metrics?

![image](https://user-images.githubusercontent.com/30403489/207541465-c8016579-8b89-4d88-a296-66df466449b2.png)
