### ISSUE TITLE
patroni with pure raft switchover issue

### ISSUE THREAD

**Issue by bagafoot** [zalando/patroni#2497]
got 3 nodes with last version of patroni, Standby Leader is in recovery mode. When trying switchover, everyting working fine  but TL remain the same.
patronictl version
`patronictl version 2.1.5`

 patronictl -c .patroni2.yaml show-config
```
loop_wait: 10
maximum_lag_on_failover: 0
postgresql:
  parameters:
    archive_command: /bin/true
    archive_mode: 'on'
    autovacuum: true
    autovacuum_max_workers: 3
    autovacuum_work_mem: 32MB
    backend_flush_after: 512kB
    bgwriter_delay: 50ms
    bgwriter_flush_after: 512kB
    bgwriter_lru_maxpages: 1000
    bgwriter_lru_multiplier: 10.0
    checkpoint_completion_target: 0.9
    checkpoint_flush_after: 256kB
    checkpoint_timeout: 5min
    checkpoint_warning: 30s
    default_statistics_target: 10000
    effective_cache_size: 512MB
    effective_io_concurrency: 2
    fsync: true
    full_page_writes: true
    hot_standby: 'on'
    hot_standby_feedback: 'on'
    huge_pages: 'off'
    log_autovacuum_min_duration: 0
    log_checkpoints: true
    log_connections: true
    log_destination: stderr
    log_disconnections: true
    log_line_prefix: 't[%m] p[%p] hp[%r] db[%d] u[%u] a[%a] tx[%x:%v] s[%c:%l] e[%e] i[%i] '
    log_lock_waits: true
    log_min_duration_statement: 0
    log_rotation_age: 1h
    log_rotation_size: 0
    log_temp_files: 0
    log_truncate_on_rotation: true
    logging_collector: true
    maintenance_work_mem: 32MB
    max_files_per_process: 1000
    max_parallel_maintenance_workers: 2
    max_parallel_workers: 8
    max_parallel_workers_per_gather: 2
    max_prepared_transactions: 600
    max_replication_slots: 10
    max_stack_depth: 2MB
    max_wal_senders: 10
    max_wal_size: 128MB
    max_worker_processes: 16
    min_wal_size: 64MB
    shared_buffers: 128MB
    superuser_reserved_connections: 50
    synchronous_commit: remote_apply
    temp_file_limit: 2097152
    track_activity_query_size: 2048
    track_commit_timestamp: true
    track_functions: all
    track_io_timing: true
    unix_socket_directories: /var/run/postgresql
    unix_socket_permissions: 493
    wal_buffers: 16MB
    wal_compression: true
    wal_keep_segments: 64
    wal_level: logical
    wal_log_hints: true
    wal_sync_method: fdatasync
    work_mem: 4MB
  slots:
    permanent_physical_slot_name:
    - name: patroni
      type: physical
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
standby_cluster:
  create_replica_methods:
  - basebackup
  host: 172.17.30.133
  port: 5432
  primary_slot_name: patroni
synchronous_mode: false
synchronous_mode_strict: false
ttl: 30
```

![patoni](https://user-images.githubusercontent.com/30403489/208658634-9223eb4f-c28e-4ad8-8eae-253dece8ac7b.PNG)

![image](https://user-images.githubusercontent.com/30403489/208659816-7d058cd6-76e4-4b56-a40c-617feb0ee759.png)
