### ISSUE TITLE
Issue with pg_hba.conf generation

### ISSUE THREAD

**Issue by Kimi450** [zalando/patroni#2505]
**Describe the bug**

Discalimer: Im just starting out with Postgres and Patroni so bare with me.

When using `patronictl edit-config` and adding a section for `pg_hba` , the `pg_hba.conf` file doesnt seem to be updated (ever). The only way to use a custom file is by pointing `hba_file` to a custom conf file instead. 

There is a note in the release notes [here](https://patroni.readthedocs.io/en/latest/releases.html?highlight=pg_hba#version-1-3) which says that Patroni will ignore the `pg_hba` section of the config if a Postgres config called `hba_file` is set. Even if this isnt present in patroni config, there is a default value in 'postgresql.conf'. And setting the `hba_file` value to an empty string doesnt seem to help. I think this note shouldve also been in the docs [here](https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst#postgresql)).

I might just be doing something wrong cause I couldnt really find anyone else facing this issue. 

**To Reproduce**
- [Install the helm chart](https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md#helm-chart) for the operator
- [install the basic manifest](https://github.com/zalando/postgres-operator/blob/master/docs/quickstart.md#create-a-postgres-cluster) which doesnt actually have any special config as far as I can see and just runs a Spilo image.
- exec into the pod
- Edit the config by running `patronictl edit-config` and add this section under `postgresql` inline with `parameters`
  ```
   pg_hba:
   - local all postgres  ident
   - host all all 0.0.0.0/0 md5
   - host replication replicator 0.0.0.0/0 md5
  ```
- `cat pgdata/pgroot/data/pg_hba.conf` to see that the file is not updated
- adding `hba_conf: ''` to `parameters` in edit-config doesnt help either

**Expected behavior**
`pg_hba.conf` file should be updated automatically and if this section is ignored if `hba_file` is set then this should be added to configuration docs.

**Screenshots**
Pic for default HBA file loc
![image](https://user-images.githubusercontent.com/24758074/209972506-8b43ecae-e60b-402a-b31a-b2df6dd73afa.png)

Pic to show edit sequence
![image](https://user-images.githubusercontent.com/24758074/209972194-4c2941f2-b61c-46d6-b188-fa92d6f0d056.png)

**Environment**
- Patroni version: patroni 2.1.4
- PostgreSQL version: postgres (PostgreSQL) 14.4 (Ubuntu 14.4-1.pgdg18.04+1)
- DCS (and its version): I dont know how to get this info but Im going to guess its using etcd?

**Patroni configuration file**
Im guessing this is the patronictl.yml file, note 100% sure. Strange that this file is having a diff section for pg_hba from what is shown under show-config

```
root@acid-minimal-cluster-0:/home/postgres# cat /home/postgres/.config/patroni/patronictl.yaml
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_mode: 'on'
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.05
        checkpoint_completion_target: 0.9
        hot_standby: 'on'
        log_autovacuum_min_duration: 0
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_lock_waits: 'on'
        log_min_duration_statement: 500
        log_statement: ddl
        log_temp_files: 0
        max_connections: 100
        max_replication_slots: 10
        max_wal_senders: 10
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        track_functions: all
        wal_compression: 'on'
        wal_level: hot_standby
        wal_log_hints: 'on'
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - auth-host: md5
  - auth-local: trust
  post_init: /scripts/post_init.sh "zalandos"
  users:
    zalandos:
      options:
      - CREATEDB
      - NOLOGIN
      password: ''
kubernetes:
  bypass_api_service: true
  labels:
    application: spilo
  port: tcp://10.96.0.1:443
  port_443_tcp: tcp://10.96.0.1:443
  port_443_tcp_addr: 10.96.0.1
  port_443_tcp_port: '443'
  port_443_tcp_proto: tcp
  ports:
  - name: postgresql
    port: 5432
  role_label: spilo-role
  scope_label: cluster-name
  service_host: 10.96.0.1
  service_port: '443'
  service_port_https: '443'
  use_endpoints: true
namespace: kimi450
postgresql:
  authentication:
    replication:
      password: pJ264RN7FZaiNVTU3GimoSJLhi0rNcU9UR8losF14gTRsawfOHNu99lPHg5dQm5U
      username: standby
    superuser:
      password: mjEXwMjqM1bRfzrIN09dMFrFIneuV0B0lQuvGc2L5jUpy4FbfRsTmHcBGyyLjWWs
      username: postgres
  basebackup_fast_xlog:
    command: /scripts/basebackup.sh
    retries: 2
  bin_dir: /usr/lib/postgresql/14/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos true
  connect_address: 172.17.0.23:5432
  create_replica_method:
  - basebackup_fast_xlog
  data_dir: /home/postgres/pgdata/pgroot/data
  listen: '*:5432'
  name: acid-minimal-cluster-0
  parameters:
    archive_command: /bin/true
    bg_mon.history_buckets: 120
    bg_mon.listen_address: 0.0.0.0
    extwlist.custom_path: /scripts
    extwlist.extensions: btree_gin,btree_gist,citext,extra_window_functions,first_last_agg,hll,hstore,hypopg,intarray,ltree,pgcrypto,pgq,pgq_node,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,timescaledb,pg_partman
    log_destination: csvlog
    log_directory: ../pg_log
    log_file_mode: '0644'
    log_filename: postgresql-%u.log
    log_rotation_age: 1d
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    pg_stat_statements.track_utility: 'off'
    shared_buffers: 100MB
    shared_preload_libraries: bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,timescaledb,pg_cron,pg_stat_kcache
    ssl: 'on'
    ssl_cert_file: /run/certs/server.crt
    ssl_key_file: /run/certs/server.key
  pg_hba:
  - local   all             all                                   trust
  - hostssl all             +zalandos    127.0.0.1/32       pam
  - host    all             all                127.0.0.1/32       md5
  - hostssl all             +zalandos    ::1/128            pam
  - host    all             all                ::1/128            md5
  - local   replication     standby                    trust
  - hostssl replication     standby all                md5
  - hostnossl all           all                all                reject
  - hostssl all             +zalandos    all                pam
  - hostssl all             all                all                md5
  pgpass: /run/postgresql/pgpass
  use_unix_socket: true
  use_unix_socket_repl: true
restapi:
  connect_address: 172.17.0.23:8008
  listen: :8008
scope: acid-minimal-cluster
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 33554432
postgresql:
  parameters:
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_vacuum_scale_factor: 0.05
    checkpoint_completion_target: 0.9
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_statement: ddl
    log_temp_files: 0
    max_connections: 100
    max_replication_slots: 10
    max_wal_senders: 10
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    track_functions: all
    wal_compression: 'on'
    wal_level: hot_standby
    wal_log_hints: 'on'
  pg_hba:
  - local all postgres  ident
  - host all all 0.0.0.0/0 md5
  - host replication replicator 0.0.0.0/0 md5
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30

```

**Have you checked Patroni logs?**
Not sure where to find this, sorry

**Have you checked PostgreSQL logs?**
Dont think this is a postgres issue so I did not check these logs

**Have you tried to use GitHub issue search?**
Yes, cant find anything useful

**Additional context**
N/A
