### ISSUE TITLE
master tag was not registered in Consul after patroni failure

### ISSUE THREAD

**Issue by yinan8128** [zalando/patroni#2517]
**Describe the bug**
2023-01-08 @ 00:30:43 patroni failure was happened as "Max retries exceeded" error, after that patroni-cluster-vm01 is still leader, patroni log shows"Register service pgclusteraa, params {... 'tags': ['master']}", but actually Patroni Node master tag was not registered in Consul, please suggest, thanks
```
[root@patroni-cluster-vm01 ~]# curl -s localhost:8500/v1/catalog/services | jq .
...
  "pgclusteraa": [
    "replica"
  ],
...
}
```

**Environment**
- Patroni version: 2.0.1
- PostgreSQL version: 11.11
- DCS (and its version): consul 1.2.2-6

**Patroni configuration file**
```
scope: pgclusteraa
name: patroni-cluster-vm01

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.10.10.4:8008

consul:
  host: 127.0.0.1:8500
  checks: []
  register_service: true

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        archive_mode: "on"
        archive_command: /bin/true
        archive_timeout: 1800s
        autovacuum: "on"
        autovacuum_work_mem: 1GB
        autovacuum_vacuum_threshold: 50
        autovacuum_vacuum_cost_delay: 2ms
        autovacuum_vacuum_cost_limit: 8000
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_threshold: 50
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_max_workers: 6
        auto_explain.log_min_duration: 60000
        auto_explain.log_nested_statements: true
        bgwriter_delay: 50ms
        bgwriter_lru_maxpages: 4000
        bgwriter_lru_multiplier: 4
        checkpoint_completion_target: 0.7
        checkpoint_timeout: 30min
        config_file: /var/lib/pgsql/11/data/postgresql.conf
        constraint_exclusion: partition
        cron.database_name: postgres
        datestyle: "ISO, MDY"
        default_statistics_target: 100
        default_text_search_config: "pg_catalog.english"
        effective_cache_size: "49517MB"
        hot_standby: "on"
        idle_in_transaction_session_timeout: 10min
        lc_messages: 'C'
        lc_monetary: 'C'
        lc_numeric: 'C'
        lc_time: 'C'
        lock_timeout: 30s
        log_autovacuum_min_duration: 500
        log_checkpoints: "off"
        log_checkpoints: "off"
        log_connections: "off"
        log_destination: "stderr"
        log_directory: "/var/log/postgresql"
        log_disconnections: "off"
        log_duration: "off"
        log_filename: 'postgresql.log'
        log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
        log_lock_waits: "on"
        log_min_duration_statement: "5s"
        log_rotation_age: 0
        log_rotation_size: 0
        log_statement: "ddl"
        log_temp_files: 1MB
        log_timezone: "UTC"
        log_truncate_on_rotation: "off"
        logging_collector: "on"
        maintenance_work_mem: 2GB
        max_connections: 1000
        max_replication_slots: 10
        max_wal_senders: 10
        max_wal_size: "30720"
        min_wal_size: 1024
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        random_page_cost: 1.1
        shared_buffers: 16505MB
        shared_preload_libraries: 'pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron'
        statement_timeout: 10min
        temp_file_limit: 5GB
        timezone: "UTC"
        track_io_timing: "on"
        unix_socket_directories: '/var/run/postgresql'
        wal_buffers: -1
        wal_compression: "on"
        wal_keep_segments: "10"
        wal_level: replica
        wal_log_hints: "on"
        work_mem: "33MB"
      recovery_conf:
        restore_command: /bin/true
  initdb:
    - encoding: UTF8
    - data-checksums
    - locale: en_US.UTF-8
    - lc-collate: en_US.UTF-8
    - lc-ctype: en_US.UTF-8

  users:
    replicator:
      password: bbb
      options:
        - replication

postgresql:
  listen: '*'
  connect_address: 10.10.10.4:5432
  data_dir: /var/lib/pgsql/11/data
  bin_dir: /usr/pgsql-11/bin
  config_dir: /var/lib/pgsql/11/data
  restore: /usr/bin/patroni_wale_restore
  pgpass: /tmp/pgpass
  authentication:
    pg_rewind:
      username: postgres
      password: aaa
    replication:
      username: replicator
      password: bbb
      network: 0.0.0.0/0
    superuser:
      username: postgres
      password: aaa
  callbacks:
    on_start: /etc/patroni/callback.sh
    on_stop: /etc/patroni/callback.sh
    on_role_change: /etc/patroni/callback.sh
  basebackup:
    - verbose
    - checkpoint: 'fast'

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "process": %(process)d, "thread": %(thread)d, "level": "%(levelname)s", "message": "%(message)s"}'
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: /bin/true
    archive_mode: 'on'
    archive_timeout: 1800s
    auto_explain.log_min_duration: 60000
    auto_explain.log_nested_statements: true
    autovacuum: 'on'
    autovacuum_analyze_scale_factor: 0.05
    autovacuum_analyze_threshold: 50
    autovacuum_max_workers: 6
    autovacuum_vacuum_cost_delay: 2ms
    autovacuum_vacuum_cost_limit: 8000
    autovacuum_vacuum_scale_factor: 0.01
    autovacuum_vacuum_threshold: 50
    autovacuum_work_mem: 1GB
    bgwriter_delay: 50ms
    bgwriter_lru_maxpages: 4000
    bgwriter_lru_multiplier: 4
    checkpoint_completion_target: 0.7
    checkpoint_timeout: 30min
    config_file: /var/lib/pgsql/11/data/postgresql.conf
    constraint_exclusion: partition
    cron.database_name: postgres
    datestyle: ISO, MDY
    default_statistics_target: 100
    default_text_search_config: pg_catalog.english
    effective_cache_size: 49517MB
    hot_standby: 'on'
    idle_in_transaction_session_timeout: 10min
    lc_messages: C
    lc_monetary: C
    lc_numeric: C
    lc_time: C
    lock_timeout: 30s
    log_autovacuum_min_duration: 500
    log_checkpoints: 'off'
    log_connections: 'off'
    log_destination: stderr
    log_directory: /var/log/postgresql
    log_disconnections: 'off'
    log_duration: 'off'
    log_filename: postgresql.log
    log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
    log_lock_waits: 'on'
    log_min_duration_statement: 5s
    log_rotation_age: 0
    log_rotation_size: 0
    log_statement: ddl
    log_temp_files: 1MB
    log_timezone: UTC
    log_truncate_on_rotation: 'off'
    logging_collector: 'on'
    maintenance_work_mem: 2GB
    max_connections: 1000
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: '30720'
    min_wal_size: 1024
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    random_page_cost: 1.1
    shared_buffers: 16505MB
    shared_preload_libraries: pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron
    statement_timeout: 10min
    temp_file_limit: 5GB
    timezone: UTC
    track_io_timing: 'on'
    unix_socket_directories: /var/run/postgresql
    wal_buffers: -1
    wal_compression: 'on'
    wal_keep_segments: '10'
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 33MB
  recovery_conf:
    restore_command: /bin/true
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
synchronous_mode: true
ttl: 30
```

**Have you checked Patroni logs?**
Time                         message   patroni.message
2023-01-08 @ 00:30:56.708	 - 	Lock owner: patroni-cluster-vm01; I am patroni-cluster-vm01	
2023-01-08 @ 00:30:56.707	 - 	no action.  i am the leader with the lock	
2023-01-08 @ 00:30:54.277	 - 	Register service pgclusteraa, params {'service_id': 'pgclusteraa/patroni-cluster-vm01', 'address': '10.245.43.38', 'port': 5432, 'check': {'http': 'http://10.245.43.38:8008/master', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['master']}
2023-01-08 @ 00:30:54.260	 - 	Synchronous standby status assigned to ['patroni-cluster-vm02']	
2023-01-08 @ 00:30:52.243	server signaled	 - 	
2023-01-08 @ 00:30:52.238	 - 	Assigning synchronous standby status to ['patroni-cluster-vm02']	
2023-01-08 @ 00:30:52.222	 - 	Lock owner: patroni-cluster-vm01; I am patroni-cluster-vm01	
2023-01-08 @ 00:30:51.210	server promoting	 - 	
2023-01-08 @ 00:30:51.210	 - 	cleared rewind state after becoming the leader	
2023-01-08 @ 00:30:51.209	 - 	promoted self to leader because i had the session lock	
2023-01-08 @ 00:30:47.868	 - 	Register service pgclusteraa, params {'service_id': 'pgclusteraa/patroni-cluster-vm01', 'address': '10.245.43.38', 'port': 5432, 'check': {'http': 'http://10.245.43.38:8008/replica', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['replica']}	
2023-01-08 @ 00:30:47.846	 - 	Software Watchdog activated with 25 second timeout, timing slack 15 seconds	
2023-01-08 @ 00:30:47.820	server closed the connection unexpectedly	 - 	
2023-01-08 @ 00:30:47.820	This probably means the server terminated abnormally	 - 	
2023-01-08 @ 00:30:47.820	before or while processing the request.	 - 	
2023-01-08 @ 00:30:47.820	connection to server was lost	 - 	
2023-01-08 @ 00:30:47.809	 - 	Lock owner: patroni-cluster-vm01; I am patroni-cluster-vm01	
2023-01-08 @ 00:30:47.809	 - 	establishing a new patroni connection to the postgres cluster	
2023-01-08 @ 00:30:47.805	 - 	Loop time exceeded, rescheduling immediately.	
2023-01-08 @ 00:30:47.804	 - 	demoted self because DCS is not accessible and i was a leader	
2023-01-08 @ 00:30:47.801	localhost:5432 - accepting connections	 - 	
2023-01-08 @ 00:30:47.790	localhost:5432 - accepting connections	 - 	
2023-01-08 @ 00:30:46.886	[2023-01-08 00:30:46.885 UTC] p=5346:6@ c=@/: LOG:  redirecting log output to logging collector process	 - 	
2023-01-08 @ 00:30:46.886	[2023-01-08 00:30:46.885 UTC] p=5346:7@ c=@/: HINT:  Future log output will appear in directory "/var/log/postgresql".	 - 	
2023-01-08 @ 00:30:46.786	[2023-01-08 00:30:46.786 UTC] p=5346:5@ c=@/: LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"	 - 	
2023-01-08 @ 00:30:46.783	[2023-01-08 00:30:46.782 UTC] p=5346:3@ c=@/: LOG:  listening on IPv4 address "0.0.0.0", port 5432	 - 	
2023-01-08 @ 00:30:46.783	[2023-01-08 00:30:46.783 UTC] p=5346:4@ c=@/: LOG:  listening on IPv6 address "::", port 5432	 - 	
2023-01-08 @ 00:30:46.779	[2023-01-08 00:30:46.779 UTC] p=5346:1@ c=@/: LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...	 - 	
2023-01-08 @ 00:30:46.779	[2023-01-08 00:30:46.779 UTC] p=5346:2@ c=@/: LOG:  pg_stat_kcache.linux_hz is set to 1000000	 - 	
2023-01-08 @ 00:30:46.775	localhost:5432 - no response	 - 	
2023-01-08 @ 00:30:46.765	 - 	postmaster pid=5346	patroni-cluster-vm01
2023-01-08 @ 00:30:43.560	File "/usr/local/lib/python3.6/site-packages/patroni/utils.py", line 344, in __call__	 - 	
2023-01-08 @ 00:30:43.560	raise RetryFailedError("Exceeded retry deadline")	 - 	
2023-01-08 @ 00:30:43.560	patroni.utils.RetryFailedError: 'Exceeded retry deadline'	 - 	
2023-01-08 @ 00:30:43.560	 - 	Error communicating with DCS	
2023-01-08 @ 00:30:43.559	urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/kv/service/pgclusteraa/?recurse=1 (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)",))	 - 	
2023-01-08 @ 00:30:43.559	During handling of the above exception, another exception occurred:	 - 	
2023-01-08 @ 00:30:43.559	Traceback (most recent call last):	 - 	
2023-01-08 @ 00:30:43.559	File "/usr/local/lib/python3.6/site-packages/patroni/dcs/consul.py", line 309, in _load_cluster	 - 	
2023-01-08 @ 00:30:43.559	_, results = self.retry(self._client.kv.get, path, recurse=True)	 - 	
2023-01-08 @ 00:30:43.559	File "/usr/local/lib/python3.6/site-packages/patroni/dcs/consul.py", line 232, in retry	 - 	
2023-01-08 @ 00:30:43.559	return self._retry.copy()(*args, **kwargs)	 - 	
2023-01-08 @ 00:30:43.558	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen	 - 	
2023-01-08 @ 00:30:43.558	method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]	 - 	
2023-01-08 @ 00:30:43.558	File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment	 - 	
2023-01-08 @ 00:30:43.558	raise MaxRetryError(_pool, url, error or ResponseError(cause))	 - 	
2023-01-08 @ 00:30:43.557	response = conn.urlopen(method, u.request_uri, **kw)	 - 	
2023-01-08 @ 00:30:43.556	return self.urlopen(method, url, **extra_kw)	 - 	
2023-01-08 @ 00:30:43.556	File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 376, in urlopen	 - 	
2023-01-08 @ 00:30:43.555	return func(*args, **kwargs)	 - 	
2023-01-08 @ 00:30:43.555	File "/usr/local/lib/python3.6/site-packages/consul/base.py", line 554, in get	 - 	
2023-01-08 @ 00:30:43.555	params=params)	 - 	
2023-01-08 @ 00:30:43.555	File "/usr/local/lib/python3.6/site-packages/patroni/dcs/consul.py", line 117, in wrapper	 - 	
2023-01-08 @ 00:30:43.555	return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))	 - 	
2023-01-08 @ 00:30:43.555	File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 75, in request	 - 	
2023-01-08 @ 00:30:43.555	method, url, fields=fields, headers=headers, **urlopen_kw	 - 	
2023-01-08 @ 00:30:43.555	File "/usr/local/lib/python3.6/site-packages/urllib3/request.py", line 96, in request_encode_url	 - 	
2023-01-08 @ 00:30:43.554	self._raise_timeout(err=e, url=url, timeout_value=read_timeout)	 - 	
2023-01-08 @ 00:30:43.554	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 341, in _raise_timeout	 - 	
2023-01-08 @ 00:30:43.554	self, url, "Read timed out. (read timeout=%s)" % timeout_value	 - 	
2023-01-08 @ 00:30:43.554	urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)	 - 	
2023-01-08 @ 00:30:43.554	During handling of the above exception, another exception occurred:	 - 	
2023-01-08 @ 00:30:43.554	Traceback (most recent call last):	 - 	
2023-01-08 @ 00:30:43.554	File "/usr/local/lib/python3.6/site-packages/patroni/utils.py", line 333, in __call__	 - 	
2023-01-08 @ 00:30:43.553	chunked=chunked,	 - 	
2023-01-08 @ 00:30:43.553	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 451, in _make_request	 - 	
2023-01-08 @ 00:30:43.552	File "/usr/lib64/python3.6/socket.py", line 586, in readinto	 - 	
2023-01-08 @ 00:30:43.552	return self._sock.recv_into(b)	 - 	
2023-01-08 @ 00:30:43.552	socket.timeout: timed out	 - 	
2023-01-08 @ 00:30:43.552	During handling of the above exception, another exception occurred:	 - 	
2023-01-08 @ 00:30:43.552	Traceback (most recent call last):	 - 	
2023-01-08 @ 00:30:43.552	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen	 - 	
2023-01-08 @ 00:30:43.550	response.begin()	 - 	
2023-01-08 @ 00:30:43.550	File "/usr/lib64/python3.6/http/client.py", line 297, in begin	 - 	
2023-01-08 @ 00:30:43.550	version, status, reason = self._read_status()	 - 	
2023-01-08 @ 00:30:43.550	File "/usr/lib64/python3.6/http/client.py", line 258, in _read_status	 - 	
2023-01-08 @ 00:30:43.550	line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")	 - 	
2023-01-08 @ 00:30:43.547	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 444, in _make_request	 - 	
2023-01-08 @ 00:30:43.547	httplib_response = conn.getresponse()	 - 	
2023-01-08 @ 00:30:43.547	File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse	 - 	
2023-01-08 @ 00:30:43.546	 - 	get_cluster	
2023-01-08 @ 00:30:43.546	Traceback (most recent call last):	 - 	
2023-01-08 @ 00:30:43.546	File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 449, in _make_request	 - 	
2023-01-08 @ 00:30:43.546	six.raise_from(e, None)	 - 	
2023-01-08 @ 00:30:43.546	File "<string>", line 3, in raise_from	 - 	
2023-01-08 @ 00:30:43.534	{"time": "2023-01-08 00:30:43,533", "name": "patroni.utils", "process": 3518, "thread": 140060513273664, "level": "WARNING", "message": "Retry got exception: HTTPConnectionPool(host='127.0.0.1', port=8500): Max retries exceeded with url: /v1/kv/service/pgclusteraa/?recurse=1 (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=8500): Read timed out. (read timeout=3.3333333333333335)",))"}	 - 	
2023-01-08 @ 00:30:22.747	 - 	no action.  i am the leader with the lock	
2023-01-08 @ 00:30:22.714	 - 	Lock owner: patroni-cluster-vm01; I am patroni-cluster-vm01	

**Have you checked PostgreSQL logs?**
2023-01-08 @ 00:30:51.436	database system is ready to accept connections
2023-01-08 @ 00:30:51.434	checkpoint starting: force	
2023-01-08 @ 00:30:51.286	archive recovery complete	
2023-01-08 @ 00:30:51.242	selected new timeline ID: 56	
2023-01-08 @ 00:30:51.212	received promote request	
2023-01-08 @ 00:30:51.212	redo is not required
...
2023-01-08 @ 00:30:46.922	database system is ready to accept read only connections	
2023-01-08 @ 00:30:46.921	consistent recovery state reached at 1016/61000098	
2023-01-08 @ 00:30:46.921	invalid record length at 1016/61000098: wanted 24, got 0	
2023-01-08 @ 00:30:46.892	entering standby mode
2023-01-08 @ 00:30:46.890	database system was shut down at 2023-01-08 00:30:45 UTC	
2023-01-08 @ 00:30:46.272	database system is shut down
...
2023-01-08 @ 00:30:45.475	checkpoint starting: shutdown immediate	
2023-01-08 @ 00:30:45.445	shutting down
...
2023-01-08 @ 00:30:43.587	received fast shutdown request	

**Additional context**
