### ISSUE TITLE
The leader does not change when the connection between DCs is broken

### ISSUE THREAD

**Issue by EcksRay** [zalando/patroni#2523]
**Describe the bug**
We have 3 DC:
In each DC, there are 2 Patroni servers, 1 ETCD server, 1 haproxy server

I simulated connection failure between 1st Data Center and 2nd, both DC are up, but 1st and 2nd DC's are doesn't "see" each other. At the same time, both DCs have a stable connection to 3rd DC.

In this case, Patroni leader still remains in 1st DC. But all clients that get connects to 2nd DC will receive errors when they try to write to the database.

**To Reproduce**
Create 3 patroni-cluster in separated subnets. Disable/Drop all route rule's from 1st network to 2nd.

**Expected behavior**
Leader will become the Patroni-server from 3rd DC.

**Environment**
- Patroni version: 2.1.4
- PostgreSQL version: 14.4
- DCS (and its version): etcd, 3.5.6
- Haproxy: 2.6.1

**Patroni configuration file**
```
scope: dmpatroni_cluster
namespace: /dmtest/
name: dmpgsql01

restapi:
  listen: 0.0.0.0:8008
  connect_address: 192.168.1.81:8008

etcd3:
  hosts:
  - 192.168.1.83:2379
  - 192.168.2.17:2379
  - 192.168.3.25:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 0
    synchronous_standby_names: '*'
    synchronous_mode: true
    synchronous_mode_strict: false
    master_start_timeout: 10
    master_stop_timeout: 0
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 500
        shared_buffers: 4GB
        effective_cache_size: 1GB
        maintenance_work_mem: 512MB
        checkpoint_completion_target: 0.7
        wal_buffers: 16MB
        default_statistics_target: 100
        random_page_cost: 1.1
        effective_io_concurrency: 200
        work_mem: 2621kB
        min_wal_size: 80MB
        max_wal_size: 1GB
        max_worker_processes: 40
        max_parallel_workers_per_gather: 10
        max_parallel_workers: 40
        max_parallel_maintenance_workers: 10
        max_locks_per_transaction: 64
        max_prepared_transactions: 0
        wal_level: logical
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_segments: 8
        logging_collector: on
        log_destination: csvlog
        log_directory: pg_log
        log_min_messages: warning
        log_min_error_statement: error
        log_min_duration_statement: 1000
        log_duration: off
        log_statement: all

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - local all all trust
  - host postgres postgres 127.0.0.1/32 trust
  - host all all 0.0.0.0/0 scram-sha-256
  - host all all 192.168.1.81/32 scram-sha-256
  - host all all 192.168.1.82/32 scram-sha-256
  - host all all 192.168.2.121/32 scram-sha-256
  - host all all 192.168.2.122/32 scram-sha-256
  - host all all 192.168.3.22/32 scram-sha-256
  - host replication sa0000mtspgrepluser 127.0.0.1/32 scram-sha-256
  - host replication sa0000mtspgrepluser 192.168.1.81/32 scram-sha-256
  - host replication sa0000mtspgrepluser 192.168.1.82/32 scram-sha-256
  - host replication sa0000mtspgrepluser 192.168.2.121/32 scram-sha-256
  - host replication sa0000mtspgrepluser 192.168.2.122/32 scram-sha-256
  - host replication sa0000mtspgrepluser 192.168.3.22/32 scram-sha-256
  users:
    repluser:
      password: 'testrepl'
      options:
        - replication
    patroni_su:
      password: 'testpatroni'
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 192.168.1.81:5432
  data_dir: /var/lib/pgsql/14/data
  bin_dir: /usr/pgsql-14/bin/
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: repluser
      password: 'testrepl'
    superuser:
      username: patroni_su
      password: 'testpatroni'
  parameters:
    unix_socket_directories: '/var/run/postgresql'
    port: 5432
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 0
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=demo-cluster-1 archive-push "%p"
    archive_mode: 'on'
    checkpoint_completion_target: 0.7
    effective_cache_size: 1GB
    log_destination: stderr
    log_directory: /var/lib/pgsql/14/log
    log_rotation_age: 7d
    log_rotation_size: 0
    log_truncate_on_rotation: true
    logging_collector: true
    maintenance_work_mem: 512MB
    max_connections: 500
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: 1GB
    min_wal_size: 80MB
    shared_buffers: 4GB
    track_commit_timestamp: false
    wal_compression: true
    wal_keep_segments: 8
    wal_level: replica
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
synchronous_standby_names: '*'
ttl: 30
```

**Have you checked Patroni logs?**

Jan 12 12:58:33 dmpgsql01 patroni[26481]: 2023-01-12 12:58:33,577 ERROR: watchprefix failed: ProtocolError('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Jan 12 12:58:33 dmpgsql01 patroni[26481]: 2023-01-12 12:58:33,582 ERROR: Request to server http://192.168.2.103:2379 failed: MaxRetryError("HTTPConnectionPool(host='192.168.2.103', port=2379): Max retries exceeded with url: /v3/kv/range (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))",)
Jan 12 12:58:33 dmpgsql01 patroni[26481]: 2023-01-12 12:58:33,582 INFO: Reconnection allowed, looking for another server.
Jan 12 12:58:33 dmpgsql01 patroni[26481]: 2023-01-12 12:58:33,582 INFO: Retrying on http://192.168.3.25:2379
Jan 12 12:58:33 dmpgsql01 patroni[26481]: 2023-01-12 12:58:33,615 INFO: Selected new etcd server http://192.168.3.25:2379
Jan 12 12:58:41 dmpgsql01 patroni[26481]: 2023-01-12 12:58:41,334 INFO: no action. I am (dmpgsql01), the leader with the lock

Jan 12 12:58:31 dmpgsql11 patroni[4831]: 2023-01-12 12:58:31,558 INFO: no action. I am (dmpgsql11), a secondary, and following a leader (dmpgsql01)
Jan 12 12:58:31 dmpgsql11 patroni[4831]: 2023-01-12 12:58:31,634 ERROR: watchprefix failed: ProtocolError('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Jan 12 12:58:31 dmpgsql11 patroni[4831]: 2023-01-12 12:58:31,642 ERROR: Request to server http://192.168.1.17:2379 failed: MaxRetryError("HTTPConnectionPool(host='192.168.1.17', port=2379): Max retries exceeded with url: /v3/kv/range (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))",)
Jan 12 12:58:31 dmpgsql11 patroni[4831]: 2023-01-12 12:58:31,642 INFO: Reconnection allowed, looking for another server.
Jan 12 12:58:31 dmpgsql11 patroni[4831]: 2023-01-12 12:58:31,642 INFO: Retrying on http://192.168.3.25:2379
Jan 12 12:58:31 dmpgsql11 patroni[4831]: 2023-01-12 12:58:31,677 INFO: Selected new etcd server http://192.168.3.25:2379
Jan 12 12:58:41 dmpgsql11 patroni[4831]: 2023-01-12 12:58:41,522 INFO: no action. I am (dmpgsql11), a secondary, and following a leader (dmpgsql01)
Jan 12 12:58:51 dmpgsql11 patroni[4831]: 2023-01-12 12:58:51,556 INFO: no action. I am (dmpgsql11), a secondary, and following a leader (dmpgsql01)

**Have you checked PostgreSQL logs?**
-

**Have you tried to use GitHub issue search?**
Yes
