### ISSUE TITLE
patronictl waiting on raft

### ISSUE THREAD

**Issue by aneustroev** [zalando/patroni#2543]
**Describe the bug**
When I try to do something by patronictl, I randomly get a infinite loop with log `INFO - waiting on raft`
Cluster qorum, ha and rest api work well.

**To Reproduce**
for example `patronictl -c <path-to-patroni-config> list` other commands works same

**Environment**
-   Patroni version: 2.1.7
-   PostgreSQL version: 10.22
-   DCS (and its version): Raft

**Patroni configuration file**
```
scope: "main"
name: "db-1"

restapi:
  listen: <ip>:<restport>
  connect_address: <ip>:<restport>
  cafile: /var/lib/postgresql/tls/ca.pem
  certfile: /var/lib/postgresql/tls/server-cert.pem
  keyfile: /var/lib/postgresql/tls/server-key.pem

ctl:
  insecure: false # Allow connections to SSL sites without certs
  certfile: /var/lib/postgresql/tls/server-cert.pem
  keyfile: /var/lib/postgresql/tls/server-key.pem
  cacert: /var/lib/postgresql/tls/ca.pem

raft:
  data_dir: /var/lib/postgresql/raft
  self_addr: <ip1>:<raftport>
  partner_addrs:
    - "<ip1>:<raftport>"
    - "<ip2>:<raftport>"
    - "<ip3>:<raftport>"

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: "false"
      parameters:
        hot_standby: "on"
        wal_log_hints: "on"
        ssl: "on"
        ssl_ciphers: 'HIGH:MEDIUM:+3DES:!aNULL' # allowed SSL ciphers
        ssl_cert_file: '/var/lib/postgresql/tls/server-cert.pem'
        ssl_key_file: '/var/lib/postgresql/tls/server-key.pem'
        ssl_ca_file: '/var/lib/postgresql/tls/ca.pem'
        listen_addresses: "0.0.0.0"
        port: "<pgport>"
        max_connections: "1000"
        timezone: "EST"
        effective_cache_size: "32GB"
        hot_standby_feedback: "on"
        max_wal_senders: "150"
        max_replication_slots: "100"
        track_activities: "on"
        autovacuum_max_workers: "3"
        track_counts: "on"
        track_io_timing: "off"
        track_functions: "none"
        track_activity_query_size: "1024"
        wal_keep_segments: "20000"
        max_wal_size: "3GB"
        min_wal_size: "1GB"
        synchronous_commit: "on"
        wal_level: "logical"
        effective_io_concurrency: "200"
        max_worker_processes: "32"
        max_parallel_workers_per_gather: "16"
        max_parallel_workers: "32"
        shared_preload_libraries: "pg_stat_statements"
        maintenance_work_mem: "4GB"
        temp_buffers: "32MB"
        shared_buffers: "32GB"
        max_standby_streaming_delay: "30s"
        max_standby_archive_delay: "300s"
        work_mem: "4MB"
        wal_buffers: "-1"
        checkpoint_timeout: "5min"
        checkpoint_completion_target: "0.5"
        fsync: "on"
        idle_in_transaction_session_timeout: "7200"

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
    - encoding: UTF8
    - data-checksums

  pg_hba:
    - "local all all trust"
    - hostssl  replication repluser 0.0.0.0/0  md5
    - host  replication repluser 127.0.0.1/32  trust
    - host  all postgres 127.0.0.1/32  trust
    - host  all all 0.0.0.0/0  md5

postgresql:
  listen: "<ip1>:<pgport>"
  connect_address: "<ip1>:<pgport>"
  data_dir: /var/lib/postgresql/data/
  unix_socket_directories: '/var/run/postgresql/'
  pg_hba:
    - "local all all trust"
    - hostssl  replication repluser 0.0.0.0/0  md5
    - host  replication repluser 127.0.0.1/32  trust
    - host  all postgres 127.0.0.1/32  trust
    - host  all all 0.0.0.0/0  md5
  authentication:
    replication:
      username: "repluser"
      password: ""
      sslmode: "verify-full"
      sslrootcert: /var/lib/postgresql/tls/ca.pem
    superuser:
      username: "postgres"
      password: ""
      sslmode: "verify-full"
      sslrootcert: /var/lib/postgresql/tls/ca.pem
    rewind:
      username: "postgres"
      password: ""
      sslmode: "verify-full"
      sslrootcert: /var/lib/postgresql/tls/ca.pem

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

```

**patronictl show-config**
```
I can't because now it is stuck
```

**Have you checked Patroni logs?**
Yes, logs and other functionality looks well.

**Have you checked PostgreSQL logs?**
Yes, logs and other functionality looks well.

**Have you tried to use GitHub issue search?**
Yes, but now found something same
