### ISSUE TITLE
Cannot connect to etcd with TLS

### ISSUE THREAD

**Issue by dsupru** [zalando/patroni#2558]
**Describe the bug**

Hi, I'm seeing this error starting up Patroni:
```
Feb 12 10:40:09 newdb patroni[89648]: 2023-02-12 10:40:09,265 ERROR: Failed to get list of machines from https://192.168.56.4:2379/v2: MaxRetryError('HTTPSConnectionPool(host=\'192.168.56.4\', port=2379): Max retries exceeded with url: /v2/machines (Caused by SSLError(SSLError("read error: Error([(\'SSL routines\', \'ssl3_read_bytes\', \'sslv3 alert bad certificate\')])")))')
Feb 12 10:40:09 newdb patroni[89648]: 2023-02-12 10:40:09,265 INFO: waiting on etcd

```
I created a CA, secret and a key using https://github.com/etcd-io/etcd/tree/main/hack/tls-setup
Etcd works fine. I can curl the cluster: 
```
vagrant@newdb:/etcd/certs$ curl --key secret-key.pem --cert secret.pem --cacert ca.pem https://192.168.56.3:2379/v2/machines

https://192.168.56.2:2379, https://192.168.56.2:4001, https://192.168.56.3:2379, https://192.168.56.3:4001, https://192.168.56.4:2379, https://192.168.56.4:4001
```

**To Reproduce**

3 VMs run Etcd:
- 192.168.56.2
- 192.168.56.3
- 192.168.56.4

Patroni instance runs on 192.168.56.2.
Patroni env:
```
PATRONI_NAME=patroni1
PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
PATRONI_POSTGRESQL_CONNECT_ADDRESS=192.168.56.2:5432
PATRONI_RESTAPI_CONNECT_ADDRESS=192.168.56.2:8008
PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
PATRONI_ETCD_CACERT=/etcd/certs/ca.pem
PATRONI_ETCD_CER=/etcd/certs/secret.pem
PATRONI_ETCD_KEY=/etcd/certs/secret-key.pem
PATRONI_ETCD_PROTOCOL=https
```
(IPs are in the patroni.yml)

1. Create keys with https://github.com/etcd-io/etcd/tree/main/hack/tls-setup
2. Run etcd (docker image: `gcr.io/etcd-development/etcd:v3.4.23`)with the keys from the above step
3. Copy patroni.yml (provided below) and patroni_env(provided above)
4. Start patroni.

**Expected behavior**

I expect Patroni to be able to communicate with etcd.

**Screenshots**

**Environment**
-   Patroni version: 3.0.0
-   PostgreSQL version: 12
-   DCS (and its version): etcd 3.4.23

**Patroni configuration file**
```
scope: postgres
namespace: /db/

etcd:
  hosts:
    - 192.168.56.2:2379
    - 192.168.56.3:2379
    - 192.168.56.4:2379

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  method: pgbackrest
  pgbackrest:
    command: "pgbackrest --stanza=test --log-level-console=info --delta restore"
    keep_existing_recovery_conf: True
    no_params: False
    recovery_conf:
      recovery_target_timeline: latest
      recovery_target_action: promote
      restore_command: "pgbackrest --stanza=test archive-get %f %p"
  dcs:
    ttl: 6
    loop_wait: 2
    retry_timeout: 2
    maximum_lag_on_failover: 1048576
    postgresql:
      parameters:
        wal_level: hot_standby
        hot_standby: "on"
        max_connections: 100
        max_worker_processes: 10
        wal_keep_segments: 3125
        max_wal_senders: 10
        max_replication_slots: 10
        max_locks_per_transaction: 64
        wal_log_hints: "on"
        track_commit_timestamp: "off"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: "pgbackrest --stanza=test archive-push %p"
      recovery_conf:
        recovery_target_timeline: latest
        restore_command: "pgbackrest --stanza=test archive-get %f %p"

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
  # post_init: /usr/local/bin/setup_cluster.sh

  initdb:
    - data-checksums

postgresql:
  use_pg_rewind: true
  use_slots: true
  unix_socket_directories: "/var/run/postgresql" # parent directory of data_dir
  data_dir: /var/lib/postgresql/12/main
  bin_dir: /usr/lib/postgresql/12/bin
  config_dir: /etc/postgresql/12/main
  pgpass: /tmp/pgpass
  pg_hba:
    - local   all             all                                     peer
    - local   replication     all             0.0.0.0/0               peer
    - hostssl all             all             0.0.0.0/0               md5
    - host    all             all             0.0.0.0/0               md5

  authentication:
      [REMOVED]
  create_replica_methods:
    - basebackup
    - pgbackrest
  basebackup:
    max-rate: "100M"
  pgbackrest:
    command: "pgbackrest --stanza=test --log-level-console=info --delta restore"
    keep_data: False
    no_params: True
  parameters:
    wal_level: hot_standby
    hot_standby: "on"
    max_connections: 1000
    max_worker_processes: 10
    wal_keep_segments: 3125 # approximately 5GB
    max_wal_senders: 10
    max_replication_slots: 10
    max_locks_per_transaction: 64
    wal_log_hints: "on"
    track_commit_timestamp: "off"
    archive_mode: "on"
    archive_timeout: 1800s
    archive_command: "pgbackrest --stanza=test archive-push %p"
  recovery_conf:
    recovery_target_timeline: latest
    restore_command: "pgbackrest --stanza=test archive-get %f %p"

watchdog:
  mode: automatic # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 3

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

```

**patronictl show-config**
```
2023-02-12 11:10:42,624 - ERROR - Failed to get list of machines from http://192.168.56.2:2379/v2: MaxRetryError("HTTPConnectionPool(host='192.168.56.2', port=2379): Max retries exceeded with url: /v2/machines (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))")
2023-02-12 11:10:42,625 - ERROR - Failed to get list of machines from http://192.168.56.3:2379/v2: MaxRetryError("HTTPConnectionPool(host='192.168.56.3', port=2379): Max retries exceeded with url: /v2/machines (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))")
2023-02-12 11:10:42,627 - ERROR - Failed to get list of machines from http://192.168.56.4:2379/v2: MaxRetryError("HTTPConnectionPool(host='192.168.56.4', port=2379): Max retries exceeded with url: /v2/machines (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))")

```

**Have you checked Patroni logs?**
Yes, the snippet of the repeated error is at the beginning of the issue description.

**Have you checked PostgreSQL logs?**
```
Feb 12 09:52:22 newdb systemd[1]: Starting PostgreSQL Cluster 12-main...
Feb 12 09:52:24 newdb systemd[1]: Started PostgreSQL Cluster 12-main.
```

**Have you tried to use GitHub issue search?**
https://github.com/zalando/patroni/issues/2036
https://github.com/zalando/patroni/issues/2543

Read through those two

**Additional context**
