### ISSUE TITLE
Clarification when post_init is run

### ISSUE THREAD

**Issue by krisavi** [zalando/patroni#2560]
**Describe the bug**
In documentation from those pieces:
```
post_bootstrap or post_init: An additional script that will be executed after initializing the cluster. The script receives a connection string URL (with the cluster superuser as a user name). The PGPASSFILE variable is set to the location of pgpass file.
```
and
```
postgresql:
  authentication:
    superuser:
      username: name for the superuser, set during initialization (initdb) and later used by Patroni to connect to the postgres.
...
    replication:
      username: replication username; the user will be created during initialization. Replicas will use this user to access the replication source via streaming replication
...
    rewind:
      username: name for the user for pg_rewind; the user will be created during initialization of postgres 11+ and all necessary [permissions](https://www.postgresql.org/docs/11/app-pgrewind.html#id-1.9.5.8.8) will be granted.
```
I would expect the order of post_init to be so that it creates the users beforehand as they are done **during** initialization. The post_init is supposed to run **after** initialization. However if I make a script and maybe add command to there to add special privileges to the expected rewind_user or replication user, then I get something along the lines:
```
Feb 15 21:49:36 pg2.test patroni[3254558]: psql:init.sql:2: ERROR:  role "rewind_user" does not exist
Feb 15 21:49:36 pg2.test patroni[3254558]: psql:init.sql:3: ERROR:  role "rewind_user" does not exist
Feb 15 21:49:36 pg2.test patroni[3254558]: psql:init.sql:4: ERROR:  role "rewind_user" does not exist
Feb 15 21:49:36 pg2.test patroni[3254558]: psql:init.sql:5: ERROR:  role "rewind_user" does not exist
Feb 15 21:49:36 pg2.test patroni[3254558]: psql:init.sql:6: ERROR:  role "rewind_user" does not exist
Feb 15 21:49:36 pg2.test patroni[3254558]: psql:init.sql:7: ERROR:  role "patroni_replication" does not exist
```

**To Reproduce**
Create a post_init script that expects rewind, replication or superuser to exist.

**Expected behavior**
The post_init should run after initialization and be able to manipulate users created during initialization. Alternatively would be good to have some information in manual specifying the order of operations, if so, then would be good to have references to SQL queries that are used to create the users and their permissions, so they could be performed manually as part of the script that further manipulates users.

**Environment**
-   Patroni version: 2.1.7
-   PostgreSQL version: 15
-   DCS (and its version): etcd 3.4.13

Relevant configuration options:
```
bootstrap:
  dcs:
    ...
  initdb:  
    -...
  post_init: /var/lib/pgsql/setup_cluster.sh
```

```
postgresql:
  ...
  authentication:
    replication:
      username: patroni_replication
    rewind:
      username: rewind_user
```
setup_cluster.sh is just wrapper script to run `psql -d $1 -f init.sql`

**Have you tried to use GitHub issue search?**
Yes
