### ISSUE TITLE
patronictl switchover gives 'Can not find suitable configuration of distributed configuration store' with etcd v2 API

### ISSUE THREAD

**Issue by skygunner** [zalando/patroni#2564]
**Describe the bug**
patronictl switchover gives 'Can not find suitable configuration of distributed configuration store' when ETCD v3 cluster operates with 
ETCD_ENABLE_V2="true", and patroni use etcd(v2) in config instead of etcd3.

**To Reproduce**
ETCD cluster version 3.5.7
ETCD version 3.5.7
Patroni version 3.0.1
Patroni use etcd (v2) instead of etcd3 in configration file. 
ETCD cluster operates wtih ETCD_ENABLE_V2="true"

**Expected behavior**
Maybe support the switchover on V2 api, or if the v2 api is gonna to phasing out soon?

**Screenshots**

**Environment**
ETCD cluster version 3.5.7
ETCD version 3.5.7
Patroni version 3.0.1
Patroni use etcd (v2) instead of etcd3 in configration file. 
ETCD cluster operates wtih ETCD_ENABLE_V2="true"

**Patroni configuration file**
```
scope: postgres
namespace: /db/
name: node1

restapi:
    listen: patroni-ip:8008
    connect_address: patroni-ip:8008

log:
  level: INFO
  dir: /tmp

etcd:
  hosts: etcd-ip1:2379,etcd-ip2:2379,etcd-ip3:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator patroni-ip/0 md5
  - host replication replicator etcd-ip1/0 md5
  - host replication replicator etcd-ip2/0 md5
  - host all all 0.0.0.0/0 md5

  users:
    admin:
      password: password
      options:
        - createrole
        - createdb

postgresql:
  listen: patroni-ip:5432
  connect_address: patroni-ip:5432
  data_dir: /data/patroni
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
      password: password
    superuser:
      username: postgres
      password: password
  parameters:
      unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
