### ISSUE TITLE
FATAL:  could not start WAL streaming: ERROR:  replication slot "XXX" does not exist

### ISSUE THREAD

**Issue by AlexZalyalowa** [zalando/patroni#2565]
Hello.
I have launched patroni cluster of 3 nodes, when it starts, one of replicas has 32mb lag while the database is empty

```
+ Cluster: test --------------+---------+---------+----+-----------+
| Member    | Host                   | Role    | State   | TL | Lag in MB |
+-----------+------------------------+---------+---------+----+-----------+
| postgresql0 | 127.0.0.1,X.X.X.05 | Leader  | running |  4 |           |
| postgresql1  | 127.0.0.1,X.X.X.06 | Replica | running |  1 |        32 |
| postgresql2 | 127.0.0.1,X.X.X.08 | Replica | running |  5 |         0 |
+-----------+------------------------+---------+---------+----+-----------+
```
there's an error in replicas' logs
```
STATEMENT:  START_REPLICATION SLOT "postgresql2" 0/5000000 TIMELINE 5
FATAL:  could not start WAL streaming: ERROR:  replication slot "postgresql2" does not exist
```

There's no errors in leader's logs
```
2023-02-22 15:04:12.555 MSK [80113] LOG:  received promote request
2023-02-22 15:04:12.555 MSK [80113] LOG:  redo done at 0/5000440 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 8.43 s
2023-02-22 15:04:12.556 MSK [80113] LOG:  selected new timeline ID: 4
2023-02-22 15:04:12.582 MSK [80113] LOG:  archive recovery complete
2023-02-22 15:04:12.587 MSK [80111] LOG:  database system is ready to accept connections
```

but replication doesn't work on master
```
# curl -s http://X.X.X.5:8008/master | jq .
{
  "state": "running",
  "postmaster_start_time": "2023-02-22 15:04:04.115650+03:00",
  "role": "master",
  "server_version": 140006,
  "xlog": {
    "location": 83894368
  },
  "timeline": 4,
  "dcs_last_seen": 1677069573,
  "database_system_identifier": "7202919472059551881",
  "patroni": {
    "version": "3.0.1",
    "scope": "test"
  }
}

```

**Environment**
-   Patroni version: 3.0.1
-   PostgreSQL version: 14.6

**Patroni configuration file**
```
scope: test
name:  postgresql0
restapi:
  listen: X.X.X.05:8008
  connect_address: X.X.X.05:8008
etcd3:
  hosts: 'X.X.X.05:2379,X.X.X.06:2379,X.X.X.08:2379'
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums
  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator X.X.X.05/32 md5
  - host replication replicator X.X.X.06/32 md5
  - host replication replicator X.X.X.08/32 md5
  - host all all 127.0.0.1/32 md5
  - host all all 0.0.0.0/0 md5
  users:
    admin:
      password: admin%
      options:
        - createrole
        - createdb
postgresql:
  listen: 127.0.0.1,X.X.X.05:5432
  connect_address: 127.0.0.1,X.X.X.05:5432
  data_dir: /opt/patroni/pgdata
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: zalando
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: rewind_password
  parameters:
    unix_socket_directories: '..'  # parent directory of data_dir
  pg_hba:
  - local all all md5
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator X.X.X.5/32 md5
  - host replication replicator X.X.X.6/32 md5
  - host replication replicator X.X.X.8/32 md5
  - host all all 127.0.0.1/32 md5
  - host all all 0.0.0.0/0 md5
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

**patronictl show-config**
```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters: null
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```
