### ISSUE TITLE
Patroni fails to start when being passed a long parameter string

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando/patroni#257]
We see the following error appear in the output of Patroni, as the value is a truncated parameter we assume some truncation is happening.

Probably fix: Instead of passing 1 (one) ``-o "key=value key=value"`` pass on every parameter individually as a ``-o key=value``

```text
Aug 15 14:05:18 ip-172-31-129-193 docker/9cce472c50ce[875]: waiting for server to start....2016-08-15 14:05:18 GMT [93]: [1-1] 57b1cc1e.5d 0     FATAL:  --log_s requires a value
```

```yaml
  parameters:
    archive_command: envdir "/home/postgres/etc/wal-e.d/env" wal-e --aws-instance-profile wal-push "%p" -p 1
    archive_mode: 'on'
    archive_timeout: 1800s
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_destination: csvlog
    log_directory: pg_log
    log_disconnections: 'on'
    log_file_mode: 420
    log_filename: postgresql-%u
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 500
    log_rotation_age: 1440
    log_statement: ddl
    log_temp_files: 0
    log_truncate_on_rotation: true
    logging_collector: true
    max_connections: 266
    max_replication_slots: 5
    max_wal_senders: 5
    shared_buffers: 1995MB
    ssl: 'on'
    ssl_cert_file: /home/postgres/server.crt
    ssl_key_file: /home/postgres/server.key
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    wal_keep_segments: 8
    wal_level: hot_standby
    wal_log_hints: 'on'
```
