### ISSUE TITLE
Failsafe_mode: true led to non-working cluster

### ISSUE THREAD

**Issue by GarretTheShadow** [zalando/patroni#2577]
**Describe the bug**
Patroni parameter 'failsafe_mode: true' led to cluster with 2 replicas, in case of k8s deployment use.

**To Reproduce**
1. Deploy HA scheme patroni verison 3.0.1 to k8s at least with 2 replicas. Important to use deployments instead of stateful sets.
2. Scale down and scale up both deployments.

**Expected behavior**
Master existence

**Environment**
-   Patroni version: 3.0.1
-   PostgreSQL version: 14
-   DCS (and its version): k8s v1.23.11

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
failsafe_mode: true
loop_wait: 10
maximum_lag_on_failover: 8388608
postgresql:
  parameters:
    effective_cache_size: 345600kB
    log_directory: /proc/1/fd/
    log_filename: 1
    log_line_prefix: '[%m][source=postgresql]'
    log_rotation_age: 0
    log_rotation_size: 0
    maintenance_work_mem: 28800kB
    max_connections: 200
    max_prepared_transactions: 200
    password_encryption: md5
    pg_wait_sampling.profile_queries: 'true'
    shared_buffers: 115200kB
    shared_preload_libraries: pg_stat_statements, pg_hint_plan, pg_cron, powa, pg_stat_kcache, pg_qualstats, pg_wait_sampling
    ssl: 'on'
    ssl_ca_file: /certs/ca.crt
    ssl_cert_file: /certs/tls.crt
    ssl_ciphers: ECDHE-RSA-AES128-GCM-SHA256
    ssl_key_file: /certs/tls.key
    ssl_min_protocol_version: TLSv1.2
    tcp_keepalives_count: 5
    tcp_keepalives_idle: 300
    tcp_keepalives_interval: 10
    track_io_timing: 'on'
    wal_keep_segments: 100
    work_mem: 576kB
  pg_hba:
  - local   all             postgres                                trust
  - host    all             postgres             127.0.0.1/32       trust
  - host    all             postgres             ::1/128            trust
  - local   replication     all                                     trust
  - host    replication     all                  127.0.0.1/32       trust
  - host    replication     all                  ::1/128            trust
  - host    replication     replicator           0.0.0.0/0          md5
  - host    replication     postgres             0.0.0.0/0          md5
  - host    all             all                  0.0.0.0/0          md5
  - local   all             all                                     md5
  - host    replication     replicator           ::0/0              md5
  - host    replication     postgres             ::0/0              md5
  - host    all             all                  ::0/0              md5
  recovery_conf:
    restore_command: ''
  use_pg_rewind: true
  use_slots: false
retry_timeout: 40
standby_cluster: ''
synchronous_mode: false
```

**Have you checked Patroni logs?**
```
[2023-03-01T12:22:30][INFO ][category=__main__] Role is set to replica, will terminate active applications connections
2023-03-01 12:22:30,630 INFO: following a different leader because i am not the healthiest node
[2023-03-01T12:22:30][INFO ][category=__main__] Connections are terminated successfully
2023-03-01 12:22:40,667 INFO: following a different leader because i am not the healthiest node
2023-03-01 12:22:50,667 INFO: following a different leader because i am not the healthiest node
2023-03-01 12:23:00,667 INFO: following a different leader because i am not the healthiest node
2023-03-01 12:23:10,671 INFO: following a different leader because i am not the healthiest node
2023-03-01 12:23:20,676 INFO: following a different leader because i am not the healthiest node
```

**Have you tried to use GitHub issue search?**
sure

**Additional context**
```
{
	"pg-patroni-node1-988cd4fbf-gfvn7": "http://10.129.171.245:8008/patroni",
	"pg-patroni-node2-55645777b6-2g4gp": "http://10.129.171.239:8008/patroni"
}

```
In patroni-leader Config Map, in failsafe section old pod names, looks like thats why no both pods going to replica
