### ISSUE TITLE
dynamic-options are not applied

### ISSUE THREAD

**Issue by izenk** [zalando/patroni#2584]
**Describe the bug**
Patroni is run on existing cluster.
Edit-config command shows options stored in DCS. If I change any option, patroni writes to log something like:
```
$ patronictl -c patroni.yml edit-config postgres
---
+++
@@ -38,7 +38,7 @@
     max_worker_processes: 4
     min_wal_size: 512MB
     random_page_cost: 1.1
-    shared_buffers: 1GB
+    shared_buffers: 2GB
     shared_preload_libraries: pg_stat_statements
     synchronous_commit: false
     track_commit_timestamp: false
```
```
2023-03-06 09:30:20,116 INFO: no action. I am (postgres-01), the leader with the lock
2023-03-06 09:30:20,121 INFO: Reloading PostgreSQL configuration
```

But when I check value of changed option through psql, I see nothing changed
```
postgres=# show shared_buffers;
 shared_buffers
----------------
 1GB
```

**Expected behavior**
Any option which is shown in edit-config editor will be applied to all nodes as dynamic configuration

**Environment**
-   Patroni version: 2.1.5
-   PostgreSQL version: 11.17
-   DCS (and its version): consul 1.13.2

**Patroni configuration file**
```
scope: ap-postgres
#namespace: /service/
name: postgres-01

restapi:
  listen: 0.0.0.0:8008
  connect_address: postgres-01.test:8008

consul:
  url: http://127.0.0.1:8500

log:
  level: DEBUG
  dir: /var/log/patroni
  file_size: 100000000
  file_num: 10

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 180
    synchronous_mode: false
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        data_directory: /var/lib/postgresql/11/data/main
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        track_commit_timestamp: off
        wal_level: replica
        wal_log_hints: on
        hot_standby: on
        max_connections: 200
        archive_mode: on
        archive_command: /bin/true
        shared_preload_libraries: pg_stat_statements
        hot_standby_feedback: on
        logging_collector: on
        log_directory: /var/log/postgresql
        log_filename: postgresql-%Y-%m-%d.log
        log_file_mode: 0640
        log_rotation_age: 1d
        log_rotation_size: 0
        log_line_prefix: '%m %p %q%h %u@%a %d %x:'
        log_lock_waits: on
        log_temp_files: 0
        log_checkpoints: on
        log_autovacuum_min_duration: 0
        track_io_timing: on
        autovacuum_naptime: 10min
        autovacuum_vacuum_threshold: 50
        autovacuum_analyze_threshold: 50
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_scale_factor: 0.01
        synchronous_commit: off
        shared_buffers: 1GB
        effective_cache_size: 1GB
        maintenance_work_mem: 504893kB
        work_mem: 5048kB
        max_worker_processes: 4
        max_parallel_workers_per_gather: 1
        max_parallel_workers: 2
        wal_buffers: 16MB
        min_wal_size: 512MB
        default_statistics_target: 500
        random_page_cost: 1.1
        checkpoint_completion_target: 0.9
        max_locks_per_transaction: 64
        autovacuum_max_workers: 10
        effective_io_concurrency: 200


  initdb:
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums
  - waldir: /var/lib/postgresql/11/wal/pg_wal

  pg_hba:
  - local all postgres peer
  - host all all 127.0.0.1/32 md5
  - host replication replica 127.0.0.1/32 md5
  - host replication replica 10.128.0.0/24 md5
  - host replication replica 10.129.0.0/24 md5
  - host replication replica 10.130.0.0/24 md5
  - host all all 10.128.0.0/24 md5
  - host all all 10.129.0.0/24 md5
  - host all all 10.130.0.0/24 md5

# Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

  users:
    postgres:
      options:
      - superuser
      - createrole
      - createdb
      - replication
    replica:
      password: password
      options:
      - replication

postgresql:
  listen: 0.0.0.0:5432
  connect_address: ap-postgres-01.test:5432
  data_dir: /var/lib/postgresql/11/data/main
  bin_dir: /usr/lib/postgresql/11/bin
  config_dir: /etc/postgresql/11/main
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replica
      password: password
    superuser:
      username: postgres
    rewind:
      username: rewind
      password: password
  use_unix_socket: true
  parameters:
    unix_socket_directories: '/var/run/postgresql'
    archive_mode: on
    archive_command: wal-g --config /var/lib/postgresql/11/wal-g.json wal-push %p >> /var/log/postgresql/archive_command.log 2>&1
    data_directory: /var/lib/postgresql/11/data/main
    max_locks_per_transaction: 64
    max_worker_processes: 8
    max_prepared_transactions: 0
    track_commit_timestamp: off
    wal_level: replica
    wal_log_hints: on
    hot_standby: on
    max_connections: 200
    shared_preload_libraries: pg_stat_statements
    hot_standby_feedback: on
    logging_collector: on
    log_directory: /var/log/postgresql
    log_filename: postgresql-%Y-%m-%d.log
    log_file_mode: 0640
    log_rotation_age: 1d
    log_rotation_size: 0
    log_line_prefix: '%m %p %q%h %u@%a %d %x:'
    log_lock_waits: on
    log_temp_files: 0
    log_checkpoints: on
    log_autovacuum_min_duration: 0
    track_io_timing: on
    autovacuum_naptime: 10min
    autovacuum_vacuum_threshold: 50
    autovacuum_analyze_threshold: 50
    autovacuum_vacuum_scale_factor: 0.01
    autovacuum_analyze_scale_factor: 0.01
    synchronous_commit: off
    shared_buffers: 2GB
    effective_cache_size: 2GB
    maintenance_work_mem: 504893kB
    work_mem: 5048kB
    max_worker_processes: 4
    max_parallel_workers_per_gather: 1
    max_parallel_workers: 2
    wal_buffers: 16MB
    min_wal_size: 512MB
    default_statistics_target: 500
    random_page_cost: 1.1
    checkpoint_completion_target: 0.9
    max_locks_per_transaction: 64
    autovacuum_max_workers: 10
    effective_io_concurrency: 200
  create_replica_methods:
  - wal-g
  wal-g:
    command: /test/services/patroni/scripts/wal-g_backup_fetch.sh LATEST
    no_master: 1
    no_params: True
  replica_method: wal-g
  recovery_conf:
    restore_command: /usr/local/bin/wal-g --config /var/lib/postgresql/11/wal-g.json wal-fetch %f %p
    recovery_target_timeline: latest
  pg_hba:
  - local all postgres peer
  - host all all 127.0.0.1/32 md5
  - host replication replica 127.0.0.1/32 md5
  - host replication replica 10.128.0.0/24 md5
  - host replication replica 10.129.0.0/24 md5
  - host replication replica 10.130.0.0/24 md5
  - host all all 10.128.0.0/24 md5
  - host all all 10.129.0.0/24 md5
  - host all all 10.130.0.0/24 md5

watchdog:
  mode: off
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

**patronictl show-config**
```
loop_wait: 10
master_start_timeout: 180
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: /bin/true
    archive_mode: true
    autovacuum_analyze_scale_factor: 0.01
    autovacuum_analyze_threshold: 50
    autovacuum_max_workers: 10
    autovacuum_naptime: 10min
    autovacuum_vacuum_scale_factor: 0.01
    autovacuum_vacuum_threshold: 50
    checkpoint_completion_target: 0.9
    data_directory: /var/lib/postgresql/11/data/main
    default_statistics_target: 500
    effective_cache_size: 1GB
    effective_io_concurrency: 200
    hot_standby: true
    hot_standby_feedback: true
    log_autovacuum_min_duration: 0
    log_checkpoints: true
    log_directory: /var/log/postgresql
    log_file_mode: 416
    log_filename: postgresql-%Y-%m-%d.log
    log_line_prefix: '%m %p %q%h %u@%a %d %x:'
    log_lock_waits: true
    log_rotation_age: 1d
    log_rotation_size: 0
    log_temp_files: 0
    logging_collector: true
    maintenance_work_mem: 504893kB
    max_connections: 200
    max_locks_per_transaction: 64
    max_parallel_workers: 2
    max_parallel_workers_per_gather: 1
    max_prepared_transactions: 0
    max_worker_processes: 4
    min_wal_size: 512MB
    random_page_cost: 1.1
    shared_buffers: 3GB
    shared_preload_libraries: pg_stat_statements
    synchronous_commit: false
    track_commit_timestamp: false
    track_io_timing: true
    wal_buffers: 16MB
    wal_level: replica
    wal_log_hints: true
    work_mem: 5048kB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
ttl: 30
```

**Additional context**
I understand, that may be not all of params presented in show-config/edit-config are "really" dynamic and may not be applied. But patroni does not say anything about it. I checked docs and didnt found a list of params refered to dynamic settings.
So, my questions are:
1) How patroni determines which postgres params are dynamic and which are not? (is there any list of them in docs may be)
2) Are options listed in show-config dynamic?

I read [docs](https://patroni.readthedocs.io/en/latest/SETTINGS.html#dynamic-configuration-settings)
There is a section:
```
postgresql:
use_pg_rewind: whether or not to use pg_rewind. Defaults to false.
use_slots: whether or not to use replication slots. Defaults to true on PostgreSQL 9.4+.
recovery_conf: additional configuration settings written to recovery.conf when configuring follower. There is no recovery.conf anymore in PostgreSQL 12, but you may continue using this section, because Patroni handles it transparently.
parameters: list of configuration settings for Postgres.
```
Last option "parameters" means any postgres parameter, but in reality I see, that only some of them are treated as dynamic despite they are listed in edit-config
