### ISSUE TITLE
Replication is not working in Patroni 

### ISSUE THREAD

**Issue by sayyed3** [zalando/patroni#2595]
### What happened?

Replication is not working in Patroni - replication slot does not exist

### How can we reproduce it (as minimally and precisely as possible)?

We have deployed a postgres cluster on Patroni. In which replication is not working, I am also getting an error 'replication slot does not exist'. We are stuck here for a very long time. 

### What did you expect to happen?

The Replication mechanism has to work 

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.1
-   PostgreSQL version: 15.2
-   DCS (and its version): etcd - 3.2.26

### Patroni configuration file

```yaml
/etc/patroni.yml

scope: postgres
namespace: /db/
name: node1

restapi:
listen: 172.31.15.65:8008
connect_address: 172.31.15.65:8008

etcd:
host: 172.31.13.20:2379

bootstrap:
dcs:
ttl: 30
loop_wait: 10
retry_timeout: 10
maximum_lag_on_failover: 1048576
postgresql:
use_pg_rewind: true
use_slots: true
parameters:
wal_level: replica
hot_standby: "on"
wal_keep_segments: 8
max_wal_senders: 5
max_replication_slots: 5
checkpoint_timeout: 3

initdb:
- encoding: UTF8
- data-checksums

pg_hba:
- host replication replicator 127.0.0.1/32 md5
- host replication replicator 172.31.15.65/0 md5
- host replication replicator 172.31.0.176/0 md5
- host replication replicator 172.31.6.24/0 md5
- host all all 0.0.0.0/0 md5

users:
    admin:
        password: admin
        options:
            - createrole
            - createdb
postgresql:
listen: 172.31.15.65:5432
connect_address: 172.31.15.65:5432
data_dir: /data/patroni
pgpass: /tmp/pgpass
authentication:
replication:
username: replicator
password: password
superuser:
username: postgres
password: password
parameters:
unix_socket_directories: '.'

#tags:
#nofailover: false
#noloadbalance: false
#clonefrom: false
#nosync: false
```

### patronictl show-config

```yaml
.
```

### Patroni log files

```shell
'replication slot does not exist'
```

### PostgreSQL log files

```shell
.
```

### Have you tried to use GitHub issue search?

- [X] Yes
