### ISSUE TITLE
SSL error when enable ssl in Patroni rest api

### ISSUE THREAD

**Issue by AleksandrAksenov** [zalando/patroni#2601]
### What happened?

When I enable SSL configuration for patroni restapi I get the error:
```
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:997)
```
When I remove SSL configuration - everything works fine.

### How can we reproduce it (as minimally and precisely as possible)?

* Install patroni
* Configure with the configuration below on the server
* Start Patroni
* The error appears in 5-10 seconds in logs.

### What did you expect to happen?

No error.

### Patroni/PostgreSQL/DCS version

-   Patroni version: patronictl version 3.0.1
-   PostgreSQL version: postgres (PostgreSQL) 14.7 (Ubuntu 14.7-0ubuntu0.22.04.1)
-   DCS (and its version): 
```
etcd Version: 3.3.25
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.18.1
Go OS/Arch: linux/amd64
```

### Patroni configuration file

```yaml
scope: postgres
namespace: /db/
name: postgresql0

restapi:
    listen: 10.254.0.51:8008
    connect_address: 10.254.0.51:8008
    # allowlist_include_members: true
    certfile: /mnt/patroni/server.crt
    cafile: /mnt/patroni/server.crt
    keyfile: /mnt/patroni/server.key
    ciphers: "ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:!SSLv1:!SSLv2:!SSLv3:!TLSv1:!TLSv1.1"
    authentication:
      username: user
      password: password
    allowlist:
      - 10.254.0.51/32
      - 10.254.0.52/32


etcd3:
    host: 10.254.0.53:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.254.0.51/32 md5
    - host replication replicator 10.254.0.52/32 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 10.254.0.51:5432
    connect_address: 10.254.0.51:5432
    data_dir: /mnt/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: password
        superuser:
            username: postgres
            password: password
    parameters:
        ssl: on
        sslmode: verify-ca
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
patroni[129003]: Exception in thread Thread-9 (process_request_thread):
patroni[129003]: Traceback (most recent call last):
patroni[129003]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
patroni[129003]:     self.run()
patroni[129003]:   File "/usr/lib/python3.10/threading.py", line 953, in run
patroni[129003]:     self._target(*self._args, **self._kwargs)
patroni[129003]:   File "/usr/local/lib/python3.10/dist-packages/patroni/api.py", line 885, in process_request_thread
patroni[129003]:     request.do_handshake()
patroni[129003]:   File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
patroni[129003]:     self._sslobj.do_handshake()
patroni[129003]: ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:997)
patroni[129003]: 2023-03-16 21:26:36,964 INFO: no action. I am (postgresql0), the leader with the lock
patroni[129003]: Exception in thread Thread-10 (process_request_thread):
patroni[129003]: Traceback (most recent call last):
patroni[129003]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
patroni[129003]:     self.run()
patroni[129003]:   File "/usr/lib/python3.10/threading.py", line 953, in run
patroni[129003]:     self._target(*self._args, **self._kwargs)
patroni[129003]:   File "/usr/local/lib/python3.10/dist-packages/patroni/api.py", line 885, in process_request_thread
patroni[129003]:     request.do_handshake()
patroni[129003]:   File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
patroni[129003]:     self._sslobj.do_handshake()
patroni[129003]: ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:997)
patroni[129003]: Exception in thread Thread-11 (process_request_thread):
patroni[129003]: Traceback (most recent call last):
patroni[129003]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
patroni[129003]:     self.run()
patroni[129003]:   File "/usr/lib/python3.10/threading.py", line 953, in run
patroni[129003]:     self._target(*self._args, **self._kwargs)
patroni[129003]:   File "/usr/local/lib/python3.10/dist-packages/patroni/api.py", line 885, in process_request_thread
patroni[129003]:     request.do_handshake()
patroni[129003]:   File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
patroni[129003]:     self._sslobj.do_handshake()
patroni[129003]: ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:997)
```

### PostgreSQL log files

```shell
-
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Server:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```
OpenSSL: `OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)`
