### ISSUE TITLE
Replica Nodes Restarting

### ISSUE THREAD

**Issue by ymtvs** [zalando/patroni#2606]
### What happened?

We are using logical slots and we manage them with patroni. We have 4 logical slots. But Replica nodes were restarting by themselves 4-5 times a day.  After that, we used `ignore_slots` and added 3 of them below. Now replica nodes not restarting. 

### How can we reproduce it (as minimally and precisely as possible)?

-

### What did you expect to happen?

Replica nodes will not restart. 

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.1
-   PostgreSQL version: 12.13
-   DCS (and its version): Consul v1.10.0

### Patroni configuration file

```yaml
-
```

### patronictl show-config

```yaml
basebackup:
  checkpoint: fast
  datadir: /pgsql-data/
ignore_slots:
- database: dbname
  name: locical_slot_3
  plugin: pgoutput
  type: logical
- database: dbname
  name: locical_slot_2
  plugin: pgoutput
  type: logical
- database: dbname
  name: locical_slot_1
  plugin: pgoutput
  type: logical
loop_wait: 10
master_stop_timeout: 60
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=pg-stanza archive-push %p;
    archive_mode: 'on'
    autovacuum: 'on'
    autovacuum_analyze_scale_factor: 0.001
    autovacuum_analyze_threshold: 100
    autovacuum_vacuum_cost_delay: 5ms
    autovacuum_vacuum_scale_factor: 0.001
    autovacuum_vacuum_threshold: 100
    bgwriter_delay: 50ms
    bgwriter_lru_maxpages: 1000
    bgwriter_lru_multiplier: 10.0
    checkpoint_completion_target: 0.7
    checkpoint_timeout: 5min
    cpu_tuple_cost: 0.03
    default_statistics_target: 300
    effective_cache_size: 48GB
    effective_io_concurrency: 200
    hot_standby_feedback: true
    huge_pages: 'off'
    idle_in_transaction_session_timeout: 600000
    jit: false
    log_autovacuum_min_duration: 0
    log_checkpoints: true
    log_filename: postgresql-%a.log
    log_line_prefix: '< user=%u db=%d host=%h pid=%p time=%m app=%a > '
    log_lock_waits: true
    log_min_duration_statement: 100
    log_rotation_age: 1d
    log_rotation_size: 1024MB
    log_statement: ddl
    log_temp_files: 0
    log_timezone: Turkey
    log_truncate_on_rotation: true
    logging_collector: true
    maintenance_work_mem: 2GB
    max_connections: 1000
    max_locks_per_transaction: 512
    max_logical_replication_workers: 8
    max_parallel_maintenance_workers: 4
    max_parallel_workers: 32
    max_parallel_workers_per_gather: 4
    max_replication_slots: 15
    max_wal_senders: 15
    max_wal_size: 4GB
    max_worker_processes: 32
    min_wal_size: 1GB
    password_encryption: md5
    pg_stat_statements.max: '8192'
    pg_stat_statements.save: 'on'
    pg_stat_statements.track: top
    pg_stat_statements.track_utility: 'off'
    random_page_cost: 1.5
    shared_buffers: 16GB
    shared_preload_libraries: pg_stat_statements
    temp_file_limit: 300000000
    timezone: Turkey
    track_activities: true
    track_counts: true
    track_functions: all
    vacuum_cost_limit: 400
    wal_buffers: -1
    wal_init_zero: 'off'
    wal_keep_segments: 512
    wal_level: logical
    wal_recycle: 'off'
    work_mem: 5MB
  use_pg_rewind: true
retry_timeout: 10
slots:
  logical_slot:
    database: dbname
    plugin: pgoutput
    type: logical
synchronous_mode: false
ttl: 30
```

### Patroni log files

```shell
Mar 12 12:49:57 data-pgnode-1 patroni[1092521]: 2023-03-12 12:49:57,093 INFO: no action. I am (data-pgnode-1), a secondary, and following a leader (data-pgnode-2)
Mar 12 12:50:07 data-pgnode-1 patroni[1092521]: 2023-03-12 12:50:07,165 INFO: no action. I am (data-pgnode-1), a secondary, and following a leader (data-pgnode-2)
Mar 12 12:50:07 data-pgnode-1 patroni[1092521]: 2023-03-12 12:50:07,227 ERROR: Failed to advance logical replication slot 'logical_slot_3': OperationalError('server closed the connection unexpectedly>
```

### PostgreSQL log files

```shell
< user=jobrunner db=dbname host=127.0.0.1 pid=4180713 time=2023-03-14 23:52:25.095 +03 app=Patroni > STATEMENT:  SELECT pg_catalog.pg_replication_slot_advance('logical_slot_slot', '6352/96660CE0')
< user= db= host= pid=1865935 time=2023-03-14 23:52:25.182 +03 app= > LOG:  server process (PID 4180713) was terminated by signal 11: Segmentation fault
< user= db= host= pid=1865935 time=2023-03-14 23:52:25.182 +03 app= > DETAIL:  Failed process was running: SELECT pg_catalog.pg_replication_slot_advance('logical_slot_slot', '6352/96660CE0')
< user= db= host= pid=1865935 time=2023-03-14 23:52:25.182 +03 app= > LOG:  terminating any other active server processes
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4180502 time=2023-03-14 23:52:25.182 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4180502 time=2023-03-14 23:52:25.182 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4180619 time=2023-03-14 23:52:25.182 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4180619 time=2023-03-14 23:52:25.182 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4179126 time=2023-03-14 23:52:25.182 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4179126 time=2023-03-14 23:52:25.182 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4180465 time=2023-03-14 23:52:25.182 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4180465 time=2023-03-14 23:52:25.182 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=postgres db=dbname host=127.0.0.1 pid=2787807 time=2023-03-14 23:52:25.182 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=postgres db=dbname host=127.0.0.1 pid=2787807 time=2023-03-14 23:52:25.182 +03 app=[unknown] > DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
< user=postgres db=dbname host=127.0.0.1 pid=2787807 time=2023-03-14 23:52:25.182 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4179611 time=2023-03-14 23:52:25.182 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4179611 time=2023-03-14 23:52:25.182 +03 app=[unknown] > DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4179611 time=2023-03-14 23:52:25.182 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=postgres db=postgres host=127.0.0.1 pid=2787628 time=2023-03-14 23:52:25.182 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=postgres db=postgres host=127.0.0.1 pid=2787628 time=2023-03-14 23:52:25.182 +03 app=[unknown] > DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
< user=postgres db=postgres host=127.0.0.1 pid=2787628 time=2023-03-14 23:52:25.182 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4177877 time=2023-03-14 23:52:25.182 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4177877 time=2023-03-14 23:52:25.182 +03 app=[unknown] > DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4177877 time=2023-03-14 23:52:25.182 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4178771 time=2023-03-14 23:52:25.182 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4178771 time=2023-03-14 23:52:25.182 +03 app=[unknown] > DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4178771 time=2023-03-14 23:52:25.182 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=jobrunner db=postgres host=127.0.0.1 pid=2787563 time=2023-03-14 23:52:25.182 +03 app=Patroni > WARNING:  terminating connection because of crash of another server process
< user=jobrunner db=postgres host=127.0.0.1 pid=2787563 time=2023-03-14 23:52:25.182 +03 app=Patroni > DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
< user=jobrunner db=postgres host=127.0.0.1 pid=2787563 time=2023-03-14 23:52:25.182 +03 app=Patroni > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=postgres db=trtemplate host=127.0.0.1 pid=2787806 time=2023-03-14 23:52:25.182 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=postgres db=trtemplate host=127.0.0.1 pid=2787806 time=2023-03-14 23:52:25.182 +03 app=[unknown] > DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
< user=postgres db=trtemplate host=127.0.0.1 pid=2787806 time=2023-03-14 23:52:25.182 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4179758 time=2023-03-14 23:52:25.183 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4179758 time=2023-03-14 23:52:25.183 +03 app=[unknown] > DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4179758 time=2023-03-14 23:52:25.183 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4178842 time=2023-03-14 23:52:25.183 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4178842 time=2023-03-14 23:52:25.183 +03 app=[unknown] > DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4178842 time=2023-03-14 23:52:25.183 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4179389 time=2023-03-14 23:52:25.183 +03 app=[unknown] > WARNING:  terminating connection because of crash of another server process
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4179389 time=2023-03-14 23:52:25.183 +03 app=[unknown] > DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4179389 time=2023-03-14 23:52:25.183 +03 app=[unknown] > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4180722 time=2023-03-14 23:52:25.278 +03 app=[unknown] > FATAL:  the database system is in recovery mode
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4180724 time=2023-03-14 23:52:25.351 +03 app=[unknown] > FATAL:  the database system is in recovery mode
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4180725 time=2023-03-14 23:52:25.397 +03 app=[unknown] > FATAL:  the database system is in recovery mode
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4180726 time=2023-03-14 23:52:25.470 +03 app=[unknown] > FATAL:  the database system is in recovery mode
< user=dbname_appuser db=dbname host=127.0.0.1 pid=4180727 time=2023-03-14 23:52:25.534 +03 app=[unknown] > FATAL:  the database system is in recovery mode
< user= db= host= pid=1865935 time=2023-03-14 23:52:25.551 +03 app= > LOG:  all server processes terminated; reinitializing
< user= db= host= pid=4180748 time=2023-03-14 23:52:27.518 +03 app= > LOG:  database system was interrupted while in recovery at log time 2023-03-14 23:42:29 +03
< user= db= host= pid=4180748 time=2023-03-14 23:52:27.518 +03 app= > HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
```

### Have you tried to use GitHub issue search?

- [ ] Yes
