### ISSUE TITLE
Need to rig the election

### ISSUE THREAD

**Issue by PenelopeFudd** [zalando/patroni#2616]
### What happened?

We're setting up a 3-node Zabbix cluster with Patroni, with a node in Vancouver, Seattle, and London.

When the leader dies, Zabbix and Patroni hold separate elections, and we end up with e.g. Zabbix leader in Seattle and Patroni leader in London, leading to a really slow experience.

### How can we reproduce it (as minimally and precisely as possible)?

1. Set up a clustered service (doesn't have to be Zabbix) on top of a three-node Patroni cluster.
2. Turn off the leader
3. Observe that there's a 50% chance the new leaders (the service and Patroni leaders) will be different (and due to the trans-atlantic link, the application will be slowwwwwww).

### What did you expect to happen?

I'd like the clustered service and Patroni to pick the same leader: e.g. "rig the Patroni election"

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.1.4
-   PostgreSQL version: 15.1
-   DCS (and its version): etcd 3.2.26

### Patroni configuration file

```yaml
scope: postgresql_cluster
namespace: /db/
name: postgresql_van2

restapi:
    listen: 10.10.10.10:8008
    connect_address: 10.10.10.10:8008
    authentication:
        username: this-is-not-a-userNaMe
        password: this-is-not-a-passWoRd

etcd:
    host: 10.10.10.10:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
        - encoding: UTF8
        - data-checksums

    pg_hba:
        - host replication replicator 127.0.0.1/32 md5
        - host replication replicator 10.10.10.10/0 md5
        - host replication replicator 10.20.20.20/0 md5
        - host replication replicator 10.30.30.30/0 md5
        - host all all 0.0.0.0/0 md5

postgresql:
    listen: 10.10.10.10:5432
    connect_address: 10.10.10.10:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: this-is-not-a-passWoRd2
        superuser:
            username: postgres
            password: this-is-not-a-passWoRd3
        rewind:
            username: rewind_user
            password: this-is-not-a-passWoRd4
    parameters:
        log_directory: '/var/log/postgres'
        log_filename: 'postgresql-%Y-%m-%d_%H%M%S.log'
        log_statement: 'none'
        unix_socket_directories: '.'
        shared_preload_libraries: 'timescaledb'
        timescaledb.telemetry_level: 'off'
        max_connections: 150
        shared_buffers: 4GB
        effective_cache_size: 12GB
        maintenance_work_mem: 1GB
        checkpoint_completion_target: 0.9
        wal_buffers: 16MB
        default_statistics_target: 100
        random_page_cost: 1.1
        effective_io_concurrency: 300
        work_mem: 13981kB
        min_wal_size: 2GB
        max_wal_size: 8GB

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
n/a
```

### PostgreSQL log files

```shell
n/a
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

I was going to ask about this on the Postgres Slack channel, but I can't get access to it:

* Got the address https://postgresteam.slack.com/ from the current [README.rst](https://github.com/zalando/patroni/blob/master/README.rst).

* At https://postgresteam.slack.com/signup#/domain-signup , it lets you sign up if and only if you have an email address @pgtreats.info.  I tried "Continue With Google", but got an error: "The email address must match one of the domains listed below. Please try another email."

* At https://postgresteam.slack.com/signin#/signin , I pick "Continue With Google", pick my work account, and get redirected to "https://slack.com/signin#/workspaces" with no mention of the PostgresTeam workspace visible.

* Got the address https://postgresteam.slack.com/?redir=%2Farchives%2FC9XPYG92A from the current [README.rst](https://github.com/zalando/patroni/blob/master/README.rst), it says "You need to sign in to see this page."

* Tried going to https://pgtreats.info to see about getting an email account there, was redirected to https://xzilla.net/, which lists helpful resources, and the first resource is https://postgres-slack.herokuapp.com/

* Got the address https://postgres-slack.herokuapp.com/ from https://github.com/zalando/patroni/issues/645, but it says "There's nothing here, yet."
