### ISSUE TITLE
How to change the Send-Q of patroni

### ISSUE THREAD

**Issue by PiPi-Dragon** [zalando/patroni#2620]
### What happened?

![image](https://user-images.githubusercontent.com/27352343/227507164-751790cf-d0e9-4f57-aef5-1c267b23c86e.png)
![image](https://user-images.githubusercontent.com/27352343/227508071-f79cb05f-963d-495e-9db9-c1b29ecd07db.png)
![image](https://user-images.githubusercontent.com/27352343/227511920-6b34ab55-19dc-4044-9e9e-492a3c9274ae.png)

Patroni did not receive the client's ack packet, triggering a retransmission.
There are many times the listen queue of a socket overflowed.

### How can we reproduce it (as minimally and precisely as possible)?

It is easy to occur when the server is busy, such as full pg_basebackup.

### What did you expect to happen?

We want to modify backlog size.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.0.2
-   PostgreSQL version: 10.0
-   DCS (and its version): etcd 3.4.7

### Patroni configuration file

```yaml
scope: pgtest
namespace: /service/
name: postgresql1

restapi:
    listen: 192.168.1.199:8008
    connect_address: 192.168.1.199:8008

etcd:
    hosts: 192.168.1.199:2379,192.168.1.200:2379,192.168.1.201:2379

log:
  level: DEBUG
  loggers:
    patroni.postmaster: DEBUG
    etcd.client: DEBUG
    urllib3: DEBUG

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:
                wal_log_hints: on
                max_connections: 1000              
                max_worker_processes: 128
                wal_level: replica
                max_wal_senders: 20
                max_replication_slots: 10
                effective_cache_size: 2GB          
                shared_buffers: 1GB                
                maintenance_work_mem: 512MB        
                wal_buffers: 32MB                  
                work_mem: 8MB                      
                max_parallel_workers_per_gather: 2 
                max_parallel_workers: 2            
                max_wal_size: 2GB                  
                min_wal_size: 512MB                
                archive_timeout: 1800s
                archive_command: bzip2 < %p > /pgtest/pg/archive/%f.bz2
                superuser_reserved_connections: 10
                unix_socket_permissions: 0700
                tcp_keepalives_idle: 60
                tcp_keepalives_interval: 60
                tcp_keepalives_count: 10
                vacuum_cost_delay: 0
                bgwriter_delay: 10ms
                bgwriter_lru_maxpages: 500
                bgwriter_lru_multiplier: 5.0
                effective_io_concurrency: 0
                fsync: on
                full_page_writes: on
                wal_writer_delay: 10ms
                wal_writer_flush_after: 1MB
                checkpoint_timeout: 30min
                archive_mode: always
                hot_standby: on
                wal_receiver_status_interval: 1s
                max_logical_replication_workers: 4
                max_sync_workers_per_subscription: 2
                random_page_cost: 1.2
                parallel_tuple_cost: 0.1
                parallel_setup_cost: 1000.0
                min_parallel_table_scan_size: 8MB
                min_parallel_index_scan_size: 512kB
                autovacuum_max_workers: 5
                autovacuum_vacuum_scale_factor: 0.1
                autovacuum_analyze_scale_factor: 0.05
                autovacuum_freeze_max_age: 1000000000
                autovacuum_multixact_freeze_max_age: 1200000000
                autovacuum_vacuum_cost_delay: 0
                statement_timeout: 0
                lock_timeout: 0
                idle_in_transaction_session_timeout: 2h
                vacuum_freeze_min_age: 50000000
                vacuum_freeze_table_age: 800000000
                vacuum_multixact_freeze_min_age: 50000000
                vacuum_multixact_freeze_table_age: 800000000
                datestyle: "iso, ymd"
                log_destination: "csvlog"
                log_min_duration_statement: 5s
                log_checkpoints: on
                log_connections: on
                log_disconnections: on
                log_error_verbosity: verbose
                log_lock_waits: on
                log_statement: "ddl"
                log_timezone: "PRC"
                log_autovacuum_min_duration: 0
                dynamic_shared_memory_type: posix
                logging_collector: on
                log_directory: "log"
                log_filename: "postgresql-%a.log"
                log_truncate_on_rotation: on
                log_rotation_age: 1d
                log_rotation_size: 0
                log_line_prefix: "%m [%p] "
                timezone: "PRC"
                lc_messages: "en_US.UTF-8"
                lc_monetary: "en_US.UTF-8"
                lc_numeric: "en_US.UTF-8"
                lc_time: "en_US.UTF-8"
                default_text_search_config: "pg_catalog.english"
                wal_keep_segments: 1000
                wal_sender_timeout: 60s
            recovery_conf:
                restore_command: bunzip2 < /pgtest/pg/archive/%f.bz2 > %p

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 192.168.1.199/0 md5
    - host replication replicator 192.168.1.200/0 md5
    - host replication replicator 192.168.1.201/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        pg_test:
            password: 20232023
            options:
                - createrole
                - createdb
postgresql:
    listen: 192.168.1.199:5500
    connect_address: 192.168.1.199:5500
    bin_dir: /pgtest/pg-10.21/psql/bin/
    data_dir: /pgtest/pg/data/
    pgpass: /pgtest/pg/tmp/pgpass1
    authentication:
        replication:
            username: reptest
            password: 20232023
        superuser:
            username: posttest
            password: 20232023
    parameters:
        unix_socket_directories: '/pgtest/pg/socket'
        synchronous_commit: "on"
        synchronous_standby_names: "*"

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: bzip2 < %p > /pgtest/pg/archive/%f.bz2
    archive_mode: always
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.05
    autovacuum_freeze_max_age: 1000000000
    autovacuum_max_workers: 5
    autovacuum_multixact_freeze_max_age: 1200000000
    autovacuum_vacuum_cost_delay: 0
    autovacuum_vacuum_scale_factor: 0.1
    bgwriter_delay: 100ms
    bgwriter_lru_maxpages: 500
    bgwriter_lru_multiplier: 5.0
    checkpoint_timeout: 30min
    datestyle: iso, ymd
    default_text_search_config: pg_catalog.english
    dynamic_shared_memory_type: posix
    effective_cache_size: 1GB
    effective_io_concurrency: 0
    fsync: true
    full_page_writes: true
    hot_standby: true
    idle_in_transaction_session_timeout: 2h
    lc_messages: en_US.UTF-8
    lc_monetary: en_US.UTF-8
    lc_numeric: en_US.UTF-8
    lc_time: en_US.UTF-8
    lock_timeout: 0
    log_autovacuum_min_duration: 0
    log_checkpoints: true
    log_connections: true
    log_destination: csvlog
    log_directory: log
    log_disconnections: true
    log_error_verbosity: verbose
    log_filename: postgresql-%a.log
    log_line_prefix: '%m [%p] '
    log_lock_waits: true
    log_min_duration_statement: 5s
    log_rotation_age: 1d
    log_rotation_size: 0
    log_statement: ddl
    log_timezone: PRC
    log_truncate_on_rotation: true
    logging_collector: true
    maintenance_work_mem: 512MB
    max_connections: 1000
    max_logical_replication_workers: 4
    max_parallel_workers: 2
    max_parallel_workers_per_gather: 2
    max_replication_slots: 10
    max_sync_workers_per_subscription: 2
    max_wal_senders: 20
    max_wal_size: 1GB
    max_worker_processes: 4
    min_parallel_index_scan_size: 512kB
    min_parallel_table_scan_size: 8MB
    min_wal_size: 512MB
    parallel_setup_cost: 1000.0
    parallel_tuple_cost: 0.1
    random_page_cost: 1.2
    shared_buffers: 1GB
    statement_timeout: 0
    superuser_reserved_connections: 10
    tcp_keepalives_count: 10
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 60
    timezone: PRC
    unix_socket_permissions: 448
    vacuum_cost_delay: 0
    vacuum_freeze_min_age: 50000000
    vacuum_freeze_table_age: 800000000
    vacuum_multixact_freeze_min_age: 50000000
    vacuum_multixact_freeze_table_age: 800000000
    wal_buffers: 32MB
    wal_keep_segments: 1000
    wal_level: logical
    wal_log_hints: true
    wal_receiver_status_interval: 1s
    wal_sender_timeout: 60s
    wal_writer_delay: 10ms
    wal_writer_flush_after: 1MB
    work_mem: 8MB
  recovery_conf:
    restore_command: bunzip2 < /pgtest/pg/archive/%f.bz2 > %p
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
2023-03-24 06:45:41,498 WARNING: Exception happened during processing of request from 192.168.1.199:56808
2023-03-24 06:45:41,498 WARNING: Traceback (most recent call last):
  File "/usr/local/python3.7.4/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/python3.7.4/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/python3.7.4/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/python3.7.4/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/python3.7.4/lib/python3.7/site-packages/patroni/api.py", line 524, in handle_one_request
    BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/local/python3.7.4/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/python3.7.4/lib/python3.7/site-packages/patroni/api.py", line 149, in do_OPTIONS
    self.do_GET(write_status_code_only=True)
  File "/usr/local/python3.7.4/lib/python3.7/site-packages/patroni/api.py", line 144, in do_GET
    self._write_status_code_only(status_code)
  File "/usr/local/python3.7.4/lib/python3.7/site-packages/patroni/api.py", line 32, in _write_status_code_only
    self.wfile.write('{0} {1} {2}\r\n\r\n'.format(self.protocol_version, status_code, message).encode('utf-8'))
  File "/usr/local/python3.7.4/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

### PostgreSQL log files

```shell
--
```

### Have you tried to use GitHub issue search?

- [X] Yes
