### ISSUE TITLE
patroni validate-config returns false

### ISSUE THREAD

**Issue by izenk** [zalando/patroni#2623]
### What happened?

Patroni works as exptected, but if I try to check config with '--validate-config' option, it returns False
```
patroni$ patroni --validate-config patroni.yml
watchdog.mode False didn't pass validation: Wrong value
```

### How can we reproduce it (as minimally and precisely as possible)?

Copy config from issue and try to use --validate-config

### What did you expect to happen?

Validation successful 

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.1
-   PostgreSQL version: 11.19
-   DCS (and its version):  Consul 1.13.2
-   OS version: Ubuntu 20.04.3 LTS

### Patroni configuration file

```yaml
scope: ap-postgres
#namespace: /service/
name: ap-postgres-01

restapi:
  listen: 0.0.0.0:8008
  connect_address: ap-postgres-01.ap:8008

consul:
  url: http://127.0.0.1:8500

log:
  level: INFO
  dir: /var/log/patroni
  file_size: 100000000
  file_num: 10

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 180
    synchronous_mode: false
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        unix_socket_directories: /var/run/postgresql
        data_directory: /var/lib/postgresql/11/data/main
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        track_commit_timestamp: off
        wal_level: replica
        wal_log_hints: on
        hot_standby: on
        max_connections: 200
        archive_mode: on
        archive_command: /bin/true
        shared_preload_libraries: 'pg_stat_statements,timescaledb'
        hot_standby_feedback: on
        logging_collector: on
        log_directory: /var/log/postgresql
        log_filename: postgresql-%Y-%m-%d.log
        log_file_mode: 0640
        log_rotation_age: 1d
        log_rotation_size: 0
        log_line_prefix: '%m %p %q%h %u@%a %d %x:'
        log_lock_waits: on
        log_temp_files: 1
        log_checkpoints: on
        log_autovacuum_min_duration: 0
        track_io_timing: on
        autovacuum_naptime: 10min
        autovacuum_vacuum_threshold: 50
        autovacuum_analyze_threshold: 50
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_scale_factor: 0.01
        synchronous_commit: off
        shared_buffers: 4GB
        effective_cache_size: 12GB
        maintenance_work_mem: 504893kB
        work_mem: 5048kB
        max_worker_processes: 4
        max_parallel_workers_per_gather: 1
        max_parallel_workers: 2
        wal_buffers: 16MB
        min_wal_size: 512MB
        default_statistics_target: 500
        random_page_cost: 1.1
        checkpoint_completion_target: 0.9
        max_locks_per_transaction: 64
        autovacuum_max_workers: 10
        effective_io_concurrency: 200
        timescaledb.max_background_workers: 8


  initdb:
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums
  - waldir: /var/lib/postgresql/11/wal/pg_wal

  pg_hba:
  - local all postgres peer
  - host all all 127.0.0.1/32 md5

# Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

  users:
    postgres:
      options:
      - superuser
      - createrole
      - createdb
      - replication
    replica:
      password: test
      options:
      - replication

postgresql:
  listen: 0.0.0.0:5432
  connect_address: ap-postgres-01.ap:5432
  data_dir: /var/lib/postgresql/11/data/main
  bin_dir: /usr/lib/postgresql/11/bin
  config_dir: /etc/postgresql/11/main
  pgpass: /var/lib/postgresql/11/pgpass0
  authentication:
    replication:
      username: replica
      password: test
    superuser:
      username: postgres
    rewind:
      username: rewind
      password: test
  use_unix_socket: true
  parameters:
    archive_command: wal-g --config /var/lib/postgresql/11/wal-g.json wal-push %p >> /var/log/postgresql/archive_command.log 2>&1
  create_replica_methods:
  - wal-g
  wal-g:
    command: /test/services/patroni/scripts/wal-g_backup_fetch.sh LATEST
    no_master: 1
    no_params: True
  replica_method: wal-g
  recovery_conf:
    restore_command: /usr/local/bin/wal-g --config /var/lib/postgresql/11/wal-g.json wal-fetch %f %p
    recovery_target_timeline: latest
  pg_hba:
  - local all postgres peer
  - host all all 127.0.0.1/32 md5

watchdog:
  mode: off
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

### patronictl show-config

```yaml
not applicable
```

### Patroni log files

```shell
not applicable
```

### PostgreSQL log files

```shell
not applicable
```

### Have you tried to use GitHub issue search?

- [X] Yes
