### ISSUE TITLE
`--dcs-url` command-line option of `patronictl` does not cover `etcd3` DCS

### ISSUE THREAD

**Issue by barthisrael** [zalando/patroni#2638]
### What happened?

I attempted to use `--dcs-url` commad-line option of `patronictl` command to specify the DCS URI but it did not work -- it throws an error about unknown scheme:

```bash
$ patronictl -c postgres0.yml --dcs-url "etcd://localhost:2379" list batman
+ Cluster: batman -----+-------+----+-----------+
| Member | Host | Role | State | TL | Lag in MB |
+--------+------+------+-------+----+-----------+
+--------+------+------+-------+----+-----------+

$ patronictl -c postgres0.yml --dcs-url "etcd3://localhost:2379" list batman
Error: Unknown dcs scheme: etcd3
```

### How can we reproduce it (as minimally and precisely as possible)?

Execute the following command:

```bash
patronictl -c postgres0.yml --dcs-url "etcd://localhost:2379" list batman
```

### What did you expect to happen?

Output to be:

```bash
$ patronictl -c postgres0.yml --dcs-url "etcd3://localhost:2379" list batman
+ Cluster: batman --------+--------+---------+----+-----------+
| Member      | Host      | Role   | State   | TL | Lag in MB |
+-------------+-----------+--------+---------+----+-----------+
| postgresql0 | 127.0.0.1 | Leader | running |  2 |           |
+-------------+-----------+--------+---------+----+-----------+
```

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.2
-   PostgreSQL version: 15.2
-   DCS (and its version): 3.2.26

### Patroni configuration file

```yaml
scope: batman
name: postgresql0

restapi:
  listen: 127.0.0.1:8008
  connect_address: 127.0.0.1:8008
  authentication:
    username: username
    password: password


etcd3:
  host: 127.0.0.1:2379


bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:

  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 127.0.0.1/32 md5
  - host all all 0.0.0.0/0 md5


  users:
    admin:
      password: admin%
      options:
        - createrole
        - createdb

postgresql:
  listen: 127.0.0.1:5432
  connect_address: 127.0.0.1:5432
  data_dir: data/postgresql0
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: zalando
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: rewind_password
  parameters:
    unix_socket_directories: '..'  # parent directory of data_dir


tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters: null
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
N/A
```

### PostgreSQL log files

```shell
N/A
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

I'm working on a patch to fix this issue.
