### ISSUE TITLE
patronictl - ERROR - Failed to get list of machines

### ISSUE THREAD

**Issue by Z08ADUNE** [zalando/patroni#2646]
### What happened?

Hello,

I have a random error when i use "patronictl list" or "patronictl show-config" but it's works anyway. 

2023-04-18 17:18:45,436 - ERROR - Failed to get list of machines from http://:2379/v2: LocationValueError('No host specified.')
+ Cluster: rocky_poc --------------+---------+---------+----+-----------+
| Member      | Host               | Role    | State   | TL | Lag in MB |
+-------------+--------------------+---------+---------+----+-----------+
| server1 | xxxxxx:5432 | Replica | running |  2 |         0 |
| server2 | xxxxxx:5432 | Leader  | running |  2 |           |
| server3 | xxxxxx:5432 | Replica | running |  2 |         0 |
+-------------+--------------------+---------+---------+----+-----------+

I don't use etcdv2 nor 2379 port in my etcd configuration and I don't have any errors when I use etcdctl member list

### How can we reproduce it (as minimally and precisely as possible)?

patronictl list

Error appears sometimes...

### What did you expect to happen?

No error :)

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.2
-   PostgreSQL version: 15.2
-   DCS (and its version): 
etcdctl version: 3.5.8
API version: 3.5

### Patroni configuration file

```yaml
etcd3:
  host: xxxxx:8008
  hosts:
    xxxxx:8008,
    xxxxx:8008,
    xxxxx:8008,
  protocol: http
```

### patronictl show-config

```yaml
2023-04-18 17:36:36,136 - ERROR - Failed to get list of machines from http://:2379/v2: LocationValueError('No host specified.')
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
ttl: 30
```

### Patroni log files

```shell
no errors in log files
```

### PostgreSQL log files

```shell
no errors in log files
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Thanks a lot :).
