### ISSUE TITLE
Stream Replication in Cascade using Patroni

### ISSUE THREAD

**Issue by Paulo-Rogerio** [zalando/patroni#2653]
### What happened?

Hello !! I would like to use stream replication in cascade format, but I could see that all the workers (replica) connect to the **primary**, and that wasn't exactly what I expected to happen. I activated the replicationfrom tags in patroni but it didn't have the expected result. _What I need is:_ **RO4** receiving stream from **RO3**, this one in turn receiving stream from **RO2** and this one in turn reviewing stream from RW. Is this possible to be configured in patroni?

```
+ Cluster: pg-poc-patroni-paulo -----------------------------------------------------------------+---------+---------+----+-----------------------+
| Member                  | Host                            | Role    | State   | TL | Lag in MB | Tags                                           |
+-------------------------+----------------------------------------------------------------------+---------+---------+----+-----------------------+
| pg-poc-patroni-paulo-01 | pg-poc-patroni-paulo-01.estudos | Leader  | running | 60 |           | noloadbalance: true                            |
|                         |                                 |         |         |    |           | replicatefrom: false                           |
|                         |                                 |         |         |    |           | robalance: true                                |
+-------------------------+----------------------------------------------------------------------+---------+---------+----+-----------------------+
| pg-poc-patroni-paulo-02 | pg-poc-patroni-paulo-02.estudos | Replica | running | 60 |         0 | nofailover: true                               |
|                         |                                 |         |         |    |           | noloadbalance: true                            |
|                         |                                 |         |         |    |           | replicatefrom: pg-poc-patroni-paulo-01.estudos |
|                         |                                 |         |         |    |           | robalance: true                                |
+-------------------------+----------------------------------------------------------------------+---------+---------+----+-----------------------+
| pg-poc-patroni-paulo-03 | pg-poc-patroni-paulo-03.estudos | Replica | running | 60 |         0 | nofailover: true                               |
|                         |                                 |         |         |    |           | replicatefrom: pg-poc-patroni-paulo-02.estudos |
|                         |                                 |         |         |    |           | robalance: false                               |
+-------------------------+----------------------------------------------------------------------+---------+---------+----+-----------------------+
```

Even with the tags defined , observe that all  replica are receiving data from pg-poc-patroni-paulo-01 ( RW ). 

```bash
12593 ?        S      0:00 /usr/pgsql-14/bin/postgres -D /data/14/pgdata --config-file=/data/14/pgdata/postgresql.conf --listen_addresses=0.0.0.0 --port=5432 --cluster_name=pg-poc-patroni-paulo --wal_level=replica --hot_standby=on --max_connections=3001
12596 ?        Ss     0:00  \_ postgres: pg-poc-patroni-paulo: logger
12598 ?        Ss     0:00  \_ postgres: pg-poc-patroni-paulo: checkpointer
12599 ?        Ss     0:00  \_ postgres: pg-poc-patroni-paulo: background writer
12600 ?        Ss     0:00  \_ postgres: pg-poc-patroni-paulo: walwriter
12601 ?        Ss     0:00  \_ postgres: pg-poc-patroni-paulo: autovacuum launcher
12602 ?        Ss     0:00  \_ postgres: pg-poc-patroni-paulo: archiver
12603 ?        Ss     0:00  \_ postgres: pg-poc-patroni-paulo: stats collector
12604 ?        Ss     0:00  \_ postgres: pg-poc-patroni-paulo: logical replication launcher
12606 ?        Ss     0:06  \_ postgres: pg-poc-patroni-paulo: postgres postgres [local] idle
12621 ?        Ss     0:00  \_ postgres: pg-poc-patroni-paulo: walsender postgres 10.33.33.189(36511) streaming 1/860001C0
13929 ?        Ss     0:00  \_ postgres: pg-poc-patroni-paulo: walsender postgres 10.33.33.190(33999) streaming 1/860001C0
```
What it really needed was....
**RO2** => (stream replication) **RO1** => ( stream replication ) **RW**  

This is possible using patroni?

### How can we reproduce it (as minimally and precisely as possible)?

Well to reproduce, just create a cluster with 3 nodes and try to cascade the stream replication . 
Ex: **RO2** => (stream replication) **RO1** => ( stream replication ) **RW**  

### What did you expect to happen?

Stream Replication in cascade

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.1
-   PostgreSQL version: 14
-   DCS (and its version): 3.0.1 

### Patroni configuration file

```yaml
---
name: pg-poc-patroni-paulo-01
namespace: /patroni/
scope: pg-poc-patroni-paulo

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.33.33.112:8008
  verify_client: required
  authentication:
    username: patroni
    password: "123456"   

etcd3:
  protocol: http
  hosts: "10.33.33.112:2379,10.33.33.189:2379,10.33.33.190:2379"
log:
  level: "INFO"
  dir: "/var/log/patroni"
  file_num: "2"
tags:
  clonefrom: false 
  robalance: true 
  noloadbalance: true 
  replicatefrom: false # pg-poc-patroni-paulo-01 on host pg-poc-patroni-paulo-02 | pg-poc-patroni-paulo-02 on host pg-poc-patroni-paulo-03
  nofailover: false  # true on pg-poc-patroni-paulo-02 and pg-poc-patroni-paulo-03 

postgresql:
  listen: 0.0.0.0:5432
  connect_address: pg-poc-patroni-paulo-01.estudos 
  data_dir: "/data/14/pgdata"
  bin_dir: "/usr/pgsql-14/bin"
  config_dir: "/data/14/pgdata"
  pgpass: /var/lib/pgsql/.pgpass
  use_unix_socket: True
  parameters:
    unix_socket_directories: "/var/run/postgresql"
    hba_file: "/data/14/pgdata/pg_hba.conf"
    ident_file: "/data/14/pgdata/pg_ident.conf"
    archive_mode: on
    archive_command: "pgbackrest --stanza=pg-poc-patroni-paulo archive-push %p"
    shared_buffers: "932MB"
    max_connections: "3000"
    min_wal_size: "2GB"
    max_wal_size: "5GB"
    idle_in_transaction_session_timeout: "10min"
    shared_preload_libraries: "pg_stat_statements"
    tcp_keepalives_idle: "600"
    tcp_keepalives_interval: "60"
    tcp_keepalives_count: "5"
    autovacuum_freeze_max_age: "1000000000"
    autovacuum_vacuum_cost_delay: "2ms"
    vacuum_cost_limit: "3000"
    vacuum_cost_page_dirty: "40"
    autovacuum_vacuum_scale_factor: "0.06"
    synchronous_commit: "off"
    cpu_tuple_cost: "0.1"
    random_page_cost: "2"
    log_file_mode: "0644"
    statement_timeout: "1h"
    stats_temp_directory: "/dev/shm"
    data_directory: "/data/14/pgdata"
    temp_file_limit: "1GB"
    log_directory: "/var/log/postgresql"
    log_destination: "stderr"
    log_filename: "postgresql-%a.log"
    logging_collector: "true"
    log_rotation_age: "1d"
    log_rotation_size: "0"
    log_truncate_on_rotation: "true"
  create_replica_methods:
    - pgbackrest
    - basebackup
  pgbackrest:
    command: "pgbackrest --stanza=pg-poc-patroni-paulo restore"
    keep_existing_recovery_conf: False
    no_paramas: True
    keep_data: True
  basebackup:
    checkpoint: 'fast'
  recovery_conf:
      clonefrom: true
      replicatefrom: pg-poc-patroni-paulo-01.estudos
      recovery_target_timeline: latest
      restore_command: "pgbackrest --config=/etc/pgbackrest/pgbackrest.conf --stanza=pg-poc-patroni-paulo --log-level-file=detail archive-get %f %p"
  authentication:
    replication:
      username: postgres
      password: "123456"
    superuser:
      username: postgres
      password: "123456"
    rewind:
      username: postgres
      password: "123456"
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication all 0.0.0.0/0 md5
    - local replication postgres peer
    - local all all peer

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 20
    maximum_lag_on_failover: 1048576
    master_start_timeout: 60
    postgresql:
      create_replica_methods:
        - pgbackrest
        - basebackup
      use_pg_rewind: true
      use_slots: true
      parameters:
        shared_buffers: "932MB"
        max_connections: "3000"
        min_wal_size: "2GB"
        max_wal_size: "5GB"
        idle_in_transaction_session_timeout: "10min"
        shared_preload_libraries: "pg_stat_statements"
        tcp_keepalives_idle: "600"
        tcp_keepalives_interval: "60"
        tcp_keepalives_count: "5"
        autovacuum_freeze_max_age: "1000000000"
        autovacuum_vacuum_cost_delay: "2ms"
        vacuum_cost_limit: "3000"
        vacuum_cost_page_dirty: "40"
        autovacuum_vacuum_scale_factor: "0.06"
        synchronous_commit: "off"
        cpu_tuple_cost: "0.1"
        random_page_cost: "2"
        log_file_mode: "0644"
        statement_timeout: "1h"
        stats_temp_directory: "/dev/shm"
        data_directory: "/data/14/pgdata"
        temp_file_limit: "1GB"
        log_directory: "/var/log/postgresql"
        log_destination: "stderr"
        log_filename: "postgresql-%a.log"
        logging_collector: "true"
        log_rotation_age: "1d"
        log_rotation_size: "0"
        log_truncate_on_rotation: "true"
  initdb: ['encoding=UTF8', 'data-checksums', 'auth-local=trust', 'locale=en_US.UTF-8', 'auth-host=md5', 'auth-local=trust']
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication all 0.0.0.0/0 md5
    - local replication postgres peer
    - local all all peer
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 60
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=pg-poc-patroni-paulo archive-push %p
    archive_mode: 'on'
    autovacuum_freeze_max_age: '1000000000'
    autovacuum_vacuum_cost_delay: 10ms
    autovacuum_vacuum_scale_factor: '0.06'
    checkpoint_completion_target: '0.7'
    checkpoint_segments: 384MB
    cpu_tuple_cost: '0.1'
    data_directory: /data/14/pgdata
    datestyle: iso, mdy
    default_statistics_target: '100'
    default_text_search_config: pg_catalog.english
    effective_cache_size: 2560MB
    effective_io_concurrency: '4'
    extra_float_digits: '3'
    hot_standby: 'on'
    hot_standby_feedback: 'on'
    idle_in_transaction_session_timeout: 10min
    include_dir: ifood_conf.d
    lc_messages: en_US.UTF-8
    lc_monetary: en_US.UTF-8
    lc_numeric: en_US.UTF-8
    lc_time: en_US.UTF-8
    listen_addresses: '*'
    log_autovacuum_min_duration: '0'
    log_checkpoints: 'on'
    log_connections: 'on'
    log_destination: stderr
    log_directory: /var/log/postgresql
    log_disconnections: 'on'
    log_file_mode: '0644'
    log_filename: postgresql-%a.log
    log_line_prefix: '%m [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h'
    log_lock_waits: 'on'
    log_min_duration_statement: 100ms
    log_rotation_age: 1d
    log_rotation_size: '0'
    log_statement: ddl
    log_temp_files: '0'
    log_timezone: Etc/GMT+3
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    maintenance_work_mem: 224MB
    max_connections: '3001'
    max_parallel_workers_per_gather: '0'
    max_replication_slots: '10'
    max_wal_senders: '10'
    max_wal_size: 5GB
    min_wal_size: 2GB
    port: '5432'
    random_page_cost: '2'
    shared_buffers: 896MB
    shared_preload_libraries: pg_stat_statements
    ssl: 'on'
    ssl_cert_file: /estudos/postgresql-ssl/server.crt
    ssl_key_file: /estudos/postgresql-ssl/server.key
    statement_timeout: 1h
    stats_temp_directory: /dev/shm
    synchronous_commit: 'off'
    tcp_keepalives_count: '5'
    tcp_keepalives_idle: '600'
    tcp_keepalives_interval: '60'
    temp_file_limit: 196GB
    timezone: Etc/GMT+3
    vacuum_cost_limit: '3000'
    vacuum_cost_page_dirty: '40'
    wal_buffers: '-1'
    wal_level: hot_standby
    wal_sender_timeout: 10min
    work_mem: 1152kB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 20
ttl: 30
```

### Patroni log files

```shell
`
2023-04-24 16:22:31,727 INFO: no action. I am (pg-poc-patroni-paulo-03), a secondary, and following a leader (pg-poc-patroni-paulo-01)
2023-04-24 16:22:41,771 INFO: no action. I am (pg-poc-patroni-paulo-03), a secondary, and following a leader (pg-poc-patroni-paulo-01)
2023-04-24 16:22:51,728 INFO: no action. I am (pg-poc-patroni-paulo-03), a secondary, and following a leader (pg-poc-patroni-paulo-01)
2023-04-24 16:23:01,776 INFO: no action. I am (pg-poc-patroni-paulo-03), a secondary, and following a leader (pg-poc-patroni-paulo-01)
2023-04-24 16:23:11,727 INFO: no action. I am (pg-poc-patroni-paulo-03), a secondary, and following a leader (pg-poc-patroni-paulo-01)
2023-04-24 16:23:21,774 INFO: no action. I am (pg-poc-patroni-paulo-03), a secondary, and following a leader (pg-poc-patroni-paulo-01)
2023-04-24 16:23:31,727 INFO: no action. I am (pg-poc-patroni-paulo-03), a secondary, and following a leader (pg-poc-patroni-paulo-01)
2023-04-24 16:23:41,772 INFO: no action. I am (pg-poc-patroni-paulo-03), a secondary, and following a leader (pg-poc-patroni-paulo-01)
`
```

### PostgreSQL log files

```shell
`
2023-04-24 16:22:18.618 -03 [20756]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1LOG:  connection received: host=127.0.0.1 port=49342
2023-04-24 16:22:33.619 -03 [20837]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1LOG:  connection received: host=127.0.0.1 port=49420
2023-04-24 16:22:48.618 -03 [20915]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1LOG:  connection received: host=127.0.0.1 port=49504
2023-04-24 16:23:03.619 -03 [20998]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1LOG:  connection received: host=127.0.0.1 port=49588
2023-04-24 16:23:18.619 -03 [21076]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1LOG:  connection received: host=127.0.0.1 port=49672
2023-04-24 16:23:33.619 -03 [21157]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1LOG:  connection received: host=127.0.0.1 port=49750
2023-04-24 16:23:48.618 -03 [21236]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1LOG:  connection received: host=127.0.0.1 port=49832
2023-04-24 16:24:03.618 -03 [21324]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1LOG:  connection received: host=127.0.0.1 port=49916
2023-04-24 16:24:18.619 -03 [21402]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1LOG:  connection received: host=127.0.0.1 port=50000
2023-04-24 16:24:33.618 -03 [21483]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1LOG:  connection received: host=127.0.0.1 port=50078
2023-04-24 16:24:48.619 -03 [21564]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=127.0.0.1LOG:  connection received: host=127.0.0.1 port=50162
`
```

### Have you tried to use GitHub issue search?

- [X] Yes
