### ISSUE TITLE
Members refuse to update configuration with Pending Restart

### ISSUE THREAD

**Issue by pgodfrin-nov** [zalando/patroni#2654]
### What happened?

I cannot get the Patroni Dynamic configuration to update the environment. In addition to patronictl reload & restart. I've tried stopping and start the database and also a reboot. Nothing doing, won't update. As this is my production system this reconfiguration is needed to manage some memory errors.

### How can we reproduce it (as minimally and precisely as possible)?

I'm not certain how to reproduce it, but I'll paste my process here:
## Standby:
```
postgres@prdudb01:~=> ptop
+ Cluster: unidb01 (7050494637474675106) --------+-----+-----------+-----------------+
| Member     | Host          | Role    | State   |  TL | Lag in MB | Pending restart |
+------------+---------------+---------+---------+-----+-----------+-----------------+
| prdudb02   | 172.19.71.142 | Leader  | running | 186 |           | *               |
| + prdudb01 | 172.19.60.108 | Replica | running | 186 |         0 | *               |
+------------+---------------+---------+---------+-----+-----------+-----------------+
postgres@prdudb01:~=> pctl show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
maximum_lag_on_syncnode: -1
postgresql:
  parameters:
    jit: false
    max_connections: 160
    max_locks_per_transaction: 64
    max_prepared_transactions: 500
    max_worker_processes: 2048
    search_path: '"$user", tsdba, timeseries, max_cmpl, public'
    track_commit_timestamp: 'on'
    wal_keep_size: 12GB
    work_mem: 32MB
retry_timeout: 10
synchronous_mode: false
ttl: 30
use_pg_rewind: true
use_slots: true
```
ps -ef:
_note the running max_connections_
```
postgres  302951       1  0 05:19 ?        00:00:48 /usr/bin/python3 /usr/bin/patroni /postgres/admin/patroni/prdudb01-patroni.yaml
postgres  355569  355558  0 06:35 pts/0    00:00:00 -bash
postgres  462852       1  0 09:14 ?        00:00:05 /usr/lib/postgresql/13/bin/postgres -D /postgres/udb01/data --config-file=/postgres/udb01/data/postgresql.conf --listen_addresses=0.0.0.0 --port=5432 --cluster_name=unidb01 --wal_level=replica --hot_standby=on --max_connections=250 --max_wal_senders=10 --max_prepared_transactions=500 --max_locks_per_transaction=64 --track_commit_timestamp=on --max_replication_slots=10 --max_worker_processes=2048 --wal_log_hints=on

```

## Primary:
```
postgres@prdudb02:~=> ptop
+ Cluster: unidb01 (7050494637474675106) --------+-----+-----------+-----------------+
| Member     | Host          | Role    | State   |  TL | Lag in MB | Pending restart |
+------------+---------------+---------+---------+-----+-----------+-----------------+
| prdudb02   | 172.19.71.142 | Leader  | running | 186 |           | *               |
| + prdudb01 | 172.19.60.108 | Replica | running | 186 |         0 | *               |
+------------+---------------+---------+---------+-----+-----------+-----------------+
postgres@prdudb02:~=> pctl show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
maximum_lag_on_syncnode: -1
postgresql:
  parameters:
    jit: false
    max_connections: 160
    max_locks_per_transaction: 64
    max_prepared_transactions: 500
    max_worker_processes: 2048
    search_path: '"$user", tsdba, timeseries, max_cmpl, public'
    track_commit_timestamp: 'on'
    wal_keep_size: 12GB
    work_mem: 32MB
retry_timeout: 10
synchronous_mode: false
ttl: 30
use_pg_rewind: true
use_slots: true
```
ps -ef
_note the running max_connections_
```
postgres  277275       1  0 03:43 ?        00:01:02 /usr/bin/python3 /usr/bin/patroni /postgres/admin/patroni/prdudb02-patroni.yaml
postgres  277418       1  0 03:43 ?        00:00:22 /usr/lib/postgresql/13/bin/postgres -D /postgres/udb01/data --config-file=/postgres/udb01/data/postgresql.conf --listen_addresses=0.0.0.0 --port=5432 --cluster_name=unidb01 --wal_level=replica --hot_standby=on --max_connections=250 --max_wal_senders=10 --max_prepared_transactions=500 --max_locks_per_transaction=64 --track_commit_timestamp=on --max_replication_slots=10 --max_worker_processes=2048 --wal_log_hints=on
```
### Reload and restart on Standby:
```
postgres@prdudb01:~=> pctl reload unidb01 prdudb01
+ Cluster: unidb01 (7050494637474675106) ------+-----+-----------+-----------------+
| Member   | Host          | Role    | State   |  TL | Lag in MB | Pending restart |
+----------+---------------+---------+---------+-----+-----------+-----------------+
| prdudb01 | 172.19.60.108 | Replica | running | 186 |         0 | *               |
| prdudb02 | 172.19.71.142 | Leader  | running | 186 |           | *               |
+----------+---------------+---------+---------+-----+-----------+-----------------+
Are you sure you want to reload members prdudb01? [y/N]: y
Reload request received for member prdudb01 and will be processed within 10 seconds
postgres@prdudb01:~=> pglg
          N.nspname,
          relname,
          pg_table_size(C.oid) as table_size, pg_indexes_size(C.oid) as index_size, pg_total_relation_size(C.oid) as total_size
        FROM pg_class C
        LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
        WHERE nspname NOT IN ('pg_catalog', 'information_schema') AND
          nspname !~ '^pg_toast' AND
          relkind = 'r' AND
          ( relname ~ '[[:alnum:]]' )
2023-04-26 17:07:33 UTC PRDUDB01 [p:462870 s:00000] :::LOG:  restartpoint starting: time
2023-04-26 17:07:37 UTC PRDUDB01 [p:463124 s:00000] 127.0.0.1(37312):datadog-agent:SELECT:LOG:  duration: 2400.365 ms  statement: 
        SELECT
          N.nspname,
          relname,
          pg_table_size(C.oid) as table_size, pg_indexes_size(C.oid) as index_size, pg_total_relation_size(C.oid) as total_size
        FROM pg_class C
        LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
        WHERE nspname NOT IN ('pg_catalog', 'information_schema') AND
          nspname !~ '^pg_toast' AND
          relkind = 'r' AND
          ( relname ~ '[[:alnum:]]' )
2023-04-26 17:07:39 UTC PRDUDB01 [p:462870 s:00000] :::LOG:  restartpoint complete: wrote 615 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=5.898 s, sync=0.062 s, total=5.980 s; sync files=28, longest=0.008 s, average=0.003 s; distance=4208 kB, estimate=5159 kB
2023-04-26 17:07:39 UTC PRDUDB01 [p:462870 s:00000] :::LOG:  recovery restart point at 133D/CA6C4358
2023-04-26 17:07:39 UTC PRDUDB01 [p:462870 s:00000] :::DETAIL:  Last completed transaction was at log time 2023-04-26 17:07:37.73896+00.
2023-04-26 17:07:39 UTC PRDUDB01 [p:462852 s:00000] :::LOG:  received SIGHUP, reloading configuration files
2023-04-26 17:07:39 UTC PRDUDB01 [p:462852 s:55P02] :::LOG:  parameter "max_connections" cannot be changed without restarting the server
2023-04-26 17:07:39 UTC PRDUDB01 [p:462852 s:F0000] :::LOG:  configuration file "/postgres/udb01/data/postgresql.conf" contains errors; unaffected changes were applied
postgres@prdudb01:~=> pctl restart unidb01 prdudb01
+ Cluster: unidb01 (7050494637474675106) ------+-----+-----------+-----------------+
| Member   | Host          | Role    | State   |  TL | Lag in MB | Pending restart |
+----------+---------------+---------+---------+-----+-----------+-----------------+
| prdudb01 | 172.19.60.108 | Replica | running | 186 |         0 | *               |
| prdudb02 | 172.19.71.142 | Leader  | running | 186 |           | *               |
+----------+---------------+---------+---------+-----+-----------+-----------------+
When should the restart take place (e.g. 2023-04-26T13:09)  [now]: 
Are you sure you want to restart members prdudb01? [y/N]: y
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2)  []: 
Success: restart on member prdudb01

```
### max_connections remains unchanged
```
postgres  302951       1  0 05:19 ?        00:00:49 /usr/bin/python3 /usr/bin/patroni /postgres/admin/patroni/prdudb01-patroni.yaml
postgres  355569  355558  0 06:35 pts/0    00:00:00 -bash
postgres  472845  472831  0 09:29 pts/2    00:00:00 -bash
postgres  546950  546940  0 11:18 pts/1    00:00:00 -bash
postgres  582261       1 11 12:09 ?        00:00:00 /usr/lib/postgresql/13/bin/postgres -D /postgres/udb01/data --config-file=/postgres/udb01/data/postgresql.conf --listen_addresses=0.0.0.0 --port=5432 --cluster_name=unidb01 --wal_level=replica --hot_standby=on --max_connections=250 --max_wal_senders=10 --max_prepared_transactions=500 --max_locks_per_transaction=64 --track_commit_timestamp=on --max_replication_slots=10 --max_worker_processes=2048 --wal_log_hints=on
```

### What did you expect to happen?

I'd expect the config to change. I've done this plenty of times, and frankly I don't understand why this is happening now.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
```
patroni 2.1.3
```
-   PostgreSQL version: 
```
[tsdb@prdudb01] # select version();
                                                             version                                                              
----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 13.5 (Ubuntu 13.5-2.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
```
-   DCS (and its version): 
```
postgres@prdudb01:~=> etcd --version
etcd Version: 3.5.2
Git SHA: 99018a77b
Go Version: go1.16.3
Go OS/Arch: linux/amd64
```

### Patroni configuration file

```yaml
#
# prd unidb01
# prdudb01
# filename:  prdudb01-patroni.yaml
# more details: https://patroni.readthedocs.io/en/latest/SETTINGS.html#settings
#
# SCOPE     is the name of the ETCD cluster
# NAME      is the host (server) name
# NAMESPACE is the root location in the DCS
# 
# github: https://github.com/zalando/patroni
# docs:   https://patroni.readthedocs.io/en/latest/index.html
#
################################################################################
# Maintenance:
#   03-31-22    peg
#   cleaning up comments and other garbage. Original code is found in
#   /etc/patroni/config.yml.in
#   05-12-22  peg
#   adapting to prod version
#   01-09-22  peg
#   Increasing instance class to m6i.4xlarge
#   upping some memory parms
################################################################################

scope: unidb01
namespace: /unidb01
name: prdudb01

log:
  level: WARNING
  #level: DEBUG
  dir: /postgres/admin/logs
  format: '%(asctime)s %(processName)s %(levelname)s: %(message)s'
#  loggers: 
#    patroni.postmaster: NOTICE

restapi:
  listen: 172.19.60.108:8008
  connect_address: 172.19.60.108:8008

# etcd v3
etcd3:
  hosts:
  - 172.19.60.108:2379
  - 172.19.71.142:2379
  - 172.19.58.37:2379
  - 172.19.68.25:2379

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    #initialize: true
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    master_stop_timeout:

#   03-31-22    peg
#   DISALLOW INITDB ON BOOTSTRAP
  method:
  postgresql:
      use_pg_rewind: true
      parameters:
        checkpoint_timeout: '30s'
        checkpoint_completion_target: '0.2'
        cluster_name: 'unidb01'
        datestyle: 'iso, mdy'
        default_text_search_config: 'pg_catalog.english'
        dynamic_shared_memory_type: posix  
        jit: off
        work_mem: 32MB
        max_connections: 200
        max_worker_processes: 1024
        lc_messages: 'C.UTF-8'                 
        lc_monetary: 'C.UTF-8'                 
        lc_numeric: 'C.UTF-8'                  
        lc_time: 'C.UTF-8'                      
        listen_addresses: '*'            
        log_destination: 'stderr'           
        log_directory: '/postgres/admin/logs'
        log_timezone: 'Etc/UTC'
        port: 5432
        timezone: 'Etc/UTC'
        superuser_reserved_connections: 10
        wal_keep_size: 2GB

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 172.19.60.108:5432
  data_dir: /postgres/udb01/data
  bin_dir: /usr/lib/postgresql/13/bin
#  config_dir:
  pgpass: /home/postgres/.pgpass
  authentication:
    replication:
      username: replication
    superuser:
      username: postgres
    rewind:  # Has no effect on postgres 10 and lower
      username: postgres
  use_pg_rewind: true
  parameters:
    archive_command: 'pgbackrest --stanza=unidb01 archive-push %p'
    archive_mode: 'on'
    archive_timeout: '900s'
#   PEG 01-09-23    instance type upgrade
    autovacuum_work_mem: 32MB
    bgwriter_lru_maxpages: 1024
    bgwriter_flush_after: 0
    checkpoint_flush_after: 0
    checkpoint_timeout: '30s'
    checkpoint_completion_target: '0.2'
    cluster_name: 'unidb01'
    commit_delay: 100000
    commit_siblings: 5
    datestyle: 'iso, mdy'
    default_statistics_target: 5000
    default_text_search_config: 'pg_catalog.english'
    dynamic_shared_memory_type: posix  
    effective_cache_size: '44GB'
    effective_io_concurrency:  100
    full_page_writes: 'on'    
    fsync: 'on'
    enable_partitionwise_aggregate: on
    hot_standby_feedback: on
    huge_pages: 'on'
    # not applicable due to pgbouncer peg 8-18-21
    #idle_in_transaction_session_timeout: '15s'
    #DYN jit: off
    lc_messages: 'C.UTF-8'                 
    lc_monetary: 'C.UTF-8'                 
    lc_numeric: 'C.UTF-8'                  
    lc_time: 'C.UTF-8'                      
    listen_addresses: '*'            
    lock_timeout: '15s'
###########################################################################
#   LOG SETTINGS
#   Valid values arei:
#   DEBUG5, DEBUG4, DEBUG3, DEBUG2, DEBUG1, 
#     INFO, NOTICE, WARNING, ERROR, LOG, 
#       FATAL,PANIC 
#   Each level includes all the levels that follow it.
############################################################################ 
# minimal logging
#    log_min_messages: log
#    log_error_verbosity: default
#    log_min_error_statement: log
#    log_min_messages: log
############################################################################
# normal logging
    log_min_messages: INFO
    log_min_error_statement: INFO
    log_error_verbosity: default
    log_min_duration_statement: 1000ms
############################################################################
# debug logging
#    log_min_messages: DEBUG1
#######DATADOG################################################################
# keep log_statement commented out
#    log_statement: ddl
#   keep log duration commented out
#    log_duration: 'off'
############################################################################
    log_destination: 'stderr'           
    log_directory: '/postgres/admin/logs'
    log_file_mode: 0740                   
    log_filename: 'alert_prdudb01.log'        # log file name pattern,
#    log_line_prefix: '%m PRDUDB01 [p:%p s:%e] '
    log_line_prefix: '%t PRDUDB01 [p:%p s:%e] %r:%a:%i:'
    log_rotation_age: '43200'
    log_timezone: 'Etc/UTC'
    log_truncate_on_rotation: 'on'
    logging_collector: on
#   PEG 01-09-23    instance type upgrade
    maintenance_work_mem: 24MB          
    max_connections: 150
    max_parallel_workers: 1024
    max_parallel_workers_per_gather: 8
    #DYN max_worker_processes: 512
    max_wal_size: 8GB
    min_wal_size: 2GB
    port: 5432
    restore_command: 'pgbackrest --stanza=unidb01 archive-get %f "%p"'
#   PEG 01-09-23    instance type upgrade
#    shared_buffers: 20GB                  
    #DYN: search_path: '"$user", tsdba, timeseries, max_cmpl, public'
    shared_buffers: 46GB                  
    shared_preload_libraries: 'pg_freespacemap,pg_visibility,pg_buffercache,pg_stat_statements,auto_explain,timescaledb'
    ssl: 'off'
    synchronous_commit: 'off'
    synchronous_standby_names: 'first 1 ("prdudb01","prdudb02")'
    temp_buffers: 16MB                     
    temp_tablespaces: 'temp01'
    timezone: 'Etc/UTC'
    track_commit_timestamp: 'on'
    unix_socket_directories: '/var/run/postgresql'
#   PEG 01-09-23    instance type upgrade
#    wal_buffers: 512MB
    wal_buffers: 512MB 
    wal_compression: on
    #DYN wal_keep_size: 0
    wal_init_zero: 'off'
    wal_level: replica
    wal_log_hints: "on"
    wal_receiver_status_interval: '0'
    wal_writer_delay: 3s
    wal_writer_flush_after : 1024MB
    #DYN work_mem: 32MB                      
    superuser_reserved_connections: 10
    #ssl_cert_file: 'maxshsrv.crt'
    #ssl_key_file:  'maxshsrv.key'
    # Timescale specific parms
    timescaledb.max_background_workers:  32
###########################################################################
# Stats settings
    pg_stat_statements.max: 100
    pg_stat_statements.save: on
    pg_stat_statements.track: top
    pg_stat_statements.track_planning: off
    pg_stat_statements.track_utility: on
#   The telemetry service creates very large statements:
#   Values and upsert statements are 10,000 entries
#   This should keep the data in  $PGDATA/pg_stat smaller
    track_activity_query_size: 1024
############################################################################    
  pg_hba:
  # TYPE         DATABASE        USER                ADDRESS                  METHOD
  - local       all             postgres,godfrinpe,datadog                  trust
  - local       replication     postgres,replication                        trust
#   PGBouncer bequeaths connections to postgres via port 5432 and the localhost IP
  - hostnossl   all             all                     127.0.0.1/32        md5
# Backend Subnet CIDR - app04p1
  - hostnossl   all             all                     172.19.72.0/21      md5
  - hostnossl   all             all                     172.19.56.0/21      md5
  - hostnossl   all             all                     172.19.64.0/21      md5
# Backend Subnet CIDR - app04p2
  - hostnossl   all             all                     172.16.26.0/23      md5
  - hostnossl   all             all                     172.16.28.0/23      md5
  - hostnossl   all             all                     172.16.30.0/23      md5
# Cross instance/node communication
  - host        postgres        postgres                127.0.0.1/32       trust
  - host        replication     replication             127.0.0.1/32       trust
  - host        postgres        postgres,replication    172.19.71.142/32   trust
  - host        all             godfrinpe               172.19.71.142/32   trust
  - host        replication     postgres,replication    172.19.71.142/32   trust
  # Access db via VPN
  - hostnossl   all             all                     10.226.20.0/23          md5

  recovery_conf:
    restore_command: 'pgbackrest --stanza=unidb01 archive-get %f "%p"'
    standby_mode: on
    primary_conninfo: 'application_name=prdudb01 host=prdudb02.novcds.io user=replication port=5432'
#    recovery_target_timeline: 37
    primary_slot_name: prdudb01


watchdog:
#TODO: check out softdog
#  mode: automatic # Allowed values: off, automatic, required
  mode: off # Allowed values: off, automatic, required
#  prdice: /prd/watchdog
#  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
postgres@prdudb01:/postgres/admin/patroni=> pctl show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
maximum_lag_on_syncnode: -1
postgresql:
  parameters:
    jit: false
    max_connections: 160
    max_locks_per_transaction: 64
    max_prepared_transactions: 500
    max_worker_processes: 2048
    search_path: '"$user", tsdba, timeseries, max_cmpl, public'
    track_commit_timestamp: 'on'
    wal_keep_size: 12GB
    work_mem: 32MB
retry_timeout: 10
synchronous_mode: false
ttl: 30
use_pg_rewind: true
use_slots: true
```

### Patroni log files

```shell
2023-04-26 10:13:04,452 MainProcess ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 610, in get_postgresql_status
    row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 592, in query
    return self.server.query(sql, *params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 680, in query
    raise e
  File "/usr/lib/python3/dist-packages/patroni/api.py", line 676, in query
    cursor.execute(sql, params)
psycopg2.errors.OutOfMemory: out of memory
DETAIL:  Failed on request of size 3384 in memory context "ExecutorState".

2023-04-26 10:16:49,032 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:16:51,060 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:17:32,225 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:17:32,234 MainProcess ERROR: Error when reading postmaster.opts
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/postgresql/rewind.py", line 413, in read_postmaster_opts
    with open(os.path.join(self._postgresql.data_dir, 'postmaster.opts')) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/postgres/udb01/data/postmaster.opts'
2023-04-26 10:17:32,245 MainProcess ERROR: Crash recovery finished with code=1
2023-04-26 10:17:39,073 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:17:49,032 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:17:52,617 MainProcess ERROR: Crash recovery finished with code=-6
2023-04-26 10:17:59,032 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:18:09,030 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:18:11,981 MainProcess ERROR: Crash recovery finished with code=-6
2023-04-26 10:18:13,295 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:18:16,207 MainProcess ERROR: Crash recovery finished with code=-6
2023-04-26 10:18:19,074 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:18:29,074 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:18:32,682 MainProcess ERROR: Crash recovery finished with code=-6
2023-04-26 10:18:39,030 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:18:49,030 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:18:52,144 MainProcess ERROR: Crash recovery finished with code=-6
2023-04-26 10:18:59,074 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:19:03,797 MainProcess WARNING: Postgresql is not running.
2023-04-26 10:19:05,076 MainProcess ERROR: postmaster is not running
2023-04-26 10:19:19,031 MainProcess WARNING: Postgresql is not running.

NOTE: PGDATA directory
postgres@prdudb01:/postgres/udb01/data=> ll
total 280K
-rw-r----- 1 postgres tsdba    3 Jan 20  2022 PG_VERSION
-rw-r----- 1 postgres tsdba  183 Apr 26 05:19 backup_label.old
drwxr-x--- 6 postgres tsdba 4.0K Apr 25 21:33 base/
-rw-r----- 1 postgres tsdba   47 Apr 26 12:18 current_logfiles
drwxr-x--- 2 postgres tsdba 4.0K Apr 26 12:10 global/
-rw-rw---- 1 postgres tsdba  494 Apr 26 05:16 patroni.dynamic.json
drwxr-x--- 2 postgres tsdba  92K Apr 26 12:17 pg_commit_ts/
drwxr-x--- 2 postgres tsdba 4.0K Jan 20  2022 pg_dynshmem/
-rw-r--r-- 1 postgres tsdba 1.2K Apr 26 12:09 pg_hba.conf
-rw-r--r-- 1 postgres tsdba 1.2K Apr 26 12:09 pg_hba.conf.backup
-rw-r----- 1 postgres tsdba 1.6K Apr 26 05:17 pg_ident.conf
-rw-r----- 1 postgres tsdba 1.6K Apr 26 12:09 pg_ident.conf.backup
drwxr-x--- 4 postgres tsdba 4.0K Apr 26 12:18 pg_logical/
drwxr-x--- 4 postgres tsdba 4.0K Jan 20  2022 pg_multixact/
drwxr-x--- 2 postgres tsdba 4.0K Jan 20  2022 pg_notify/
drwxr-x--- 2 postgres tsdba 4.0K Apr 26 05:16 pg_replslot/
drwxr-x--- 2 postgres tsdba 4.0K Jan 20  2022 pg_serial/
drwxr-x--- 2 postgres tsdba 4.0K Jan 20  2022 pg_snapshots/
drwxr-x--- 2 postgres tsdba 4.0K Apr 26 12:09 pg_stat/
drwxr-x--- 2 postgres tsdba 4.0K Apr 26 12:18 pg_stat_tmp/
drwxr-x--- 2 postgres tsdba  12K Apr 26 12:09 pg_subtrans/
drwxr-x--- 2 postgres tsdba 4.0K Aug  9  2022 pg_tblspc/
drwxr-x--- 2 postgres tsdba 4.0K Jan 20  2022 pg_twophase/
lrwxrwxrwx 1 postgres tsdba   19 Jan 20  2022 pg_wal -> /postgres/wal/udb01/
drwxr-x--- 2 postgres tsdba 4.0K Apr 26 05:38 pg_xact/
-rw-r----- 1 postgres tsdba  181 Apr 26 05:17 postgresql.auto.conf
-rw-r----- 1 postgres tsdba  31K Apr 26 05:17 postgresql.base.conf
-rw-r----- 1 postgres tsdba  31K Apr 26 12:09 postgresql.base.conf.backup
-rw-r--r-- 1 postgres tsdba 3.2K Apr 26 12:09 postgresql.conf
-rw-r--r-- 1 postgres tsdba 3.2K Apr 26 12:09 postgresql.conf.backup
-rw-r----- 1 postgres tsdba  450 Apr 26 12:09 postmaster.opts
-rw-r----- 1 postgres tsdba  101 Apr 26 12:09 postmaster.pid
-rw-r----- 1 postgres tsdba    0 Apr 26 05:16 recovery.signal.nop
-rw-r--r-- 1 postgres tsdba    0 Apr 26 05:19 standby.signal
```

### PostgreSQL log files

```shell
2023-04-26 17:09:51 UTC PRDUDB01 [p:582261 s:00000] :::LOG:  starting PostgreSQL 13.5 (Ubuntu 13.5-2.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9
.3.0, 64-bit
2023-04-26 17:09:51 UTC PRDUDB01 [p:582261 s:00000] :::LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-04-26 17:09:51 UTC PRDUDB01 [p:582261 s:00000] :::LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-04-26 17:09:51 UTC PRDUDB01 [p:582264 s:00000] :::LOG:  database system was shut down in recovery at 2023-04-26 17:09:50 UTC
2023-04-26 17:09:51 UTC PRDUDB01 [p:582264 s:00000] :::LOG:  entering standby mode
2023-04-26 17:09:51 UTC PRDUDB01 [p:582270 s:57P03] 127.0.0.1(39660):[unknown]::FATAL:  the database system is starting up
2023-04-26 17:09:51 UTC PRDUDB01 [p:582264 s:00000] :::LOG:  restored log file "000000BA.history" from archive
2023-04-26 17:09:52 UTC PRDUDB01 [p:582264 s:00000] :::LOG:  redo starts at 133D/CBA21B70
2023-04-26 17:09:52 UTC PRDUDB01 [p:582264 s:00000] :::LOG:  consistent recovery state reached at 133D/CBB79B40
2023-04-26 17:09:52 UTC PRDUDB01 [p:582264 s:00000] :::LOG:  invalid record length at 133D/CBB79B40: wanted 24, got 0
2023-04-26 17:09:52 UTC PRDUDB01 [p:582261 s:00000] :::LOG:  database system is ready to accept read only connections
2023-04-26 17:09:52 UTC PRDUDB01 [p:582278 s:00000] :::LOG:  started streaming WAL from primary at 133D/C8000000 on timeline 186
```

### Have you tried to use GitHub issue search?

- [X] Yes
