### ISSUE TITLE
After patroni upgrade from 2.1.3 to 3.0.2, patroni Pending restart

### ISSUE THREAD

**Issue by yinan8128** [zalando/patroni#2663]
### What happened?

After patroni upgrade from 2.1.3 to 3.0.2, we run patronictl list command that shows patroni Pending restart

patronictl -c /etc/patroni/postgresql.yml list
+ Cluster: pgcluster02 -----------+--------------+--------------+---------+----+-----------+-----------------+
| Member                          | Host         | Role         | State   | TL | Lag in MB | Pending restart |
+---------------------------------+--------------+--------------+---------+----+-----------+-----------------+
| patroni-cluster02-vm01          | 10.10.10.1   | Leader       | running |  7 |           | *               |
| patroni-cluster02-vm02          | 10.10.10.2   | Sync Standby | running |  7 |         0 | *               |
| patroni-cluster02-vm03          | 10.10.10.3   | Replica      | running |  7 |         0 | *               |
+---------------------------------+--------------+--------------+---------+----+-----------+-----------------+

pending_restart items:

postgres=# \x
Expanded display is on.
postgres=# select * from pg_settings where pending_restart=true;
-[ RECORD 1 ]---+--------------------------------------------------------------------------------
name            | recovery_target
setting         |
unit            |
category        | Write-Ahead Log / Recovery Target
short_desc      | Set to "immediate" to end recovery as soon as a consistent state is reached.
extra_desc      |
context         | postmaster
vartype         | string
source          | configuration file
min_val         |
max_val         |
enumvals        |
boot_val        |
reset_val       |
sourcefile      | /var/lib/pgsql/14/data/postgresql.conf
sourceline      | 95
pending_restart | t
-[ RECORD 2 ]---+--------------------------------------------------------------------------------
name            | recovery_target_lsn
setting         |
unit            |
category        | Write-Ahead Log / Recovery Target
short_desc      | Sets the LSN of the write-ahead log location up to which recovery will proceed.
extra_desc      |
context         | postmaster
vartype         | string
source          | configuration file
min_val         |
max_val         |
enumvals        |
boot_val        |
reset_val       |
sourcefile      | /var/lib/pgsql/14/data/postgresql.conf
sourceline      | 96
pending_restart | t
-[ RECORD 3 ]---+--------------------------------------------------------------------------------
name            | recovery_target_name
setting         |
unit            |
category        | Write-Ahead Log / Recovery Target
short_desc      | Sets the named restore point up to which recovery will proceed.
extra_desc      |
context         | postmaster
vartype         | string
source          | configuration file
min_val         |
max_val         |
enumvals        |
boot_val        |
reset_val       |
sourcefile      | /var/lib/pgsql/14/data/postgresql.conf
sourceline      | 97
pending_restart | t
-[ RECORD 4 ]---+--------------------------------------------------------------------------------
name            | recovery_target_time
setting         |
unit            |
category        | Write-Ahead Log / Recovery Target
short_desc      | Sets the time stamp up to which recovery will proceed.
extra_desc      |
context         | postmaster
vartype         | string
source          | configuration file
min_val         |
max_val         |
enumvals        |
boot_val        |
reset_val       |
sourcefile      | /var/lib/pgsql/14/data/postgresql.conf
sourceline      | 98
pending_restart | t
-[ RECORD 5 ]---+--------------------------------------------------------------------------------
name            | recovery_target_timeline
setting         | latest
unit            |
category        | Write-Ahead Log / Recovery Target
short_desc      | Specifies the timeline to recover into.
extra_desc      |
context         | postmaster
vartype         | string
source          | configuration file
min_val         |
max_val         |
enumvals        |
boot_val        | latest
reset_val       | latest
sourcefile      | /var/lib/pgsql/14/data/postgresql.conf
sourceline      | 99
pending_restart | t
-[ RECORD 6 ]---+--------------------------------------------------------------------------------
name            | recovery_target_xid
setting         |
unit            |
category        | Write-Ahead Log / Recovery Target
short_desc      | Sets the transaction ID up to which recovery will proceed.
extra_desc      |
context         | postmaster
vartype         | string
source          | configuration file
min_val         |
max_val         |
enumvals        |
boot_val        |
reset_val       |
sourcefile      | /var/lib/pgsql/14/data/postgresql.conf
sourceline      | 100
pending_restart | t

### How can we reproduce it (as minimally and precisely as possible)?

patroni upgrade from 2.1.3 to 3.0.2

### What did you expect to happen?

After patroni upgrade from 2.1.3 to 3.0.2, patroni not pending restart

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.1.3 upgrade to 3.0.2
-   PostgreSQL version: 14.6
-   DCS (and its version): consul 1.2.2-6

### Patroni configuration file

```yaml
scope: pgcluster02
name: patroni-cluster02-vm01

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.10.10.1:8008

consul:
  host: 127.0.0.1:8500
  checks: []
  register_service: true

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    failsafe_mode: true
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        archive_mode: "on"
        archive_command: /bin/true
        archive_timeout: 1800s
        autovacuum: "on"
        autovacuum_work_mem: 1GB
        autovacuum_vacuum_threshold: 50
        autovacuum_vacuum_cost_limit: 8000
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_threshold: 50
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_max_workers: 6
        auto_explain.log_min_duration: 60000
        auto_explain.log_nested_statements: true
        bgwriter_delay: 50ms
        bgwriter_lru_maxpages: 4000
        bgwriter_lru_multiplier: 4
        checkpoint_completion_target: 0.7
        checkpoint_timeout: 30min
        config_file: /var/lib/pgsql/14/data/postgresql.conf
        constraint_exclusion: partition
        cron.database_name: postgres
        datestyle: "ISO, MDY"
        default_statistics_target: 100
        default_text_search_config: "pg_catalog.english"
        effective_cache_size: "2649MB"
        hot_standby: "on"
        idle_in_transaction_session_timeout: 10min
        jit: "off"
        lc_messages: 'C'
        lc_monetary: 'C'
        lc_numeric: 'C'
        lc_time: 'C'
        lock_timeout: 30s
        log_autovacuum_min_duration: 500
        log_checkpoints: "off"
        log_connections: "off"
        log_destination: "stderr"
        log_directory: "/var/log/postgresql"
        log_disconnections: "off"
        log_duration: "off"
        log_filename: 'postgresql.log'
        log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
        log_lock_waits: "on"
        log_min_duration_statement: "5s"
        log_recovery_conflict_waits: "on"
        log_rotation_age: 0
        log_rotation_size: 0
        log_statement: "ddl"
        log_temp_files: 1MB
        log_timezone: "UTC"
        log_truncate_on_rotation: "off"
        logging_collector: "on"
        maintenance_work_mem: 2GB
        max_connections: 1000
        max_replication_slots: 10
        max_wal_senders: 10
        max_wal_size: "3532"
        min_wal_size: 1024
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        random_page_cost: 1.1
        shared_buffers: 883MB
        shared_preload_libraries: 'pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron'
        statement_timeout: 10min
        temp_file_limit: 5GB
        timezone: "UTC"
        track_io_timing: "on"
        unix_socket_directories: '/var/run/postgresql'
        wal_buffers: -1
        wal_compression: "on"
        wal_keep_size: "160MB"
        wal_level: replica
        wal_log_hints: "on"
        work_mem: "1MB"
      recovery_conf:
        restore_command: /bin/true
  initdb:
    - encoding: UTF8
    - data-checksums
    - locale: en_US.UTF-8
    - lc-collate: en_US.UTF-8
    - lc-ctype: en_US.UTF-8

  users:
    replicator:
  users:
    replicator:
      password: aaa
      options:
        - replication

postgresql:
  listen: '*'
  connect_address: 10.10.10.1:5432
  data_dir: /var/lib/pgsql/14/data
  bin_dir: /usr/pgsql-14/bin
  config_dir: /var/lib/pgsql/14/data
  hba_file: /var/lib/pgsql/14/data/pg_hba.conf
  restore: /usr/bin/patroni_wale_restore
  pgpass: /tmp/pgpass
  authentication:
    pg_rewind:
      username: postgres
      password: aaa
    replication:
      username: replicator
      password: bbb
      network: 0.0.0.0/0
    superuser:
      username: postgres
      password: aaa
  basebackup:
    - verbose
    - checkpoint: 'fast'

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "process": %(process)d, "thread": %(thread)d, "level": "%(levelname)s", "message": "%(message)s"}'
```

### patronictl show-config

```yaml
# patronictl -c /etc/patroni/postgresql.yml show-config
failsafe_mode: true
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: /bin/true
    archive_mode: 'on'
    archive_timeout: 1800s
    auto_explain.log_min_duration: 60000
    auto_explain.log_nested_statements: true
    autovacuum: 'on'
    autovacuum_analyze_scale_factor: 0.05
    autovacuum_analyze_threshold: 50
    autovacuum_max_workers: 6
    autovacuum_vacuum_cost_limit: 8000
    autovacuum_vacuum_scale_factor: 0.01
    autovacuum_vacuum_threshold: 50
    autovacuum_work_mem: 1GB
    bgwriter_delay: 50ms
    bgwriter_lru_maxpages: 4000
    bgwriter_lru_multiplier: 4
    checkpoint_completion_target: 0.7
    checkpoint_timeout: 30min
    config_file: /var/lib/pgsql/14/data/postgresql.conf
    constraint_exclusion: partition
    cron.database_name: postgres
    datestyle: ISO, MDY
    default_statistics_target: 100
    default_text_search_config: pg_catalog.english
    effective_cache_size: 2649MB
    hot_standby: 'on'
    idle_in_transaction_session_timeout: 10min
    jit: 'off'
    lc_messages: C
    lc_monetary: C
    lc_numeric: C
    lc_time: C
    lock_timeout: 30s
    log_autovacuum_min_duration: 500
    log_checkpoints: 'off'
    log_connections: 'off'
    log_destination: stderr
    log_directory: /var/log/postgresql
    log_disconnections: 'off'
    log_duration: 'off'
    log_filename: postgresql.log
    log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
    log_lock_waits: 'on'
    log_min_duration_statement: 5s
    log_recovery_conflict_waits: 'on'
    log_rotation_age: 0
    log_rotation_size: 0
    log_statement: ddl
    log_temp_files: 1MB
    log_timezone: UTC
    log_truncate_on_rotation: 'off'
    logging_collector: 'on'
    maintenance_work_mem: 2GB
    max_connections: 1000
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: '3532'
    min_wal_size: 1024
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    random_page_cost: 1.1
    shared_buffers: 883MB
    shared_preload_libraries: pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron
    statement_timeout: 10min
    temp_file_limit: 5GB
    timezone: UTC
    track_io_timing: 'on'
    unix_socket_directories: /var/run/postgresql
    wal_buffers: -1
    wal_compression: 'on'
    wal_keep_size: 160MB
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 1MB
  recovery_conf:
    restore_command: /bin/true
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
synchronous_mode: true
ttl: 30
```

### Patroni log files

```shell
N.A
```

### PostgreSQL log files

```shell
N.A
```

### Have you tried to use GitHub issue search?

- [X] Yes
