### ISSUE TITLE
Patroni spawns multiple OS Processes.

### ISSUE THREAD

**Issue by ithirisece** [zalando/patroni#2665]
### What happened?

we started seeing multiple failover on one of our patroni cluster.

Postgres DB version : psql (14.4)
patronictl version 2.1.3
NAME="CentOS Linux"

1. Patroni nodes are continuously failing over to replica nodes since leader node spawn multiple processes( within a minute it reaches 10000+ connections).
2. connections are from both leader and replica nodes.
3. Patroni tries to establish those connections from replica and leader nodes. Following are the connection details.
4. /usr/pgsql-14/bin/postgres -D /<data_Location> --config-file=/postgresql.conf --listen_addresses=0.0.0.0 --port=5432 --cluster_name=<cluster_name> --wal_level=replica --hot_standby=on --max_connections=300 --max_wal_senders=10 --max_prepared_transactions=0 --max_locks_per_transaction=64 --track_commit_timestamp=False --max_replication_slots=10 --max_worker_processes=8 --wal_log_hints=on

5. Added new nodes to the cluster but still it spawns multiple OS processes.

could you please let me know if these behaviour is seen before? If yes, please share the fix.

### How can we reproduce it (as minimally and precisely as possible)?

 Issue is still persist.

This is the version we use.

Postgres DB version : psql (14.4)
patronictl version 2.1.3
NAME="CentOS Linux"

### What did you expect to happen?

patroni stops spawning mutiple(12000+) processes.

### Patroni/PostgreSQL/DCS version

-   Patroni version: patronictl version 2.1.3
-   PostgreSQL version: psql (14.4)
-   DCS (and its version)

### Patroni configuration file

```yaml
scope: postgres<>
name: <servername>
namespace: /service/

restapi:

  listen: 0.0.0.0:8008

  connect_address: <IPADDRESS>:8008
log:
  level: DEBUG
  dir: <data_location>
  file_num: 4
  file_size: 262144000 #250 MB
etcd:
  hosts: <etc hosts>
bootstrap:
  method: initdb
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 5242880
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    synchronous_node_count: 1
    # standby_cluster:
      # host: 127.0.0.1
      # port: 1111
      # primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 300
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: replica
        wal_log_hints: on
        track_commit_timestamp: off
        hot_standby: on
        archive_mode: on

  initdb:  # List options to be passed on to initdb
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums


  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    #- host replication replicator 127.0.0.1/32 md5
    #- host all all 0.0.0.0/0 md5

    - hostssl replication     replicator all                md5
    - hostssl all     postgres localhost                md5
    - hostssl all     postgres all                md5
    - local   all             postgres                    peer
    - local   all             all                                   md5

    - hostssl all             all                all                md5 clientcert=verify-ca



postgresql:

  listen: 0.0.0.0:5432

  connect_address: <IPADDRESS>:5432
  use_unix_socket: true
  data_dir: </data>
  bin_dir: /usr/pgsql-14/bin
# config_dir: /<postgres>/config
  pgpass: /home/postgres/.pgpass
  authentication:
    replication:
      username: replicator
      password: <password>
    superuser:
      username: postgres
      password: <postgres>
#    rewind:  # Has no effect on postgres 10 and lower
#      username: rewind_user
#      password: <pwd>
  parameters:
    unix_socket_directories: /var/run/postgresql
    stats_temp_directory: <temp_direc>
    superuser_reserved_connections: 5
    huge_pages: try
    shared_buffers: 1792MB
    work_mem: 36MB
    maintenance_work_mem: 448MB
    effective_cache_size: 5GB
    checkpoint_timeout: 5min
    checkpoint_completion_target: 0.9
    min_wal_size: 80MB
    max_wal_size: 1GB
    wal_buffers: 16MB
    default_statistics_target: 100
    seq_page_cost: 1
    random_page_cost: 4
    effective_io_concurrency: 2
    synchronous_commit: on
    autovacuum: on
    autovacuum_max_workers: 5
    autovacuum_vacuum_scale_factor: 0.01
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_vacuum_cost_limit: 200
    autovacuum_vacuum_cost_delay: 20
    autovacuum_naptime: 1s
    max_files_per_process: 4096
    archive_timeout: 1800s
    archive_command: pgbackrest --stanza=<postgres-stanza> archive-push %p
    #archive_command: /bin/true
    wal_keep_size: 1024
    wal_keep_segments: 64
    max_wal_senders: 10
    max_replication_slots: 10
    shared_preload_libraries: pg_stat_statements,auto_explain,pg_cron
    cron.host: ''
    cron.database_name: 'postgres'
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    pg_stat_statements.save: off
    auto_explain.log_min_duration: 10s
    auto_explain.log_analyze: true
    auto_explain.log_buffers: true
    auto_explain.log_timing: false
    auto_explain.log_triggers: true
    auto_explain.log_verbose: true
    auto_explain.log_nested_statements: true
    track_io_timing: on
    log_lock_waits: on
    log_temp_files: 0
    track_activities: on
    track_counts: on
    track_functions: all
    log_checkpoints: on
    logging_collector: on
    log_truncate_on_rotation: on
    log_rotation_age: 1d
    log_rotation_size: 1GB
    log_line_prefix: '%t [%p-%l] %r %q%u@%d '
    log_filename: 'postgresql-%a.log'
    log_directory: <logfileloc>
    log_connections: on
    log_disconnections: on
    log_statements: on
    log_file_mode: 0644
    ssl: 'on'
    ssl_ca_file: /<location>/root.crt
    ssl_cert_file: /<location>/server.crt
    ssl_key_file: /<location>/server.key
  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false

#  callbacks:
#    on_start:
#    on_stop:
#    on_restart:
#    on_reload:
#    on_role_change:
  create_replica_methods:
    - basebackup
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'
watchdog:
  mode: off  # Allowed values: off, automatic, required
  device: <watchdog location>
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false



  # specify a node to replicate from (cascading replication)
#  replicatefrom: (node name)
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 5242880
postgresql:
  parameters:
    archive_mode: true
    hot_standby: true
    max_connections: 300
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_worker_processes: 8
    track_commit_timestamp: false
    wal_level: replica
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
synchronous_mode_strict: false
synchronous_node_count: 1
ttl: 30
```

### Patroni log files

```shell
patroni.log
```

### PostgreSQL log files

```shell
/usr/pgsql-14/bin/postgres -D /<data_Location> --config-file=/postgresql.conf --listen_addresses=0.0.0.0 --port=5432 --cluster_name=<cluster_name> --wal_level=replica --hot_standby=on --max_connections=300 --max_wal_senders=10 --max_prepared_transactions=0 --max_locks_per_transaction=64 --track_commit_timestamp=False --max_replication_slots=10 --max_worker_processes=8 --wal_log_hints=on
```

### Have you tried to use GitHub issue search?

- [X] Yes
