### ISSUE TITLE
Patroni Exception on re-init attempt

### ISSUE THREAD

**Issue by udesaiitrs** [zalando/patroni#2667]
### What happened?

We have a Postgres cluster that has been running for a week or so running on Kuberenetes w/the Timescale extension. We scaled our cluster with `kubectl scale` and scaled up/down in order, i.e. timescale-0 -> timescale-1 -> timescale-2 on scale up, and reverse on scale down. When scaled back up, we saw the python error below without much detail. Then the secondary stays in the error state as seen in the logs. 

### How can we reproduce it (as minimally and precisely as possible)?

Start a Postgres cluster with Timescale using the versions below. Create a couple tables / hypertables and send constant high volume data (we saw this issue with 10k records / sec and also 50k records / sec) for 3-5 days. It might be reproduced with a shorter timeframe. Then scale down the cluster in reverse order from when initialized so that the primary does not failover when scaling down. 

### What did you expect to happen?

Expected the secondary to start up normally and healthy.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.1.7
-   PostgreSQL version: 14.7, Timescale: 2.10.3
-   DCS (and its version): (not sure how to find this)

### Patroni configuration file

```yaml
bootstrap:
  dcs:
    loop_wait: 10
    ttl: 30
    retry_timeout: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      use_pg_rewind: true
      remove_data_directory_on_rewind_failure: true
      parameters:
        archive_command: /etc/timescaledb/scripts/pgbackrest_archive.sh %p
        archive_mode: "on"
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 10
        autovacuum_naptime: 120s
        autovacuum_vacuum_cost_limit: 500
        autovacuum_vacuum_scale_factor: 0.2
        checkpoint_timeout: 1800
        dynamic_shared_memory_type: "sysv"
        hot_standby: "on"
        log_autovacuum_min_duration: 1000
        log_checkpoints: "on"
        log_connections: "off"
        log_disconnections: "off"
        log_line_prefix: '%m: %u@%d,app=%a '
        log_lock_waits: "on"
        log_min_duration_statement: 3s
        log_replication_commands: "on"
        log_statement: none
        max_connections: 100
        max_parallel_workers: 20
        max_prepared_transactions: 150
        max_worker_processes: 40
        max_standby_archive_delay: 120s
        max_standby_streaming_delay: 120s
        pg_stat_statements.max: 1000
        pljava.java_thread_pg_entry: 'throw'
        pljava.libjvm_location: '/usr/lib/jvm/custom-runtime/lib/server/libjvm.so'
        pljava.vmoptions: '-Xshare:auto -Xms8m -Xmx8m -Xss196k -XX:MaxMetaspaceSize=16m -XX:ReservedCodeCacheSize=4m -XX:+UseSerialGC'
        shared_preload_libraries: timescaledb,pg_stat_statements
        synchronous_commit: local
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        temp_file_limit: 20GB
        timescaledb.max_background_workers: 20
        timescaledb.passfile: ../.pgpass
        timescaledb.telemetry_level: 'off'
        unix_socket_directories: /var/run/postgresql
        unix_socket_permissions: "0750"
        wal_level: "replica"
        wal_log_hints: "on"
        wal_compression: "true"
  method: restore_or_initdb
  restore_or_initdb:
    command: |
      /etc/timescaledb/scripts/restore_or_initdb.sh --encoding=UTF8 --locale=C.UTF-8
    keep_existing_recovery_conf: true
kubernetes:
  role_label: hostname.com/timescale-role
  scope_label: hostname.com/timescale-cluster
  use_endpoints: true
log:
  level: INFO
postgresql:
  authentication:
    replication:
      username: standby
    superuser:
      username: postgres
  basebackup:
  - waldir: /var/lib/postgresql/wal/pg_wal
  callbacks:
    on_reload: /etc/timescaledb/scripts/patroni_callback.sh
    on_restart: /etc/timescaledb/scripts/patroni_callback.sh
    on_role_change: /etc/timescaledb/scripts/patroni_callback.sh
    on_start: /etc/timescaledb/scripts/patroni_callback.sh
    on_stop: /etc/timescaledb/scripts/patroni_callback.sh
  create_replica_methods:
  - basebackup
  listen: 0.0.0.0:5432
  pg_hba:
  - local     all             postgres                              peer
  - local     all             all                                   md5
  - host      all             all                127.0.0.1/32       md5
  - host      all             all                ::1/128            md5
  - host      replication     standby            all                md5
  - host      all             all                all                md5
  recovery_conf:
    restore_command: /etc/timescaledb/scripts/pgbackrest_archive_get.sh %f "%p"
  use_unix_socket: true
restapi:
  listen: 0.0.0.0:8008
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 33554432
postgresql:
  parameters:
    archive_command: /etc/timescaledb/scripts/pgbackrest_archive.sh %p
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 10
    autovacuum_naptime: 120s
    autovacuum_vacuum_cost_limit: 500
    autovacuum_vacuum_scale_factor: 0.2
    checkpoint_timeout: 1800
    dynamic_shared_memory_type: sysv
    hot_standby: 'on'
    log_autovacuum_min_duration: 1000
    log_checkpoints: 'on'
    log_connections: 'off'
    log_disconnections: 'off'
    log_line_prefix: '%m: %u@%d,app=%a '
    log_lock_waits: 'on'
    log_min_duration_statement: 3s
    log_replication_commands: 'on'
    log_statement: none
    max_connections: 100
    max_parallel_workers: 20
    max_prepared_transactions: 150
    max_standby_archive_delay: 120s
    max_standby_streaming_delay: 120s
    max_worker_processes: 40
    pg_stat_statements.max: 1000
    pljava.java_thread_pg_entry: throw
    pljava.libjvm_location: /usr/lib/jvm/custom-runtime/lib/server/libjvm.so
    pljava.vmoptions: -Xshare:auto -Xms8m -Xmx8m -Xss196k -XX:MaxMetaspaceSize=16m -XX:ReservedCodeCacheSize=4m -XX:+UseSerialGC
    shared_preload_libraries: timescaledb,pg_stat_statements
    synchronous_commit: local
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    temp_file_limit: 20GB
    timescaledb.max_background_workers: 20
    timescaledb.passfile: ../.pgpass
    timescaledb.telemetry_level: 'off'
    unix_socket_directories: /var/run/postgresql
    unix_socket_permissions: '0750'
    wal_compression: 'true'
    wal_level: replica
    wal_log_hints: 'on'
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
timescale-2 (node with error) logs in comments
```

### PostgreSQL log files

```shell
timescale-0 (primary) logs in comments
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

We did not see this issue with our last set up which was Postgres 14.6 and Timescale 2.8.1 which was using Patroni 2.1.2. Only started noticing this after upgrading.
