### ISSUE TITLE
Patroni fail to add a new member when using two datacenter consul cluster

### ISSUE THREAD

**Issue by gerardo-ongres** [zalando/patroni#2670]
### What happened?

Hi all. I am planning to deploy Patroni using a two dc federated consul. I already have the federated consul clusters working:
```
[erauser@hvidldiodb12 ~]$ consul members -wan
Node                           Address             Status  Type    Build   Protocol  DC   Partition  Segment
hvidldiodb12.phx.aexp.com.dc1  10.13.102.155:8302  alive   server  1.15.2  2         dc1  default    <all>
hvidldiodb13.phx.aexp.com.dc1  10.13.102.156:8302  alive   server  1.15.2  2         dc1  default    <all>
hvidldiodb14.phx.aexp.com.dc1  10.13.102.157:8302  alive   server  1.15.2  2         dc1  default    <all>
hvidldiodb15.phx.aexp.com.dc2  10.13.102.158:8302  alive   server  1.15.2  2         dc2  default    <all>
hvidldiodb16.phx.aexp.com.dc2  10.13.102.159:8302  alive   server  1.15.2  2         dc2  default    <all>
```

Patroni service are running in the same hosts as consul.
Patroni configuration related to using consul:
```
namespace: /service/
scope: tddiodb11-consul
name: host_1
log:
    dir: /var/log/patroni
    level: DEBUG
restapi:
    connect_address: 10.13.102.155:8679
    listen: 10.13.102.155:8679

consul:
    host: 127.0.0.1:8500
    scheme: http
    dc: dc1
```
So far so good, I managed to start three nodes (from dc1) successfully:
```
+ Cluster: tddiodb11-consul ------------+---------+----+-----------+
| Member | Host          | Role         | State   | TL | Lag in MB |
+--------+---------------+--------------+---------+----+-----------+
| host_1 | 10.13.102.155 | Replica      | running |  4 |         0 |
| host_2 | 10.13.102.156 | Leader       | running |  4 |           |
| host_3 | 10.13.102.157 | Sync Standby | running |  4 |         0 |
+--------+---------------+--------------+---------+----+-----------+
```

But when attempting to start patroni on a node from dc2 (same patroni configuration) this happens:
```
2023-05-11 10:04:59,733 DEBUG: http://127.0.0.1:8500/ "PUT /v1/session/create?dc=dc1 HTTP/1.1" 500 85
2023-05-11 10:04:59,733 WARNING: Retry got exception: 500 rpc error making call: rpc error making call: apply failed: Missing node registration
```
Not sure what is missing here. It is actually possible to write using `consul kv put` from a dc2 into dc1:

```
[erauser@hvidldiodb15 patroni-consul]$ hostname
hvidldiodb15.phx.aexp.com
[erauser@hvidldiodb15 patroni-consul]$ consul members -wan
Node                           Address             Status  Type    Build   Protocol  DC   Partition  Segment
hvidldiodb12.phx.aexp.com.dc1  10.13.102.155:8302  alive   server  1.15.2  2         dc1  default    <all>
hvidldiodb13.phx.aexp.com.dc1  10.13.102.156:8302  alive   server  1.15.2  2         dc1  default    <all>
hvidldiodb14.phx.aexp.com.dc1  10.13.102.157:8302  alive   server  1.15.2  2         dc1  default    <all>
hvidldiodb15.phx.aexp.com.dc2  10.13.102.158:8302  alive   server  1.15.2  2         dc2  default    <all>
hvidldiodb16.phx.aexp.com.dc2  10.13.102.159:8302  alive   server  1.15.2  2         dc2  default    <all>
```
```
[erauser@hvidldiodb15 patroni-consul]$ consul kv put -datacenter=dc1 mydata 2
Success! Data written to: mydata
```
Any hints will be much appretiated.

### How can we reproduce it (as minimally and precisely as possible)?

Let me know if more details are needed.

### What did you expect to happen?

Patroni members running on DC2 should join the patroni cluster

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.177
-   PostgreSQL version: 13
-   DCS (and its version): consul 1.15.2

### Patroni configuration file

```yaml
namespace: /service/
scope: tddiodb11-consul
name: host_1
log:
    dir: /var/log/patroni
    level: DEBUG
restapi:
    connect_address: 10.13.102.155:8679
    listen: 10.13.102.155:8679

consul:
    host: 127.0.0.1:8500
    scheme: http
    dc: dc1
bootstrap:
    dcs:
        loop_wait: 10
        master_start_timeout: 300
        maximum_lag_on_failover: 1048576
        postgresql:
            callbacks:
                on_role_change: /etc/patroni/patroni_callback.sh
                on_start: /etc/patroni/patroni_callback.sh
                on_stop: /etc/patroni/patroni_callback.sh
            parameters:
                archive_command: sh /etc/patroni/cfg/archive_command_pgbackrest.sh
                    %p %f
                archive_mode: 'on'
                archive_timeout: 0
                config_file: /pgsql/tddiodb12/data/postgresql.conf
                hot_standby: 'on'
                log_directory: /pgsql/tddiodb12/log
                max_connections: 500
                max_locks_per_transaction: 64
                max_prepared_transactions: 0
                max_replication_slots: 10
                max_wal_senders: 10
                max_worker_processes: 8
                track_commit_timestamp: false
                wal_keep_segments: 700
                wal_level: hot_standby
                wal_log_hints: true
            recovery_conf:
                restore_command: sh /etc/patroni/cfg/restore_command_pgbackrest.sh
                restore_command: sh /etc/patroni/cfg/restore_command_pgbackrest.sh
                    %p %f
            use_pg_rewind: true
            use_slots: false
        retry_timeout: 10
        synchronous_mode: 'on'
        synchronous_mode_strict: 'on'
        ttl: 30
    initdb:
    -   encoding: UTF8
    - data-checksums
    -   waldir: /pgsql/tddiodb12/pg_wal
    pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication rep_user 10.13.102.154/32 trust
    - host replication rep_user 10.13.102.155/32 trust
    - host replication rep_user 10.13.102.156/32 trust
    - host replication rep_user 10.13.102.157/32 trust
    - host replication rep_user 10.13.102.158/32 trust
    - host replication rep_user 10.13.102.159/32 trust
postgresql:
    authentication:
        replication:
            password: xxxxxxxxxxx
            username: rep_user
        superuser:
            password: xxxxxxxxxxxxx
            username: postgres
    basebackup:
-   max-rate: 100M
    -   waldir: /pgsql/tddiodb12/pg_wal
    bin_dir: /usr/pgsql-13/bin
    callbacks:
        on_role_change: /etc/patroni/patroni_callback.sh
        on_start: /etc/patroni/patroni_callback.sh
        on_stop: /etc/patroni/patroni_callback.sh
    connect_address: 10.13.102.155:5432
    data_dir: /pgsql/tddiodb12/data
    listen: localhost,10.13.102.155:5432
    parameters:
        unix_socket_directories: /tmp
    pgpass: /tmp/pgpass0
watchdog:
    device: /dev/watchdog
    mode: automatic
    safety_margin: 5
tags:
    clonefrom: false
    nofailover: false
    noloadbalance: false
    nosync: false
```

### patronictl show-config

```yaml
namespace: /service/
scope: tddiodb11-consul
name: host_1
log:
    dir: /var/log/patroni
    level: DEBUG
restapi:
    connect_address: 10.13.102.155:8679
    listen: 10.13.102.155:8679

consul:
    host: 127.0.0.1:8500
    scheme: http
    dc: dc1
bootstrap:
    dcs:
        loop_wait: 10
        master_start_timeout: 300
        maximum_lag_on_failover: 1048576
        postgresql:
[erauser@hvidldiodb12 ~]$ ^C
[erauser@hvidldiodb12 ~]$ sudo vi /etc/patroni/patroni.yml
[erauser@hvidldiodb12 ~]$ patronictl -c /etc/patroni/patroni.yml show-config
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  callbacks:
    on_role_change: /etc/patroni/patroni_callback.sh
    on_start: /etc/patroni/patroni_callback.sh
    on_stop: /etc/patroni/patroni_callback.sh
  parameters:
    archive_command: exit 0
    archive_mode: 'on'
    archive_timeout: 0
    compute_query_id: true
    hot_standby: 'on'
    logging_collector: 'on'
    max_connections: 500
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    shared_preload_libraries: pg_stat_statements
    track_commit_timestamp: false
    wal_keep_segments: 700
    wal_level: hot_standby
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
synchronous_mode: 'on'
synchronous_mode_strict: 'on'
ttl: 30
```

### Patroni log files

```shell
2023-05-11 10:04:16,192 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-05-11 10:04:16,207 DEBUG: http://127.0.0.1:8500 "PUT /v1/session/create?dc=dc1 HTTP/1.1" 500 62
2023-05-11 10:04:16,207 DEBUG: Retry got exception: 500 rpc error making call: apply failed: Missing node registration
2023-05-11 10:04:17,229 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2023-05-11 10:04:17,239 DEBUG: http://127.0.0.1:8500 "PUT /v1/session/create?dc=dc1 HTTP/1.1" 500 85
2023-05-11 10:04:17,240 WARNING: Retry got exception: 500 rpc error making call: rpc error making call: apply failed: Missing node registration
2023-05-11 10:04:17,240 ERROR: refresh_session
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/utils.py", line 334, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/consul.py", line 306, in _do_refresh_session
    lock_delay=0.001, behavior='delete')
  File "/usr/local/lib/python3.6/site-packages/consul/base.py", line 3717, in create
    data=data)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/consul.py", line 124, in wrapper
    return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/consul.py", line 88, in response
    raise ConsulInternalError(msg)
patroni.dcs.consul.ConsulInternalError: 500 rpc error making call: rpc error making call: apply failed: Missing node registration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/consul.py", line 317, in refresh_session
    return self.retry(self._do_refresh_session)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/consul.py", line 244, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/utils.py", line 345, in __call__
    raise RetryFailedError("Exceeded retry deadline")
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
```

### PostgreSQL log files

```shell
no error appears in the postgres logs
```

### Have you tried to use GitHub issue search?

- [X] Yes
