### ISSUE TITLE
Fail to start postgres: not healthy enough for leader race

### ISSUE THREAD

**Issue by JasonkayZK** [zalando/patroni#2679]
### What happened?

I tried to use patroni to deploy a single-node cluster.
But when i mount the postgres data directory as a cifs:

```bash
mount -t cifs -o username=root,password=123456,uid=postgres,gid=postgres,dir_mode=0755,file_mode=0755,mfsymlinks,cache=none //172.28.204.212/share /user/node-data/postgresql/data
```

Patroni assumed that this node is not healthy enough, and changed postgres as a secondary:

```shell
2023-05-16 18:51:45,227 INFO: Connecting to 127.0.0.1:2181
2023-05-16 18:51:45,269 INFO: Zookeeper connection established, state: CONNECTED
2023-05-16 18:51:45,335 WARNING: Postgresql is not running.
2023-05-16 18:51:45,336 INFO: Lock owner: None; I am node-c3883ec5-3f5b-4988-b5b3-ef625a386318
2023-05-16 18:51:45,354 INFO: Lock owner: None; I am node-c3883ec5-3f5b-4988-b5b3-ef625a386318
2023-05-16 18:51:45,378 INFO: Lock owner: None; I am node-c3883ec5-3f5b-4988-b5b3-ef625a386318
2023-05-16 18:51:45,507 INFO: starting as a secondary
2023-05-16 18:51:45,516 INFO: Lock owner: None; I am node-c3883ec5-3f5b-4988-b5b3-ef625a386318
2023-05-16 18:51:45,516 INFO: not healthy enough for leader race
2023-05-16 18:51:45,516 INFO: restarting after failure in progress
2023-05-16 18:51:46,352 INFO: postmaster pid=14919
```

But when i not mount the directory, it worked just fine!

So i'm wondering how patroni check that a node is healthy enough.

### How can we reproduce it (as minimally and precisely as possible)?

Mount the postgres data on a cifs.

### What did you expect to happen?

.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 1.5.1
-   PostgreSQL version: 10.10
-   DCS (and its version):  zookeeper-3.4.13

### Patroni configuration file

```yaml
scope: pg-cluster
name: node-c3883ec5-3f5b-4988-b5b3-ef625a386318

restapi:
  listen: 0.0.0.0:8008
  connect_address: 0.0.0.0:8008


zookeeper:
    hosts: ['127.0.0.1:2181']

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    # synchronous_mode: true
    # synchronous_mode_strict: true
    # synchronous_standby_names: "*"
    postgresql:
      use_pg_rewind: true
      remove_data_directory_on_rewind_failure: true
      parameters:
        max_connections: "1000"
        autovacuum_vacuum_cost_limit: 1000
        wal_keep_segments: 512
        lock_timeout: 1800s

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
    - auth-host: md5
    - auth-local: trust
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 172.28.204.222/16 md5
  - host all all 0.0.0.0/0 md5

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 0.0.0.0:5432
  data_dir: /user/data
  bin_dir: /usr/lib/postgresql10/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: 123456
  parameters:
    unix_socket_directories: '.'
```

### patronictl show-config

```yaml
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: zookeeper, exhibitor'
```

### Patroni log files

```shell
.
```

### PostgreSQL log files

```shell
.
```

### Have you tried to use GitHub issue search?

- [X] Yes
