### ISSUE TITLE
connect ETCD with auth issue

### ISSUE THREAD

**Issue by EdithChenLi** [zalando/patroni#2686]
### What happened?

We are trying to integrate with ETCD3(authorization enabled), the etcdctl can get/update and manage the etcd with client certification(no passoword/username),  but seems patroni can not connect with ETCD3 correctly with same client certification, and is keeping request username/password, it this as expected? does patroni support non-password client cetification connection?(the client certification CN name is patroni owner patroni_usr)

The patroni log:
DEBUG: New etcd  client created for htps://127.0.0.1:4001
DEBUG: Starting new HTTPS connection(1): xxxxx:2379
DEBUG: https:xxxx:2379 "GET /version HTTP/1.1" 200 45
..........
DEBUG:https:xxxx:2379 "POST /v3alpha/kv/rang HTTP/1.1" 403 50
CRITICAL: Username or password not set, authentication is not possible
ERROR: KVCache.run <PermissionDEnied errro: 'etcdserver: permission denied, code: 7>
.......

### How can we reproduce it (as minimally and precisely as possible)?

1. ETCD created with --client-auth-auth=true
2. Enable the etcd basic auth (patroni_usr user with root role), patroni_usr also is patroni service owner
3. start patroni with client ceritification for user patroni_usr

### What did you expect to happen?

Need advise if any configuration wrong or this feature not supported

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.1
-   PostgreSQL version: 14.7
-   DCS (and its version): ETCD3.2

### Patroni configuration file

```yaml
etcd3:
   hosts:xx:2379,xx:2379, xx:2379
   protocol:https
   cacert:  $PATH/ca.pem
   cert: $PATH/patroni_usr.pem
   key: $PATH/patroni_usr.key
```

### patronictl show-config

```yaml
for etcd part only

etcd3:
   hosts:xx:2379,xx:2379, xx:2379
   protocol:https
   cacert:  $PATH/ca.pem
   cert: $PATH/patroni_usr.pem
   key: $PATH/patroni_usr.key
```

### Patroni log files

```shell
The patroni log:
DEBUG: New etcd  client created for htps://127.0.0.1:4001
DEBUG: Starting new HTTPS connection(1): xxxxx:2379
DEBUG: https:xxxx:2379 "GET /version HTTP/1.1" 200 45
..........
DEBUG:https:xxxx:2379 "POST /v3alpha/kv/rang HTTP/1.1" 403 50
CRITICAL: Username or password not set, authentication is not possible
ERROR: KVCache.run <PermissionDEnied errro: 'etcdserver: permission denied, code: 7>
.......
```

### PostgreSQL log files

```shell
DB not up as patroni can not connect with DCS
```

### Have you tried to use GitHub issue search?

- [X] Yes
