### ISSUE TITLE
REST API: no network port opened for connect_address

### ISSUE THREAD

**Issue by viteisele** [zalando/patroni#2696]
### What happened?

REST API should use two different IP addresses on my Linux server for listen and connect_address:

restapi:
  connect_address: 10.77.225.19:8008
  listen: 10.73.225.19:8008

With curl I can open a http connection to the listen address, but with connect_address there is an error message that the connection is rejected.

It seems that there is no port allocated for  connect_address: when I set connect_address to  10.77.225.19:22, which is used by ssh daemon, then patroni starts without error.

### How can we reproduce it (as minimally and precisely as possible)?

Set listen and connect_address of Rest API to different IP Addresses and try to connect to the connect_address

### What did you expect to happen?

The IP Address for connect_address should accept http request for Rest API

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.2
-   PostgreSQL version: 15.3
-   DCS (and its version):  etcd 3.4.3

### Patroni configuration file

```yaml
scope: "TEST-SAN"
namespace: "/patroni/"
name: prod22
etcd3:
  username: "test"
  password: "XXXX"
  hosts:
  - 10.74.21.9:2379
restapi:
  connect_address: 10.77.225.19:8008
  listen: 10.73.225.19:8008
  authentication:
    username: "test"
    password: "XXXX"
bootstrap:
```

### patronictl show-config

```yaml
failsafe_mode: true
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_mode: always
    max_connections: 300
    wal_keep_size: 256
  pg_hba:
  - local   all             postgres                                peer
```

### Patroni log files

```shell
Date/time type storage: 64-bit integers
  Float8 argument passing: by value
  Data page checksum version: 1
  Mock authentication nonce: a57e8bd48dfda97fde78cc9220bae72bce1c42a16475cbd796d89e43676453cb

2023-05-25 17:16:55,719 INFO: Lock owner: prod20; I am prod22
2023-05-25 17:16:55,723 INFO: Local timeline=19 lsn=0/4E0001B8
2023-05-25 17:16:55,744 INFO: primary_timeline=19
2023-05-25 17:16:55,744 INFO: Lock owner: prod20; I am prod22
2023-05-25 17:16:55,747 INFO: starting as a secondary
2023-05-25 17:16:56,134 INFO: postmaster pid=1261
```

### PostgreSQL log files

```shell
no problem with PostgreSQL
```

### Have you tried to use GitHub issue search?

- [X] Yes
