### ISSUE TITLE
Replica on old timeline

### ISSUE THREAD

**Issue by jbnjohnathan** [zalando/patroni#2711]
### What happened?

After doing a restore using pgbackrest the Replica node is stuck on timeline 4, while the Leader and Sync standby are on timeline 8.
```
# patronictl -c /etc/patroni/patroni.yml list
+ Cluster: db-cluster ----+--------------+---------+----+-----------+
| Member        | Host       | Role         | State   | TL | Lag in MB |
+---------------+------------+--------------+---------+----+-----------+
| db01 | 10.50.3.34 | Leader       | running |  8 |           |
| db02 | 10.50.3.35 | Sync Standby | running |  8 |         0 |
| db03 | 10.50.3.36 | Replica      | running |  4 |       128 |
+---------------+------------+--------------+---------+----+-----------+
```

```
# patronictl -c /etc/patroni/patroni.yml reinit db-cluster db03
+ Cluster: db-cluster ----+--------------+---------+----+-----------+
| Member        | Host       | Role         | State   | TL | Lag in MB |
+---------------+------------+--------------+---------+----+-----------+
| db01 | 10.50.3.34 | Leader       | running |  8 |           |
| db02 | 10.50.3.35 | Sync Standby | running |  8 |         0 |
| db03 | 10.50.3.36 | Replica      | running |  4 |       128 |
+---------------+------------+--------------+---------+----+-----------+
Are you sure you want to reinitialize members db03? [y/N]: y
Success: reinitialize for member db03
```

 After re-init, the Replica is still behind
```
# patronictl -c /etc/patroni/patroni.yml list
+ Cluster: db-cluster ----+--------------+---------+----+-----------+
| Member        | Host       | Role         | State   | TL | Lag in MB |
+---------------+------------+--------------+---------+----+-----------+
| db01 | 10.50.3.34 | Leader       | running |  8 |           |
| db02 | 10.50.3.35 | Sync Standby | running |  8 |         0 |
| db03 | 10.50.3.36 | Replica      | running |  4 |       128 |
+---------------+------------+--------------+---------+----+-----------+
```
Logs afte reinit
```
Jun 09 13:41:35 db03 patroni[51058]: 2023-06-09 13:41:35,353 INFO: Lock owner: db01; I am db03
Jun 09 13:41:35 db03 patroni[51058]: 2023-06-09 13:41:35,446 INFO: reinitialize in progress
Jun 09 13:41:36 db03 patroni[57036]: /var/run/postgresql:5432 - accepting connections
Jun 09 13:41:36 db03 patroni[57038]: /var/run/postgresql:5432 - accepting connections
Jun 09 13:41:36 db03 patroni[51058]: 2023-06-09 13:41:36,314 INFO: Lock owner: db01; I am db03
Jun 09 13:41:36 db03 patroni[51058]: 2023-06-09 13:41:36,315 INFO: establishing a new patroni connection to the postgres cluster
Jun 09 13:41:36 db03 patroni[51058]: 2023-06-09 13:41:36,374 INFO: no action. I am (db03), a secondary, and following a leader (db01)
```

I also tried to stop the service on the Replica, deleting the postgres data directory and starting Patroni again.
After this the Replica sync data into the data directory again but remains on timeline 4

### How can we reproduce it (as minimally and precisely as possible)?

Unclear

### What did you expect to happen?

I expected the Replica to sync the timeline with the Leader

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.2
-   PostgreSQL version: 14
-   DCS (and its version): etcd 3.5.7

### Patroni configuration file

```yaml
---

scope: db-cluster
name: db03
namespace: /service/


restapi:
  listen: 10.50.3.36:8008
  connect_address: db03:8008
  certfile: /etc/pki/tls/certs/db03.crt
  keyfile: /etc/pki/tls/private/db03.key
  cafile: /etc/pki/tls/certs/ca.pem
  authentication:
    username: patroni
    password: XXXXXX

ctl:
  cacert: /etc/pki/tls/certs/ca.pem

etcd3:
  hosts: db01:2379,db02:2379,db03:2379
  protocol: https
  cacert: /etc/pki/tls/certs/ca.pem
  cert: /etc/pki/tls/certs/db03.crt
  key: /etc/pki/tls/private/db03.key


bootstrap:
  method: pgbackrest
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_node_count: 1
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 1000
        superuser_reserved_connections: 5
        password_encryption: scram-sha-256
        max_locks_per_transaction: 512
        max_prepared_transactions: 0
        huge_pages: try
        shared_buffers: 7972MB
        effective_cache_size: 23916MB
        work_mem: 128MB
        maintenance_work_mem: 256MB
        checkpoint_timeout: 15min
        checkpoint_completion_target: 0.9
        min_wal_size: 2GB
        max_wal_size: 8GB
        wal_buffers: 32MB
        default_statistics_target: 1000
        seq_page_cost: 1
        random_page_cost: 4
        effective_io_concurrency: 2
        synchronous_commit: on
        autovacuum: on
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_scale_factor: 0.01
        autovacuum_vacuum_cost_limit: 500
        autovacuum_vacuum_cost_delay: 2
        autovacuum_naptime: 1s
        max_files_per_process: 4096
        archive_mode: on
        archive_timeout: 1800s
        archive_command: pgbackrest --stanza=db-cluster archive-push %p
        wal_level: replica
        wal_keep_size: 2GB
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: on
        wal_log_hints: on
        wal_compression: on
        shared_preload_libraries: pg_stat_statements,auto_explain
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        pg_stat_statements.track_utility: false
        pg_stat_statements.save: true
        auto_explain.log_min_duration: 10s
        auto_explain.log_analyze: true
        auto_explain.log_buffers: true
        auto_explain.log_timing: false
        auto_explain.log_triggers: true
        auto_explain.log_verbose: true
        auto_explain.log_nested_statements: true
        auto_explain.sample_rate: 0.01
        track_io_timing: on
        log_lock_waits: on
        log_temp_files: 0
        track_activities: on
        track_counts: on
        track_functions: all
        log_checkpoints: on
        logging_collector: on
        log_truncate_on_rotation: on
        log_rotation_age: 1d
        log_rotation_size: 0
        log_line_prefix: '%t [%p-%l] %r %q%u@%d '
        log_filename: postgresql-%a.log
        log_directory: /var/log/postgresql
        hot_standby_feedback: on
        max_standby_streaming_delay: 30s
        wal_receiver_status_interval: 10s
        idle_in_transaction_session_timeout: 10min
        jit: off
        max_worker_processes: 24
        max_parallel_workers: 8
        max_parallel_workers_per_gather: 2
        max_parallel_maintenance_workers: 2
        ssl: on
        ssl_ca_file: /etc/pki/tls/certs/ca.pem
        ssl_cert_file: /etc/pki/tls/certs/db.crt
        ssl_key_file: /etc/pki/tls/private/db.key
        ssl_ciphers: HIGH:MEDIUM:+3DES:!aNULL
        ssl_prefer_server_ciphers: on
        ssl_min_protocol_version: TLSv1.2

#  initdb:  # List options to be passed on to initdb
#    - encoding: UTF8
#    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5


postgresql:
  listen: 10.50.3.36,10.50.3.37,127.0.0.1:5432
  connect_address: 10.50.3.36:5432
  use_unix_socket: true
  data_dir: /var/lib/pgsql/14/data
  bin_dir: /usr/pgsql-14/bin
  config_dir: /var/lib/pgsql/14/data
  pgpass: /var/lib/pgsql/.pgpass_patroni
  authentication:
    replication:
      username: replicator
      password: XXXX
    superuser:
      username: postgres
      password: XXXXX
#    rewind:  # Has no effect on postgres 10 and lower
#      username: rewind_user
#      password: rewind_password
  parameters:
    unix_socket_directories: /var/run/postgresql
    stats_temp_directory: /var/lib/pgsql_stats_tmp


  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: true


  create_replica_methods:
    - basebackup
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'

  recovery_conf:
    restore_command: pgbackrest --stanza=db-cluster archive-get %f %p

watchdog:
  mode: automatic  # Allowed values: off, automatic, required
  device: /dev/watchdog  # Path to the watchdog device
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

  # specify a node to replicate from (cascading replication)
#  replicatefrom: (node name)
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=db-cluster archive-push %p
    archive_mode: 'on'
    archive_timeout: 1800s
    auto_explain.log_analyze: 'true'
    auto_explain.log_buffers: 'true'
    auto_explain.log_min_duration: 10s
    auto_explain.log_nested_statements: 'true'
    auto_explain.log_timing: 'false'
    auto_explain.log_triggers: 'true'
    auto_explain.log_verbose: 'true'
    auto_explain.sample_rate: 0.01
    autovacuum: 'on'
    autovacuum_analyze_scale_factor: 0.01
    autovacuum_max_workers: 5
    autovacuum_naptime: 1s
    autovacuum_vacuum_cost_delay: 2
    autovacuum_vacuum_cost_limit: 500
    autovacuum_vacuum_scale_factor: 0.01
    checkpoint_completion_target: 0.9
    checkpoint_timeout: 15min
    default_statistics_target: 1000
    effective_cache_size: 23916MB
    effective_io_concurrency: 2
    hot_standby: 'on'
    hot_standby_feedback: 'on'
    huge_pages: try
    idle_in_transaction_session_timeout: 10min
    jit: 'off'
    log_checkpoints: 'on'
    log_directory: /var/log/postgresql
    log_filename: postgresql-%a.log
    log_line_prefix: '''%t [%p-%l] %r %q%u@%d '''
    log_lock_waits: 'on'
    log_rotation_age: 1d
    log_rotation_size: 0
    log_temp_files: 0
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    maintenance_work_mem: 256MB
    max_connections: 1000
    max_files_per_process: 4096
    max_locks_per_transaction: 512
    max_parallel_maintenance_workers: 2
    max_parallel_workers: 8
    max_parallel_workers_per_gather: 2
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_standby_streaming_delay: 30s
    max_wal_senders: 10
    max_wal_size: 8GB
    max_worker_processes: 24
    min_wal_size: 2GB
    password_encryption: scram-sha-256
    pg_stat_statements.max: 10000
    pg_stat_statements.save: 'true'
    pg_stat_statements.track: all
    pg_stat_statements.track_utility: 'false'
    random_page_cost: 4
    seq_page_cost: 1
    shared_buffers: 7972MB
    shared_preload_libraries: pg_stat_statements,auto_explain
    ssl: 'on'
    ssl_ca_file: /etc/pki/tls/certs/ca.pem
    ssl_cert_file: /etc/pki/tls/certs/db.crt
    ssl_ciphers: HIGH:MEDIUM:+3DES:!aNULL
    ssl_key_file: /etc/pki/tls/private/db.key
    ssl_min_protocol_version: TLSv1.2
    ssl_prefer_server_ciphers: 'on'
    superuser_reserved_connections: 5
    synchronous_commit: 'on'
    track_activities: 'on'
    track_counts: 'on'
    track_functions: all
    track_io_timing: 'on'
    wal_buffers: 32MB
    wal_compression: 'on'
    wal_keep_size: 2GB
    wal_level: replica
    wal_log_hints: 'on'
    wal_receiver_status_interval: 10s
    work_mem: 128MB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
synchronous_node_count: 1
ttl: 30
```

### Patroni log files

```shell
.
```

### PostgreSQL log files

```shell
.
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

After a while Replica is suddenly on correct timeline and no lag. But it remained with a static amount of lag for around 10-20 minutes.
