### ISSUE TITLE
Patroni ignores GUC's specified as string if they are validated

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando/patroni#2735]
### What happened?

We configure our Patroni using a golang operator. One of the things it does is to configure the `patroni.yaml`, for example:

```yaml
        bootstrap:
          dcs:
            postgresql:
              parameters:
                log_checkpoints: "on"
                log_connections: "off"
                max_connections: "57"
```

This used to work fine, but we just switched to the most recent Patroni, and this fails. `max_connections` is not honored, it is set to the default of 100.

Cmdlines as set by Patroni:
```console
$ cat /proc/154/cmdline | tr '\0' '\n'
/usr/lib/postgresql/14/bin/postgres
-D
/home/postgres/pgdata/data
--config-file=/home/postgres/pgdata/data/postgresql.conf
--listen_addresses=0.0.0.0
--port=5432
--cluster_name=a59r0uuuj3-an
--wal_level=replica
--hot_standby=on
--max_connections=100
--max_wal_senders=10
--max_prepared_transactions=100
--max_locks_per_transaction=69
--track_commit_timestamp=off
--max_replication_slots=10
--max_worker_processes=8
--wal_log_hints=on
```

### How can we reproduce it (as minimally and precisely as possible)?

Set `max_connections` to `"57"` in `patroni.yaml` and see the results.

### What did you expect to happen?

That the parameter was interpreted and used by Patroni.

Notice that `max_connections` is *missing* from patronictl show-config, and therefore defaults to 100.

Other guc's that are not involved in the parameter checking, for example, `autovacuum_max_workers` are handled correctly. (This makes sense to me, Patroni does not inspect these, it only passes them along).

p

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.3
-   PostgreSQL version: 15.3
-   DCS (and its version): Kubernetes

### Patroni configuration file

Slightly redacted

```yaml
bootstrap:
  dcs:
    failsafe_mode: true
    loop_wait: 10
    master_start_timeout: 15
    maximum_lag_on_failover: 16777217
    postgresql:
      authentication: {}

     parameters:
        autovacuum_max_workers: "10"
        max_connections: "79"
```

### patronictl show-config

Slightly redacted

```yaml
postgresql:
  parameters:
    archive_command: envdir /etc/postgresql/environment "/etc/postgresql/scripts/timescaledb/wal_archive_command_pgbackrest.sh" "%p"
    archive_mode: 'on'
    archive_timeout: 300s
    autovacuum_max_workers: '10'
    autovacuum_naptime: '10'
    checkpoint_completion_target: '0.9'
    effective_cache_size: 3GB
    effective_io_concurrency: '256'
    extwlist.custom_path: /etc/postgresql/scripts
    hot_standby: 'on'
    maintenance_work_mem: 512MB
    max_locks_per_transaction: 69
    max_parallel_workers: '2'
    max_parallel_workers_per_gather: '1'
    max_prepared_transactions: 100
    max_slot_wal_keep_size: 5GB
    max_wal_size: 6GB
    max_worker_processes: 8
```

### Patroni log files

```shell
postgresql:
  parameters:
    autovacuum_max_workers: '10'
```

### PostgreSQL log files

```shell
not relevant
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Created a [tentative PR](https://github.com/zalando/patroni/pull/2734) to solve this.
