### ISSUE TITLE
3.0.3 does not change max_connections

### ISSUE THREAD

**Issue by IgorOhrimenko** [zalando/patroni#2750]
### What happened?

patroni 3.0.3 is ignoring change the max_connections from DCS
```
Jul 11 19:08:34 test-01 patroni[10090]: 2023-07-11 19:08:34,726 INFO: No PostgreSQL configuration items changed, nothing to reload.
```

https://github.com/zalando/patroni/assets/24807060/b1b950fa-a9ad-4b91-96a4-7d32fc3eccc3

### How can we reproduce it (as minimally and precisely as possible)?

debian 11
pip install patroni
systemctl start patroni.service

### What did you expect to happen?

```
Jul 11 19:07:25 test-01 patroni[10041]: 2023-07-11 19:07:25,230 INFO: Changed max_connections from 100 to 101 (restart might be required)
Jul 11 19:07:25 test-01 patroni[10041]: 2023-07-11 19:07:25,231 INFO: Reloading PostgreSQL configuration.
Jul 11 19:07:25 test-01 patroni[10055]: 2023-07-11 19:07:25.236 MSK [10055] LOG:  received SIGHUP, reloading configuration files
Jul 11 19:07:25 test-01 patroni[10055]: 2023-07-11 19:07:25.237 MSK [10055] LOG:  parameter "max_connections" cannot be changed without restarting the server
Jul 11 19:07:25 test-01 patroni[10055]: 2023-07-11 19:07:25.237 MSK [10055] LOG:  configuration file "/var/lib/postgresql/15/cluster-psql-test/postgresql.conf" contains errors; unaffected changes were applied
Jul 11 19:07:25 test-01 patroni[10077]: server signaled
```

https://github.com/zalando/patroni/assets/24807060/9a801d4a-e08e-475f-bae4-9d079634895f

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.3
-   PostgreSQL version: 14 and 15
-   DCS (and its version): etcd3

### Patroni configuration file

```yaml
name:  test-01.psql.lan
scope: cluster-psql-test

restapi:
  listen: 10.10.10.10:4432
  connect_address: 10.10.10.10:4432

etcd3:
  protocol: http
  username: patroni
  password: pass
  srv:      psql.lan

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "off"
        shared_buffers: "985MB"
        effective_cache_size: "1674MB"
        maintenance_work_mem: "197MB"
        work_mem: "2MB"
        wal_buffers: "16MB"
        checkpoint_completion_target: "0.9"
        default_statistics_target: "100"
        min_wal_size: "1GB"
        max_wal_size: "2GB"
        effective_io_concurrency: "200"
        hot_standby: "on"
        log_destination: "stderr"
        log_directory: "/var/log/postgresql"
        log_filename: "cluster-psql-test.log"
        logging_collector: "on"
        log_min_duration_statement: "5000"
        log_rotation_age: "0"
        log_rotation_size: "0"
        max_standby_streaming_delay: "30s"
        max_connections: "500"
        max_replication_slots: "10"
        max_wal_senders: "10"
        pg_stat_statements.max: "10000"
        pg_stat_statements.track: "all"
        random_page_cost: "1.1"
        shared_preload_libraries: "pg_stat_statements"
        synchronous_commit: "on"
        unix_socket_directories: "/var/run/postgresql/"
        wal_keep_segments: "100"
        wal_level: "logical"
        wal_log_hints: "on"
        wal_keep_size: "2GB"
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.0.0.0/8 md5
    - host all all 127.0.0.1/32 md5
    - host all all 10.0.0.0/8 md5
  users:
    test:
      password: test
postgresql:
  listen: 127.0.0.1,10.10.10.10:5432
  connect_address: 10.10.10.10:5432
  bin_dir:  /usr/lib/postgresql/15/bin
  data_dir: /var/lib/postgresql/15/cluster-psql-test
  pgpass: /var/lib/postgresql/.pgpass
  authentication:
    replication:
      username: replicator
      password: test
    superuser:
      username: postgres
      password: test
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_mode: 'off'
    hot_standby: 'on'
    log_destination: stderr
    log_directory: /var/log/postgresql
    log_filename: cluster-psql-test.log
    log_min_duration_statement: '5001'
    max_connections: '100'
    unix_socket_directories: /var/run/postgresql/
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
Jul 11 19:08:34 test-01 patroni[10090]: 2023-07-11 19:08:34,726 INFO: No PostgreSQL configuration items changed, nothing to reload.
```

### PostgreSQL log files

```shell
Nothing error
```

### Have you tried to use GitHub issue search?

- [X] Yes
