### ISSUE TITLE
Securing Patroni REST API change sslmode

### ISSUE THREAD

**Issue by yinan8128** [zalando/patroni#2753]
### What happened?

Hi

Thank you for the help of https://github.com/zalando/patroni/issues/2739

https://github.com/zalando/patroni/issues/2739#issuecomment-1628335422 "That the host to which the request is made matches CN in the certificate"

https://github.com/zalando/patroni/issues/2739#issuecomment-1628494974 "While for HTTPS defaults are way stricter, and similar to verify-full"

Is it possible to secure Patroni REST API HTTPS solution or Using SSL Certificates solution to support client/ctl/patroni itself usage to choose sslmode like verify-ca not verify-full?(Which postgresql supported) I checked both patroni document and below articles not mentioned, or now only support verify-full please?
https://www.percona.com/blog/securing-patroni-rest-api-end-points-part-1/
https://www.percona.com/blog/securing-patroni-rest-api-end-points-part-2-using-ssl-certificates/

I asked in slack no answer yet, if possible, could you please advise how to configure? Then no need have to add ip address or hostname to server certificate CN part and worry about ip address or hostname change

### How can we reproduce it (as minimally and precisely as possible)?

N.A

### What did you expect to happen?

Securing Patroni REST API HTTPS solution or Using SSL Certificates solution support client/ctl/patroni itself usage to choose sslmode like verify-ca not verify-full, then no need have to add ip address or hostname to server certificate CN part and worry about ip address or hostname change

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.2
-   PostgreSQL version: 11.18
-   DCS (and its version): consul 1.2.2

### Patroni configuration file

```yaml
scope: pgcluster11
name: patroni_cluster-1279371700

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.65.178.43:8008
  authentication:
    username: patroniAdmin
    password: aaa
  certfile: /var/lib/pgsql/tls/server.crt
  keyfile: /var/lib/pgsql/tls/server.key
  cafile: /var/lib/pgsql/tls/root.crt

consul:
  host: 127.0.0.1:8500
  checks: []
  register_service: true

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    failsafe_mode: true
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        archive_mode: "on"
        archive_command: /bin/true
        archive_timeout: 1800s
        autovacuum: "on"
        autovacuum_work_mem: 1GB
        autovacuum_vacuum_threshold: 50
        autovacuum_vacuum_cost_delay: 2ms
        autovacuum_vacuum_cost_limit: 8000
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_threshold: 50
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_max_workers: 6
        auto_explain.log_min_duration: 60000
        auto_explain.log_nested_statements: true
        bgwriter_delay: 50ms
        bgwriter_lru_maxpages: 4000
        bgwriter_lru_multiplier: 4
        checkpoint_completion_target: 0.7
        checkpoint_timeout: 30min
        config_file: /var/lib/pgsql/11/data/postgresql.conf
        constraint_exclusion: partition
        cron.database_name: postgres
        datestyle: "ISO, MDY"
        default_statistics_target: 100
        default_text_search_config: "pg_catalog.english"
        effective_cache_size: "5952MB"
        hot_standby: "on"
        idle_in_transaction_session_timeout: 10min
        lc_messages: 'C'
        lc_monetary: 'C'
        lc_numeric: 'C'
        lc_time: 'C'
        lock_timeout: 30s
        log_autovacuum_min_duration: 500
        log_checkpoints: "off"
        log_connections: "off"
        log_destination: "stderr"
        log_directory: "/var/log/postgresql"
        log_disconnections: "off"
        log_duration: "off"
        log_filename: 'postgresql.log'
        log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
        log_lock_waits: "on"
        log_min_duration_statement: "5s"
        log_rotation_age: 0
        log_rotation_size: 0
        log_statement: "ddl"
        log_temp_files: 1MB
        log_timezone: "UTC"
        log_truncate_on_rotation: "off"
        logging_collector: "on"
        maintenance_work_mem: 2GB
        max_connections: 1000
        max_replication_slots: 10
        max_wal_senders: 10
        max_wal_size: "7936"
        min_wal_size: 1024
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        random_page_cost: 1.1
        shared_buffers: 1984MB
        shared_preload_libraries: 'pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron'
        ssl: 'on'
        ssl_ca_file: '/var/lib/pgsql/tls/root.crt'
        ssl_cert_file: '/var/lib/pgsql/tls/server.crt'
        ssl_key_file: '/var/lib/pgsql/tls/server.key'
        statement_timeout: 10min
        temp_file_limit: 5GB
        timezone: "UTC"
        track_io_timing: "on"
        unix_socket_directories: '/var/run/postgresql'
        wal_buffers: -1
        wal_compression: "on"
        wal_keep_segments: "10"
        wal_level: replica
        wal_log_hints: "on"
        work_mem: "3MB"
      recovery_conf:
        restore_command: /bin/true
  initdb:
    - encoding: UTF8
    - data-checksums
    - locale: en_US.UTF-8
    - lc-collate: en_US.UTF-8
    - lc-ctype: en_US.UTF-8

  users:
    replicator:
      password: ccc
      options:
        - replication

postgresql:
  listen: '*'
  connect_address: 10.65.178.43:5432
  data_dir: /var/lib/pgsql/11/data
  bin_dir: /usr/pgsql-11/bin
  config_dir: /var/lib/pgsql/11/data
  hba_file: /var/lib/pgsql/11/data/pg_hba.conf
  restore: /usr/bin/patroni_wale_restore
  pgpass: /tmp/pgpass
  authentication:
    pg_rewind:
      username: postgres
      password: bbb
    replication:
      username: replicator
      password: ccc
      network: 0.0.0.0/0
    superuser:
      username: postgres
      password: bbb
  callbacks:
    on_start: /etc/patroni/callback.sh
    on_stop: /etc/patroni/callback.sh
    on_role_change: /etc/patroni/callback.sh
  basebackup:
    - verbose
    - checkpoint: 'fast'
  pg_hba:
    - local all postgres trust
    - local all all trust
    - host replication replicator 0.0.0.0/0 md5
    - host replication replicator ::/0 md5
    - host replication postgres 127.0.0.1/32 trust
    - host replication postgres ::1/128 trust
    - host all all 127.0.0.1/32 md5
    - host all all ::1/128 md5
    - host postgres postgres 10.65.178.43/32 md5
    - host postgres pgwatch2 10.65.178.43/32 md5
    - host postgres replicator 10.65.178.43/32 md5
    - host postgres postgres 10.65.178.45/32 md5
    - host postgres pgwatch2 10.65.178.45/32 md5
    - host postgres replicator 10.65.178.45/32 md5
    - host postgres postgres 10.65.162.52/32 md5
    - host postgres pgwatch2 10.65.162.52/32 md5
    - host postgres replicator 10.65.162.52/32 md5
    - host postgres all 0.0.0.0/0 reject
    - host postgres all ::/0 reject
    - hostnossl all all 0.0.0.0/0 md5
    - hostnossl all all ::/0 md5
    - hostssl all all 0.0.0.0/0 md5 clientcert=1
    - hostssl all all ::/0 md5 clientcert=1

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "process": %(process)d, "thread": %(thread)d, "level": "%(levelname)s", "message": "%(message)s"}'
```

### patronictl show-config

```yaml
# patronictl -c /etc/patroni/postgresql.yml show-config                                                                                                  [34/1992]
failsafe_mode: true
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: /bin/true
    archive_mode: 'on'
    archive_timeout: 1800s
    auto_explain.log_min_duration: 60000
    auto_explain.log_nested_statements: true
    autovacuum: 'on'
    autovacuum_analyze_scale_factor: 0.05
    autovacuum_analyze_threshold: 50
    autovacuum_max_workers: 6
    autovacuum_vacuum_cost_delay: 2ms
    autovacuum_vacuum_cost_limit: 8000
    autovacuum_vacuum_scale_factor: 0.01
    autovacuum_vacuum_threshold: 50
    autovacuum_work_mem: 1GB
    bgwriter_delay: 50ms
    bgwriter_lru_maxpages: 4000
    bgwriter_lru_multiplier: 4
    checkpoint_completion_target: 0.7
    checkpoint_timeout: 30min
    config_file: /var/lib/pgsql/11/data/postgresql.conf
    constraint_exclusion: partition
    cron.database_name: postgres
    datestyle: ISO, MDY
    default_statistics_target: 100
    default_text_search_config: pg_catalog.english
    effective_cache_size: 5952MB
    hot_standby: 'on'
    idle_in_transaction_session_timeout: 10min
    lc_messages: C
    lc_monetary: C
    lc_numeric: C
    lc_time: C
    lock_timeout: 30s
    log_autovacuum_min_duration: 500
    log_checkpoints: 'off'
    log_connections: 'off'
    log_destination: stderr
    log_directory: /var/log/postgresql
    log_disconnections: 'off'
    log_duration: 'off'
    log_filename: postgresql.log
    log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
    log_lock_waits: 'on'
    log_min_duration_statement: 5s
    log_rotation_age: 0
    log_rotation_size: 0
    log_statement: ddl
    log_temp_files: 1MB
    log_timezone: UTC
    log_truncate_on_rotation: 'off'
    logging_collector: 'on'
    maintenance_work_mem: 2GB
    max_connections: 1000
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: '7936'
    min_wal_size: 1024
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    random_page_cost: 1.1
    shared_buffers: 1984MB
    shared_preload_libraries: pg_stat_statements,pg_stat_kcache,auto_explain,pg_cron
    ssl: 'on'
    ssl_ca_file: /var/lib/pgsql/tls/root.crt
    ssl_cert_file: /var/lib/pgsql/tls/server.crt
    ssl_key_file: /var/lib/pgsql/tls/server.key
    statement_timeout: 10min
    temp_file_limit: 5GB
    timezone: UTC
    track_io_timing: 'on'
    unix_socket_directories: /var/run/postgresql
    wal_buffers: -1
    wal_compression: 'on'
    wal_keep_segments: '10'
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 3MB
  recovery_conf:
    restore_command: /bin/true
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
synchronous_mode: true
ttl: 30
```

### Patroni log files

```shell
N.A
```

### PostgreSQL log files

```shell
N.A
```

### Have you tried to use GitHub issue search?

- [X] Yes
