### ISSUE TITLE
wrong validate for value = 0

### ISSUE THREAD

**Issue by anyafit** [zalando/patroni#2817]
### What happened?

if i set max_prepared_transaction = 0 i have warning:
`2023-08-16 10:51:35,219 - WARNING - postgresql parameter max_prepared_transactions=0 failed validation, defaulting to 0`

### How can we reproduce it (as minimally and precisely as possible)?

set max_prepared_transaction = 0 (or other parametr, max_connections for example)

### What did you expect to happen?

if value 0 is correct, than don't report it

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.1.0
-   PostgreSQL version: 13
-   DCS (and its version): etcd

### Patroni configuration file

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 100
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 4
    max_worker_processes: 8
    wal_keep_segments: 50
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 100
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 4
    max_worker_processes: 8
    wal_keep_segments: 50
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
no
```

### PostgreSQL log files

```shell
no
```

### Have you tried to use GitHub issue search?

- [X] Yes
