### ISSUE TITLE
Patroni restarts manually stopped replica in maintenance mode(pause)

### ISSUE THREAD

**Issue by kuzmindb** [zalando/patroni#2834]
### What happened?

Under certain circumstances Patroni restarts PostgreSQL that was previously stopped by pg_ctl in maintenance mode. Key point is that Postgres does not stop immediatly in such cases.

### How can we reproduce it (as minimally and precisely as possible)?

I managed to reproduce it with the following script.
The idea is to slow down the stopping process of Postgres and force it stop just when Patroni is about to run another loop.
This script is sending a STOP signal to checkpointer to emulate long shut down. Then it watches on replica key in dcs to be in sync with Patroni loop. When Patroni updates member key, the script executes pg_ctl stop and wait for loop_wait seconds, then wakes up checkpointer.
In my test environment this script reproduces described behavior most of the times. If it doesn't - just unpause the cluster and try again.
```
#!/bin/env bash

VICTIM_PID=$(/usr/pgsql-13/bin/psql -Aqtc "select pid from pg_stat_activity where backend_type = 'checkpointer'")

/usr/local/bin/patronictl -c /etc/patroni/patroni.yml pause --wait
kill -STOP $VICTIM_PID
curl -o /dev/null -s "localhost:2379/v2/keys/service/postgres-cluster/members/pause-test-2?wait=true"
/usr/pgsql-13/bin/pg_ctl -D /var/lib/pgsql/13/data stop -m fast --no-wait
sleep 10 # loop_wait
kill -CONT $VICTIM_PID

# take a nap and check if postgres is running again
sleep 20
/usr/pgsql-13/bin/pg_isready
```

### What did you expect to happen?

> When Postgres is stopped, Patroni does not try to start it.

https://patroni.readthedocs.io/en/latest/pause.html

### Patroni/PostgreSQL/DCS version

Patroni/PostgreSQL/DCS version
-   Patroni version: 2.1.7 and 3.1.0
-   PostgreSQL version: 13.9
-   DCS (and its version): etcd 3.5.9, v2 api(but it doesn't matter, reproduces on v3 as well)

### Patroni configuration file

```yaml
---
scope: postgres-cluster
name: pause-test-2
namespace: /service/


restapi:
  listen: 192.168.26.67:8008
  connect_address: 192.168.26.67:8008

etcd:
  host: 192.168.26.67:2379
  hosts: 192.168.26.34:2379,192.168.26.67:2379,192.168.26.47:2379

bootstrap:
  method: initdb
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: false
    synchronous_node_count: 1
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_command: /bin/true
        logging_collector: on
        log_truncate_on_rotation: on
        log_rotation_age: 1d
        log_rotation_size: 0
        log_line_prefix: '%t [%p-%l] %r %q%u@%d '
        log_filename: postgresql-%a.log
        log_directory: /var/log/postgresql

  initdb:  # List options to be passed on to initdb
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5


postgresql:
  listen: 192.168.26.67,127.0.0.1:5432
  connect_address: 192.168.26.67:5432
  use_unix_socket: true
  data_dir: /var/lib/pgsql/13/data
  bin_dir: /usr/pgsql-13/bin
  config_dir: /var/lib/pgsql/13/data
  pgpass: /var/lib/pgsql/.pgpass_patroni
  authentication:
    replication:
      username: replicator
      password: replicator-pass
    superuser:
      username: postgres
      password: postgres-pass
#    rewind:  # Has no effect on postgres 10 and lower
#      username: rewind_user
#      password: rewind_password
  parameters:
    unix_socket_directories: /var/run/postgresql
    stats_temp_directory: /var/lib/pgsql_stats_tmp


  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false


  create_replica_methods:
    - basebackup
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'


watchdog:
  mode: off  # Allowed values: off, automatic, required
  device: /dev/watchdog  # Path to the watchdog device
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: /bin/true
    log_directory: /var/log/postgresql
    log_filename: postgresql-%a.log
    log_line_prefix: '%t [%p-%l] %r %q%u@%d '
    log_rotation_age: 1d
    log_rotation_size: 0
    log_truncate_on_rotation: true
    logging_collector: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
synchronous_node_count: 1
ttl: 30
```

### Patroni log files

```shell
Two attempts:
 - From 10:15:21 to 10:16:54 without PATRONI_LOG_LEVEL=DEBUG
 - From 10:17:27 to 10:17:52 with PATRONI_LOG_LEVEL=DEBUG

https://pastebin.com/1cneNQzK
```

### PostgreSQL log files

```shell
https://pastebin.com/16kPN6aW
```

### Have you tried to use GitHub issue search?

- [X] Yes
