### ISSUE TITLE
wal_keep_size in the cluster configuration has no effect

### ISSUE THREAD

**Issue by victor-sudakov** [zalando/patroni#2835]
### What happened?

I am changing the `wal_keep_size` parameter via `patronictl edit-config` and the new value shows in the `patronictl show-config` output. However the new value is not assigned to cluster members even after I run  `patronictl reload` of the members.

### How can we reproduce it (as minimally and precisely as possible)?

Please change the `wal_keep_size` parameter via `patronictl edit-config` and inspect the actual `postgresql.conf` on cluster members or run `show wal_keep_size;` on them . The value there will remain unchanged.

### What did you expect to happen?

I expected to new value of the `wal_keep_size parameter` to be propagated to cluster members.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.4-1.pgdg110+1
-   PostgreSQL version: 15.4
-   DCS (and its version): Consul 1.16.1

### Patroni configuration file

```yaml
---
# vim: syntax=yaml cursorcolumn: expandtab:
# Managed by Ansible. Please do not edit manually.
# See https://github.com/zalando/patroni/blob/master/docs/dynamic_configuration.rst for explanations
scope: "15-dblogs"
namespace: "dblogs"
name: "db-logs1"

log:
  dir: /var/log/postgresql/
  file_num: 10
  file_size: 1048576

consul:
  host: 127.0.0.1:8500
  register_service: true

restapi:
  listen: xx.xx.xx.75:8008
  connect_address: xx.xx.xx.75:8008
  authentication:
    username: dblogscluster
    password: XXXXXXXXXXXXX

bootstrap:
  # some desired options for 'initdb'
  initdb:
    - encoding: UTF-8
    - locale: C.UTF-8
    - data-checksums
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 104857600
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_node_count: 1
    postgresql:
      check_timeline: true
      use_pg_rewind: false
      remove_data_directory_on_rewind_failure: true
      remove_data_directory_on_diverged_timelines: true
      # The following parameters are given as command line options
      # overriding the settings in postgresql.conf.
      parameters: # Dynamic configuration from DCS, see the docs
        max_connections: 960
        max_locks_per_transaction: 256
        max_worker_processes: 16
        max_prepared_transactions: 960
        max_wal_senders: 10
        max_replication_slots: 10
        track_commit_timestamp: "on"
        wal_level: "logical"
        wal_log_hints: "on"
        shared_buffers: "2GB"
        effective_cache_size: "4GB"
        superuser_reserved_connections: 8
        lc_messages: "C"
        timezone: "GMT"
        timezone_abbreviations: "PMT"
        ssl: "off"
        log_min_duration_statement: 1000
        log_checkpoints: "on"
        log_connections: "on"
        log_disconnections: "on"
        log_autovacuum_min_duration: 0
        log_error_verbosity: "verbose"
        log_line_prefix: "<%u%%%d%%%h%%%i>"
        log_lock_waits: "on"
        log_statement: "all"
        log_timezone: "America/Phoenix"
        log_destination: "stderr"
        archive_command: "/usr/local/bin/wal-g wal-push %p >> /var/log/postgresql/archive_command.log 2>&1"
        archive_mode: "on"
        shared_preload_libraries: "pg_stat_statements"
        idle_in_transaction_session_timeout: "1min"
        authentication_timeout: "8s"
        pg_stat_statements.track: "all"
        jit: "off"
        hot_standby_feedback: on
        track_functions: "all"
      pg_hba:
        - local   all             all                                     trust
        - host    all             all             127.0.0.1/32            trust
        - host    all             all             ::1/128                 trust
        - host    replication   repmgr            xx.xx.xx.0/20          trust
        - host    all             all             xx.xx.xx.0/20          md5
postgresql:
  create_replica_method:
    - basebackup
  basebackup:
    checkpoint: 'fast'

  listen: "xx.xx.xx.75,127.0.0.1:5432"
  connect_address: xx.xx.xx.75:5432
  use_unix_socket: true
  data_dir: "/fastdrive/pg_data/15/dblogs"
  bin_dir: /usr/lib/postgresql/15/bin
  pgpass: /var/lib/postgresql/15-dblogs.pgpass
  authentication:
    replication:
      username: repman
      password: XXXXXXXXXXXXX
    superuser: # A superuser role is required in order for Patroni to manage the local Postgres instance
      username: postgres
      password: XXXXXXXXXXXXX
  parameters: # Local configuration from patroni.yml, see the docs
    logging_collector: "on"
    log_directory: "/var/log/postgresql"
    log_filename: "postgresql-15-dblogs.log"
    shared_buffers: "14GB"
    temp_buffers: "16MB"
    effective_cache_size: "24GB"
    work_mem: "40MB"
    maintenance_work_mem: "960MB"

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 104857600
postgresql:
  check_timeline: true
  parameters:
    archive_command: /usr/local/bin/wal-g wal-push %p >> /var/log/postgresql/archive_command.log 2>&1
    archive_mode: 'on'
    authentication_timeout: 8s
    client_min_messages: warning
    effective_cache_size: 4GB
    hot_standby_feedback: true
    idle_in_transaction_session_timeout: 1min
    jit: 'off'
    lc_messages: C
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_destination: stderr
    log_disconnections: 'on'
    log_duration: 'off'
    log_error_verbosity: default
    log_line_prefix: <%u%%%d%%%h%%%i>
    log_lock_waits: 'on'
    log_min_duration_statement: 1000
    log_statement: ddl
    log_timezone: America/Phoenix
    max_connections: 960
    max_locks_per_transaction: 256
    max_prepared_transactions: 960
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 16
    pg_stat_statements.track: all
    shared_buffers: 2GB
    shared_preload_libraries: pg_stat_statements
    ssl: 'off'
    superuser_reserved_connections: 8
    timezone: GMT
    timezone_abbreviations: PMT
    track_commit_timestamp: 'on'
    track_functions: all
    wal_keep_size: 2G
    wal_level: logical
    wal_log_hints: 'on'
  pg_hba:
  - local   all             all                                     trust
  - host    all             all             127.0.0.1/32            trust
  - host    all             all             ::1/128                 trust
  - host    replication   repmgr            ::1/128                 trust
  - host    replication   repmgr            127.0.0.1/32            trust
  - host    replication   repmgr            xx.xx.xx.0/20          trust
  - host    all             all             xx.xx.xx.0/20          md5
  remove_data_directory_on_diverged_timelines: true
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: false
retry_timeout: 10
synchronous_mode: false
synchronous_node_count: 1
ttl: 30
```

### Patroni log files

```shell
2023-08-27 22:22:02,289 INFO: No PostgreSQL configuration items changed, nothing to reload.

after issuing `patronictl edit-config`
```

### PostgreSQL log files

```shell
There are no relevant events.
```

### Have you tried to use GitHub issue search?

- [X] Yes
