### ISSUE TITLE
PostgreSQL `listen` and `max_connections` Parameter is not working

### ISSUE THREAD

**Issue by mhkarimi1383** [zalando/patroni#2836]
### What happened?

Hi, I want to change postreSQL listen and max_connections configuration, But after changing that nothing changes in potgresql.conf

also some other paramerters in postgresql is not getting applied, and that's also strange

for example `max_prepared_transactions: 262143` is not applied and I'm getting

```
WARNING:patroni.postgresql.validator:Value=500500 of parameter=max_prepared_transactions is too big, decreasing to 262143
2023-08-29 19:33:15,715 WARNING: Value=500500 of parameter=max_prepared_transactions is too big, decreasing to 262143
INFO:patroni.postgresql.postmaster:postmaster pid=178
2023-08-29 19:33:17,203 INFO: postmaster pid=178
2023-08-29 19:33:17.205 GMT [178] FATAL:  500500 is outside the valid range for parameter "max_prepared_transactions" (0 .. 262143)
```

NOTE: I'm using Citus in this setup for the first time, and my normal postgreSQL clusters are Ok

### How can we reproduce it (as minimally and precisely as possible)?

here is my docker-compose

```yaml
version: "2.4"
services:
  "my-db":
    image: patroni-citus
    build:
      context: "/compose/patroni-src"
      dockerfile: "/compose/patroni-src/Dockerfile.citus"
    restart: always
    container_name: "my-db"
    network_mode: "host"
    shm_size: 4G
    environment:
      PATRONI_NAME: "my-db-coord-0"
      PATRONI_CITUS_GROUP: "0"
      PATRONI_SCOPE: "my-db"
      SCOPE: "my-db"
      PATRONI_CITUS_DATABASE: "my-db"
      PATRONI_ETCD_HOSTS: x.x.x.x:{{ etcd_listen_port }},x.x.x.x:{{ etcd_listen_port }},x.x.x.x:{{ etcd_listen_port }}
      PATRONI_SUPERUSER_USERNAME: "postgres"
      PATRONI_SUPERUSER_PASSWORD: "postgres"
      PATRONI_REPLICATION_USERNAME: replicator
      PATRONI_REPLICATION_PASSWORD: "supersecret"
      PATRONI_admin_PASSWORD: "supersecret"
      PATRONI_admin_OPTIONS: "createdb,createrole"
      ALLOW_NOSSL: "True"
      PGSSLMODE: "verify-ca"
      PGSSLKEY: /etc/ssl/private/ssl-cert-snakeoil.key
      PGSSLCERT: /etc/ssl/certs/ssl-cert-snakeoil.pem
      PGSSLROOTCERT: /etc/ssl/certs/ssl-cert-snakeoil.pem
      PATRONI_POSTGRESQL_LISTEN: "192.168.1.2:5532"
      PGPORT: "5532"
      PGVERSION: 15
```

### What did you expect to happen?

Getting currect version while checking out configs and `netstat -tupln`

### Patroni/PostgreSQL/DCS version

-   Patroni version: v3.1.0 (cloned from github)
-   PostgreSQL version: 15
-   DCS (and its version): 

### Patroni configuration file

```yaml
bootstrap:
  dcs:
    postgresql:
      listen: '127.0.0.1,0.0.0.0,192.168.1.2:5532'
      parameters:
        port: '5532
        max_connections: '500'
postgresql:
  use_pg_rewind: true
  listen: '127.0.0.1,0.0.0.0,192.168.1.2:5532'
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host all all 127.0.0.1/32 trust
    - host replication replicator 0.0.0.0/0 md5
    - local all all trust
    - hostssl replication replicator all md5 clientcert=verify-ca
    - hostssl all all all md5 clientcert=verify-ca
  parameters:
    ssl: on
    max_connections: '500'
    port: '5532'
    ssl_ca_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
    ssl_cert_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
    ssl_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
```

### patronictl show-config

```yaml
Output is empty
```

### Patroni log files

```shell
Nothing
```

### PostgreSQL log files

```shell
Nothing
```

### Have you tried to use GitHub issue search?

- [X] Yes
