### ISSUE TITLE
Eventhough the Postgres nodes are running and active , the patroni list shows that nodes are stopped.

### ISSUE THREAD

**Issue by hem040490** [zalando/patroni#2860]
### What happened?

Eventhough the Postgres nodes are running and active , the patroni list shows that nodes are stopped. Once node 2 is active and rest nodes are stopped , although the pg are up and running in other nodes.

### How can we reproduce it (as minimally and precisely as possible)?

We are using the centos for nodes and haproxy .
Node1 master Postgres node
Node 2 replica pg node of node1
Node3 haproxy and patroni

### What did you expect to happen?

All nodes need to be active if the Pg is up and running in all nodes .

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 15.2
-   DCS (and its version): 

### Patroni configuration file

```yaml
namespace: percona_lab
scope: cluster_1
name: node1

restapi:
    listen: 0.0.0.0:8008
    connect_address: 10.104.0.1:8008

etcd:
    host: 10.104.0.1:2379  # ETCD node IP address

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  dcs:
     ttl: 30
     loop_wait: 10
     retry_timeout: 10
     maximum_lag_on_failover: 1048576
     slots:
         percona_cluster_1:
         type: physical
     postgresql:
         use_pg_rewind: true
         use_slots: true
         parameters:
             wal_level: replica
             hot_standby: "on"
             wal_keep_segments: 10
             max_wal_senders: 5
             max_replication_slots: 10
             wal_log_hints: "on"
             logging_collector: 'on'
 # some desired options for 'initdb'
 initdb: # Note: It needs to be a list (some options need values, others are switches)
     - encoding: UTF8
     - data-checksums
 pg_hba: # Add following lines to pg_hba.conf after running 'initdb'
     - host replication replicator 127.0.0.1/32 trust
     - host replication replicator 0.0.0.0/0 md5
     - host all all 0.0.0.0/0 md5
     - host all all ::0/0 md5
 # Some additional users which needs to be created after initializing new cluster
 users:
     admin:
         password: qaz123
         options:
             - createrole
             - createdb
     percona:
         password: qaz123
         options:
             - createrole
             - createdb

postgresql:
  cluster_name: cluster_1
  listen: 0.0.0.0:5432
  connect_address: 10.104.0.1:5432
  data_dir: /data/pgsql
  bin_dir: /usr/pgsql-11/bin
  pgpass: /tmp/pgpass
  authentication:
      replication:
          username: replicator
          password: replPasswd
      superuser:
          username: postgres
          password: qaz123
  parameters:
      unix_socket_directories: "/var/run/postgresql/"
  create_replica_methods:
      - basebackup
  basebackup:
      checkpoint: 'fast'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
namespace: percona_lab
scope: cluster_1
name: node1

restapi:
    listen: 0.0.0.0:8008
    connect_address: 10.104.0.1:8008

etcd:
    host: 10.104.0.1:2379  # ETCD node IP address

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  dcs:
     ttl: 30
     loop_wait: 10
     retry_timeout: 10
     maximum_lag_on_failover: 1048576
     slots:
         percona_cluster_1:
         type: physical
     postgresql:
         use_pg_rewind: true
         use_slots: true
         parameters:
             wal_level: replica
             hot_standby: "on"
             wal_keep_segments: 10
             max_wal_senders: 5
             max_replication_slots: 10
             wal_log_hints: "on"
             logging_collector: 'on'
 # some desired options for 'initdb'
 initdb: # Note: It needs to be a list (some options need values, others are switches)
     - encoding: UTF8
     - data-checksums
 pg_hba: # Add following lines to pg_hba.conf after running 'initdb'
     - host replication replicator 127.0.0.1/32 trust
     - host replication replicator 0.0.0.0/0 md5
     - host all all 0.0.0.0/0 md5
     - host all all ::0/0 md5
 # Some additional users which needs to be created after initializing new cluster
 users:
     admin:
         password: qaz123
         options:
             - createrole
             - createdb
     percona:
         password: qaz123
         options:
             - createrole
             - createdb

postgresql:
  cluster_name: cluster_1
  listen: 0.0.0.0:5432
  connect_address: 10.104.0.1:5432
  data_dir: /data/pgsql
  bin_dir: /usr/pgsql-11/bin
  pgpass: /tmp/pgpass
  authentication:
      replication:
          username: replicator
          password: replPasswd
      superuser:
          username: postgres
          password: qaz123
  parameters:
      unix_socket_directories: "/var/run/postgresql/"
  create_replica_methods:
      - basebackup
  basebackup:
      checkpoint: 'fast'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### Patroni log files

```shell
namespace: percona_lab
scope: cluster_1
name: node1

restapi:
    listen: 0.0.0.0:8008
    connect_address: 10.104.0.1:8008

etcd:
    host: 10.104.0.1:2379  # ETCD node IP address

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  dcs:
     ttl: 30
     loop_wait: 10
     retry_timeout: 10
     maximum_lag_on_failover: 1048576
     slots:
         percona_cluster_1:
         type: physical
     postgresql:
         use_pg_rewind: true
         use_slots: true
         parameters:
             wal_level: replica
             hot_standby: "on"
             wal_keep_segments: 10
             max_wal_senders: 5
             max_replication_slots: 10
             wal_log_hints: "on"
             logging_collector: 'on'
 # some desired options for 'initdb'
 initdb: # Note: It needs to be a list (some options need values, others are switches)
     - encoding: UTF8
     - data-checksums
 pg_hba: # Add following lines to pg_hba.conf after running 'initdb'
     - host replication replicator 127.0.0.1/32 trust
     - host replication replicator 0.0.0.0/0 md5
     - host all all 0.0.0.0/0 md5
     - host all all ::0/0 md5
 # Some additional users which needs to be created after initializing new cluster
 users:
     admin:
         password: qaz123
         options:
             - createrole
             - createdb
     percona:
         password: qaz123
         options:
             - createrole
             - createdb

postgresql:
  cluster_name: cluster_1
  listen: 0.0.0.0:5432
  connect_address: 10.104.0.1:5432
  data_dir: /data/pgsql
  bin_dir: /usr/pgsql-11/bin
  pgpass: /tmp/pgpass
  authentication:
      replication:
          username: replicator
          password: replPasswd
      superuser:
          username: postgres
          password: qaz123
  parameters:
      unix_socket_directories: "/var/run/postgresql/"
  create_replica_methods:
      - basebackup
  basebackup:
      checkpoint: 'fast'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### PostgreSQL log files

```shell
namespace: percona_lab
scope: cluster_1
name: node1

restapi:
    listen: 0.0.0.0:8008
    connect_address: 10.104.0.1:8008

etcd:
    host: 10.104.0.1:2379  # ETCD node IP address

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  dcs:
     ttl: 30
     loop_wait: 10
     retry_timeout: 10
     maximum_lag_on_failover: 1048576
     slots:
         percona_cluster_1:
         type: physical
     postgresql:
         use_pg_rewind: true
         use_slots: true
         parameters:
             wal_level: replica
             hot_standby: "on"
             wal_keep_segments: 10
             max_wal_senders: 5
             max_replication_slots: 10
             wal_log_hints: "on"
             logging_collector: 'on'
 # some desired options for 'initdb'
 initdb: # Note: It needs to be a list (some options need values, others are switches)
     - encoding: UTF8
     - data-checksums
 pg_hba: # Add following lines to pg_hba.conf after running 'initdb'
     - host replication replicator 127.0.0.1/32 trust
     - host replication replicator 0.0.0.0/0 md5
     - host all all 0.0.0.0/0 md5
     - host all all ::0/0 md5
 # Some additional users which needs to be created after initializing new cluster
 users:
     admin:
         password: qaz123
         options:
             - createrole
             - createdb
     percona:
         password: qaz123
         options:
             - createrole
             - createdb

postgresql:
  cluster_name: cluster_1
  listen: 0.0.0.0:5432
  connect_address: 10.104.0.1:5432
  data_dir: /data/pgsql
  bin_dir: /usr/pgsql-11/bin
  pgpass: /tmp/pgpass
  authentication:
      replication:
          username: replicator
          password: replPasswd
      superuser:
          username: postgres
          password: qaz123
  parameters:
      unix_socket_directories: "/var/run/postgresql/"
  create_replica_methods:
      - basebackup
  basebackup:
      checkpoint: 'fast'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### Have you tried to use GitHub issue search?

- [X] Yes
