### ISSUE TITLE
Include wal and tablespace directories in 

### ISSUE THREAD

**Issue by udesaiitrs** [zalando/patroni#2864]
### What happened?

Digging through the code, it seems that there is an improvement that can be made to the default basebackup implementation. Currently, there is a check to see if ONLY the data_dir is empty, and if not then `remove_data_directory()` is called. This call however, removes the data dir, wal dir, and all user defined tablespaces as well. This results in the `reinit` call to correctly remove wal and tablespace directories, but there can be instances where the basebackup call fails during a `reinit`, and certain files are leftover in the wal or tablespace dir. When the basebackup calls runs again, it will error out since those directories are not empty.

### How can we reproduce it (as minimally and precisely as possible)?

Create an HA Postgres cluster w/Patroni and 1 or more tablespaces. Running a reinit command results in this type of behavior on the target PG instance:

```
2023-09-14 18:56:31,698 INFO: Removing data directory: /var/lib/postgresql/data
2023-09-14 18:56:31,698 INFO: Removing WAL directory: /var/lib/postgresql/wal/pg_wal
2023-09-14 18:56:31,798 INFO: Removing user defined tablespace directory: /var/lib/postgresql/tablespaces/timeseries_tablespace_2/data
2023-09-14 18:56:31,799 INFO: Removing user defined tablespace directory: /var/lib/postgresql/tablespaces/timeseries_tablespace_1/data
2023-09-14 18:56:31,799 INFO: Removing user defined tablespace directory: /var/lib/postgresql/tablespaces/timeseries_tablespace_3/data
pg_basebackup: initiating base backup, waiting for checkpoint to complete
pg_basebackup: checkpoint completed
pg_basebackup: write-ahead log start point: 0/B000028 on timeline 2
pg_basebackup: starting background WAL receiver
pg_basebackup: created temporary replication slot "pg_basebackup_152"
   11/48256 kB (0%), 0/4 tablespaces (...data/PG_14_202107181/16388/17553)
   98/48256 kB (0%), 0/4 tablespaces (...data/PG_14_202107181/16388/17690)
  143/48256 kB (0%), 1/4 tablespaces (...data/PG_14_202107181/16388/17717)
  144/48256 kB (0%), 2/4 tablespaces (...ablespace_3/data/PG_14_202107181)
48267/48267 kB (100%), 3/4 tablespaces (...ostgresql/data/global/pg_control)
48267/48267 kB (100%), 4/4 tablespaces                                         
pg_basebackup: write-ahead log end point: 0/B000138
pg_basebackup: waiting for background process to finish streaming ...
pg_basebackup: syncing data to disk ...
pg_basebackup: renaming backup_manifest.tmp to backup_manifest
pg_basebackup: base backup completed
2023-09-14 18:56:33,175 INFO: replica has been created using basebackup
```

### What did you expect to happen?

Looking through the code, it seems like it should be possible to include checks to see if the wal and tablespace directories are empty:

Links:

- where ONLY data dir is checked for emptiness, and COULD include other directories: https://github.com/zalando/patroni/blob/75dbe4ff96a7443fde4fe3d2ddc7492ec2710530/patroni/postgresql/bootstrap.py#L302

- where WAL dir is removed: https://github.com/zalando/patroni/blob/75dbe4ff96a7443fde4fe3d2ddc7492ec2710530/patroni/postgresql/__init__.py#L1299

- where tablespace dirs are removed: https://github.com/zalando/patroni/blob/75dbe4ff96a7443fde4fe3d2ddc7492ec2710530/patroni/postgresql/__init__.py#L1304

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.1.0
-   PostgreSQL version: 14.9
-   DCS (and its version): 

### Patroni configuration file

```yaml
bootstrap:
  dcs:
    loop_wait: 10
    ttl: 30
    retry_timeout: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      use_pg_rewind: true
      remove_data_directory_on_rewind_failure: true
      parameters:
        archive_command: /etc/timescaledb/scripts/pgbackrest_archive.sh %p
        archive_mode: "on"
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 20
        autovacuum_naptime: 120s
        autovacuum_vacuum_cost_limit: 2500
        autovacuum_vacuum_scale_factor: 0.2
        dynamic_shared_memory_type: "sysv"
        hot_standby: "on"
        log_autovacuum_min_duration: 1000
        log_checkpoints: "on"
        log_connections: "off"
        log_disconnections: "off"
        log_line_prefix: '%m: %u@%d,app=%a '
        log_lock_waits: "on"
        log_min_duration_statement: 3s
        log_replication_commands: "on"
        log_statement: none
        max_connections: 100
        max_parallel_workers: 20
        max_prepared_transactions: 150
        max_worker_processes: 40
        max_standby_archive_delay: 120s
        max_standby_streaming_delay: 120s
        pg_stat_statements.max: 1000
        pljava.java_thread_pg_entry: 'throw'
        pljava.libjvm_location: '/usr/lib/jvm/custom-runtime/lib/server/libjvm.so'
        pljava.vmoptions: '--add-modules=jdk.unsupported'
        pljava.policy_urls: '"file:${org.postgresql.sysconfdir}/pljava.policy","file:/usr/lib/jvm/custom-runtime/custom-pljava-ext.policy","="'
        shared_preload_libraries: timescaledb,pg_stat_statements
        synchronous_commit: local
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        temp_file_limit: 20GB
        timescaledb.max_background_workers: 20
        timescaledb.passfile: ../.pgpass
        timescaledb.telemetry_level: 'off'
        unix_socket_directories: /var/run/postgresql
        unix_socket_permissions: "0750"
        wal_level: "replica"
        wal_log_hints: "on"
        wal_compression: "true"
  method: restore_or_initdb
  restore_or_initdb:
    command: |
      /etc/timescaledb/scripts/restore_or_initdb.sh --encoding=UTF8 --locale=C.UTF-8
    keep_existing_recovery_conf: true
kubernetes:
  role_label: role
  scope_label: cluster
  use_endpoints: true
log:
  level: INFO
postgresql:
  authentication:
    replication:
      username: standby
    superuser:
      username: postgres
  basebackup:
  - waldir: /var/lib/postgresql/wal/pg_wal
  - checkpoint: fast
  - progress
  - verbose
  callbacks:
    on_reload: /etc/timescaledb/scripts/patroni_callback.sh
    on_restart: /etc/timescaledb/scripts/patroni_callback.sh
    on_role_change: /etc/timescaledb/scripts/patroni_callback.sh
    on_start: /etc/timescaledb/scripts/patroni_callback.sh
    on_stop: /etc/timescaledb/scripts/patroni_callback.sh
  create_replica_methods:
  - basebackup
  listen: 0.0.0.0:5432
  pg_hba:
  - local     all             postgres                              peer
  - local     all             all                                   md5
  - host      all             all                127.0.0.1/32       md5
  - host      all             all                ::1/128            md5
  - host      replication     standby            all                md5
  - host      all             all                all                md5
  use_unix_socket: true
restapi:
  listen: 0.0.0.0:8008
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 33554432
postgresql:
  parameters:
    archive_command: /etc/timescaledb/scripts/pgbackrest_archive.sh %p
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 20
    autovacuum_naptime: 120s
    autovacuum_vacuum_cost_limit: 2500
    autovacuum_vacuum_scale_factor: 0.2
    checkpoint_timeout: 1800
    dynamic_shared_memory_type: sysv
    hot_standby: 'on'
    log_autovacuum_min_duration: 1000
    log_checkpoints: 'on'
    log_connections: 'off'
    log_disconnections: 'off'
    log_line_prefix: '%m: %u@%d,app=%a '
    log_lock_waits: 'on'
    log_min_duration_statement: 3s
    log_replication_commands: 'on'
    log_statement: none
    max_connections: 100
    max_parallel_workers: 20
    max_prepared_transactions: 150
    max_standby_archive_delay: 120s
    max_standby_streaming_delay: 120s
    max_worker_processes: 40
    pg_stat_statements.max: 1000
    pljava.java_thread_pg_entry: throw
    pljava.libjvm_location: /usr/lib/jvm/custom-runtime/lib/server/libjvm.so
    pljava.policy_urls: '"file:${org.postgresql.sysconfdir}/pljava.policy","file:/usr/lib/jvm/custom-runtime/custom-pljava-ext.policy","="'
    pljava.vmoptions: --add-modules=jdk.unsupported -Xshare:auto -Xms8m -Xmx8m -Xss196k -XX:MaxMetaspaceSize=16m -XX:ReservedCodeCacheSize=4m -XX:+UseSerialGC
    shared_preload_libraries: timescaledb,pg_stat_statements
    synchronous_commit: local
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    temp_file_limit: 20GB
    timescaledb.max_background_workers: 20
    timescaledb.passfile: ../.pgpass
    timescaledb.telemetry_level: 'off'
    unix_socket_directories: /var/run/postgresql
    unix_socket_permissions: '0750'
    wal_compression: 'true'
    wal_level: replica
    wal_log_hints: 'on'
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
-
```

### PostgreSQL log files

```shell
-
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

I don't mind trying to open a PR for review, please let me know!
