### ISSUE TITLE
failover not paying attention ttl  

### ISSUE THREAD

**Issue by kos12345** [zalando/patroni#2868]
### What happened?

when i have network problem between master and replicas - the failover takes place immediately, not paying attention to the settings
ttl:60
loop_wait: 40
retry_timeout: 10

**my actions and log patroni**
2023-09-16 **12:06:45,365** INFO: no action. I am (pgsql3), a secondary, and following a leader (pgsql1)

at this time i disconnected master pgsql1 and then replica pgsql3 promoted to leader.

2023-09-16 12:06:58,910 WARNING: Request failed to pgsql1: GET http://10.50.96.11:8008/patroni (HTTPConnectionPool(host='10.50.96.11', port=8008): Max retries exceeded with url: /patroni (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa510766320>, 'Connection to 10.50.96.11 timed out. (connect timeout=2)')))
2023-09-16 **12:06:59,027** INFO: promoted self to leader by acquiring session lock
2023-09-16 12:07:00,077 INFO: no action. I am (pgsql3), the leader with the lock
2023-09-16 12:07:00,160 INFO: no action. I am (pgsql3), the leader with the lock

why replica not waiting loop_wait + retry_timeout x 2  ?? 
she must be a leader after one minutes only

what is my mistake?

### How can we reproduce it (as minimally and precisely as possible)?

disconnect master from network. look how quickly replica become leader.  

### What did you expect to happen?

60 seconds pause before replica will be promoted to master

### Patroni/PostgreSQL/DCS version

-   Patroni version:  3.1.0
-   PostgreSQL version:  doesn't matter. 10-15
-   DCS (and its version):  doesn't matter. consul, etcd

### Patroni configuration file

```yaml
doesn't matter. all settings default. 
ttl:60
loop_wait: 40
retry_timeout: 10
watchdog:
 mode:off
```

### patronictl show-config

```yaml
failsafe_mode: false
loop_wait: 40
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: pg_probackup-10 archive-push -B /home/backup_user/probackup --instance=server1 --wal-file-path=%p --wal-file-name=%f --remote-host=10.50.96.16 --remote-user=backup_user --overwrite
      --compress
    archive_mode: 'on'
    archive_timeout: 1800s
    checkpoint_completion_target: 0.9
    default_statistics_target: 100
    effective_cache_size: 1GB
    effective_io_concurrency: 250
    hot_standby: 'on'
    log_connections: false
    log_destination: csvlog
    log_directory: /var/log/postgresql
    log_min_duration_statement: '60000'
    log_min_error_statement: INFO
    log_statement: ddl
    maintenance_work_mem: 256MB
    max_connections: 100
    max_locks_per_transaction: 64
    max_parallel_workers_per_gather: 2
    max_replication_slots: 15
    max_wal_senders: 15
    max_wal_size: 2GB
    max_worker_processes: 8
    min_wal_size: 1GB
    pg_stat_statements.max: 1000
    pg_stat_statements.track: all
    random_page_cost: 1.1
    shared_buffers: 512MB
    shared_preload_libraries: pg_stat_statements,pg_stat_kcache,pg_qualstats,pg_wait_sampling,powa
    synchronous_commit: remote_write
    synchronous_standby_names: '*'
    track_commit_timestamp: 'off'
    track_io_timing: 'on'
    wal_buffers: 16MB
    wal_keep_segments: 5
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 4MB
  pg_hba:
  - local all monitoring peer map=zabbix
  - host replication backup 10.50.96.16/32 trust
  - host all backup 10.50.96.16/32 trust
  - local   all             all                                     trust
  - host    all             all             127.0.0.1/32            trust
  - host    all             all             ::1/128                 trust
- local   replication     all                                     trust
  - host    replication     all             127.0.0.1/32            trust
  - host    replication     all             ::1/128                 trust
  - host all all 0.0.0.0/0 md5
  - host replication replicator 0.0.0.0/0 md5
  pg_ident:
  - zabbix zabbix monitoring
  recovery_conf:
    restore_command: pg_probackup-10 archive-get -B /home/backup_user/probackup --instance=server1 --remote-host=10.50.96.16 --wal-file-path=%p --wal-file-name=%f --remote-user=backup_user
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
ttl: 60
```

### Patroni log files

```shell
2023-09-16 **12:06:45,365** INFO: no action. I am (pgsql3), a secondary, and following a leader (pgsql1)
2023-09-16 12:06:58,910 WARNING: Request failed to pgsql1: GET http://10.50.96.11:8008/patroni (HTTPConnectionPool(host='10.50.96.11', port=8008): Max retries exceeded with url: /patroni (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa510766320>, 'Connection to 10.50.96.11 timed out. (connect timeout=2)')))
2023-09-16 **12:06:59,027** INFO: promoted self to leader by acquiring session lock
2023-09-16 12:07:00,077 INFO: no action. I am (pgsql3), the leader with the lock
2023-09-16 12:07:00,160 INFO: no action. I am (pgsql3), the leader with the lock
```

### PostgreSQL log files

```shell
2023-09-16 12:06:59.030 MSK,,,968,,65056e91.3c8,13,,LOG,00000,"received promote request",,,,,,,,,""
```

### Have you tried to use GitHub issue search?

- [X] Yes
