### ISSUE TITLE
Patroni doesnt make replication and error on status patroni 

### ISSUE THREAD

**Issue by gulyaissina** [zalando/patroni#2906]
### What happened?

I'm installing a cluster on an Ubuntu 22.04 virtual machine. Consists of 2 servers (Postgresql 14, patroni 3) and 1 server with etcd.
The installation completed without errors. The databases have been initialized (leader and replica)
But when changes occur on the master, the replica does not move to another database.
Ports 5432 and users postrges and replicator are open and accessible (from my external computer using the pgadmin )
Etcd worked without errors and the patron receives the keys (log file)

root@node2:~# patronictl -c /etc/patroni.yml list
+ Cluster: pg_ha_cluster (7288179137836923881) ----+-----------+
| Member | Host           | Role    | State   | TL | Lag in MB |
+--------+----------------+---------+---------+----+-----------+
| node1  | 192.168.56.103 | Leader  | running | 13 |           |
| node2  | 192.168.56.104 | Replica | running |    |         0 |
+--------+----------------+---------+---------+----+-----------+

Error message on patroni status (patroni.yml got from ur githup and wrote my IP adreses, check all space and indent)

FATAL:  could not connect to the primary server: connection to server at "192.168.56.103", port 5432 failed: FATAL could not connect to the primary server: connection to server at "192.168.56.103", port 5432 failed: FATAL:
no pg_hba.conf entry for replication connection from host "192.168.56.104", user "replicato>

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/zalando/patroni/assets/115543094/b49897de-8d8c-4732-aa24-450c7a7253b2)
root@node2:~# systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
     Loaded: loaded (/etc/systemd/system/patroni.service; enabled; vendor preset: enabled)
     **Active: active (running)** since Wed 2023-10-11 00:05:48 +06; 3h 40min ago
   Main PID: 9115 (patroni)
      Tasks: 15 (limit: 2201)
     Memory: 52.7M
        CPU: 8min 354ms
     CGroup: /system.slice/patroni.service
             ├─ 9115 /usr/bin/python3 /usr/local/bin/patroni /etc/patroni.yml
             ├─ 9152 postgres -D /var/lib/postgresql/14/main --config-file=/var/lib/postgresql/14/main/postgresql.conf --listen_addresses=192.168.56.104 --port=5432 --cluster_name=pg_ha_cl>
             ├─ 9154 "postgres: pg_ha_cluster: startup recovering 000000010000000000000001" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" >
             ├─ 9155 "postgres: pg_ha_cluster: checkpointer " "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" >
             ├─ 9156 "postgres: pg_ha_cluster: background writer " "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ">
             ├─ 9157 "postgres: pg_ha_cluster: stats collector " "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" >
             ├─ 9164 "postgres: pg_ha_cluster: postgres postgres 192.168.56.104(55240) idle" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "">
             ├─ 9343 "postgres: pg_ha_cluster: postgres postgres 192.168.56.1(62779) idle" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ">
             ├─ 9655 "postgres: pg_ha_cluster: postgres postgres 192.168.56.1(64402) idle" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ">
             ├─ 9657 "postgres: pg_ha_cluster: postgres postgres 192.168.56.1(64426) idle" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ">
             └─15134

### What did you expect to happen?

replication and when leader power of switchover

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3 
-   PostgreSQL version: 14
-   DCS (and its version): 

### Patroni configuration file

```yaml
scope: pg_ha_cluster
name: node1

restapi:
  listen: 192.168.56.103:8008
  connect_address: 192.168.56.103:8008
# dir: /var/log/postgresql
#  cafile: /etc/ssl/certs/ssl-cacert-snakeoil.pem
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
  authentication:
    username: postgres
    password: postgres
etcd:
  host: 192.168.56.102:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 0
    postgresql:
      use_pg_rewind: true
  # pg_hba:
 #     - host replication replicator 127.0.0.1/32 md5
  #    - host replication replicator 192.168.56.103/0 md5
   #   - host replication postgres 192.168.56.104/0 md5
   #   - host all all 0.0.0.0/0 md5
      #  - hostssl all all 0.0.0.0/0 md5
#      use_slots: true
    parameters:
    unix_socket_directories: '..'  # parent directory of data_dir
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
#    replicatefrom: postgresql1

_________________________________
scope: pg_ha_cluster
name: node2

restapi:
  listen: 192.168.56.104:8008
  connect_address: 192.168.56.104:8008
# dir: /var/log/postgresql
#  cafile: /etc/ssl/certs/ssl-cacert-snakeoil.pem
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
  authentication:
    username: postgres
    password: postgres
etcd:
  host: 192.168.56.102:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 0
    postgresql:
      use_pg_rewind: true
  # pg_hba:
 #     - host replication replicator 127.0.0.1/32 md5
  #    - host replication replicator 192.168.56.103/0 md5
   #   - host replication postgres 192.168.56.104/0 md5
   #   - host all all 0.0.0.0/0 md5
      #  - hostssl all all 0.0.0.0/0 md5
#      use_slots: true
    parameters:
        password_encryption: 'scram-sha-256'   # tried with md5 at first but the same error
#        wal_level: hot_standby
#        hot_standby: "on"
#        max_connections: 100
#        max_worker_processes: 8
#        wal_keep_segments: 8
#        max_wal_senders: 10
#        max_replication_slots: 10
#        max_prepared_transactions: 0
#        max_locks_per_transaction: 64
#        wal_log_hints: "on"
#        track_commit_timestamp: "off"
#        archive_mode: "on"
#        archive_timeout: 1800s
#        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
#      recovery_conf:
#        restore_command: cp ../wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:
   - encoding: UTF8
   - data-checksums
  pg_hba:
   - host replication replicator 127.0.0.1/32 scram-sha-256  #at first try with md5 but the same problem
   - host replication replicator 192.168.56.103/0 scram-sha-256
   - host replication replicator 192.168.56.104/0 scram-sha-256
   - host all all 0.0.0.0/0 scram-sha-256
      #  - hostssl all all 0.0.0.0/0 md5

  # Some additional users which needs to be created after initializing new cluster
  users:
     postgres:
       password: postgres
       options:
        - createrole
        - createdb

postgresql:
  listen: 192.168.56.104:5432
  connect_address: 192.168.56.104:5432
  data_dir: /var/lib/postgresql/14/main
  parameters:
    # Fully qualified kerberos ticket file for the running user
    # same as KRB5CCNAME used by the GSS
#    krb_server_keyfile: /var/spool/keytabs/postgres
    unix_socket_directories: '..'  # parent directory of data_dir
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
#    replicatefrom: postgresql1
```

### patronictl show-config

```yaml
patronictl show-config
Error: Can not find suitable configuration of distributed configuration store
Available implementations: etcd, etcd3, kubernetes
root@node2:~#
```

### Patroni log files

```shell
root@node2:~# tail /var/log/postgresql/patroni.log
2023-10-10 10:17:04,547 DEBUG: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=0, status=None)
2023-10-10 10:17:04,550 DEBUG: http://192.168.56.102:2379 "GET /v2/keys/service/pg-ha-cluster/?recursive=true&quorum=false HTTP/1.1" 200 653
2023-10-10 10:17:04,552 DEBUG: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=0, status=None)
2023-10-10 10:17:04,556 DEBUG: http://192.168.56.102:2379 "PUT /v2/keys/service/pg-ha-cluster/members/node2 HTTP/1.1" 200 703
2023-10-10 10:17:13,313 DEBUG: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=0, status=None)
2023-10-10 10:17:13,318 DEBUG: http://192.168.56.102:2379 "PUT /v2/keys/service/pg-ha-cluster/members/node2 HTTP/1.1" 200 729
2023-10-10 10:17:13,318 DEBUG: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=0, status=None)
2023-10-10 10:17:13,321 DEBUG: http://192.168.56.102:2379 "GET /v2/keys/service/pg-ha-cluster/?recursive=true&quorum=false HTTP/1.1" 200 679
2023-10-10 10:17:13,322 DEBUG: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=0, status=None)
2023-10-10 10:17:13,326 DEBUG: http://192.168.56.102:2379 "PUT /v2/keys/service/pg-ha-cluster/members/node2 HTTP/1.1" 200 729
root@node2:~#
```

### PostgreSQL log files

```shell
nothing, old messages
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

i try with different yml files and pg_hba configuration, but it hasnt solve my problem
