### ISSUE TITLE
Node Eviction on High CPU Utilization

### ISSUE THREAD

**Issue by moindba** [zalando/patroni#2910]
### What happened?

When ever there is High CPU Utilization Replica Node Eviction Happen.

When we have check systemctl status patroni.services its active and but in patronictl list node is not showing

Steps we have taken to resolved.
1. systemctl stop patroni.services 
2. systemctl start patroni.services  -- it started but still node is not showing in the patronictl list
3. we have decided to reboot the VM -- after restarting the VM evicted node started syncing with the cluster.

### How can we reproduce it (as minimally and precisely as possible)?

High CPU Utlization

### What did you expect to happen?

its happening twice till now

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.0.2
-   PostgreSQL version: 12.8
-   DCS (and its version): 3.3.5

### Patroni configuration file

```yaml
---

scope: postgres-cluster
name: pg1-xx-xx-xx
namespace: /service/

log:
  level: DEBUG
  traceback_level: ERROR
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000
  dir: /var/log/patroni
  file_num: 4
  file_size: 25000000
  loggers:
    patroni.postmaster: WARNING
    urllib3: WARNING

restapi:
  listen: xx.xx.xx.xx:8008
  connect_address: xx.xx.xx.xx:8008
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

etcd:
  hosts: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

bootstrap:
  method: pgbackrest
  pgbackrest:
    command: "pgbackrest --stanza=prod --log-level-console=info --delta restore"
    keep_existing_recovery_conf: True
    no_params: True
    recovery_conf:
      recovery_target_timeline: latest
      recovery_target_action: promote
      restore_command: "pgbackrest --stanza=prod archive-get %f %p"
  method: initdb
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_node_count: 2
    # standby_cluster:
      # host: 127.0.0.1
      # port: 1111
      # primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 250
        superuser_reserved_connections: 10
        max_locks_per_transaction: 256
        max_prepared_transactions: 0
        huge_pages: try
        shared_buffers: 2GB
        work_mem: 16MB
        maintenance_work_mem: 256MB
        effective_cache_size: 4GB
        checkpoint_timeout: 15min
        checkpoint_completion_target: 0.9
        min_wal_size: 1GB
        max_wal_size: 2GB
        wal_buffers: 16MB
        default_statistics_target: 1000
        seq_page_cost: 1
        random_page_cost: 1.1
        effective_io_concurrency: 200
        synchronous_commit: on
        autovacuum: on
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_vacuum_cost_limit: 200
        autovacuum_vacuum_cost_delay: 20
        autovacuum_naptime: 1s
        max_files_per_process: 4096
        archive_mode: on
        archive_timeout: 1800s
        archive_command: cd .
        wal_level: replica
        wal_keep_segments: 200
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: on
        wal_log_hints: on
        shared_preload_libraries: pg_stat_statements,auto_explain
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        pg_stat_statements.save: off
        auto_explain.log_min_duration: 10s
        auto_explain.log_analyze: true
        auto_explain.log_buffers: true
        auto_explain.log_timing: false
        auto_explain.log_triggers: true
        auto_explain.log_verbose: true
        auto_explain.log_nested_statements: true
        track_io_timing: on
        log_lock_waits: on
        log_temp_files: 0
        track_activities: on
        track_counts: on
        track_functions: all
        log_checkpoints: on
        logging_collector: on
        log_truncate_on_rotation: on
        log_rotation_age: 1d
        log_rotation_size: 0
        log_line_prefix: '%t [%p-%l] %r %q%u@%d '
        log_filename: 'postgresql-%a.log'
        log_directory: /var/log/postgresql
        idle_in_transaction_session_timeout: 600000
        max_worker_processes: 24
        max_parallel_workers: 24
        max_parallel_workers_per_gather: 4
        max_parallel_maintenance_workers: 2

  initdb:  # List options to be passed on to initdb
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5


postgresql:
  listen: xx.xx.xx.xx,xx.xx.xx.xx,127.0.0.1:5432
  connect_address: xx.xx.xx.xx:5432
  use_unix_socket: true
  data_dir: /mnt/dbstorage/postgresql/12/main
  bin_dir: /usr/lib/postgresql/12/bin
  config_dir: /etc/postgresql/12/main
  pgpass: /var/lib/postgresql/.pgpass_patroni
  autovacuum: 'on'
  authentication:
    replication:
      username: replicator
      password: xxx
    superuser:
      username: postgres
      password: xxxx
#    rewind:  # Has no effect on postgres 10 and lower
#      username: rewind_user
#      password: rewind_password
  parameters:
    unix_socket_directories: /var/run/postgresql
    stats_temp_directory: /var/lib/pgsql_stats_tmp


  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false

#  callbacks:
#    on_start:
#    on_stop:
#    on_restart:
#    on_reload:
#    on_role_change:

  create_replica_methods:
    - pgbackrest
    - basebackup
  pgbackrest:
    command: /usr/bin/pgbackrest --stanza=prod --link-all --delta restore
    keep_data: True
    no_params: True
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'


watchdog:
  mode: off  # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

  # specify a node to replicate from (cascading replication)
#  replicatefrom: (node name)
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=prod archive-push %p
    archive_mode: true
    archive_timeout: 1800s
    auto_explain.log_analyze: true
    auto_explain.log_buffers: true
    auto_explain.log_min_duration: 10s
    auto_explain.log_nested_statements: true
    auto_explain.log_timing: false
    auto_explain.log_triggers: true
    auto_explain.log_verbose: true
    autovacuum: true
    autovacuum_analyze_scale_factor: 0.02
    autovacuum_max_workers: 5
    autovacuum_naptime: 1s
    autovacuum_vacuum_cost_delay: 20
    autovacuum_vacuum_cost_limit: 200
    autovacuum_vacuum_scale_factor: 0.01
    checkpoint_completion_target: 0.9
    checkpoint_timeout: 15min
    default_statistics_target: 100
    effective_cache_size: 4GB
    effective_io_concurrency: 200
    hot_standby: true
    hot_standby_feedback: true
    huge_pages: try
    idle_in_transaction_session_timeout: 600000
    lock_timeout: 50000
    log_checkpoints: true
    log_directory: /var/log/postgresql
    log_filename: postgresql-%a.log
    log_line_prefix: '%t [%p-%l] %r %q%u@%d '
    log_lock_waits: true
    log_rotation_age: 1d
    log_rotation_size: 2097152
    log_temp_files: 0
    log_truncate_on_rotation: true
    logging_collector: true
    maintenance_work_mem: 1GB
    max_connections: 2500
    max_files_per_process: 4096
    max_locks_per_transaction: 256
    max_parallel_maintenance_workers: 4
    max_parallel_workers: 16
    max_parallel_workers_per_gather: 4
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: 8GB
    max_worker_processes: 16
    min_wal_size: 2GB
    pg_stat_statements.max: 10000
    pg_stat_statements.save: false
    pg_stat_statements.track: all
    random_page_cost: 1.1
    seq_page_cost: 1
    shared_buffers: 16GB
    shared_preload_libraries: pg_stat_statements,auto_explain
    superuser_reserved_connections: 10
    synchronous_commit: true
    track_activities: true
    track_counts: true
    track_functions: all
    track_io_timing: true
    wal_buffers: 16MB
    wal_keep_segments: 130
    wal_level: replica
    wal_log_hints: true
    work_mem: 4MB
  pg_hba:
  - local all postgres  ident
  - host all all 0.0.0.0/0 md5
  - host replication replicator 0.0.0.0/0 md5
  recovery_conf:
    restore_command: pgbackrest --stanza=prod archive-get %f "%p"
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: true
synchronous_node_count: 2
ttl: 30
```

### Patroni log files

```shell
---

scope: postgres-cluster
name: pg1-xx-xx-xx
namespace: /service/

log:
  level: DEBUG
  traceback_level: ERROR
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000
  dir: /var/log/patroni
  file_num: 4
  file_size: 25000000
  loggers:
    patroni.postmaster: WARNING
    urllib3: WARNING

restapi:
  listen: xx.xx.xx.xx:8008
  connect_address: xx.xx.xx.xx:8008
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

etcd:
  hosts: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

bootstrap:
  method: pgbackrest
  pgbackrest:
    command: "pgbackrest --stanza=prod --log-level-console=info --delta restore"
    keep_existing_recovery_conf: True
    no_params: True
    recovery_conf:
      recovery_target_timeline: latest
      recovery_target_action: promote
      restore_command: "pgbackrest --stanza=prod archive-get %f %p"
  method: initdb
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_node_count: 2
    # standby_cluster:
      # host: 127.0.0.1
      # port: 1111
      # primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 250
        superuser_reserved_connections: 10
        max_locks_per_transaction: 256
        max_prepared_transactions: 0
        huge_pages: try
        shared_buffers: 2GB
        work_mem: 16MB
        maintenance_work_mem: 256MB
        effective_cache_size: 4GB
        checkpoint_timeout: 15min
        checkpoint_completion_target: 0.9
        min_wal_size: 1GB
        max_wal_size: 2GB
        wal_buffers: 16MB
        default_statistics_target: 1000
        seq_page_cost: 1
        random_page_cost: 1.1
        effective_io_concurrency: 200
        synchronous_commit: on
        autovacuum: on
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_vacuum_cost_limit: 200
        autovacuum_vacuum_cost_delay: 20
        autovacuum_naptime: 1s
        max_files_per_process: 4096
        archive_mode: on
        archive_timeout: 1800s
        archive_command: cd .
        wal_level: replica
        wal_keep_segments: 200
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: on
        wal_log_hints: on
        shared_preload_libraries: pg_stat_statements,auto_explain
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        pg_stat_statements.save: off
        auto_explain.log_min_duration: 10s
        auto_explain.log_analyze: true
        auto_explain.log_buffers: true
        auto_explain.log_timing: false
        auto_explain.log_triggers: true
        auto_explain.log_verbose: true
        auto_explain.log_nested_statements: true
        track_io_timing: on
        log_lock_waits: on
        log_temp_files: 0
        track_activities: on
        track_counts: on
        track_functions: all
        log_checkpoints: on
        logging_collector: on
        log_truncate_on_rotation: on
        log_rotation_age: 1d
        log_rotation_size: 0
        log_line_prefix: '%t [%p-%l] %r %q%u@%d '
        log_filename: 'postgresql-%a.log'
        log_directory: /var/log/postgresql
        idle_in_transaction_session_timeout: 600000
        max_worker_processes: 24
        max_parallel_workers: 24
        max_parallel_workers_per_gather: 4
        max_parallel_maintenance_workers: 2

  initdb:  # List options to be passed on to initdb
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5


postgresql:
  listen: xx.xx.xx.xx,xx.xx.xx.xx,127.0.0.1:5432
  connect_address: xx.xx.xx.xx:5432
  use_unix_socket: true
  data_dir: /mnt/dbstorage/postgresql/12/main
  bin_dir: /usr/lib/postgresql/12/bin
  config_dir: /etc/postgresql/12/main
  pgpass: /var/lib/postgresql/.pgpass_patroni
  autovacuum: 'on'
  authentication:
    replication:
      username: replicator
      password: xxx
    superuser:
      username: postgres
      password: xxxx
#    rewind:  # Has no effect on postgres 10 and lower
#      username: rewind_user
#      password: rewind_password
  parameters:
    unix_socket_directories: /var/run/postgresql
    stats_temp_directory: /var/lib/pgsql_stats_tmp


  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false

#  callbacks:
#    on_start:
#    on_stop:
#    on_restart:
#    on_reload:
#    on_role_change:

  create_replica_methods:
    - pgbackrest
    - basebackup
  pgbackrest:
    command: /usr/bin/pgbackrest --stanza=prod --link-all --delta restore
    keep_data: True
    no_params: True
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'


watchdog:
  mode: off  # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

  # specify a node to replicate from (cascading replication)
#  replicatefrom: (node name)
```

### PostgreSQL log files

```shell
didn't find anything in postgresql logs
```

### Have you tried to use GitHub issue search?

- [X] Yes
