### ISSUE TITLE
Patroni doesn't apply wal_level option to Postgres

### ISSUE THREAD

**Issue by swood** [zalando/patroni#2923]
### What happened?

Hello. I am trying to configure a Postgres cluster with Patroni with logical replication slots to use for Debezium. However, the wal_level option is still `replica` besides on the `logical` in the Patroni configuration.

### How can we reproduce it (as minimally and precisely as possible)?

Just use my configuration.

### What did you expect to happen?

I expect to have wal_level: logical option in the Postgres configuration.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.1.2
-   PostgreSQL version:  13.12-1
-   DCS (and its version):  etcd

### Patroni configuration file

```yaml
name: patroni-1
namespace: service
scope: patroni
level: debug
traceback_level: True
etcd3:
  hosts: 1.1.1.1:2379,1.1.1.2:2379,1.1.1.3:2379
  cacert: /etc/ssl/ca.crt
  cert: /etc/ssl/client.crt
  key: /etc/ssl/client.key
  protocol: 'https'
restapi:
  connect_address: '1.1.1.1:8009'
  listen: '0.0.0.0:8009'
  protocol: 'http'
  authentication:
    username: 'admin'
    password: 'password'
ctl:
  insecure: True
bootstrap:
  dcs:
    ttl: 35
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 10485760
    synchronous_mode: False
    synchronous_mode_strict: False
    pg_rewind: True
    slots:
      logicreplia:
        database: testdb
        plugin: pgoutput
        type: logical
    postgresql:
      use_pg_rewind: True
      use_slots: True
      parameters:
        listen_addresses: '*'
        hot_standby_feedback: 'on'
        max_connections: 2200
        tcp_keepalives_idle: 5
        tcp_keepalives_interval: 1
        tcp_keepalives_count: 5
        bgwriter_delay: 10ms
        bgwriter_lru_maxpages: 5000
        bgwriter_lru_multiplier: 10.0
        bgwriter_flush_after: 256
        fsync: on
        full_page_writes: on
        synchronous_commit: off
        commit_delay: 1000
        commit_siblings: 100
        shared_buffers: "2GB"
        effective_cache_size: "2GB"
        work_mem: "1MB"
        maintenance_work_mem: "2GB"
        wal_level: logical
        logical_decoding: on
        max_wal_senders: 10
        wal_keep_size: "2GB"
        min_wal_size: "1GB"
        max_wal_size: "2GB"
        wal_compression: off
        wal_sync_method: fdatasync
        wal_log_hints: on
        checkpoint_completion_target: 0.9
        checkpoint_warning: 10min
        checkpoint_flush_after: 256
        checkpoint_timeout: 30min
        temp_buffers: 128MB
        effective_io_concurrency: 200
        random_page_cost: 1.1
        datestyle: 'iso, mdy'
        timezone: 'UTC'
        lc_messages: 'en_US.UTF-8'
        lc_monetary: 'en_US.UTF-8'
        lc_numeric: 'en_US.UTF-8'
        lc_time: 'en_US.UTF-8'
        default_text_search_config: 'pg_catalog.english'
        max_worker_processes: 72
        max_parallel_workers_per_gather: 6
        max_parallel_workers: 40
        max_parallel_maintenance_workers: 4
        max_logical_replication_workers: 8
        max_replication_slots: 10
        log_line_prefix: '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h'
        log_timezone: 'UTC'
        log_checkpoints: on
        log_lock_waits: on
        log_temp_files: 0
        log_destination: syslog
        log_min_duration_statement: 200ms
        log_statement: ddl
        shared_preload_libraries: 'pg_stat_statements,auto_explain'
        pg_stat_statements.track: top
        stats_temp_directory: "/var/run/postgresql"
        auto_explain.log_min_duration: '60s'
        auto_explain.log_analyze: on
        auto_explain.log_buffers: on
        auto_explain.log_wal: on
        auto_explain.log_settings: on
        autovacuum: True
        autovacuum_max_workers: 10
        autovacuum_naptime: 1
        autovacuum_vacuum_threshold: 50
        autovacuum_analyze_threshold: 10
        autovacuum_vacuum_scale_factor: 0.03
        autovacuum_analyze_scale_factor: 0.01
        autovacuum_vacuum_insert_scale_factor: 0.01
        autovacuum_vacuum_cost_limit: 5000
        autovacuum_vacuum_cost_delay: 10ms
        idle_in_transaction_session_timeout: 30min
        statement_timeout: 30min
        jit: on
  initdb:
    - encoding: UTF8
    - data-checksums
postgresql:
  pg_hba:
    - host all zabbix 127.0.0.1/32 ident
    - host all patroni all md5
    - host all all 127.0.0.1/32 md5
    - local all all peer
    - local all postgres peer
    - host all replica 1.1.1.2/32 trust
    - host all replica 127.0.0.1/32 trust
    - host replication replica 1.1.1.1/32 md5
    - host all all 1.1.1.1/32 md5
    - host replication replica 1.1.1.2/32 md5
    - host all all 1.1.1.3/32 md5
    - host replication replica 1.1.1.2/32 md5
    - host all all 1.1.1.3/32 md5
  authentication:
    superuser:
      username: postgres
      password:  password3
    replication:
      username: replica
      password:  password2
  listen: 0.0.0.0:5432
  connect_address: 1.1.1.1:5432
  config_dir: /etc/postgresql/13/main
  data_dir: /var/lib/postgresql/13/main
  bin_dir: /usr/lib/postgresql/13/bin
  parameters:
    listen_addresses: '*'
    hot_standby_feedback: on
    max_connections: 2200
    tcp_keepalives_idle: 5
    tcp_keepalives_interval: 1
    tcp_keepalives_count: 5
    bgwriter_delay: 10ms
    bgwriter_lru_maxpages: 5000
    bgwriter_lru_multiplier: 10.0
    bgwriter_flush_after: 256
    fsync: on
    full_page_writes: on
    synchronous_commit: off
    commit_delay: 1000
    commit_siblings: 100
    shared_buffers: "2GB"
    effective_cache_size: "2GB"
    work_mem: "16MB"
    maintenance_work_mem: "2GB"
    wal_level: logical
    max_wal_senders: 10
    wal_keep_size: "4GB"
    min_wal_size: "4GB"
    max_wal_size: "10GB"
    wal_compression: off
    wal_sync_method: fdatasync
    wal_log_hints: on
    checkpoint_completion_target: 0.9
    checkpoint_warning: 10min
    checkpoint_flush_after: 256
    checkpoint_timeout: 30min
    temp_buffers: "128MB"
    effective_io_concurrency: 200
    random_page_cost: 1.1
    datestyle: 'iso, mdy'
    timezone: 'UTC'
    lc_messages: 'en_US.UTF-8'
    lc_monetary: 'en_US.UTF-8'
    lc_numeric: 'en_US.UTF-8'
    lc_time: 'en_US.UTF-8'
    default_text_search_config: 'pg_catalog.english'
    max_worker_processes: 72
    max_parallel_workers_per_gather: 6
    max_parallel_workers: 40
    max_parallel_maintenance_workers: 4
    max_logical_replication_workers: 8
    max_replication_slots: 10
    log_line_prefix: '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h'
    log_timezone: 'UTC'
    log_checkpoints: on
    log_lock_waits: on
    log_temp_files: 0
    log_destination: syslog
    log_min_duration_statement: 200ms
    log_statement: ddl
    shared_preload_libraries: 'pg_stat_statements,auto_explain'
    pg_stat_statements.track: top
    stats_temp_directory: "/var/run/postgresql"
    auto_explain.log_min_duration: '60s'
    auto_explain.log_analyze: on
    auto_explain.log_buffers: on
    auto_explain.log_wal: on
    auto_explain.log_settings: on
    autovacuum: True
    autovacuum_max_workers: 10
    autovacuum_naptime: 1
    autovacuum_vacuum_threshold: 50
    autovacuum_analyze_threshold: 10
    autovacuum_vacuum_scale_factor: 0.03
    autovacuum_analyze_scale_factor: 0.01
    autovacuum_vacuum_insert_scale_factor: 0.01
    autovacuum_vacuum_cost_limit: 5000
    autovacuum_vacuum_cost_delay: 10ms
    idle_in_transaction_session_timeout: 30min
    statement_timeout: 30min
    jit: on
```

### patronictl show-config

```yaml
nothing. Which is another question:

# patronictl -c /etc/patroni/config.yml show-config
{}
```

### Patroni log files

```shell
No errors, no information.
```

### PostgreSQL log files

```shell
No errors, no information.
```

### Have you tried to use GitHub issue search?

- [X] Yes
