### ISSUE TITLE
Logical slot true issue in replica vm

### ISSUE THREAD

**Issue by Selimtatlisu** [zalando/patroni#2949]
### What happened?

We are using patroni version 3.1.0 in our pgs cluster. When we look at the logical slots on the master node it shows as true.It is a normal. 
But when we check the logical slots on the replica vm's and then we see one slot as true. 
This causes the wal disk to fill up. 

### How can we reproduce it (as minimally and precisely as possible)?

-

### What did you expect to happen?

I expect logical slots to appear as false in replica vm's

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.1.0
-   PostgreSQL version: 14.5

### Patroni configuration file

```yaml
slots:
  debezium_events_debezium_v1:
    database: ***
    plugin: pgoutput
    type: logical
  debezium_mails_debezium:
    database: ***
    plugin: pgoutput
    type: logical
```

### patronictl show-config

```yaml
--
```

### Patroni log files

```shell
--
```

### PostgreSQL log files

```shell
--
```

### Have you tried to use GitHub issue search?

- [X] Yes
