### ISSUE TITLE
restapi section versus ctl section

### ISSUE THREAD

**Issue by kikijolicoeur** [zalando/patroni#2973]
### What happened?

some patronictl commands or functionnality (like switchover or failover) no more work when I upgraded patroni from 3.0.4 to 3.1.X or 3.2.X. 
I noticed what there was a breaking change in 3.1.0  in Patroni Release notes: 

"Changed semantic of restapi.keyfile and restapi.certfile (Alexander Kukushkin)
Previously Patroni was using restapi.keyfile and restapi.certfile as client certificates as a fallback if there were no respective configuration parameters in the ctl section."

My restapi section use cerfile, keyfile and cafile. 
the documentation said that the ctl section is optional. So in my patroni configuration file ctl section is commented (with #).
After upgrade (and discover that the failover no more work)  I understood that in my case, the ctl section was mandatory.

### How can we reproduce it (as minimally and precisely as possible)?

restapi:
  listen: X.X.X.X:8008
  connect_address: X.X.X.X:8008
  certfile: /etc/patroni/server.crt
  keyfile: /etc/patroni/server.key
  #keyfile_password: 
  cafile: /etc/ssl/certs/cgdm-pgha.crt
  #ciphers: “ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:!SSLv1:!SSLv2:!SSLv3:!TLSv1:!TLSv1.1”
  verify_client: optional

#ctl:
#insecure: false
#cacert: /etc/ssl/certs/cgdm-pgha.crt
#certfile: /etc/patroni/server.crt
#keyfile: /etc/patroni/server.key

### What did you expect to happen?

I think, the documentation should indicates that the ctl section is mandatory in case of using certificate.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.2.0
-   PostgreSQL version: 15.4
-   DCS (and its version): etcd 3.5.9

### Patroni configuration file

```yaml
---
scope: "15-main"
namespace: "/postgresql/dcropg15ha04/"
name: "rebpgh1w001.hosting.cegedim.cloud"

etcd3:
  hosts: 10.25.52.137:2379,10.25.52.138:2379,10.25.52.91:2379,10.25.52.109:2379,10.25.52.139:2379  
  protocol: https
  cacert: "/etc/ssl/certs/cgdm-etcd.crt"
  cert: "/etc/patroni/etcd_client.crt"
  key: "/etc/patroni/etcd_client.key"
  username: "XXXXXXXX"
  password: "XXXXXXXXXX"

log:
  level: INFO
  traceback_level: ERROR
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000 
  dir: /var/log/patroni
  file_num: 60
  file_size: 25000000
  loggers:
    patroni.postmaster: WARNING
    urllib3: WARNING

bootstrap:
  # Custom bootstrap method
  # The options --scope= and --datadir= are passed to the custom script by
  # patroni and passed on to pg_createcluster by pg_createcluster_patroni
  method: pg_createcluster
  pg_createcluster:
    command: /usr/bin/cgdm_paas_postgres_instance_patroni

  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 60
    loop_wait: 5
    retry_timeout: 27
    maximum_lag_on_failover: "10485760"
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    synchronous_node_count: 1
    # standby_cluster:
      # host: 127.0.0.1
      # port: 1111
      # primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
      use_slots: true
      #recovery_conf:
      parameters:
         wal_keep_segments: 64
         wal_log_hints: on
         wal_level: logical
         hot_standby: on
         max_replication_slots: 10
         max_wal_senders: 10
         track_commit_timestamp: off
         max_worker_processes: 8
         max_connections: 500
         max_locks_per_transaction: 64
         max_prepared_transactions: 0
         logging_collector: on
         log_directory: '/var/log/postgresql'
         log_filename: 'postgresql-15-main.log'
         cluster_name: '15-main'
         data_directory: '/var/lib/postgresql/data/15/main'
         log_line_prefix: '%m [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '
         unix_socket_permissions: "0770"
         log_destination: stderr
         work_mem: 100MB
         maintenance_work_mem: 1GB
      # the following section (pg_hba) is written into /config key into ETCD. After that any node
      # will take this value and write it into pg_hba.conf. Later, you can use patronictl edit-config to change pg_hba
      # on all nodes in the cluster.
      pg_hba:
        - local   all             postgres                              peer
        - local   all             XXXXXXXXX                             peer
        - local   all             all                                   peer
        - host    all             XXXXXXXXXXXXX    127.0.0.1/32         scram-sha-256
        - host    replication     XXXXXXXXXXXXX    127.0.0.1/32         scram-sha-256        
        - host    all             XXXXXXX          10.255.0.0/21        scram-sha-256
        - host    all             XXXXXXXXX        0.0.0.0/0            scram-sha-256
        - host    all             all              10.25.29.0/24        scram-sha-256
        - host    all             all              10.62.25.0/24        scram-sha-256
        - host    replication     XXXXXXXXXXXXX    10.25.52.174/32       scram-sha-256
        - host    cgdm            XXXXXXXXXXXXX    10.25.52.174/32       scram-sha-256        
        - host    cgdm            XXXXXXXXXX       10.25.52.174/32       scram-sha-256
        - host    postgres        XXXXXXXXXX       10.25.52.174/32       scram-sha-256
        - host    replication     XXXXXXXXXXXXX    10.25.52.216/32       scram-sha-256
        - host    cgdm            XXXXXXXX         10.25.52.216/32       scram-sha-256        
        - host    cgdm            XXXXXXXXXX       10.25.52.216/32       scram-sha-256
        - host    postgres        XXXXXXXXXX       10.25.52.216/32       scram-sha-256
        
        - host    cgdm            all              0.0.0.0/0            reject
        - host    all             all              0.0.0.0/0            scram-sha-256

  users:


postgresql:
  database: cgdm
  authentication:
    superuser:
      username: postgres
      password:
    replication:
      username: "XXXXXXXXXXX"
      password: "XXXXXXXXXXX"
    rewind:  # Has no effect on postgres 10 and lower
      username: "XXXXXXXXXXX"
      password: "XXXXXXXXXXX"

  callbacks:
    #on_start:
    #on_stop:
    #on_restart:
    #on_reload:
    #on_role_change:
  connect_address: 10.25.52.174:5432
  config_dir: /etc/postgresql/15/main
  data_dir: /var/lib/postgresql/data/15/main
  bin_dir: /usr/lib/postgresql/15/bin
  listen: "10.25.52.174,127.0.0.1:5432"
  use_unix_socket: true
  pgpass: /var/lib/postgresql/15-main.pgpass
  # custom_conf:
  parameters:
    unix_socket_directories: '/var/run/postgresql'
    # Emulate default Debian/Ubuntu logging
    logging_collector: 'on'
    log_directory: '/var/log/postgresql'
    log_filename: 'postgresql-15-main.log'
    archive_command: pgbackrest --stanza=dcropg15ha04-000001 archive-push %p
  pg_ctl_timeout: 60
  use_pg_rewind: true
  remove_data_directory_on_rewind_failure: true
  remove_data_directory_on_diverged_timelines: true
  # Custom clone method
  # The options --scope= and --datadir= are passed to the custom script by
  # patroni and passed on to pg_createcluster by pg_clonecluster_patroni
  create_replica_method:
    - pg_clonecluster
  pg_clonecluster:
    command: /usr/bin/cgdm_clonecluster_patroni
  pre_promote:

restapi:
  listen: 10.25.52.174:8008
  connect_address: 10.25.52.174:8008
  certfile: /etc/patroni/server.crt
  keyfile: /etc/patroni/server.key
  #keyfile_password: 
  cafile: /etc/ssl/certs/cgdm-pgha.crt
  #ciphers: “ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:!SSLv1:!SSLv2:!SSLv3:!TLSv1:!TLSv1.1”
  verify_client: optional
#  http_extra_headers:
#  https_extra_headers:
#    'X-Frame-Options': 'SAMEORIGIN'
#    'X-XSS-Protection': '1; mode=block'
#    'X-Content-Type-Options': 'nosniff'
# 
#  authentication:
#    username: username
#
#ctl:
#   insecure: false
#   cacert: /etc/ssl/certs/cgdm-pgha.crt
#   certfile: /etc/patroni/server.crt
#   keyfile: /etc/patroni/server.key

watchdog:
  mode: required
  device: /dev/watchdog
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
  # specify a node to replicate from (cascading replication)
  # replicatefrom: (node name)
```

### patronictl show-config

```yaml
loop_wait: 5
master_start_timeout: 300
maximum_lag_on_failover: '10485760'
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=dcropg15ha04-000001 archive-push %p
    cluster_name: 15-main
    data_directory: /var/lib/postgresql/data/15/main
    hot_standby: true
    log_destination: stderr
    log_directory: /var/log/postgresql
    log_filename: postgresql-15-main.log
    log_line_prefix: '%m [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h '
    logging_collector: true
    maintenance_work_mem: 1GB
    max_connections: 500
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    shared_preload_libraries: pg_stat_statements,timescaledb
    track_commit_timestamp: false
    unix_socket_permissions: '0770'
    wal_keep_segments: 64
    wal_level: logical
    wal_log_hints: true
    work_mem: 100MB
  pg_hba:
  - local   all             postgres                              peer
  - local   all             XXXXXXXXX                             peer
  - local   all             all                                   peer
  - host    all             XXXXXXXXXXXXX    127.0.0.1/32         scram-sha-256
  - host    replication     XXXXXXXXXXXXX    127.0.0.1/32         scram-sha-256
  - host    all             XXXXXXX          10.255.0.0/21        scram-sha-256
  - host    all             XXXXXXXXX        0.0.0.0/0            scram-sha-256
  - host    all             all              10.25.29.0/24        scram-sha-256
  - host    all             all              10.62.25.0/24        scram-sha-256
  - host    replication     XXXXXXXXXXXXX    10.25.52.174/32       scram-sha-256
  - host    cgdm            XXXXXXXXXXXXX    10.25.52.174/32       scram-sha-256
  - host    cgdm            XXXXXXXXXXXXX    10.25.52.174/32       scram-sha-256
  - host    postgres        XXXXXXXXXXXX     10.25.52.174/32       scram-sha-256
  - host    replication     XXXXXXXXXXXX     10.25.52.216/32       scram-sha-256
  - host    cgdm            XXXXXXXX         10.25.52.216/32       scram-sha-256
  - host    cgdm            XXXXXXXXXX       10.25.52.216/32       scram-sha-256
  - host    postgres        XXXXXXXXXX       10.25.52.216/32       scram-sha-256
  - host    cgdm            all              0.0.0.0/0            reject
  - host    all             all              0.0.0.0/0            scram-sha-256
  use_pg_rewind: true
  use_slots: true
retry_timeout: 27
synchronous_mode: false
synchronous_mode_strict: false
synchronous_node_count: 1
ttl: 60
```

### Patroni log files

```shell
root@rebpgh1w002:~# patronictl switchover
Current cluster topology
+ Cluster: 15-main (7286107793335413019) ----------+---------+-----------+----+-----------+
| Member                            | Host         | Role    | State     | TL | Lag in MB |
+-----------------------------------+--------------+---------+-----------+----+-----------+
| rebpgh1w001.hosting.cegedim.cloud | 10.25.52.174 | Replica | streaming | 16 |         0 |
| rebpgh1w002.hosting.cegedim.cloud | 10.25.52.216 | Leader  | running   | 16 |           |
+-----------------------------------+--------------+---------+-----------+----+-----------+
Primary [rebpgh1w002.hosting.cegedim.cloud]: 
Candidate ['rebpgh1w001.hosting.cegedim.cloud'] []: rebpgh1w001.hosting.cegedim.cloud
When should the switchover take place (e.g. 2023-12-05T09:51 )  [now]: 
Are you sure you want to switchover cluster 15-main, demoting current leader rebpgh1w002.hosting.cegedim.cloud? [y/N                                                                                                                        ]: y
Switchover failed, details: 403, client certificate required
```

### PostgreSQL log files

```shell
not a PG issue
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

As the documentation said, the keys restapi.certfile, restapi.keyfile, restapi.cafile are optional. So after I commented out the ctl section and verify that the failover works well, I tried to comment restapi.certfile, restapi.keyfile, restapi.cafile. I ran a switchover and the result was :
root@rebpgh1w002:/etc/patroni# patronictl switchover --leader rebpgh1w001.hosting.cegedim.cloud --candidate rebpgh1w002.hosting.cegedim.cloud --force
Current cluster topology
+ Cluster: 15-main (7286107793335413019) ----------+---------+-----------+----+-----------+
| Member                            | Host         | Role    | State     | TL | Lag in MB |
+-----------------------------------+--------------+---------+-----------+----+-----------+
| rebpgh1w001.hosting.cegedim.cloud | 10.25.52.174 | Leader  | running   | 17 |           |
| rebpgh1w002.hosting.cegedim.cloud | 10.25.52.216 | Replica | streaming | 17 |         0 |
+-----------------------------------+--------------+---------+-----------+----+-----------+
Switchover failed, details: 412, switchover is not possible: no good candidates have been found

In the patroni logfile on the leader:
2023-12-05 10:19:09,037 INFO: received switchover request with leader=rebpgh1w001.hosting.cegedim.cloud candidate=rebpgh1w002.hosting.cegedim.cloud scheduled_at=None
2023-12-05 10:19:09,039 WARNING: Request failed to rebpgh1w002.hosting.cegedim.cloud: GET http://10.25.52.216:8008/patroni (__init__() got an unexpected keyword argument 'assert_hostname')

So in my case with Patroni 3.2.0 I need the ctl section with certificate parameter AND the restapi with (same) certificate parameter.
