### ISSUE TITLE
Replication is failing

### ISSUE THREAD

**Issue by Kumar6295** [zalando/patroni#2988]
### What happened?

Hi All,
i am using postgresql with patroni cluster.it was working fine. 
i was faced resource issue in one of the server. so , one of the node was down so long.
now , resource is increase,using systemctl start patroni. service is start.

node 1 having 2 TB of data.
node 2 i am trying to up.

checked patronictl it is showing replica.
 patronictl -c /etc/patroni.yml  list
+----------+--------+--------------+--------+------------------+-----+-----------+
| Cluster  | Member |     Host     |  Role  |      State       |  TL | Lag in MB |
+----------+--------+--------------+--------+------------------+-----+-----------+
| postgres |  pg01  | 10.20.30.01 |        | creating replica |     |   unknown |
| postgres |  pg02  | 10.20.30.02 | Leader |     running      | 838 |           |
+----------+--------+--------------+--------+------------------+-----+-----------+

it working fine and suddenly below errors coming.

**systemctl status**

 systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/etc/systemd/system/patroni.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2023-12-18 10:56:57 IST; 12h ago
 Main PID: 78723 (patroni)
    Tasks: 8
   CGroup: /system.slice/patroni.service
           ├─78723 /usr/local/bin/python3.6 /usr/local/bin/patroni /etc/patroni.yml
           └─94493 /usr/pgsql-11/bin/pg_basebackup --pgdata=/DATA/pgdata/patroni -X stream --dbname=dbname=postgres user=replicator host=172.21.82.30 port=5432 .......................

Dec 18 10:56:57 chaithanya-60 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Dec 18 14:56:05 chaithanya-60 patroni[78723]: pg_basebackup: COPY stream ended before last file was finished
Dec 18 14:56:05 chaithanya-60 patroni[78723]: pg_basebackup: removing data directory "/DATA/pgdata/patroni"
Dec 18 19:05:13 chaithanya-60 patroni[78723]: pg_basebackup: COPY stream ended before last file was finished
Dec 18 19:05:13 chaithanya-60 patroni[78723]: pg_basebackup: removing data directory "/DATA/pgdata/patroni"
Dec 18 23:00:02 chaithanya-60 patroni[78723]: pg_basebackup: COPY stream ended before last file was finished
Dec 18 23:00:02 chaithanya-60 patroni[78723]: pg_basebackup: removing data directory "/DATA/pgdata/patroni"

how to resolve the issue.kindly suggest.

### How can we reproduce it (as minimally and precisely as possible)?

..

### What did you expect to happen?

replication should be work fine and make it ccluster .

### Patroni/PostgreSQL/DCS version

postgresql : 11.7
etcd:2.3.1
patroni :  1.6.4

### Patroni configuration file

```yaml
scope: postgres
name: pg01

restapi:
    listen:  10.20.30.01:8008
    connect_address: 10.20.30.01:8008

etcd:
    hosts: 10.20.30.02:2379,10.20.30.01:2379,10.20.30.03:2379

bootstrap:
    dcs:
        ttl: 180
        loop_wait: 45
        retry_timeout: 60
        maximum_lag_on_failover: 2048576
        postgresql:
            use_pg_rewind: true
            parameters:
                    wal_level: logical
                    hot_standby: "on"
                    wal_keep_segments: 250
                    max_wal_senders: 30
                    max_replication_slots: 30
                    checkpoint_timeout: 30
                    max_connections: 1000
                    max_locks_per_transaction: 256
                    max_worker_processes: 16
                    shared_preload_libraries: "timescaledb"

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host all          postgres    10.20.30.02/32  md5
    - host all          postgres    10.20.30.01/32  md5
    - host replication  replicator  10.20.30.02/32  md5
    - host replication  replicator  10.20.30.01/32  md5
    - host all          all         0.0.0.0/0        md5
    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 0.0.0.0:5432
    bin_dir: /usr/pgsql-11/bin
    connect_address:  10.20.30.01:5432
    data_dir: /DATA-NAS/pgdata/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: 'Replica'

        superuser:
            username: postgres
            password: 'adminpostgres'
    parameters:
        unix_socket_directories: '.'
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log:

   dir: /var/log/patroni
   level: INFO
```

### patronictl show-config

```yaml
loop_wait: 45
maximum_lag_on_failover: 2048576
postgresql:
  parameters:
    checkpoint_timeout: 30
    hot_standby: 'on'
    max_connections: 1000
    max_locks_per_transaction: 256
    max_replication_slots: 30
    max_wal_senders: 30
    shared_buffers: 16000MB
    shared_preload_libraries: timescaledb
    wal_keep_segments: 250
    wal_level: logical
  use_pg_rewind: true
retry_timeout: 60
ttl: 180
```

### Patroni log files

```shell
**patroni log**

2023-12-18 23:02:12,653 INFO: bootstrap from leader 'pg02' in progress
2023-12-18 23:02:57,653 INFO: Lock owner: pg02; I am pg01
2023-12-18 23:02:57,658 INFO: bootstrap from leader 'pg02' in progress
2023-12-18 23:03:39,818 ERROR: Error when fetching backup: pg_basebackup exited with code=1
2023-12-18 23:03:39,818 WARNING: Trying again in 5 seconds
2023-12-18 23:03:42,653 INFO: Lock owner: pg02; I am pg01
2023-12-18 23:03:42,661 INFO: bootstrap from leader 'pg02' in progress
```

### PostgreSQL log files

```shell
**postgresql log**
2023-12-18 23:00:02.274 IST [92775] ERROR:  invalid segment number 0 in file "pg_internal.init.55042"
2023-12-18 23:00:02.275 IST [92775] WARNING:  4 temporary files and directories not closed at end-of-transaction
2023-12-18 23:00:57.345 IST [92996] LOG:  terminating walsender process due to replication timeout
```

### Have you tried to use GitHub issue search?

- [X] Yes
