### ISSUE TITLE
Generated pg_basebackup command should be logged

### ISSUE THREAD

**Issue by caseyandgina** [zalando/patroni#3011]
### What happened?

When Patroni initializes a node, the pg_basebackup command it generates is not logged, and it's challenging to try to reproduce from the configuration.  I ran into an issue recently where there was a lingering hidden file in a custom WAL directory when I was trying to reinitialize, and it took me hours to figure out why.  This is not the first time I've run into this - it's tripped me up at least a half dozen times over the past few years.  It should not be this hard to determine what is going wrong, and logging the generated command would allow me to quickly copy/paste and try to run it in the foreground.  Perhaps including logging of the pg_basebackup error output would be in order as well, at least when log level is set to DEBUG.

### How can we reproduce it (as minimally and precisely as possible)?

Reinitialize a node and watch the Patroni log, at either INFO or DEBUG log level.

### What did you expect to happen?

Something more than this:

ERROR: Error when fetching backup: pg_basebackup exited with code=1
ERROR: failed to bootstrap from leader '...'

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.2.1
-   PostgreSQL version: 14.10
-   DCS (and its version): Not relevant

### Patroni configuration file

```yaml
---
scope: 14-truth
namespace: /db/
name: prime-br2-pg-truth-0

bootstrap:
  dcs:
    loop_wait: 3
    maximum_lag_on_failover: 1048576
    retry_timeout: 10
    ttl: 30
    postgresql:
      parameters:
        archive_command: envdir /etc/wal-g/14-truth /usr/local/bin/wal-g wal-push "%p"
        archive_mode: true
        archive_timeout: 5min
        autovacuum_vacuum_cost_delay: 10ms
        autovacuum_vacuum_scale_factor: 0.2
        autovacuum_vacuum_threshold: 10000
        checkpoint_completion_target: 0.9
        checkpoint_timeout: 30min
        cluster_name: truth
        default_statistics_target: 100
        effective_cache_size: 252GB
        effective_io_concurrency: 200
        hot_standby_feedback: true
        huge_pages: try
        idle_in_transaction_session_timeout: 15min
        log_autovacuum_min_duration: 0
        log_checkpoints: true
        log_connections: true
        log_destination: stderr
        log_directory: /var/log/postgresql/14/truth
        log_disconnections: true
        log_duration: false
        log_error_verbosity: DEFAULT
        log_file_mode: '0640'
        log_filename: '%Y-%m-%d_%H.log'
        log_line_prefix: '%m [%p]: %qdb=%d,user=%u,app=%a,client=%h %v '
        log_lock_waits: true
        log_min_duration_statement: 250ms
        log_min_messages: WARNING
        log_recovery_conflict_waits: true
        log_replication_commands: false
        log_rotation_age: 1h
        log_rotation_size: 0
        log_statement: none
        log_temp_files: 0
        log_timezone: Etc/UTC
        logging_collector: true
        maintenance_work_mem: 2GB
        max_connections: 2500
        max_logical_replication_workers: 24
        max_parallel_maintenance_workers: 4
        max_parallel_workers: 64
        max_parallel_workers_per_gather: 4
        max_replication_slots: 64
        max_stack_depth: 7MB
        max_sync_workers_per_subscription: 24
        max_wal_senders: 16
        max_wal_size: 120GB
        min_wal_size: 70GB
        max_worker_processes: 64
        pg_stat_statements.track: all
        random_page_cost: 1.1
        restore_command: envdir /etc/wal-g/14-truth /usr/local/bin/wal-g wal-fetch "%f" "%p"
        shared_buffers: 126GB
        shared_preload_libraries: pg_stat_statements,pg_cron
        stats_temp_directory: /run/postgresql/14-truth.pg_stat_tmp
        superuser_reserved_connections: 30
        temp_file_limit: 4GB
        timezone: Etc/UTC
        track_activities: true
        track_activity_query_size: 4096
        track_functions: all
        track_io_timing: true
        unix_socket_directories: /run/postgresql
        wal_buffers: 64MB
        wal_keep_size: 60GB
        wal_level: logical
        work_mem: 64MB
      pg_hba:
        REDACTED
      pg_ident:
        REDACTED
  initdb:
    - allow-group-access
    - data-checksums
    - encoding: UTF8
    - locale: en_US.UTF8
    - waldir: /var/lib/postgresql/wal/14/truth
  users:
    REDACTED

etcd3:
  hosts:
    - prime-br2-etcd-0:2379
    - prime-br2-etcd-1:2379
    - prime-br2-etcd-2:2379

log:
  level: INFO
  dir: /var/log/patroni/14-truth
  file_num: 4
  file_size: 16777216

postgresql:
  authentication:
    replication:
      username: replication
      password: 'REDACTED'
    rewind:
      username: postgres
      password: 'REDACTED'
    superuser:
      username: postgres
      password: 'REDACTED'
  basebackup:
    - checkpoint: fast
    - waldir: /var/lib/postgresql/wal/14/truth
  bin_dir: /usr/lib/postgresql/14/bin
  connect_address: prime-br2-pg-truth-0:5432
  create_replica_methods:
    - basebackup
  data_dir: /var/lib/postgresql/14/truth
  listen: '*:5432'
  pgpass: /var/lib/postgresql/.pgpass.14-truth
  use_pg_rewind: true
  use_unix_socket: true

restapi:
  listen: '*:8008'
  connect_address: prime-br2-pg-truth-0:8008
```

### patronictl show-config

```yaml
Not relevant
```

### Patroni log files

```shell
ERROR: Error when fetching backup: pg_basebackup exited with code=1
ERROR: failed to bootstrap from leader '...'
```

### PostgreSQL log files

```shell
N/A, it never gets that far.
```

### Have you tried to use GitHub issue search?

- [X] Yes
