### ISSUE TITLE
Updating the unix_socket_directories using patronictl  edit-config does not reflect in patroni config file

### ISSUE THREAD

**Issue by omaichang** [zalando/patroni#3032]
### What happened?

postgres=# show unix_socket_directories;
 unix_socket_directories
-------------------------
 /tmp
(1 row)

[xxx@xxx ~]$ cat /etc/patroni/patroni.yml |grep unix
    unix_socket_directories: '/tmp'

Ran the following command to update the postgresql parameter
patronictl -c /etc/patroni/patroni.yml edit-config test_clus1 --pg unix_socket_directories="/tmp,/var/run/postgresql" -q --force
Show-config shows the update applied at patroni level
[xxxx@xxx ~]$ /usr/local/bin/patronictl -c /etc/patroni/patroni.yml show-config|grep unix
    unix_socket_directories: /tmp,/var/run/postgresql
restarted all nodes of the cluster
    [xxxx@xxx~]$ /usr/local/bin/patronictl -c /etc/patroni/patroni.yml restart test_clus1
+--------+---------------+---------+---------+----+-----------+
| Member | Host          | Role    | State   | TL | Lag in MB |
+ Cluster: test_clus1 (7686898789787) --+----+-----------+
| host_0 | x.x.x.x    | Replica | running | 12 |         0 |
| host_1 | x.x.x.x    | Leader  | running | 12 |           |
| host_2 | x.x.x.x    | Replica | running | 12 |         0 |
+--------+---------------+---------+---------+----+-----------+
When should the restart take place (e.g. 2024-03-08T16:30)  [now]:
Are you sure you want to restart members host_0, host_1, host_2? [y/N]: y
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2)  []:
Success: restart on member host_0
Success: restart on member host_1
Success: restart on member host_2

Validate after the change
Check again - No change to parameter on the instance
postgres=# show unix_socket_directories;
 unix_socket_directories
-------------------------
 /tmp
(1 row)

Show-config shows the update applied at patroni level
[xxxx@xxx ~]$ /usr/local/bin/patronictl -c /etc/patroni/patroni.yml show-config|grep unix
    unix_socket_directories: /tmp,/var/run/postgresql

Why would the update not be applied to the patroni config file and to the instance?

### How can we reproduce it (as minimally and precisely as possible)?

Use the attached patroni parameter file. 
[xxx@xxx ~]$ cat /etc/patroni/patroni.yml |grep unix
    unix_socket_directories: '/tmp'

Run the following command to update the postgresql parameter
patronictl -c /etc/patroni/patroni.yml edit-config test_clus1 --pg unix_socket_directories="/tmp,/var/run/postgresql" -q --force
Show-config shows the update applied at patroni level
[xxxx@xxx ~]$ /usr/local/bin/patronictl -c /etc/patroni/patroni.yml show-config|grep unix
    unix_socket_directories: /tmp,/var/run/postgresql
restart all nodes of the cluster
    [xxxx@xxx~]$ /usr/local/bin/patronictl -c /etc/patroni/patroni.yml restart test_clus1
+--------+---------------+---------+---------+----+-----------+
| Member | Host          | Role    | State   | TL | Lag in MB |
+ Cluster: test_clus1 (7686898789787) --+----+-----------+
| host_0 | x.x.x.x    | Replica | running | 12 |         0 |
| host_1 | x.x.x.x    | Leader  | running | 12 |           |
| host_2 | x.x.x.x    | Replica | running | 12 |         0 |
+--------+---------------+---------+---------+----+-----------+
When should the restart take place (e.g. 2024-03-08T16:30)  [now]:
Are you sure you want to restart members host_0, host_1, host_2? [y/N]: y
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2)  []:
Success: restart on member host_0
Success: restart on member host_1
Success: restart on member host_2

### What did you expect to happen?

when the patroni parameter is updated/modified, it should reflect on the instance and in the patroni config file for persistance.

### Patroni/PostgreSQL/DCS version

-   Patroni version: [postgres@hviqlgmgdb01 log]$ patroni --version
patroni 2.1.1

-   PostgreSQL version: 13.5
-   DCS (and its version): 

### Patroni configuration file

```yaml
[xxx@xxx ~]$ cat /etc/patroni/patroni.yml
namespace: /service/
scope: test_clus1
name: host_0

log:
  level: DEBUG
  dir: /var/log/patroni

restapi:
    # URL to access the Patroni’s REST API
    connect_address: x.x.x.x:8679
    # IP address:port that Patroni will listen to for HAProxy
    listen:          x.x.x.x:8679

etcd:
    protocol: http
    hosts: x.x.x.x:2379,x.x.x.x:2379,x.x.x.x:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        wal_level: hot_standby
        hot_standby: "on"
        wal_keep_size: 11200
        max_wal_senders: 10
        max_replication_slots: 10
        wal_log_hints: on
        config_file:  data_dir/postgresql.conf
        archive_mode: "on"
        archive_timeout: 0
        max_connections: 200
        max_locks_per_transaction: 64
        max_worker_processes: 4
        max_prepared_transactions: 0
        track_commit_timestamp: off
        archive_command: 'sh /etc/patroni/cfg/archive_command_pgbackrest.sh %p %f'
        log_directory: /pgsql/tqgmgdb01/log
        password_encryption: trust
      recovery_conf:
        restore_command: 'sh /etc/patroni/cfg/restore_command_pgbackrest.sh %p %f'
      callbacks:
        on_start: /etc/patroni/patroni_callback.sh
        on_stop: /etc/patroni/patroni_callback.sh
        on_role_change: /etc/patroni/patroni_callback.sh

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - auth: trust
  - encoding: UTF8
  - data-checksums
  - auth-local: peer
  - waldir: /pgsql/tqgmgdb01/pg_wal
  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host all postgres x.x.x.x/32 trust
  - host all postgres x.x.x.x/32 trust
  - host all postgres x.x.x.x/32 trust

  - host all all 0.0.0.0/0 trust
  - host replication rep_user x.x.x.x/32 trust
  - host replication rep_user x.x.x.x/32 trust
  - host replication rep_user x.x.x.x/32 trust

# Additional script to be launched after initial cluster
# creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

postgresql:
  listen: localhost,x.x.x.x:5432
  connect_address: x.x.x.x:5432
  data_dir: /data_dir
  bin_dir:  /usr/pgsql-13/bin
  pgpass: /tmp/pgpass0
  authentication:
    superuser:
      username: postgres
      password: postgres
    replication:
      username: rep_user
      password: rep_user
  parameters:
    unix_socket_directories: '/tmp'
  basebackup:
    - max-rate: 100M
    - waldir: /wal_dir
  custom_conf: /home/postgresql/pg_params.conf
  callbacks:
    on_start: /etc/patroni/patroni_callback.sh
    on_stop: /etc/patroni/patroni_callback.sh
    on_role_change: /etc/patroni/patroni_callback.sh

watchdog:
  mode: automatic # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: False
    noloadbalance: False
    clonefrom: false
    nosync: False
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  callbacks:
    on_role_change: /etc/patroni/patroni_callback.sh
    on_start: /etc/patroni/patroni_callback.sh
    on_stop: /etc/patroni/patroni_callback.sh
  parameters:
    archive_command: sh /etc/patroni/cfg/archive_command_pgbackrest.sh %p %f
    archive_mode: 'on'
    archive_timeout: 0
    config_file: /data_dir/postgresql.conf
    hot_standby: 'on'
    log_directory: /log
    max_connections: 200
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 4
    password_encryption: trust
    pg_stat_statements.max: 1000
    pg_stat_statements.track: top
    shared_preload_libraries: pg_stat_statements,pg_buffercache
    track_commit_timestamp: false
    unix_socket_directories: /tmp,/var/run/postgresql
    wal_keep_size: 11200
    wal_level: hot_standby
    wal_log_hints: true
  recovery_conf:
    restore_command: sh /etc/patroni/cfg/restore_command_pgbackrest.sh %p %f
  use_pg_rewind: true
  use_slots: false
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
[xxx@xxx ~]$ grep -ri unix  /var/log/patroni/patroni.log*
nothing in the log dirs for the parameter update
```

### PostgreSQL log files

```shell
log]$ grep -ri unix *
postgresql-2024-03-06_042019.log:2024-03-06 04:20:19.511 GMT [1771101] LOG:  00000: listening on Unix socket "/tmp/.s.PGSQL.5432"
postgresql-2024-03-06_042533.log:2024-03-06 04:25:34.015 GMT [2205] LOG:  00000: listening on Unix socket "/tmp/.s.PGSQL.5432"
postgresql-2024-03-06_043159.log:2024-03-06 04:31:59.157 GMT [2230] LOG:  00000: listening on Unix socket "/tmp/.s.PGSQL.5432"
postgresql-2024-03-08_183027.log:2024-03-08 18:30:27.316 GMT [1533506] LOG:  00000: listening on Unix socket "/tmp/.s.PGSQL.5432"
postgresql-2024-03-08_222831.log:2024-03-08 22:28:31.775 GMT [1626475] LOG:  00000: listening on Unix socket "/tmp/.s.PGSQL.5432"
postgresql-2024-03-08_223023.log:2024-03-08 22:30:23.928 GMT [1627749] LOG:  00000: listening on Unix socket "/tmp/.s.PGSQL.5432"
postgresql-2024-03-08_223136.log:2024-03-08 22:31:36.965 GMT [1628085] LOG:  00000: listening on Unix socket "/tmp/.s.PGSQL.5432"
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
You have the following in the configuration file:
```yaml
postgresql:
  parameters:
    unix_socket_directories: '/tmp'
```

And it overrides global configuration from DCS.
Please read the documentation: https://patroni.readthedocs.io/en/latest/patroni_configuration.html
