### ISSUE TITLE
cp in patroni 3.2.2 could not finish archiving the wal log.

### ISSUE THREAD

**Issue by Jerry-Freelancer** [zalando/patroni#3037]
### What happened?

In version 3.2.2, archive _ command: "cp %p/postgresql/archive/%f" cannot be used to archive the wal log, but archive _ command: "/usr/bin/cp %p/postgresql/archive/%f" can only be used to complete the archive, and the log prompts that the cp command cannot be found.

### How can we reproduce it (as minimally and precisely as possible)?

cp %p/postgresql/archive/%f

### What did you expect to happen?

Under normal circumstances, the archive of wal logs is completed, and I use it normally in version 3.0.2.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.2.2
-   PostgreSQL version: 15.6
-   DCS (and its version): 

### Patroni configuration file

```yaml
scope: pg_cluster
namespace: /service
name: pgdb01

log:
  level: INFO
  traceback_level: ERROR
  dir: /postgresql/app/patroni
  file_num: 10
  file_size: 104857600

restapi:
  listen: 192.168.5.171:8008
  connect_address: 192.168.5.171:8008

etcd:
  hosts: 192.168.5.171:2379,192.168.5.172:2379,192.168.5.173:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    max_timelines_history: 0
    master_start_timeout: 300
    master_stop_timeout: 0
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 3000
        superuser_reserved_connections: 100
        max_locks_per_transaction: 64
        max_worker_processes: 2
        max_prepared_transactions: 0
        wal_level: logical
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_size: 4096MB  # wal_keep_size = wal_keep_segments * wal_segment_size = 128 * 32MB
        hot_standby: "on"
        listen_addresses: "*"
        port: 5432
        cluster_name: "pg_cluster"
        archive_mode: always
        archive_command: "cp %p /postgresql/archive/%f"

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 192.168.5.171:5432
  data_dir: /postgresql/data
  pgpass: /home/postgres/.pgpass
  pg_ctl_timeout: 60
  use_pg_rewind: true
  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: true
  authentication:
    replication:
      username: repuser
      password: repuser123
    superuser:
      username: postgres
      password: postgres

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

### patronictl show-config

```yaml
[root@pgdb01 ~]# patronictl show-config
loop_wait: 10
master_start_timeout: 300
master_stop_timeout: 0
max_timelines_history: 0
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: cp %p /postgresql/archive/%f
    archive_mode: true
    cluster_name: pg_cluster
    hot_standby: 'on'
    listen_addresses: '*'
    max_connections: 3000
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 2
    port: 5432
    superuser_reserved_connections: 100
    track_commit_timestamp: false
    wal_keep_size: 4096MB
    wal_level: logical
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
ttl: 30
```

### Patroni log files

```shell
2024-03-26 10:40:59,751 INFO: no action. I am (pgdb01), the leader with the lock
2024-03-26 10:41:09,716 INFO: no action. I am (pgdb01), the leader with the lock
2024-03-26 10:41:19,724 INFO: no action. I am (pgdb01), the leader with the lock
2024-03-26 10:41:29,707 INFO: no action. I am (pgdb01), the leader with the lock
2024-03-26 10:41:39,708 INFO: no action. I am (pgdb01), the leader with the lock
```

### PostgreSQL log files

```shell
2024-03-26 10:40:58.744 CST [7445] FATAL:  archive command failed with exit code 127
2024-03-26 10:40:58.744 CST [7445] DETAIL:  The failed archive command was: cp pg_wal/00000009.history /postgresql/archive/00000009.history
2024-03-26 10:40:58.745 CST [7422] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.005 s, total=0.016 s; sync files=2, longest=0.005 s, average=0.003 s; distance=0 kB, estimate=0 kB
sh: line 1: cp: command not found
```

### Have you tried to use GitHub issue search?

- [X] Yes
