### ISSUE TITLE
Parameters such as max_connections, max_replication_slots, etc changed.  No apparent way to find out how, by who, what or when change occurred.

### ISSUE THREAD

**Issue by tomkcpr** [zalando/patroni#3054]
### What happened?

In reference to:

https://github.com/zalando/patroni/issues/1177

where parameters such as:

max_connections
max_replication_slots
etc

were set.  There is no apparent tracking of how, by whom or when the parameter changes.  Settings were reverted but not able to tell what, who, when and how the parameters changed. 

### How can we reproduce it (as minimally and precisely as possible)?

This is what I'm trying to figure out as I'm not yet sure how this occurred.

### What did you expect to happen?

I expected the parameters to be at the earlier values in post:

https://github.com/zalando/patroni/issues/1177

however, they were reverted to the default values.

### Patroni/PostgreSQL/DCS version

etcd: 3.2.32
patroni: 2.1.1
postgresql 12.18

### Patroni configuration file

```yaml
Was or used to be the following:

# patronictl -c /etc/patroni.yml edit-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 256
    max_replication_slots: 64
    max_wal_senders: 32
    wal_keep_segments: 64
  use_pg_rewind: true
retry_timeout: 10
ttl: 30


Now it is as follows. However, the parameter 'wal_keep_size: 10240' was only an addition:

# patronictl -c /etc/patroni.yml edit-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    wal_keep_size: 10240
  use_pg_rewind: true
retry_timeout: 10
ttl: 30

and max_connections is reset to 100 alongside other parameters that were also reset to their originals.  This is not the exact config file, hoping that's ok, but the full file does include and did include the customized parameters below:

# cat /etc/patroni.yml
scope: postgres
namespace: /db/
name: postgresql0

restapi:
    listen: psql01.nix.mds.xyz:8008
    connect_address: psql01.nix.mds.xyz:8008

etcd:
    host: psql01.nix.mds.xyz:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator psql01.nix.mds.xyz/0 md5
    - host replication replicator psql02.nix.mds.xyz/0 md5
    - host replication replicator psql03.nix.mds.xyz/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: psql01.nix.mds.xyz:5432
    bin_dir: /usr/pgsql-12/bin
    connect_address: psql01.nix.mds.xyz:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    unix_socket_directories: /data/patroni
    authentication:
        replication:
            username: replicator
            password: secretpassword
        superuser:
            username: postgres
            password: secretpassword
    parameters:
        unix_socket_directories: '.'
        max_connections: '256'
        max_replication_slots: '64'
        wal_keep_segments: '64'
        max_wal_senders: 32

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

Checking on the postgresql server, the parameters were indeed reverted.
```

### patronictl show-config

```yaml
Please see above.
```

### Patroni log files

```shell
Unable to retrieve this unfortunately, since this may have been months ago.  Hoping this is ok for now.
```

### PostgreSQL log files

```shell
Empty.  Only 7 days are kept and by the time the change was noticed, all of these are 0 bytes and no errors are printed.
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

When cluster recovery is done, folks will do things such as empty and recreate the postgresql directory to let replication fix things or clear the etcd DB directories to clear errors or if they run out of options to bring etcd back up due to some other errors.   There is replication between different sites as well. 

Logs system log files, such as /var/log/messages, do contain history of commands ran such as 

`patronictl -c /etc/patroni.yml edit-config`

But there is no delta of parameters saved, and hence, unable to tell that the action actually changed them or just added a single parameter.  

Just need to know where to look to find the above and if such functionality / ability does not currently exist, perhaps this can be a feature request.
