### ISSUE TITLE
3.2.2 throwing unexpected exception

### ISSUE THREAD

**Issue by einhverfr** [zalando/patroni#3066]
### What happened?

This often happens when Patroni 3.2.2 starts.

establishing a new patroni heartbeat connection to postgres
2024-05-10 05:27:26,921 INFO: PostgreSQL is still starting up, 87 seconds until timeout
2024-05-10 05:27:32,038 INFO: Lock owner: DRS-INDBPG-01; I am DRS-INDBPG-01
2024-05-10 05:27:32,108 ERROR: Unexpected exception
Traceback (most recent call last):
  File "C:\PES\patroni\patroni\ha.py", line 1972, in run_cycle
    info = self._run_cycle()
           ^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\ha.py", line 1886, in _run_cycle
    msg = self.process_healthy_cluster()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\ha.py", line 1427, in process_healthy_cluster
    return self.enforce_follow_remote_member(msg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\ha.py", line 821, in enforce_follow_remote_member
    return self.follow(demote_reason, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\ha.py", line 671, in follow
    change_required, restart_required = self.state_handler.config.check_recovery_conf(node_to_follow)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\postgresql\config.py", line 797, in check_recovery_conf
    primary_conninfo = params['primary_conninfo']
                       ~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\collections.py", line 150, in __getitem__
    return self._values[key.lower()][1]
           ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'primary_conninfo'
2024-05-10 05:27:32,117 INFO: Unexpected exception raised, please report it as a BUG

The same stack trace happens when the connection fails.  Environment is on Windows using the Patroni Environment Setup package from Cybertec with their bundled Python libraries

### How can we reproduce it (as minimally and precisely as possible)?

My best guess is to install on Windows the PES and Python dependencies as bundled.  Then set up Patroni without passwords but require them in the pg_hba.conf.  The stack trace will follow the fe_sendauth no password supplied messages.

### What did you expect to happen?

I didn't expect this message in the logs....  The message seems harmless.  It looks like a problem handling bad connections but the recovery seems fine.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.2.2
-   PostgreSQL version:  15.5
-   DCS (and its version): etcd (not sure version)


### Patroni configuration file

```yaml
(Ip addresses have been removed and authentication info sanitized)

scope: pgcluster
#namespace: /service/
name: PRD-INDBPG-03
log:
    log_size: 102400
    log_num: 30    

restapi:
  listen: 0.0.0.0:8008
  connect_address: IP28:8008
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

etcd3:
  hosts: IP26:2379,IP27:2379,IP28:2379

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
#        wal_level: hot_standby
#        hot_standby: "on"
#        wal_keep_segments: 8
#        max_wal_senders: 5
#        max_replication_slots: 5
#        wal_log_hints: "on"
#        archive_mode: "on"
#        archive_timeout: 1800s
#        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
#      recovery_conf:
#        restore_command: cp ../wal_archive/%f %p
# some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums
  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
#  - hostssl all all 0.0.0.0/0 md5
  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

postgresql:
  listen: 0.0.0.0:5432
  connect_address: IP28:5432
  data_dir: F:/pg_data
  bin_dir: C:/Program Files/PostgreSQL/15/bin
  #pgpass: pgpass0
  authentication:
    replication:
      username: patroni_replicator
      password: somepasswd
    superuser:
      username: patroni
      password: somepasswd


#watchdog:
#  mode: automatic # Allowed values: off, automatic, required
#  device: /dev/watchdog

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```


### patronictl show-config

```yaml
C:\PES\patroni>patronictl.py -c patroni.yaml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 1500
    recovery_target_timeline: latest
    restore_command: ssh barman@IP barman get-wal pg %f > %p
  use_pg_rewind: false
  use_slots: true
retry_timeout: 10
slots:
  barman:
    type: physical
  patroni_dr:
    type: physical
ttl: 30
use_pg_rewind: false
```


### Patroni log files

```shell
establishing a new patroni heartbeat connection to postgres
2024-05-10 05:27:26,921 INFO: PostgreSQL is still starting up, 87 seconds until timeout
2024-05-10 05:27:32,038 INFO: Lock owner: DRS-INDBPG-01; I am DRS-INDBPG-01
2024-05-10 05:27:32,108 ERROR: Unexpected exception
Traceback (most recent call last):
  File "C:\PES\patroni\patroni\ha.py", line 1972, in run_cycle
    info = self._run_cycle()
           ^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\ha.py", line 1886, in _run_cycle
    msg = self.process_healthy_cluster()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\ha.py", line 1427, in process_healthy_cluster
    return self.enforce_follow_remote_member(msg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\ha.py", line 821, in enforce_follow_remote_member
    return self.follow(demote_reason, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\ha.py", line 671, in follow
    change_required, restart_required = self.state_handler.config.check_recovery_conf(node_to_follow)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\postgresql\config.py", line 797, in check_recovery_conf
    primary_conninfo = params['primary_conninfo']
                       ~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\PES\patroni\patroni\collections.py", line 150, in __getitem__
    return self._values[key.lower()][1]
           ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'primary_conninfo'
2024-05-10 05:27:32,117 INFO: Unexpected exception raised, please report it as a BUG
```


### PostgreSQL log files

```shell
Nothing relevant in the PostgreSQL log files.  This sometimes appears to happen more consistently when PostgreSQL cannot be connected to.
```


### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

_No response_

**Comment by CyberDem0n** [comment]
Something is really strange here, according to the stack trace this node is running in a `standby cluster` (enforce_follow_remote_member), but there is no `standby_cluster` section in `patronictl show-config`.

**Comment by CyberDem0n** [comment]
@einhverfr please provide Patroni logs from the moment it started and also postgres logs from exactly this moment.

**Comment by einhverfr** [comment]
mea culpa!

I sent the show-config from the wrong cluster!

```
C:\PES\patroni>patronictl.py -c patroni.yaml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    recovery_target_timeline: latest
    restore_command: ssh barman@10.3.1.41 barman get-wal pg %f > %p
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
slots:
  barman:
    type: physical
standby_cluster:
  create_replica_methods:
  - basebackup
  host: 10.1.1.10
  port: 5432
  primary_slot_name: patroni_dr
ttl: 30
```
