### ISSUE TITLE
patroni_failsafe_mode_is_active prometheus metric always 0

### ISSUE THREAD

**Issue by JorgeGomezDBA** [zalando/patroni#3070]
### What happened?

The patroni_failsafe_mode_is_active prometheus metric always shows 0 value.

### How can we reproduce it (as minimally and precisely as possible)?

Reading the metric with the failsafe mode active.

### What did you expect to happen?

The metric shows the correct value when the failsafe mode is active.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.1.0
-   PostgreSQL version: 15
-   DCS (and its version): etcd 3.3.11

### Patroni configuration file

```yaml
scope: XXXXXXXXXXXXXXXXXXXXXXX
namespace: /db/
name: XXXXXXXXXXXXXXXXXXXXX

restapi:
    listen: X.X.X.X:8008
    connect_address: node_name:8008
    certfile: crt path
    keyfile: key path
    cafile: ca path
    verify_client: optional

ctl:
    insecure: false
    certfile: crt path
    keyfile: key path
    cafile: ca path

etcd:
    host: 127.0.0.1:2379

bootstrap:
    dcs:
        standby_cluster:
            host: X.X.X.X
            port: 5432
            primary_slot_name: slot_name
            create_replica_methods:
            - pgbackrest
            - basebackup
            pgbackrest:
              command: pgbackrest --stanza=name --delta restore
              keep_data: True
              no_params: True
            basebackup:
              checkpoint: 'fast'
        slots:
          node1:
            type: physical
          node2:
            type: physical
          node3:
            type: physical

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - hostssl replication replicator X.X.X.X/32 md5
    - hostssl replication replicator X.X.X.X/32 md5
    - hostssl replication replicator X.X.X.X/32 md5
    - host all all 0.0.0.0/0 md5
    users:
        user:
            password: password
            options:
                - createrole
                - createdb

postgresql:
    use_unix_socket: true
    listen: X.X.X.X:5433
    connect_address: X.X.X.X:5433
    bin_dir: /usr/pgsql-15/bin
    data_dir: /postgresql/pgdata
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: name
            password: password
        superuser:
            username: name
            password: password
    parameters:
        password_encryption: 'md5'
        unix_socket_directories: '/var/run/postgresql/'
        archive_mode: on
        archive_command: pgbackrest --stanza=name archive-push %p
        log_directory: /postgresql/logs
        log_filename: postgresql-%Y%m%d.log
        max_connections: 100
        shared_buffers: 1GB
        log_min_duration_statement: 1000
        pg_partman_bgw.role: role_name
        pg_partman_bgw.dbname: db_name
        log_error_verbosity: terse
        shared_preload_libraries: pg_partman_bgw,pg_stat_statements
        ssl: true
        ssl_cert_file: crt path
        ssl_key_file: key path
        ssl_ca_file: ca path
    recovery_conf:
        recovery_target_timeline: latest
        restore_command: pgbackrest --stanza=name archive-get %f %p
    create_replica_methods:
      - pgbackrest
      - basebackup
    pgbackrest:
        command: pgbackrest --stanza=name --delta restore
        keep_data: True
        no_params: True
    basebackup:
        checkpoint: 'fast'
        max-rate: '100M'
tags:
    nofailover: true
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
patronictl show-config
Error: Can not find suitable configuration of distributed configuration store
Available implementations: etcd, etcd3, kubernetes
```

### Patroni log files

```shell
N/A
```

### PostgreSQL log files

```shell
N/A
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

--patroni_failsafe_mode_is_active{scope="scope_name"} 0
