### ISSUE TITLE
Slave reports errors after being reinitialized

### ISSUE THREAD

**Issue by irminsul** [zalando/patroni#327]
Hi,

I used `patronictl reinit -c /config/patroni.yml hephaistos postgres2` on my cluster to reinitialize the node `postgres2`.

`pg_stat_replication` and `patronictl list` tell me that everything is fine:

```
# patronictl list -c /config/postgres.yml hephaistos
+------------+-----------+------------+--------+---------+-----------+
| Cluster    | Member    | Host       | Leader |  State  | Lag in MB |
+------------+-----------+------------+--------+---------+-----------+
| hephaistos | postgres0 | 10.20.6.15 |   *    | running |         0 |
| hephaistos | postgres1 | 10.20.1.5  |        | running |         0 |
| hephaistos | postgres2 | 10.20.2.14 |        | running |         0 |
+------------+-----------+------------+--------+---------+-----------+
```

However, the following error message started to appear in the logs of `postgres2`:

```
ERROR:  requested starting point 0/69000000 on timeline 7 is not in this server's history
DETAIL:  This server's history forked from timeline 7 at 0/68B480C8.
```

Should I be worried or is this behavior expected?
### System information
- Kubernetes 1.4.0 (GKE)
- Postgres 9.5.4
- Patroni 1.1
- Full log of `postgres2` after running `patronictl reinit`:
  
  ```
  2016-10-05 09:05:54,107 INFO: Removing data directory: /data/postgresql/data
  2016-10-05 09:05:54,284 INFO: Starting new HTTPS connection (1): kubernetes.default.svc.cluster.local
  
  WARNING:  skipping special file "./.s.PGSQL.5432"
  2016-10-05 09:06:02,481 INFO: replica has been created using basebackup
  2016-10-05 09:06:02,482 INFO: bootstrapped from leader 'postgres0'
  2016-10-05 09:06:02,485 INFO: closed patroni connection to the postgresql cluster
  waiting for server to start....LOG:  database system was interrupted; last known up at 2016-10-05 09:06:00 UTC
  2016-10-05 09:06:02,542 INFO: Lock owner: postgres0; I am postgres2
  2016-10-05 09:06:02,543 INFO: reinitialize in progress
  FATAL:  the database system is starting up
  .FATAL:  the database system is starting up
  .LOG:  entering standby mode
  LOG:  recovered replication state of node 1 to 0/A0D2540
  LOG:  redo starts at 0/88000028
  LOG:  consistent recovery state reached at 0/88000130
  LOG:  database system is ready to accept read only connections
  LOG:  started streaming WAL from primary at 0/89000000 on timeline 9
  done
  server started
  2016-10-05 09:06:05,720 INFO: Starting new HTTPS connection (1): kubernetes.default.svc.cluster.local
  2016-10-05 09:06:12,535 INFO: establishing a new patroni connection to the postgres cluster
  2016-10-05 09:06:12,545 INFO: Lock owner: postgres0; I am postgres2
  2016-10-05 09:06:12,546 INFO: does not have lock
  2016-10-05 09:06:12,548 INFO: no action.  i am a secondary and i am following a leader
  ERROR:  requested starting point 0/69000000 on timeline 7 is not in this server's history
  DETAIL:  This server's history forked from timeline 7 at 0/68B480C8.
  2016-10-05 09:06:22,545 INFO: Lock owner: postgres0; I am postgres2
  2016-10-05 09:06:22,545 INFO: does not have lock
  2016-10-05 09:06:22,546 INFO: no action.  i am a secondary and i am following a leader
  ERROR:  requested starting point 0/69000000 on timeline 7 is not in this server's history
  DETAIL:  This server's history forked from timeline 7 at 0/68B480C8.
  [...]
  ```

**Comment by ants** [comment]
Having extra .history files in the archive can cause this. Check what
timeline master is using and delete all files with a bigger timeline number
from the archive.

I don't have a good idea how we could have a safeguard for this. Maybe have
Patroni store master timeline in the dcs and have a custom restore command
that checks this.

**Comment by alexeyklyukin** [comment]
I find it weird that the replica that just started with the timeline 9 complains about the wrong position on timeline 7. 

Are you sure the message is coming from the replica you've rebuilt and not from some other one?
Does replication actually work (if you create a table on the master - will it propagate to the replica?)
Can you show the pg_controldata output on both the master and the problematic replica?

**Comment by zenitraM** [comment]
Are you using WAL-E on restore_command? - we had a similar issue (inconsistent timelines) after a  wrong fork was written to it, after #329. New nodes would get confused by this .history.

I like the idea of adding a proxy restore_command that is aware of the DCS state

**Comment by irminsul** [comment]
@ants: There are no extra .history files, this is what the replica looks like after a reinit:
```console
root@postgres1-hephaistos-2623968813-f11pt:/data/postgresql/data/pg_xlog# ls -la                                                                                                                                                              
total 32784
drwx------  3 postgres postgres     4096 Oct  7 08:23 .
drwx------ 19 postgres postgres     4096 Oct  7 08:23 ..
-rw-------  1 postgres postgres      295 Oct  7 08:23 00000009.history
-rw-------  1 postgres postgres 16777216 Oct  7 08:23 000000090000000000000095
-rw-------  1 postgres postgres 16777216 Oct  7 08:23 000000090000000000000096
drwx------  2 postgres postgres     4096 Oct  7 08:23 archive_status
```

Surprisingly, if I spin up a replica manually (`pg_basebackup -D /var/lib/postgresql -X stream -d "host=pg-master-hephaistos user=replicator" -R && echo "hot_standby = 'on' >> recovery.conf" && pg_ctl start -D /var/lib/postgresql -l replica.log`), there are no error messages at all:

```console
$ tail -f replica.log 
LOG:  database system was interrupted; last known up at 2016-10-07 08:38:56 UTC
LOG:  entering standby mode
LOG:  redo starts at 0/97000028
LOG:  consistent recovery state reached at 0/970000F8
LOG:  database system is ready to accept read only connections
LOG:  started streaming WAL from primary at 0/98000000 on timeline 9
```

@alexeyklyukin: It's definitly the replica that produces these errors:

```console
$ kubectl logs --since 30s postgres1-hephaistos-2623968813-f11pt
2016-10-07 08:28:12,542 INFO: Lock owner: postgres0; I am postgres1
2016-10-07 08:28:12,543 INFO: does not have lock
2016-10-07 08:28:12,543 INFO: no action.  i am a secondary and i am following a leader
2016-10-07 08:28:22,542 INFO: Lock owner: postgres0; I am postgres1
2016-10-07 08:28:22,543 INFO: does not have lock
2016-10-07 08:28:22,543 INFO: no action.  i am a secondary and i am following a leader
ERROR:  requested starting point 0/69000000 on timeline 7 is not in this server's history
DETAIL:  This server's history forked from timeline 7 at 0/68B480C8.
ERROR:  requested starting point 0/69000000 on timeline 7 is not in this server's history
DETAIL:  This server's history forked from timeline 7 at 0/68B480C8.
2016-10-07 08:28:32,542 INFO: Lock owner: postgres0; I am postgres1
2016-10-07 08:28:32,542 INFO: does not have lock
2016-10-07 08:28:32,543 INFO: no action.  i am a secondary and i am following a leader
```

However, replication does work fine. Changes on the master propagate to the replicas instantly (It's only a test setup, so there is no load on the cluster).

Master:
```console
root@postgres0-hephaistos-3861308076-54ehi:/# pg_controldata /data/postgresql/data 
pg_control version number:            942
Catalog version number:               201510051
Database system identifier:           6330869859674431510
Database cluster state:               in production
pg_control last modified:             Fri Oct  7 07:47:05 2016
Latest checkpoint location:           0/94618B40
Prior checkpoint location:            0/945C4840
Latest checkpoint's REDO location:    0/94618B08
Latest checkpoint's REDO WAL file:    000000090000000000000094
Latest checkpoint's TimeLineID:       9
Latest checkpoint's PrevTimeLineID:   9
Latest checkpoint's full_page_writes: on
Latest checkpoint's NextXID:          0/48997
Latest checkpoint's NextOID:          49488
Latest checkpoint's NextMultiXactId:  62
Latest checkpoint's NextMultiOffset:  123
Latest checkpoint's oldestXID:        616
Latest checkpoint's oldestXID's DB:   1
Latest checkpoint's oldestActiveXID:  48997
Latest checkpoint's oldestMultiXid:   1
Latest checkpoint's oldestMulti's DB: 1
Latest checkpoint's oldestCommitTsXid:42441
Latest checkpoint's newestCommitTsXid:48996
Time of latest checkpoint:            Fri Oct  7 07:46:57 2016
Fake LSN counter for unlogged rels:   0/1
Minimum recovery ending location:     0/0
Min recovery ending loc's timeline:   0
Backup start location:                0/0
Backup end location:                  0/0
End-of-backup record required:        no
wal_level setting:                    logical
wal_log_hints setting:                on
max_connections setting:              100
max_worker_processes setting:         10
max_prepared_xacts setting:           0
max_locks_per_xact setting:           64
track_commit_timestamp setting:       on
Maximum data alignment:               8
Database block size:                  8192
Blocks per segment of large relation: 131072
WAL block size:                       8192
Bytes per WAL segment:                16777216
Maximum length of identifiers:        64
Maximum columns in an index:          32
Maximum size of a TOAST chunk:        1996
Size of a large-object chunk:         2048
Date/time type storage:               64-bit integers
Float4 argument passing:              by value
Float8 argument passing:              by value
Data page checksum version:           1
```

Slave:
```console
root@postgres1-hephaistos-2623968813-f11pt:/# pg_controldata /data/postgresql/data
pg_control version number:            942
Catalog version number:               201510051
Database system identifier:           6330869859674431510
Database cluster state:               in archive recovery
pg_control last modified:             Fri Oct  7 07:54:32 2016
Latest checkpoint location:           0/946C69C8
Prior checkpoint location:            0/94618B40
Latest checkpoint's REDO location:    0/946C6990
Latest checkpoint's REDO WAL file:    000000090000000000000094
Latest checkpoint's TimeLineID:       9
Latest checkpoint's PrevTimeLineID:   9
Latest checkpoint's full_page_writes: on
Latest checkpoint's NextXID:          0/49031
Latest checkpoint's NextOID:          49488
Latest checkpoint's NextMultiXactId:  62
Latest checkpoint's NextMultiOffset:  123
Latest checkpoint's oldestXID:        616
Latest checkpoint's oldestXID's DB:   1
Latest checkpoint's oldestActiveXID:  49031
Latest checkpoint's oldestMultiXid:   1
Latest checkpoint's oldestMulti's DB: 1
Latest checkpoint's oldestCommitTsXid:42441
Latest checkpoint's newestCommitTsXid:49030
Time of latest checkpoint:            Fri Oct  7 07:51:57 2016
Fake LSN counter for unlogged rels:   0/1
Minimum recovery ending location:     0/946EE828
Min recovery ending loc's timeline:   9
Backup start location:                0/0
Backup end location:                  0/0
End-of-backup record required:        no
wal_level setting:                    logical
wal_log_hints setting:                on
max_connections setting:              100
max_worker_processes setting:         10
max_prepared_xacts setting:           0
max_locks_per_xact setting:           64
track_commit_timestamp setting:       on
Maximum data alignment:               8
Database block size:                  8192
Blocks per segment of large relation: 131072
WAL block size:                       8192
Bytes per WAL segment:                16777216
Maximum length of identifiers:        64
Maximum columns in an index:          32
Maximum size of a TOAST chunk:        1996
Size of a large-object chunk:         2048
Date/time type storage:               64-bit integers
Float4 argument passing:              by value
Float8 argument passing:              by value
Data page checksum version:           1
```

Patroni config:
```yaml
# The following settings are specified by environment variables:
# PATRONI_POSTGRESQL_DATA_DIR = $(PGROOT)/data
# PATRONI_CONFIG = /config/postgres.yml
# PATRONI_NAME = postgres[0,1,2]
# PATRONI_SCOPE = hephaistos
# PATRONI_POSTGRESQL_CONNECT_ADDRESS = $(POD_IP):5432
# PATRONI_RESTAPI_CONNECT_ADDRESS = $(POD_IP):8008
# PATRONI_REPLICATION_PASSWORD = <secret>
# PATRONI_SUPERUSER_PASSWORD = <secret>
# PATRONI_admin_PASSWORD = <secret>

restapi:
  listen: 0.0.0.0:8008

etcd:
  host: etcd.default.svc.cluster.local:2379

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: false
      use_slots: true
      parameters:
        wal_level: logical
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 10
        max_replication_slots: 10
        wal_log_hints: "on"
        max_worker_processes: 10
        shared_preload_libraries: "pglogical"
        track_commit_timestamp: on

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
  - host replication pghoard 0.0.0.0/0 md5

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
    superuser:
      username: postgres
  callbacks:
    on_start: /callback_role.py
    on_stop: /callback_role.py
    on_restart: /callback_role.py
    on_role_change: /callback_role.py
  parameters:
    unix_socket_directories: '.'
```

@zenitraM: I am using replication slots to control WAL retention on the master. Continuous archiving and WAL-E are not part of my setup. I am using [pghoard](https://github.com/ohmu/pghoard) for PITR though.
