### ISSUE TITLE
Unclear how archive_command is configured

### ISSUE THREAD

**Issue by ClaudiuPID** [zalando/patroni#430]
Hi,

I have 2 clusters with patroni, one is 1.2.3 and the other 1.2.4 and for both I have the bellow problem.
I am using 3 servers and archive_command should be different on all of them but instead I have the same command on all.
```archive_command = 'mkdir -p /var/lib/postgresql/wal_archive && test ! -f /var/lib/postgresql/wal_archive/%f && cp /var/lib/postgresql/data/sql1/%p /var/lib/postgresql/wal_archive/%f'```

Partial extract from patroni.yml:
```
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: True
      parameters:
        archive_mode: "on"
        wal_level: hot_standby
        archive_command: mkdir -p /var/lib/postgresql/wal_archive && test ! -f /var/lib/postgresql/wal_archive/%f && cp /var/lib/postgresql/data/sqlX/%p /var/lib/postgresql/wal_archive/%f
```
Where sqlX is a match for each server and that is sql{1,2,3}.

If I failover the master from sql1 to any other sql node, I will get errors for archive_command since it is trying to copy data from /var/lib/postgresql/data/sql1/pg_xlog/ and never from itself. Where sql1 is a remote host now.
And in my case /var/lib/postgresql/wal_archive is a glusterfs mount point.

I don't recall having this problem when I was using version 0.9x, but I might be wrong since I do not remember manually failing over.
Am I missing something?

**Comment by CyberDem0n** [comment]
Hi @ClaudiuPID 

1. `bootstrap.dcs` section is written into DCS only once and if you later (for existing cluster) change it in configuration file it wont take any effect.
2. Everything stored in DCS would have the same values on all cluster nodes. I.e. if DCS contains `/var/lib/postgresql/data/sql1/` that means all it would be the same in archive_command on all cluster nodes.

If you need to change some configuration parameters in DCS, you have to use [REST API](http://patroni.readthedocs.io/en/latest/dynamic_configuration.html#rest-api)

And if you want to have a different archive_command on the nodes, you need to set it's value in the configuration file on every node. This way it will work as on v0.9.
```yaml
postgresql:
  parameters:
    archive_command: 'mkdir -p /var/lib/postgresql/wal_archive && test ! -f /var/lib/postgresql/wal_archive/%f && cp /var/lib/postgresql/data/sqlX/%p /var/lib/postgresql/wal_archive/%f'
```

And probably remove archive_command from DCS config:
```bash
$ curl -s -XPATCH -d \
        '{"postgresql":{"parameters":{"archive_command":null}}}' \
        http://localhost:8008/config
```

P.S. your archive_command is broken. cp command is not doing fsync, so there is no guaranty that data was really written on disk.
