### ISSUE TITLE
add ability to have custom postgresql.conf. pg_hba.conf

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#53]
Add the following lines to patroni.yml:

postgresql_config_file: /path/to/custom/file
pg_hba_file: /path/to/custom/file

If present, these configuration variables will cause the files named to be copied to the data directory after it is initialized and before PostgreSQL is started up.

A TODO for me.

**Comment by jberkus** [comment]
Yes, I realize that Patroni already has a way to take config settings for postgres in the patroni.yml file.  However, the formatting and organization of these is rather painful if you have a large number of special config settings.

**Comment by CyberDem0n** [comment]
Actually it's already possible to specify locations for config file and hba file with using standard options:
```yaml
postgresql:
  parameters:
    hba_file: /path/to/custom/pg_hba.conf
    config_file: /path/to/custom/postgresql.conf
```
But it wont copy these file to the data directory.
