### ISSUE TITLE
EtcdKeyNotFound: Key not found : /service/mycluster/leader

### ISSUE THREAD

**Issue by Valeriyy** [zalando/patroni#534]
Hello! I want to run failover on 2 nodes, but I have error:

> 2017-10-02 18:00:18,703 INFO: Selected new etcd server http://127.0.0.1:2379
> 2017-10-02 18:00:19,216 ERROR:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 329, in wrapper
>     retval = func(self, *args, **kwargs) is not None
>   File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 511, in delete_leader
>     return self._client.delete(self.leader_path, prevValue=self._name)
>   File "/usr/lib/python2.7/site-packages/etcd/client.py", line 645, in delete
>     self.key_endpoint + key, self._MDELETE, params=kwds)
>   File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 211, in api_execute
>     return self._handle_server_response(response)
>   File "/usr/lib/python2.7/site-packages/etcd/client.py", line 987, in _handle_server_response
>     etcd.EtcdError.handle(r)
>   File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 306, in handle
>     raise exc(msg, payload)
> EtcdKeyNotFound: Key not found : /service/mycluster/leader
> Traceback (most recent call last):
>   File "/bin/patroni", line 11, in <module>
>     load_entry_point('patroni==1.3.4', 'console_scripts', 'patroni')()
>   File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 173, in main
>     return patroni_main()
>   File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 142, in patroni_main
>     patroni.run()
>   File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 114, in run
>     logger.info(self.ha.run_cycle())
>   File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1070, in run_cycle
>     info = self._run_cycle()
>   File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1018, in _run_cycle
>     self.dcs.initialize(create_new=(self.cluster.initialize is None), sysid=self.state_handler.sysid)
>   File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 400, in sysid
>     data = self.controldata()
>   File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1214, in controldata
>     env={'LANG': 'C', 'LC_ALL': 'C', 'PATH': os.environ['PATH']})
>   File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
>     process = Popen(stdout=PIPE, *popenargs, **kwargs)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> 

How I can configure etcd on 2 nodes to solve this problem?
I just intalled etcd from YUM and start command:
> service etcd start

My patroni config:

> name: server1
> scope: &scope mycluster
> 
> etcd:
>   host: 127.0.0.1:2379
> 
> restapi:
>   listen: 0.0.0.0:8080
>   connect_address: 172.16.148.23:8080
> 
> bootstrap:
>   dcs:
>     ttl: &ttl 30
>     loop_wait: &loop_wait 10
>     maximum_lag_on_failover: 1048576 # 1 megabyte in bytes
>     postgresql:
>       use_pg_rewind: true
>       use_slots: true
>       parameters:
>         archive_mode: "on"
>         wal_level: hot_standby
>         archive_command: mkdir -p ../wal_archive && cp %p ../wal_archive/%f
>         max_wal_senders: 10
>         wal_keep_segments: 8
>         archive_timeout: 1800s
>         max_replication_slots: 5
>         hot_standby: "on"
>         wal_log_hints: "on"
> 
> pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
>   - host replication replicator 192.168.0.0/16 md5
>   - host all all 0.0.0.0/0 md5
> 
> postgresql:
>   listen: 0.0.0.0:5432
>   connect_address: 172.16.148.23:5432
>   data_dir: /var/lib/pgsql/9.6/data
>   pg_rewind:
>     username: superuser
>     password: 12345
>   pg_hba:
>   - host all all 0.0.0.0/0 md5
>   - hostssl all all 0.0.0.0/0 md5
>   replication:
>     username: replicator
>     password: 12345
>     network:  192.168.0.0/16
>   superuser:
>     username: superuser
>     password: 12345
>   admin:
>     username: admin
>     password: 12345
>   restore: /usr/bin/patroni_wale_restore

**Comment by alexeyklyukin** [comment]
>File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 400, in sysid
data = self.controldata()
File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1214, in controldata
env={'LANG': 'C', 'LC_ALL': 'C', 'PATH': os.environ['PATH']})
File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
process = Popen(stdout=PIPE, *popenargs, **kwargs)
File "/usr/lib64/python2.7/subprocess.py", line 711, in init
errread, errwrite)
File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

It looks like Patroni tried to execute pg_controldata in order to read the sysid of the cluster and failed with "no such file or directory". Are your PostgreSQL binaries  in the `PATH`? Alternatively, you can make Patroni aware of them using the `bin_dir` option (on the same level as your `data_dir` one), pointing to the directory containing your PostgreSQL binaries.

**Comment by Valeriyy** [comment]
Thank you! It really was a problem.
I have next problem. Patroni try starting postgresql in standby mode. 
This is the first node in the cluster, what patroni must run in master mode, but patroni created config **/var/lib/pgsql/9.6/data/recovery.conf**:
> primary_slot_name = 'site2_appdb01'
> standby_mode = 'on'
> recovery_target_timeline = 'latest'

And postgresql unsuccessfully trying start in standby mode:

> < 2017-10-03 12:24:35.591 MSK > LOG:  database system was interrupted while in recovery at log time 2017-10-02 17:59:31 MSK
> < 2017-10-03 12:24:35.591 MSK > HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
> < 2017-10-03 12:24:35.592 MSK > FATAL:  the database system is starting up
> < 2017-10-03 12:24:35.598 MSK > WARNING:  recovery command file "recovery.conf" specified neither primary_conninfo nor restore_command
> < 2017-10-03 12:24:35.598 MSK > HINT:  The database server will regularly poll the pg_xlog subdirectory to check for files placed there.
> < 2017-10-03 12:24:35.598 MSK > LOG:  entering standby mode
> < 2017-10-03 12:24:35.598 MSK > FATAL:  the database system is starting up
> < 2017-10-03 12:24:35.599 MSK > WARNING:  WAL was generated with wal_level=minimal, data may be missing
> < 2017-10-03 12:24:35.599 MSK > HINT:  This happens if you temporarily set wal_level=minimal without taking a new base backup.
> < 2017-10-03 12:24:35.599 MSK > FATAL:  hot standby is not possible because wal_level was not set to "replica" or higher on the master server
> < 2017-10-03 12:24:35.599 MSK > HINT:  Either set wal_level to "replica" on the master, or turn off hot_standby here.
> < 2017-10-03 12:24:35.600 MSK > LOG:  startup process (PID 17038) exited with exit code 1
> < 2017-10-03 12:24:35.600 MSK > LOG:  aborting startup due to startup process failure
> < 2017-10-03 12:24:35.601 MSK > LOG:  database system is shut down

**Comment by Valeriyy** [comment]
My patroni config:

```
name: site2-appdb01
scope: &scope site2-appdb

etcd:
  host: 127.0.0.1:2379

restapi:
  listen: 0.0.0.0:8080
  connect_address: 172.16.148.23:8080
# auth: 'username:{{ patroni_rest_password }}'

bootstrap:
  dcs:
    ttl: &ttl 30
    loop_wait: &loop_wait 10
    maximum_lag_on_failover: 1048576 # 1 megabyte in bytes
    postgresql:
      use_pg_rewind: true
#      use_slots: true
      parameters:
#        archive_mode: "on"
#        wal_level: hot_standby
#        archive_command: mkdir -p ../wal_archive && cp %p ../wal_archive/%f
#        max_wal_senders: 10
#        wal_keep_segments: 8
#        archive_timeout: 1800s
#        max_replication_slots: 5
#        hot_standby: "on"
#        wal_log_hints: "on"

pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host    all             all             172.16.148.0/24         md5
  - host    all             all             172.16.149.0/24         md5
  - host    all             all             127.0.0.1/32            md5
  - host    replication     postgres        172.16.148.0/24         md5
  - host    replication     postgres        172.16.149.0/24         md5

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 172.16.148.23:5432
  data_dir: /var/lib/pgsql/9.6/data
  pg_rewind:
    username: superuser
    password: 1q2W3e4r
  pg_hba:
  - host    all             all             172.16.148.0/24         md5
  - host    all             all             172.16.149.0/24         md5
  - host    all             all             127.0.0.1/32            md5
  - host    replication     postgres        172.16.148.0/24         md5
  - host    replication     postgres        172.16.149.0/24         md5
  replication:
    username: replicator
    password: 1q2W3e4r
    network:  192.168.0.0/16
  superuser:
    username: superuser
    password: 1q2W3e4r
  admin:
    username: admin
    password: 1q2W3e4r
  restore: /usr/bin/patroni_wale_restore
```
