### ISSUE TITLE
When using custom bootstrap, Patroni does not write a postgresql.conf during startup

### ISSUE THREAD

**Issue by snooc** [zalando/patroni#535]
When using Patroni with a custom bootstrap method, Patroni does not write a postgresql.conf until the server has started. The postgresql.conf file is then generated and postgres is reloaded.

It looks like the cause of this is: https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L1110

Is this expected behavior? I am using a custom bootstrap method to restore from backups and expected patroni to start up postgres with the configuration specified in YAML, not after a reload. Some of the configuration options that I have are for a custom extension that cannot be reloaded and require a full server restart.

Here is the log output:

```
...CUSTOM BOOTSTRAP FINISHES RUNNING. CUSTOM BOOTSTRAP RUNS INITDB, STARTS SERVER, LOADS PG_DUMP, STOPS SERVER

2017-10-04 00:40:45,990 INFO: postmaster pid=839
< 2017-10-04 00:40:46.006 UTC > LOG:  database system was shut down at 2017-10-04 00:40:44 UTC
< 2017-10-04 00:40:46.008 UTC > LOG:  MultiXact member wraparound protections are now enabled
< 2017-10-04 00:40:46.012 UTC > LOG:  autovacuum launcher started
< 2017-10-04 00:40:46.012 UTC > LOG:  database system is ready to accept connections
2017-10-04 00:40:47,047 INFO: establishing a new patroni connection to the postgres cluster
2017-10-04 00:40:47,069 INFO: running post_bootstrap
server signaled
< 2017-10-04 00:40:47.077 UTC > LOG:  received SIGHUP, reloading configuration files
2017-10-04 00:40:48,080 INFO: closed patroni connection to the postgresql cluster
2017-10-04 00:40:48,091 INFO: establishing a new patroni connection to the postgres cluster
Database started
2017-10-04 00:40:48,109 INFO: initialized a new cluster
```

**Comment by CyberDem0n** [comment]
Hi @snooc,

Can you please post a config file here?

**Comment by snooc** [comment]
Not a problem @CyberDem0n 

```
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeouts: 10
    maximum_lag_on_failover: 104857600
    postgresql:
      parameters:
        hot_standby: on
        max_connections: 100
        max_replication_slots: 5
        max_wal_senders: 5
        wal_keep_segments: 8
        wal_level: hot_standby
        wal_log_hints: on
        log_min_messages: warning
        client_min_messages: notice
      use_pg_rewind: false
      use_slots: true
    retry_timeout: 15
    ttl: 15
  method: custom_initdb
  custom_initdb:
    command: /etc/patroni/bootstrap.sh
etcd:
  host: "etcd:2379"
  scope: system-db
  ttl: 15
postgresql:
  scope: system-db
  name: 49299a830858
  listen: 0.0.0.0:5432
  connect_address: "49299a830858:5432"
  data_dir: /var/lib/pgsql/9.6/data
  parameters:
    ssl: on
    ssl_cert_file: /etc/postgresql/tls/server.crt
    ssl_key_file: /etc/postgresql/tls/server.key

    log_destination: stderr
    logging_collector: off

    idle_in_transaction_session_timeout: 60000
    lock_timeout: 5000

    shared_preload_libraries: "some_custom_extension"
    "some_custom_extension.some_setting": "some-setting-value"
    "some_custom_extension.another_setting": false
  pg_hba:
    - local all all peer
    - hostssl all postgres 127.0.0.1/32 md5
    - hostssl all postgres 0.0.0.0/0 reject
    - hostssl replication replicator 0.0.0.0/0 md5
    - hostssl all all 0.0.0.0/0 md5
  authentication:
    replication:
      username: replicator
      password: some-password
    superuser:
      username: postgres
      password: some-password
  create_replica_method:
    - basebackup
  callbacks:
    on_reload: /etc/patroni/default_callback.sh
    on_restart: /etc/patroni/default_callback.sh
    on_role_change: /etc/patroni/default_callback.sh
    on_start: /etc/patroni/default_callback.sh
    on_stop: /etc/patroni/default_callback.sh
scope: system-db
restapi:
  connect_address: "49299a830858:8008"
  listen: "0.0.0.0:8008"
  authentication:
    username: "admin"
    password: "secret-password"
watchdog:
  mode: off
```
