### ISSUE TITLE
pass postgresql connect_address to callbacks

### ISSUE THREAD

**Issue by schmitch** [zalando/patroni#550]
it would be good to dynamically create consul services, to pass the connect_address of postgresql to the callback scripts, so that it will be easier to make the postgresql master available over consul dns.

**Comment by CyberDem0n** [comment]
Hi @schmitch ,

sorry for being so late, but actually you can solve this problem on the level of patroni config file.
Just pass connect_address as an additional argument:
```yaml
postgresql:
  callbacks:
    on_start: '/my_callback.sh connect-address:port'
    on_stop: '/my_callback.sh connect-address:port'
    on_role_change: '/my_callback.sh connect-address:port'
```
