### ISSUE TITLE
system ID mismatch using Consul

### ISSUE THREAD

**Issue by hlx98007** [zalando/patroni#575]
Hi, when try to bootstrap a second postgres instance to join the existing pg cluster (has only 1 node), patroni complains `2017-12-12 21:16:01,073 CRITICAL: system ID mismatch, node postgresql2 belongs to a different cluster: 6497216458191333666 != 6497220080226496012`

Here is our postgres.yml:
```
dcs_api: 'consul://x.x.x.x:8500'
namespace: /service/
scope: example
name: postgresql1 # (1, 2, 3 here for different nodes)

restapi:
  listen: <eth0_ip>:8008    # rest api should be accessible remotely or locally?

consul:
  host: x.x.x.x
  port: 8500

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
        max_connections: 500
        shared_buffers: 1GB
        huge_pages: off
        temp_buffers: 128MB
        work_mem: 16MB
        maintenance_work_mem: 256MB
        dynamic_shared_memory_type: posix
        vacuum_cost_limit: 2000
        bgwriter_delay: 20ms
        effective_io_concurrency: 2
        wal_level: logical
        checkpoint_timeout: 15min
        max_wal_size: 50GB
        min_wal_size: 1GB
        checkpoint_completion_target: 0.8
        archive_mode: on
        archive_command: '/bin/true'
        max_wal_senders: 8
        max_replication_slots: 8
        track_commit_timestamp: on
        hot_standby: on
        hot_standby_feedback: on
        random_page_cost: 1.2
        effective_cache_size: 2GB
        default_statistics_target: 1000
        logging_collector: on
        max_locks_per_transaction: 256
        hba_file: /etc/postgresql/9.6/main/pg_hba.conf
        ident_file: /etc/postgresql/9.6/main/pg_ident.conf

  initdb:
    - encoding: UTF8

  pg_hba:
    - local   all             postgres                                  peer
    - local   all             all                                       trust
    - host    all             all             10.0.0.0/8                md5
    - host    replication     repuser         10.0.0.0/8                md5

postgresql:
  listen: <local_eth0_ip>:5432
  connect_address: <eth0_ip>:5432
  data_dir: /var/lib/postgresql/9.6/main
  pgpass: /tmp/pgpass0
  authentication:
    superuser:
      username: postgres
      password: pg_password
    replication:
      username: repuser
      password: rp_password
  parameters:
    unix_socket_directories: '.'
  custom_conf: /etc/postgresql/9.6/main/postgresql.conf

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
```

I understand there are some parameters not needed for the configuration however we found a few issues:
1. 1.3.6 of Patroni won't honor some config such as `max_locks_per_transaction: 256` so we had to change https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L217 to ` parameters = config['parameter'].copy()`. Otherwise postgresql won't start.
2. Once postgres1 is setup, using the same yml configuration for postgres2 and execute `patroni /etc/patroni/postgres.yml` will lead to `system ID mismatch` error.
