### ISSUE TITLE
reinit command doesn't take into account the node name

### ISSUE THREAD

**Issue by kostiantyn-nemchenko** [zalando/patroni#624]
Hi,

I've noticed that `patronictl reinit` command does not honor cluster member name and simply bootstraps itself if the role is secondary.

Steps to reproduce the issue:
1) Set up 3 nodes cluster.
2) Log in to the 1st secondary node and try to reinitialize the 2nd one.
```
postgres@node-01:~$ date
Tue Feb 13 09:31:26 UTC 2018

postgres@node-01:~$ patronictl -c /etc/patroni/node-01.yml reinit main
+---------+---------+---------------+--------+---------+-----------+
| Cluster |  Member |      Host     |  Role  |  State  | Lag in MB |
+---------+---------+---------------+--------+---------+-----------+
|   main  | node-01 | 192.168.33.10 |        | running |       0.0 |
|   main  | node-02 | 192.168.33.11 |        | running |       0.0 |
|   main  | node-03 | 192.168.33.12 | Leader | running |       0.0 |
+---------+---------+---------------+--------+---------+-----------+
Which member do you want to reinitialize [node-02, node-03, node-01]? []: node-02
Are you sure you want to reinitialize members node-02? [y/N]: y
Success: reinitialize for member node-02
```
3) Check out log files locally.
```
Feb 13 09:31:34 node-01 patroni[6147]: 2018-02-13 09:31:34.813 UTC [6711] LOG:  database system is shut down
Feb 13 09:31:34 node-01 patroni[6147]: 2018-02-13 09:31:34,817 INFO: Removing data directory: /var/lib/postgresql/10/main
Feb 13 09:31:35 node-01 patroni[6147]: 2018-02-13 09:31:35,418 INFO: replica has been created using basebackup
Feb 13 09:31:35 node-01 patroni[6147]: 2018-02-13 09:31:35,419 INFO: bootstrapped from leader 'node-03'
Feb 13 09:31:35 node-01 patroni[6147]: 2018-02-13 09:31:35,422 INFO: closed patroni connection to the postgresql cluster
```
4) Check out files creation time and server start time.
```
postgres@node-01:~$ psql -c "select access, modification, change from pg_stat_file('PG_VERSION');"
         access         |      modification      |         change         
------------------------+------------------------+------------------------
 2018-02-13 09:31:35+00 | 2018-02-13 09:31:35+00 | 2018-02-13 09:31:35+00
(1 row)

postgres@node-01:~$ psql -c "select pg_postmaster_start_time()"
   pg_postmaster_start_time    
-------------------------------
 2018-02-13 09:31:35.485135+00
(1 row)
```

There's nothing special in log files on the target 'node-02' regarding its re-initialization.

Is this expected, or is it a bug?

**Comment by CyberDem0n** [comment]
That is very strange.
Can you please show configuration files from all nodes?
Especially I am interested in `restapi` section.

**Comment by kostiantyn-nemchenko** [comment]
@CyberDem0n thanks for the response.

> Especially I am interested in restapi section.

The `restapi` section is the same on all cluster members:
```yaml
restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008
```
> Can you please show configuration files from all nodes?

Here are configuration files from all nodes:
<details>
 <summary>node-01</summary>

```yaml
scope: main
namespace: /service/
name: node-01

restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008

consul:
  host: 127.0.0.1:8500
  port: 8500
  scheme: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: False
    postgresql:
      use_pg_rewind: True
      use_slots: True
      parameters:
        max_connections: 1000
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: 'replica'
        wal_log_hints: 'on'
        track_commit_timestamp: 'off'
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_segments: 0

  initdb:
    - encoding: UTF8
    - data-checksums

  users:
    postgres:
      password: supersecretpostgrespasswd
      options:
        - superuser
    replicator:
      password: repuserpasswd
      options:
        - replication

postgresql:
  authentication:
    superuser:
      username: postgres
      password: supersecretpostgrespasswd
    replication:
      username: replicator
      password: repuserpasswd
  callbacks:
  connect_address: 192.168.33.10:5432
  create_replica_methods:
    - basebackup
  data_dir: /var/lib/postgresql/10/main
  config_dir: /etc/postgresql/10/main
  bin_dir: /usr/lib/postgresql/10/bin
  listen: 0.0.0.0:5432
  use_unix_socket: True
  pgpass: /var/lib/postgresql/.pgpass
  parameters:
    unix_socket_directories: '/var/run/postgresql'
  pg_hba:
    - local all postgres  peer
    - local all all  peer
    - host all all 0.0.0.0/0 md5
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 192.168.33.0/24 md5
  pg_ctl_timeout: 60
  use_pg_rewind: true
  pg_rewind:
    username: postgres
    password: supersecretpostgrespasswd
  remove_data_directory_on_rewind_failure: False
    
watchdog:
  mode: automatic 
  device: /dev/watchdog
  safety_margin: -1

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```
</details>

<details>
 <summary>node-02</summary>

```yaml
scope: main
namespace: /service/
name: node-02

restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008

consul:
  host: 127.0.0.1:8500
  port: 8500
  scheme: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: False
    postgresql:
      use_pg_rewind: True
      use_slots: True
      parameters:
        max_connections: 1000
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: 'replica'
        wal_log_hints: 'on'
        track_commit_timestamp: 'off'
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_segments: 0

  initdb:
    - encoding: UTF8
    - data-checksums

  users:
    postgres:
      password: supersecretpostgrespasswd
      options:
        - superuser
    replicator:
      password: repuserpasswd
      options:
        - replication

postgresql:
  authentication:
    superuser:
      username: postgres
      password: supersecretpostgrespasswd
    replication:
      username: replicator
      password: repuserpasswd
  callbacks:
  connect_address: 192.168.33.11:5432
  create_replica_methods:
    - basebackup
  data_dir: /var/lib/postgresql/10/main
  config_dir: /etc/postgresql/10/main
  bin_dir: /usr/lib/postgresql/10/bin
  listen: 0.0.0.0:5432
  use_unix_socket: True
  pgpass: /var/lib/postgresql/.pgpass
  parameters:
    unix_socket_directories: '/var/run/postgresql'
  pg_hba:
    - local all postgres  peer
    - local all all  peer
    - host all all 0.0.0.0/0 md5
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 192.168.33.0/24 md5
  pg_ctl_timeout: 60
  use_pg_rewind: true
  pg_rewind:
    username: postgres
    password: supersecretpostgrespasswd
  remove_data_directory_on_rewind_failure: False
    
watchdog:
  mode: automatic 
  device: /dev/watchdog
  safety_margin: -1

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```
</details>

<details>
 <summary>node-03</summary>

```yaml
scope: main
namespace: /service/
name: node-03

restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008

consul:
  host: 127.0.0.1:8500
  port: 8500
  scheme: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: False
    postgresql:
      use_pg_rewind: True
      use_slots: True
      parameters:
        max_connections: 1000
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: 'replica'
        wal_log_hints: 'on'
        track_commit_timestamp: 'off'
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_segments: 0

  initdb:
    - encoding: UTF8
    - data-checksums

  users:
    postgres:
      password: supersecretpostgrespasswd
      options:
        - superuser
    replicator:
      password: repuserpasswd
      options:
        - replication

postgresql:
  authentication:
    superuser:
      username: postgres
      password: supersecretpostgrespasswd
    replication:
      username: replicator
      password: repuserpasswd
  callbacks:
  connect_address: 192.168.33.12:5432
  create_replica_methods:
    - basebackup
  data_dir: /var/lib/postgresql/10/main
  config_dir: /etc/postgresql/10/main
  bin_dir: /usr/lib/postgresql/10/bin
  listen: 0.0.0.0:5432
  use_unix_socket: True
  pgpass: /var/lib/postgresql/.pgpass
  parameters:
    unix_socket_directories: '/var/run/postgresql'
  pg_hba:
    - local all postgres  peer
    - local all all  peer
    - host all all 0.0.0.0/0 md5
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 192.168.33.0/24 md5
  pg_ctl_timeout: 60
  use_pg_rewind: true
  pg_rewind:
    username: postgres
    password: supersecretpostgrespasswd
  remove_data_directory_on_rewind_failure: False
    
watchdog:
  mode: automatic 
  device: /dev/watchdog
  safety_margin: -1

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```
</details>
