### ISSUE TITLE
Feature request: do not delete PGDATA

### ISSUE THREAD

**Issue by uspen** [zalando/patroni#625]
Hello!

It would be nice to have an option for create_replica_metod like "do not delete PGDATA". We use pgbackrest with the option --delta and it's very fast.

**Comment by alexeyklyukin** [comment]
Good idea. PRs are welcome :-)

**Comment by uspen** [comment]
Sory, i dont know python

**Comment by bradnicholson** [comment]
I'm have need of this and am willing to tackle it, but it's not clear to me the best way to do so.  Looking for some pointers if you have any.

I was thinking of adding a `keep_data` parameter to custom replica creation method like this:

```
postgresql:
    create_replica_method:
        - pgBackRest
        - basebackup
    pgBackReset:
        command: pgBackRest_restore
        keep_data: True
```

But the issue I'm seeing the code to delete the data dir is being called prior to any of the replica creation logic here:
https://github.com/zalando/patroni/blob/master/patroni/ha.py#L886

Not to mention the ha object has no knowledge of the Postgres section of the config.

Any ideas?

**Comment by sharmay** [comment]
New to patroni and my first set of changes are available in https://github.com/sharmay/patroni

```
postgresql:
    create_replica_method:
        - pgBackRest
        - basebackup
    pgBackReset:
        command: /usr/bin/pgbacktest --stanza=mydb --delta restore
        keep_data: True
        no_params: True
```

PR will be created after further testing. 

Please let me know your comment.

Give it a try @bradnicholson @uspen

**Comment by CyberDem0n** [comment]
@sharmay there is no need to reinvent the weel.

Just wrap `pgBackRest` into a simple shell script, which will skip all unknown arguments.

Not deleting the PGDATA is a different story, and deserves working on it.

**Comment by sharmay** [comment]
@CyberDem0n will wrap it in a script.

Just for my knowledge what are the benefits of wrapping in a script ?

**Comment by CyberDem0n** [comment]
> what are the benefits of wrapping in a script?

The biggest benefit is: it works without any changes in Patroni :)
If you really want it in the Patroni code (skipping unwanted arguments), please go ahead and implement it.

**Comment by sharmay** [comment]
How about this approach ?
```
postgresql:
    create_replica_method:
        - pgBackRest
        - basebackup
    pgBackReset:
        command: /usr/bin/pgbacktest
        args:
            - "--stanza=mydb"
            - "--delta"
            - "restore"
        keep_data: True
        no_params: True
```
- Add Args section to handle command arguments.
- Keep args pristine as some args may be command to custom backup prog and do not require -- prefix
- Extra args are still controlled using no_params flag
