### ISSUE TITLE
Make Deletion of recovery.conf Optional

### ISSUE THREAD

**Issue by bradnicholson** [zalando/patroni#637]
When bootstrapping a cluster with the custom_replica creation, Patroni automatically deletes the  recovery.conf if it exists.  

When bootstrapping a replica from a pgBackRest restore, we would like to let pgBackRest generate the appropriate recovery.conf and have Patroni leave it in place.

To accomplish that, I'd like to add an optional parameter called `keep_existing_recovery_conf` (as below).  If that parameter is present and set to `True`, skip the deletion of the recovery.conf

```
bootstrap:
    method: <custom_bootstrap_method_name>
    <custom_bootstrap_method_name>:
        command: <path_to_custom_bootstrap_script> [param1 [, ...]]
        keep_existing_recovery_conf: True
```

**Comment by CyberDem0n** [comment]
It's very easy to implement, but should we really to that?
Patroni already gives you all control over recovery.conf, it is possible to configure what it will put inside of it after running custom bootstrap script:

```yaml
bootstrap:
    method: <custom_bootstrap_method_name>
    <custom_bootstrap_method_name>:
        command: <path_to_custom_bootstrap_script> [param1 [, ...]]
        recovery_conf:
            recovery_target_action: promote
            recovery_target_timeline: latest
            restore_command: <method_specific_restore_command>
```

Basically you can build any custom recovery.conf just by adding more options into `bootstrap.<custom_bootstrap_method_name>.recovery_conf`
