### ISSUE TITLE
kubernetes example does not start

### ISSUE THREAD

**Issue by davecramer** [zalando/patroni#641]
All three nodes are 'waiting for leader to bootstrap'

**Comment by CyberDem0n** [comment]
Hi Dave,

I think you have some k8s objects left from the previous attempt, for example `ComfigMap patronidemo-config`

This ConfigMap contains information that patronidemo cluster was already initialized. 

`$ kubectl get cm patronidemo-config -o yaml` will show you something like:
```yaml
apiVersion: v1
kind: ConfigMaps
metadata:
  annotations:
    config: '{"postgresql":{"use_pg_rewind":true}}'
    initialize: "6535013044642451482"
  creationTimestamp: 2018-03-20T13:08:13Z
  labels:
    application: patroni
    cluster-name: patronidemo
```

If you see there `metadata.annotations.initialize`, that means cluster was already initialized and Patroni will not run initdb the second time.


Just remove it and it will start working: `kubectl delete cm patronidemo-config`
