### ISSUE TITLE
Problem starting sample configuration with "patroni postgres0.yml"

### ISSUE THREAD

**Issue by malinkalive** [zalando/patroni#648]
Hi all,
when I am running patroni with 

```
...
bootstrap:
  dcs:
    ttl: 30 #line 13
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        max_wal_senders: 5
        max_replication_slots: 5
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: 600s
        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
      recovery_conf: #line29
        restore_command: cp ../wal_archive/%f %p...
```
i`m getting error like:
```
mar 26 19:57:06 zabbix1 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
mar 26 19:57:06 zabbix1 patroni[4005]: Traceback (most recent call last):
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/local/bin/patroni", line 11, in <module>
mar 26 19:57:06 zabbix1 patroni[4005]:     sys.exit(main())
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/local/lib/python2.7/dist-packages/patroni/__in
mar 26 19:57:06 zabbix1 patroni[4005]:     return patroni_main()
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/local/lib/python2.7/dist-packages/patroni/__in
mar 26 19:57:06 zabbix1 patroni[4005]:     patroni = Patroni()
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/local/lib/python2.7/dist-packages/patroni/__in
mar 26 19:57:06 zabbix1 patroni[4005]:     self.config = Config()
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/local/lib/python2.7/dist-packages/patroni/conf
mar 26 19:57:06 zabbix1 patroni[4005]:     self._local_configuration = self._load_config_file()
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/local/lib/python2.7/dist-packages/patroni/conf
mar 26 19:57:06 zabbix1 patroni[4005]:     config = yaml.safe_load(f)
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/__init__.py",
mar 26 19:57:06 zabbix1 patroni[4005]:     return load(stream, SafeLoader)
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/__init__.py",
mar 26 19:57:06 zabbix1 patroni[4005]:     return loader.get_single_data()
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/constructor.p
mar 26 19:57:06 zabbix1 patroni[4005]:     node = self.get_single_node()
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/composer.py",
mar 26 19:57:06 zabbix1 patroni[4005]:     document = self.compose_document()
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/composer.py",
mar 26 19:57:06 zabbix1 patroni[4005]:     node = self.compose_node(None, None)
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/composer.py",
mar 26 19:57:06 zabbix1 patroni[4005]:     node = self.compose_mapping_node(anchor)
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/composer.py",
mar 26 19:57:06 zabbix1 patroni[4005]:     item_value = self.compose_node(node, item_key)
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/composer.py",
mar 26 19:57:06 zabbix1 patroni[4005]:     node = self.compose_mapping_node(anchor)
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/composer.py",
mar 26 19:57:06 zabbix1 patroni[4005]:     item_value = self.compose_node(node, item_key)
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/composer.py",
mar 26 19:57:06 zabbix1 patroni[4005]:     node = self.compose_mapping_node(anchor)
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/composer.py",
mar 26 19:57:06 zabbix1 patroni[4005]:     while not self.check_event(MappingEndEvent):
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/parser.py", l
mar 26 19:57:06 zabbix1 patroni[4005]:     self.current_event = self.state()
mar 26 19:57:06 zabbix1 patroni[4005]:   File "/usr/lib/python2.7/dist-packages/yaml/parser.py", l
mar 26 19:57:06 zabbix1 patroni[4005]:     "expected <block end>, but found %r" % token.id, token.
mar 26 19:57:06 zabbix1 patroni[4005]: yaml.parser.ParserError: while parsing a block mapping
mar 26 19:57:06 zabbix1 patroni[4005]:   in "/etc/patroni/cskmswia.yml", line 13, column 9
mar 26 19:57:06 zabbix1 patroni[4005]: expected <block end>, but found '<block mapping start>'
mar 26 19:57:06 zabbix1 patroni[4005]:   in "/etc/patroni/cskmswia.yml", line 29, column 11
mar 26 19:57:06 zabbix1 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FA
mar 26 19:57:06 zabbix1 systemd[1]: patroni.service: Unit entered failed state.
mar 26 19:57:06 zabbix1 systemd[1]: patroni.service: Failed with result 'exit-code'.
```
when i commented lines num. 28-30 patroni starts correctly. Can somebody help me with my config?
