### ISSUE TITLE
Load balancing sql read , write request

### ISSUE THREAD

**Issue by msfeghouli** [zalando/patroni#685]
Hi , i am seeting up spilo with kubernetes and i would like to know how can we load balance read , write request on the cluster .
i managed to route to the master pod , but still don't know how to route read only request to all standby pod 
please help

**Comment by alexeyklyukin** [comment]
Hi @msfeghouli.

You can define a service that uses `role_label` selectors inside in order to route your requests to replicas. For example:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    application: spilo
    role: replica
    version: patronidemo
  name: patronidemo-repl
  namespace: default
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    role: replica
    cluster-name: patronidemo
  type: ClusterIP

```

Given that in Patroni the `role_label` is configured to `role` (default) and the cluster label to `cluster-name` (also default) it will make a new service called `patronidemo-repl` that will route your request to only pods with of cluster `patronidemo` with a role `replica`.

Also take a look a the https://github.com/zalando-incubator/postgres-operator project, that does a lot of work for you, allowing you to run your PostgreSQL clusters by providing a simple manifest like [this](https://github.com/zalando-incubator/postgres-operator/blob/master/manifests/minimal-postgres-manifest.yaml)
