### ISSUE TITLE
[Question] ERROR - replication slot "postgresql1" does not exist even though it is present in master

### ISSUE THREAD

**Issue by debraj-manna** [zalando/patroni#702]
I am trying to create a three node patroni cluster. 
I started node1 first and then after some time whenever I am trying to start node2 and node3 I am seeing the below error in logs in node2 and node3.

```
2018-06-10 16:43:17.807 UTC [6090] FATAL:  could not start WAL streaming: ERROR:  replication slot "postgresql1" does not exist
cp: cannot stat ‘/var/lib/postgresql/wal_archive/0000000E.history’: No such file or directory
cp: cannot stat ‘/var/lib/postgresql/wal_archive/0000000D000000000000008F’: No such file or directory
2018-06-10 16:43:22.813 UTC [6120] ERROR:  replication slot "postgresql1" does not exist
2018-06-10 16:43:22.813 UTC [6119] FATAL:  could not start WAL streaming: ERROR:  replication slot "postgresql1" does not exist
cp: cannot stat ‘/var/lib/postgresql/wal_archive/0000000E.history’: No such file or directory
2018-06-10 16:43:23,661 INFO: Lock owner: postgresql0; I am postgresql1
2018-06-10 16:43:23,661 INFO: does not have lock
2018-06-10 16:43:23,663 INFO: no action.  i am a secondary and i am following a leader
cp: cannot stat ‘/var/lib/postgresql/wal_archive/0000000D000000000000008F’: No such file or directory
2018-06-10 16:43:27.816 UTC [6144] ERROR:  replication slot "postgresql1" does not exist
2018-06-10 16:43:27.816 UTC [6143] FATAL:  could not start WAL streaming: ERROR:  replication slot "postgresql1" does not exist
cp: cannot stat ‘/var/lib/postgresql/wal_archive/0000000E.history’: No such file or directory
^Csupport@platform2:/var/log/postgresql/patroni$ cd /var/lib/postgrql/wal_archive/
-bash: cd: /var/lib/postgresql/wal_archive/: No such file or directory
```
But I can see the replication slots in the `master`
```
vnera=# select * from pg_replication_slots;
-[ RECORD 1 ]-------+------------
slot_name           | postgresql2
plugin              |
slot_type           | physical
datoid              |
database            |
temporary           | f
active              | f
active_pid          |
xmin                |
catalog_xmin        |
restart_lsn         |
confirmed_flush_lsn |
-[ RECORD 2 ]-------+------------
slot_name           | postgresql1
plugin              |
slot_type           | physical
datoid              |
database            |
temporary           | f
active              | f
active_pid          |
xmin                |
catalog_xmin        |
restart_lsn         |
confirmed_flush_lsn |
```
No error in `node1`

```
2018-06-10 17:17:58,517 INFO: Lock owner: postgresql0; I am postgresql0
2018-06-10 17:17:58,525 INFO: no action.  i am the leader with the lock
2018-06-10 17:18:08,517 INFO: Lock owner: postgresql0; I am postgresql0
2018-06-10 17:18:08,524 INFO: no action.  i am the leader with the lock
2018-06-10 17:18:18,518 INFO: Lock owner: postgresql0; I am postgresql0
```

Output of `patronictl`

```
ubuntu@platform1:/var/log/postgresql$ patronictl -c /etc/patroni/patroni.yml list
+---------+-------------+---------------------+--------+---------+-----------+
| Cluster |    Member   |         Host        |  Role  |  State  | Lag in MB |
+---------+-------------+---------------------+--------+---------+-----------+
|  arkin  | postgresql0 | localhost,platform1 | Leader | running |           |
|  arkin  | postgresql1 | localhost,platform2 |        | running |           |
|  arkin  | postgresql2 | localhost,platform3 |        | running |           |
+---------+-------------+---------------------+--------+---------+-----------+
```

**Environment**

- Patroni - 1.4.4
- Postgres - 10.4
- OS - Ubuntu 14.04

Below are the `patroni.yml` of the three nodes. Can someone let me know what is going wrong?

**NODE 1**
```
ttl: &ttl 30
loop_wait: &loop_wait 10
scope: &scope arkin
#namespace: /service/
name: postgresql0

restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008
zookeeper:
  scope: *scope
  session_timeout: *ttl
  reconnect_timeout: *loop_wait
  hosts:
    - localhost:2181

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "off"
        wal_level: hot_standby
        max_wal_senders: 10
        wal_keep_segments: 100
        archive_timeout: 1800s
        max_replication_slots: 10
        hot_standby: "on"
        wal_log_hints: "on"
        unix_socket_directories: '/tmp'
        max_connections: 400
        shared_buffers: 256MB
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_vacuum_scale_factor: 0.10
        log_autovacuum_min_duration: 0
        autovacuum_naptime: 15s
        autovacuum_max_workers: 6

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host postgres all 0.0.0.0/0 trust
  - host all all 0.0.0.0/0 md5
  - host replication all 0.0.0.0/0 trust

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: localhost,platform1:5432
  bin_dir: /usr/lib/postgresql/10/bin
  data_dir: /var/lib/postgresql/10/data/postgresql0
  maximum_lag_on_failover: 104857600 # 1 megabyte i
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
      network:  0.0.0.0/0
    superuser:
      username: postgres
      password: C0113ct0r
  parameters:
    unix_socket_directories: '.'
  create_replica_method:
   - basebackup  
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
```
 **NODE 2**
```
ttl: &ttl 30
loop_wait: &loop_wait 10
scope: &scope arkin
#namespace: /service/
name: postgresql1

restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008
zookeeper:
  scope: *scope
  session_timeout: *ttl
  reconnect_timeout: *loop_wait
  hosts:
    - localhost:2181

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "off"
        wal_level: hot_standby
        max_wal_senders: 10
        wal_keep_segments: 100
        archive_timeout: 1800s
        max_replication_slots: 10
        hot_standby: "on"
        wal_log_hints: "on"
        unix_socket_directories: '/tmp'
        max_connections: 400
        shared_buffers: 256MB
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_vacuum_scale_factor: 0.10
        log_autovacuum_min_duration: 0
        autovacuum_naptime: 15s
        autovacuum_max_workers: 6

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host postgres all 0.0.0.0/0 trust
  - host all all 0.0.0.0/0 md5
  - host replication all 0.0.0.0/0 trust
#  - hostssl all all 0.0.0.0/0 md5

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: localhost,platform2:5432
  bin_dir: /usr/lib/postgresql/10/bin
  data_dir: /var/lib/postgresql/10/data/postgresql0
  maximum_lag_on_failover: 104857600 # 1 megabyte i
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
      network:  0.0.0.0/0
    superuser:
      username: postgres
      password: C0113ct0r
  parameters:
    unix_socket_directories: '.'
  create_replica_method:
   - basebackup  
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
```
 **NODE 3**
```
ttl: &ttl 30
loop_wait: &loop_wait 10
scope: &scope arkin
#namespace: /service/
name: postgresql2

restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008
zookeeper:
  scope: *scope
  session_timeout: *ttl
  reconnect_timeout: *loop_wait
  hosts:
    - localhost:2181

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "off"
        wal_level: hot_standby
        max_wal_senders: 10
        wal_keep_segments: 100
        archive_timeout: 1800s
        max_replication_slots: 10
        hot_standby: "on"
        wal_log_hints: "on"
        unix_socket_directories: '/tmp'
        max_connections: 400
        shared_buffers: 256MB
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_vacuum_scale_factor: 0.10
        log_autovacuum_min_duration: 0
        autovacuum_naptime: 15s
        autovacuum_max_workers: 6

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host postgres all 0.0.0.0/0 trust
  - host all all 0.0.0.0/0 md5
  - host replication all 0.0.0.0/0 trust

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: localhost,platform3:5432
  bin_dir: /usr/lib/postgresql/10/bin
  data_dir: /var/lib/postgresql/10/data/postgresql0
  maximum_lag_on_failover: 104857600 # 1 megabyte i
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
      network:  0.0.0.0/0
    superuser:
      username: postgres
      password: C0113ct0r
  parameters:
    unix_socket_directories: '.'
  create_replica_method:
   - basebackup  
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
```
