### ISSUE TITLE
[Question]How to handle a slave which has been disconnected from master for long time?

### ISSUE THREAD

**Issue by debraj-manna** [zalando/patroni#704]
Let's say if I am using asynchronous streaming application with the below configuration in a 3 node cluster.

```
bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "off"
        wal_level: hot_standby
        max_wal_senders: 10
        wal_keep_segments: 100
        max_replication_slots: 10
        hot_standby: "on"
        wal_log_hints: "on"
        unix_socket_directories: '/tmp'
        max_connections: 400
        shared_buffers: 250MB
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_vacuum_scale_factor: 0.10
        log_autovacuum_min_duration: 0
        autovacuum_naptime: 15s
        autovacuum_max_workers: 6
```

Let's say one of the slave node suddenly lose its connection to `master` for long time. 

1. In this case I think the size of XLOG on master will keep on building as the the XLOG are not being consumed by the disconnected slave's replication slot. So is there any setting in patorni configuration which will remove the slave and remove its replication slot if it is disconnected from master for x time duration? 
2. What is the recommended way to handle this case?

**Comment by alago197** [comment]
I think that if the slave disconnects, or is not available from the rest of the cluster, after its member key in the DCS expires, the master actually removes its replication slot, and the entries in DCS too are cleaned up.  Attached a test (Patroni 1.4.3 version).  

[slave_disconnect.txt](https://github.com/zalando/patroni/files/2089754/slave_disconnect.txt)

**Comment by debraj-manna** [comment]
Thanks @alago197 for replying. 
Is there any field in `patroni.yml` which controls the member key expiration in DCS ? I mean how can I set the expiry time for the member key in DCS.

**Comment by CyberDem0n** [comment]
> Is there any field in patroni.yml which controls the member key expiration in DCS ?

No, member keys have the same ttl as the leader key.

TTL for the leader key is not controlled by Patroni configuration file either.

Moreover, in your original message you are referring to the `bootstrap.dcs` section, which contains a global configuration and applied only when you deploy a new cluster. If you will try to change it in the file for existing cluster, these changes will have no effect.

If you really want to change these parameters and understand what you are doing, you have to do it with: `patronictl -c patroni.yml edit-config cluster-name`

**Comment by alago197** [comment]
Hi @debraj-manna ,

I don't know of a key that could control individual member expiration, but it's the TTL the main parameter (applying to all members) which determines the liveness and expiration time of the member, I think.  Its very nicely explained in the docs and in a presentation/slides the main developers wrote on https://speakerdeck.com/alexeyklyukin/managing-postgresql-clusters-with-patroni?slide=11

**Comment by debraj-manna** [comment]
Thanks @CyberDem0n and @alago197 . It is clear now.

I have a follow up question. If the disconnected node comes back up after long time and let's say by then the XLOG might have got removed from the master. In this case how does the disconnected slave joins back the cluster and does the catch up ? Will `create_replica_method` method be called ?

**Comment by CyberDem0n** [comment]
Ideally, wal segments should be archived to some external storage system, in this case, replica will be able to replay wal segments missing on the primary from the archive.

Patroni itself has no idea why replica is lagging behind and doesn't try to solve such problems by reinitializing replicas (we don't want to destroy the last copy of your precious data). The only Patroni can do - make sure that delayed replica will not be selected as new primary during automatic failover.

**Comment by debraj-manna** [comment]
@CyberDem0n So I should keep both streaming and archiving mode enabled like below. If it is not able to replay wal segments from primary then it will fall back to the archive to get the missing file.  

```
bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "on"
        wal_level: hot_standby
        max_wal_senders: 10
        wal_keep_segments: 100
        max_replication_slots: 10
        hot_standby: "on"
        wal_log_hints: "on"
        unix_socket_directories: '/tmp'
        max_connections: 400
        shared_buffers: 250MB
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_vacuum_scale_factor: 0.10
        log_autovacuum_min_duration: 0
        autovacuum_naptime: 15s
        autovacuum_max_workers: 6
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
       recovery_conf:
         restore_command: cp ../wal_archive/%f %p
         archive_cleanup_command: pg_archivecleanup -d ../wal_archive %r
```

1. Is my understanding correct ? 
2. Does patroni provide any option to delete old wal log files from archive in master?
