### ISSUE TITLE
Patronictl is throwing Exception and patroni is failing to start

### ISSUE THREAD

**Issue by debraj-manna** [zalando/patroni#717]
My patroni cluster with Patroni 1.4.4 on Ubuntu 14.4 is failing to start and patronictl is throwing exception like below -

Anyone has faced this ?
```
upport@vrni-platform:~$ patronictl -c /etc/patroni/patroni.yml list
+---------+-------------+-----------+------+--------------+-----------+
| Cluster |    Member   |    Host   | Role |    State     | Lag in MB |
+---------+-------------+-----------+------+--------------+-----------+
|  arkin  | postgresql0 | localhost |      | start failed |   unknown |
+---------+-------------+-----------+------+--------------+-----------+
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/local/lib/python2.7/dist-packages/kazoo/protocol/connection.py", line 480, in zk_loop
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'CLOSED'
```

Patroni version

```
support@vrni-platform:~$ pip show patroni
---
Metadata-Version: 1.1
Name: patroni
Version: 1.4.4
Summary: PostgreSQL High-Available orchestrator and CLI
Home-page: https://github.com/zalando/patroni
Author: Alexander Kukushkin, Oleksii Kliukin, Feike Steenbergen
Author-email: alexander.kukushkin@zalando.de, oleksii.kliukin@zalando.de, feike.steenbergen@zalando.de
License: The MIT License
Location: /usr/local/lib/python2.7/dist-packages
Requires: urllib3, psycopg2, PyYAML, requests, six, click, prettytable, tzlocal, python-dateutil, psutil, cdiff
Entry-points:
  [console_scripts]
  patroni = patroni:main
  patroni_aws = patroni.scripts.aws:main
  patroni_wale_restore = patroni.scripts.wale_restore:main
  patronictl = patroni.ctl:ctl
```

kazoo version

```
support@vrni-platform:~$ pip show kazoo
---
Metadata-Version: 2.1
Name: kazoo
Version: 2.5.0
Summary: Higher Level Zookeeper Client
Home-page: https://kazoo.readthedocs.io
Author: Kazoo team
Author-email: python-zk@googlegroups.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: six
```

Patroni.yml

```
ttl: &ttl 30
loop_wait: &loop_wait 10
scope: &scope arkin
#namespace: /service/
name: postgresql0

restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008
zookeeper:
  scope: *scope
  session_timeout: *ttl
  reconnect_timeout: *loop_wait
  hosts:
    - localhost:2181

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "off"
        wal_level: hot_standby
        max_wal_senders: 10
        wal_keep_segments: 100
        archive_timeout: 1800s
        max_replication_slots: 10
        hot_standby: "on"
        wal_log_hints: "on"
        unix_socket_directories: '/tmp'
        max_connections: 500
        shared_buffers: 256MB
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_vacuum_scale_factor: 0.10
        log_autovacuum_min_duration: 0
        autovacuum_naptime: 15s
        autovacuum_max_workers: 6
      recovery_conf:
        restore_command: cp /var/lib/postgresql/wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host postgres all 127.0.0.1/32 trust
  - host all all 0.0.0.0/0 md5
  - host replication all 0.0.0.0/0 trust
#  - hostssl all all 0.0.0.0/0 md5

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: localhost:5432
  data_dir: /var/lib/postgresql/data/postgresql0
  maximum_lag_on_failover: 104857600 # 1 megabyte i
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
      network:  0.0.0.0/0
    superuser:
      username: postgres
      password: C0113ct0r
  parameters:
    unix_socket_directories: '.'
  create_replica_method:
   - basebackup  
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
```
