### ISSUE TITLE
[Question] How to convert a async cluster to sync strict cluster?

### ISSUE THREAD

**Issue by debraj-manna** [zalando/patroni#718]
I want to convert an async cluster with below configurations  to a sync cluster with strict mode enabled.

```
ubuntu@platform1:~$ sudo patronictl -c /etc/patroni/patroni.yml show-config arkin
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_mode: 'off'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: 0.05
    autovacuum_max_workers: 6
    autovacuum_naptime: 15s
    autovacuum_vacuum_scale_factor: 0.1
    hot_standby: 'on'
    log_autovacuum_min_duration: 0
    max_connections: 400
    max_replication_slots: 10
    max_wal_senders: 10
    shared_buffers: 512MB
    unix_socket_directories: /tmp
    wal_keep_segments: 100
    wal_level: hot_standby
    wal_log_hints: 'on'
  recovery_conf:
    restore_command: cp /var/lib/postgresql/wal_archive/%f %p
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

On trying to do it via patronictl it is throwing me the below error - 

```
buntu@platform1:~$ sudo patronictl -c /etc/patroni/patroni.yml  edit-config  --pg 'synchronous_mode: true' --pg 'synchronous_mode_strict: true' arkin
Error: Invalid parameter setting postgresql.parameters.synchronous_mode: true
```
1. Can someone let me know what is the wrong in the above command?
2. Does patronictl also restarts the slave as part of this for configuration to take effect or I have to do it using `patronictl restart` on each cluster member ?
