### ISSUE TITLE
max_connections

### ISSUE THREAD

**Issue by zpavlig** [zalando/patroni#727]
Hello.
How change max_connections?

tried to change in three ways:
1- postgresql.yml
2- postgresql.base.conf
3- patronictl -c postgresql.yml edit-config

No result...

```
cat /var/lib/pgsql/9.6/data/postgresql.conf | grep max_conn
max_connections = '100'
```

```
postgres=# SHOW max_connections;
 max_connections
-----------------
 100
(1 row)
```

thx.

**Comment by alexeyklyukin** [comment]
Did you also do a restart of each cluster member afterwards? The third method is the only one that is correct, since max_connections can only be changed [globally per cluster](https://patroni.readthedocs.io/en/latest/dynamic_configuration.html). Changing max_connections requiring restart of the PostgreSQL instance, which can also be accomplished  with `patronictl restart` (it's better to restart the replicas first).

BTW, *reducing* the value of `max_connections` may lead to the replica being unable to start if it has a lag. This is solved with in https://github.com/zalando/patroni/commit/e939304001dbce26b895a0cc22b72722b14e5ecd

**Comment by zpavlig** [comment]
yes, restart patroni two ways:

1) patronictl -c postgresql.yml restart CLUSTER_NAME

Success: restart on member node-1
Success: restart on member node-2
Success: restart on member node-3

2) systemctl restart patroni for three nodes

no result

patronictl -c postgresql.yml edit-config:

```
loop_wait: 10
master_start_timeout: 30
maximum_lag_on_failover: 1048576
postgresql:
  max_connections: 800
  parameters: null
  use_pg_rewind: true
retry_timeout: 10
synchronous_mode: true
ttl: 30
```
