### ISSUE TITLE
Auto choice master in kubernetes

### ISSUE THREAD

**Issue by morgoved** [zalando/patroni#874]
my config 
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: &cluster_name patroni-gogit
  labels:
    application: patroni
    cluster-name: *cluster_name
spec:
  replicas: 3
  serviceName: *cluster_name
  template:
    metadata:
      labels:
        application: patroni
        cluster-name: *cluster_name
    spec:
      serviceAccountName: patroni-gogit
      containers:
      - name: *cluster_name
        image: mgm:5000/patroni10  # docker build -t patroni .
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /home/postgres/pgdata
          name: pgdata
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PATRONI_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PATRONI_KUBERNETES_LABELS
          value: '{application: patroni, cluster-name: patroni-gogit}'
        - name: PATRONI_SUPERUSER_USERNAME
          value: postgres
        - name: PATRONI_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: superuser-password
        - name: PATRONI_REPLICATION_USERNAME
          value: standby
        - name: PATRONI_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: replication-password
        - name: PATRONI_SCOPE
          value: *cluster_name
        - name: PATRONI_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PATRONI_POSTGRESQL_DATA_DIR
          value: /home/postgres/pgdata/pgroot/data
        - name: PATRONI_POSTGRESQL_PGPASS
          value: /tmp/pgpass
        - name: PATRONI_POSTGRESQL_LISTEN
          value: '0.0.0.0:5432'
        - name: PATRONI_RESTAPI_LISTEN
          value: '0.0.0.0:8008'
      terminationGracePeriodSeconds: 0
      nodeSelector:
        pg: pg
      volumes:
      - name: pgdata
#        emptyDir: {}
        hostPath:
          path: /u01/pg-patroni/
#  volumeClaimTemplates:
#  - metadata:
#      labels:
#        application: spilo
#        spilo-cluster: *cluster_name
#      annotations:
#        volume.alpha.kubernetes.io/storage-class: anything
#      name: pgdata
#    spec:
#      accessModes:
#      - ReadWriteOnce
#      resources:
#        requests:
#          storage: 5Gi

---
apiVersion: v1
kind: Endpoints
metadata:
  name: &cluster_name patroni-gogit
  labels:
    application: patroni
    cluster-name: *cluster_name
subsets: []

---
apiVersion: v1
kind: Service
metadata:
  name: &cluster_name patroni-gogit
  labels:
    application: patroni
    cluster-name: *cluster_name
spec:
#  type: ClusterIP
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 31234
  selector:
#    application: patroni
     cluster-name: *cluster_name
---
apiVersion: v1
kind: Secret
metadata:
  name: &cluster_name patroni-gogit
  labels:
    application: patroni
    cluster-name: *cluster_name
type: Opaque
data:
  superuser-password: emFsYW5kbw==
  replication-password: cmVwLXBhc3M=

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patroni-gogit

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patroni-gogit
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  # delete is required only for 'patronictl remove'
  - delete
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - patch
  - update
  # the following three privileges are necessary only when using endpoints
  - create
  - list
  - watch
  # delete is required only for for 'patronictl remove'
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patroni-gogit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: patroni-gogit
subjects:
- kind: ServiceAccount
  name: patroni-gogit
```
Periodically connecting from an external client I get

```
psql -h 192.168.192.31 -p 31234 -U postgres
Password for user postgres:
psql (10.6)
Type "help" for help.
postgres = # CREATE database test;
ERROR: can not execute read-only transaction
```
How to make the service map only to the master?
