### ISSUE TITLE
Bootstrap pg_hba for system app, postgresql pg_hba for user app

### ISSUE THREAD

**Issue by patsevanton** [zalando/patroni#878]
Hello!
I have idea. Please will think about it:

```yaml
bootstrap:
  pg_hba:
    - host replication replicator 192.168.88.91/32 md5
    - host replication replicator 192.168.88.90/32 md5
    - host replication replicator 192.168.88.89/32 md5

postgresql:
  pg_hba:
    - host test1 test2 192.168.1.1/32 md5
```
I run cluster with bootstrap pg_hba.
But later (may when i restart patroni service) pg_hba changed.
2 places where you can declare pg_hba confusing.

Can create feature bootstrap pg_hba for system app, postgresql pg_hba for user app?
Final pg_hba merge bootstrap pg_hba and postgresql pg_hba.

![](https://habrastorage.org/webt/sr/ny/_4/srny_4ytxzeyamido2heglxkwa0.png)

![](https://habrastorage.org/webt/ul/gw/p8/ulgwp89g35yp2ci4mtdsz6-qc_g.png)
