### ISSUE TITLE
Help with restore configuration

### ISSUE THREAD

**Issue by supabibz** [zalando/patroni#888]
Dear all,

I'm no PostgreSQL DBA and I need a bit of help to configure my Patroni cluster for restoring.

My problem : when a server hosting DB1 reboots, Patroni does the failover perfectly to DB2. However, when the DB1 restarts after the reboot, postgres cannot restore the data from DB2 (the new leader) :

```
+---------+------------------------+---------------+--------+---------+-----------+
| Cluster |         Member         |      Host     |  Role  |  State  | Lag in MB |
+---------+------------------------+---------------+--------+---------+-----------+
|  pg_VAL | pg_VAL_1               | 10.125.XXX.XXX|        | running |     15260 |
|  pg_VAL | pg_VAL_2               | 10.125.XXX.XXX| Leader | running |         0 |
+---------+------------------------+---------------+--------+---------+-----------+

```

PostgreSQL logs show this :

> FATAL: could not start WAL streaming: ERROR: requested starting point A5/A9000000 on timeline 3 is not in this server's history

Using the patronictl reinit command fixes the issue but this is just a workaround :

`patronictl -c /etc/patroni.yml reinit pg_VAL
`

After some minutes, no more lag and replication works fine.

Could you tell me how to simply configure the restore and what would be the impact on the infra?

My patroni.yml :

```
scope: pg_VAL
namespace: /db/
name: pg_VAL_1

restapi:
    listen: 10.125.XXX.XXX:8008
    connect_address: 10.125.XXX.XXX:8008

etcd:
    host: 10.125.XXX.XXX:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.125.XXX.XXX/0 md5
    - host replication replicator 10.125.XXX.XXX/0 md5
    - host all postgres 10.125.XXX.XXX/0 trust
    - host zabbix zabbix 10.125.XXX.XXX/0 trust
    - host all postgres 10.125.XXX.XXX/0 trust
    - host zabbix zabbix 10.125.XXX.XXX/0 trust
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: xxxxxxx
            options:
                - createrole
                - createdb

postgresql:
    listen: 10.125.XXX.XXX:5432
    connect_address: 10.125.XXX.XXX:5432
    data_dir: /patroni/pgsql
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: XXX
        superuser:
            username: postgres
            password: XXX
    parameters:
        unix_socket_directories: '.'
        shared_buffers: 16GB
        effective_cache_size: 48GB
        maintenance_work_mem: 2GB
        checkpoint_completion_target: 0.7
        wal_buffers: 16MB
        default_statistics_target: 100
        random_page_cost: 1.1
        effective_io_concurrency: 300
        work_mem: 41943kB
        min_wal_size: 1GB
        max_wal_size: 2GB
        max_parallel_workers_per_gather: 2
        max_connections: 200
        max_worker_processes: 4



tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```
