### ISSUE TITLE
[1.5.4] Unable to bootstrap the cluster, while call initdb

### ISSUE THREAD

**Issue by tuxmaster5000** [zalando/patroni#940]
When trying to bootstrap the cluster, patroni will crash on start with an python exception, because it will "feed" initdb with "---"

> 2019-01-21T15:30:45+0100 foo systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
> 2019-01-21T15:30:46+0100 foo patroni[112103]: 2019-01-21 15:30:46,248 INFO: Lock owner: None; I am foo.foo.foo
> 2019-01-21T15:30:46+0100 foo patroni[112103]: 2019-01-21 15:30:46,260 INFO: trying to bootstrap a new cluster
> 2019-01-21T15:30:46+0100 foo patroni[112103]: 2019-01-21 15:30:46,263 INFO: Lock owner: None; I am foo.foo.foo
> 2019-01-21T15:30:46+0100 foo patroni[112103]: 2019-01-21 15:30:46,263 INFO: not healthy enough for leader race
> 2019-01-21T15:30:46+0100 foo patroni[112103]: 2019-01-21 15:30:46,264 INFO: bootstrap in progress
> 2019-01-21T15:30:46+0100 foo patroni[112103]: /usr/pgsql-11/bin/initdb: unrecognized option '---'
> 2019-01-21T15:30:46+0100 foo patroni[112103]: Try "initdb --help" for more information.
> 2019-01-21T15:30:46+0100 foo patroni[112103]: pg_ctl: database system initialization failed
> 2019-01-21T15:30:46+0100 foo patroni[112103]: 2019-01-21 15:30:46,293 INFO: removing initialize key after failed attempt to bootstrap the cluster
> 2019-01-21T15:30:46+0100 foo patroni[112103]: 2019-01-21 15:30:46,741 INFO: Lock owner: None; I am foo.foo.foo
> 2019-01-21T15:30:46+0100 foo python3[112103]: detected unhandled Python exception in '/usr/bin/patroni'
> 2019-01-21T15:30:46+0100 foo python3[112103]: error sending data to ABRT daemon:
> 2019-01-21T15:30:46+0100 foo patroni[112103]: Traceback (most recent call last):
> 2019-01-21T15:30:46+0100 foo patroni[112103]: File "/usr/bin/patroni", line 11, in <module>
> 2019-01-21T15:30:46+0100 foo patroni[112103]: load_entry_point('patroni==1.5.4', 'console_scripts', 'patroni')()
> 2019-01-21T15:30:46+0100 foo patroni[112103]: File "/usr/lib/python3.4/site-packages/patroni/__init__.py", line 182, in main
> 2019-01-21T15:30:46+0100 foo patroni[112103]: return patroni_main()
> 2019-01-21T15:30:46+0100 foo patroni[112103]: File "/usr/lib/python3.4/site-packages/patroni/__init__.py", line 148, in patroni_main
> 2019-01-21T15:30:46+0100 foo patroni[112103]: patroni.run()
> 2019-01-21T15:30:46+0100 foo patroni[112103]: File "/usr/lib/python3.4/site-packages/patroni/__init__.py", line 119, in run
> 2019-01-21T15:30:46+0100 foo patroni[112103]: logger.info(self.ha.run_cycle())
> 2019-01-21T15:30:46+0100 foo patroni[112103]: File "/usr/lib/python3.4/site-packages/patroni/ha.py", line 1294, in run_cycle
> 2019-01-21T15:30:46+0100 foo patroni[112103]: info = self._run_cycle()
> 2019-01-21T15:30:46+0100 foo patroni[112103]: File "/usr/lib/python3.4/site-packages/patroni/ha.py", line 1202, in _run_cycle
> 2019-01-21T15:30:46+0100 foo patroni[112103]: return self.post_bootstrap()
> 2019-01-21T15:30:46+0100 foo patroni[112103]: File "/usr/lib/python3.4/site-packages/patroni/ha.py", line 1098, in post_bootstrap
> 2019-01-21T15:30:46+0100 foo patroni[112103]: self.cancel_initialization()
> 2019-01-21T15:30:46+0100 foo patroni[112103]: File "/usr/lib/python3.4/site-packages/patroni/ha.py", line 1093, in cancel_initialization
> 2019-01-21T15:30:46+0100 foo patroni[112103]: raise PatroniException('Failed to bootstrap cluster')
> 2019-01-21T15:30:46+0100 foo patroni[112103]: patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
> 2019-01-21T15:30:46+0100 foo systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
> 2019-01-21T15:30:46+0100 foo systemd[1]: Unit patroni.service entered failed state.
> 2019-01-21T15:30:46+0100 foo systemd[1]: patroni.service failed.

**Comment by tuxmaster5000** [comment]
This was my first idea.
But the file looks valid.
yamllint will report no errors.
My second try was to remove the starting "---" of the config file, but the result is the same.

**Comment by tuxmaster5000** [comment]
Here my tried file:
```
---
scope: mycluster
name: foo.foo.foo
restapi:
  listen: XX.XX.XX.XX:8443
  certfile: "/etc/pki/tls/certs/XX.pem"
  keyfile: "/etc/pki/tls/private/XX.pem"
  connect_address: XX.XX.XX.XX:8443
consul:
  host: 127.0.0.1
  scheme: http
  port: 8500
  verify: true
bootstrap:
  dcs:
    postgresql:
      parameters:
        log_destination: syslog
        logging_collector: 'on'
        password_encryption: scram-sha-256
  initdb:
    "- locale": UTF8
    "- encoding": UTF8
    "- data-checksums": ''
  pg_hba:
    "- host replication intern_replikation scram-sha-256": ''
  users:
    intern_replikation:
      passwort: XX
      options:
        "- replication":
postgresql:
  data_dir: "/var/lib/pgsql/11/data"
  listen: 127.0.0.1,::1,XX.XX.XX.XX:5432
  use_unix_socket: true
  connect_address: XX.XX.XX.XX:5432
  authentication:
    replication:
      username: intern_replikation
      password: XX
  parameters:
    unix_socket_directories: "/var/run/postgresql"
  bin_dir: "/usr/pgsql-11/bin"

```

**Comment by CyberDem0n** [comment]
Having syntatically correct yaml doesn't give you a guaranty to have a correct config file.

Please compare:

```yaml
  initdb:
    "- locale": UTF8
    "- encoding": UTF8
    "- data-checksums": ''
  pg_hba:
    "- host replication intern_replikation scram-sha-256": ''
```

with https://github.com/zalando/patroni/blob/master/postgres0.yml#L53-L58
```yaml
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 127.0.0.1/32 md5
```
