### ISSUE TITLE
Example use of keep_existing_recovery_conf

### ISSUE THREAD

**Issue by EtienneM** [zalando/patroni#959]
Hi guys,

I am really struggling setting up pgBackRest with Patroni, especially the restoration part. Apparently, for this to work I need to make use of what was implemented for #637. But I really don't understand what should be added in the patroni.yml configuration file for this to work. Here is an excerpt of my current configuration file:

```yml
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true

  initdb:
    - encoding: UTF8
    - locale: en_US.utf8
    - data-checksums

  post_bootstrap: /postgresql_post_bootstrap

  pg_hba:
[...]
```

If I understand, I should remove the `initdb` bloc and replace it with something like:

```yml
  method: pgbackrest
  pgbackrest:
    command: XXX
    keep_existing_recovery_conf: True
```

What should be in the `XXX` placeholder? Do you have any idea?

I was wondering whether @bradnicholson who created the PR has an example to share

**Comment by bradnicholson** [comment]
Have you seen the Bootstrapping docs [here](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#bootstrap) and [here](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#building-replicas)?

In the bootstrap section, specify a custom bootstrap method, and set `keep_existing_recovery_conf` to True.

In the Building replicas section, there is an example of calling pgBackRest (that is the command).

**Comment by EtienneM** [comment]
Yes definitely I had a look to these pages and read them a lot. Sorry if I missed something obvious but I am asking for an example because I didn't find a working solution.

Isn't there a difference between building a replica and bootstrapping a new node? I tried modifying my Patroni bootstrap section with:

```yml
bootstrap:
  method: pgbackrest
  pgbackrest:
    command: /postgresql_bootstrap_cluster.sh
    keep_existing_recovery_conf: True
[...]
```

And the script is 
```bash
#!/usr/bin/env bash

while getopts ":-:" optchar; do
  [[ "${optchar}" == "-" ]] || continue
  case "${OPTARG}" in
    datadir=* )
        DATA_DIR=${OPTARG#*=}
        ;;
    scope=* )
        SCOPE=${OPTARG#*=}
        ;;
  esac
done

/usr/bin/pgbackrest --stanza=$SCOPE --delta restore
```

But when I create a new cluster, it fails with an error on the call to pgbackrest. So it's not just calling pgbackrest...

```
ERROR [125]: : $PGDATA directory /var/lib/postgresql/postgresql0 does not exist
```
