### ISSUE TITLE
my cluster is broken after upgrading helm chart

### ISSUE THREAD

**Issue by k1ng440** [zalando/patroni#960]
Hello,
my cluster is not being available to sync after upgraded the chart and spilo. 

ssh to pod and did patronictl list and no member found. 
+---------+--------+------+------+-------+-----------+
| Cluster | Member | Host | Role | State | Lag in MB |
+---------+--------+------+------+-------+-----------+
+---------+--------+------+------+-------+-----------+

i just need the master to asap

**Comment by k1ng440** [comment]
```
oinread-patroni-1 patroni 2019-01-31 00:29:51,208 INFO: Could not take out TTL lock
coinread-patroni-1 patroni 2019-01-31 00:29:51,343 INFO: following new leader after trying and failing to obtain lock
coinread-patroni-1 patroni 2019-01-31 00:30:01,112 INFO: Could not take out TTL lock
coinread-patroni-1 patroni 2019-01-31 00:30:01,148 INFO: following new leader after trying and failing to obtain lock
coinread-patroni-1 patroni 2019-01-31 00:30:11,110 INFO: Could not take out TTL lock
coinread-patroni-1 patroni 2019-01-31 00:30:11,138 INFO: following new leader after trying and failing to obtain lock
coinread-patroni-1 patroni 2019-01-31 00:30:21,111 INFO: Could not take out TTL lock
coinread-patroni-1 patroni 2019-01-31 00:30:21,138 INFO: following new leader after trying and failing to obtain lock
```

```
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_mode: 'on'
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.05
        checkpoint_completion_target: 0.9
        hot_standby: 'on'
        log_autovacuum_min_duration: 0
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_lock_waits: 'on'
        log_min_duration_statement: 500
        log_statement: ddl
        log_temp_files: 0
        max_connections: 1000
        max_replication_slots: 5
        max_wal_senders: 5
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        track_functions: all
        wal_keep_segments: 8
        wal_level: hot_standby
        wal_log_hints: 'on'
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums
  post_init: /scripts/post_init.sh "zalandos"
  users:
    admin:
      options:
      - createrole
      - createdb
      password: xx-xxx
kubernetes:
  labels:
    app: patroni
    release: my-patroni
  pod_ip: 10.8.9.23
  ports:
  - name: postgresql
    port: 5432
  role_label: spilo-role
  scope_label: app
  use_endpoints: true
postgresql:
  authentication:
    replication:
      password: xx
      username: standby
    superuser:
      password: xx-xxx
      username: postgres
  bin_dir: /usr/lib/postgresql/10/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos true
  connect_address: 10.8.9.23:5432
  data_dir: /home/postgres/pgdata/pgroot/data
  listen: 0.0.0.0:5432
  name: my-patroni-0
  parameters:
    archive_command: /bin/true
    bg_mon.listen_address: 0.0.0.0
    extwlist.custom_path: /scripts
    extwlist.extensions: btree_gin,btree_gist,citext,hstore,intarray,ltree,pgcrypto,pgq,pg_trgm,postgres_fdw,uuid-ossp,hypopg,pg_partman
    log_destination: csvlog
    log_directory: ../pg_log
    log_file_mode: '0644'
    log_filename: postgresql-%u.log
    log_rotation_age: 1d
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    shared_buffers: 13637MB
    shared_preload_libraries: bg_mon,pg_stat_statements,pg_cron,set_user,pgextwlist,timescaledb
    ssl: 'on'
    ssl_cert_file: /home/postgres/server.crt
    ssl_key_file: /home/postgres/server.key
  pg_hba:
  - local   all             all                                   trust
  - hostssl all             +zalandos    127.0.0.1/32       pam
  - host    all             all                127.0.0.1/32       md5
  - hostssl all             +zalandos    ::1/128            pam
  - host    all             all                ::1/128            md5
  - hostssl replication     standby all                md5
  - hostssl all             +zalandos    all                pam
  - host    all             all                all                md5
  use_unix_socket: true
restapi:
  connect_address: 10.8.9.23:8008
  listen: 0.0.0.0:8008
```
