### ISSUE TITLE
Incomplete pg_hba content when using a custom bootstrap method

### ISSUE THREAD

**Issue by EtienneM** [zalando/patroni#961]
Related to my quest of setting up pgBackRest along with Patroni (cf. #959), I have a weird behaviour.

First I have the following Patroni configuration file:

```yml
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true

  initdb:
    - encoding: UTF8
    - locale: en_US.utf8
    - data-checksums

  pg_hba:
    - hostssl   replication replicator 10.255.0.0/16 md5
    - hostnossl replication all        0.0.0.0/0     reject
    - local     postgres    postgresql               peer

    - host all all 0.0.0.0/0 md5


  post_bootstrap: /postgresql_post_bootstrap

[...]
```

My `post_bootstrap` script contains among other things the line `pgbackrest --stanza=$DB_USER --log-level-console=info stanza-create`. In this case, it works well!

But now, I modified my Patroni configuration file to remove the `initdb` bloc and replace it with:

```yml
  method: pgbackrest
  pgbackrest:
    command: /postgresql_bootstrap_replica --username=SUPERUSER_USERNAME --password=SUPERUSER_PASSWORD
    keep_existing_recovery_conf: True
```

That's the only modification. And the `pgbackrest --stanza=$DB_USER --log-level-console=info stanza-create` line fails with 

```
FATAL:  no pg_hba.conf entry for host "[local]", user "postgresql", database "postgres", SSL off
```

And indeed the file contains:

```
# Do not edit this file manually!
# It will be overwritten by Patroni!
local   replication     replicator              trust
local   all     admin_patroni           trust
host    replication     replicator      127.0.0.1/32    trust
host    all     admin_patroni   127.0.0.1/32    trust
host    replication     replicator      ::1/32  trust
host    all     admin_patroni   ::1/32  trust                                                                                                                                                
```

But I don't understand where does this `pg_hba` comes from. Why its content changed by just changing the bootstrap method? Do you think it might be an issue with Patroni? I had a look into the code but don't understand why the `pg_hba` content is different if the bootstrap method is initdb or my custom one.

FWIW here is my bootstrap script after parsing the argument on the command line:

```bash
if [[ ! -d $DATA_DIR ]]; then
  echo "Initialize a new replica"
  pgpassfile=$(mktemp)
  echo $SUPERUSER_PASSWORD > $pgpassfile
  /usr/lib/postgresql/10/bin/pg_ctl -D $DATA_DIR \
    -o "--encoding=UTF8 --locale=en_US.utf8 --data-checksums \
        --username=$SUPERUSER_USERNAME \
        --pwfile=$pgpassfile" \
        initdb
  rm $pgpassfile
else
  echo "Restore an existing replica"
  /usr/bin/pgbackrest --stanza=$SCOPE --delta restore
fi
```

I also checked the pg_hba content in the working case and it is the static pg_hba I have (before Patroni overwrites it):

```
hostssl   replication replicator 10.255.0.0/16 md5
hostnossl replication all        0.0.0.0/0     reject
local     postgres    postgresql               peer
host      all         all        0.0.0.0/0     md5
```

**Comment by EtienneM** [comment]
I also tried moving the `pg_hba` section to `postgresql` instead of `bootstrap` section but it does not change the issue

**Comment by CyberDem0n** [comment]
When doing a custom bootstrap Patroni temporary [generates](https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L1156-L1169) a different pg_hba.conf with trust access for superuser and replication connections from localhost and unix socket.
It is necessary because of the original pg_hba.conf from the backup or whatever is in the patroni.yaml might require password authentication, but the superuser password could differ from the `postgresql.authentication.superuser.password`. Without trust we can't change it.

Apparently your Patroni config contains superuser name which is different from the name used by pgbackrest. Just make them use the same superuser name.

```
postgresql:
  authentication:
    spueruser:
      username: admin_patroni
    replication:
      username: replicator
```

P.S. post_bootstrap script receives a connection as an argument: `postgres://user@host:port/database`
