### ISSUE TITLE
standby_cluster with wal log shipping

### ISSUE THREAD

**Issue by carolfly86** [zalando/patroni#969]
Hi, We would like to setup a standy_cluster with wal log fetching (no streaming replication) using wal-e.

I have below configs:
```
bootstrap:
  dcs:
    standby_cluster:
      create_replica_methods:
       - wal_e
      restore_command: /usr/bin/envdir /etc/wal-e.d/env /opt/wal-e/bin/wal-e wal-fetch "%f" "%p"
```

and in postgres section

```
postgresql:
  create_replica_methods:
    - wal_e
    - basebackup
  wal_e:
    command: patroni_wale_restore
    no_master: 1
    envdir: /etc/wal-e.d/env
    use_iam: 1
```

When I start patroni, it still created a recovery.conf file without the restore_command. Can you please let me know what am I missing?

**Comment by combrs** [comment]
Are you add additional section in 'postgres' to patroni config like this?
````
recovery_conf:
    restore_command: /usr/local/bin/restore_command.sh %f %p
````
As stated in doc:
recovery_conf: additional configuration settings written to recovery.conf when configuring follower.

**Comment by CyberDem0n** [comment]
Looks like you changed patroni config right after the standby cluster was initialized.
That doesn't work. `bootstrap` section works only once, during initialization, after that you have to make changes via `patronictl edit-config`.

Actually I've checked it locally, made a basebackup to the `data/backup` directory and put into the config:
```yaml
bootstrap:
  dcs:
    standby_cluster:
      restore_command: 'cp ../wal_archive/%f %p'
      create_replica_methods: ['copy']
postgresql:
  copy:
    command: features/backup_restore.sh --sourcedir=data/backup
```

Here is the recovery.conf that was generated:
```
restore_command = 'cp ../wal_archive/%f %p'
standby_mode = 'on'
recovery_target_timeline = 'latest'
```

From another side I've found a small problem in the Patroni and fixed it in the https://github.com/zalando/patroni/pull/971
