### ISSUE TITLE
wal_level not changes from 'replica' to 'hot_standby'

### ISSUE THREAD

**Issue by Valeriyy** [zalando/patroni#976]
Hello!
1. I'm changed my patroni.yml:
```
log:
  dir: /logs/patroni
  file_num: 10
  file_size: 104857600
  #level: DEBUG

consul:
  host: 127.0.0.1:8500

restapi:
  listen: 0.0.0.0:8008
  connect_address: 172.27.42.108:8008

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: false
      parameters:
        wal_level: hot_standby
        max_connections: 1000
        max_wal_senders: 15
        wal_keep_segments: 512

postgresql:
  data_dir: /mnt/disk1/pgsql/test
  listen: 0.0.0.0:5432
  connect_address: 172.27.42.108:5432
  bin_dir: /usr/pgsql-9.6/bin
  authentication:
    superuser:
      username: root
      password: mydevpass
    replication:
      username: repl
      password:

tags:
  nofailover: false
```
2. I'm executed edit-config:
```
# /home/patroni/bin/patronictl -c /etc/patroni.yml edit-config postgresql                                                                                                                                                                              
--- 
+++ 
@@ -2,6 +2,7 @@
 maximum_lag_on_failover: 1048576
 postgresql:
   parameters:
+    wal_level: "hot_standby"
     max_connections: 1000
     max_wal_senders: 15
     wal_keep_segments: 512

Apply these changes? [y/N]: y
Configuration changed
```
3. I'm restarted cluster:
```
# /home/patroni/bin/patronictl -c /etc/patroni.yml restart postgresql
+------------+---------------------------------------+---------------+--------+---------+-----------+
|  Cluster   |                 Member                |      Host     |  Role  |  State  | Lag in MB |
+------------+---------------------------------------+---------------+--------+---------+-----------+
| postgresql | temp-pg1.server.ru | 172.27.42.101 |        | running |         0 |
| postgresql | temp-pg2.server.ru | 172.27.42.108 | Leader | running |         0 |
+------------+---------------------------------------+---------------+--------+---------+-----------+
Are you sure you want to restart members temp-pg1.server.ru, temp-pg2.server.ru ? [y/N]: y
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2)  []: 
When should the restart take place (e.g. 2015-10-01T14:30)  [now]: 
Success: restart on member temp-pg1.server.ru
Success: restart on member temp-pg2.server.ru
```

But 'wal_level' not changed in postgresql.conf to 'hot_standby' value:
```
# cat /var/lib/pgsql/test/postgresql.conf | grep wal_level
wal_level = 'replica'
```
Why is this happening and how do I change the value of wal_level?
