### ISSUE TITLE
standby_cluster bootstrap using custom script without host and port

### ISSUE THREAD

**Issue by carolfly86** [zalando/patroni#999]
patroni version: 1.5.5

hi, I'm trying to bootstrap a standby_cluster with wal log shipping using custom script.
I would like the standby_cluster to not connect to the master, so I omitted the host and port info in the config, but the bootstrap would not  start without those info. 

``` 
2019-03-06 18:11:45,020 INFO: trying to bootstrap a new standby leader
 2019-03-06 18:11:45,021 ERROR: failed to bootstrap clone from remote master None
```

```
bootstrap:
  dcs:
    standby_cluster:
      create_replica_methods: ['wal_e']
      restore_command: "/usr/bin/envdir /etc/wal-e.d/env /opt/wal-e/bin/wal-e wal-fetch %f %p"
```

postgresql section contains the wal_e replica method:

```
postgresql:
  wal_e:
    command: "/var/opt/gitlab/patroni/scripts/wale-restore.sh"
```
